intellij-rust/intellij-rust

- test/org/rust/lang/RustAnnotatorTest.kt
- testData/annotator/attributes.rs
> (T): test for attributes Annotator

- src/org/rust/lang/core/lexer/RustTokenType.kt
- src/org/toml/lang/TomlFileType.kt
- src/org/toml/lang/TomlHighlighter.kt
- src/org/toml/lang/core/grammar/toml.bnf
- src/org/toml/lang/core/lexer/TomlLexer.flex
- src/org/toml/lang/core/parser/TomlParserDefinition.kt
Spec: https://github.com/toml-lang/toml/blob/master/README.md
> Update toml lexer/parser to match the spec

- src/org/rust/lang/core/grammar/rust.bnf
- src/org/rust/lang/core/psi/RustDeclarationSet.kt
- src/org/rust/lang/core/psi/impl/RustFileImpl.kt
- src/org/rust/lang/core/psi/impl/mixin/RustBlockImplMixin.kt
- src/org/rust/lang/core/psi/impl/mixin/RustFnItemImplMixin.kt
- src/org/rust/lang/core/psi/impl/mixin/RustPathPartImplMixin.kt
- src/org/rust/lang/core/resolve/RustResolveEngine.kt
- src/org/rust/lang/core/resolve/ref/RustAbstractQualifiedReference.kt
- src/org/rust/lang/core/resolve/scope/RustResolveScope.kt
- src/org/rust/lang/core/resolve/scope/RustResolveScopeBase.kt
- test/org/rust/lang/RustAnnotatorTest.kt
- test/org/rust/lang/RustStructureViewTest.kt
- test/org/rust/lang/RustTestCase.kt
- test/org/rust/lang/core/RustResolveTestCase.kt
- testData/resolve/argument.rs
- testData/resolve/locals.rs
- testData/resolve/ordering.rs
- testData/resolve/shadowing.rs
- testData/resolve/unbound.rs
We can resolve function arguments now!
> Start resolve

- src/org/rust/lang/core/psi/impl/mixin/RustBlockImplMixin.kt
- src/org/rust/lang/core/psi/impl/mixin/RustFnItemImplMixin.kt
- src/org/rust/lang/core/psi/util/RustPsiUtil.kt
- test/org/rust/lang/core/RustResolveTestCase.kt
- testData/resolve/nested.rs
> (RES): support complex patterns

- src/org/rust/lang/core/grammar/rust.bnf
- src/org/rust/lang/core/psi/RustCompositeElement.kt
- src/org/rust/lang/structure/RustStructureViewElement.kt
- src/org/rust/lang/structure/RustStructureViewTreeElement.kt
@alexeykudinkin please confirm that this is a better approach to working with PSI.
> (NAV): refactor file structure

- src/org/rust/lang/core/grammar/rust.bnf
- src/org/rust/lang/core/psi/impl/mixin/RustLambdaExprImplMixin.kt
- src/org/rust/lang/core/resolve/RustResolveEngine.kt
- test/org/rust/lang/core/RustResolveTestCase.kt
- testData/resolve/closure.rs
> Implement resolve in closure parameters, too

- resources/META-INF/plugin.xml
- src/org/toml/lang/TomlCommenter.kt
> Implement TomlCommenter class

- resources/META-INF/plugin.xml
- src/org/toml/lang/TomlBraceMatcher.kt
> Implement TomlBraceMatcher class

- README.md
- doc/Emacs.md
- doc/Usage.md
- doc/Vim.md
@alexeykudinkin @atsky I've tried to write some Rust code (my homework :) ) in intellij rust yesterday, and it is possible :)
So I started some documentation for the users of the plugin.
Guys, what do you think? Isn't it too early?
> (DOC): basic usage docs

- build.gradle
- test/org/rust/lang/RustStructureViewTest.kt
- test/org/rust/lang/core/RustResolveTestCase.kt
- test/org/rust/lang/core/parser/RustCTRSTestCase.kt
- moved jUnit dependency to correct dependency block in Gradle file
- use [AssertJ](http://joel-costigliola.github.io/assertj/index.html) for simpler and more fluent assertions
> Small test improvements

- build.gradle
> Gradle build script cleanup

- test/org/rust/lang/annotator/RustAnnotatorTest.kt
- test/org/rust/lang/formatter/RustFormatterTestCase.kt
- test/org/rust/lang/structure/RustStructureViewTest.kt
- testData/structure/enums.rs
- testData/structure/enums.txt
- testData/structure/functions.rs
- testData/structure/functions.txt
- testData/structure/impls.rs
- testData/structure/impls.txt
- testData/structure/structs.rs
- testData/structure/structs.txt
- testData/structure/traits.rs
- testData/structure/traits.txt
This PR adds more and improves the existing unit tests for the file structure view.
> Structure View Tests

- src/org/rust/lang/icons/RustIconProvider.kt
- src/org/rust/lang/icons/RustIcons.kt
see #47 
this PR is very likely to conflict with #57
> More structure view improvments

- resources/META-INF/plugin.xml
- resources/org/rust/colorscheme/RustDarcula.xml
- resources/org/rust/colorscheme/RustDefault.xml
- resources/org/rust/colorscheme/highlighterDemoText.rs
- src/org/rust/lang/colorscheme/RustColorSettingsPage.kt
- src/org/rust/lang/colorscheme/RustColors.kt
- src/org/rust/lang/highlight/RustHighlighter.kt
Add color settings page for Rust
Add specific color settings for lifetime
> Add color settings page for Rust

- .travis.yml
- build.gradle
- gradle.properties
> TravisCI: Disable source file download

- resources/META-INF/plugin.xml
- src/org/toml/lang/annotator/TomlAnnotator.kt
- test/org/toml/lang/TomlTestCase.kt
- test/org/toml/lang/Utils.kt
- test/org/toml/lang/annotator/TomlAnnotatorTest.kt
- testData/toml/annotator/inline_tables.toml
Add toml annotator
Create error annotation for multiline inline tables
> Add toml annotator

- src/org/rust/lang/core/psi/impl/mixin/RustModItemImplMixin.kt
- src/org/rust/lang/icons/RustIcons.kt
- src/org/rust/lang/structure/RustFileTreeElement.kt
- src/org/rust/lang/structure/RustModTreeElement.kt
- test/org/rust/lang/structure/RustStructureViewTest.kt
- testData/structure/mods.rs
- testData/structure/mods.txt
> Add "mod" items to the structure view

- gradle/wrapper/gradle-wrapper.properties
Use complete distribution of gradle to make Intellij IDEA happy and smart
> Use complete distribution of gradle

- src/org/rust/lang/spellchecker/RustSpellcheckingStrategy.kt
- src/org/rust/lang/spellchecker/StringLiteralTokenizer.kt
- test/org/rust/lang/spellchecker/RustSpellCheckerTest.kt
- testData/spellchecker/comments.rs
- testData/spellchecker/comments_suppressed.rs
- testData/spellchecker/string_literals.rs
- testData/spellchecker/string_literals_suppressed.rs
> Make spellcheck cancelable for string literals

- resources/META-INF/plugin.xml
- resources/org/rust/lang/codestyle/code_sample.rs
- src/org/rust/lang/codestyle/RustCodeStyleSettings.kt
- src/org/rust/lang/codestyle/RustCodeStyleSettingsProvider.kt
- src/org/rust/lang/codestyle/RustLanguageCodeStyleSettingsProvider.kt
This only implements the "Right Margin" option for now and sets it to 99
resolves #86
> Add Rust code style settings

- resources/org/rust/lang/colorscheme/RustDarcula.xml
- resources/org/rust/lang/colorscheme/RustDefault.xml
- src/org/rust/lang/annotator/RustAnnotator.kt
- src/org/rust/lang/colorscheme/RustColorSettingsPage.kt
- src/org/rust/lang/colorscheme/RustColors.kt
- test/org/rust/lang/annotator/RustAnnotatorTest.kt
- testData/annotator/macro.rs
Highlight macro invocation
Related to #88
> Highlight macro invocation

- resources/org/rust/lang/colorscheme/RustDarcula.xml
- resources/org/rust/lang/colorscheme/RustDefault.xml
- src/org/rust/lang/annotator/RustAnnotator.kt
- src/org/rust/lang/colorscheme/RustColorSettingsPage.kt
- src/org/rust/lang/colorscheme/RustColors.kt
- test/org/rust/lang/annotator/RustAnnotatorTest.kt
- testData/annotator/type_parameters.rs
> Highlight type parameters

- src/org/rust/lang/documentation/RustDocumentationProvider.kt
- test/org/rust/lang/documentation/RustDocumentationProviderTest.kt
- testData/org/rust/lang/documentation/testdata/nested_function.html
- testData/org/rust/lang/documentation/testdata/nested_function.rs
This PR adds support for `getQuickNavigateInfo()` on function calls
> Documentation Provider improvements

- src/org/rust/lang/typing/RustEnterInLineCommentHandler.kt
- test/org/rust/lang/typing/RustEnterHandlerTest.kt
- testData/org/rust/lang/typing/testdata/before_line_comment.rs
- testData/org/rust/lang/typing/testdata/before_line_comment_after.rs
- testData/org/rust/lang/typing/testdata/directly_after_token.rs
- testData/org/rust/lang/typing/testdata/directly_after_token_after.rs
- testData/org/rust/lang/typing/testdata/inside_token.rs
- testData/org/rust/lang/typing/testdata/inside_token_after.rs
> Fix EnterInLineCommentHandler

- src/org/rust/lang/RustSdkType.kt
Support multirust toolchains as rust sdk
> Support multirust toolchains as rust sdk

- src/org/rust/lang/RustSdkType.kt
> SdkType: Add support for Linux and Windows

- resources/org/rust/lang/colorscheme/RustDarcula.xml
- resources/org/rust/lang/colorscheme/RustDefault.xml
- src/org/rust/lang/annotator/RustAnnotator.kt
- src/org/rust/lang/colorscheme/RustColorSettingsPage.kt
- src/org/rust/lang/colorscheme/RustColors.kt
- test/org/rust/lang/annotator/RustAnnotatorTest.kt
- testData/org/rust/lang/annotator/fixtures/mut_binding.rs
Highlight mut binding
Related to #89
> Highlight mut binding

- resources/META-INF/plugin.xml
- resources/fileTemplates/internal/Rust File.rs.html
- src/org/rust/lang/actions/RustCreateFileAction.kt
Fixed branch with single file action
> Added RustCreateFileAction

- resources/org/rust/lang/colorscheme/RustDarcula.xml
- resources/org/rust/lang/colorscheme/RustDefault.xml
continues the discussion from #115
> ColorScheme: Adjust macro colors and remove italic styling

- resources/META-INF/plugin.xml
- src/org/rust/lang/inspections/ApproxConstantInspection.kt
- test/org/rust/lang/inspections/RustInspectionsTest.kt
- testData/org/rust/lang/inspections/fixtures/approx_constant.rs
inspired by https://github.com/Manishearth/rust-clippy/wiki#approx_constant
> Inspections: Add "Approximate Constants" inspection

- .gitignore
- resources/META-INF/plugin.xml
- resources/intentionDescriptions/ExpandModule/after.rs.template
- resources/intentionDescriptions/ExpandModule/before.rs.template
- resources/intentionDescriptions/ExpandModule/description.html
- src/org/rust/lang/intentions/ExpandModule.kt
- test/org/rust/lang/intentions/RustIntentionsTest.kt
- testData/org/rust/lang/intentions/fixtures/expand_module.rs
Implement expand module intention
> Implement expand module intention

- CONTRIBUTING.md
> "Contributing.md" improvements

- resources/META-INF/plugin.xml
- src/org/rust/lang/inspections/SelfConventionInspection.kt
- test/org/rust/lang/inspections/RustInspectionsTest.kt
- testData/org/rust/lang/inspections/fixtures/self_convention.rs
inspired by https://github.com/Manishearth/rust-clippy/wiki#wrong_self_convention
> Inspections: Add "Self Convention" inspection

- src/org/rust/lang/documentation/RustDocumentationProvider.kt
This PR does a bit of cleanup on the `DocumentationProvider` implementation.
> DocumentationProvider improvements

- resources/META-INF/plugin.xml
- src/org/rust/lang/RustDescriptionProvider.kt
- src/org/rust/lang/core/RustParserDefinition.kt
- src/org/rust/lang/core/lexer/RustTokenElementTypes.java
- src/org/rust/lang/search/RustFindUsagesProvider.kt
- src/org/rust/lang/search/RustWordScanner.kt
> Implement FindUsageProvider

- src/main/kotlin/org/rust/lang/core/psi/RustQualifiedReferenceElement.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustPathPartImplMixin.kt
- src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
- src/test/kotlin/org/rust/lang/core/resolve/RustResolveTestCase.kt
- src/test/kotlin/org/rust/lang/core/resolve/RustUseResolveTestCase.kt
- src/test/resources/org/rust/lang/core/resolve/fixtures/nested_super.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/self.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/super.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/use/relative_child.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/wrong_self.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/wrong_super.rs
@alexeykudinkin @atsky please review
> (RES): resolve of relative paths

- README.md
- gradle.properties
> Downgraded JDK requirements

- src/main/kotlin/org/rust/lang/core/completion/RustCompletionEngine.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustBlockImplMixin.kt
- src/main/kotlin/org/rust/lang/core/psi/util/RustPsiExtensions.kt
- src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RustQualifiedReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/scope/RustResolveScope.kt
- src/test/kotlin/org/rust/lang/core/completion/RustCompletionTest.kt
- src/test/resources/org/rust/lang/core/completion/fixtures/function_name.rs
- src/test/resources/org/rust/lang/core/completion/fixtures/function_name_after.rs
- src/test/resources/org/rust/lang/core/completion/fixtures/local_scope.rs
- src/test/resources/org/rust/lang/core/completion/fixtures/local_variable.rs
- src/test/resources/org/rust/lang/core/completion/fixtures/local_variable_after.rs
- src/test/resources/org/rust/lang/core/completion/fixtures/path.rs
- src/test/resources/org/rust/lang/core/completion/fixtures/path_after.rs
Ok, here is the second take on the completion :)
@alexeykudinkin @atsky please review.
I don't like that this don't respect scope of locals and thus gives false positives. However I don't see how this can be fixed without duplicating scope visitor and without introducing something like processors from #196 
But this is still much better then nothing :)
> (COMPLETION): initial

- src/main/kotlin/org/rust/cargo/project/CargoMetadata.kt
> (CARGO): update metadata format

- src/main/resources/org/rust/ide/liveTemplates/Rust.xml
Add surround templates as suggested in https://github.com/intellij-rust/intellij-rust/pull/178#issuecomment-175185077
> templates: Add loop, while, for live templates

- src/main/kotlin/org/rust/ide/intentions/ContractModule.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/ContractModule/after.rs.template
- src/main/resources/intentionDescriptions/ContractModule/before.rs.template
- src/main/resources/intentionDescriptions/ContractModule/description.html
- src/test/kotlin/org/rust/ide/intentions/RustIntentionsTest.kt
- src/test/resources/org/rust/ide/intentions/fixtures/contract_module/after/mod.rs
- src/test/resources/org/rust/ide/intentions/fixtures/contract_module/after/other.rs
- src/test/resources/org/rust/ide/intentions/fixtures/contract_module/before/mod.rs
- src/test/resources/org/rust/ide/intentions/fixtures/contract_module/before/other/mod.rs
The intention will only execute if the given "mod.rs" file is the only
file in its containing directory.
This intention is very similar to the Expand Module intention.
Resolve #223
> Add Contract Module intention

- src/main/kotlin/org/rust/ide/surround/DelimiterSurrounder.kt
- src/main/kotlin/org/rust/ide/surround/RustSurroundDescriptor.kt
- src/main/kotlin/org/rust/lang/core/psi/RustElementFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/util/RustPsiExtensions.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/surround/RustSurroundDescriptorTest.kt
> (SURROUND) add delimiter surrounder

- src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/colorscheme/RustColorSettingsPage.kt
- src/main/kotlin/org/rust/ide/colorscheme/RustColors.kt
- src/main/kotlin/org/rust/ide/highlight/syntax/RustHighlighter.kt
This aims to reduce color-related duplication to avoid problems like with https://github.com/intellij-rust/intellij-rust/commit/14fe4c41d01e3dbebb6fd9bd7bec59414399c736.
@himikof please review
> (MISC): simplify color handling

- src/main/kotlin/org/rust/ide/intentions/ExtractInlineModule.kt
- src/main/kotlin/org/rust/lang/core/psi/util/RustModExtensions.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/ExtractInlineModule/after.rs.template
- src/main/resources/intentionDescriptions/ExtractInlineModule/before.rs.template
- src/main/resources/intentionDescriptions/ExtractInlineModule/description.html
- src/test/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntentionTest.kt
- src/test/kotlin/org/rust/ide/intentions/RustIntentionsTest.kt
- src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
- src/test/resources/org/rust/ide/intentions/fixtures/invalid_extract_inline_module/after/main.rs
- src/test/resources/org/rust/ide/intentions/fixtures/invalid_extract_inline_module/before/main.rs
- src/test/resources/org/rust/ide/intentions/fixtures/valid_extract_inline_module/after/foo.rs
- src/test/resources/org/rust/ide/intentions/fixtures/valid_extract_inline_module/after/main.rs
- src/test/resources/org/rust/ide/intentions/fixtures/valid_extract_inline_module/before/main.rs
Fix #270 
and test will be covered later.
> (INTENSION) move inline mod to file

- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustUseItemImplMixin.kt
- src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
- src/test/kotlin/org/rust/lang/core/resolve/RustUseResolveTestCase.kt
- src/test/resources/org/rust/lang/core/resolve/fixtures/use/nested_wildcards.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/use/super_wildcard.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/use/two_wildcards.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/use/wildcard.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/use/wildcard_cycle.rs
@alexeykudinkin please review.
> (RES): whildcard (star) imports

- src/main/kotlin/org/rust/ide/navigation/goto/RustGotoSuperHandler.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/navigation/RustNavigationTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RustMultifileResolveTestCaseBase.kt
- src/test/resources/org/rust/ide/navigation/fixtures/goto_super.rs
- src/test/resources/org/rust/ide/navigation/fixtures/goto_super_after.rs
> (ACTION) add go super mod action

- src/main/kotlin/org/rust/ide/intentions/AddDerive.kt
- src/test/kotlin/org/rust/ide/intentions/AddDeriveIntentionTest.kt
- src/test/resources/org/rust/ide/intentions/fixtures/add_derive/add_derive_pub_struct.rs
- src/test/resources/org/rust/ide/intentions/fixtures/add_derive/add_derive_pub_struct_after.rs
Fixes #329 
@matklad please review
> (INTENTION, FIX) Fixed add derive intention in presence of pub modifiers

- src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoProjectWorkspaceImpl.kt
Looks like the simplest way to provide the necessary synchronization is to leverage existing read/write actions infra. This should prevent effects like https://github.com/intellij-rust/intellij-rust/pull/348#issuecomment-215506753.
> (WORKSPACE): synchronize via read/write actions

- src/main/kotlin/org/rust/lang/core/lexer/RustEscapesLexer.kt
See discussion under 9970c82fb72d28b37ca434356cf4868880aec900
> (MISC): avoid unnecessary `subSequence` calls

- doc/Tips.md
- src/main/resources/org/rust/ide/liveTemplates/Rust.xml
Use `tf` to inflate the following:
```
#[test]
fn $NAME$() {
$END$
}
> Test function template

- src/main/kotlin/org/rust/ide/formatter/RustFmtBlock.kt
- src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/main/kotlin/org/rust/ide/formatter/impl/utils.kt
Mostly readability improvements
> (FMT): small polish

- src/main/kotlin/org/rust/ide/icons/RustIcons.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustModDeclItemImplMixin.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustPatBindingImplMixin.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustTypeItemImplMixin.kt
As the title mentions. Nothing too major, just adds icons for the completion dialog.
> Add more icon getters.

- src/main/kotlin/org/rust/ide/annotator/RustExpressionAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RustAnnotatorTest.kt
- src/test/resources/org/rust/ide/annotator/fixtures/unnecessary_for_parens.rs
- src/test/resources/org/rust/ide/annotator/fixtures/unnecessary_if_parens.rs
- src/test/resources/org/rust/ide/annotator/fixtures/unnecessary_match_parens.rs
- src/test/resources/org/rust/ide/annotator/fixtures/unnecessary_return_parens.rs
- src/test/resources/org/rust/ide/annotator/fixtures/unnecessary_while_parens.rs
> Add more annotations for unnecessary parens.

- src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
I've been reading the resolve engine and I found that I don't quite understand the purpose of  `ResolveContext`. It has only two subclasses, `Trivial` and `Empty`, which do not do anything exciting. Just inlining `ResolveContext` into `resolveIn` leads to a shorter and simpler code. Perhaps there is no need for this class? @alexeykudinkin what do you think about this?
> (RES): simplify

- src/main/kotlin/org/rust/ide/formatter/impl/alignment.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustCodeStyleSettings.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustLanguageCodeStyleSettingsProvider.kt
- src/test/kotlin/org/rust/ide/formatter/RustFormatterTestCase.kt
- src/test/resources/org/rust/ide/formatter/fixtures/align_params_in_calls_off.rs
- src/test/resources/org/rust/ide/formatter/fixtures/align_params_in_calls_off_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/align_params_off.rs
- src/test/resources/org/rust/ide/formatter/fixtures/align_params_off_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/align_ret_where_off.rs
- src/test/resources/org/rust/ide/formatter/fixtures/align_ret_where_off_after.rs
All alignment can be now turned off
> (FMT): Moar options

- src/main/kotlin/org/rust/ide/formatter/impl/alignment.kt
- src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustCodeStyleSettings.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustLanguageCodeStyleSettingsProvider.kt
- src/test/kotlin/org/rust/ide/formatter/RustFormatterTestCase.kt
- src/test/resources/org/rust/ide/formatter/fixtures/align_where_bounds_off.rs
- src/test/resources/org/rust/ide/formatter/fixtures/align_where_bounds_off_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/items.rs
- src/test/resources/org/rust/ide/formatter/fixtures/items_after.rs
> (FMT): indent & align where bounds

- src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
- src/main/kotlin/org/rust/cargo/runconfig/RustExplainFilter.kt
- src/test/kotlin/org/rust/cargo/runconfig/RustExplainFilterTest.kt
This should resolve #450. I hope you like it.
Cheers,
Jesse
> (RUN) "--explain Exxxx" now links to relevant Rust error index entry

- src/main/kotlin/org/rust/cargo/runconfig/CargoCommandConfiguration.kt
- src/main/kotlin/org/rust/cargo/runconfig/forms/CargoRunConfigurationEditorForm.form
- src/main/kotlin/org/rust/cargo/runconfig/forms/CargoRunConfigurationEditorForm.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForBin.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningfulConfigurationName.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForAnnotatedFunctions.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForModules.xml
This should resolve #490.
Cheers,
Jesse
> (RUN): Adds "backtrace" checkbox to run configurations

- src/main/kotlin/org/rust/ide/formatter/blocks/RustMacroArgFmtBlock.kt
- src/main/kotlin/org/rust/ide/formatter/impl/alignment.kt
- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/main/kotlin/org/rust/ide/formatter/impl/utils.kt
- src/test/kotlin/org/rust/ide/formatter/RustFormatterTestCase.kt
- src/test/resources/org/rust/ide/formatter/fixtures/issue543a.rs
- src/test/resources/org/rust/ide/formatter/fixtures/issue543a_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/issue543b.rs
- src/test/resources/org/rust/ide/formatter/fixtures/issue543b_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/issue543c.rs
- src/test/resources/org/rust/ide/formatter/fixtures/issue543c_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/spacing_after.rs
> (FMT): fix #543

- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustCodeStyleSettings.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustLanguageCodeStyleSettingsProvider.kt
- src/main/resources/org/rust/ide/formatter/settings/wrap_sample.rs
- src/test/kotlin/org/rust/ide/formatter/RustFormatterTestCase.kt
- src/test/resources/org/rust/ide/formatter/fixtures/macro_use.rs
- src/test/resources/org/rust/ide/formatter/fixtures/macro_use_after.rs
- src/test/resources/org/rust/ide/formatter/fixtures/macro_use_off.rs
- src/test/resources/org/rust/ide/formatter/fixtures/macro_use_off_after.rs
> (FMT): allow #[macro_use] attr to be placed in line with extern crate item

- src/main/kotlin/org/rust/ide/formatter/impl/alignment.kt
fixes #559 
No tests, because this one feels rather like a parser recovery issue than formatter for me.
> (FMT): fix #559

- src/main/java/org/rust/lang/core/psi/RustTokenElementTypes.java
- src/main/kotlin/org/rust/lang/core/grammar/rust.bnf
- src/main/kotlin/org/rust/lang/core/psi/RustBinaryExprElementEx.kt
> (PSI): provide operator accessor for binary exprs

- src/main/resources/intentionDescriptions/AddCurlyBracesIntention/after.rs.template
- src/main/resources/intentionDescriptions/AddCurlyBracesIntention/before.rs.template
- src/main/resources/intentionDescriptions/AddDeriveIntention/after.rs.template
- src/main/resources/intentionDescriptions/RemoveCurlyBracesIntention/after.rs.template
- src/main/resources/intentionDescriptions/RemoveCurlyBracesIntention/before.rs.template
- src/main/resources/intentionDescriptions/RemoveParenthesesFromExprIntention/after.rs.template
- src/main/resources/intentionDescriptions/RemoveParenthesesFromExprIntention/before.rs.template
- src/main/resources/intentionDescriptions/UnwrapLambdaExprIntention/after.rs.template
- src/main/resources/intentionDescriptions/UnwrapLambdaExprIntention/before.rs.template
- src/main/resources/intentionDescriptions/WrapLambdaExprIntention/after.rs.template
- src/main/resources/intentionDescriptions/WrapLambdaExprIntention/before.rs.template
@matklad @mkaput  to highlight the changes in intention description code snippets.
> add spot block for intention descriptions

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
> lookup elements for multiline declaration

- src/main/kotlin/org/rust/ide/inspections/RustCStringPointerInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RustCStringPointer.html
- src/test/kotlin/org/rust/ide/inspections/RustInspectionsTest.kt
- src/test/resources/org/rust/ide/inspections/fixtures/cstring_pointer.rs
> add unsafe CString pointer inspection

- src/main/kotlin/org/rust/ide/annotator/RustItemsAnnotator.kt
- src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
- src/test/kotlin/org/rust/ide/annotator/RustAnnotatorTestBase.kt
- src/test/kotlin/org/rust/ide/annotator/RustItemAnnotatorTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RustMultiFileResolveTestCase.kt
- src/test/resources/org/rust/ide/annotator/fixtures/items/helper.rs
- src/test/resources/org/rust/ide/annotator/fixtures/items/invalid_module_declarations.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/mod_relative/foo.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/mod_relative/main.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/mod_relative/sub.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/mod_relative2/foo.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/mod_relative2/main.rs
- src/test/resources/org/rust/lang/core/resolve/fixtures/mod_relative2/sub/mod.rs
Improve handling of explicit path attributes on module declarations
> Improve explicit path attributes on module declarations

- src/main/kotlin/org/rust/lang/core/resolve/ref/RustReferenceBase.kt
- src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
- src/test/resources/org/rust/ide/refactoring/fixtures/rename/rename_file/after/bar.rs
- src/test/resources/org/rust/ide/refactoring/fixtures/rename/rename_file/after/main.rs
- src/test/resources/org/rust/ide/refactoring/fixtures/rename/rename_file/before/foo.rs
- src/test/resources/org/rust/ide/refactoring/fixtures/rename/rename_file/before/main.rs
> Fix NPE when renaming Rust file

- src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.form
- src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
- src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
First step for #308 
seems to achieve the whole supporting is a long journey, so maybe tackle it with seperated PRs is better 😃
> show rustup version in settings panel

- src/main/kotlin/org/rust/ide/navigation/goto/RustGotoSuperHandler.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustImplMethodMemberImplMixin.kt
- src/test/kotlin/org/rust/ide/navigation/goto/RustNavigationTest.kt
- src/test/resources/org/rust/ide/navigation/goto/fixtures/goto_super_method.rs
- src/test/resources/org/rust/ide/navigation/goto/fixtures/goto_super_method_after.rs
Fix for #541.
@matklad, please review
> (MISC): extend GotoSuper action to work for iml methods. Fix #541

- .gitignore
lib file is definitely for lexing and parsing processes, no need to ignore changes about them.
> remove unnecessary git ignore

- src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
- src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
- src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
This reduces duplication in the `RustToolchain` and also makes it easier to use, because there is only one method with `isDispatchThread` precondition. 
@zjhmale please review.
> Toolchain dedup

- src/main/kotlin/org/rust/lang/core/types/RustCharacterType.kt
- src/main/kotlin/org/rust/lang/core/types/RustFloatType.kt
- src/main/kotlin/org/rust/lang/core/types/RustIntegerType.kt
- src/main/kotlin/org/rust/lang/core/types/RustStringType.kt
- src/main/kotlin/org/rust/lang/core/types/visitors/impl/RustTypificationEngine.kt
- src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
- src/test/kotlin/org/rust/lang/core/type/RustExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RustTypeResolvingTest.kt
> Fixes for inference of primitive types and literals

- src/main/kotlin/org/rust/ide/docs/RustDocumentationProvider.kt
- src/test/kotlin/org/rust/ide/docs/RustQuickNavigationInfoTest.kt
- src/test/resources/org/rust/ide/docs/fixtures/nav/expanded_signature.html
- src/test/resources/org/rust/ide/docs/fixtures/nav/expanded_signature.rs
- src/test/resources/org/rust/ide/docs/fixtures/nav/multiple_where.html
- src/test/resources/org/rust/ide/docs/fixtures/nav/multiple_where.rs
- src/test/resources/org/rust/ide/docs/fixtures/nav/trait_method.html
- src/test/resources/org/rust/ide/docs/fixtures/nav/trait_method.rs
This is the preliminary work required for #650. Since I'm a newbie at Kotlin and IDEA, I'd really appreciate any input on style and better ways to structure the checks I'm doing.
> (MISC) Improve quick doc signature generation

- src/main/java/org/rust/lang/core/psi/RustTokenElementTypes.java
- src/main/kotlin/org/rust/ide/formatter/impl/utils.kt
- src/main/kotlin/org/rust/ide/highlight/RustHighlighter.kt
- src/main/kotlin/org/rust/lang/core/psi/RustTokenType.kt
> (MISC) Mark Rust tokens as operators

- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/test/kotlin/org/rust/ide/formatter/RustFormatterTest.kt
- src/test/resources/org/rust/ide/formatter/fixtures/issue654.rs
- src/test/resources/org/rust/ide/formatter/fixtures/issue654_after.rs
> (MISC) Remove spaces between struct name and tuple params

- src/main/kotlin/org/rust/ide/typing/RustRawLiteralHashesBalancer.kt
- src/test/kotlin/org/rust/ide/typing/RustTypingMiscTests.kt
- src/test/kotlin/org/rust/ide/typing/RustTypingTestCaseBase.kt
> (MISC): fix offset check

- src/main/kotlin/org/rust/ide/actions/RustStringLiteralJoinLinesHandler.kt
- src/main/kotlin/org/rust/ide/typing/utils.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/actions/RustStringLiteralJoinLinesHandlerTest.kt
- src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
> (ACTION): string literal joiner

- src/main/kotlin/org/rust/ide/inspections/RustSuspiciousAssignmentInspection.kt
- src/main/kotlin/org/rust/ide/inspections/fixes/SubstituteTextFix.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RustSuspiciousAssignment.html
- src/test/kotlin/org/rust/ide/inspections/RustSuspiciousAssignmentInspectionTest.kt
An analogue of the Clippy's [suspicious_assignment_formatting](https://github.com/Manishearth/rust-clippy/wiki#suspicious_assignment_formatting) lint with a couple of quick fixes.
> (MISC) Suspicious Assignment inspection

- src/main/kotlin/org/rust/lang/core/types/visitors/impl/RustTypificationEngine.kt
- src/test/kotlin/org/rust/lang/core/type/RustExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RustTypificationTestBase.kt
It's second attempt of this PR. 
https://github.com/intellij-rust/intellij-rust/pull/712
> (TYPE): Resolve ==,!=,<=,>=,<,>,||,&& to bool

- src/main/kotlin/org/rust/ide/inspections/RustCStringPointerInspection.kt
- src/main/kotlin/org/rust/ide/inspections/RustDoubleNegInspection.kt
- src/main/kotlin/org/rust/ide/inspections/RustDropRefInspection.kt
- src/main/kotlin/org/rust/ide/inspections/RustUnresolvedReferenceInspection.kt
No functional changes involved. Just minor refactoring, simplification and bringing inspections to a a common style.
> (MISC): Inspections refactoring

- src/main/kotlin/org/rust/ide/intentions/AddElseIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/AddElseIntention/after.rs.template
- src/main/resources/intentionDescriptions/AddElseIntention/before.rs.template
- src/main/resources/intentionDescriptions/AddElseIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/AddElseIntentionTest.kt
What do you think, is it useful intention or it's too elementary action for intention?
> (INT) Add else branch intention

- src/main/kotlin/org/rust/ide/surroundWith/expression/RustExpressionSurrounderBase.kt
- src/main/kotlin/org/rust/ide/surroundWith/expression/RustWithIfExpSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/expression/RustWithNotSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/expression/RustWithParenthesesSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/expression/RustWithWhileExpSurrounder.kt
- src/main/kotlin/org/rust/ide/template/postfix/surrounderBasedPostfixTemplates.kt
- src/test/kotlin/org/rust/ide/surroundWith/RustSurrounderTestCaseBase.kt
- src/test/kotlin/org/rust/ide/surroundWith/expression/RustWithIfExpSurrounderTest.kt
- src/test/kotlin/org/rust/ide/surroundWith/expression/RustWithWhileExpSurrounderTest.kt
- src/test/kotlin/org/rust/ide/surroundWith/statement/RustWithForSurrounderTest.kt
- src/test/kotlin/org/rust/ide/surroundWith/statement/RustWithIfSurrounderTest.kt
- src/test/kotlin/org/rust/ide/surroundWith/statement/RustWithWhileSurrounderTest.kt
- src/test/kotlin/org/rust/ide/template/postfix/ElsePostfixTemplateTest.kt
- src/test/kotlin/org/rust/ide/template/postfix/IfPostfixTemplateTest.kt
- src/test/kotlin/org/rust/ide/template/postfix/PostfixTemplateTestCase.kt
- src/test/kotlin/org/rust/ide/template/postfix/WhileNotPostfixTemplateTest.kt
Fix syntax error, which appears immediately after surrounder use.
> (SURR): Correct postprocess

- src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/MatchToIfLetIntention/after.rs.template
- src/main/resources/intentionDescriptions/MatchToIfLetIntention/before.rs.template
- src/main/resources/intentionDescriptions/MatchToIfLetIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
> (INT): Match to if let

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
Fixes the `--color=always` position [problem](https://github.com/intellij-rust/intellij-rust/issues/646#issuecomment-266288142).
> (MISC): Fix color argument position

- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustCodeStyleSettings.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RustLanguageCodeStyleSettingsProvider.kt
- src/test/kotlin/org/rust/ide/formatter/RustFormatterTest.kt
> Disable inline macro use by default

- src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RustPsiFactory.kt
- src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Small fix for methods declarations and implementation. And tests.
> (INT): UnElideLifetimes for methods

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/icons/RustIcons.kt
- src/main/kotlin/org/rust/lang/core/completion/RustCompletionEngine.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustExternCrateItemImplMixin.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RustExternCrateReferenceImpl.kt
- src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
- src/test/kotlin/org/rust/lang/core/completion/RustExternCrateCompletionTest.kt
Adds autocompletion for extern crate names.
> (COMPL): Extern crate names completion

- src/main/kotlin/org/rust/ide/icons/RustIcons.kt
- src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
A couple of improvements of attributes completion:
1. Add parenthesis to attributes that require additional arguments.
2. Add icon to attributes (the same as used for annotations in Java/Kotlin) in completion list.
> (COMPL): Attributes completion improvement

- src/main/kotlin/org/rust/lang/core/RustPsiPattern.kt
- src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributor.kt
- src/test/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributorTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RustPsiPatternTest.kt
Autocompletion for the `break` and `continue` keywords inside loops.
> (COMPL): Autocomplete break and continue keywords

- src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributor.kt
- src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributorTest.kt
They somehow totally slipped my mind.
> (COMPL): const and static keywords completion

- ARCHITECTURE.md
> (DOC): Fix typos

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/annotator/RustErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustLifetimeParamElementImplMixin.kt
- src/main/kotlin/org/rust/lang/core/resolve/ScopeEntry.kt
- src/test/kotlin/org/rust/ide/annotator/RustErrorAnnotatorTest.kt
It's E0263 (lifetime name duplication) from #886.
> (ANNOT): Detect lifetime names duplication

- src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
- src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
- src/test/kotlin/org/rust/cargo/toolchain/CargoProjectResolveTest.kt
- src/test/resources/org/rust/cargo/toolchain/fixtures/case_insensitive_mods/Cargo.toml
- src/test/resources/org/rust/cargo/toolchain/fixtures/case_insensitive_mods/src/BAR.rs
- src/test/resources/org/rust/cargo/toolchain/fixtures/case_insensitive_mods/src/FOO.rs
- src/test/resources/org/rust/cargo/toolchain/fixtures/case_insensitive_mods/src/lib.rs
> RES: fix module resolve for case-insensitive file systems

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Seems to work fine on the file level now :tada: 
@alygin please review
> Sidetable duplicates

- src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt
- src/main/kotlin/org/rust/ide/annotator/RsCrateDocLineMarkerProvider.kt
- src/main/kotlin/org/rust/ide/icons/RsIcons.kt
- src/main/kotlin/org/rust/lang/core/resolve/ResolveEngine.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/annotator/RsCrateDocLineMarkerProviderTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsLineMarkerProviderTestBase.kt
- src/test/kotlin/org/rust/lang/RsTestBase.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Adds gutter icons that open external crate documentation as described in #931.
> (ANNOT): Crate docs gutter icon

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> (ANNOT): Detect function param names duplication

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> (ANNOT): Ignore raw pointers in E0106 annotation

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
Fixes the issues reported in #988 (at least on Arch Linux).
> Fix TERM environment variable setting

- src/main/kotlin/org/rust/ide/inspections/RsSimplifyBooleanExpressionInspection.kt
- src/main/kotlin/org/rust/ide/utils/ExprUtils.kt
Fix of [#1000](https://github.com/intellij-rust/intellij-rust/issues/1000).
Happy anniversary 1000-th issue :)
> INSP: Fix of simplify boolean expression inspection not to change PSI tree

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Annotate undeclared lifetimes and labels (E0261 and E0426 from #886)
> ANNOT: Undeclared lifetimes and labels annotation E0261/E0426

- src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
- src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
closes #1025
@mkaput looks ok?
> FMT: fix where indent in impls

- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/main/kotlin/org/rust/ide/utils/PresentationUtils.kt
- src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RsPatBindingImplMixin.kt
- src/main/kotlin/org/rust/lang/core/types/PatternMatching.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
Refactoring and various improvements of quick navigation info.
> DOC: Better quick navigation info

- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
- src/main/kotlin/org/rust/lang/core/types/RustPsiExtensions.kt
- src/main/kotlin/org/rust/lang/core/types/RustType.kt
- src/main/kotlin/org/rust/lang/core/types/RustTypeFingerprint.kt
- src/main/kotlin/org/rust/lang/core/types/RustTypificationEngine.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustArrayType.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustPointerType.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustSliceType.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustStringSliceType.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsCoercionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsSubtypingTest.kt
Now it is possible to check that current type can be implicitly converted to another type
> TY: Add slice methods completion, subtyping support

- src/main/kotlin/org/rust/lang/core/resolve/ResolveEngine.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
> RES: Resolve lifetime declarations in polybounds

- src/main/kotlin/org/rust/ide/projectView/RsTreeStructureProvider.kt
> MISC: Fix mod.rs promotion

- src/main/kotlin/org/rust/lang/core/psi/ext/RsRefLikeType.kt
- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/types/RustTypificationEngine.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
This are various small problems that were found while working on other code parts.
If you have an idea how to properly test for any of the changed behaviour I would be happy to add new tests.
> Various small fixes

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/RsRefactoringSupportProvider.kt
- src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/AddMutableTest.kt
- src/test/resources/org/rust/ide/annotator/fixtures/performance/main.rs
This checks field, functions and assignment and allow quick fix.
> ANNOT: Extend mutable check annotator and add quick fix

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
> RUN: Colored output for cargo check

- src/main/resources/org/rust/ide/liveTemplates/test.xml
tbn doesn't really mean anything, I didn't think enough when I added that
> tbn -> bfn

- src/main/kotlin/org/rust/ide/formatter/RsFmtContext.kt
- src/main/kotlin/org/rust/ide/formatter/RsMatchArmCommaFormatProcessor.kt
- src/main/kotlin/org/rust/ide/formatter/RsTrailingCommaFormatProcessor.kt
- src/main/kotlin/org/rust/ide/formatter/Util.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RsCodeStyleSettings.kt
- src/main/kotlin/org/rust/ide/formatter/settings/RsLanguageCodeStyleSettingsProvider.kt
- src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
> FMT: configurable commas removal

- src/main/kotlin/org/rust/lang/core/types/types/RustFloatType.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustIntegerType.kt
> Ignore 'isKindWeak' in type comparision

- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/RsRefactoringSupportProvider.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionAction.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionDialog.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandler.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandlerAction.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
@matklad What do you think? 
Any tip to test my Action?
> TYPE: Implement extract method without support of parameter

- src/main/resources/META-INF/idea-only.xml
- src/main/resources/META-INF/plugin.xml
> Add RsModuleType to all IDEs

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/ImplementMembersFix.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/core/overrideImplement/ImplementMembersFixTest.kt
close https://github.com/intellij-rust/intellij-rust/issues/1115
> Fix implement members

- src/main/kotlin/org/rust/lang/core/resolve/Resolve.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsExternCrateReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsFieldExprReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsLabelReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsLifetimeReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsModReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsUseGlobReferenceImpl.kt
Useful for more clear stacktraces
> RES: uniquify names of resolve processing functions

- exampleProject/src/main.rs
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/RsConvertToNamedFieldsAction.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsActionTest.kt
https://zippy.gfycat.com/SpiritedRealArieltoucan.webm
> REF: convert tuple struct to block struct refactoring

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsNamespaceResolveTest.kt
closes https://github.com/intellij-rust/intellij-rust/issues/1138
> RES: better handle namespaces in use items

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
> COMP: Suggest associated types

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
> RES: resolve references to constants in patterns

- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/main/kotlin/org/rust/ide/utils/PresentationUtils.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustEnumType.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustStructOrEnumTypeBase.kt
- src/main/kotlin/org/rust/lang/core/types/types/RustStructType.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
- src/test/resources/org/rust/ide/docs/fixtures/doc/conditional_binding.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/conditional_binding.rs
- src/test/resources/org/rust/ide/docs/fixtures/doc/fn_arg.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/fn_arg.rs
- src/test/resources/org/rust/ide/docs/fixtures/doc/generic_enum_variable.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/generic_enum_variable.rs
- src/test/resources/org/rust/ide/docs/fixtures/doc/generic_struct_variable.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/generic_struct_variable.rs
- src/test/resources/org/rust/ide/docs/fixtures/doc/tuple_destructuring.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/tuple_destructuring.rs
- src/test/resources/org/rust/ide/docs/fixtures/doc/variable.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/variable.rs
Add quick documentation for local variables.
> local variable documentation

- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
- src/test/resources/org/rust/ide/docs/fixtures/doc/conditional_binding.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/fn_arg.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/generic_enum_variable.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/generic_struct_variable.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/struct_field.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/struct_field.rs
- src/test/resources/org/rust/ide/docs/fixtures/doc/tuple_destructuring.html
- src/test/resources/org/rust/ide/docs/fixtures/doc/variable.html
> Improve quick documentation of struct fields

- src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
- src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt
- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
I uses an idea by @kumbayo. Is it okay?
> RES: Support autoderef using language attribute

- src/main/kotlin/org/rust/cargo/runconfig/RsProjectTasksRunner.kt
- src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
- src/main/resources/META-INF/plugin.xml
Note to self: remove FAQ entry on release.
> Bind "build project" to `cargo build`

- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Separate "look in the index and cache" and "run dfs on derefs" phases
> TYPE: slightly refactor search of deref'ed types

- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
> COMP: Should not complete for function with test attribute

- src/main/kotlin/org/rust/lang/core/types/types/RustReferenceType.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
> Nicer to string for reference types

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
> DBG: discover test binaries

- appveyor.yml
- bors.toml
> CI: gate PRs on appveyor

- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: Basic support for closure type inference

- src/main/kotlin/org/rust/ide/typing/RsAngleBraceHandlers.kt
- src/test/kotlin/org/rust/ide/typing/RsAngleBraceTypedHandlerTest.kt
> TYPE: don't jump over `>` in comments

- src/main/kotlin/org/rust/lang/core/psi/ext/RsRefLikeType.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
> Improve primitive type autocompletion

- src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: tuple field type inference

- src/main/kotlin/org/rust/ide/hints/RsParameterInfoHandler.kt
> Fix ClassCastException during completion

- src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
- src/main/kotlin/org/rust/ide/miscExtensions/RsDescriptionProvider.kt
- src/main/kotlin/org/rust/ide/miscExtensions/RsModTabTitleProvider.kt
- src/main/kotlin/org/rust/ide/utils/PresentationUtils.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProviderTest.kt
> Add breadcrumbs

- src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
- src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
- src/test/kotlin/org/rust/ide/folding/RsFoldingTest.kt
- src/test/resources/org/rust/ide/folding/fixtures/block_comment.rs
- src/test/resources/org/rust/ide/folding/fixtures/comments.rs
> TYPE: fold doc comments

- src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
- src/main/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntention.kt
- src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt
> INT: do not show "remove unnecessary parens" for struct literals

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANNOT: Detect wrong safe or unsafe impls E0199/E0200

- src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
> TY: infer generic type params in pattern matching

- src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt
> Less obtrusive missing struct fields error highlighting

- src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Support type inference of generic method call exprs.
> TY: improve type inference of method call expr

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
The 2 main improvements are:
* Ranges ".." and "..." are typified to ops::Rangexxx
* The macros vec![] and format!("") are typified to vec::Vec<T> and String
> Typification improvements

- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Add integration test to check interaction between range expression and index expression type inference
> T: vec slice resolve test

- .idea/runConfigurations/Test.xml
- .idea/runConfigurations/Test_Slow.xml
- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/ide/actions/RsFmtFileAction.kt
- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
- src/test/kotlin/org/rust/cargo/RsCargoCheckAnnotatorTest.kt
- src/test/kotlin/org/rust/cargo/RustWithToolchainTestBase.kt
- src/test/kotlin/org/rust/cargo/commands/CargoFmtTest.kt
- src/test/kotlin/org/rust/cargo/project/workspace/impl/CargoTomlWatcherIntegrationTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/RunConfigurationTestCase.kt
- src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
- src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorTest.kt
- src/test/kotlin/org/rustSlowTests/RsResolvePerformanceTest.kt
- src/test/resources/org/rust/cargo/commands/fixtures/fmt/hello/Cargo.toml
- src/test/resources/org/rust/cargo/commands/fixtures/fmt/hello/src/main.rs
- src/test/resources/org/rust/cargo/runconfig/fixtures/hello/Cargo.toml
- src/test/resources/org/rust/cargo/runconfig/fixtures/hello/src/main.rs
Make it easier to test `CargoCheckAnnotator`. 
cc @vasily-kirichenko
> Check test

- src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/SpecifyTypeExplicitlyIntention/after.rs.template
- src/main/resources/intentionDescriptions/SpecifyTypeExplicitlyIntention/before.rs.template
- src/main/resources/intentionDescriptions/SpecifyTypeExplicitlyIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
> INT: add specify type explicitly intention

- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
> TY: IOB while infering lambda type

- src/main/kotlin/org/rust/ide/annotator/fixes/ImplementMembersFix.kt
- src/main/kotlin/org/rust/ide/core/overrideImplement/ImplementMembersHandler.kt
- src/main/kotlin/org/rust/ide/core/overrideImplement/generateUtil.kt
> FIX: show nice error message if there's nothing to implement

- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
> Don't access disposed models in Cargo check

- src/main/kotlin/org/rust/ide/formatter/RsSingleImportRemoveBracesFormatProcessor.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/formatter/RsFormatterImportBracesTest.kt
> (FMT) Remove redundant braces around single item imports

- src/main/kotlin/org/rust/lang/refactoring/RsConvertToNamedFieldsAction.kt
> Don't KNPE when invoking refactoring in the wrong context

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
> GRAM: allow bare `*` imports

- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
libcollection is renamed as liballoc
> T: fix tests with nightly rust

- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
> ANN: don't resave already saved document

- src/main/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspection.kt
- src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeParameter.kt
- src/main/resources/inspectionDescriptions/RsWrongTypeParametersNumber.html
- src/test/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspectionTest.kt
> INSP: Extend wrong type parameters inspection and add a simple fix.

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/intentions/AddElseIntention.kt
> Fix a couple of warnings

- src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoProjectWorkspaceServiceImpl.kt
> Warn when opening a member of the workspace

- src/main/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspection.kt
- src/test/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspectionTest.kt
> INSP: Fix false postive and cleanup code for more readability

- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
> Safe check

- src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
`inferExpressionType` is getting too big: at this moment it takes more than 200 lines.
I've split it into several functions for each expression type except one-liner expressions.
> Expressions refactoring

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsNamespaceResolveTest.kt
> RES: don't suggest values in name resolution for struct literal paths

- src/main/kotlin/org/rust/ide/highlight/RsRainbowVisitor.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/highlight/RsRainbowVisitorTest.kt
Has anyone a idea for a better icon?
> TYPE: Rainbow highlighter for variable

- src/main/kotlin/org/rust/ide/formatter/RsReturnStatementFormatProcessor.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
- src/test/resources/org/rust/ide/formatter/fixtures/expressions_after.rs
#1090 add semicolon after return
> FMT: add semicolon after return

- src/main/kotlin/org/rust/ide/actions/RsJoinLinesHandler.kt
- src/main/kotlin/org/rust/ide/formatter/impl/utils.kt
- src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTest.kt
- src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTestBase.kt
> TYPE: remove `,` on join lines in more cases

- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
- src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorTest.kt
> ANN: reduce dead code warning span

- src/main/kotlin/org/rust/ide/hints/RsParameterInfoHandler.kt
- src/main/kotlin/org/rust/lang/core/completion/CompletionEngine.kt
> COMP: Autopopup parameter info

- src/main/kotlin/org/rust/lang/core/completion/RsMacroDefinitionCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
> MACRO: support super resolve

- src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
Use of string interpolation is fraught with risks...
> Fixed associated type name

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: infer type of loop expressions

- src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
> TYPE: Highlight exit points of the function

- src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt
* Fix relation between `Copy` and `Clone` traits
* Find manual implementations of derivable traits and skip them in completion suggestions
> COMP: Improve derive completion 2

- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
> TY: infer Self type in assoc function

- src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
There were BIG problems (OOME #1563) with type inference in mysql_async project, so i thought it's reasonable to embed it into our performance tests.
// Also fixed project dir refresh in test's VFS
> T: Added option mysql_async test to RsHighlightingPerformanceTest

- src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
- src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
- src/main/kotlin/org/rust/ide/utils/CallInfo.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
> TYPE: Extend hints

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunLineMarkerContributor.kt
- src/test/kotlin/org/rust/cargo/runconfig/test/CargoTestRunLineMarkerContributorTest.kt
> CARGO: Support basic run tests in mod

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/hints/RsImplementationTextSelectioner.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeBearingItemElement.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/hints/RsQuickDefinitionTest.kt
> Fix quick definition

- src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
> TYPE: Classify usage type

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> Fix autoderef for tuple field access

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
- src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunLineMarkerContributor.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunLineMarkerContributor.kt
- src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
- src/main/kotlin/org/rust/ide/annotator/RsCrateDocLineMarkerProvider.kt
- src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
- src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
- src/main/kotlin/org/rust/ide/typing/utils.kt
- src/main/kotlin/org/rust/ide/update/UpdateComponent.kt
- src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTest.kt
> Fix backcompat warnings

- src/main/kotlin/org/rust/ide/formatter/blocks/RsFmtBlock.kt
- src/test/kotlin/org/rust/ide/formatter/RsAutoIndentTest.kt
closes https://github.com/intellij-rust/intellij-rust/issues/1602
> TYPE: better indent handing for last field

- .idea/dictionaries/matklad.xml
- src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyStructOrEnum.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyUnknown.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
closes https://github.com/intellij-rust/intellij-rust/issues/1548
> Shorten long types in hints

- debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerTypesHelper.kt
- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
- src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
- src/test/kotlin/org/rust/ide/docs/RsStdlibResolveLinkTest.kt
- src/test/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactoryTest.kt
Support links in quick documentation.
> QDOC: links

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Now traversing PSI manually, looking for each element type and its children we should process.
(Last preparations before implementing honest type inference)
> TypeInference refactoring

- src/main/kotlin/org/rust/lang/core/types/Extensions.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
> TY: Infer receiver type even if dot expr is not finished

- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt
> Short types with ignore ref as level

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
- src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
- src/main/kotlin/org/rust/ide/inspections/RsVariableMutableInspection.kt
- src/main/kotlin/org/rust/ide/intentions/SetMutableIntention.kt
- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsRefLikeType.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsSelfParameter.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/types/Extensions.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
- src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
> Use enum `Mutability` instead of boolean flags

- src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
- src/main/kotlin/org/rust/cargo/runconfig/ui/RunCargoCommandDialog.kt
- src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
- src/main/kotlin/org/rust/cargo/util/CargoCommandLineEditor.kt
- src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
Add UI component for adding Cargo commands with completion. Currently it is used only in **Run Cargo Command** action, but the plan is to plug it into run configurations as well.
https://zippy.gfycat.com/FixedGiantAiredaleterrier.webm
r? @vlad20012
> Cargo command editor

- src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
- src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
> COMP: if/match completion

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
> Fix rustfmt with workspaces

- src/main/kotlin/org/rust/ide/intentions/FillMatchArmsIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/FillMatchArmsIntention/after.rs.template
- src/main/resources/intentionDescriptions/FillMatchArmsIntention/before.rs.template
- src/main/resources/intentionDescriptions/FillMatchArmsIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/FillMatchArmsIntentionStdTest.kt
- src/test/kotlin/org/rust/ide/intentions/FillMatchArmsIntentionTest.kt
> INT: `Fill match arms` intention

- .travis.yml
Just checking if it could help with recent CI failures
> CI: disable incremental compilation of Kotlin

- src/main/kotlin/org/rust/cargo/project/CargoToolWindow.kt
- src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoTomlWatcher.kt
- src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectAction.kt
- src/main/resources/META-INF/plugin.xml
Add a toolbar which gives a nicer representation of Cargo status.
> Add toolbar

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
> RES: support associated constants

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
This enables auto completion on arrays.
> Coerce arrays to slices

- src/main/kotlin/org/rust/ide/inspections/RsTryMacroInspection.kt
> Fix exceptions happening after running the "Change try! to ?" inspection

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/cargo/toolchain/ProxyHelper.kt
- src/test/kotlin/org/rust/cargo/toolchain/CargoProxyTest.kt
fixes #1021 
I accidentally closed #1558 by deleting commit, so I recreated another PR
> CARGO: fix proxy

- src/main/kotlin/org/rust/ide/inspections/RsFieldInitShorthandInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsFieldInitShorthand.html
- src/test/kotlin/org/rust/ide/inspections/RsFieldInitShorthandInspectionTest.kt
> INSP: field init shorthand inspection

- src/main/kotlin/org/rust/ide/presentation/Utils.kt
- src/test/kotlin/org/rust/ide/structure/RsStructureViewTest.kt
> TYPE: Add visiblity for explict public in structure view

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeDeclarationElement.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/RsPsiTypeImplUtil.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsNamespaceResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
> RES: uniform handling of associated items

- src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
- src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Not sure if the implementation can be less copy-pasty...
> PSI: Cache file items

- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
I've tried implementing a `bulidMap` function, and it didn't turn out to be significantly more readable :(
> RES: simplify a tiny bit

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
@vlad20012 @matklad Did i miss any case?
> ANN: Support of errors E0616 and E0624

- src/main/kotlin/org/rust/lang/core/completion/RsMacroDefinitionCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
> COMP: Refactor macro comp and walkup

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsAnnotatorTestBase.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Fix incorrect annotation on private fields for super structs

- src/main/resources/META-INF/plugin.xml
Commit eecdf544ae002 updated the date but forgot to increment the number.
> Fix URL of the Changelog

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
- src/main/kotlin/org/rust/lang/core/types/RsDiagnostic.kt
- src/main/kotlin/org/rust/lang/core/types/TraitRef.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyStructOrEnum.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
It is very experimental and very basic (=D). It has a lot of false negatives, but should not contain false positives. Anyway, false positive is a bug. Report it.
> Experimantal basic type checking

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Fixes #1639 
@matklad @Undin r?
> COMP: Fix function self ref and double colon

- src/main/kotlin/org/rust/lang/core/psi/ext/RsBaseType.kt
- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
- src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
> RES: Support impl for type parameter `impl<T> Trait for T`

- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
> RES: don't use 'resolve' while indexing

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt
> TY: Coerce container type while index expr type inference

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsReference.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/utils/helpers.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Partially f'ixes #1753 
It doesn't affect path resolution for now, just type inference
> TY: supported UFCS & multiple impls of the same trait

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsAssertEqual.html
- src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt
#1762
This is my first development with IntelliJ plugin.
So please give me feedback on building expression.
> (INSP): add assert! -> assert_eq(ne) inspection

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> Fix E0424 False Positive on use with parens

- src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
> Don't relay on order of resolve in Cargo metadata

- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
* Introduce arrays with unknown size
* ~~Implement rough array size expression calculation~~
* Use long for array size value
Fixes #1790
> TY: Improve array expr type inference

- CONTRIBUTORS.txt
> maraisr is now a contrib :tada:

- src/main/kotlin/org/rust/ide/actions/RsFmtFileAction.kt
Never written a single line of Kotlin before - so please be nice! :heart: 
fixes #1131
> Let the user know to install cargo fmt

- src/main/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntention.kt
- src/test/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntentionTest.kt
Not too sure what the issue #1797 was talking about - but thinking it's something along these lines?
fixes #1797
> [#1797] Unsafe block checked

- CONTRIBUTING.md
> DOC: labels meaning

- src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
Fixes #1794 .
I'll try to support by checking type name.
But is it correct way to check type of struct field?
> Improve AddStructFieldsFix to support fill struct & fill struct recurively.

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/inspections/RsExperimentalChecksInspection.kt
- src/main/kotlin/org/rust/lang/core/types/RsDiagnostic.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsExperimentalChecks.html
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsTypeCheckTest.kt
Can't fix all typecheck false-positives (#1753) quickly, so turn it off :(
> ANN: typecheck is now a disabled by default inspection

- src/main/kotlin/org/rust/ide/intentions/FillMatchArmsIntention.kt
- src/test/kotlin/org/rust/ide/intentions/FillMatchArmsIntentionTest.kt
> INT: Add arms before right brace

- src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
- src/main/kotlin/org/rust/lang/core/types/Extensions.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
> HINT: Remove redundant local variable type hint

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
We really need to make a real bot some day, but a PR template should be a good stop-gap solution.
r? @vlad20012
> Add a PR template which mentions CLA

- src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
> INSP: Don't warn about conventions when implementing traits

- .github/PULL_REQUEST_TEMPLATE.md
- src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
> Update Cargo command line completions

- src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
- src/main/kotlin/org/rust/cargo/util/CargoCommandLineEditor.kt
- src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
Add `--manifest-path` to completion.
> Cargo comp

- src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
- src/main/kotlin/org/rust/openapiext/utils.kt
- src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
- src/test/kotlin/org/rust/cargo/project/model/CargoProjectsServiceTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
closes #1870
Ideas serialization can't deserialize `java.nio.Path`.
r? @vlad20012
> Fix project settings serialization

- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/colors/RsColors.kt
- src/main/resources/org/rust/ide/colors/RustDarcula.xml
- src/main/resources/org/rust/ide/colors/RustDefault.xml
> Highlight mutable references and mutable parameters

- .idea/dictionaries/matklad.xml
- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/runconfig/RsProjectTasksRunner.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
- src/test/kotlin/org/rust/cargo/toolchain/CargoCommandLineTest.kt
- src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
> Simplify handing of `--` options

- src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsSelfParameter.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt
- src/main/kotlin/org/rust/lang/core/types/Extensions.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/stdext/Utils.kt
- src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
> Add `isCopy(Ty)` method

- src/main/kotlin/org/rust/cargo/runconfig/command/RunClippyAction.kt
- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
> Simplify run clippy action

- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionDialog.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandlerAction.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsSignatureComponent.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
Partial fixes #1774 
@vlad20012 r?
> TYPE: Extend extract to support return parameter

- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionDialog.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandlerAction.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
> TYPE: Allow expression as last return parameter

- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionDialog.kt
> Fix compiler warnings

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes #1852.
This is my  first contribution. Should I add my name to the `CONTRIBUTORS.txt` file as part of this pull request?
> ANN: Fix E0121 false positive.

- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
> TYPE: Extract function replace unknown types

- intellij-toml/src/main/kotlin/org/toml/lang/TomlFileTypeFactory.kt
> Register Gopkg.lock as a TOML file (GO-4774)

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
> RES: resolve else branch of 'if let' expression correctly

- src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
- src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsPartialParseCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
> Deprecate checkSingleCompletion

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
PR for issue #1888. Currently work in progress.
Tasks:
> [COMP] Semicolon completion in use statements

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Fix another E0121 false positive.

- intellij-toml/README.md
- intellij-toml/src/main/kotlin/org/toml/lang/psi/Psi.kt
> TOML: touch up docs

- src/test/kotlin/org/rust/ide/core/overrideImplement/ImplementMembersFixTest.kt
Follow up to https://github.com/intellij-rust/intellij-rust/pull/1938#issuecomment-339894860.
> WIP: Improve "implement members fix" tests.

- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
> T: Added test for `Iterator::collect` with `_` in path parameter

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/RsExtraSemicolonInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsDivergingTypeInferenceTest.kt
> TY: block with bot expressions has bot type

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
> Fixed #1649

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> Fixed #1743 unknown type should be more priority than `!` type

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Unify.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
> Fixed #1927 Stack Overflow with cyclic type of infinite size

- ARCHITECTURE.md
> ARCHITECTURE.md Spelling gralde -> gradle

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/lang/refactoring/RsNameSuggestions.kt
- src/test/kotlin/org/rust/lang/refactoring/RsIntroduceVariableHandlerTest.kt
Hello,
I made a fix for #1785.
Regards,
Guillaume
> #1785 Fix extract variable for tuple arguments

- .idea/runConfigurations/Run.xml
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
- src/main/kotlin/org/rust/stdext/Collections.kt
- src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
> TY: derive Sized trait impl

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
This fulfills the issue:
https://github.com/intellij-rust/intellij-rust/issues/1692
> (TY): add inference of `impl Trait`

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFix.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt
* check that types of function args and return type have `Sized` trait bound
* add quick fixes: convert to reference and convert to `Box`
> ANN: function args and return type must be Sized

- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/main/kotlin/org/rust/ide/surroundWith/statement/RsWithBlockSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/statement/RsWithForSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/statement/RsWithIfSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/statement/RsWithLoopSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/statement/RsWithWhileSurrounder.kt
- src/main/kotlin/org/rust/ide/surroundWith/utils.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/test/kotlin/org/rust/ide/formatter/RsFormatterLineBreaksTest.kt
- src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
- src/test/resources/org/rust/ide/formatter/fixtures/line_breaks/all.rs
- src/test/resources/org/rust/ide/formatter/fixtures/line_breaks/all_after.rs
closes https://github.com/intellij-rust/intellij-rust/issues/825
closes https://github.com/intellij-rust/intellij-rust/pull/1534
> Keep comments on the first line when reformatting

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsCompositeElement.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Make #2058 work with traits from other cates
> Fix fake path resolution

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
* Support basic specialization
* Fixed complex method pick with deref
* Fixed mutables in cache (again)
> Couple of fixes

- src/main/kotlin/org/rust/lang/core/macros/ExpansionResult.kt
- src/main/kotlin/org/rust/lang/core/macros/LazyStatic.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
- src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/stdext/Collections.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
if_std in futures-rs and failure now works
> MACRO: expand `&item*` pattern

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
- src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
- src/test/resources/org/rust/ide/folding/fixtures/crates.rs
- src/test/resources/org/rust/ide/folding/fixtures/mods.rs
- src/test/resources/org/rust/ide/folding/fixtures/uses.rs
I have implemented some code foldings. Now it can fold repeating items like uses, mods and, crates.
Fulfilled #1939 request.
> Code foldings

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt
- src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
- src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsAnnotatorTestBase.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
* Introduce `RsVisible` interface and implement it for `RsMod`
* Annotate if you try to use private module
* Minor improvement in 'outside of scope' error description (including fix of #2081)
> Module visibility

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsAnnotatorTestBase.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Correctly check access to sibling modules
> Sibling mod visibility

- README.md
> DOC: fix toml directory link

- CONTRIBUTING.md
- src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt
> ACT: implement 'goto type declaration' action

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
Performed proposed refactoring from PR #1901 and thus finally resolving issue #1888.
> [COMP] Refactored LookupElements.kt

- src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Also add some comments to make the code easier to understand.
> Better handle multiple attributes with the same name

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
- src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTest.kt
> INT: Improve auto import

- src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
> Changed timeout for `rustc --print sysroot` from 5 sec to 10.

- CONTRIBUTORS.txt
- src/main/resources/inspectionDescriptions/RsDanglingElse.html
> fix typo in RsDanglingElse.html

- build.gradle.kts
Add to commits only release related changes insetad of all changes in project folder
> GRD: slightly improve 'makeRelease' task.

- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandlerAction.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
> TYPE: Support input parameter for extraction

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandlerAction.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
> TYPE: Correctly extract associated function in trait item #2185

- .travis.yml
- MAINTAINING.md
- build.gradle.kts
- gradle.properties
- intellij-toml/src/main/resources/META-INF/plugin.xml
- src/main/kotlin/org/rust/cargo/util/CargoCommandLineEditor.kt
- src/main/kotlin/org/rust/ide/actions/RsJoinRawLinesHandler.kt
- src/main/kotlin/org/rust/ide/actions/RsNewProjectAction.kt
- src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
- src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
* Update kotlin, IDEA & CLion
* Support 2018.1 IDEs
> Support 2018.1 IDEs

- CONTRIBUTORS.txt
> add my name

- src/main/kotlin/org/rust/ide/intentions/AddElseIntention.kt
Fixed a type in the getText() assignment. "is" -> "this"
> #2215 Resolution

- src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
> RES: correctly resolve modules with 'path' attribute

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/RsTestBase.kt
- src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
// this test was a "fuel" for several previous PRs
> T: assert that all expressions typified in type inference tests

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
> TY: fixed #2129 resolve type vars for pattern matching

- src/main/kotlin/org/rust/cargo/project/CargoToolWindow.kt
> UI: wrap cargo tool window content with scroll view

- intellij-toml/src/main/kotlin/org/toml/lang/TomlFileTypeDetector.kt
- intellij-toml/src/main/resources/META-INF/plugin.xml
> TOML: detect '.cargo/config' as toml file

- src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
> HINT: Remove unnecessary inlay hint in lambda expr

- src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt
- src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt
> TYPE: don't move inner attributes in 'optimize import'

- src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt
- src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt
> TYPE: Support sorting of extern crates

- src/main/kotlin/org/rust/cargo/toolchain/BacktraceMode.kt
- src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable configuration uses default environment.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable producer works for bin.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable producer works for example.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ hyphen in name works.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main fn is more specific than test mod.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main mod and test mod have same specificity.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ meaningful configuration name.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ producer use complete function path.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test configuration uses default environment.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer adds bin name.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for annotated functions.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for files.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for modules.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for root module.xml
This seems to be a more reasonable default!
> Use short backtraces by default

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/formatter/processors/RsSingleImportRemoveBracesFormatProcessor.kt
- src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt
- src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt
- src/test/kotlin/org/rust/ide/formatter/RsSingleImportRemoveBracesFormatProcessorTest.kt
Fixed extra comma deletion while formatting and add my nick to contributors.
> FMT: Fixes #2277 (extra comma deletion)

- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
https://github.com/intellij-rust/intellij-rust/pull/2197#pullrequestreview-95631728
> TYPE: clean up "extract function" refactoring

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
- src/main/kotlin/org/rust/lang/core/types/infer/ProjectionCache.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Snapshot.kt
- src/main/kotlin/org/rust/lang/core/types/infer/SnapshotMap.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Unify.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
- src/test/kotlin/org/rust/lang/core/type/RsSnapshotMapTest.kt
- src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
This PR brings a LARGE optimization (more than x2 on mysq_async test) and opens the possibility to implement associated type bindings (`Iterator<Item=T>`)
> PERF: Fulfillment (type inference) optimization

- src/main/kotlin/org/rust/ide/formatter/processors/RsSingleImportRemoveBracesFormatProcessor.kt
- src/test/kotlin/org/rust/ide/formatter/RsSingleImportRemoveBracesFormatProcessorTest.kt
FMT: Improved braces deletion for use-groups with aliases(see tests).
> FMT: Improved braces deletion for use-groups with aliases

- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
Fixes #2189
Added a test for #2184 works without any changes.
@Undin r?
> Support mutablity of a variable during extraction

- src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsLifetimeParameter.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/MoveTypeConstraintToParameterListIntention/after.rs.template
- src/main/resources/intentionDescriptions/MoveTypeConstraintToParameterListIntention/before.rs.template
- src/main/resources/intentionDescriptions/MoveTypeConstraintToParameterListIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntentionTest.kt
> INT: move type parameter bouds from the where clause to parameter list

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/refactoring/introduceVariable/RsNameSuggestions.kt
- src/main/kotlin/org/rust/openapiext/Testmark.kt
It increases performance up to 20% on `mysq_async` test.
> PERF: better cache macros during resolve

- src/main/kotlin/org/rust/ide/inspections/fixes/import/AutoImportFix.kt
- src/test/kotlin/org/rust/FileTree.kt
- src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt
- src/test/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspectionTest.kt
- src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
* don't import path in use item
* don't highlight references with multiple resolutions
* correctly import items from extern crate
Fixes #2347
> INSP: Auto import improvements

- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotatorTest.kt
Fixes #1950
@Undin r? Any idea for tests?
>  ANN: Move mutable annotation into a own annotator 

- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/implementMembers/impl.kt
- src/test/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandlerTest.kt
> INT: "implement members" quickfix now substitutes generic types

- src/main/kotlin/org/rust/ide/intentions/FlipBinaryExpressionIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/FlipBinaryExpressionIntention/after.rs.template
- src/main/resources/intentionDescriptions/FlipBinaryExpressionIntention/before.rs.template
- src/main/resources/intentionDescriptions/FlipBinaryExpressionIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/FlipBinaryExpressionIntentionTest.kt
> INT: Flip operator of binary expression

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Fixes #1992
Fixes #1897 
Fixes #2162
Also a part of #1806
> Fix issues with `Self` type

- src/main/kotlin/org/rust/ide/presentation/Ty.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
> TY: take into account type arguments when projecting associated types

- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Added some tests for array indexing to ensure that #1806 is really fixed and catch similar problems in future
> T: array indexing

- src/main/kotlin/org/rust/toml/RsTomlCompletionProvider.kt
- src/test/kotlin/org/rust/toml/CargoTomlCompletionContributorTest.kt
Have no idea if it actually works :( WiFi here is garbage :(
> Completion for dev-dependencies in TOML

- intellij-toml/src/main/grammars/TomlLexer.flex
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.toml
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.txt
Shout-out to LALRPOP for detecting this ambiguity statically!
> Fix key-date ambiguity in TOML

- src/main/kotlin/org/rust/ide/presentation/Utils.kt
- src/test/kotlin/org/rust/ide/structure/RsStructureViewTest.kt
> Generic impl presentation in structure view

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
> TY: fixed type inference for binary expressions

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReference.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: Fixed type inference for `Self {}` struct literal

- intellij-toml/src/main/grammars/TomlParser.bnf
- intellij-toml/src/main/kotlin/org/toml/lang/parse/TomlParserUtil.kt
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.toml
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.txt
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/tables.toml
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/tables.txt
> TOML: more IDE-friendly (and completion-fiendly) TOML grammar

- src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/test/kotlin/org/rust/lang/refactoring/RsExtractFunctionTest.kt
> TYPE: Properly pass variables into extracted function

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/ide/inspections/import/ui.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
Take into account extern crate alias while auto import
Fixes #2444
> INSP: extern crate alias

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: Fixed lambda without return

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
> TY: fixed `Self` subst to assoc fns in trait impls for primitives

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
> TY: Fixed try operator

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
> TY&RES: Correctly resolve cmp/eq ops for numerics

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/refactoring/implementMembers/impl.kt
- src/main/kotlin/org/rust/lang/refactoring/implementMembers/ui.kt
- src/test/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandlerTest.kt
> ACT: "Implement members" should honor thе оrder of trait members in the definition

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
> Fix error description

- src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt
- src/test/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspectionTest.kt
`SortImplTraitMembersFix` would not work properly if the `impl`
was missing implementations of one or more members of the trait.
Fixes #2476.
> INSP: Fix "Apply same member order" for incomplete `impls`

- README.md
> DOC: fix timcity link

- src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
- src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
- src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
- src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt
- src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
- src/main/kotlin/org/rust/ide/ui/layout.kt
> UI: split rust settings into sections

- src/main/resources/META-INF/clion-only.xml
> Drop outdated action reference in clion-only.xml

- intellij-toml/src/main/resources/META-INF/plugin.xml
> TOML: support 2018.2

- src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
Currently, we use rust parser directly to parse args of macro call.
But we don't initialize it properly and recent changes in IDEA (https://github.com/JetBrains/intellij-community/commit/e5f1ce24daea81f97f3dae2937684872f73ddf29)
cause NPE because of it.
These changes use similar code with `RustParser#parseLight` to init parser and fix NPE
Fixes #2548
Fixes #2552
> MACRO: fix NPE while macro expansion

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/stdext/Collections.kt
- src/test/kotlin/org/rust/ide/inspections/RsTypeCheckInspectionStdTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Fixes #2482 
Fixes #2460 
Fixes #2440 
Fixes #2514
> TY&RES: fixed method pick logic

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
- src/main/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributor.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer ignores selected files that contain no tests.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for multiple files.xml
> RUN: Add test run configurations when multiple files are selected

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
> Fixed CCE while type inference

- .github/ISSUE_TEMPLATE.md
> DOC: issue template

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Previously we corrupted the cache with (mutable) type variables.
The error was caught by recently added asserts
> Fixed concurrency errors in trait selection

- src/main/kotlin/org/rust/openapiext/ProjectCache.kt
ProjectCache is intensive used in type inference, so this change should speedup type inference in some function after its body change (e.g. completion)
As I see, all current usages of ProjectCache can safely depend on rust structure mod tracker instead of global psi mod tracker
> PERF: use rust structure mod tracker in `ProjectCache`

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsClosuresResolveTest.kt
> TY: Infer closure parameter types from trait object

- src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
- src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
- src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
- src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
- src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
> RUN: add UI option to disable using '--all-target' flag while cargo build/check

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
1. Previous solution have a bug: if module structure changed without
changing of files containing macros, and macro call should be
resolved to another macro, its old expansion may be not invalidated
2. Previous solution have a  performance issue: if we type in some
file containing a macro call, any typing in this file triggers
its re-expansion
> PERF: use rust structure mod tracker to cache macro expansions

- CONTRIBUTING.md
- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/injected/RsRegExpInjector.kt
- src/main/kotlin/org/rust/ide/injected/RsStringLiteralEscaper.kt
- src/main/kotlin/org/rust/ide/spelling/StringLiteralTokenizer.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
- src/main/kotlin/org/rust/lang/utils/RsEscapesUtils.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/lang/utils/RsEscapesUtilsTest.kt
Highlight & analyze regular expressions
Related to #2231
>  LI: provided RegExp language injection into string literals

- src/main/kotlin/org/rust/lang/core/types/Substitution.kt
> PERF: Override equals/hashCode in Substitution

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
> RES: Fixes resolving items imported in crate root

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
Looks like we have a bug in `RsFile#isCrateRoot` method because some users get exceptions from `check(scope.isCrateRoot)`.
But we check that we pass only crate root into `exportedMacros` function.
So let's drop this check, log when argument is nor crate root and return an empty list.
Fixes #2659
> RES: fix exception while macro resolve

- intellij-toml/src/main/grammars/TomlParser.bnf
- intellij-toml/src/main/kotlin/org/toml/lang/parse/TomlParserUtil.kt
- intellij-toml/src/test/kotlin/org/toml/lang/TomlParserTest.kt
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.toml
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.txt
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.toml
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.txt
> TOML&GRAM: Make toml grammar more strict to line breaks

- src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
- src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsMemoryCategorizationTest.kt
> Fix memory categorization of rvalue expressions

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/lang/core/macros/LazyStatic.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
- src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
> Rename ExpansionResult -> RsExpandedElement

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: Fixed call expr with callee of struct without fields type

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsMemoryCategorizationTest.kt
> Add deref adjustments inside inferIndexExprType

- src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
- src/main/kotlin/org/rust/lang/core/types/Kind.kt
- src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
- src/main/kotlin/org/rust/lang/core/types/regions/ReEarlyBound.kt
- src/main/kotlin/org/rust/lang/core/types/regions/Region.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
Small refactoring for Region, Ty, and Kind classes.
Provides ability to check TypeFlag for TypeFoldable.
> TY: TypeFlag checking for TypeFoldable

- src/main/kotlin/org/rust/ide/injected/RsRegExpInjector.kt
> Fixed UI freeze on typing a string literal inside some complex function

- src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
> Use "lang" attribute to find PartialOrd trait

- src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
> RUN: fix project selection

- src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
- src/main/kotlin/org/rust/stdext/Collections.kt
- src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
- src/test/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandlerTest.kt
> MACRO: fixed expansions of a macro with empty group (cfg_if! case)

- src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt
- src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
- src/main/kotlin/org/rust/ide/newProject/RsPackageNameValidator.kt
- src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
- src/test/kotlin/org/rust/ide/newProject/RsProjectNameValidationTest.kt
> PRJ: validate package name while new project creation

- src/main/kotlin/org/rust/ide/intentions/FlipBinaryExpressionIntention.kt
- src/main/resources/intentionDescriptions/RsShowRecursiveMacroExpansionIntention/after.rs.template
- src/main/resources/intentionDescriptions/RsShowRecursiveMacroExpansionIntention/before.rs.template
- src/main/resources/intentionDescriptions/RsShowRecursiveMacroExpansionIntention/description.html
- src/main/resources/intentionDescriptions/RsShowSingleStepMacroExpansionIntention/after.rs.template
- src/main/resources/intentionDescriptions/RsShowSingleStepMacroExpansionIntention/before.rs.template
- src/main/resources/intentionDescriptions/RsShowSingleStepMacroExpansionIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/FlipBinaryExpressionIntentionTest.kt
- src/test/kotlin/org/rust/ide/intentions/RsIntentionDocumentationTest.kt
- src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
* Add documentation for new `Show macro expansion` intentions
* Add text for `FlipBinaryExpressionIntention`
* Improve intention documentation test
> INT: Intention documentation

- src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
- src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt
> Fix NoClassDefFoundError

- src/test/kotlin/org/rust/lang/core/macros/RsErrorChainMacroExpansionTest.kt
- src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
Replaced step by step expansion with recursive
> T: test error-chain macro fully expansion

- src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
- src/test/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspectionTest.kt
> INSP: Fix needless lifetimes inspection

- src/main/grammars/RustParser.bnf
> remove dead code in grammar

- src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
- src/main/kotlin/org/rust/lang/core/types/infer/outlives/FreeRegionMap.kt
- src/main/kotlin/org/rust/lang/core/types/infer/outlives/TransitiveRelation.kt
- src/main/kotlin/org/rust/lang/core/types/regions/ReEmpty.kt
- src/main/kotlin/org/rust/lang/core/types/regions/ReFree.kt
- src/main/kotlin/org/rust/lang/core/types/regions/ReScope.kt
- src/main/kotlin/org/rust/lang/core/types/regions/Region.kt
- src/main/kotlin/org/rust/lang/core/types/regions/Scope.kt
- src/main/kotlin/org/rust/stdext/Collections.kt
- src/test/kotlin/org/rust/lang/RsTestBase.kt
- src/test/kotlin/org/rust/lang/core/type/RsScopeTest.kt
Will be used in the future for region inference and borrow checker.
> TY: Implement scopes and free regions

- src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/ide/inspections/import/AutoImportHintFix.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
> INSP: Unresolved reference inspection and auto import quick fix for trait method references

- src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
Fixes [2778 comment](https://github.com/intellij-rust/intellij-rust/issues/2778#issuecomment-416008917)
> ANN: fixed AddStructFieldsFix for aliased structs

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
> TY: Fixed empty vec![]

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
> TY: fixed iterating over mutable vec

- src/main/kotlin/org/rust/ide/hints/RsDeclarationRangeHandler.kt
- src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/structure/RsStructureViewTest.kt
Refactoring for RsStructureViewModel.
Support for nested items in the structure view model of a function.
Implementation of DeclarationRangeHandler.
The `View | Context Info` feature is provided by the platform using StructureViewModel and DeclarationRangeHandler implementations.
> ACT: Support `Context Info` action

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
- src/test/kotlin/org/rust/lang/core/completion/RsModCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroPathResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
> RES&COMP: resolve and complete paths in include macros

- intellij-toml/src/main/resources/META-INF/plugin.xml
- src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
* Make code compatible with 2018.3 sources
* Drop useless attributes in `plugin.xml` of toml plugin
> 183 preparation

- src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
- src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
- src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
- src/main/resources/postfixTemplates/IterPostfixTemplate/description.html
- src/test/kotlin/org/rust/ide/template/postfix/IterPostFixTemplateTest.kt
> add 'iter' postfix template for iterable expressions

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
> INSP: Fixed wrong trait import suggestion for trait objects

- src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
> T: fixed test (required stdlib)

- src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
> Template `iter`: allow a user to modify loop variable

- src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
> RES: resolve references to extern crate root in 2018 edition

- src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
- src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt
- src/test/kotlin/org/rust/ide/actions/mover/RsItemUpDownMoverTest.kt
- src/test/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMoverTest.kt
- src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt
- src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTestBase.kt
> Add RsStatementUpDownMover

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsPartialParseCompletionTest.kt
> Fix completion for private items

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
> COMP: fix private extern crate completion

- src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
Rust crates contain test/bench/example targets. If they are indexed
they will be shown in completion/resolve. By this commit we
exclude non-lib targets of project dependencies from index and
also exclude "tests" and "benches" dir from stdlib crates by name.
It would be nice to exclude it by target, but we currently
know nothing about stdlib targets.
> RES: exclude non-lib dependency targets from index

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
> RES: correctly resolve paths with explicit extern crate items in 2018 edition

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/test/kotlin/org/rust/ide/inspections/RsTypeCheckInspectionTest.kt
> TY: Fixed wrong disambiguating of hardcoded impls

- src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
- src/main/kotlin/org/rust/lang/refactoring/generateConstructor/GenerateConstructorHandler.kt
- src/main/kotlin/org/rust/lang/refactoring/generateConstructor/ui.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/lang/refactoring/GenerateConstructorTest.kt
> ACT: add 'Rust.GenerateConstructor' action

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspectionTest.kt
> Add deref adjustment to index expr of unknown type

- .travis.yml
- gradle-183.properties
- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
> :arrow_up: nightly rust and IDEA

- src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
- src/test/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspectionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/2844.
> TY: Fix lifetime elision

- CONTRIBUTORS.txt
> Add myself to CONTRIBUTORS.txt

- src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
> MISC: Memory leak #2408

- src/main/kotlin/org/rust/cargo/project/model/AttachCargoProjectAction.kt
- src/main/kotlin/org/rust/cargo/project/model/CargoProjectActionBase.kt
- src/main/kotlin/org/rust/cargo/project/model/DetachCargoProjectAction.kt
- src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt
- src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectAction.kt
also make cargo/project-related actions DumbAware
Closes #2824
> MISC: Show project structure in dump mode #2824

- src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
Suggestions for better controls naming are welcome.
Fixes #2885
> MISC: Excluding radio buttons for "New Project"-Template #2885

- src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
- src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsShortTypeRenderingTest.kt
Let's fix this hell with futures and type hints https://gfycat.com/SmallCarefulDiamondbackrattlesnake
Fixes #2850
Fixes #1874
> Smarter type shortening in type hints

- src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
- src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
> COMP: fix typo in cargo command completion

- src/main/kotlin/org/rust/lang/refactoring/introduceVariable/RsNameSuggestions.kt
- src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
- src/test/kotlin/org/rust/lang/refactoring/RsIntroduceVariableHandlerTest.kt
- src/test/kotlin/org/rust/lang/refactoring/implementMembers/RsNameSuggestionsKtTest.kt
> Fix name suggestions (freshen default name)

- src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
> RES: correctly resolve struct enum variants

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
> INSP: Fixed unresolved trait method if trait is aliased

- src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
- src/main/kotlin/org/rust/stdext/Collections.kt
> Fix NoClassDefFoundError on CLion

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/NestUseStatementsIntention/after.rs.template
- src/main/resources/intentionDescriptions/NestUseStatementsIntention/before.rs.template
- src/main/resources/intentionDescriptions/NestUseStatementsIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
I implemented "NestUseStatementsIntention".
The issue is here https://github.com/intellij-rust/intellij-rust/issues/2577
> INT: Implement "NestUseStatementsIntention"

- src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
- src/main/resources/META-INF/plugin.xml
> MISC: Cargo.toml does not properly open as project in IDEA #2835

- src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/CargoRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/CompositeCargoRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main mod is more specific than test mod.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test fn is more specific than main mod.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for nested modules 1.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for nested modules 2.xml
Fixes https://github.com/intellij-rust/intellij-rust/issues/1252.
> RUN: Fix running tests from line marker

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
> RES: Support paths start with crate name for 2015 edition

- build.gradle.kts
- gradle-183.properties
* Update IDEA & CLion 2018.3
* Update gradle plugins (including kotlin 1.3.0) and dependencies
> GRD: Update dependencies

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeTest.kt
- src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
- src/test/kotlin/org/rust/ide/inspections/RsReassignImmutableInspectionTest.kt
> Make functions with external linkage unsafe

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/2996.
> RUN: Fix first test status under Windows

- src/main/kotlin/org/rust/ide/wordSelection/RsBlockSelectionHandler.kt
- src/main/kotlin/org/rust/ide/wordSelection/RsFieldLikeSelectionHandler.kt
- src/main/kotlin/org/rust/ide/wordSelection/RsGroupSelectionHandler.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/wordSelection/RsBlocksAndBodiesSelectionHandlerTest.kt
- src/test/kotlin/org/rust/ide/wordSelection/RsSelectionHandlerTestBase.kt
> Improve extend selection for function/struct/trait bodies #2973

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
- src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt
- src/test/kotlin/org/rust/cargo/util/CargoArgsParserTest.kt
> RUN: Run single test in debug properly

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/RsTypeCheckInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Take into account tuple size during unification
> TY&ANN: Fixed tuple typecheck

- src/main/kotlin/org/rust/lang/core/types/borrowck/gatherLoans/GatherMoves.kt
- src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
> Fix borrowck wrong move error when deref Box

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/2630.
> RUN: Fix run tests in debug

- src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/BenchRunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/ExecutableRunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench configuration uses default environment.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable configuration uses default environment.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test configuration uses default environment.xml
Fixes https://github.com/intellij-rust/intellij-rust/issues/3022.
> RUN: Take into account the template for "Cargo Command" configurations

- src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
Helps to find bugs in #3059 :)
> T: better tests for resolve cache invalidation

- src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/CargoRunConfigurationProducer.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
- src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3061.
> RUN: Use unique CargoCommandConfigurationType instance

- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
> TY: Assume `Self` is always copyable

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3030.
> RUN: Show stdout for failed tests

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
- src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
- src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
- src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestConsoleProperties.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt
- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3016.
> RUN: Fix debug output and use test runner in debug mode

- src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
> T: more tests for RsResolveCache

- src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
- src/main/kotlin/org/rust/lang/core/types/Extensions.kt
(when the Rust language is injected to another language)
> Fixed cache invalidation in Rust language injection

- src/183/main/kotlin/org/rust/ide/runAnything/CargoRunAnythingHelpGroup.kt
- src/183/main/kotlin/org/rust/ide/runAnything/CargoRunAnythingProvider.kt
- src/183/main/kotlin/org/rust/ide/runAnything/RunAnythingCargoItem.kt
- src/183/main/resources/META-INF/platform-plugin.xml
- src/183/test/kotlin/org/rust/ide/runAnything/CargoRunAnythingProviderTest.kt
- src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/RunClippyAction.kt
- src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
- src/test/kotlin/org/rust/RustProjectDescriptors.kt
- src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/2872.
Examples:
> RUN: Support `Run Anything` action for Cargo

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/runconfig/RsTestRunner.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3100.
> RUN: Properly handle explicit `--no-run`

- src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectAction.kt
> CARGO: enable "Refresh Cargo project" button when toolchain/cargo is OK

- src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
- src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
- src/test/kotlin/org/rust/ide/formatter/RsAutoIndentTest.kt
- src/test/kotlin/org/rust/ide/formatter/RsFormatterLineBreaksTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/2378.
> FMT: Fix if-expressions formatting

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
> Improve AddStructFieldsFix for Vec #3169

- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
- src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsAssocTypeBindingReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsBinaryOpReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsExternCrateReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsLabelReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsLifetimeReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMetaItemReferenceContributor.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsModReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt
- src/main/kotlin/org/rust/toml/CargoTomlKeyReferenceContributor.kt
This is needed for another [PR](https://github.com/intellij-rust/intellij-rust/pull/3145).
It should also improve the completion response time, because now completion variants will appear in batches.
TODO:
* Add completion-based performance tests
> COMP: Provide basic completion via completion contributor

- src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt
- src/test/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntentionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3166.
> INT: Fix remove curly braces intention

- src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
> TY: Fix isMovesByDefault on copyable array

- src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/ChopParameterListIntention/after.rs.template
- src/main/resources/intentionDescriptions/ChopParameterListIntention/before.rs.template
- src/main/resources/intentionDescriptions/ChopParameterListIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/ChopParameterListIntentionTest.kt
> INT: add "Put parameters on separate lines" intention

- src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3191.
> ANN: Fix Edition 2018 keywords annotator

- CONTRIBUTING.md
> DOC: Fix typos in readme

- src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Add tests for various combinations of `mut` and `ref` keywords
in the short and long form.
This tests show some problems around handling of `mut` and `ref` in
struct/enum patterns.
Link to the match ergonomics RFC from the tests, so it is easier
to check what is tested here.
CC #3225
> TY: Add more tests for match ergonomics around `mut` and `ref` keywords

- src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt
> ANN: Fix nested redundant parentheses

- src/main/kotlin/org/rust/ide/inspections/RsWhileTrueLoopInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsWhileTrueLoop.html
- src/test/kotlin/org/rust/ide/inspections/RsWhileTrueLoopInspectionTest.kt
> INSP: Denote infinite loops with 'loop { ... }'

- src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
Replace using of apache common lib with platform code
> Drop redundant code dependency

- src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
- src/test/kotlin/org/rust/lang/core/completion/RsResolveCacheCompletionTest.kt
> COMP: fix cache invalidation for completion

- .travis.yml
- build.gradle.kts
- pretty_printers_tests/Cargo.lock
- pretty_printers_tests/Cargo.toml
- pretty_printers_tests/Settings_linux.toml
- pretty_printers_tests/Settings_macos.toml
- pretty_printers_tests/lldb_batchmode.py
- pretty_printers_tests/src/main.rs
- pretty_printers_tests/src/test_runner.rs
- pretty_printers_tests/tests/rc_arc.rs
- pretty_printers_tests/tests/string.rs
- pretty_printers_tests/tests/tuple.rs
- pretty_printers_tests/tests/vec.rs
- pretty_printers_tests/tests/vec_deque.rs
Implement the test runner for bundled LLDB pretty-printers.
Inspired by [rustc test runner](https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/runtest.rs) and corresponding [debuginfo tests](https://github.com/rust-lang/rust/tree/master/src/test/debuginfo).
> LLDB pretty-printers test runner

- src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt
- src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
- src/main/kotlin/org/rust/ide/refactoring/extraxtExpressionUi.kt
- src/main/kotlin/org/rust/ide/refactoring/extraxtExpressionUtils.kt
- src/main/kotlin/org/rust/ide/refactoring/introduceParameter/RsIntroduceParameterHandler.kt
- src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt
- src/main/kotlin/org/rust/ide/refactoring/introduceParameter/ui.kt
- src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt
- src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/test/kotlin/org/rust/ide/refactoring/RsIntroduceParameterTest.kt
- src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
- src/test/kotlin/org/rust/ide/refactoring/implementMembers/RsNameSuggestionsKtTest.kt
This is implementation of introduce variable option:
> INT Implement introduce parameter feature.

- src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
- src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
> Handle unreachability due to never type in CFG building

- src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
- src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3245.
> TYPE: Provide type hints for shorthands in pat literals

- debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerTypesHelper.kt
> DBG: fix resolveToDeclaration

- prettyPrinters/lookup.py
- prettyPrinters/providers.py
- pretty_printers_tests/tests/os_string.rs
Add `OsString` support.
The [previous PR](https://github.com/intellij-rust/intellij-rust/pull/3075) was closed accidentally.
> Bundled pretty-printer for LLDB: OsString

- src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
- src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/ChopArgumentListIntention/after.rs.template
- src/main/resources/intentionDescriptions/ChopArgumentListIntention/before.rs.template
- src/main/resources/intentionDescriptions/ChopArgumentListIntention/description.html
- src/main/resources/intentionDescriptions/JoinArgumentListIntention/after.rs.template
- src/main/resources/intentionDescriptions/JoinArgumentListIntention/before.rs.template
- src/main/resources/intentionDescriptions/JoinArgumentListIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/ChopArgumentListIntentionTest.kt
- src/test/kotlin/org/rust/ide/intentions/JoinArgumentListIntentionTest.kt
> INT: add "Put arguments on separate lines/one line" intentions

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
> RES: fix Self-qualified path resolve

- src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
- src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
> Fix CFG for if let and while let

- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt
- src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/2203. Relates to https://github.com/intellij-rust/intellij-rust/issues/2622.
> TY: Type inference for generators

- .travis.yml
Also reduce number of jobs to 5
> CI: add name for each matrix job

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Annotate the `yield` keyword as experimental

- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
> T: Cleanup

- build.gradle.kts
- gradle.properties
It should add some kind of order relation between builds
> GRD: introduce `patchVersion` for intellij-rust plugin

- src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
> ACT: Fix rustfmt install action

- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
- src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
> TY: fix type inference of `Self` type inside impl for primitive

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
> INSP: correctly import item inside nested module

- src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
This is a fix for a very rare cases, so it can be classified as something minor/internal
> TY: fix primitive type fallback

- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
> ANN: Fix duplication of error messages from `cargo check`

- src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/3332.
> ANN: Save all documents before `cargo check`

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
- src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
- src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
> INSP: support wildcard reexports in auto import

- CONTRIBUTORS.txt
- toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
- toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
> CARGO: Fix documentation link for renamed dependency

- src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3370.
> ANN: Fix irrefutability check for struct literals

- src/main/kotlin/org/rust/lang/core/psi/ext/RsPatField.kt
- src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
- src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3354.
> TY: Supported box pattern (for struct fields)

- src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
- src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
- src/main/resources/postfixTemplates/DbgPostfixTemplate/after.rs.template
- src/main/resources/postfixTemplates/DbgPostfixTemplate/before.rs.template
- src/main/resources/postfixTemplates/DbgPostfixTemplate/description.html
- src/test/kotlin/org/rust/ide/template/postfix/DbgPostfixTemplateTest.kt
> COMP: add `dbg` postfix completion

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
> TY: add adjustments for str inside binary expr

- src/main/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFix.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFixTest.kt
Fixed version of #3187
Closes #3183
Closes #3187
> ANN: add quickfix to create lifetime parameter from usage

- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
> COMP: support completion from index for enums

- src/main/kotlin/org/rust/ide/actions/ToggleCargoCheckAction.kt
- src/main/resources/META-INF/plugin.xml
(made similar to ToggleInlineHintsAction action)
> ACT: add an action to enable/disable cargo check annotator

- src/main/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributor.kt
- src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
> Fix extra line markers next to syntax errors

- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt
- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
- src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/3293. Relates to https://github.com/intellij-rust/intellij-rust/issues/2622.
> TY: Type inference for async/await

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
- src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3391.
> ANN: Fix irrefutability check for tuple struct literals and nullary enum variants

- src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: consider const pattern not irrefutable

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsTraitImplementation.html
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
- src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Extract some error annotations about trait implementation into separate inspection
> INSP: Trait implementation inspection

- src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
- src/test/kotlin/org/rust/ide/inspections/fixes/AddMutableFixTest.kt
> Process tuple parameters in `Add mut` quick-fix

- src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
> T: fix completion performance test

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
We switched to AST during resolve of a macro call
form expansion of another macro
bors r+
> PERF&MACRO&RES: Fix PSI switch to AST during macro resolve

- src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
See [comment](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000014084/comments/360000019204) for explanation.
> REF: Make member inplace rename available for identifier owners

- src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
- src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
- src/main/resources/postfixTemplates/RefPostfixTemplate/after.rs.template
- src/main/resources/postfixTemplates/RefPostfixTemplate/before.rs.template
- src/main/resources/postfixTemplates/RefPostfixTemplate/description.html
- src/main/resources/postfixTemplates/RefmPostfixTemplate/after.rs.template
- src/main/resources/postfixTemplates/RefmPostfixTemplate/before.rs.template
- src/main/resources/postfixTemplates/RefmPostfixTemplate/description.html
- src/test/kotlin/org/rust/ide/template/postfix/RefPostfixTemplateTest.kt
- src/test/kotlin/org/rust/ide/template/postfix/RefmPostfixTemplateTest.kt
fixes https://github.com/intellij-rust/intellij-rust/issues/3400
> COMP: add `.ref` and `.refm` postifx template

- src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
- src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3128.
Depends on https://github.com/intellij-rust/intellij-rust/pull/3299.
> REF: Rename corresponding item in trait or impls

- src/main/grammars/RustParser.bnf
- src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
- src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
- src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldLookup.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodOrField.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt
Also, enable default insert handler for index-based completion
Fixes #3406
Related to #2174
> COMP: automatically add trait import while trait method completion

- intellij-toml/src/main/kotlin/org/toml/ide/icons/TomlIcons.kt
- intellij-toml/src/main/kotlin/org/toml/lang/psi/ElementTypes.kt
- intellij-toml/src/main/resources/icons/toml-file.svg
- intellij-toml/src/main/resources/icons/toml-file_dark.svg
> TOML: icons for toml files

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
The cache was broken in #3262
Part of #3429
> Fix trait selection cache pollution (was broken in 77016c72d7b20bf62d)

- build.gradle.kts
Return zero error code even tests fail.
Non-zero error code make the corresponding TeamCity builds failed even failed tests are muted
> GRD: Make TeamCity builds green

- README.md
> Add plugin version/download count badges

- src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
- src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt
- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt
Now this setting has "Import out of scope items while completion" name
and affects completion from index too
> COMP: generalize "Add trait imports" setting

- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
TODO add a test for this case
bors r+
> Fixed "completion with autoimport" in doctest injections

- src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
- src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
>  Process orPats during CFG building

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsCondition.kt
- src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
>  Process orPats inside ExprUseWalker

- src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
...that leads to crashes in language injection
> Fixed SpecializedAssertQuickFix produced incorrect PSI

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/InvertIfIntention/after.rs.template
- src/main/resources/intentionDescriptions/InvertIfIntention/before.rs.template
- src/main/resources/intentionDescriptions/InvertIfIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
> INT: Invert If Intention

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
- src/main/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspection.kt
- src/test/kotlin/org/rust/ide/inspections/fixes/AddMutableFixTest.kt
If I understand issue correctly this PR should work for #3277.
> INSP: Provide AddMutableFix for assignment with immutable ref for RsAssignToImmutableInspection 

- src/main/kotlin/org/rust/lang/core/psi/RsPsiTreeChangeListener.kt
- src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
> Fix exception on renaming

- src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckAnnotatorPass.kt
- src/main/kotlin/org/rust/ide/annotator/cargoCheck/RsCargoCheckUtils.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/3466.
> ANN: Cancel cargo check process on any PSI change

- src/main/kotlin/org/rust/ide/actions/RsRunCargoCheckAction.kt
- src/main/kotlin/org/rust/ide/inspections/RsCargoCheckInspection.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsCargoCheck.html
Closes https://github.com/intellij-rust/intellij-rust/issues/773.
Depends on https://github.com/intellij-rust/intellij-rust/pull/3432 and https://github.com/intellij-rust/intellij-rust/pull/3466.
> INSP & ACT: Add cargo check inspection and run cargo check action

- src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
- src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3470.
> INT: Take into account defaulted type parameters during `Implement members`

- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
> CARGO: don't try to setup cargo package module roots if project is already disposed

- src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
- src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
- src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
- src/main/kotlin/org/rust/ide/utils/ExprUtils.kt
- src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
Add the quick fix for "Use of uninitialized variable" error. Includes the refactoring of `AddStructFieldsFix.kt`.
Merge after #3315
> Add "Initialize with a default value" quick fix

- README.md
Replaces [![official JetBrains project](http://jb.gg/badges/official-flat-square.svg)](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub) with [![official JetBrains project](https://jb.gg/badges/official.svg)](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)
> Use the flat JetBrains badge

- gradle-191.properties
It should avoid exception in CLion debugger because of incompatible changes
Closes #3502
> GRD: bump sinceBuild for 191 platform

- src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3524.
> REF: Don't rename tuple fields

- src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
>  T: fix test name

- src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
- src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/3490.
> ACT: Rustfmt now uses correct config file

- src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
- src/main/kotlin/org/rust/openapiext/ProjectCache.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3539.
> ANN: Fix external linter cache

- debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerLanguageSupport.kt
- debugger/src/main/kotlin/org/rust/debugger/lang/RsEvaluator.kt
> DBG: Show variable value by hovering

- src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
- src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
Partial revert of https://github.com/intellij-rust/intellij-rust/pull/3467.
See https://github.com/rust-lang/rust-clippy/issues/3890.
> ANN: Don't try to kill the external linter process on any PSI change

- bors.toml
> CI: turn on appveyor

- src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
> Fixes IndexNotReadyException during indexing #3545

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Fixes false-negative part of #3514
> TY: coerce types in vec! macro expressions

- src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
- src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
- src/main/resources/postfixTemplates/IterPostfixTemplate/before.rs.template
- src/test/kotlin/org/rust/ide/template/postfix/IterPostFixTemplateTest.kt
> COMP: add `for` postfix completion

- src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
- src/test/kotlin/org/rust/ide/inspections/RsDeprecationInspectionTest.kt
Now it doesn't touch ast when possible
> INSP: fix deprecation inspection

- .travis.yml
- build.gradle.kts
- src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
> INSP: Fix deprecation inspection on clion

- gradle-183.properties
- gradle-191.properties
- gradle.properties
Also, make 191 platform default for developing
> GRD: update IDEA & CLion

- src/main/kotlin/org/rust/ide/intentions/RemoveDbgIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/RemoveDbgIntention/after.rs.template
- src/main/resources/intentionDescriptions/RemoveDbgIntention/before.rs.template
- src/main/resources/intentionDescriptions/RemoveDbgIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/RemoveDbgIntentionTest.kt
> INT: Remove dbg!

- src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/DestructureIntention/after.rs.template
- src/main/resources/intentionDescriptions/DestructureIntention/before.rs.template
- src/main/resources/intentionDescriptions/DestructureIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
> INT: Add `Use destructuring declaration` intention

- src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
> Don't affect psi of other languages while renaming

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
> Fix doing large work on EDT during macro expansion

- build.gradle.kts
Previously, we had some hacks to build plugin correctly: we manually copy jar files and plugin xml configuration files from non-root modules to root one to include them into the final plugin archive.
Found out that xml copying is redundant and looks like everything works fine without this action
Copying of jar files breaks test by throwing `ClassNotFoundException` for some modules, especially when you try to run tests with CLion.
Also, we had to add test dependency on `debugger` module in core one to make core tests work with CLion
Now, we copy jar files only while plugin archive creation and don't do it before test running
Should fix tests in #3618
> GRD: fix test running of non root modules

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
- src/main/kotlin/org/rust/stdext/Concurrency.kt
> Fix deadlock in new macro expansion engine

- clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/lang/utils/RsDemangler.kt
- src/test/kotlin/org/rust/lang/utils/RsDemanglerTest.kt
Rewritten from [rustc-demangle](https://github.com/alexcrichton/rustc-demangle).
> RUN: Implement demangler for rustc symbol names

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3351.
> ANN: Fix duplicate parameter name error

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
> RES&MACRO: Fix StackOverflow during macro resolve

- src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
Previously we used ConcurrentHashMap.clear() to clear
a cache. There are 2 problems with this approach:
1. it is slow
2. hash table is never trimmed, so it can take hundreds of megabytes
forever
Found this problem during an investigation of macro expansion performance
> PERF: Clear resolve cache by purging a HashMap

- debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
- src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
> RUN: Fix MSVC toolchain detection on debug

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
- src/main/kotlin/org/rust/lang/core/macros/ReexpandMacrosAction.kt
- src/main/kotlin/org/rust/openapiext/utils.kt
> MACRO: add missing executeUnderProgress

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3536.
>  TY: Fix type inference for fields owners

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
> MACRO: disable code analysis during macro expansion

- src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
> PERF: disable macro duplication check in production

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3585.
> COMP: Show local definitions in top of the completion list

- prettyPrinters/lldb_lookup.py
- prettyPrinters/lldb_providers.py
- prettyPrinters/rust_types.py
- pretty_printers_tests/tests/hash_map.rs
> DBG: Add HashMap/HashSet formatter for lldb

- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3672.
> RUN: Line marker for test with `quickcheck` attribute

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
> COMP: Fix lookup element presentation and priority for tuple field decl

- toml/src/main/kotlin/org/rust/toml/RsTomlKeysCompletionProvider.kt
Add completion for new Cargo.toml keys (and remove some invalid keys)
bors r+
> TOML&COMP: update Cargo.toml completable keys

- .travis.yml
- appveyor.yml
> CI: use rust 1.34 on CI

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
... if switching between projects during macro expansion
bors r+
> Fix macro expansion progress bar hung

- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
> COMP: fix #3694

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> RES&TY: fix Self in struct/enum

- src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
> PERF: use rustStructureModTracker in more places

- src/main/kotlin/org/rust/ide/search/RsFindUsagesHandler.kt
- src/main/kotlin/org/rust/ide/search/RsFindUsagesHandlerFactory.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3613.
> Find usages of the base declaration

- src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
Fixes
```
java.lang.AssertionError: Already disposed: Project (Disposed) sonic
at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:245)
at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:970)
at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:243)
at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:236)
at …
```
> ANN: Check if project is not disposed before setting highlights from external linter to editor

- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
- src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
> Move settings from `misc.xml` to `workspace.xml`

- src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
- src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
- src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
- src/main/kotlin/org/rust/openapiext/Template.kt
- src/main/kotlin/org/rust/openapiext/utils.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3326.
> INT & TYPE: Force user to fill initializers for generated fields

- src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
> Fix possible cache pollution during macro resolve

- src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
> RES&ANN: fix restricted visibility for mod

- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
- src/main/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributor.kt
- src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
- src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/3734.
> RES: Fix navigation to files and targets (in test tool window)

- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoBenchRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt
- src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
- src/main/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributor.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
- src/main/kotlin/org/rust/openapiext/utils.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/BenchRunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer doesn't works for directories inside non-benches source root.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer doesn't works for directories without benches.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for benches source root.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for directories inside benches source root.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer doesn't works for directories inside non-tests source root.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer doesn't works for directories without tests.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for directories inside tests source root.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for project root.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for tests source root.xml
Allows you to run:
* all tests from a Cargo project root
* all tests from a Cargo package root
* all tests in directory under the "tests" source root
* all benches in directory under the "benches" source root
Examples:
Can be merged after https://github.com/intellij-rust/intellij-rust/pull/2998 and https://github.com/intellij-rust/intellij-rust/pull/2956.
> RUN: Run all tests or benches in directory

- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
- src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt
> Mark as excluded workspace `target` dir

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
According to our tests, this increases highlighting performance up to 15%
> PERF: slightly optimize name resolution (better cache)

- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
> COMP: fix completion after tuple field expr

- src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
- src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
> TY: fix TyProjection folding

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
- src/main/kotlin/org/rust/ide/actions/InstallBinaryCrateAction.kt
- src/main/kotlin/org/rust/ide/actions/InstallCargoPackageAction.kt
- src/main/kotlin/org/rust/ide/intentions/RunCargoExpandIntention.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/RunCargoExpandIntention/after.rs.template
- src/main/resources/intentionDescriptions/RunCargoExpandIntention/before.rs.template
- src/main/resources/intentionDescriptions/RunCargoExpandIntention/description.html
Closes https://github.com/intellij-rust/intellij-rust/issues/3701.
> INT: Expand mod with `cargo expand`

- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
> CLEAN: fix typo

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Very necessary for #3640 b/c now macro expansions are often switched to AST and so documents exist.
It's hard to write a test because of concurrent nature of this stuff.
> MACRO: fix nested macro expansion if document is exists for the file

- src/191/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
- src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
> Fix #3764 possible NPE in VFS batch (macro expansion)

- src/main/kotlin/org/rust/ide/folding/RsCodeFoldingOptionsProvider.kt
- src/main/kotlin/org/rust/ide/folding/RsCodeFoldingSettings.kt
- src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
- src/main/kotlin/org/rust/ide/folding/impl/RsCodeFoldingSettingsImpl.kt
- src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
- src/test/resources/org/rust/ide/folding/fixtures/raw_identifiers.rs
Reverts changes from #3759
See https://github.com/intellij-rust/intellij-rust/pull/3759#issuecomment-487634133 for more details
> TYPE: Revert raw identifiers folding

- src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
We should perform expansion and take macro call/def hashes at once
(with a single read lock acquisition), or it can lead to
inconsistent state
> MACRO: fix possible inconsistency between stored expansions and hashes

- intellij-toml/src/main/kotlin/org/toml/lang/psi/TomlPsiFactory.kt
- intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlPsiFactoryTest.kt
1st out of 4 groundwork PRs thanks to which there will be in turn added support for newer crate version intention and an error annotator detecting common mistakes in dependencies. The PRs are divided so that it's 
easier to review them.
Final effect once the groundwork and 2 feature (new version intention, error checking) PRs will be merged:
> PSI: Add TomlPsiFactory

- src/main/kotlin/org/rust/ide/inspections/RsDropRefInspection.kt
- src/main/kotlin/org/rust/ide/inspections/fixes/RemoveRefFix.kt
- src/test/kotlin/org/rust/ide/inspections/RsDropRefInspectionTest.kt
> INSP: Fix false positive for RsDropRefInspection

- src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/FlattenUseStatementsIntention/after.rs.template
- src/main/resources/intentionDescriptions/FlattenUseStatementsIntention/before.rs.template
- src/main/resources/intentionDescriptions/FlattenUseStatementsIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
I believe this closes #2577.
Please feel free to give me your feedback
> INT: Implement "FlattenUseStatementsIntention"

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Detect E0081: Duplicate enum discriminant

- src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
- src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
- src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt
Fixes #3225, fixes #3791, fixes #3776
> TY: fix match ergonomics

- src/main/kotlin/org/rust/lang/core/psi/ext/RsSelfParameter.kt
- src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt
> Fix go-to-declaration (and find usages) for self parameter

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/ReplaceWithStdMemDropFix.kt
- src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceWithStdMemDropFixTest.kt
> ANN: Detect E0040: Explicit destructor call

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
> RES: finally support unified paths (2018 edition)

- src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
> PERF&ACT: fix too slow showing large macro expansions

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Detect E0120: impl Drop for Trait is illegal

- src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
> MACRO: fix "Outdated stub in index" crashes

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Detect E0184: Cannot implement both Copy and Drop

- src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
- src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
> COMP: add completion for deprecated attribute

- src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
> CLEAN: fix RsAbstractable interface

- src/main/kotlin/org/rust/ide/hints/RsParameterInfoHandler.kt
- src/main/kotlin/org/rust/openapiext/utils.kt
> PERF: fix possible UI freezes caused by parameter info popup

- .travis.yml
- src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
- src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
> Update nightly rust & compiler features

- src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedElement.kt
> Add forgotten greenStub

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
- src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestDiffTest.kt
> RUN: swap expected and actual values in test result diff

- src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotatorTest.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3815.
>  ANN&TY: Support postfix await syntax

- src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
- src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
- src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
See
https://internals.rust-lang.org/t/new-style-chocolatey-packages-windows/9890/6
> try to fetch stdlib from sysroot even without rustup

- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
The `https://github.com/rust-lang/rust` project (aka "rustc",
aka "rust-lang/rust") contains stdlib sources inside the project.
Now we locate such sources and do not link external stdlib to
the project. This fixes a lot of bugs when working with
rust-lang/rust project.
> Automatically detect "stdlib" when working with rust-lang/rust project

- src/main/kotlin/org/rust/ide/refactoring/extractFunction/ExtractFunctionParameterTablePanel.kt
- src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt
This PR attempts to improve the Extract method dialog UI.
Related issues: https://github.com/intellij-rust/intellij-rust/issues/2186, https://github.com/intellij-rust/intellij-rust/issues/2183
Right now it fixes an exception that was thrown when an invalid name was used for the name of the function (https://github.com/intellij-rust/intellij-rust/issues/1934).
I also tried to use a simple text field instead of the dropdown list if there are no suggestions to offer, however `NameSuggestionsField` always returns true from `hasSuggestions()` method (which is caused by the way it's used in the dialog), so I'm not sure how to recognize when there are no suggestions (maybe use a different component altogether)?
> REF: improve extract method dialog UI

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
> CLEAN: fix comment

- src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
- src/main/kotlin/org/rust/ide/inspections/checkMatch/RsMatchCheckInspection.kt
- src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
> Fix match check on complex patterns with multiple types

- src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
> RES: ignore atom use items on 2018 edition

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3870.
> INSP: Fix E0069 false positive

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
- src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
- src/main/kotlin/org/rust/lang/core/types/Extensions.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
- src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/3589.
> COMP: Take into account expected expression type on completion

- src/main/kotlin/org/rust/ide/typing/RsBraceMatcher.kt
- src/test/kotlin/org/rust/ide/typing/RsBraceMatcherTest.kt
> TYPE:fix angle brace matching with macro call inside

- src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
- src/main/kotlin/org/rust/lang/core/stubs/index/RsFeatureIndex.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3868.
> Fix feature indexing

- src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
Crate attributes like #![foobar] in doctests was broken in #3857
> LI: fix crate attributes parsing in doctest

- src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
- src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
In this #3827 PR parameter renaming support was added to "Extract function" **dialog**. However, the current implementation of "Extract function" does not perform parameter renaming in the **extracted function** and produces redundantly renamed arguments (on the call site).
This PR fixes it.
> REF: Fix parameters renaming in "Extract function"

- clion/src/192/main/kotlin/org/rust/clion/cargo/CargoBuildConfiguration.kt
- clion/src/192/main/kotlin/org/rust/clion/cargo/CargoBuildConfigurationProvider.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/RsCachingStackElementReader.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/RsProfilerRunner.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/RsSymbolSearcher.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceNavigatableNativeCall.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
- clion/src/192/main/kotlin/org/rust/clion/profiler/perf/RsPerfProfilerProcess.kt
- clion/src/192/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
- clion/src/192/main/kotlin/org/rust/clion/valgrind/RsValgrindRunner.kt
- clion/src/192/main/resources/META-INF/platform-clion-only.xml
> Support profiler and valgrind memcheck in CLion 2019.2

- src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
> CLEAN: replace `!isAssocFn` with `isMethod`

- src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
- src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
- src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectStructure.kt
- src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
- src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
- src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
- src/main/kotlin/org/rust/ide/actions/RustfmtCargoProjectAction.kt
- src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
- src/main/kotlin/org/rust/openapiext/utils.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
...and improve "Reformat File with Rustfmt" action.
Depends on https://github.com/intellij-rust/intellij-rust/pull/3490.
>  ACT: Add "Reformat Cargo Project with Rustfmt" action

- src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
- src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentPopup.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/AddFmtStringArgumentIntention/after.rs.template
- src/main/resources/intentionDescriptions/AddFmtStringArgumentIntention/before.rs.template
- src/main/resources/intentionDescriptions/AddFmtStringArgumentIntention/description.html
- src/test/kotlin/org/rust/ide/intentions/AddFmtStringArgumentIntentionTest.kt
> INT: `Add format string argument` intention

- src/main/kotlin/org/rust/ide/typing/RsAngleBraceHandlers.kt
- src/test/kotlin/org/rust/ide/typing/RsAngleBraceTypedHandlerTest.kt
> TYPE:fix angle brace completion before brace

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/BenchRunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt
- src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt
- src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
- src/test/kotlin/org/rust/ide/lineMarkers/RsLineMarkerProviderTestBase.kt
- src/test/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProviderTest.kt
- src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt
- src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ bench producer works for module declarations.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test mod decl is more specific than main mod.xml
- src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for module declarations.xml
Closes https://github.com/intellij-rust/intellij-rust/issues/3185. Depends on https://github.com/intellij-rust/intellij-rust/pull/3752.
> RUN: Line marker to run tests/benches from mod decl

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
> Do not throw exception when MacroExpansionManager component is loadeing in tests

- CONTRIBUTORS.txt
- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/MakePublicFix.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
> ANN: Make public fix

- src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt
The problem was introduced in #3876
> Fix expression type provider multiselect

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/RemoveAttrFix.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsAttr.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/RemoveAttrFixTest.kt
> ANN: Detect E0084: Enum with no variants can't have repr attribute

- src/main/kotlin/org/rust/ide/search/RsReadWriteAccessDetector.kt
- src/test/kotlin/org/rust/ide/search/RsReadWriteAccessDetectorTest.kt
> Fix ReadWriteAccessDetector struct literal

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
- src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
> TY: fix never type unification

- src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
Now, extension classes shouldn't have other extensions as constructor params
bors r+
> Fix warnings in `MissingToolchainNotificationProvider`

- src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
> RUN: Fix parsing target name in debug

- bors.toml
> CI: increase bors timeout

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/RemoveAttrFixTest.kt
>  ANN: Detect E0518: Inline attribute is allowed only on functions 

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
> ANN: Detect E0118: Can impl only `struct`s, `enum`s and `union`s

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
> RES: Fix unified path & star import priorities

- .idea/runConfigurations/Generate_Parser.xml
- intellij-toml/src/main/grammars/TomlParser.bnf
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.toml
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/keys.txt
- intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/tables.txt
> TOML: Support dot keys

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Part of #3628
The PR is mostly a set of heuristics to make progress bar filling more smooth and uniform.
> MACRO: better progress fraction calculation during macro expansion

- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
- src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
> Fix #3966 Error during macro expansion

- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
> Fix #3891 Non-idempotent computation in RsMacroIndex

- intellij-toml/README.md
> TOML: add plugin download/version badges

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Detect E0322, E0328: Explicit impl for sized and unsize trait

- src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
- src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
- src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
fixed exit points highlighting for :
- try blocks
- async blocks
- caret at `?`
> TYPE:fixed exit points highlighting

- src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
> RES: fix issue #3989

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/3985. Depends on https://github.com/intellij-rust/intellij-rust/pull/3990.
> ANN: Annotate const generics as experimental

- src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
- src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/3985. Depends on https://github.com/intellij-rust/intellij-rust/pull/3990.
>  COMP & RES: Resolve const generics

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
- src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
> TY: Take into account const parameter type

- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/colors/RsColors.kt
- src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
> ANN: Highlight const generics

- src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
- src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
> TY: fix access struct field with associated type

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
- src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
> ANN: Fix E0118 false positive

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> ANN: Detect E0132: Invalid `#[start]` function

- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/colors/RsColors.kt
- src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
- src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
Also:
* improve display names for some colors
* update highlighter demo
Closes #4039
> ANN: separate color for function and method calls

- src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt
- src/test/kotlin/org/rust/ide/intentions/AddFmtStringArgumentIntentionTest.kt
> INT: Handle format macros with destinations in AddFmtStringArgument

- src/main/kotlin/org/rust/ide/typing/RsQuoteHandler.kt
- src/test/kotlin/org/rust/ide/typing/RsQuoteHandlerTest.kt
Solves the same problem and based on #3865. See https://github.com/intellij-rust/intellij-rust/pull/3865#issuecomment-499553783
> TYPE: improve heuristic for quote handler

- src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
- src/main/kotlin/org/rust/ide/colors/RsColors.kt
- src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
- src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
We decided to look at colors refactoring more intently
bors r+
> Revert colors for function/method calls

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
> QFIX: Add option to create a mod file in a subdirectory

- src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
- src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/4019.
> PRJ: Make creation of the project automatically open generated files

- src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
It should fix periodic fails of this test
> T: fix completion auto popup test

- src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
- src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/test/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFixTest.kt
> ANN: add "Create field" quick fix for "No such field" error

- src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
- src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
- src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/3995.
> INT: Fix creation of new module if no corresponding directory exists

- src/main/kotlin/org/rust/ide/intentions/ConvertStructIntentions.kt
- src/main/kotlin/org/rust/ide/refactoring/RsBaseEditorRefactoringAction.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/intentionDescriptions/ConvertToStructIntention/after.rs.template
- src/main/resources/intentionDescriptions/ConvertToStructIntention/before.rs.template
- src/main/resources/intentionDescriptions/ConvertToStructIntention/description.html
- src/main/resources/intentionDescriptions/ConvertToTupleIntention/after.rs.template
- src/main/resources/intentionDescriptions/ConvertToTupleIntention/before.rs.template
- src/main/resources/intentionDescriptions/ConvertToTupleIntention/description.html
Implementation for https://github.com/intellij-rust/intellij-rust/issues/3180#issuecomment-498246594
> INT:make convert struct refactorings available as intentions

- src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
- src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
> Fix never type processing in CFGBuilder

- src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Should fix @cemelo's case in #3780
> Fix an infinite recursion around getBounds

- src/main/kotlin/org/rust/lang/core/types/borrowck/BorrowChecker.kt
- src/main/kotlin/org/rust/lang/core/types/borrowck/CheckLoans.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
> Fix slice destructing processing in borrowck

- src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
- src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
- src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
- src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/4117.
> ANN: Evaluate const enum discriminant

- src/main/kotlin/org/rust/ide/inspections/RsTraitObjectInspection.kt
- src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
- src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitType.kt
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/RsTraitObject.html
- src/test/kotlin/org/rust/ide/inspections/RsTraitObjectInspectionTest.kt
> INSP:added inspection for dyn keyword for trait objects

- src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
> T: commit dependency version

- src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
- src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
- src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
> Fix struct pat processing in borrowck
