META-INF/plugin.xml
src/org/rust/lang/RustFileType.kt
src/org/rust/lang/RustFileTypeFactory.kt
src/org/rust/lang/RustHighlighter.kt
src/org/rust/lang/RustHighlighterFactory.kt
src/org/rust/lang/RustLanguage.kt

* set default extension for rust to ".rs'"
* use proper icon for files
* extract RustHighlighterFactory to a separate file
The last change is a workaround:class not found exception was thrown when Factory was inside RustHighlighter
@alexeykudinkin am I correct that (INF) is infrastructure?

(INF): Fix RustFileType

---

.gitmodules
test/org/rust/lang/core/parser/RustParserCtrsTestCase.kt

Rust language conformance test suite (https://github.com/brson/ctrs) is
added as a submodule to testData.
Parser is checked against the ctrs files and reports
unexpected parsing failures or successes. No PSI comparison is made.
@Atsky, please review.
PS: 3001 files are tested in 4.5 seconds.

(T): add ctrs tests

---

META-INF/plugin.xml
src/org/rust/lang/RustHighlighter.kt
src/org/rust/lang/annotator/RustAnnotator.kt
src/org/rust/lang/colorscheme/RustColors.kt
src/org/rust/lang/core/grammar/rust.bnf

At the moment it only highlights attributes
@Atsky please review.
I'm not sure, where Colors should go, there is a similar class in RustHighlighter.

(INF): add Rust annotator

---

META-INF/plugin.xml
src/org/rust/lang/core/grammar/rust.bnf
src/org/rust/lang/core/psi/impl/mixin/RustFnItemImplMixin.kt
src/org/rust/lang/icons/RustIconProvider.kt
src/org/rust/lang/icons/RustIcons.kt
src/org/rust/lang/structure/RustPsiStructureViewFactory.kt
src/org/rust/lang/structure/RustStructureViewElement.kt
src/org/rust/lang/structure/RustStructureViewModel.kt
src/org/rust/lang/structure/RustStructureViewTreeElement.kt

This adds basic file structure.
The structure is flat and consists of a list of functions and methods, found in the file. It can be enhanced greatly, but even in current the state it helps navigating large files, like `libsyntax/parser/parser.rs` tremendously.  
IconProvider for PSI nodes is added as a side effect. 
I plan to add smoke test for the structure in the next PR.

Basic support for file structure

---

test/org/rust/lang/RustStructureViewTest.kt
testData/structure/functions.rs

Matching is simplistic at the moment: the top level of the structure
view is expanded, the resulting "tree" is dumped to a string and the
names of expected entries are searched for. This should work fine while
we have a flat structure. This should also be resilient to adding more kinds of structure elements.
@Atsky please, review. I'm particularly not sure about `Disposer.dispose` thing, because Kotlin's version does not have one. But if I omit disposing, I get warnings about leaks in console.

(T): smoke test for StructureView

---

src/org/rust/lang/core/grammar/rust.bnf
src/org/rust/lang/core/parser/RustParserUtil.kt
test/org/rust/lang/core/parser/RustParserCtrsTestCase.kt

This is one possible approach to dealing with `no_struct_literal_expr`.  4 more tests pass! :)
When parsing condition in `if/when/match`, certain kinds of
expressions are forbidden. Namely, struct literals (`Foo {i: 92}`) and
block-ending ranges (`1..{42}`). This helps in such situations:
```
if i < Foo {
...
}
for x in 1.. {
...
}
```
This commit adds a boolean flag to the parser, which keeps track of the
context and allows to impose the restrictions without duplicating the
grammar for expressions. Rustc's `libsyntax/parser/parser.rs` handles
the situation in a similar way.
Reference: https://github.com/rust-lang/rfcs/blob/master/text/0092-struct-grammar.md

(PAR): implement `no_struct_literal_expr`

---

src/org/rust/lang/core/grammar/rust.bnf
src/org/rust/lang/core/psi/impl/mixin/RustCondLetExprImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustMatchArmImplMixin.kt
src/org/rust/lang/core/resolve/RustResolveEngine.kt
test/org/rust/lang/core/RustResolveTestCase.kt
testData/resolve/iflet.rs
testData/resolve/match.rs
testData/resolve/whilelet.rs

@Atsky please review.
I hate the explicit forwarding of `visitCondLet` to `visitResolveScope`, but generate `RustVisitor` has the following code
```java
public void visitCondLetExpr(@NotNull RustCondLetExpr o) {
visitRestrictedExpr(o);
// visitResolveScope(o);
}
```
It is understandable (neither of `RestrictedExpr` and `ResolveScope` is a subset of the other), but it still feels ugly.

Resolve match

---

src/org/rust/lang/core/grammar/rust.bnf
src/org/rust/lang/core/psi/impl/mixin/RustScopedLetExprImplMixin.kt
src/org/rust/lang/core/resolve/RustResolveEngine.kt
test/org/rust/lang/core/RustResolveTestCase.kt
testData/resolve/for.rs

The implementation is merged together with if/while let expressions. I renamed `RustCondLetExpr` to `RustScopedLetExpr` because a for loop is a kind of let (binding) expression, but not a conditional one.

Implement resolve in for loops

---

resources/META-INF/plugin.xml
src/org/rust/lang/RustDocumentationProvider.kt
test/org/rust/lang/RustDocumentationProviderTest.kt
testData/documentation/variable1.html
testData/documentation/variable1.rs
testData/documentation/variable2.html
testData/documentation/variable2.rs

This PR adds a veeeery basic implementation of the `DocumentationProvider` interface for local variables and parameters.

Add basic DocumentationProvider implementation

---

src/org/rust/lang/core/grammar/rust.bnf
src/org/rust/lang/core/psi/RustItem.kt
src/org/rust/lang/core/psi/extensions.kt
src/org/rust/lang/core/psi/impl/RustItemImpl.kt
src/org/rust/lang/core/psi/impl/mixin/RustAnonParamImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustLambdaParamImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustLetDeclImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustMatchPatImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustModItemImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustParamImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustPatFieldImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustScopedForDeclImplMixin.kt
src/org/rust/lang/core/psi/impl/mixin/RustScopedLetDeclImplMixin.kt
src/org/rust/lang/core/psi/util/RustPsiUtil.kt
src/org/rust/lang/core/resolve/RustResolveEngine.kt
test/org/rust/lang/core/RustResolveTestCase.kt
testData/resolve/mod_items.rs

This starts resolve for modules and items.
It  relays on the extension method to get `items` out of the `mod`, but it could be trivially removed once the generated `RustModItem` has the necessary method.

Resolve items

---

resources/META-INF/plugin.xml
src/org/rust/lang/spellchecker/LiteralExpressionTokenizer.kt
src/org/rust/lang/spellchecker/RustSpellcheckingStrategy.kt

This only works for comments as of now, but can be extended to work for strings and identifiers as well.

Enable spellchecking for Rust files

---

src/org/rust/lang/highlight/RustHighlighter.kt

This PR simplifies the code in the `RustHighlighter` class by using the expression body syntax and merging two `if` and `when` blocks

Highlighter cleanup

---

resources/META-INF/plugin.xml
src/org/rust/lang/RustSdkType.kt

This PR adds a basic `SdkType` implementation for the Rust language. I guess this can later be used to run specific versions of `rustc` and/or `cargo` for various sorts of tasks.

"Rust SDK" SdkType implementation

---

resources/org/rust/lang/colorscheme/highlighterDemoText.rs
src/org/rust/lang/colorscheme/RustColorSettingsPage.kt

I am somewhat unsure of whether the manual annotating (which needs to be kept in sync with the actual annotator) is the best approach here, but it seems to work.
See #114.

Colorscheme: manually annotate highlighter demo text

---

doc/Usage.md
resources/META-INF/plugin.xml
resources/org/rust/lang/liveTemplates/Rust.xml
src/org/rust/lang/template/RustFileContextType.kt
src/org/rust/lang/template/RustLiveTemplatesProvider.kt

@atsky please review.
This adds a `Rust file` template context, so the user can create her own snippets for Rust. 
This also adds two snippets for printing `p -> println!("")` and for printing a debug representation of value `pd -> println!("{:#?}", )`. The last one is nice, because nobody remembers the cryptic `:#?`syntax for debug pretty printing.

(MISC): add Rust live templates

---

.travis.yml
build.gradle
gradle.properties

`downloadSources Boolean.valueOf(downloadSources)` was essentially a no-op introduced by 0d055fd

Gradle: Fix name collision in IntelliJ plugin configuration

---

src/org/rust/lang/core/resolve/RustResolveEngine.kt
test/org/rust/lang/core/resolve/RustResolveTestCase.kt
testData/org/rust/lang/core/resolve/fixtures/let_cycle1.rs
testData/org/rust/lang/core/resolve/fixtures/let_cycle2.rs

@atsky @alexeykudinkin please review.
This has O(n^2) behaviour for pathalogical cases like `let x = {let x = { let x = ...}}` but I guess it is OK.

(RES): fix resolve of `let x = x`

---

src/org/rust/lang/search/RustFindUsagesProvider.kt

Returning an empty string here will automatically ask the DescriptionProvider, but should prevent the infinite recursion that could happen before.
Resolves #139

FindUsagesProvider: Return empty strings

---

src/org/rust/lang/core/grammar/rust.bnf
src/org/rust/lang/core/psi/util/RustModExtensions.kt
src/org/rust/lang/core/psi/util/RustPsiExtensions.kt
src/org/rust/lang/core/resolve/RustResolveEngine.kt
src/org/rust/lang/intentions/ExpandModule.kt
test/org/rust/lang/core/resolve/RustProjResolveTestCase.kt
testData/org/rust/lang/core/resolve/fixtures/child_mod/child.rs
testData/org/rust/lang/core/resolve/fixtures/child_mod/main.rs
testData/org/rust/lang/core/resolve/fixtures/nested_child_mod/inner/child.rs
testData/org/rust/lang/core/resolve/fixtures/nested_child_mod/main.rs

When we see `mod foo;` we should try to find a file corresponding to
`foo`. It is possible only if a parent module is a directory owner.
A module is a directory owner if it is either
* a crate root
* a nested inline module
* called `mod.rs`
It is an error to have `mod foo;` in a non directory owning module.
The file name for `foo` is (modulo #[path = ] attribute) a directory
name of the parent module plus either `/foo.rs` or `/foo/mod.rs`.
Example 1
```Rust
// file src/main.rs, a crate root
mod foo; // src/foo.rs
mod inner {
mod foo; // src/inner/foo.rs
}
```
Example 2
```Rust
// file src/foo.rs
mod bar; // forbidden
mod inner {
mod foo; // src/inner/foo.rs
}
```
The semantics of `mod foo;` nested inside a function is not fully
specified at the moment: …

(RES): implement child modules resolve

---

src/org/rust/lang/RustFileType.kt
src/org/rust/lang/RustFileTypeFactory.kt
src/org/rust/lang/RustLanguage.kt
src/org/rust/lang/codestyle/RustCodeStyleSettingsProvider.kt
src/org/rust/lang/codestyle/RustLanguageCodeStyleSettingsProvider.kt
src/org/rust/lang/core/RustParserDefinition.kt
src/org/rust/lang/core/lexer/RustTokenType.kt
src/org/rust/lang/core/psi/RustCompositeElementType.kt
src/org/rust/lang/core/psi/impl/RustFileImpl.kt
src/org/rust/lang/module/RustModuleBuilder.kt
src/org/rust/lang/module/RustModuleType.kt
src/org/rust/lang/spellchecker/RustSpellcheckingStrategy.kt
src/org/rust/lang/template/RustFileContextType.kt
src/org/toml/lang/TomlFileType.kt
src/org/toml/lang/TomlFileTypeFactory.kt
src/org/toml/lang/TomlLanguage.kt
src/org/toml/lang/core/lexer/TomlTokenType.kt
src/org/toml/lang/core/parser/TomlParserDefinition.kt
src/org/toml/lang/core/psi/TomlElementType.kt
src/org/toml/lang/core/psi/TomlFile.kt
test/org/rust/lang/core/parser/RustParsingTestCaseBase.kt

This removes *classes* RustLanguage and TomlLanguage and uses objects instead. 
See https://github.com/alexeykudinkin/intellij-rust/issues/144 and https://github.com/alexeykudinkin/intellij-rust/commit/c35874d618d732d39de5558b6842330e65d1f7c3 for motivation. 
@alexeykudinkin @atsky if it is OK, I would like to refactor FileTypes in a similar manner.

(INF): change Language to object instead of a class

---

src/org/rust/lang/core/psi/impl/RustNamedElementImpl.kt
test/org/rust/lang/core/resolve/RustResolveTestCase.kt

The documentation for PsiElement.getTextOffset clearly states:
Returns the offset in the file to which the caret should be placed
when performing the navigation to the element. (For classes implementing
PsiNamedElement, this should return the offset in the file of the
name identifier.)
This condition did not hold w.r.t. RustNamedElement, causing issues such as #112.
The offset in nested module test case is updated accordingly.
Fixes #112.

Implement getTextOffset properly for RustNamedElement

---

src/org/rust/lang/core/psi/impl/RustFileImpl.kt
src/org/rust/lang/core/psi/impl/RustNamedElementImpl.kt
src/org/rust/lang/core/psi/impl/mixin/RustPathPartImplMixin.kt
src/org/rust/lang/core/psi/util/RustModExtensions.kt
src/org/rust/lang/core/psi/util/RustPsiExtensions.kt
src/org/rust/lang/core/resolve/RustResolveEngine.kt
src/org/rust/lang/core/resolve/util/RustResolveUtil.kt
test/org/rust/lang/core/resolve/RustMultifileResolveTestCase.kt
test/org/rust/lang/core/resolve/RustResolveTestCase.kt
test/org/rust/lang/core/resolve/RustResolveTestCaseBase.kt
test/org/rust/lang/core/resolve/RustUseResolveTestCase.kt
testData/org/rust/lang/core/resolve/fixtures/global_path/bar.rs
testData/org/rust/lang/core/resolve/fixtures/global_path/foo.rs
testData/org/rust/lang/core/resolve/fixtures/global_path/lib.rs
testData/org/rust/lang/core/resolve/fixtures/use/view_path.rs

This add resolve for `::foo::bar` paths everywhere and `foo::bar` paths
in `use foo::bar`. It also lays foundation for proper use resolve and
`self::foo`, `super::foo` resolve.
`view_path_part_leftish` is made a distinct subclass of path part. This is necessary to override `isFullyQualified`. The name is way to long for a public PSI node, so I am open for suggestions for a shorter one (`use_path_start` maybe?). The code for determining the crate root and parent module is not strictly correct, but is a good approximation. 
I am also not sure about `getGlobalResolveScopeFor` -> `getCrateRootFor` renaming. I think it is better to stick to Rust specific term in this case. 
@alexeykudinkin @atsky please review

(RES): resolve global paths

---

CONTRIBUTING.md
README.md

I checked the links which I changed, they all work.
I intentionally did not change the travis and gitter links, as I didn't know, if this would brake something.
Further, I removed the FAQ section from README.md as the link pointed to the Github-Wiki for this repository and this seems to be disabled right now.

Changed Github links to use the organization namespace. 

---

src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
src/main/kotlin/org/rust/lang/core/resolve/scope/RustResolveScope.kt

The main part is that instead of threading `visited` set through all of the resolve function, we use a statefull object (`Resolver`).
`RustResolveEngine` now contains only public interface, the implementation is provided via top level private items in the file.

(RES): refactor RustResolveEngine

---

build.gradle
gradle.properties

Ok, I figured out why I was getting `NoSuchMethodError`. Here is the story
IDEA uses a separate class loader for each plugin ([ref](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_class_loaders.html?search=Class)) which loads classes from plugin's lib directory. So in theory it is possible to write a plugin which won't depend on the host IDEA Kotlin version. 
In practice, our plugin distribution does include `kotlin-stdlib` and `kotlin-runtime` jars in the lib directory, so we **are independent** from the Kotlin version bundled with user's IDEA. The user can even uninstall the Kotlin plugin and it won't affect the Rust plugin.
It's all rainbows and unicorns, but why the tests were failing :) ? 
Turns out, the `kotlin-runtime` dependency was not used during the …

(BUILD): upgrade Kotlin to beta3

---

src/main/kotlin/org/rust/ide/navigation/goto/RustClassNavigationContributor.kt
src/main/kotlin/org/rust/ide/navigation/goto/RustNavigationContributorBase.kt
src/main/kotlin/org/rust/ide/navigation/goto/RustSymbolNavigationContributor.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustItemImplMixin.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RustItemIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RustStructOrEnumIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/types/RustEnumItemStubElementType.kt
src/main/kotlin/org/rust/lang/core/stubs/types/RustItemStubElementType.kt
src/main/kotlin/org/rust/lang/core/stubs/types/RustStructItemStubElementType.kt
src/main/resources/META-INF/plugin.xml

This adds goto symbol (any item) and goto class (struct or enum). I faild to find tests for this functions in go/erlang plugin, hence there is no tests. 

(NAV): goto symbol and class

---

STYLE.md

I hate to stop and think if I should use braces with this `if` or not, so I decided to add a style rule for it. Unfortunately I've picked the worst possible one: sometimes you use braces and sometimes you omit them :)
@alexeykudinkin @atsky what do you think?

(DOC): specify `if`s style

---

src/main/resources/org/rust/ide/liveTemplates/Rust.xml

I found this template helpful, using `a` and `ae` live templates for testing. 
If this makes sense for upstream, I might also do another PR for the `debug_` equivalents.

Adds LiveTemplate for assert! and assert_eq!

---

src/main/kotlin/org/rust/ide/typing/RustEnterInLineCommentHandler.kt
src/test/kotlin/org/rust/ide/typing/RustEnterHandlerTest.kt
src/test/resources/org/rust/ide/typing/fixtures/at_file_beginning.rs
src/test/resources/org/rust/ide/typing/fixtures/at_file_beginning_after.rs
src/test/resources/org/rust/ide/typing/fixtures/inside_string_literal.rs
src/test/resources/org/rust/ide/typing/fixtures/inside_string_literal_after.rs

Check whether an end-of-line at caret is actually a whitespace
before moving to a previous element, and do not fail on
whitespace at the beginning of file.
Fixes #185.

Fix NPE in RustEnterInLineCommentHandler

---

src/main/kotlin/org/rust/ide/spellchecker/StringLiteralTokenizer.kt
src/main/kotlin/org/rust/lang/core/lexer/RustLexerUtil.kt
src/main/kotlin/org/rust/lang/utils/RustEscapesUtils.kt
src/test/kotlin/org/rust/ide/spellchecker/RustSpellCheckerTest.kt
src/test/kotlin/org/rust/lang/core/lexer/RustEscapesLexingTestCase.kt
src/test/kotlin/org/rust/lang/utils/RustEscapesUtilsTest.kt
src/test/resources/org/rust/ide/spellchecker/fixtures/string_literals_with_escapes.rs

This PR ports `unescapeRust` extension method from #244. Also, as @matklad suggested, wires it with the spellchecker code, to support Rust-style escape sequences.

Unescaping

---

build.gradle
gradle.properties
src/main/resources/META-INF/plugin.xml

WIP
This does not work yet
* we need to wait until gralde intellij plugin 0.0.41, which will include https://github.com/JetBrains/gradle-intellij-plugin/commit/ab9507d99e06b9965c0f0304ac8daf8c0fda1290
* for [some obscure reason](https://gist.github.com/matklad/9353e40bbc51fb3dd753), it does not work for IDEA 15.0.3. I guess it's better just to wait until 15.0.4

(MISC): update kotlin to 1.0.0

---

src/main/kotlin/org/rust/cargo/CargoConstants.kt
src/main/kotlin/org/rust/cargo/CargoProjectDescription.kt
src/main/kotlin/org/rust/cargo/project/CargoProjectResolver.kt
src/main/kotlin/org/rust/cargo/project/module/RustModuleType.kt
src/main/kotlin/org/rust/cargo/project/module/persistence/CargoModuleTargetsService.kt
src/main/kotlin/org/rust/cargo/project/module/persistence/CargoProjectDataService.kt
src/main/kotlin/org/rust/cargo/project/module/persistence/impl/CargoModuleTargetsServiceImpl.kt
src/main/kotlin/org/rust/cargo/project/module/util/RustCrateUtil.kt
src/main/kotlin/org/rust/cargo/util/PlatformUtil.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/lang/core/resolve/RustMultifileResolveTestCaseBase.kt

This PR adds exact information about modules crate roots. 
The info is available via `CargoModuleTargetsService`, which is a persistent module level service. 
The information is populated after the import from external system via `CargoProjectDataService`. 
The user visible change is that crates with non default layout (like cargo itself) start to resolve.
@alexeykudinkin I may do some tweaks to it tomorrow, but it is generally ready for a review.

(CARGO): introduce CargoModuleTargetsService

---

src/main/kotlin/org/rust/cargo/project/settings/CargoProjectSettings.kt
src/test/java/com/intellij/openapi/externalSystem/test/AbstractExternalSystemTest.groovy
src/test/java/com/intellij/openapi/externalSystem/test/ExternalProjectBuilder.groovy
src/test/java/com/intellij/openapi/externalSystem/test/ExternalSystemImportingTestCase.java
src/test/java/com/intellij/openapi/externalSystem/test/ExternalSystemTestCase.java
src/test/java/com/intellij/openapi/externalSystem/test/ExternalSystemTestUtil.java
src/test/java/com/intellij/openapi/externalSystem/test/README.txt
src/test/java/com/intellij/openapi/externalSystem/test/TestExternalProjectSettings.java
src/test/java/com/intellij/openapi/externalSystem/test/TestExternalSystemExecutionSettings.groovy
src/test/java/com/intellij/openapi/externalSystem/test/TestExternalSystemLocalSettings.groovy
src/test/java/com/intellij/openapi/externalSystem/test/TestExternalSystemManager.groovy
src/test/java/com/intellij/openapi/externalSystem/test/TestExternalSystemSettings.groovy
src/test/java/com/intellij/openapi/externalSystem/test/TestExternalSystemSettingsListener.java
src/test/kotlin/org/rust/cargo/project/CargoImportTestCase.kt
src/test/kotlin/org/rust/cargo/project/CargoImportTestCaseBase.kt

This finally adds tests for importing a Cargo project. 
TestCase class is [copy-pasted](https://upsource.jetbrains.com/idea-ce/file/idea-ce-90d7fa536950e73b47d19aef3c978dfbb89b4d7c/platform/external-system-impl/testSrc/com/intellij/openapi/externalSystem/test/ExternalSystemImportingTestCase.java?nav=0:0:focused), because it is not included in any published IDEA jars :(
The test itself [is a breeze](https://github.com/intellij-rust/intellij-rust/blob/0a3d9c618a4cd3ba462541b8cbb6680ae49bc83b/src/test/kotlin/org/rust/cargo/project/CargoImportTestCase.kt).
It also tests previously untested bits of #259 .
@alexeykudinkin please review.

(T): add tests for cargo import

---

src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/colorscheme/RustColorSettingsPage.kt
src/main/resources/org/rust/ide/colorscheme/highlighterDemoText.rs

Annotator was updated in 14fe4c4.
I'm not sure about names of the new color settings. Only the identifier is highlighted, and only in the declarations, not on every use.

Update RustColorSettingsPage to match annotator changes

---

src/main/kotlin/org/rust/cargo/project/module/util/RustCrateUtil.kt
src/main/kotlin/org/rust/lang/core/psi/util/RustPsiExtensions.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RustModulesIndexExtension.kt
src/test/kotlin/org/rust/cargo/project/CargoLibrariesResolveTestCase.kt

This resolves #271 and #272 by changing `getModule` implementation to return non null value even for elements from libraries.
The test here is very integrated. It literally launches cargo, downloads `rand` from crates.io`, imports project and resolves a reference. 
@alexeykudinkin please review.

(RES): fix resolve of submodules in libraries

---

src/main/kotlin/org/rust/ide/intentions/ExpandModule.kt

Fix #269 
for now `mod.rs` and `src/lib.rs` will not have ExpandModule Intention.

(INTENTION) fix ExpandModule isAvaiable predicate

---

.gitignore
build.gradle
src/test/kotlin/org/rust/RustWithSdkTestCaseBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RustStdlibResolveTestCase.kt

This adds a gradle task to download latest rust sources from rust-lang.org and an sdk aware base test case. 
Rust sources are downloaded only once, when the `test` task is executed for the first time. Their size is 20 mb, so I think we can just always download them.

(T): download rust sources for tests

---

src/main/resources/META-INF/plugin.xml

Fix #232 
* gradle aleardy handle the classpath to kotlin external jars, so there is no need to maintain kotlin jars in two place.
* and the version tag here is also redundent. if we now use gradle and gradle-idea-plugin, version here https://github.com/intellij-rust/intellij-rust/blob/master/gradle.properties#L11 will override the version tag in `plugin.xml`, reference to https://github.com/ignatov/intellij-erlang/blob/master/plugin/resources/META-INF/plugin.xml#L21, this is also tested use my tiny plugins.

(PLUGIN) remove redundent tags

---

src/main/kotlin/org/rust/cargo/commands/Cargo.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/forms/CargoRunConfigurationEditorForm.form
src/main/kotlin/org/rust/cargo/runconfig/forms/CargoRunConfigurationEditorForm.kt

This PR is to run cargo with environment variables, ex. `RUST_LOG` for `env_logger`.
It adds two ui components:
- `Environment variables` field on the run config dialog
- `Environment Variables` dialog on clicking a `...` button

(RUNCONFIG) Show env vars dialog, and run cargo with env vars

---

src/main/kotlin/org/rust/lang/core/grammar/rust.bnf
src/main/kotlin/org/rust/lang/core/psi/impl/RustBinaryExprExternalTokens.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustBinaryExprImplMixin.kt

These accessors disappeared in #325. Now they're back

(PSI): add missing accessors for tokens created by collapsing

---

src/main/kotlin/org/rust/lang/core/grammar/rust.bnf

This forces grammar kit to generate proper accessors for expresisons.
Before:
```Java
public interface RustIfExpr extends RustExpr {
@NotNull
List<RustBlock> getBlockList();
@Nullable
RustExpr getExpr(); // this is the `then` branch, condition is missing
@Nullable
PsiElement getElse(); 
@NotNull
PsiElement getIf();
}
public interface RustParenExpr extends RustExpr {
@NotNull
PsiElement getLparen();
@NotNull
PsiElement getRparen();
}
```
After:
```Java
public interface RustIfExpr extends RustExpr {
@NotNull
List<RustBlock> getBlockList();
@NotNull
List<RustExpr> getExprList();
@Nullable
PsiElement getElse();
@NotNull
PsiElement getIf();
}
public interface RustParenExpr extends RustExpr {
@Nullable
RustExpr getExpr();
@NotNull
PsiElement getLparen();
@NotNull
PsiElement getRparen();
}
``` …

(GRAM): force accessor generation

---

src/main/kotlin/org/rust/ide/formatter/RustSpacing.kt
src/test/resources/org/rust/ide/formatter/fixtures/spacing.rs
src/test/resources/org/rust/ide/formatter/fixtures/spacing_after.rs

```rust
extern crate std     as ruststd;
```
was't fixed

(FMT): improve spacing for extern crate items

---

src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoProjectWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoProjectWorkspaceListener.kt
src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoProjectWorkspaceImpl.kt
src/main/kotlin/org/rust/cargo/util/ModuleUtil.kt
src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
src/main/kotlin/org/rust/cargo/util/TasksUtil.kt
src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectAction.kt
src/main/kotlin/org/rust/lang/utils/Utils.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/cargo/toolchain/CargoProjectResolveTestCase.kt
src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RustPackageLibraryResolveTestCase.kt

1. Made module-component instead of a service (as soon as it gets a state, it should not be service anymore).
2. Killed persistence and made it transparent one-directional proxy of the `Cargo.toml` project-workspace.
3. Refactored some concurrency issues (and hopefully didn't introduced new ones).

`CargoProjectWorkspace` refactoring

---

src/main/kotlin/org/rust/lang/core/psi/RustNamedElement.kt
src/main/kotlin/org/rust/lang/core/psi/RustQualifiedReferenceElement.kt
src/main/kotlin/org/rust/lang/core/psi/impl/RustFile.kt
src/main/kotlin/org/rust/lang/core/psi/impl/RustNamedElementImpl.kt
src/main/kotlin/org/rust/lang/core/psi/impl/RustStubbedNamedElementImpl.kt

Make `nameElement` an implementation detail, because it is one.
https://github.com/intellij-rust/intellij-rust/issues/360#issuecomment-215733855

(PSI): refactor RustNamedElement

---

src/main/kotlin/org/rust/ide/documentation/RustDocumentationProvider.kt
src/main/kotlin/org/rust/lang/core/grammar/rust.bnf
src/main/kotlin/org/rust/lang/core/psi/RustNamedElement.kt
src/main/kotlin/org/rust/lang/core/psi/impl/RustFile.kt
src/main/kotlin/org/rust/lang/core/psi/impl/RustNamedElementImpl.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustImplMethodImplMixinMember.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustItemImplMixin.kt

Implements quick documentation in the Documentation Provider by adding a read-only property `documentation: String?` on `RustNamedItem`. This is not _quite_ the right way to go about implementing this, but it is robust enough that it works over all resolved items.
The Markdown parser available in the IntelliJ API is not quite suitable for formatting the documentation string. It does not properly handle the HTML entity codes necessary to provide space indentation in code blocks, nor does it handle things like strikethrough.
A continued improvement would be to provide the full declaration at the top of the documentation text (i.e. instead of just the name, show `pub fn the_function(t: isize) -> isize`) for functions, and visibility for traits structs and enums.
Fixes #370

Quick documentation support for resolved items.

---

src/test/kotlin/org/rust/ide/documentation/RustDocumentationProviderTest.kt
src/test/kotlin/org/rust/ide/documentation/RustQuickDocumentationTest.kt

These tests failed on Windows because `assertThat(actual).isEqualTo(expected)` doesn't differentiate between `\n` and `\r\n`

(T, MISC): fix bad eol handling

---

src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustPathImplMixin.kt
src/test/kotlin/org/rust/lang/core/resolve/RustResolveTestCase.kt
src/test/resources/org/rust/lang/core/resolve/fixtures/self_type.rs

This adds a resolve test a a way to trigger the assertion, but it seems that actually implementing resolve for Self right now is hard, so the test just checks for Self not resolving. If this is not desirable, I can drop the test altogether.

(PSI): Fix assertion related to Self type in impls

---

src/main/kotlin/org/rust/lang/core/resolve/indexes/RustModulesIndex.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RustModulesIndexExtension.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoProjectResolveTestCase.kt

Module index stores a mapping from names to mod_decls. Each mod decl is
represented as an offset in the file.
Finding a super module for a given file is a two step process.
First, mod_decl candidates are found in the index based on their
names (this may give false positives).
Then, each candidate is resovled and if it resolves to the target
file (modulo usual complication with the `origianlFile` for completion),
then it is the answer.
closes #421 
Looks like I have not hit a roadblock. Tests pass and looks like it actually works :) 

(RES): change ModuleIndex algorithm

---

src/main/kotlin/org/rust/ide/actions/smartenter/SemicolonFixer.kt
src/main/kotlin/org/rust/lang/core/grammar/rust.bnf
src/test/kotlin/org/rust/ide/actions/smartenter/RustSmartEnterProcessorTest.kt
src/test/resources/org/rust/ide/actions/smartenter/fixtures/fix_call_in_stmt.rs
src/test/resources/org/rust/ide/actions/smartenter/fixtures/fix_call_in_stmt_after.rs
src/test/resources/org/rust/ide/actions/smartenter/fixtures/fix_match_in_let.rs
src/test/resources/org/rust/ide/actions/smartenter/fixtures/fix_match_in_let_after.rs

Smart enter action did bogus things in `fix_match_in_let.rs` test case, so I simplified/fixed the implementation and added some tests.
The new implementation uncovers an interesting question: should a smart enter action in Rust always insert a semicolon when used for the last expression in a block? I think that it should, and the previously existing tests already require this behavior.

Improve SemicolonsFixer in smart enter action

---

src/main/kotlin/org/rust/lang/core/types/RustStructType.kt

For example, see [syntax index](https://doc.rust-lang.org/book/syntax-index.html) for `impl` keyword.

(MISC): Impl blocks without traits are inherent, not inherited

---

src/main/kotlin/org/rust/ide/hints/RustExpressionTypeProvider.kt

With this change, Ctrl+Shift+P works nicely for me. Unfortunately, I'm not sure how to write a test.
Collecting parent expressions until an item boundary makes more sense than doing the opposite.
`escapeXml` call is needed due to `getInformationHint` result being interpreted as HTML, so `<unknown>` now displays properly.

(IDE): fix type info hints provider

---

src/main/kotlin/org/rust/ide/completion/DeriveCompletionProvider.kt
src/main/kotlin/org/rust/ide/completion/RustCompletionContributor.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/completion/RustDeriveCompletionTest.kt
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/complete_on_enum.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/complete_on_enum_after.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/complete_on_struct.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/complete_on_struct_after.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_already_derived.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_already_derived_after.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_inner_attr.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_inner_attr_after.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_non_derive_attr.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_non_derive_attr_after.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_on_fn.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_on_fn_after.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_on_mod.rs
src/test/resources/org/rust/ide/completion/fixtures/derive_traits/doesnt_complete_on_mod_after.rs

This PR adds autocompletion for derivable traits.  It's pretty naive right now, only omitting suggestions for traits that have already been specified in the `derive` attribute.  Eventually, I would like it to omit suggestions for traits that can't be derived (not suggesting `Copy` for a struct that has non-Copy fields, for example), and traits that have already been manually implemented.

(COM): Add derivable trait completion

---

CONTRIBUTING.md
build.gradle
src/test/kotlin/org/rust/Performance.kt
src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
src/test/kotlin/org/rust/lang/core/parser/RustParserPerformanceTest.kt

This adds the first performance test. The test simply executes the parser on the compiler's source code.

(T): use rust sources to test parser performance

---

src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/highlight/syntax/RustHighlighter.kt
src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
src/test/resources/org/rust/ide/annotator/fixtures/attributes.rs

Before:
After:
Small tweak but makes attributes more appealing to me :smile:

(HIGHLIGHTER): re-highlight literals in attributes

---

doc/Features.md

I believe this is the default shortcut for symbol search on windows.

(DOC): Fix find symbol shortcut

---

src/main/kotlin/org/rust/lang/core/grammar/rust.bnf

`RustMacroItemElement` declares a `getOuterAttrList()`, it should really just extend `RustOuterAttributeOwner`.  This is my naive attempt to do this.  It's a WIP because I still need to figure out how to make `RustMacroItemElement` not declare its own `getOuterAttrList()` method.
This is a generalization I need for [this](https://github.com/intellij-rust/intellij-rust/pull/486) PR.

[WIP] (PSI): Make RustMacroItemElement extend RustOuterAttributeOwner

---

src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt

Eg: cargo 0.10.0 (10ddd7d 2016-04-08)
Defaults to stable if missing.

Fix cargo version regex to support missing stable or nightly.

---

src/main/kotlin/org/rust/ide/folding/RustFoldingBuilder.kt
src/test/kotlin/org/rust/ide/folding/RustFoldingTestCase.kt
src/test/resources/org/rust/ide/folding/fixtures/block_comment.rs
src/test/resources/org/rust/ide/folding/fixtures/macro_brace_arg.rs
src/test/resources/org/rust/ide/folding/fixtures/match_expr.rs
src/test/resources/org/rust/ide/folding/fixtures/use_glob_list.rs

Couple of improvements to folding.
* Now using a recursive visitor. This should have much higher performance than using a find-all operation for every kind of fold possible on every edit.
* A few more foldables.
* Block comments fold with appropriate fold indicator.
Future improvements could include folding up all attributes in a block (doc comments included), various argument-like elements, use blocks.

Improve folding

---

src/main/kotlin/org/rust/ide/intentions/AddCurlyBracesIntention.kt
src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt
src/main/kotlin/org/rust/lang/core/psi/RustElementFactory.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/intentionDescriptions/AddCurlyBracesIntention/after.rs.template
src/main/resources/intentionDescriptions/AddCurlyBracesIntention/before.rs.template
src/main/resources/intentionDescriptions/AddCurlyBracesIntention/description.html
src/main/resources/intentionDescriptions/RemoveCurlyBracesIntention/after.rs.template
src/main/resources/intentionDescriptions/RemoveCurlyBracesIntention/before.rs.template
src/main/resources/intentionDescriptions/RemoveCurlyBracesIntention/description.html
src/test/kotlin/org/rust/ide/intentions/AddCurlyBracesIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntentionTest.kt
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_alias.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_alias_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_extra.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_extra_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_longer.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_longer_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_simple.rs
src/test/resources/org/rust/ide/intentions/fixtures/add_curly_braces/add_curly_braces_simple_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_alias.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_alias_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_extra.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_extra_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_longer.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_longer_after.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_simple.rs
src/test/resources/org/rust/ide/intentions/fixtures/remove_curly_braces/remove_curly_braces_simple_after.rs

Changes `use std::ptr;` to `use std::{ptr};` and back.

Intentions to add/remove curly braces on singleton imports

---

src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
src/test/kotlin/org/rust/ide/formatter/RustFormatterTestCase.kt
src/test/resources/org/rust/ide/formatter/fixtures/issue569.rs
src/test/resources/org/rust/ide/formatter/fixtures/issue569_after.rs

(FMT): add spacing rules for lifetime lists in polybounds

---

.travis.yml
appveyor.yml
src/main/kotlin/org/rust/cargo/commands/Cargo.kt
src/main/kotlin/org/rust/ide/actions/RustFmtFileAction.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/cargo/commands/CargoFmtTest.kt
src/test/resources/org/rust/cargo/commands/fixtures/fmt/hello/Cargo.toml
src/test/resources/org/rust/cargo/commands/fixtures/fmt/hello/src/main.rs

Fixes #256 
@matklad hey,  it's been a while since our last discussion about this issue, i think i may pick it up and fix it again. i update the code use `RustToolchain` and the reformat action behaviors alright. so there still emerge the question that should i call `rustfmt` command directly just as your last comment in the deprecated PR or `cargo fmt` is just fine now, cause the version of `rustfmt` is bumped up from `0.3.0` to `0.5.0`.
and `multirust` has been placed with `rustup`, so maybe the exit code problem may not bother us any longer right?
btw, `RustToolchain` abstraction layer is such a excellent idea 😄

(ACTION) add rustfmt reformat file action

---

src/main/kotlin/org/rust/ide/inspections/duplicates/RustDuplicateInspectionTool.kt
src/main/kotlin/org/rust/ide/inspections/duplicates/RustDuplicateStructFieldInspection.kt
src/main/kotlin/org/rust/ide/inspections/duplicates/RustDuplicateTraitConstantInspection.kt
src/main/kotlin/org/rust/ide/inspections/duplicates/RustDuplicateTraitMethodInspection.kt
src/main/kotlin/org/rust/ide/inspections/duplicates/RustDuplicateTraitTypeInspection.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RustDuplicateTraitConstant.html
src/main/resources/inspectionDescriptions/RustDuplicateTraitMethod.html
src/main/resources/inspectionDescriptions/RustDuplicateTraitType.html
src/test/kotlin/org/rust/ide/inspections/RustInspectionsTest.kt
src/test/resources/org/rust/ide/inspections/fixtures/duplicate_trait_constant.rs
src/test/resources/org/rust/ide/inspections/fixtures/duplicate_trait_method.rs
src/test/resources/org/rust/ide/inspections/fixtures/duplicate_trait_type.rs

Addresses #542 
Added `RustDuplicateInspectionTool` to facilitate the creation of inspections to find duplicate occurrences. 
Rewrote`RustDuplicateStructFieldInspection` to extend `RustDuplicateInspectionTool`.
Added inspections for duplicate trait methods, constants, and associated types (respectively `RustDuplicateTraitMethodInspection`, `RustDuplicateTraitConstantInspection`, and `RustDuplicateTraitConstantInspection`).
Feedback is very much appreciated.

(INSP): Add duplicate trait item inspections

---

README.md

Now that the IntelliJ family has a common year based versioning system, update the README to make it simpler for new people to know that all 2016+ versions are supported.

Make Compatible IDEs section clearer

---

src/main/kotlin/org/rust/ide/template/RustContextType.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/org/rust/ide/liveTemplates/other.xml
src/main/resources/org/rust/ide/liveTemplates/test.xml
src/test/kotlin/org/rust/ide/template/RustLiveTemplatesTest.kt
src/test/resources/org/rust/ide/template/fixtures/attribute.rs
src/test/resources/org/rust/ide/template/fixtures/attribute_after.rs

The live templates "macro", "main", "tfn" and "tmod" are enabed
in most areas of a rust file.
Disable this live templates inside attributes where they are not useful.
Fixes #634

(SNIPPETS): Do not offer live templates in attributes

---

src/main/kotlin/org/rust/ide/typing/RustEnterInStringLiteralHandler.kt
src/test/kotlin/org/rust/ide/typing/RustTypingMiscTests.kt
src/test/kotlin/org/rust/ide/typing/RustTypingTestCaseBase.kt
src/test/kotlin/org/rust/lang/RustTestCaseBase.kt

It's important to remember that `HighlighterIterator#getTokenType()` for empty document throws IndexOutOfBounds exception.
fix #680

(EDT): check offset validity

---

src/main/kotlin/org/rust/ide/typing/RustQuoteHandler.kt
src/test/kotlin/org/rust/ide/typing/RustQuoteHandlerTest.kt
src/test/resources/org/rust/ide/typing/quoteHandler/fixtures/double_quote_in_raw_literal.rs
src/test/resources/org/rust/ide/typing/quoteHandler/fixtures/double_quote_in_raw_literal_after.rs
src/test/resources/org/rust/ide/typing/quoteHandler/fixtures/single_quote_in_raw_literal.rs
src/test/resources/org/rust/ide/typing/quoteHandler/fixtures/single_quote_in_raw_literal_after.rs

I decided not to complete quotes inside, as it might be cumbersome sometimes, also checked out what does PyCharm do in `"""..."""` literals and it's also not completing quotes inside.
fix #687

(EDT): fix quote completion in raw literals

---

src/main/kotlin/org/rust/ide/icons/RustIcons.kt
src/main/kotlin/org/rust/ide/structure/RustConstTreeElement.kt
src/main/kotlin/org/rust/ide/structure/RustModTreeElement.kt
src/main/kotlin/org/rust/ide/structure/RustStaticTreeElement.kt
src/main/kotlin/org/rust/ide/structure/RustStructureViewModel.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustConstItemImplMixin.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustStaticItemImplMixin.kt
src/test/kotlin/org/rust/ide/structure/RustStructureViewTest.kt
src/test/resources/org/rust/ide/structure/fixtures/consts.rs
src/test/resources/org/rust/ide/structure/fixtures/consts.txt
src/test/resources/org/rust/ide/structure/fixtures/statics.rs
src/test/resources/org/rust/ide/structure/fixtures/statics.txt

This fix adds information about constants and static values to the Project Structure window. They are displayed as bindings with the final and static markers respectively:

Display consts and statics in the Project Structure window

---

src/main/kotlin/org/rust/ide/utils/RustModTabTitleProvider.kt
src/main/resources/META-INF/plugin.xml

Overview
===
In order to help figure users understand what module file they're working in, this PR forces the editor to _qualify_ the tab name.
Previously, a tab for a module file would simply display `mod.rs`. This has been changed to include the parent directory (e.g. `foo/mod.rs`).
Addresses #696 
Technical Details
===
Created an concrete implementation of `EditorTabTitleProvider` for module files and registered it with the plugin.
When providing a tab title, we check to see if we are using a rust file and if that file is a module. If that's the case, we just pull in the parent directory's name and separate them with a forward slash.

(MISC): Qualify mod.rs files with parent dir name

---

src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt

IDEA uses `familyName` as the title of an intention in the Preferences window. `DemorgansLawIntention` returns the `text` field as its family name. The problem is that the value of the `text` property is dynamic. It depends on the last performed code analysis and can even be empty when no suitable piece of code is found for the intention. Thus, the intention is displayed under different titles and sometimes even with no title at all.
The PR fixes the problem by providing the DeMorgan's Law intention with a constant family name.

(MISC) DeMorgan intention title fix

---

src/main/kotlin/org/rust/ide/inspections/RustDoubleNegInspection.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RustDoubleNeg.html
src/test/kotlin/org/rust/ide/inspections/RustDoubleNegInspectionTest.kt

Inspection that is an analogue of Clippy's [double_neg](https://github.com/Manishearth/rust-clippy/wiki#double_neg) lint. Catches expressions of the form `--x` which are no-op in Rust.

(MISC) Double Negation inspection

---

src/main/kotlin/org/rust/ide/inspections/RustMissingElseInspection.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RustMissingElse.html
src/test/kotlin/org/rust/ide/inspections/RustMissingElseInspectionTest.kt

A partial analogue of the Clippy's [suspicious_else_formatting](https://github.com/Manishearth/rust-clippy/wiki#suspicious_else_formatting) inspection. Detects `if`-statements with potentially missing `else`s. A quick fix adds an `else` to the `if`.

(INSP) Missing Else inspection

---

src/main/kotlin/org/rust/ide/inspections/RustDanglingElseInspection.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RustDanglingElse.html
src/test/kotlin/org/rust/ide/inspections/RustDanglingElseInspectionTest.kt

A partial analogue of the Clippy's [suspicious_else_formatting](https://github.com/Manishearth/rust-clippy/wiki#suspicious_else_formatting) inspection. Detects `else if`s that are separated by new lines:
if (cond) {
} else
if (another_cond) {
}
The inspection provides quick fixes for removing `else` and for joining `else if`.

(INSP) Dangling Else inspection

---

src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/RegexpFileLinkFilter.kt
src/main/kotlin/org/rust/cargo/runconfig/RustBacktraceFilter.kt
src/main/kotlin/org/rust/cargo/runconfig/RustConsoleFilter.kt
src/main/kotlin/org/rust/cargo/runconfig/RustPanicFilter.kt
src/test/kotlin/org/rust/cargo/runconfig/HighlightFilterTestBase.kt
src/test/kotlin/org/rust/cargo/runconfig/RustBacktraceFilterTest.kt
src/test/kotlin/org/rust/cargo/runconfig/RustConsoleFilterTest.kt
src/test/kotlin/org/rust/cargo/runconfig/RustPanicFilterTest.kt

I've added source code links for panics and stack backtraces output the same way they are added to the compiler messages now.
In this outuput:
thread 'main' panicked at 'something went wrong', src/main.rs:24
stack backtrace:
1:        0x10df17d88 - std::sys::backtrace::tracing::imp::write::hb03a0f85d9cccd1b
2:        0x10df1983f - std::panicking::default_hook::{{closure}}::h945d25329ef3fdd6
3:        0x10df18dd5 - std::panicking::default_hook::hc98de28314f7e4d1
4:        0x10df19326 - std::panicking::rust_panic_with_hook::hf47d6a84575c96f5
5:        0x10df11f33 - std::panicking::begin_panic::hc373b7d24bec0770
6:        0x10df121e9 - ptest::main::h2cd7a4ff8d266cce
at src/main.rs:24
7:        0x10df19dfa - __rust_maybe_catch_panic
8:        0x10df18916 - …

(MISC) Source code links in panics and stacktraces

---

src/main/kotlin/org/rust/ide/inspections/RustNamingInspection.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RustArgumentNaming.html
src/main/resources/inspectionDescriptions/RustAssocTypeNaming.html
src/main/resources/inspectionDescriptions/RustConstNaming.html
src/main/resources/inspectionDescriptions/RustEnumNaming.html
src/main/resources/inspectionDescriptions/RustEnumVariantNaming.html
src/main/resources/inspectionDescriptions/RustFieldNaming.html
src/main/resources/inspectionDescriptions/RustFunctionNaming.html
src/main/resources/inspectionDescriptions/RustLifetimeNaming.html
src/main/resources/inspectionDescriptions/RustMacroNaming.html
src/main/resources/inspectionDescriptions/RustMethodNaming.html
src/main/resources/inspectionDescriptions/RustModuleNaming.html
src/main/resources/inspectionDescriptions/RustStaticConstNaming.html
src/main/resources/inspectionDescriptions/RustStructNaming.html
src/main/resources/inspectionDescriptions/RustTraitNaming.html
src/main/resources/inspectionDescriptions/RustTypeAliasNaming.html
src/main/resources/inspectionDescriptions/RustTypeParameterNaming.html
src/main/resources/inspectionDescriptions/RustVariableNaming.html
src/test/kotlin/org/rust/ide/inspections/NamingNotationsTest.kt
src/test/kotlin/org/rust/ide/inspections/RustNamingInspectionTest.kt

A set of inspections that match the `rustc`'s lints `non_snake_case`, `non_camel_case_types` and `non_upper_case_globals` with the following minor differences:
- Associated constants are not inspected (they are experimental in Rust and not supported by the plugin so far, if I understand correctly)
- Associated types are inspected while `rustc` ignores them when checking names
- The inspections sometimes offer better renaming options (`fooBar` &rarr; `FooBar` instead of `fooBar` &rarr; `Foobar` in `rustc`)
I've extracted separate inspections for every element type (the same way it's done in Java) because it will help to adjust inspections with higher level of granularity after improvements (see below).
Further improvements I'm thinking of:
- Analyze `#[allow(...)]` attributes to suppress …

(INSP) Naming Convention inspections

---

src/main/kotlin/org/rust/ide/inspections/RustNamingInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt
src/test/kotlin/org/rust/ide/inspections/RustNamingInspectionTest.kt

I've implemented the Rename fix for the Naming Convention inspections. It renames the element to the suggested name. The next element types are not supported:
- Associated types
- Macros
- Lifetimes
- Trait methods
It seems there're no links between declarations of these elements and their usages. When such links are added, the fix will be easy to activate for them too.

(INSP) Rename Fix for Naming Convention inspections

---

src/main/kotlin/org/rust/ide/inspections/RustNamingInspection.kt
src/test/kotlin/org/rust/ide/inspections/RustNamingInspectionTest.kt

The scope of Variable Naming inspection is narrowed to local `let ...` statements. Bindings within `match`es and `if let`s  are ignored.
Fixes #730

(INSP): Fix for Naming Convention inspection false positives

---

src/main/kotlin/org/rust/lang/core/types/RustEnumType.kt
src/main/kotlin/org/rust/lang/core/types/RustFunctionType.kt
src/main/kotlin/org/rust/lang/core/types/RustStructOrEnumTypeBase.kt
src/main/kotlin/org/rust/lang/core/types/RustStructType.kt
src/main/kotlin/org/rust/lang/core/types/RustTupleType.kt
src/main/kotlin/org/rust/lang/core/types/RustType.kt
src/main/kotlin/org/rust/lang/core/types/RustTypeParameterType.kt
src/main/kotlin/org/rust/lang/core/types/visitors/impl/RustTypeResolvingVisitor.kt
src/main/kotlin/org/rust/lang/core/types/visitors/impl/RustTypificationEngine.kt
src/test/kotlin/org/rust/lang/core/type/RustGenericExpressionTypeInferenceTest.kt

@alexeykudinkin @mkaput please review. The main interface changes are here: https://github.com/intellij-rust/intellij-rust/compare/type-params?expand=1#diff-231e8a807fef2b7083c5227a54b3aed0R23

(TYPE): support for type parameters substitutions

---

src/main/kotlin/org/rust/ide/annotator/RustTraitMethodImplLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/icons/RustIcons.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/annotator/RustLineMarkerProviderTestBase.kt
src/test/kotlin/org/rust/ide/annotator/RustTraitMethodImplLineMarkerProviderTest.kt

Trait methods implementations are annotated with icons on the gutter. Icons are linked to the trait method declarations. Pure implementations and overridings feature different icons:

(MISC): Line markers for trait method implementations

---

src/main/kotlin/org/rust/ide/annotator/RustTraitLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/icons/RustIcons.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustImplItemImplMixin.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/annotator/RustTraitLineMarkerProviderTest.kt
src/test/kotlin/org/rust/ide/annotator/RustTraitMethodImplLineMarkerProviderTest.kt

A `LineMarkerProvider` that adds an icon to a trait declaration that allows to jump to the trait implementations.
There's a problem that if a trait has a rustdoc comment and/or attributes, the icon is placed at the beginning of the comment/attribute, not at the trait declaration line. I can try to find a workaround in this marker provider, but I think it would be better (and maybe even easier) to solve the problem in the parser, though I don't know how to do that.

(MISC): Go to trait impl gutter icon

---

src/main/kotlin/org/rust/ide/annotator/RustRecursiveCallLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/icons/RustIcons.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/annotator/RustRecursiveCallLineMarkerProviderTest.kt

This is #756. Just reopened because of failed checks due to github temporary inaccessibility.
An annotator that detects and marks recursive calls:
Works for pure functions, associated functions and methods.

(MISC): Recursive calls gutter marker

---

README.md

Help new users find the related TOML plugin for `Cargo.toml` and `Cargo.lock` files.

Add reference to TOML plugin

---

src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/colors/RustColors.kt
src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
src/test/kotlin/org/rust/ide/annotator/RustHighlightingAnnotatorTest.kt
src/test/resources/org/rust/ide/annotator/fixtures/highlighting/function_arguments.rs
src/test/resources/org/rust/ide/annotator/fixtures/highlighting/type_parameters.rs

This adds parameters to the color settings as requested in #734. I split `self` params from the rest (similar to the screenshot in #734), but I'm not sure if that is what the project wants, so please give input if this PR seems misguided.

(MISC): Add function parameter color control

---

src/main/kotlin/org/rust/cargo/runconfig/RustExplainFilter.kt
src/test/kotlin/org/rust/cargo/runconfig/RustExplainFilterTest.kt

The compiler used to output errors with an [--explain E####] message,
but recent changes now use a new error[E####] format instead.
This CL updates the relevant console filter to recongize both
formats. If it comes across either pattern, it will turn them into
links to the appropriate Rust Compiler Error Index entry.

(MISC): Console now recognizes new error message format

---

src/main/kotlin/org/rust/ide/inspections/RustLint.kt
src/main/kotlin/org/rust/ide/inspections/RustLintLevel.kt
src/main/kotlin/org/rust/ide/inspections/RustNamingInspection.kt
src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/RustCompositeElement.kt
src/main/kotlin/org/rust/lang/core/psi/RustDocAndAttributeOwner.kt
src/test/kotlin/org/rust/ide/inspections/RustLintLevelTest.kt
src/test/kotlin/org/rust/ide/inspections/RustNamingInspectionTest.kt

I've implemented a function that detects the level of the given lint for the given PSI element (`PsiElement.lintLevel(RustLint): RustLintLevel`). 
The function analyses `allow`, `warn` and `deny` attributes and follows the same rules as `rustc` does. As the result, it allows to automatically suppress inspections based on the attributes in the source code. Potentially, it can also be used to automatically change the inspections warning levels. It's now used in the naming inspections and so fixes #775.
The scope of analysis is now limited by a file. This is the only known deviation from how `rustc` works. What would be the better way [than I use](https://github.com/alygin/intellij-rust/blob/f32d0628f96bd4448afdfe1ae26ba23943f504ba/src/main/kotlin/org/rust/lang/core/psi/RustCompositeElement.k …

(INSP): Automatic inspections suppression

---

src/main/kotlin/org/rust/ide/inspections/RustSelfConventionInspection.kt
src/main/kotlin/org/rust/lang/core/psi/RustDocAndAttributeOwner.kt
src/test/resources/org/rust/ide/inspections/fixtures/self_convention.rs

Suppresses Self Convention Inspections for items that derive `Copy`.
It won't work if one uses `impl Copy for T` explicitly, but I think such cases are rare and can be ignored here.
Fixes #515

(INSP): Suppress Self Convention Inspection for copyable items

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/test/kotlin/org/rust/cargo/runconfig/RunConfigurationTestCase.kt

Makes the `cargo` and `rustc` output colored on Linux and Mac.
Unfortunately, I don't know how to make it work on Windows and have no Windows machine for experiments. It uses Win API by default and can switch to `msys` under certain circumstances, but I think neither of these will work in IDEA. Though, I might be wrong about it.
Fixes #646 for Linux and Mac

(MISC): Colored output

---

src/main/kotlin/org/rust/ide/hints/RustParameterInfoHandler.kt
src/main/kotlin/org/rust/ide/info/RustParameterInfoHandler.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/hints/RustParameterInfoHandlerTest.kt

This one adds arguments info hints to function and method calls (Cmd+P). It works where the current resolvers work:
A possible further improvement would be to extract descriptions of the aliased types in generic functions and show them instead of aliases. It might be the common mechanism for both these hints and the completion engine (and something else?).
Fixes #437

(HINT): Functions/methods arguments hint

---

src/main/kotlin/org/rust/ide/annotator/RustTraitMethodImplLineMarkerProvider.kt
src/test/kotlin/org/rust/ide/annotator/RustTraitMethodImplLineMarkerProviderTest.kt

Fixes positioning of the "go to declaration" gutter icon when comments or attributes are provided for the function/method.
Before the fix, it was placed at the beginning of the comment/attribute.

(MISC): Gutter icon position fix

---

src/main/kotlin/org/rust/cargo/runconfig/RustExplainFilter.kt
src/test/kotlin/org/rust/cargo/runconfig/RustExplainFilterTest.kt

Fixes #804
Those messages now look like this:

(MISC): Error links improvements

---

src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/colors/RustColors.kt
src/main/resources/org/rust/ide/colors/highlighterDemoText.rs

Makes the `?` operator colored as a keyword ([screenshots](https://github.com/intellij-rust/intellij-rust/issues/785#issuecomment-264547200)). A setting to customise the color is also provided.
We can decide what color to use before merging the PR.
Fixes #785. Also fixes the `self` parameter display in the color settings window (it's displayed as a simple parameter now).

(MISC): Coloring ? operator

---

src/main/kotlin/org/rust/ide/inspections/RustNamingInspection.kt
src/main/kotlin/org/rust/lang/refactoring/NameSuggestions.kt
src/main/kotlin/org/rust/lang/refactoring/RustLocalVariableHandler.kt
src/main/kotlin/org/rust/lang/refactoring/RustNameSuggestions.kt
src/test/kotlin/org/rust/lang/refactoring/NameSuggestionsKtTest.kt
src/test/kotlin/org/rust/lang/refactoring/RustLocalVariableHandlerTest.kt

This pr expands the functionality introduced in #796
So far it follows these rules:
If the type is resolved suggest the first letter of the type name.
If its an argument to a function call, suggest the name of the argument in the function definition.
If its a function call suggest the name of the function and the enclosing namespace (if any).
If a name is already bound in the local scope do not suggest it.
This is mainly based on what the go plugin does.
Intellij in java also does the following if you are introducing a variable for a string literal, it uses the contents of the literal for the name, would this special case also make sense for rust?
We might want to use the is array setting on the Intellij NameUtil, however i'm not completely certain what it does and how much value it might …

(Misc) Local variable names suggestions

---

src/main/resources/org/rust/ide/liveTemplates/test.xml

Mainly because I'm used to `tfn` and tried `tbn`
I just copied the `tfn` one, is there something else to change? Couldn't find any tests related to that

Add tbn live template for bench fn

---

src/main/kotlin/org/rust/lang/core/completion/RustCompletionEngine.kt
src/test/kotlin/org/rust/lang/core/completion/RustCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RustCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RustStdlibCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RustTypeAwareCompletionTest.kt

Adds parentheses to functions/methods on autocompletion.
If the function has arguments, the cursor is positioned between parentheses, otherwise it moves after the closing parenthesis.
Parentheses are not added when the completion is performed within a `use` block.

(COMPL): Add parentheses when autocomplete functions/methods

---

src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt
src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoProjectWorkspaceImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/RustBacktraceFilter.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
src/main/kotlin/org/rust/lang/core/resolve/RustResolveEngine.kt
src/main/resources/org/rust/ide/colors/RustDarcula.xml
src/main/resources/org/rust/ide/colors/RustDefault.xml
src/test/kotlin/org/rust/cargo/runconfig/HighlightFilterTestBase.kt
src/test/kotlin/org/rust/cargo/runconfig/RustBacktraceFilterTest.kt
src/test/kotlin/org/rust/cargo/runconfig/RustConsoleFilterTest.kt
src/test/kotlin/org/rust/cargo/runconfig/RustPanicFilterTest.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestCase.kt
src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RustTypeAwareResolveTestCase.kt

Work is still in progress on this feature (#821), but it's already pretty functional.
I'm creating the PR to have an early feedback on the general approach and on some parts of the code related to elements resolving and working with cargo project metadata. Those of particular interest are marked with TODO's.
@matklad, could you, please, have a look at it?

(MISC): Add source code links to stack backtraces

---

src/main/kotlin/org/rust/ide/annotator/RustHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/colors/RustColors.kt
src/main/resources/org/rust/ide/colors/highlighterDemoText.rs

Brings element names that are used in the color customization panel into line with the Rust lingo (used in the official documentation). Also provides an example of an associated function call in the demo source code.
I would also rename some of the `RustColor` variant names accordingly, but that will reset colors for those users who have customized them and there're no simple way (at least, I didn't find it) to just copy values from the old settings. So, I'm not sure if it's ok to do so.

(MISC): Color customization terms cleanup

---

src/main/kotlin/org/rust/cargo/runconfig/RustBacktraceFilter.kt

In Rust 1.14, the function that prints stack backtraces has been moved to another module. The new location is added to the `RustBacktraceFilter`'s skip list.

(RUN): New backtrace write function location in Rust 1.14

---

src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt
src/main/kotlin/org/rust/cargo/project/PackageOrigin.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoProjectWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoProjectWorkspaceImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/RustBacktraceFilter.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/cargo/util/ModuleUtil.kt
src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt

`Package.isWorkspaceMember` is substituted for `Package.origin`, which allows to make distinction between stdandard libraries, workspace packages, direct dependencies and transitive dependencies.
I've also removed `Package.dependencies` since it has always been empty and none used it.

(PROJ): Introduce PackageOrigin

---

src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt
src/main/kotlin/org/rust/lang/core/completion/RustCompletionEngine.kt
src/test/kotlin/org/rust/lang/RustTestCaseBase.kt

Hyphens in crate names are replaced with underscores on autocompletion.

(COMPL): Fix hyphenated crate names completion

---

src/main/kotlin/org/rust/lang/core/completion/RustCompletionEngine.kt

Stdlib modules now use the `RUST_FILE` icon on autocompletion. This fix rewrites it to `MODULE`, the same icon as other modules use.

(COMPL): Fix icon for stdlib module in autocompletion

---

src/main/kotlin/org/rust/lang/core/RustPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RustCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributorTest.kt
src/test/kotlin/org/rust/lang/core/completion/RustPsiPatternTest.kt

1. New keywords added: `crate`, `extern`, `fn`, `impl`, `mod`, `mut`, `pub`, `unsafe`, `use`.
2. Each part of a keywords phrase is now completed separately. For instance, the phrase `pub unsafe fn` completes word by word, each completion variant depends on the preceding keyword.
3. Many keywords (`enum`, `struct`, `use` etc) are now also completed within functions/methods.

(COMPL): Keywords completion improvement

---

src/main/kotlin/org/rust/lang/core/RustPsiPattern.kt
src/test/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributorTest.kt
src/test/kotlin/org/rust/lang/core/completion/RustPsiPatternTest.kt

I've fixed a couple of corner cases in keywords completion when they depend on other preceding keywords.

(COMPL): Fix keywords completion

---

src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RustAttributeCompletionTest.kt

The `cfg` attribute can be applied pretty everywhere.

(COMPL): cfg attribute completion fix

---

src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RustKeywordCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RustCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RustKeywordCompletionContributorTest.kt

Autocomplete `self::` and `super::` after `use`.

(COMPL): Complete self and super after use

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/annotator/RustInvalidSyntaxAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RustTypeAliasImplMixin.kt
src/test/kotlin/org/rust/ide/annotator/RustInvalidSyntaxAnnotatorTest.kt

Here's the second part of #864. Type aliases grammar rule is unified and all the checks are moved to `RustInvalidSyntaxAnnotator`. I've also extracted detection of two Rust errors related to the issue (E0202, E0449) and provided them with the same messages as rustc produces.
Unfortunately, there's one broken parsing test I can't fix: `RustPartialParsingTestCase > testTraitBody`. It looks like a recovery problem we faced earlier, but I have no clue how to solve it. The parser just interprets some gibberish as a beginning of a type alias statement.
@matklad, could you, please, take a look at it?

(GRAM): Switch from multi-rule mode to annotator for type aliases

---

src/main/kotlin/org/rust/cargo/project/CargoProjectDescription.kt
src/main/kotlin/org/rust/lang/core/completion/RustCompletionEngine.kt
src/test/kotlin/org/rust/lang/RustTestCaseBase.kt
src/test/kotlin/org/rust/lang/core/completion/RustExternCrateCompletionTest.kt

Use target with `kind = LIB` in autocompletion instead of the package name.
Fixes #903

(COMPL): Extern crates completion fix

---

src/main/kotlin/org/rust/ide/annotator/RustErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RustErrorAnnotatorTest.kt

Annotation to highlight the E0403 error &mdash; duplication of type parameter names.
Part of #886

(ANNOT): Detect type param names duplication

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RsFunctionImplMixin.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt

I'd like to commit this part of the functions grammar unification (#864) to make it survive the next wave of the renaming armageddon :)
Free functions, impl and trait functions/methods are unified along with their parameters.
Foreign functions will be the next step.

(GRAM): Unify functions grammar

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

One more grammar rules unification from #864: this one is for struct / enum variant field declarations, including tuple-like.

(GRAM): struct / enum variant fields decl grammar unification

---

src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt

Minor `derive` attribute completion improvements:
- Complete `derive` with parentheses on `struct`s
- Complete [RustcEncodable](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/trait.Encodable.html) and [RustcDecodable](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/trait.Decodable.html) derivables
- Debug code removed
- `DeriveCompletionProvider` and its test class renamed to get in line with other classes and to make navigation easier

(COMPL): Derive completion improvement

---

src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt

Makes the Self Convention Inspection handle `mut self` correctly for the `into_*` case, the same way as Clippy works.
Fixes #950.

(INSP): Fix self convention inspection for `into_`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Removes the annotation on mutable static constants in `extern` blocks as they are allowed by Rust (discussed [here](https://github.com/intellij-rust/intellij-rust/pull/967#pullrequestreview-18971241)).

(ANNOT): Allow foreign mutable static consts

---

src/main/kotlin/org/rust/lang/core/resolve/ResolveEngine.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

While working on [E0061](https://doc.rust-lang.org/error-index.html#E0061) (wrong arguments number) detection I stumbled upon a problem with methods and associated functions resolve when there's a conflict between the inherent implementation and a trait implementation.
For instance:
```rust
struct Foo;
impl Foo {
fn bar(&self) {}
}
trait Bar {
fn bar(&self);
}
impl Bar for Foo {
fn bar(&self) {}
}
fn main() {
let foo = Foo;
foo.bar();  // <-- resolves to Bar::bar() now, but must be resolved to Foo::bar()
}
```
I've fixed the problem for methods, but left associated functions intact so far (though, I've provided an ignored failing test for them).
If this fix looks fine, I'll get back to associated functions. Do I understand correctly that I have to extract something like …

(RES): Resolve conflicts between inherent / trait functions

---

src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt

PR for issue #962 
This intention convert
```rust
if let A(value) = x {
//Stuff for A
} else if let B(value) = x {
//Stuff for B
} else {
//Stuff for something else
}
```
to
```rust
match x {
A(value) => {
//Stuff for A
},
B(value) => {
//Stuff for B
},
_ => {
//Stuff for something else
}
}
```

INT: Add IfLetToMatchIntention

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/impl/mixin/RsFunctionImplMixin.kt
src/main/kotlin/org/rust/lang/core/resolve/ResolveEngine.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt

Wrong arguments number detection ([E0061](https://doc.rust-lang.org/error-index.html#E0061) from #886).
I had to skip cases when a function call resolves to a trait implementation to eliminate some tricky false positives (see tests).

(ANNOT): Wrong arguments number annotation

---

src/main/kotlin/org/rust/lang/core/completion/CompletionEngine.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsModReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RsModCompletionTest.kt

This PR add autocomplete for module declaration statements.
The autocomplete is created by taking all the `.rs` filenames without the extension + all the directory name that contains a `mod.rs` file inside.
Fix #883

Mod completion

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Extends E0061 detection (from #886) to tuple-like structs and enum variants.

(ANNOT): Detect E0061 for tuple-like structs

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Detects missing lifetimes ([E0106](https://doc.rust-lang.org/error-index.html#E0106) from #886) in structs, enums and type aliases.

(ANNOT): Missing lifetime annotation

---

src/main/kotlin/org/rust/ide/inspections/RsSimplifyBooleanExpressionInspection.kt
src/main/kotlin/org/rust/ide/intentions/SimplifyBooleanExpressionIntention.kt
src/main/kotlin/org/rust/ide/utils/ExprUtils.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RsSimplifyBooleanExpression.html
src/test/kotlin/org/rust/ide/intentions/SimplifyBooleanExpressionIntentionTest.kt

First sketch of advanced analisys of expressions and its usage in simplifications.
`expr.isPure()` tries to infer if an expression is functionally pure and throws no errors.
Now expressions like `a || true` are simplified to `true` (since paths like `a` are always pure, so expression `a || true` has no side effects, no panics and `||` is not overloadable).
Expressions like `f() || true` are not simplified because function call can have side effects.
There is a lot of work to do, but I want to know, is a design like this ok or it should be done in the completely another way.

INT: Purity check of expressions, improved simplification of boolean expressions

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt

Should work on Mac (thanks, @alygin!) and Linux
Closes #988 (for real, this time)

Set TERM to "ansi"

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Detects usage of type placeholders in function signatures and constants ([E0121](https://doc.rust-lang.org/error-index.html#E0121) from #886).

ANNOT: Annotate type placeholders in item signatures

---

src/main/kotlin/org/rust/lang/refactoring/RsNamesValidator.kt
src/main/kotlin/org/rust/lang/refactoring/RsRenameProcessor.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

There's a problem with renaming now: `RsNameValidator` hasn't a clue about the type of the element being renamed. So, it has to always allow both regular `identifier`s and `quote_identifier`s because we want to be able to rename everything. This leads to throwing an error when you provide a name of a wrong type (for instance, `foo` for a lifetime, or `'foo` for a function).
This change introduces an implementation of `RenamePsiElementProcessor` that substitutes wrong names to valid ones (by adding or removing a quote sign when needed) thus preventing mentioned errors.
The problem could have been solved in the `RsReferenceBase.doRename()`, but `RenamePsiElementProcessor` provides additional functionality that will allow us to do other refactoring improvements (like handling name …

REN: Don’t fail on wrong id type while renaming

---

src/main/kotlin/org/rust/lang/core/psi/util/RustExprExtensions.kt
src/main/kotlin/org/rust/lang/core/types/types/RustIntegerType.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Infer integer literal kinds for array sizes and enum variant discriminants. It will help with a couple of error annotations.

TY: Type inference for array sizes and enum variant discriminants

---

debugger/build.gradle
debugger/download_deps.sh
debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerTypesHelper.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/CargoDebugConfiguration.kt

Update Debugger plugin to work with intellij-rust plugin 0.1.0.1698
Also updated CLion dependency from 16.3.2 to 16.3.3.
Tested and now works fine on CLion 16.3.3 with intellij-rust-plugin 0.1.0.1698
Fixes https://github.com/intellij-rust/intellij-rust/issues/1059

Update Debugger plugin to work with intellij-rust plugin 0.1.0.1698

---

src/main/kotlin/org/rust/cargo/runconfig/ui/CargoRunConfigurationEditorForm.kt

Various small fixes of the run configuration edit window:
1. Add title to the "Additional arguments" window to fix `Assertion failed: Dialog title shouldn't be empty or null: []` exception that sometimes occurs.
2. Make fields wide again!
3. Add quick focus hotkeys to the fields with no such keys.

RUN: Run config UI fixes

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt
src/main/kotlin/org/rust/cargo/runconfig/ui/CargoRunConfigurationEditorForm.kt
src/main/kotlin/org/rust/cargo/toolchain/BacktraceMode.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable configuration uses default environment.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test configuration uses default environment.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForBin.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForExample.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForExamples.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/hyphenInNameWorks.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/mainFnIsMoreSpecificThanTestMod.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/mainModAndTestModHaveSameSpecificity.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningfulConfigurationName.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testFnIsMoreSpecificThanMainMod.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerAddsBinName.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForAnnotatedFunctions.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForFiles.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForModules.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForRootModule.xml

Rust now supports [short backtraces](https://github.com/rust-lang/rust/pull/38165) in nightly.
This PR:
1. Changes the "Print backtrace" flag to backtrace mode combo box (No, Short, Full). "Short" will work the same way as "Full" in beta and stable until the feature is promoted. Full is default.
2. Adds support of short backtraces to the filter that "linkifies" function names.

RUN: Support short backtraces

---

src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/LIbraryUtil.kt
src/main/kotlin/org/rust/cargo/project/workspace/Stdlib.kt
src/main/kotlin/org/rust/cargo/project/workspace/impl/CargoProjectWorkspaceServiceImpl.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
src/main/kotlin/org/rust/ide/annotator/RsCrateDocLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
src/main/kotlin/org/rust/lang/core/completion/CompletionEngine.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsCompositeElement.kt
src/main/kotlin/org/rust/lang/core/resolve/ResolveEngine.kt
src/test/kotlin/org/rust/FileTree.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoProjectResolveTest.kt
src/test/kotlin/org/rust/ide/annotator/RsCrateDocLineMarkerProviderTest.kt
src/test/kotlin/org/rust/ide/annotator/RsLineMarkerProviderTestBase.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeParametersResolveTest.kt

When multiple versions of a particular crate are used in the same project (transitively, through dependencies), resolve references to the correct version of the crate depending on what package the reference belongs to.
Fixes #1015

RES: Resolve to correct crate version

---

src/main/kotlin/org/rust/ide/folding/RsCodeFoldingOptionsProvider.kt
src/main/kotlin/org/rust/ide/folding/RsCodeFoldingSettings.kt
src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/main/kotlin/org/rust/ide/folding/impl/RsCodeFoldingSettingsImpl.kt
src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/folding/RsFoldingTest.kt
src/test/resources/org/rust/ide/folding/fixtures/macro_brace_arg.rs
src/test/resources/org/rust/ide/folding/fixtures/one_liner_function.rs

Implements #1097 
I'd like to only fold one-liners by default when the flag Preferences -> Editor -> General -> Code Folding -> One-line methods is on, but don't know how to get its value. There's the `CodeFoldingSettings` class, but it doesn't provide access to the "Collapse by default" preferences block. Any hints on how that could be achieved?

FOLD: Fold one liner functions

---

src/main/kotlin/org/rust/lang/core/resolve/Resolve.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

Fix lifetime resolve when it's declared in a `where for<...>` clause.

RES: Fix lifetime resolve in where clauses

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddTurbofishFix.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddTurbofishFixTest.kt

Now addressing:
* nesting `parse<Option<Option<i32>>("41")`
* boundary `3 < parse<i32>("41") > 10`
But not yet:
* `Something<Gen>::func()`
* `func<Some<_>>()`
* `func<A, B>()`
*Note*: `create()` and `createFromText()` come from `RsPsiFactory` because I didn't find any other usable and public implementation. Thoughts are welcome.

ANN: Improvement on add turbofish quick fix.Support nested generics.

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

E0107 (wrong number of lifetime parameters) and more cases of E0106 (missing lifetime) annotations. From #886

ANN: More lifetime error annotations

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt

Fixes the #1114 false positive. I'm not sure this should be the final solution, just want to provide some fix before the alpha release.
cc @farodin91

ANN: Fix mutability annotation on enum variants

---

src/main/kotlin/org/rust/lang/core/types/types/RustEnumType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustStructType.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

See #1120 for more info. I removed `RustStructType.struct` field and made equality by `item` (same with `RustEnumType`). I'm not sure about the implementation, but this PR contains useful tests that demonstrate the problem (and its fix).

COMP: Complete trait methods implemented for struct or enum (Fixes #1120)

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Annotates [E0243](https://doc.rust-lang.org/error-index.html#E0243)/[E0244](https://doc.rust-lang.org/error-index.html#E0244) errors &ndash; not enough / too many type arguments.
From #886

ANN: Wrong type arguments number annotations

---

src/main/kotlin/org/rust/lang/core/types/RustTypificationEngine.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

provides generic types inference for struct/enum expressions
```rust
struct SomeStruct<T1, T2> { a: T1, b: T2 }
fn main() {
let x = SomeStruct { a: 5u16, b: 5u8 };
(x.a, x.b)
//^ (u16, u8)
}
```

TY: infer struct or enum expr type parameters

---

src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt

Use built-in grayed links support (since 2016.1 as far as I remember) in backtraces instead of coloring them manually.

FLT: Use built-in grayed links

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Annotates empty `return`s in functions that return values.
[E0069](https://doc.rust-lang.org/error-index.html#E0069) from #886

ANN: Annotate invalid empty returns (E0069)

---

src/main/kotlin/org/rust/lang/core/types/RustTypificationEngine.kt
src/main/kotlin/org/rust/lang/core/types/types/RustFloatType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustIntegerType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustNumericType.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Now correctly infer types in cases like this
```rust
struct SomeStruct<T> { a: T, b: T }
fn main() {
let x = SomeStruct { a: 0, b: 5u16 };
x.a
//^ u16
}
```

TY: basic infer non-suffixed numeric types

---

src/main/kotlin/org/rust/lang/core/types/RustTypificationEngine.kt
src/main/kotlin/org/rust/lang/core/types/types/RustEnumType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustStructOrEnumTypeBase.kt
src/main/kotlin/org/rust/lang/core/types/types/RustStructType.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

It works now!
```rust
struct S1<T>(T);
struct S3<T1, T2, T3>(T1, T2, T3);
type A<T1, T2> = S3<T2, S1<T1>, S3<S1<T2>, T2, T2>>;
type B = A<u16, u8>;
fn f(b: B) {
(b.0, (b.1).0, ((b.2).0).0)
//^ (u8, u16, u8)
}
```

TY: fully supported generic type aliasing of struct/enum

---

src/main/kotlin/org/rust/ide/typing/RsTypingHandler.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/typing/RsBraceMatcherTest.kt

https://github.com/intellij-rust/intellij-rust/issues/1022
This case is similar with inserting `>` after `.<` in Java so my implementation is based on
https://github.com/JetBrains/intellij-community/blob/f8093cba578089b13314197faee7b3436ab831f5/java/java-impl/src/com/intellij/codeInsight/editorActions/JavaTypedHandler.java#L290

TYPE: automatically insert '>' after '::<'

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt

Makes all the packages that reside within our project treated as workspace members even if they're not listed by cargo in the `workspace_members` block.
Since cargo doesn't explicitly provide package paths, I extract them from the package `id`s and check if manifests of other packages sit somewhere within them.
Fixes #1137

CARGO: Treat nested packages as workspace members

---

src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/test/resources/org/rust/ide/folding/fixtures/one_liner_function.rs

Prevents one-line functions from showing their contents when collapsed if the resulting line is longer than the right margin setting allows. Such functions also don't autofold.
Fixes #1162

FOLD: Fully fold one-liners that exceed line margin

---

src/test/kotlin/org/rustSlowTests/RsCompilerSourcesPerformance.kt

tests are no longer distributed by default with rust-src, and this
particular test has never caught a bug anyway.

T: drop compiler tests parsing

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Support inference of:
* sequence expressions like `[1, 2, 3]`. Array element type is the same with type of first element of the sequence. Should we infer type of all elements?
* expressions with initialization value like `[0; 8]`. Size can be extracted only from integer literal.
TODO:
* support compile time expressions as array size

TY: initial support of array expression type inference

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/main/kotlin/org/rust/lang/core/types/RustType.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/types/RustPrimitiveType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustReferenceType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustSliceType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustStringSliceType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustTraitType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustTypeParameterType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustUnitType.kt
src/main/kotlin/org/rust/lang/core/types/types/RustUnknownType.kt

RsImplIndex now just looks for impls and that's it. 
Actual method and trait extraction happens in `RustType.kt`
cc @farodin91 @vlad20012 
This is not ready to merge yet as is (I want to do some cleanups tomorrow), but it's otherwise ready for a review.

Move autoderef logic to one place

---

src/main/kotlin/org/rust/cargo/project/workspace/Stdlib.kt

`init` and `onSuccess` happen on different iterations of the event loop
and `oldLibrary` can die between them. Let's just remove this check,
because we don't update stdlib concurrently anymore.

Don't touch Library after it's been disposed

---

src/main/kotlin/org/rust/lang/core/completion/CompletionEngine.kt
src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt

COMP: Show the trait of an method

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/ui/CargoRunConfigurationEditorForm.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/RustChannel.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable configuration uses default environment.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test configuration uses default environment.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForBin.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForExample.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/executableProducerWorksForExamples.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/hyphenInNameWorks.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/mainFnIsMoreSpecificThanTestMod.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/mainModAndTestModHaveSameSpecificity.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/meaningfulConfigurationName.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testFnIsMoreSpecificThanMainMod.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerAddsBinName.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForAnnotatedFunctions.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForFiles.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForModules.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/testProducerWorksForRootModule.xml

If rustup is available, allows to select a channel in run configuration:
If the channel is not `[Default]`, `rustup run {channel}` is used to execute cargo.
At the moment, the set of channels is predefined and their presence is not checked. In the future, the setting can be changed to "Toolchain" and use `rustup show` to fill the list automatically. But I guess such improvement should somehow merge into the current `RustToolchain` infrastructure, and thus be carefully thought over beforehand.
What do you think? Is it ok to have the feature with this caveat?

RUN: Select channel in run configuration

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt

Colored output works correctly for clippy now, so it's whitelisted.

CARGO: Colored output for clippy

---

src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt

Cargo reports library crates with `proc-macro = true` as `kind = proc-macro`, not `kind = lib` (for example, `serde_derive`). As a result, such crates are not resolved in `extern crate` clauses. This fix makes proc-macro crates treated as lib crates and correctly resolved.

CARGO: Support proc-macro crate kind

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/LIbraryUtil.kt
src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt

Rust stdlib includes several crates that can be used as dependencies without mentioning in Cargo.toml yet are not a part of the prelude. For instance, we can use `extern crate rand;` in nightly when `#![feature(rand)]` is provided. So, such crates should be added as stdlib roots to be resolved (they now have `isRoot = false`).
The problem is that there are external crates with the same names (`rand` and `term` are main troublemakers). Adding such crates as dependencies to Cargo.toml brings name conflicts and breaks resolving when [we use the mentioned approach](https://github.com/intellij-rust/intellij-rust/pull/1145#issuecomment-299711548).
This fix introduces stdlib crate types: root, featured, dependency. Unlike roots, featured crates are only added to packages as a part of stdlib when …

CARGO: Support feature gated stdlib dependencies

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsIndexExpr.kt
src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt
src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt

* more flexible `canUnifyWith` for RustNumericType: numeric type can be unified with type with different kind if it's weak
* initial support for index expression type inference using `Index` trait

TY: initial support of index expression type inference

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt

Fixes an E0384 false positive when a mutable static constant is reassigned. Also a minor refactoring.
Though technically, it's not a E0384, I think we can still handle it here because Rust has no designated code for this case.
cc @farodin91

ANN: Fix E0384 false positive

---

src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyStructOrEnum.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyUnknown.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Improve type inference of function call expressions. Now we can infer type parameter not only directly:
```rust
fn foo<T>(arg: T) -> T { ... }
let x = foo(123) // x: i32
```
but also from more complex generic arguments:
```rust
fn foo<T>(arg: (T, T)) -> [T; 2] { ... }
let x = foo((1, 2)); // x: [i32; 2]
``` 
Slightly modified `canUnifyWith` methods are used to achieve it.

TY: improve type inference of function call expr

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt

Cargo's `rustc` subcommand is color-friendly.

CARGO: Colorize `rustc` command output

---

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt

Intelligently complete return with `;` or ` `

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddTurbofishFix.kt
src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt
src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
src/main/kotlin/org/rust/ide/utils/ExprUtils.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt
src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/main/kotlin/org/rust/lang/utils/RsBooleanExpUtils.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsArithmeticOpsTest.kt

Infer type of arithmetic binary expression.
Now inference doesn't work in following cases:
* for primitive types because their implementations are created with macros
* for generic types when `Output = Self`:
```rust
impl<T> Add for Foo<T> {
type Output = Self;
fn add(self, rhs: Self) -> Self { ... }
}
```
* if `Output` is generic and its type parameters should be inferred from `RHS` type:
```rust
impl<T1, T2> Add<Bar<T2>> for Foo<T1> {
type Output = FooBar<T1, T2>;
fn add(self, rhs: Bar<T2>) -> FooBar<T1, T2> { ... }
}
```

TY: initial support of arithmetic binary expression type inference

---

src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

closes https://github.com/intellij-rust/intellij-rust/issues/865

TY: autoderef does not erase type parameter info

---

src/main/grammars/RustParser.bnf
src/test/kotlin/org/rust/lang/core/completion/RsPartialParseCompletionTest.kt
src/test/resources/org/rust/lang/core/parser/fixtures/partial/struct_expr_fields.txt

GRAM: better parser recovery for struct fields

---

src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt

Add `proc_macro` to stdlib roots.
For some unknown to me reasons, rustup doesn't install `libproc_macro` sources for nightly toolchain, so the resolving of `extern crate proc_macro` won't work with nightly at the moment. I'll try to find out more about it, but there's nothing more to do on the plugin side, so it closes #1311.

CARGO: Add proc_macro to stdlib roots

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt

closes #1313
Stub can be updated concurrently, so we need to store it in a local
variable. At least, that is the theory: I don't know any other way we
could get a Java NPE here!

PSI: fix NPE when retrieving lang attribute

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt

Сloses #640
Closes #1217
It temporary breaks potentially useful quick doc in some cases where we can't infer variable type, for example, tuple destructuring in function declaration, but it should be fixed from type inference side.

Show the type of variable on hover

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

External C functions are allowed to be variadic. Variadic functions
take a minimum amount of arguments and passing more arguments is valid/expected.
Our current implementation always expects the exact number of arguments
to be passed and displays an error otherwise.
Fix this behavior and provide an show error E0060
when not passing enough arguments to a variadic function.
RsMethodCallExpr.expectedParamsCount() was only adjusted for consistency
as variadic calls are only allowed for extern C functions.

ANNOT: Handle wrong number of arguments passed to variadic functions

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Negative impls can sometimes be necessary when you want to remove certain
automatically derived marker traits like Send and Sync.
This negative impls does not require (or allow) the unsafe keyword even
when the trait itself is marked as unsafe.
This fixes a wrong error being displayed in libcore/marker.rs for
impl<T: ?Sized> !Send for *const T { }
CC #886

ANNOT: Do not require/allow unsafe on negative impls of traits [E0198]

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

This allows to properly resolve modules when a pat binding with the same name exists.
It covers the following situations creating pat bindings:
- if let
- while let
- for
- match arms
- lambdas

RES: Handle pat binding names overlapping with module names

---

src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt

Closes #1277 
Add checkbox into new project wizard to choose project/module type: executable or library.

Executable and library rust project types

---

src/main/kotlin/org/rust/lang/core/resolve/LangItems.kt
src/test/kotlin/org/rust/lang/core/type/RsIndexTypeInferenceTest.kt

Closes #1420 
`container[index]` is syntactic sugar for `*container.index(index)` (see [index doc](https://doc.rust-lang.org/std/ops/trait.Index.html)) so type of `container[index]` must be `Output` instead of `&Output`.

TY: index operation must return 'Output' type instead of '&Output'

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsArrayType.kt
src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/main/kotlin/org/rust/utils/Extensions.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

TY: catch NumberFormatException if tuple field name isn't number

---

src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt

Move all checkboxes which aren't retaled to project creation from `RustProjectSettingsPanel` into `RustProjectConfigurable` component.

Remove checkboxes from new project wizard

---

src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

It was done as part of a refactoring, but references to a tuple struct (constructor) are works now.
```rust
struct S<T>(T);
fn main() {
let f = S::<u8>;
f(1).0
}      //^ u8
```
There is a special case with unit struct (`struct S;`). It may be initialized in both syntax: as literal `S {}` or as tuple `S()`. So we can't treat it as a function type (or literal syntax will not work) and should handle in a special way

TY: treat path to tuple struct/enum as function type

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt

**NOTE**:
This implementation uses original text of type parameter bound to create quick doc. So if type parameter bound contains extra whitespace symbols:
```rust
fn foo<T: Into< String >> { ... }
```
quick doc will contain them too:
```
type parameter T: Into< String >
```
But quick doc for some other language items, for example, struct fields, has the same problem, so I think it should be fixed at the same time in other PR.

QDOC: quick documentation for type parameters

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitRef.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt

Turns out that to fix that SO, one has to simply remove logic duplication between `resolveToBoundTrait` and `advanceResolve` of paths themselves. 
closes #1455

TY: use common infra for resolving Fn traits

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/ide/utils/PresentationUtils.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt

* use same type parameter representation in navigation info as in quick doc
* add info if function/method in extern block and its abi name
* show parent object: trait or module name for function/method instead of full path of function/method
* show type parameters declared in impl object

QDOC: quick doc improvements

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt

Improve quick doc and navigation info for structs, enums, traits, type aliases and associated types

QDOC: quick doc improvements 2

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/test/kotlin/org/rust/lang/core/resolve/RsClosuresResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

```rust
struct S<X>(X);
trait Tr<Y> { fn foo(&self) -> Y; }
impl<Z> Tr<Z> for S<Z> { fn foo(&self) -> Z { unimplemented!() } }
fn bar<A, B: Tr<A>>(b: B) -> A { b.foo() }
fn main() {
let a = bar(S(1));
a
} //^ i32
```

TY: infer type parameters from trait bounds

---

src/main/kotlin/org/rust/ide/formatter/RsSingleImportRemoveBracesFormatProcessor.kt
src/test/kotlin/org/rust/ide/formatter/RsFormatterImportBracesTest.kt

Fix #1512 and don't leave broken code.

FMT: Should not break the code by leave `use some::self`

---

src/main/grammars/RustParser.bnf
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
src/test/resources/org/rust/lang/core/parser/fixtures/partial/enum_vis.txt

GRAM: parse 'eprint!' and 'eprintln!' as 'FormatLikeMacro'

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/utils/Extensions.kt

PsiElement.children allocates an ArrayList and an array, so we should iterate over children manually.
In Java I would write an iterator, but in Kotlin we have inline functions, so why do we need an iterator?) Kotlin ruled

Iterate over psi children effectively

---

src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt

TYPE: Add inlay parameter hints

---

src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt

Closes #1465 
* Drop suggestions of `RustcEncodable` and `RustcDecodable` traits
* Add completion variants with dependencies

COMP: improve derive completion

---

src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorTest.kt

Closes #1497 
In `RsCargoCheckAnnotator` we check that message belongs to file by [equality of path suffix](https://github.com/intellij-rust/intellij-rust/blob/78754355e3cc823d75292f596d5c4ca1c17b26ad/src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt#L147-L148) with path from the message. But if the current file is not project file (from stdlib or dependency) and it has path with the same suffix, we calculate offsets for incorrect file and sometimes it can lead to invalid range.

ANN: don't try to annotate non project files

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyStructOrEnum.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyUnknown.kt
src/main/kotlin/org/rust/lang/core/types/ty/UnifyResult.kt

Refactored extremely hacky `Ty.canUnifyWith` method.
Now it's possible to implement precise/fuzzy impl lookup originally discussed at #1245 (also you can look at `RsPreciseTraitMatchingTest` TODO tests).
To do it we should somehow filter fuzzy matched impls after `findImplsAndTraits` call (currently there are no any flags and return type `Collection<BoundElement<RsTraitOrImpl>>` already seems quite complicated)
And I guess after it we'll be able to easily implement `impl<T> for T` resolution.

Refactored Ty.canUnifyWith

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt

Support path value parameters in quick documentation.
It allows us to correctly show `FnOnce`, `FnMut` and `Fn` trait bounds.

QDOC: support path value parameters

---

src/main/kotlin/org/rust/ide/presentation/Ty.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsBaseType.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

`!` type (TyNever) is result of `return`, `break` & `continue` exprs, and also `panic!()`, `unimplemented!()` and so on. Rust handles `!` in a special way, e.g. allow it to become any type, or ignore match arm that return it.
It isn't fixing #1599 completely, but if remove semicolon after `return 0` in that example,  it will work.

TY: implemented `!` type

---

src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Fixed:
```rust
fn main() {
const X: i32 = 1;
}                //^ i32
```

TY: fixed inference consts and statics inside functions

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RsMacroDefinitionCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

Partially fixes #1598 
* no macro completion in `RsItemElement` definition
```rust
impl Whatever /*caret*/
```
* no macro completion after path segment
```rust
Whatever::/*caret*/
```

COMP: improve macro completion

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
src/test/resources/org/rust/lang/core/parser/fixtures/partial/enum_vis.txt

panic!(), unimplemented!() and unreachable!() unconditionally panic
and thus have a return type of "!".
All 3 support a format!() syntax so support that as well.

Fix the return type of panic!() and unreachable!()

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

This improves resolving of trait methods for various primitive types.
In particular tuples, arrays, functions and the never type.
All tuples share the same fingerprint "(tuple)".
All arrays and slices share the same fingerprint "[T]".
All functions share the same fingerprint "fn()".
The never type uses the fingerprint "!".

TY: Improve indexing and type resolving for primitive types

---

src/main/grammars/RustParser.bnf

A tiny parser optimization: special macros do a ton of matching by text, but we can try to match on tokens first.

GRAM: optimize macro parsing

---

src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt

A mutable reference to a empty struct without braces would produce an error
"Cannot borrow immutable local variable `EmptyStruct` as mutable"
struct EmptyStruct;
let error = &mut EmptyStruct;
let ok = &mut EmptyStruct { };
The solution for this is very similar to 6842c263b91feeb99c78fb7319d8757203d47ebf for #1114
An empty struct expression with and without braces have a different
PSI representation.
EmptyStruct is a RsPathExpr which resolves to a RsStructItem
EmptyStruct {} is a RsStructLiteral which is handled by the else in RsExpr.isMutable

ANN: Fix wrong mutability annotation on empty structs without braces

---

src/main/kotlin/org/rust/ide/presentation/Ty.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/TraitRef.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/Unify.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyInfer.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyStructOrEnum.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/main/kotlin/org/rust/lang/core/types/ty/UnifyResult.kt
src/test/kotlin/org/rust/lang/core/resolve/RsClosuresResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsNumericLiteralTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

Really it's just a part of The Ultimate Type Inference™. I just found something like an "incremental point", so await a new PRs soon.
Good news is that a lot of really advanced type inference are working now:
```rust
fn main() {
let a = 0;
//^ u8
let mut vec = Vec::new();
vec.push(a);
vec.push(1u8);
}
```
```rust
fn main() {
let vec = vec![1, 2, 3];
let b: Vec<_> = vec.into_iter().collect();
b
//^ Vec<i32>
}
```
Bad news is that the code is now like an awful Frankenstein molded out of our old type inference (with substitutions, Ty.unifyWith and so on) and the new one. I think we can live with it for a bit :)

TY: advanced type inference & unification

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt
src/main/kotlin/org/rust/lang/utils/IndexUtils.kt
src/main/kotlin/org/rust/lang/utils/ProjectCache.kt

`getCachedValue` relies on identity of passed-in lambdas, and Kotlin's
inline does not help us to maintain these identities. So let's create
keys ourselves instead.
r? @vlad20012

Fix unsound `findWithCache`

---

build.gradle.kts
src/test/kotlin/org/rust/cargo/runconfig/RunConfigurationTestCase.kt
src/test/kotlin/org/rust/cargo/runconfig/filters/HighlightFilterTestBase.kt
src/test/kotlin/org/rust/cargo/runconfig/filters/RsExplainFilterTest.kt
src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
src/test/kotlin/org/rust/ide/hints/RsQuickDefinitionTest.kt
src/test/kotlin/org/rust/ide/surroundWith/RsSurrounderTestBase.kt
src/test/kotlin/org/rust/ide/template/postfix/PostfixTemplateTest.kt
src/test/kotlin/org/rust/ide/typing/RsBraceMatcherTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt
src/test/kotlin/org/rust/lang/core/parser/RsCompleteParsingTestCase.kt
src/test/kotlin/org/rust/lang/core/parser/RsPartialParsingTestCase.kt
src/test/kotlin/org/rust/lang/core/resolve/RsNonPhysicalFileResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
src/test/kotlin/org/rust/lang/refactoring/RsNameSuggestionsKtTest.kt

Instead of using fluent assertions, write a plain `check` and, once a
test fails, add an artisanal hand-crafted error message with the help of
awesome "Kotlin $string literals".
r? @vlad20012

T: drop assertj dependency

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

- Distinguish between *const and *mut pointers to help resolving to only 1 candidate
- Distinguish between & and &mut references to help resolving to only 1 candidate
- Resolve inherent implementations on primitives for "primitive::method()" syntax
CC #371
Fixes #1667

Primitive type resolving improvements

---

src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt

Was broken with bf9dad5300081f4d3b979cb2570594ef87b4e41b

Fixed "unresolved reference" inspection

---

src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt

Is it legal if method named `getExpressionsAt` now return not only expressions?)

Type information on var binding #1696

---

src/main/kotlin/org/rust/lang/core/psi/RsLiteralKind.kt
src/main/kotlin/org/rust/lang/core/types/infer/Expressions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

TY: Correct infer types of byte literals `b'a'` and `b"abc"`

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

e.g.
```rust
let a = Box::new(0);
let b = *a;
```

TY: Supported overloaded deref

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

This helps in the case of
```
let v = Vec::<u16>::new();
```
which is now correctly typified as Vec<u16>

Consider type parameters in paths when resolving associated items

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

The code added by 2b958e5c090742f (#1747) can be made more clear
by using a destructuring declaration instead of writing
"base.element" in many places.

TY: Use destructuring declaration to clean up newly introduced code

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt

I've failed to pinpoint the actual issue within Cargo: executing a ton
of processes manually works flawlessly. That means that perhaps we do
something different in CLion, but I have no idea what exactly is
different.

Try to fix Cargo deadlock in CLion on windows.

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

In places that expect a *const T it is possible to pass a *mut T due to coercion.
See https://doc.rust-lang.org/nomicon/coercions.html
This fixes a wrong E0308 error when using a *mut T at a points where a *const T is expected.
(function argument, let statement, ...)
CC: #1753

ANN: Coerce *mut pointers to *const pointers to fix a wrong E0308

---

src/main/kotlin/org/rust/cargo/icons/CargoIconProvider.kt
src/main/kotlin/org/rust/ide/icons/RsIconProvider.kt
src/main/resources/META-INF/plugin.xml

1) Make sure that Cargo.toml & Cargo.lock icons work in file chooser
2) Move build.rs to other special crate roots and make it work again,
after yet one another regression due to Java's polymorphic equality

Fix file icons

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/cargo/CargoConstants.kt
src/main/kotlin/org/rust/cargo/icons/CargoIconProvider.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt

Run `xargo` command instead of `cargo` if both `xargo` binary is available and cargo project directory contains `Xargo.toml`.
Closes #1477

CARGO: Adding `xargo` support

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/inspections/RsVariableMutableInspectionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsNumericLiteralTypeInferenceTest.kt

In places that expect a pointer it is possible to pass a reference due to coercion.
Coercion can also remove mutability.
See https://doc.rust-lang.org/nomicon/coercions.html
&T     -> *const T
&mut T -> *mut T
&mut T -> *const T

Coerce references to pointers

---

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
src/main/kotlin/org/rust/ide/inspections/RsDanglingElseInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsMissingElseInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsSuspiciousAssignmentInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/SubstituteTextFix.kt

This is important because a fix might be not recalculated after whitespace-only changes.

Use relative offsets in `SubstituteText` fix.

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsSelfParameter.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

The self parameter of a method can be written in a short hand and in an explicit variant.
The explicit variant also supports a special case for Box<Self>.
```
self      -> self: Self
&self     -> self: &Self
&mut self -> self: &mut Self
-         -> self: Box<Self>
```
Fix type the inference for this explicit type syntax on the self parameter.

Support explicit self type in method parameter 

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt
src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt

Due to a typo we would not react to src/lib.rs being created.
This would cause us to not refresh our cargo workspace / crate roots.
(WorkspaceImpl.targetByCrateRootUrl)
This in turn could cause a wrong error
"Cannot declare a new module at this location"
because src/lib.rs would not be recognized as crate root.
Fixes #1638

CARGO: Refresh the cargo project when src/lib.rs is created or deleted

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt

Also, allow colorized command output without forcing colorization.
Resolves #1824, #1822.

CARGO: use new channel syntax

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/RustChannel.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt

Rustup channel names are case sensitive. Remove distinction between actual
channel names and their UI caption (with initial capitals).
Resolves #1827

CARGO: Fix channel selection command lines

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoCommandLineTest.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt

I was unable to debug a program in CLion because it was not possible in the Run Configuration dialog box to set parameters to pass to the application being debugged.
I added a new "Run Arguments" field to the dialog box, plumbed it through to both run and debug mode, and tested as much as I could with IntelliJ (I'm not sure how to debug it in CLion, but it appears to launch with the correct parameters...)

Resolve #1587: It is not possible to debug applications with command line parameters

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

Added the completion of semicolons after a function in a use statement. 
Fixes #1856

[COMP] added semicolon completion when completing a function in use statement

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/core/overrideImplement/ImplementMembersFixTest.kt

Fixes #1895.
Properly include `unsafe` keyword when implementing trait methods.

COMP: Implement unsafe methods.

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt

Fixes #1945 
Some preliminary refactoring were done in #1946 and #1947.
So, what the hell is going on here, and why am I so excited about this issue? :) 
We use `CargoWorkspace` as our project model. Workspace is a hierarchical structure `Workspace > Package > Target`. Here are some useful properties about it:
1) It's logically immutable and tread safe (there's some caching of virtual file happening for perfromance).
2) Packages have dependencies on each other, which creates a graph data structure. 
3) Targets and packages have backlinks to containing package and workspace, to make it easy to go not only in Workspace > Package > Target direction, but int the opposite one as well.
Crucially, 2) and 3) imply that the data structure is cyclic. Together with 1), it poses an interesting …

Correctly rebuild workspace when adding stdlib

---

src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsNamingInspectionTest.kt

Renaming macros and lifetime parameters works quite well.
So enable the quick fix which offers to automatically rename the item.

INSP: Enable automatic fixing of macro and lifetime parameter naming conventions

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPathReferenceElement.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsBinaryOpReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsExternCrateReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLabelReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLifetimeReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMetaItemReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsModReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReference.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReference.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceCached.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsUseGlobReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

And some references refactoring. Now the one reference that can `advancedResolve` is path reference

Delegate method/field resolution to type inference engine

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

The PR make this `default` call to be resolved to the particular impl of the `Default` trait for `String`.
```rust
let a: String = Default::default();
```
And even more complicated stuff:
```rust
let a = From::from;
let b = a("");
let c: String = b;
```
Yes, this compiles by rustc and `from` now resolved to the particular impl `From` for `String` =)
Same with UFCS.
And the same approach should also be applied for regular method calls.
Really the current implementation does not suit me very much. It looks a bit ugly. Discussion is required =D

RES: resolve UFCS & assoc fn calls to a particular impls

---

src/main/resources/META-INF/plugin.xml

We have it in resources for two years, but haven't actually enabled
it via plugin.xml =/

Enable Rust file template

---

ARCHITECTURE.md
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt

When the explicit path ends with "/mod.rs" then resolving inside this module would be broken.

Improve handling of explicit #[path = "foo/mod.rs"] attribute

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandler.kt
src/main/kotlin/org/rust/openapiext/Testmark.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Sooo, I've got this idea a while ago (actually, I've stolen it from Dart), that it would be cool to connect certain tests and `if`s in code, to get precise coverage information. Today I've figured out that it can be 90% done without some custom code-generation tricks. 
What do you think?
cc @vlad20012 @Undin @mkaput

T: add Testcrumbs to make testsuite more resilient to refactorings

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt

Addresses issue #2042
Changes the AssertEqualInspection refactor suggestion to append the rest of the argument list.
Originally, applying the refactor would pull apart the binary expression and replace it with two args, but any subsequent args on the assert were deleted.
(this is my first PR to this project so I wanted to start small)

INSP Apply assert arg on refactor of AssertEqualInspection

---

src/main/resources/META-INF/plugin.xml

The latest plugin versions support only 2017.2 and 2017.3 builds but plugin.xml says that plugin supports 2017.1 as well.
This change fixes it.
Fixes #2031 (I know that it is already closed:) )

Correct since build value

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt

All `RsPreciseTraitMatchingTest` tests now passes
1. We now filter methods of traits that are not imported
2. We now check trait bounds of impls
We do not do anything above if we don't have method name ambiguity, i.e. name resolution succeeded with exactly single entity

Method ambiguity resolution

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Some infrastructure for this was prepared in #1997 and #2058. Additionally now we resolve ambiguous trait impls during trait selection
@Undin, it's done =)

RES: Enable `impl<T: Bound> for T`

---

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt

It's nice to find one day that _disabled_ inspections don't work as we expect :)

INSP: Fixed type mismatch annotations style

---

CONTRIBUTING.md
src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt
src/main/kotlin/org/rust/ide/newProject/ConfigurationData.kt
src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt
src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
src/main/resources/META-INF/plugin.xml

Partially closes #557 
This implementation should work with:
* **PyCharm Community** (checked with 172.4343.24 and 173.3727.88)
* **PyCharm Professional** (checked with 172.4343.24 and 173.3727.88)
* **PyCharm Edu** (checked with 172.4539)
* **WebStorm** (checked with 172.4343.25 and 173.3727.69)
* **RubyMine** (checked with 172.4155.44 and 173.3727.77)
* **PhpStorm** (checked with 172.4155.41 and 173.3727.84)
Unfortunately, project creation in **CLion** still **doesn't work**

PRJ: support rust project creation in small IDEs

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

Allow ambiguity in trait bounds checking

---

src/main/kotlin/org/rust/cargo/CargoConstants.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt

It helps tools like clippy, which use their own RUSTC. Historically,
this was implemented because not everyone was using rustup, and, thus,
not everybody had `rustc` in PATH, but hopefully this is not a problem
anymore.
closes https://github.com/intellij-rust/intellij-rust/issues/1941

CARGO: Don't explicitely set RUSTC env var

---

CONTRIBUTING.md

I like tag concept very much and dislike documentation inconsistency with reality

DOC: add 'MACRO' tag in CONTRIBUTING.md

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt

This is embarrassing 😓 
@Undin this might fix the problem with futures.

MACRO: fix stub based code path for macro definition

---

src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
src/main/resources/META-INF/toml-only.xml
src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt

Fixes #1776 
@matklad Any idea to fix the problem with the test?

CARGO: Annotate basic docs in cargo.toml

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/refactoring/implementMembers/ui.kt
src/test/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Hello,
I propose a fix for "Implement members fix lists members that are already implemented" #1989
I'm not sure the change I made in TraitImplementationInfo is the best solution. If someone has a better idea, I will be happy to update my fix.
Guillaume

#1989: Implement trait members - remove already implement members

---

src/main/kotlin/org/rust/ide/actions/RsNewProjectAction.kt
src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
src/main/kotlin/org/rust/ide/newProject/RsProjectSettingsStep.kt
src/main/resources/META-INF/clion-only.xml
src/main/resources/META-INF/plugin.xml

Temporary workaround for new project creation in CLion.
Should be removed when CLion will support not CMake projects.
* Introduce 'New Rust Project' action
* Add this action to welcome screen in CLion because otherwise it can be found only from search

PRJ: create temporary action for new rust project creation in CLion

---

src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

In Rust macros are in a different namespace than names and types.
This change fixes a wrong E0428 error when a macro has the same name
as a module, struct or function.

Fix namespacing of macro definitions

---

src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt

Getting a &mut reference to a function/method works in rustc so we must show an error for it.
Fixes #1858

Do not show errors on &mut ref to a function/method

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddAsTyFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddAsTyFixTest.kt

This commit adds quick-fix for the numeric types mismatch,
which fulfills the first bullet-point of the issue:

ANN: add quick fix on numeric type mismatch

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

We resolve all type aliases in the struct literal and use the actual struct type as result.

Handle type aliases used in struct literals

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFix.kt
src/main/kotlin/org/rust/ide/presentation/Ty.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFixTest.kt
src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt

This commit adds quick-fix for the types mismatch when
impl From<A> for B exists for actual type A and expected type B,
which fulfills the third bullet-point of the issue:

ANN: add quick fix for type mismatch when impl From<A> for B exists

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/psi/RsAttributeTest.kt
src/test/kotlin/org/rust/lang/core/stubs/RsStubAccessTest.kt
src/test/kotlin/org/rust/lang/core/type/RsCoercionTest.kt
src/test/resources/org/rust/lang/core/stubs/fixtures/main.rs

Avoid loading the PSI when reading inner/outer attributes.
Correctly allow and attach comments and inner/outer attributes on various items.
This is in preparation for #2166

Stub and PSI improvements related to inner and outer attributes

---

src/main/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntention.kt
src/test/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntentionTest.kt

Fixed issue when the plugin doesn't insert a comma after unwrapped single expression.
Fixes #2176

INT: insert comma when remove braces from single expr

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToOwnedTyFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToOwnedTyFixTest.kt

This commit adds quick-fix for the types mismatch when
impl `ToOwned` for A exists and B is `Owned` type of A
where A is actual type and B is expected type,
which fulfills part of the forth bullet-point of the issue:

ANN: add quick fix for type mismatch when impl ToOwned for A exists and B is Owned type of A

---

src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt
src/main/kotlin/org/rust/ide/intentions/import/ui.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionStdTest.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

Part of #1737 and #2174
Fixes #2157
TODO:
* support `pub use` with wildcards
* filter import candidates for the same item (for example, `std::sync::Arc` and `alloc::arc::Arc`)

Initial reexports support for auto import

---

CONTRIBUTING.md
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt

Don't filter example targets to allow launching them in debug mode
Fixes #2200

DBG: allow to debug example binaries

---

src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt
src/test/kotlin/org/rust/ide/annotator/RsTypeCheckTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Finally fixes #1753 ([andy-hanson's case](https://github.com/intellij-rust/intellij-rust/issues/1753#issuecomment-331313940))

TY: unify `expected` type with fn/method return type & struct fields

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/annotator/RsTypeCheckTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Note: typecheck is a disabled by default inspection, and this PR **do not** enables it by default =)
Most of bugs with references has been already fixed, so now we can safely enable typecheck for it. 
Also it allows to implement more items from #1730 (c.c @oleg-semenov)
Can be merged after #2209

INSP: enable typecheck for reference types

---

src/main/kotlin/org/rust/ide/inspections/RsVariableMutableInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsWrongTypeParametersNumberInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RemoveMutableFix.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RemoveRefFix.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeParameter.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt

Don't save psi elements directly in quick fix object to avoid potential memory leak
and recalculate them after typing

INSP: fix warnings

---

src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt

@Undin r?
I start working on it. 
- Remove curly braces
- Order using the only path of a UseSpeck
- support optimize of all mod in a file
- sort inner usegroup (first level)
- move use to the top level of a mod
- support merging of imports (no trivial)
- grouping into semantic imports (std, crates, inner mods) (no trivial)
- remove unused imports (possible use anntoation by cargo check) (no trivial)
- next sort mod extern crates

TYPE: Initial import optimizer

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsTraitMethodImplLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt
src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProvider.kt
src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt
src/main/kotlin/org/rust/ide/presentation/Utils.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
src/main/kotlin/org/rust/lang/core/types/RsPsiTypeImplUtil.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionHandlerAction.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/annotator/RsTraitMethodImplLineMarkerProviderTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt
src/test/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProviderTest.kt
src/test/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProviderTest.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt

Allow to navigate from "const" and "type" in trait impl blocks to the according place in the trait the same way we already do for "fn".
Also slightly improve documentation and the breadcrumb bar entries related to "const" and "type".
This is a preparation for #2163

Improve navigation around const and type in traits

---

src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspectionTest.kt

Improve `Different impl member order from the trait` inspection highlighting to underline only `impl Trait for Type` part instead of the whole impl element

INSP: highlight only part of impl 

---

src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt

IntelliJ IDEA complains about this, so I removed it.
CLA will come later, since the sign-up form is currently broken.
Since the fix is so small and should not actually change anything, I am unsure which prefix to pick from https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#commit-messages

Fix self-assignment of state in RustProjectSettingsServiceImpl

---

CONTRIBUTING.md

Change the names to reflect what the actual plugins are called, to simplify search for future contributors.
CLA will come later, since the sign-up form is currently broken.

DOC: Fix names of recommended plugins in contributor docs

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/openapiext/utils.kt

Current beta/nightly cargo returns paths relative to workspace directory but stable returns paths relative to project dir.
This fix takes into account these changes to add links in console properly

RUN: Fix console links

---

src/test/kotlin/org/rust/lang/core/stubs/RsStubExistenceTest.kt

Check that stubs for exprs/literals are exists/not exists in
some places
Merge it after end of 2017.2 support

T: added stub existence test

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt

PSI: 'Not all trait items implemented' checks items only by their names

---

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt

to correctly take into account changes related to `crate` visibility introduced in #2284

Increase stub version

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Fixes #2144
```rust
fn main() {
let a;
a = 0;
a;
} //^ i32
```

TY: Fixes #2144 var with later initialization

---

src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt
src/main/kotlin/org/rust/ide/intentions/import/ui.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionStdTest.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTestBase.kt

These changes allow collecting items which are reachable via module reexports
```rust
mod foo {
mod bar {
pub mod baz {
pub struct FooBar;
}
}
pub use self::bar::baz; // <- reexported module
}
fn main() {
let x = FooBar;  // <- now auto import can find correct import path `foo::baz::FooBar`
}
```
Note: these changes don't intent to support module reexports with alias and reexports with wildcard

INT: Support module reexports

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt
src/main/kotlin/org/rust/ide/intentions/import/ui.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionStdTest.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTest.kt

* Take into account inner attributes of module (fixes #2299)
* Fix import of generic items
* Allow importing enum variants

INT: Auto import improvements

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConverToStringFix.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConverToStringFixTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFixTest.kt

This commit adds quick-fix for the types mismatch when String is
expected type and impl `ToString` for actual type exists.
This fulfills part of the 2nd bullet-point of the issue:
Also unifying naming of couple of Fixes.

ANN: add quick fix on String type mismatch

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToStrFix.kt
src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToStringFix.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToStrFixTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToStringFixTest.kt

This commit adds quick-fix for the types mismatch when `&str`
or `&mut str` is expected type and `String` is actual type.
This fulfills part of the 2nd bullet-point of the issue:
Also fixing the name of ConvertToStringFix class.

ANN: add quick fix on str/String type mismatch

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/ide/presentation/Ty.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsAssocTypeBinding.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsAssocTypeBindingReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/stdext/Collections.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt

We now support this stuff:
```rust
trait Tr { type Item; }
fn foo<B: Tr<Item=u8>>(_: B) {
let a: B::Item = 0;
a;
} //^ u8
```
And it's even don't affect performance because of #2287

TY: Support associated type bindings

---

build.gradle.kts

This dependency brings stdlib sources and make goto definition for kotlin classes/functions usable

GRD: add compile time dependency on kotlin's stdlib

---

src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/runconfig/RsProjectTasksRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt
src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectAction.kt
src/main/kotlin/org/rust/ide/actions/RsBuildAction.kt
src/main/resources/META-INF/plugin.xml

* build action for small IDEs (if IDE is CLion then the action is available only for 2018.1 and above)
* show `Use cargo check when build project` checkbox in all IDEs

ACT: Implement build action for small IDEs

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Byte string literals like b"Example" are &[u8; ?] arrays.
Currently we infer the array length from the raw text length.
But if the string contains escape characters this will give us
the wrong array length.
Instead first unescape the string and then check its length.
This also requires bumping he stub version
as the literal length is stored in stubs.

TY: Correctly typify length of byte string literals containing escape characters

---

build.gradle.kts

The current way (since #2213) of loading the intellij-toml plugin
from build.gradle.kts requires a fix for
JetBrains/gradle-intellij-plugin#238.
But the current latest stable version 0.2.18 of gradle-intellij-plugin
does not yet contain this fix.
This causes toml support to not work during development.
Go back to the old way of loading the intellij-toml plugin
until a bugfix version of intellij-toml containing the fix is released.
See JetBrains/gradle-intellij-plugin#258 for more details.

Add a workaround for loading of the intellij-toml plugin

---

src/main/kotlin/org/rust/ide/intentions/import/ImportNameIntention.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionStdTest.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/import/ImportNameIntentionTestBase.kt

part of #1737
* drop useless candidates from stdlib
* don't add import candidate if there is import candidate with reexport from ancestor module

INT: Filter import candidates

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt

After supporting of `impl<T> for T` we've got a tons of irrelevant method completions for ANY TYPE. This PR tries to fix it via trait bounds checking.

COMP: Filter method completion variants by trait bounds of impls

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt

Example:
```
#[lang = "std::iter::Iterator"]
trait Iterator {}
```
... and thanks to this, removed some legacy code that was used in tests only

 Added the ability to set a fake item path in tests via lang attribute

---

src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt
src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
src/test/kotlin/org/rust/ide/actions/RsMoveLeftRightHandlerTest.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt

* implement move left/right action for bounds of trait types (trait objects, `impl`/`dyn Trait`)
* support `goto type declaration` for `impl Trait`

Improvements of trait types support

---

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt

Fixes #2082
Temorary replace `<` & `>` with `❮` & `❯`. But I don't sure it's the best possible symbols.

ANN: Fixed #2082 correctly display generic type in tooltips

---

src/main/kotlin/org/rust/ide/formatter/processors/RsStatementSemicolonFormatProcessor.kt
src/test/kotlin/org/rust/ide/formatter/RsStatementSemicolonFormatProcessorTest.kt

FMT: redundant semicolon in match expression

---

src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsNumericLiteralTypeInferenceTest.kt

Now we corrrectly resolve method calls on unconstrained integers/floats, e.g. `0.foo()`.
Also a part of #1806

TY&RES: find impls for unconstrained integers/floats

---

src/main/kotlin/org/rust/ide/inspections/fixes/import/AutoImportFix.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt

Now we ignore primitive types in a path if all path is a primitive type name.
But when primitive type name is part of path, for example `f64::abs`,
we highlight it as an unresolved reference because our resolve can't resolve primitive types.
This fix checks if base path is a primitive type name instead of full path
Fixes #2367
Fixes #2388

INSP: don't highlight paths with primitive type name

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/inspections/RsReassignImmutableInspectionTest.kt

When variable is assigned with "ref" modifier like `let ref a = ... `, and you apply make mutable quick fix, it will result in wrong `let mut a = ... ` instead of `let ref mut a = ... `.
This PR fixes this issue.

INT: Fix make mutable intention

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Collects already visited type alias elements to prevent infinite loops while resolving fields in struct literals and struct literal type inference

RES & TY: Prevent infinite loops with cyclic type aliases

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFixTest.kt

This commit adds quick-fix for the types mismatch when
`impl TryFrom<A> for B` exists where A is actual type and B is expected
type, which fulfills part of the forth bullet-point of the issue:
https://github.com/intellij-rust/intellij-rust/issues/1730.
The Fix skips suggesting the "TryFrom" when it's implemented through
`impl<T, U> TryFrom<U> for T where T: From<U> { type Error = Infallible; ...}`, 
since the regular "From" should is already suggested in those cases.

ANN: add type mismatch quick fix using TryFrom

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFixTest.kt

Related to #1730. 
- better (strict) API for trait selection
- use autoderef to select traits, e.g.
```rust
fn main() {
let a: Box<Cow<str>> = ...;
let b: &str = a; // suggest to insert `.borrow()`
}
```
- TryFrom fix implemented without `convert::Infallible`, that was recently removed from stdlib

ANN: improved Quick fixes on type mismatch

---

src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

INSP: don't highlight generic params by unresolved reference inspection

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt

This uses `--all-targets` for error/warning annotations and to build/check the project.  
Fixes #1433 
Fixes #2178

ANN: Build/check all targets for both annotations and project build.

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt

This commit add CheckBox for controlling `-Zoffline` flag passed to `cargo check` and `cargo build` commands (usually invoked by Ctrl+F9). It may be useful in some situations.

Add support for offline checking/building on Ctrl+f9

---

src/main/kotlin/org/rust/cargo/project/configurable/RustProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt

Macros now can be disabled in the plugin settings

MACRO: added an option to disable macro expansion

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

TY: Fixed type of `vec![1; 2]` macro

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

Really this commit as a first experiment with
expression-context macro expansion and type inference inside macros
Fixes #2229
Fixes #2452 
Fixes #2461

TY: Fixed `write!` & `writeln!` macro return type

---

src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt
src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt

We currently put a space between the '?' and 'Sized' so it looks like "T: ? Sized".
rustfmt does not add a space, so lets match its behavior.
Fixes #2377

FMT: Do not put a space between '?' and 'Sized'

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

When typifying `vec![0; 1]` we would trigger `error("Trying to infer expression type twice")`
in `RsExpr.inferType(expected: Ty?)`
This is because `inferChildExprsRecursively(expr.macroCall)`
already typified all children inside the vec[] and
`vecArg.exprList.firstOrNull()?.inferType()`
would typify the first child a second time.
Adapt a test from #2469 that was not actually testing vec![] repeat mode.
Fixes #2500

TY: Do not cause IllegalStateException when typifying vec![0; 1]

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

This makes typification of enums honor repr attributes like `#[repr(u16)]`.

Support setting the enum discriminant type via #[repr(u*)] attribute 

---

MAINTAINING.md
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettingsConfigurable.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/resources/META-INF/clion-only.xml

Loads pretty printers into IDE debugger to show values of rust variables in more convenient for user way. `rust-gdb` and `rust-lldb` use the same pretty-printers.
Some samples:
**lldb (without pretty-printers)**
**gdb (with rust pretty-printers)**
**lldb (with rust pretty-printers)**
It's still far from perfect when lldb is used because doesn't allow to see separate elements of `Vec` but it's better than now
Fixes #2140

DBG: load default pretty printers for rust

---

src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorTest.kt

Currently `cargo check` command with `--all-targets` can generate the same messages.
The previous implementation of `RsCargoCheckAnnotator` didn't take into account it and created an annotation for each `cargo check` message.
Now it uses only unique messages
Fixes #2503

ANN: Show only unique annotations by 'RsCargoCheckAnnotator'

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
src/main/kotlin/org/rust/cargo/project/model/DetachCargoProjectAction.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectStructure.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectStructureTree.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt
src/main/kotlin/org/rust/cargo/runconfig/command/RunClippyAction.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt
src/test/kotlin/org/rustSlowTests/CargoProjectStructureTest.kt

* Show workspace members and targets in cargo toolwindow
* Allow running targets from cargo toolwindow by double click
TODO:
* Come up with icons for target nodes
Fixes #2151

UI & CARGO: Improve workspace tree

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt

Shows error messages in the following cases:
* Debug toolchain is not configured. It prevents the following error
* Rust toolchain is `msvc`
Currently, CLion doesn't support debugging with `msvc` toolchain. Also in this case `rustc` generates `.pdb` file and adds it in artefact list (now it's reason why we show weird error message about multiple binary files). I do nothing with such files intentionally to support them properly when `msvc` toolchain will be supported by CLion
Fixes #2462

DBG: improve error messages for debugger

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

We currently expand macros textually instead of based on AST nodes
as rustc does.
This can cause problems where the macro expansion interacts badly
with operator precedence rules and produces wrong results.
For example this code (from the documentation of write!())
```rust
let mut s = String::new();
let a = write!(&mut s, "text");
```
would be wrongly expanded to
```rust
let a = &mut (s.write_fmt(...))
```
and typified as `&mut Result<(), Error>`
instead of
```rust
let a = (&mut s).write_fmt(...)
```
and being typified as `Result<(), Error>`.
Work around this problem by surrounding all expressions with parenthesis
during expansion.
CC #2229

MACRO: Surround expressions with parenthesis during macro expansion

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyWithDerefsRefsFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToTyWithDerefsRefsFixTest.kt

This commit adds quick-fix for the types mismatch when getting from
an actual type to an expected type is possible through a seuence of
dereferences and references, which fulfills the fifth and sixth
bullet-points of the issue:
https://github.com/intellij-rust/intellij-rust/issues/1730.

ANN: add type mismatch quick fix using derefs and refs

---

src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt

INSP: Make the "Convert to assert_(eq|ne)!" fixes not kick in for non-Debug types

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

This makes sure that renaming a lambda parameter, with text occurrences,
does not touch comments outside the lambda expression.
Fixes #2557.

TYPE: Narrow the search scope of lambda expression parameter bindings

---

src/main/kotlin/org/rust/ide/inspections/RsAssertEqualInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/StdKnownItems.kt
src/main/kotlin/org/rust/lang/refactoring/extractFunction/RsExtractFunctionConfig.kt
src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/RsFieldInitShorthandInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/RsSimplifyPrintInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/RsTryMacroInspectionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsPrimitiveTypeImplsTest.kt

* Move some code related to core traits from `ImplLookup` into `StdKnownItems`
* Hardcode impls of some core traits:`Copy`, `Clone`, `Default`, `Hash`, `PartialEq`, `Eq`, `PartialOrd` and `Ord` for primitive types
* Add tests to check impls of core traits for primitive types
* Check types implement `PartialEq` trait in `RsAssertEqualInspection`

TY: Improve primitive types impls

---

src/main/kotlin/org/rust/cargo/runconfig/filters/RsExplainFilter.kt
src/main/kotlin/org/rust/ide/annotator/RsCargoCheckAnnotator.kt
src/main/kotlin/org/rust/ide/icons/RsIconProvider.kt
src/main/kotlin/org/rust/ide/projectView/RsTreeStructureProvider.kt
src/main/kotlin/org/rust/lang/RsConstants.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
src/main/kotlin/org/rust/lang/refactoring/RsDowngradeModuleToFile.kt
src/main/kotlin/org/rust/lang/refactoring/RsPromoteModuleToDirectoryAction.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ take into account path attribute.xml

In the following case
```rust
//- main.rs
#[path="bar.rs"]
mod foo;
//- bar.rs
fn foo() {}
```
fully qualified name of `foo` function is `foo::foo`.
But currently, we don't take into account module declaration and its attributes and return file system name as mod name for file. Because of it we return incorrect `bar::foo` in case above.
This change fixes it.
Fixes #2584

ModName should take into account #[path] attribute of mod declaration

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt

See also: https://github.com/rust-lang-nursery/rustfmt/commit/5d9f5aa05a668e7dfef87b46d89dad2884df9d41
Fixes #2579

rustfmt: use write-mode and skip-children flags only when supported

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinition.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt
src/test/kotlin/org/rust/ide/docs/RsDocumentationProviderTest.kt
src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt
src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt

It's initial implementation - it provides links only for stdlib items and it doesn't support reexports (as well as all our quick documentation does).
It means:
* we generate link according to a fully qualified name of resolved item and don't take into account its reexport path. For example, we generate https://doc.rust-lang.org/alloc/string/struct.String.html instead of https://doc.rust-lang.org/std/string/struct.String.html. It's not a big problem, because doc.rust-lang.org provides very similar pages for both links.
* we don't provide links to element from private module but available only via reexport. For example, `Iterator` trait.
Also, it's the first part of big plan to generate fully qualified name with similar schema as documentation link.
Part of #1875

QDOC: Provide links to external documentation

---

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToBorrowedTyWithMutFixTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTraitFixTestBase.kt

This commit makes the quick-fixes that use BororwMut and AsMut traits
to be applicable only for truly mutable expressions. This fixes part of
the: https://github.com/intellij-rust/intellij-rust/issues/2472

ANN: Only allow BororwMut and AsMut quick-fixes on mutable expressions

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt

* Create quick documentation html using `DocumentationMarkup`
* Use `h2` and `h3` tags for sections instead of `h1` and `h2` respectively
**Before:**
**After:**

QDOC: update quick doc layout

---

src/main/kotlin/org/rust/lang/core/macros/ExpansionResult.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModificationTrackerOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeInferenceCachingTest.kt
src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt

Now we will invalidate type inference cache only if a current function or program structure was changed. I.e. if we type in some function, inferred types of other functions will not be flushed.
Should fix most of "high CPU usage" issues

PERF: introduce fn-local modification trackers

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
src/test/kotlin/org/rust/ide/docs/RsStdlibResolveLinkTest.kt

Rust doc comments may contain relative links like `struct.String.html`, `#method.clear`, `../../std/macro.vec.html`, etc.
Currently, we don't process them and final documentation text in quick doc contains relative links
which can't be opened.
These changes do the following things:
* resolve all relative links with base URI, where base URI is constructed from current item path
* use `psi_element://` scheme to make quick doc processes such links
* try to parse link content in `RsDocumentationProvider#getDocumentationElementForLink` into `RsQualifiedName` and find `RsElement` with the same qualified name object.
Note: a lot of links in stdlib provide paths based on reexports. This implementation does **NOT** support such path, i.e. `RsDocumentationProvider#getDocumentationElementForLink` …

QDOC: initial support of documentation links

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/openapiext/utils.kt

Use own `testAssert` function instead of kotlin stdlib `assert` to throw assert error only in unit tests.
Also it allows us to calculate test action only if needed

T: testAssert function

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/toolchain/CommandLineExt.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt

* Add `RustcInfo` property to `CargoProject` object which contains rustc sysroot and version
* Move sysroot computation from `Rustup` to `RustToolchain` because we should have ability
to get sysroot without rustup

CARGO: improve cargo project and toolchains api

---

src/main/kotlin/org/rust/ide/formatter/blocks/RsFmtBlock.kt
src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt

`Nullable` annotation was added on `com.intellij.formatting.ASTBlock#getNode()` recently.
It brokes kotlin source compatibility because now kotlin considers that `ASTBlock#getNode()` returns nullable type instead of platform type.

Fix compatibility with 182 IDE sources

---

src/main/kotlin/org/rust/lang/core/macros/ExpansionResult.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMembers.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/refactoring/implementMembers/impl.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
src/test/kotlin/org/rust/lang/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Now we can expand macros in this context:
```rust
impl Foo {
foo!();
bar!();
}
```
and can resolve method generated by these macros.
Also fixed some inspections to work properly with members defined by a macro.

Expand macros in trait and impl bodies

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
src/main/kotlin/org/rust/stdext/Profiling.kt
src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt

Use `rustStructureModificationTracker` for macro resolve cache invalidaiton.
Also measure average time of references resolution after typing over all functions in file.
It should show more representative result because resolution in single function can depend on not all
cases and such measurement can mislead us

PERF: macro resolve cache invalidation

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

`ProgressManager.checkCanceled()` is used to cancel (by throwing an
an exception) the current task. I.e. if user requested completion
and then canceled it. This call is often found in the platform (e.g.
in ResolveCache we call `checkCanceled()` on each cache lookup),
so we can decide that it is cheap and its use is good practice.
In this commit I've added `checkCanceled()` to some possible
long recursive/loop operations like type inference.

PERF: Added several `ProgressManager.checkCanceled()` calls

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
src/main/kotlin/org/rust/ide/inspections/RsReassignImmutableInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/stdext/Collections.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotatorTest.kt
src/test/kotlin/org/rust/ide/inspections/RsReassignImmutableInspectionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsMemoryCategorizationTest.kt

Add mutability categories support for checking assignments to immutable memory (see [mem_categorization.rs](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/mem_categorization.rs)).

Add mutability categories

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt

This bug led to extremely deep types and IDE freeze/OOME

TY: fixed wrong `Self` substitution inside traits

---

src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
src/main/kotlin/org/rust/lang/core/macros/ExpansionResult.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/docs/RsDocumentationProviderTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt

Actually resolve items defined with a macro to the corresponding
macro call

RES: make "go to declaration" works with items defined with a macro

---

src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
src/test/kotlin/org/rust/ide/inspections/RsTypeCheckInspectionTest.kt

TY: fixed typecheck false-positive when matching with string literal

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

Fixed crash on typecheck error from expanded macro (like `write!()`)

---

src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt

PRJ: make stdlib selection button inactive when if rustup available

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt

We should be very careful with `stub` getter...

Fixed possible NPE in `RsAbstractable.owner`

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

This works for `"33".to_owned().parse().un<caret>`
This change may also affect the current results of type inference failures. Previously we can often see something like `<T as Iterator>::Item` in types and it mostly meant that type is inferred incorrectly. Now we will show only `<unknown>`
Fixes #2425

COMP: Don't filter completion for partially unknown type

---

src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLifetime.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RsNeedlessLifetimes.html
src/test/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspectionTest.kt

Checks for lifetime annotations which can be removed by relying on lifetime elision.
Corresponds to [needless_lifetimes](https://github.com/rust-lang-nursery/rust-clippy/wiki#needless_lifetimes) lint from Rust Clippy (see [lifetimes.rs](https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/lifetimes.rs)).
Also implements quickfix for removing needless lifetimes.

INSP: Needless lifetimes inspection

---

src/main/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsReassignImmutableInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RsAssignToImmutable.html
src/test/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspectionTest.kt

Add `RsAssignToImmutableInspection` corresponds to [E0594](https://doc.rust-lang.org/error-index.html#E0594) Rust error.

INSP: Assign to immutable inspection

---

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt
src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionGroup.kt
src/main/kotlin/org/rust/ide/intentions/RsElementBaseIntentionAction.kt
src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/intentionDescriptions/RsShowMacroExpansionIntention/after.rs.template
src/main/resources/intentionDescriptions/RsShowMacroExpansionIntention/before.rs.template
src/main/resources/intentionDescriptions/RsShowMacroExpansionIntention/description.html
src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
src/test/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentionBaseTest.kt

Add actions and intentions for expanding simple (non-procedural) macros. 
Actions are available via right-click context menu.
~~WIP: no test yet.~~
UPD: Simple tests are added.

MACRO: Macro expansion actions and intentions

---

src/main/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentions.kt

Macro expansion can take some time, that is why we run it in background with progress window.
However, progress window cannot be shown in write action, so we have to disable write action mode for macro expansion intentions.

MACROS: Make macro expansion intentions start not in write actions

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: treat `self` and `Self` as identifiers in macro matching

---

src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

Currently, we add prelude from `std` crate to all modules.
But if crate has `#![no_std]` or `#![no_core]` attributes we shouldn't do it.
In the case of `#![no_std]` compiler implicitly adds prelude from `core` crate and
in the case of `#![no_core]` compiler does nothing.
Also, there is unstable `#[prelude_import]` attribute that used in `std` and `core`
to explicitly add some custom prelude (actually, it is used to add prelude of `std` and `core`
to the corresponding crate because they use `#![no_std]` and `#![no_core]` respectively)
These changes implement similar logic as compiler uses. Note, we don't search
`#[prelude_import]` and just add `std::prelude` to `std` and `core::prelude` to `core` crates.

RES: use correct prelude module

---

src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/CommandLineExt.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
src/main/kotlin/org/rust/ide/notifications/Utils.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/cargo/commands/CargoFmtTest.kt
src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
src/test/kotlin/org/rust/lang/RsTestBase.kt

* Add panel for rustfmt with options to use `--skip-children` flag
* Use `rustfmt` directly instead of `cargo fmt` to reformat only one file
* Allow a user to install `rustfmt` from IDE
Fixes #2761

CARGO: improve rustfmt formating

---

src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt
src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt

Use `TyUnknown` instead of original type parameter.

Fix substitution in pattern matching

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsMemoryCategorizationTest.kt

Add `category` to `Cmt` (category, mutability, and type); implement memory categorization cache.
Some parts of memory categorization are unused now, but they will be necessary for borrow checking.

Implement categorization of expressions

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

Some crates depend on another version of the same crate. For example, `rand 0.3` and `num-traits 0.1`.
And currently, name resolution of `extern crate` item for such transitive dependencies returns two items: `lib.rs` of the current crate (it's wrong) and `lib.rs` of transitive dependency (correct resolution). It leads to broken resolution and completion for a user because such crates actively use reexports from their transitive dependencies which we fail to resolve.
These changes fix this bug. Now we don't add a lib target of the current crate to resolve results while extern crate resolution inside the lib target, i.e. we ignore `lib.rs` of `rand 0.3` while resolution `extern crate rand` inside `lib.rs` of `rand 0.3` because it refers to `lib.rs` of `rand 0.4` (transitive dependency of …

RES: fix extern crate resolution with several versions of the same crate in dependencies

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddCrateKeywordFix.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/MockEdition.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTest.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddFeatureAttributeFixTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/FixUsePathsFixTest.kt

* check and quick fix to use the corresponding feature (edition 2015)
* check and quick fix if `crate` keyword is missed (edition 2018)
* improve "`crate` is allowed only at the beginning" annotation to highlight using `crate` keyword in non root use group

INSP: Crate in path inspections

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/inspections/RsAnchoredPathsInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/AddCrateKeywordFix.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RsAnchoredPaths.html
src/test/kotlin/org/rust/ide/inspections/RsAnchoredPathsInspectionTest.kt

Because there isn't a final decision about paths in `use` items, it was decided to move related code annotation into separate inspection and disable it by default not to generate false positive annotations.
When new path design will be fixed, we will adopt inspection (if it is necessary) and enable it

INSP: move checks for anchored paths to separate inspection

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/lang/core/macros/LazyStatic.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt

Adds macro expansion support for multiple `lazy_static` declarations in the same block.
I'm not sure how to go about writing a new test for this, since it seems that `RsResolveTestBase#checkByCode()` does not support resolving multiple symbols.

MACRO: expand multiple `lazy_static` definitions in the same call

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
src/test/kotlin/org/rust/cargo/RustWithToolchainTestBase.kt
src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt

After each refresh add `src`, `examples`, `tests` and `benches` folders
of each workspace package as source roots and `target` folder as excluded folder
Fixes #2493
Fixes #2869

Improve content roots detection

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/colors/RsColorSettingsPage.kt
src/main/kotlin/org/rust/ide/colors/RsColors.kt
src/main/kotlin/org/rust/ide/highlight/RsHighlighter.kt
src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
src/test/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotatorTest.kt

Resolves the TODO I left in 2 years ago; naming mostly follows java's color menu.
This also added highlighting for constants and unsafe (as requested by https://github.com/intellij-rust/intellij-rust/issues/2814).
`./gradlew :runIde` looks good, but `./gradlew :test` segfaults, so I'm banking on CI to cover this.
Figured out the syntax from [GroovyColorSettingsPage.kt](https://github.com/JetBrains/intellij-community/blob/4999f5293e4307870020f1d0d672a3d35a52f22d/plugins/groovy/src/org/jetbrains/plugins/groovy/highlighter/GroovyColorSettingsPage.kt)
Closes #2814

Group syntax highlighting options into collapsible menus.

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/ide/inspections/import/ui.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
src/test/kotlin/org/rust/ide/docs/RsStdlibResolveLinkTest.kt

* Move `ImportItem` class and related code from `AutoImportFix.kt` into `RsQualifiedNamedElement.kt` as `QualifiedNamedItem` to reuse logic with reexport in fully qualified links resolution
* Partially support resolution of fully qualified links in quick documentation.

QDOC: Reexports in doc links

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/openapiext/utils.kt
src/main/kotlin/org/rust/toml/CargoTomlCompletionContributor.kt
src/main/kotlin/org/rust/toml/CargoTomlDependencyCompletionProvider.kt
src/main/kotlin/org/rust/toml/CargoTomlKeyReferenceContributor.kt
src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
src/main/kotlin/org/rust/toml/CratesIoApi.kt
src/main/kotlin/org/rust/toml/RsTomlKeysCompletionProvider.kt
src/main/kotlin/org/rust/toml/Util.kt
src/test/kotlin/org/rust/toml/CargoTomlCompletionContributorTest.kt
src/test/kotlin/org/rust/toml/CargoTomlCompletionTestBase.kt
src/test/kotlin/org/rust/toml/CargoTomlDependenciesCompletionTest.kt
src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt

With this PR we should be able to complete versions of dependencies in cargo toml when caret is placed to toml value position, i.e.
```
[dependencies]
rand <caret>
rand = <caret>
rand = "<caret>"
[dependencies.<caret>]
<caret>
```
Fixes #2856

Improve dependencies completion in Cargo.toml

---

src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspectionTest.kt

Fix tuple categorization: add deref adjustments, use index as field name

---

.idea/runConfigurations/Generate_Parser.xml

We had problems with the fact that the lexer did not re-compile
by "Generate Parser" IDEA run configuration.

GRD: build the rust lexer in addition to parser by IDEA run config

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoPackageIndex.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/ide/search/RsCargoProjectScope.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt

* Introduce cargo project search scope
* Use this scope to exclude transitive dependencies' items from auto import candidates

INSP: don't search initial items for auto import in transitive dependencies

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

INSP: insert use items after outer attributes in auto import quick fix

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

I need some help with this. I believe I have found the correct place to perform this type
inference, but I'm not sure how to proceed. I believe what needs to happen is to look up
a declaration that matches the struct field's name, and then if it matches, tell the type
inference system that the type of the variable is coercible to the field's type, but I
could not figure out how to do this.

Unify types of shorthand struct fields

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2015.kt

Our implementation already processes std/core crates so with lookup into workspace
it leads to multiple resolution results and prevents from success resolution of all items in std/core crates
Fixes #2877

RES: Don't search std/core crates in workspace in 2018 Edition

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Partially fixes #2876
(at least it fixes typechecker false-positive)

TY: force to <unknown> type of multi-resolved PathExpr

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt

Due to the fact that completion results are now filtered by trait bounds, the fact that IJ-Rust don't understand auto traits (Sync/Send) may be awkward. I think it's better to temporary make any type Sync/Send and then see more completion than less.

TY: derive auto traits (Sync/Send) to all types

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt

```rust
trait Tr { type Item; }
impl<T> Tr for T { type Item = (); }
struct S;
fn main() { let a: S::/*caret*/; }
```
In this case associated types aren't allowed ([E0223](https://doc.rust-lang.org/error-index.html#E0223)). I think we should remove them from completion, but resolve them as previously. It allows to simply implement E0223 analysis in future

COMP: filter associated types from completion where they aren't allowed

---

src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

1. Filter private fields
2. Filter `#[doc(hidden)]` items

Improved completion filtering by visibility

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

TY: coerce type in tuple and array expressions

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/typing/RsAngleBraceHandlers.kt
src/main/kotlin/org/rust/ide/typing/RsAttributeParenthesisHandler.kt
src/main/kotlin/org/rust/ide/typing/RsBraceTypedHandler.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/typing/RsAttributeParenthesisTypedHandlerTest.kt

This PR implements issue #2715 for completing parentheses typed inside of attributes (`#[]` and `#![]`).
Please let me know if there are any edge cases I may have missed or extra tests that I should add! :)
@Undin

Attribute parenthesis completion

---

src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt

If the elements of the graph contain string, for example `print!("Hello");`, then the output becomes syntactically incorrect.
Escaping solves this problem.

Fix output in graph description written in the DOT language

---

src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/BoundElement.kt
src/main/kotlin/org/rust/lang/core/types/Substitution.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt

Just few renames.
Part of #2828.

TY: Use name 'lifetime' when it comes to RsLifetime or RsLifetimeParameter, and name 'region' in other cases

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/main/kotlin/org/rust/stdext/Collections.kt
src/test/kotlin/org/rust/lang/core/type/RsTyTraitObjectRegionTest.kt

Provides a region for [TyTraitObject](https://github.com/intellij-rust/intellij-rust/blob/294ce3e58c853537404dbcd46bf2d804a7d7b5f3/src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt#L28).
This is part of #2828.
For details, see [RFC#0599](https://github.com/rust-lang/rfcs/blob/master/text/0599-default-object-bound.md).

TY: TyTraitObject region

---

src/main/kotlin/org/rust/lang/core/resolve/Processors.kt

Lazy `ScopeEntry.element` is never accessed from different thread,
so we don't need synchronization here

Make `RsResolveProcessor.lazy()` non thread safe

---

src/main/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsReassignImmutableInspection.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/inspections/RsReassignImmutableInspectionTest.kt

Just some small cleanup. I hope this is allowed.
Related to #1732, I believe. I think this handles the last cases of hard coded "[E0000]" strings. There are a few other cases in `RsWrongLifetimeParametersNumberInspection.kt`, which I handled in #2937.
I've also changed the error message of E0384 to match the output by Rust.

Clean up error annotation handling.

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt

- don't fill struct that can't be instantiated (have private fields)
- insert `&` for reference types
- fixed trailing commas
- fixed possible NPEs

ANN: Improve "Add missing fields" quickfix:

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt

This fixes cache invalidation after replacing a line with comment
(`ctrl+/`)

Fix inc rust structure mod tracker on element replacement

---

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt

I don't know why `reformatText` works better then `reformatRange`, but the last really fails on `table!` macro from diesel

ACT&MACRO: fix expansion formatting in 'show macro expansion action'

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable configuration uses default environment.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable producer works for bin.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ executable producer works for example.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ hyphen in name works.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main fn is more specific than test mod.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ main mod and test mod have same specificity.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ meaningful configuration name.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ producer use complete function path.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ take into account path attribute.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test configuration uses default environment.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer adds bin name.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer ignores selected files that contain no tests.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for annotated functions.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for files.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for modules.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for multiple files.xml
src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ test producer works for root module.xml

Closes https://github.com/intellij-rust/intellij-rust/issues/2812.
Makes the `--all-features` option enabled by default and applies it only to tests.

RUN: Enable `--all-features` option in run configuration

---

src/main/grammars/RustParser.bnf
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

This allow macro definitions to be expanded from macros.
Resolve isn't supported, only expansion for now
bors r+

MACRO: allow macro definitions in macro expansions

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/macros/RsErrorChainMacroExpansionTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt

These fixes allows to almost completely expand `table!` macro from diesel.
Note that this PR brings extremely awful hacks around $crate metavar expansion.

MACRO: some fixes in macro expansion

---

src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt
src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt

TYPE: don't move use items before `{` in inline modules while import optimization

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

The current implementation of name resolution doesn't take into account the following use group in use items while path resolve.
It leads to multiple resolution results for paths before use group when there are several items with the same name but different namespace.
In the following case
```rust
mod foo {
pub fn bar() {}
}
fn foo() {}
use self::foo::{bar};
```
we get multiple resolution for `self::foo` path and fail to resolve `bar` because of it.
Current changes fix wrong namespace for such paths and fix multiple name resolution.
Fixes #2864
Fixes #2981

RES: more precise namespace for paths in use items

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

Currently log macros are hardcoded in our grammar and we
can't really expand them. The problem is that std contains
macro with name `debug` that is not "log" macro, and we should
be able to expand it

MACRO: expand log macros

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLifetime.kt
src/main/kotlin/org/rust/lang/refactoring/RsNamesValidator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Part of https://github.com/intellij-rust/intellij-rust/issues/2550.

TY: Do not mark `'_` as undeclared lifetime

---

build.gradle.kts
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddFeatureAttributeFixTest.kt

* Add `updateCompilerFeatures` task to update compiler features
* Update compiler features not to annotate `crate` keyword in paths since rust 1.30

Support 'crate in path' in 2015 edition

---

build.gradle.kts
debugger/src/main/kotlin/org/rust/debugger/PrettyPrinters.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettingsConfigurable.kt
prettyPrinters/lookup.py
prettyPrinters/providers.py
src/main/kotlin/org/rust/ide/update/UpdateComponent.kt
src/main/kotlin/org/rust/openapiext/utils.kt

Current version of [LLDB pretty-printer for Rust](https://github.com/rust-lang/rust/blob/master/src/etc/lldb_rust_formatters.py) is very primitive. For example, it doesn't support children-based representation of data (synthetic children).
I started to develop a new LLDB pretty-printer for Rust. This PR adds:
* `Vec`: size as summary and elements as synthetic children;
* `String` and `&str`: value as summary, also supports UTF-8;
* Regular structures, arrays, and slices: LLDB already supports it.

Add bundled pretty-printers for LLDB

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt
src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt

Fulfilled #2259 improvement (the last checkbox).
Add the ability to group imports by semantics (std, crates, inner mods, etc.)
Groups order: [here](https://github.com/isamborskiy/intellij-rust/blob/ce89a6cb41477c480edf0dfdb2d9285fc394084e/src/main/kotlin/org/rust/lang/refactoring/RsImportOptimizer.kt#L113)
Examples: [here](https://github.com/isamborskiy/intellij-rust/blob/ce89a6cb41477c480edf0dfdb2d9285fc394084e/src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt#L293) and [here](https://github.com/isamborskiy/intellij-rust/blob/ce89a6cb41477c480edf0dfdb2d9285fc394084e/src/test/kotlin/org/rust/lang/refactoring/RsImportOptimizerTest.kt#L317)

ACT: add ability to group imports by semantics for import optimizer

---

build.gradle.kts

It should help to avoid accidental using of java API which leads to `NoClassDefFoundError` in small IDEs

GRD: exclude jars related to java support from classpath

---

.travis.yml
appveyor.yml
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/stdext/Utils.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

Resolve all symlinks in packages and targets.
Also, resolve symlinks before any call of `LightDirectoryIndex` to use the same virtual files as we use while index creation
Should fix #2466, but I don't know how to create good tests for this case
Fixes #2633

Support symlinks better

---

prettyPrinters/lookup.py
prettyPrinters/providers.py

This PR adds  `tuple` and `enum` support to LLDB pretty-printers.
This implementation still doesn't work in some cases due to compilers' (debuggers'?) bugs. I've opened the corresponding [issue](https://github.com/rust-lang/rust/issues/55586).

Bundled pretty-printer for LLDB: tuple and enum support

---

src/main/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntention.kt
src/test/kotlin/org/rust/ide/intentions/RemoveParenthesesFromExprIntentionTest.kt

INT: don't show "remove unnecessary parens" for struct literals in for-loop iterator

---

build.gradle.kts
src/182/main/resources/META-INF/platform-plugin.xml
src/183/main/resources/META-INF/platform-plugin.xml
src/main/resources/META-INF/plugin.xml

Also, create an additional xml file for each platform version to support features only for a specific platform version. It should be useful when some extension point or other code is not available in some old (but still supported) platform and it's impossible to declare this features in plugin.xml

GRD: setup resources for additional source sets

---

prettyPrinters/lookup.py
prettyPrinters/providers.py

This PR adds `VecDeque` support to LLDB pretty-printers.
Merge after #3008.

Bundled pretty-printer for LLDB: VecDeque support

---

prettyPrinters/lookup.py
prettyPrinters/providers.py

This PR adds `Rc` and `Arc` support to LLDB pretty-printers.
Merge after #3017.

Bundled pretty-printer for LLDB: Rc, Arc support

---

src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
src/main/kotlin/org/rust/ide/formatter/settings/RsCodeStyleSettings.kt
src/main/kotlin/org/rust/ide/formatter/settings/RsLanguageCodeStyleSettingsProvider.kt
src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt

This allows the intellij-rust formatter to better approximate the rustfmt formatter,
which by default aligns where clauses with the parent declaration.

Add formatter setting for indenting where clauses

---

src/183/test/kotlin/org/rust/ide/search/RsUsageViewTreeTest.kt
src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt

Currently the "Group by usage type" option in the Find window is broken.
Each result is placed in its own group.
Fix this problem
This also includes the following smaller changes:
- Support `macro call` usage.
- Change `trait ref` to `trait reference` to it better align with the `type reference` usage type.
This fixes #2672

Fix Usage grouping in the "Find" window

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsBinaryOpReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLabelReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLifetimeReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceCached.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt

The most important thing is that this change opens the way
for even more precise cache invalidation. For example, we can make
specific cache for macro resolve, which is invalidated only
by changes that can affect macro resolve (e.g. module structure)

PERF: make RsResolveCache invalidation a bit more precise

---

prettyPrinters/providers.py

Fix printer's failure on empty `&str`.

Bundled pretty-printer for LLDB: fix empty &str printing

---

prettyPrinters/providers.py

Fix `StdRefSyntheticProvider`: `value` was computed incorrectly for `Ref` and `RefMut`.
The problem was that `valobj.GetChildAtIndex(0)` doesn't always correspond to `valobj.Dereference()`. For example, it was working for `Ref<i32>`, but not for `Ref<&str>`.

Bundled pretty-printer for LLDB: fix Ref provider

---

build.gradle.kts
src/main/resources/META-INF/copyright-only.xml
src/main/resources/META-INF/plugin.xml

Closes https://github.com/intellij-rust/intellij-rust/issues/2524.
Also provides copyright formatting settings for Rust files.
Note, Copyright plugin is not available in CLion (see the corresponding [issue](https://youtrack.jetbrains.com/issue/CPP-10423))

Copyright plugin support

---

src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt

TY: Fix isMovesByDefault on copyable type parameter

---

src/182/main/kotlin/org/rust/lang/doc/RsCodeFenceProvider.kt
src/183/main/kotlin/org/rust/lang/doc/RsCodeFenceProvider.kt
src/183/test/kotlin/org/rust/ide/docs/RsCodeHighlightingInQuickDocumentationTest.kt
src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt

Implement code highlighting in rust quick documentation.
In fact, it uses rust lexer to wrap some code tokens into `span` tag with the same styles as `RsHighlighter` provides. So, if you change color settings, it will also change code highlighting in quick documentation window.
Note, it's available since 2018.3 because the corresponding platform code appeared only in 2018.3
Closes #2501

QDOC: Highlight code in quick documentation

---

src/main/kotlin/org/rust/ide/typing/RsBraceMatcher.kt
src/test/kotlin/org/rust/ide/typing/RsBraceMatcherTest.kt

Looks like there was a typo inside the `InsertPairBraceBefore` set: there was no `RBRACK`, but two `RBRACE`s 😄

TYPE: insert pair brace before ']'

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

Fixes this case:
```rust
mod foo {
pub fn bar() {}
}        //X
use {{foo::{{bar}}}};
fn main() {
bar();
} //^
```

RES: Fixed use items with nested groups without paths `use {{foo}};`

---

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt

Two previous PRs (#3133 and #3103) increased stub version independently to the same value.
It can lead to stub parsing error if stubs were created by code of one of these PRs.

STUB: bump stub version

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

RES: fix private reexport with starts with `crate::`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

ANN: implement members qfux: use `Self::` instead of `<Self as T>::`

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddMutableFixText.kt

fixed #3184
This test failed on my computer which is macos 10.14.1 with rust stable 1.31.0 .
```
org.rustSlowTests.CargoProjectResolveTest > test resolve feature gated crate FAILED
java.lang.IllegalStateException: Failed to resolve the reference `libc` in `src/main.rs`.
at org.rustSlowTests.CargoProjectResolveTest.test resolve feature gated crate(CargoProjectResolveTest.kt:323)
```

add mut fix

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

Heyo, just thought I'd add the other two macro token types.
They weren't supported, as so macro expansion doesn't work at all in intellij, but with this it should be as good as it was before.
[rust macro parser](https://github.com/rust-lang/rust/blob/master/src/libsyntax/ext/tt/macro_parser.rs#L900)

Add support for lifetime and literal macro token types.

---

src/main/kotlin/org/rust/ide/intentions/FillMatchArmsIntention.kt
src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt

Maybe we should generate a wild arm in the absence of else branch? Now the absence of this arm leads to an error [E0004](https://doc.rust-lang.org/error-index.html#E0004).

INT: Fix 'if let to match' intention

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddMutableFixText.kt

Fixes #3186.
T: Added a test for this behaviour.

`Add mut` quick-fix now retains the reference's declared lifetime.

---

src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt
src/main/resources/postfixTemplates/PrintlnPostfixTemplate/after.rs.template
src/main/resources/postfixTemplates/PrintlnPostfixTemplate/before.rs.template
src/main/resources/postfixTemplates/PrintlnPostfixTemplate/description.html
src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt
src/test/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateTest.kt

I've decided to add a postfix template for creating a `println` macro for the expression applicable.
I've kept the implementation as generic as possible so that similar macros as `eprintln`, `format` would be easy to add, but this can be done later in a separate PR, after the current one is considered to be normal.
There are two minor issues I've faced when writing the tests:
1. One is the commented out test with a  `fixme` commend in it - looks like type resolution does not work as intended in this case hence macro template is not applicable.
The case seems to be rather minor though and can be fixed separately.
2. I've failed to use `Parameterized` test, so I had to leave the tests as they are now. Does not seem to be a big issue also, since all the tests are still there, but I have no …

Add println postfix template

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Trait bounds for non-base types (e.g. references) was ignored for a some reason.
```rust
struct S;
trait Foo<T> {}
impl Foo<i32> for &S {}
fn foo<'a, T1, T2>(t: &'a T1) -> T2 where &'a T1: Foo<T2> { unimplemented!() }
fn main() {
let a = foo(&S);
a;
} //^ i32
```

TY: support trait bounds for complex types

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/ext/RsPolybound.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt

Co-Authored-By: vlad9486 <vlad9486@gmail.com> (#3049)
```rust
trait Bar {
fn bar(&self);
//X
}
trait Foo where Self : Bar {
fn foo(&self) { self.bar(); }
}                      //^
```
This is NOT a fix for #2530 b/c we still ignore fn-level Self bounds

TY&RES: Take into account super traits defined with where clause

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

The case of wildcard macro import `use foo::*` was untested for a some reason and did not work =/
Fixes #3210

RES&MACRO: fix import macros with wildcard use item

---

src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt

Fixes error highlighting in this case:

INSP: Fix `Unresolved Reference` error highlighting

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt

This allows us to to correctly report an error `E0277` for the following code:
```rust
fn foo(a: str) { }
```

TY: Do not implement the trait `Sized` for `str`

---

prettyPrinters/providers.py

The `NonZero` wrapper [was removed](https://github.com/rust-lang/rust/commit/7a0911528058e87d22ea305695f4047572c5e067) from `Unique` and `NonNull`, so current LLDB pretty-printers (for `String`, `Vec`, `VecDeque`, `Rc`, `Arc`) don't work on `rustc 1.33.0-nightly`.

Fix LLDB printers due to removed NonZero wrapper

---

src/main/kotlin/org/rust/ide/refactoring/RsInPlaceVariableIntroducer.kt
src/main/kotlin/org/rust/ide/refactoring/extraxtExpressionUi.kt
src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt
src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt

1. Replacing `RsExpr` with `PsiIdentifier` leads to problems with parsing result, so now it uses `createExpression`.
2. `MemberInplaceRenamer` may not work correctly when the user starts typing right after introducing a parameter. So it was replaced with `RustInPlaceVariableIntroducer` (also providing all suggested names).

Fix expressions replacing inside introduce refactorings

---

src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt

When the `..` is placed at the start or the middle of the pattern,
we assign types as if the `..` was not there at all.
When the `..` is placed ad the end, types are already correct.
See: https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#ignoring-remaining-parts-of-a-value-with-
CC #3281

TY: Add tests for ignoring values in tuple destructuring

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Currently the plugin adds extra lifetimes when processing the functions with reference types with no parameters.
Example: [`Debug` trait, `fmt` method](https://doc.rust-lang.org/std/fmt/trait.Debug.html#tymethod.fmt): `fn fmt(&self, f: &mut Formatter) -> Result<(), Error>`
When the implementation is generated by the plugin, the following code is created:
```
fn fmt(&self, f: &mut Formatter<'a>) -> Result<(), Error> {
unimplemented!()
}
```
It seems like the generation should not add lifetimes at all, if they are not defined in the original method, that's what I've tried to achieve with the PR.

Do not add extra lifetimes for the methods implemented 

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt

Relates to https://github.com/intellij-rust/intellij-rust/issues/2463.
Before:
After:

RUN: Force colors on Windows

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

E.g. for associated types:
```rust
trait Foo {
type Item;
fn foo(&self) -> Self::Item;
}
trait Bar<A> { fn bar(&self); }
//X
fn baz<T1, T2>(t: T1)
where T1: Foo,
T1::Item: Bar<T2> {
t.foo().bar();
}         //^
```

TY&RES: Fully support trait bounds for complex types

---

src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

We had a problem that if we have multiple `#[macro_export]`
with the same name we resolved to some of them randomly
(really randomly!). Ideally it should be multiresolve.

RES: duplicated `#[macro_export]` macros now unresolved

---

src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt
src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

Now derive for Serialize, Deserialize and Fail work as well as builtin derives.
I think this makes sense even if we'll support procedural macros. Just as an optimization - serde custom derives are very widespread

TY&RES: hardcode `serde` and `failure` custom derives

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

```rust
struct S;
fn main() {
let a = box S;
a;
} //^ Box<S>
```

TY: infer box expr `box Foo`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Perhaps now it is worth moving tests for `isIrrefutable` property from `MatchToIfLetIntentionTest`.

ANN: Irrefutable let patterns error

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

The main reason why it didn't work before is wrong intermediate path creation.
`AutoImportFix#canBeResolvedToSuitableItem` didn't take into account namespace of path
and always tried to create intermediate path via `fn foo(t: $pathText) {}`.
But for paths like `Foo::<i32>::bar` it doesn't work because of syntax error.
Now, it's possible to pass namespace to `RsPsiFactory#tryCreatePath` to correctly create necessary path element
Fixes #3269

INSP: make auto import works for path with type params

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt

In case, when there isn't any trait in scope, we add all potential variants as resolve variants. But sometimes we can filter out some obviously wrong variants. 
These changes don't affect type inference/name resolution for correct code but should improve name resolution/auto import for incorrect code (when all traits are out of scope)
Fixes #3344

TY: more precise trait pick in type inference

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt

Note: this is not about name resolution or type inference. We can only expand (e.g. show expansion) such macros.
Now we can expand statement-like macros. E.g.
```rust
($ i:ident, $ j:ident) => {
struct $ i;
let $ j = 0;
($ i, $ j)
}
}
fn main() {
foo!(S, a);
}
```
I've done it without touching the grammar, but I don't sure in it, may be it's better to create MacroStmt or a something.
Also introduced class MacroExpansion that abstracts macro expansion made in different contexts.
This is also a preparation for #3015

MACRO: expand macros in stmt context

---

debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerTypesHelper.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt

Before these changes "Unresolved reference" inspection added auto import quick fix when path name is already in scope but namespace of psi element prevents correct name resolution. It led to unexpected auto import quick for incomplete code like `let map = HashMap` that can be easily created during typing.
Now the inspection checks the corresponding name is in scope for any namespace in addition to "fair" name resolution not to provide the fix in such cases.
Also, with "Ignore unresolved references without quick fix" property it removes "Unresolved reference" error annotations from unresolved but in scope names.

INSP: do not provide auto import quick fix for names which are already in scope

---

src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/BorrowChecker.kt
src/main/kotlin/org/rust/lang/core/types/regions/Scope.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

Add "Use of uninitialized variable" diagnostic

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

When typing `mod foo {}` this construction can be incomplete and
so will be parsed as module declaration `mod foo` with missed
semicolon. In this case it tries to find "foo.rs" file and
shows E0583 "File not found for module" because it doesn't exist.
I think we should not show this error if semicolon is missed.
We should let user to fix the syntax error or complete inline
module declaration first.

ANN: Non't show E0583 "File not found for module" if syntax error in declaration

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

We parse `vec![]` macro as a specific syntax construction
and previously it was not able to expand custom (non-std)
macros with such name

MACRO: Allow custom macros with name "vec"

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: Fix expansion of macros containing $crate metavar inside a group

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

Very internal stuff related to #3015. After removal of hardcoded macros surfaced some shortcomings of our type inference. This PR currently affects nothing.
// Some tests changed only because they was written without stdlib dependency and so worked wrongly

TY: enforce builtin binop operand types

---

src/main/kotlin/org/rust/ide/actions/RsCreateFileAction.kt

Before these changes new Rust file creation action was always before "New File" action
regardless of context. It can be annoying for some users.
Now it's available only inside cargo project directory.

ACT: make "New | Rust File" action less cocky

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt

2019.1 platform brings dynamic analyzer of incorrect CachedValue usages, which generate crashes on EAPs. This case is false positive, but it's easy to "fix" it anyway, so let's do it.
bors r+

Fix Incorrect CachedValue use report on 2019.1

---

src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotatorTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt

Part of #3129
Also it will be useful if we will start to expand macros in
extern blocks (macros_in_extern)

ANN: don't treat fns in wasm_bindgen extern block as unsafe

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
src/main/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoder.kt
src/main/kotlin/org/rust/cargo/runconfig/RsKillableColoredProcessHandler.kt
src/test/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoderTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/1261 (already fixed?)
Closes https://github.com/intellij-rust/intellij-rust/issues/1630 (?)
Fixes https://github.com/intellij-rust/intellij-rust/issues/1966
Fixes https://github.com/intellij-rust/intellij-rust/issues/2463
Fixes https://github.com/intellij-rust/intellij-rust/issues/1842 (does it work as expected?)
Thanks @kumbayo for [this](https://github.com/intellij-rust/intellij-rust/issues/1966#issuecomment-445550757) comment!
TODO:
* Fix issue with white color on Windows
Looks like a Rustc issue.
macOS Mojave:
```
^[[0m^[[1mFor more information about this error, try `rustc --explain E0369`.^[[0m
```
Windows 10:
```
^[[0m^[[1m^[[38;5;15mFor more information about this error, try `rustc --explain E0369`.^[[0m^M
```
As you can …

Handle 8-bit and 24-bit ANSI color escapes in console

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/3403.

ACT: Try to group auto-inserted use item with existing ones by last component

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

TODO do something with `rustStructureModificationTracker` usage in `ProjectCache` and `RsMacroIndex`

Fix cache invalidation in language injections

---

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/ide/actions/RsEnterHandler.kt
src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/main/kotlin/org/rust/ide/injected/RsSimpleMultiLineEscaper.kt
src/main/kotlin/org/rust/ide/injected/RsStringLiteralEscaper.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/ide/typing/RsEnterInLineCommentHandler.kt
src/main/kotlin/org/rust/lang/core/RsASTFactory.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt

We now thinking about code inside Rust doctests as if it is a valid Rust code, with all IDE intelligence like highlighting, completion, intentions, linting, etc.
Unresolved questions:
- postprocess reformatting is not work in injections. It means that after the most of intentions/quickfixes the code will not be formatted and so will looks ugly. Should we disable intentions/quickfixes inside injections because of this? (I think we can ignore it for now, and then fix something in the platform)
- some intentions/quickfixes can edit PSI outside of injection that leads to crashes. But I think it is smaller part of them, and we can disable specific actions if they will not work.
- Typing enter inside injections does not insert an indent at the next line. 
About testing: This is mostly manually …

LI: inject Rust language to doctests

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt

This marking is needed for generated code that will be inserted to real PSI by intentions/etc. Then postprocess formatting will be invoked on marked code only. In macro expansions (and other generated code that is not intended to be used in intentions/etc) we totally don't need it. It just consumes additional memory for storing such marks in user data of each PSI element.

PERF: Don't mark macro expansions as generated code

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt

In fact, it changes nothing because `RsLitExprImpl` already implements `ContributedReferenceHost` via `RsLitExprMixin` but now it's part of our public API

PSI: `ContributedReferenceHost` for `RsLitExp`

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt

QDOC: correct doc urls for primitive and primitive methods

---

.travis.yml
src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt
src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
src/test/kotlin/org/rust/ide/docs/RsStdlibResolveLinkTest.kt
src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorPassTest.kt

* fix external doc URLs generation for macros defined in non crate root (like `assert_eq` or `write`)
* fix documentation link resolution when link refers to a macro defined in non crate root
Note, `OLD_RUST_VERSION` was increased to 1.28 because:
* before 1.28 stdlib uses special attribute to reexport macros. It fails the corresponding test
* we also need 1.28 as minimal rustc version because of #3490

QDOC: improvements in macro quick documentation

---

src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt

It can be too annoying that this intention is available
inside all doctest injections

INT: Make "unelide lifetimes" intention unavailable in doc comments

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt

This PR fixes an error in the `Nest use statements` intention mentioned here: https://github.com/intellij-rust/intellij-rust/issues/2577#issuecomment-469150465.
Before the intention would change this code:
```
use foo;
use foo::bar;
```
into
```
use foo::{foo, bar}`;
```
which is incorrect.
Now it checks if the grouped path is the same as the base path and converts it to `self` if necessary.

INT: handle conversion of module to self in nest use intention

---

idea/src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt
src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/ide/actions/ToggleCargoCheckAction.kt
src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
src/test/kotlin/org/rustSlowTests/RsCargoCheckAnnotatorPassTest.kt

Before these changes, there was only one way to change almost all properties of `RustProjectSettingsService`:
get `data`, create new one with necessary changes and set new instance to the settings.
Because of `RustProjectSettingsService.Data` is immutable, you have to create new instance via constructor or `copy` method.
But any changes in class lead to `java.lang.NoSuchMethodError` in external code
because signatures of constructor and `copy` method are changing accordingly
These changes provide setter for each property (i.e. make each property mutable)
It should be enough to change any property and do not touch `RustProjectSettingsService.Data` class

Provide binary compatible API for Rust project settings

---

src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt

RUN: Get rid of "Use cargo check when build project" option

---

src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt

At this moment, if gson throws `JsonSyntaxException` while cargo message parsing
we get only exception without any info about json content.
These changes should provide json text in error message

CARGO: log `JsonSyntaxException` exception

---

src/test/kotlin/org/rustSlowTests/RsHighlightingPerformanceTest.kt
src/test/kotlin/org/rustSlowTests/RsRealProjectAnalysisTest.kt
src/test/kotlin/org/rustSlowTests/RsRealProjectTestBase.kt

This PR adds new test `RsRealProjectAnalysisTest` for testing our inspections and error annotators on real rust projects. It allows to easy find possible false positives produced by some new analysis. Currently, we have a LOT of false positives with existing analysis. These false positives should be fixed eventually. 
These tests are disabled on CI because they are very slow and because they are always fails (due to existing false-positives). Use it manually when adding some new analysis or changing behavior of an existing one.

T: test our analysis on real rust projects

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt

Fixes
```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field $dep in class org.rust.lang.core.resolve.ref.RsResolveCache$getCacheFor$1 has non-equivalent values:
LOCAL and
LOCAL_AND_RUST_STRUCTURE
Either make equals() hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:158)
at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:129)
at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:125) …
```

Fix "Incorrect CachedValue use" error in resolve cache

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: support `?`-groups

---

src/main/kotlin/org/rust/ide/inspections/RsSimplifyBooleanExpressionInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/SimplifyBooleanExpressionFix.kt
src/main/kotlin/org/rust/ide/intentions/SimplifyBooleanExpressionIntention.kt
src/main/kotlin/org/rust/ide/utils/BooleanExprSimplifier.kt
src/main/kotlin/org/rust/ide/utils/ExprUtils.kt
src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/SimplifyBooleanExpressionIntentionTest.kt

* Extract `SimplifyBooleanExpressionFix` from `RsSimplifyBooleanExpressionInspection`
* Extract `BooleanExprSimplifier` from `ExprUtils.kt`
* Split `RsExpr.simplifyBooleanExpression(peek: Boolean): Pair<RsExpr, Boolean>` into two functions:
- `simplify(expr: RsExpr): RsExpr?`
- `canBeSimplified(expr: RsExpr): Boolean`
* Now `simplify` doesn't perform any changes on existing PSI (unlike old `simplifyBooleanExpression`)
* Now `simplify` translates `!(1 == 2)` into `1 != 2`
* Add more tests for "Invert if" intention to specify that user can simplify resulted expression manually

Improve simplify boolean expression

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
src/main/kotlin/org/rust/cargo/runconfig/RsTestRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
src/main/kotlin/org/rust/ide/actions/runAnything/CargoRunAnythingProvider.kt
src/main/kotlin/org/rust/ide/update/UpdateComponent.kt
src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
src/main/kotlin/org/rust/openapiext/utils.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/FileTree.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt

`Preferences > Languages & Frameworks > Rust > Rustfmt > Run rustfmt on Save`
Also, now rustfmt uses the `rustfmt.toml` from the corresponding cargo project root.
Relates to https://github.com/intellij-rust/intellij-rust/issues/1087.

RUN: Run rustfmt on the document before saving

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: allow to expand std macros (outside of std)

---

intellij-toml/src/main/grammars/TomlLexer.flex
intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/numbers.toml
intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/numbers.txt

Closes https://github.com/intellij-rust/intellij-rust/issues/3118.

TOML: Support hexadecimal, binary, octal integers and nan/inf floats

---

src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt

Fixes such behavior for `RsStatementUpDownMover`:

Don't jump over multi-line whitespaces in up/down mover

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

(fixes false-possible E0308 in some rare cases)

TY: better coerce types in generic function args

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt

```rust
struct S;
impl S {
fn foo() {}
}    //X
fn main () {
<S>::foo;
}      //^
```
(the first commit is only refactoring)

TY&RES: Fix UFCS-like type-qualified paths (`<T as Foo>::bar`)

---

src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/3570.

RUN: Run rustfmt with UTF-8 charset

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPatField.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPatFieldFull.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

This is fix for some minor problems I have found while working on another issue  
- added references/highlighting of full structure pattern fields(see added test)
- Fixed parser error for tuple being destructured as block struct. Here is valid example that resulted in error in plugin:
```rust
struct A(i32,i32);
fn main(){
let A{0:a,1:b} = A(0,0);
}
```

add references from pattern fields,fix pattern parsing

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

If we aim to support proc macros one day, we have to provide a way to know what macros are imported from what crate, taking into account the fact that procedural macros can be re-exported. 
This PR is a simple bang macro (`foo!()`) resolution enhancement. Now bang macros can be resolved to a procedural macro definition function.
```rust
//- dep-proc-macro/lib.rs
#[proc_macro]
pub fn example_proc_macro(item: TokenStream) -> TokenStream { item }
//- lib.rs
use dep_proc_macro::example_proc_macro;
example_proc_macro!();
//^ dep-proc-macro/lib.rs
```
c.c. @fedochet

MACRO&RES: Resolve bang `foo!()` proc macros to appropriate functions

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceCached.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt

I have to admit that #3059 was a bad idea. We should not rely on PSI modification events. It is an infinite source of bugs. I think we'll use the default `ResolveCache` after rewriting of name resolution engine

Fix cache invalidation bugs; Partially revert of #3059

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt

@ortem I didn't update the borrow checker, but I think it should also take into account [this](https://github.com/intellij-rust/intellij-rust/pull/3543) syntax.

TY: Fix bindings extraction for pat struct

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/inspectionDescriptions/RsDeprecation.html
src/test/kotlin/org/rust/ide/inspections/RsDeprecationInspectionTest.kt

Fulfilled #3564 improvement (the first and second checkboxes):
* Implement [deprecated attribute](https://github.com/rust-lang/rfcs/blob/master/text/1270-deprecation.md) inspection (for both `#[deprecated]` and `#[rustc_deprecated]` attributes)
* Support `#[allow(deprecated)]` attribute to suppress the corresponding warnings
Example:
**Note:** update `PathExpr` in RustParser by adding implementation of `RsOuterAttributeOwner` interface

INSP: add deprecated attribute inspection

---

clion/src/191/main/kotlin/org/rust/clion/profiler/RsCachedPerfFlameChartBuilder.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/RsCachingStackElementReader.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/RsProfilerRunner.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/RsSymbolSearcher.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceNavigatableNativeCall.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/perf/RsPerfNavigatableNativeCall.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/perf/RsPerfProfilerProcess.kt
clion/src/191/main/resources/META-INF/platform-clion-only.xml
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
gradle-191.properties
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoCommandConfigurationExtension.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/RsRunConfigurationExtensionManager.kt
src/main/kotlin/org/rust/cargo/runconfig/RsTestRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/kotlin/org/rust/cargo/util/InstallUtils.kt
src/main/kotlin/org/rust/ide/actions/InstallCargoPackageAction.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/RustProjectDescriptors.kt

Add [CLion's CPU profiler](https://www.jetbrains.com/help/clion/cpu-profiler.html) support (perf on Linux and DTrace on MacOS).
Huge thanks to @KirillTim for help!

Add CLion's CPU profiler support

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt

The bug was introduced in #3556
(the removed code was a kind of legacy that we forget to remove)

Fix possible performance regression in type inference

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt

ANN: fix highlighting of keywords in paths (`crate`/`Self`)

---

src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
src/test/kotlin/org/rust/ide/docs/RsDocumentationProviderTest.kt
src/test/kotlin/org/rust/ide/inspections/RsDeprecationInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt
src/test/kotlin/org/rust/ide/inspections/RsMultipleInspectionsTestBase.kt

Before these changes, `Unresolved reference` and `Different impl member order from the trait` inspections always used AST instead of stubs that led to reparsing all files required for analysis
Now, they use stub in these cases.
Also, file tree based annotation tests check that inspections don't load files (except opened one, of course) while analysis by default

INSP: use stub in inspections if possible

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt

Currently, if I have multiple carets that get autocompleted with automatic imports included:
imports are duplicated for each caret:

COMP: Fix import duplication when multiple carets are used

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt

QDOC: show documentation of the corresponding trait item if element documentation is empty

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt

Fulfilled #3564 improvement (the last checkbox): change text attributes in completion for deprecated elements.
Example:

COMP: change text attributes in completion for deprecated items

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

Related to "Extern Prelude" and 2018 edition (but should work in 2015 edition as well)
Fixes #3421

RES: Fix non-absolute std-qualified path resolution

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

<details><summary>stacktrace</summary>
<p>
```stacktrace
java.lang.StackOverflowError
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$found$1.invoke(ItemResolution.kt:134)
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$found$1.invoke(ItemResolution.kt)
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$found$1.invoke(ItemResolution.kt:134)
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$found$1.invoke(ItemResolution.kt)
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$found$1.invoke(ItemResolution.kt:134)
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$found$1.invoke(ItemResolution.kt)
at org.rust.lang.core.resolve.ItemResolutionKt$processItemDeclarations$f …
```

RES: fix StackOverflow in name resolution

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

This reverts commit ccc5f54d
Fixes https://github.com/intellij-rust/intellij-rust/issues/3635. Reopens https://github.com/intellij-rust/intellij-rust/issues/3470.

Revert "INT: Take into account defaulted type parameters during `Implement members`"

---

clion/src/191/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
clion/src/191/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
clion/src/191/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
clion/src/191/main/kotlin/org/rust/clion/valgrind/RsValgrindRunner.kt
clion/src/191/main/resources/META-INF/platform-clion-only.xml
src/main/kotlin/org/rust/cargo/runconfig/CargoCommandConfigurationExtension.kt
src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/RsRunConfigurationExtensionManager.kt
src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt

Add [CLion's Valgrind Memcheck](https://www.jetbrains.com/help/clion/memory-profiling-with-valgrind.html) support. Works on Linux and on MacOS.
I don't know how to properly install Valgrind on MacOS Mojave, but you can try [this solution](https://stackoverflow.com/a/54818930/10445191).
Merge after #3529

Add CLion's Valgrind support

---

src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt

1. Resolve dependencies inside doctests
2. Fix single `#` excape (when newline after `#`)

Some doctest injection fixes

---

src/183/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
src/191/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
src/main/kotlin/org/rust/stdext/Concurrency.kt

1. Optimize VFS batch
That was an original implementation of VFS batch which I removed because of API difference between 183 and 191 (and 192). But this implementation works faster. So if there will be any problems (including porting on 192), we can roll back to RefreshBasedVfsBatch
2. Split expansion writing into several batches
Now we produce fewer UI freezes
Part of #3628

PERF: optimize VFS batch (macro expansion)

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/test/kotlin/org/rust/RsTestBase.kt

Now it's possible to jump into Rust stdlib sources while debugging.

DBG: Load Rust stdlib sources

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt

Tuple structs (and perhaps maybe other constructs too) previously showed empty parameter hints when being instantiated. This PR adds a condition so that if all the hints are empty, it don't bother to show any. 
Before:
After:

ANN: Don't show empty parameter hints

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/lang/doc/psi/RsDocKind.kt

Put `...*]*...` in code spans to not be parsed as markdown emphasis.

DOC: formatting RustDoc for #trimTrailingAsterisks

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt

This speeds up completion in the case of `vec![]./*caret*/;`

PERF: don't invalidate caches when edition expression contains hardcoded macros

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt

1. Enable `Show import popup` option for Rust.
2. Create file with the following code:
```rust
mod a { pub struct S; }
fn main() { let s = S; }
```
3. Try to import `S` via popup hint.

ACT: Fix AutoImportHintFix for single import-candidate case

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/ext/RsAlias.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

```rust
pub mod foo {
pub trait Foo {}
}
use foo::Foo as _;
fn bar(a: &Foo) {}
//^ unresolved
```

RES: fix underscore import shouldn't bring name to the scope

---

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt

Fixes
```
java.lang.ClassCastException: org.rust.lang.core.psi.impl.RsStructLiteralFieldImpl cannot be cast to org.rust.lang.core.psi.RsExpr
at org.rust.lang.utils.RsDiagnostic$TypeError.derefRefPathFromActualToExpected(RsDiagnostic.kt:202)
at org.rust.lang.utils.RsDiagnostic$TypeError.prepare(RsDiagnostic.kt:119)
at org.rust.lang.utils.RsDiagnosticKt.addToHolder(RsDiagnostic.kt:915)
at org.rust.ide.inspections.RsDiagnosticBasedInspection.collectDiagnostics(RsDiagnosticBasedInspection.kt:24)
at org.rust.ide.inspections.RsDiagnosticBasedInspection.access$collectDiagnostics(RsDiagnosticBasedInspection.kt:14)
at org.rust.ide.inspections.RsDiagnosticBasedInspection$buildVisitor$1.visitFunction(RsDiagnosticBasedInspection.kt:16)
at org.rust.lang.core.psi.impl.RsFunctionImpl.accept(RsFunctionImp …
```

Fix ClassCastException in derefRefPathFromActualToExpected

---

src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt

Commit document before optimize imports to avoid `java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document`.

Commit document before optimize imports

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsInspectionSuppressor.kt
src/main/kotlin/org/rust/ide/inspections/RsLint.kt
src/main/kotlin/org/rust/ide/inspections/RsLintInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsLintLevel.kt
src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/test/kotlin/org/rust/ide/inspections/RsDeprecationInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/naming/RsModuleNamingInspectionTest.kt
src/test/kotlin/org/rust/lang/core/psi/RsAttributeTest.kt

These changes provide `RsLintInspection` - base class for all inspections that should be suppressed by `allow` attribute. This class uses the correct API to suppress warning annotations. Also, it provides suppression quick fixes to add `allow(lint)` attribute to the chosen item. 
Now naming convention and deprecated inspections extend `RsLintInspection` and provide suppression quick fixes.
Note, our parser doesn't correctly parse expressions with outer attributes like
```rust
#[allow(lint)]
foo();
```
so, statement suppression quick fix is not provided in some cases. Should be fixed from grammar side
Fixes #2308

INSP: improve inspection suppression

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

From user side, it fixes multiple variants suggested by auto import quick fix for `HashSet` and `HashMap` structs

INSP: filter out redundant auto import candidates better

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt

`MacroExpansionManager.getExpandedFrom()` is used in `getContext()` which is very hot spot.
Interesting thing is that `VirtualFile.getUrl()` is slow.
Now name resolution isn't slower when new macro expansion engine is enabled

PERF&MACRO: optimize `getExpandedFrom`

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt
src/main/kotlin/org/rust/ide/actions/ui/CargoNewCrateDialog.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/actions/RsCreateCrateActionTest.kt

Hi, I tried implementing an action that would create a new Cargo crate in a project (as described here: https://github.com/intellij-rust/intellij-rust/issues/2944).
It's my first time making a non-trivial contribution to IntelliJ, so please let me know if I made any obvious mistakes.
~~Workspace modification - it would be nice to add the new crate to an existing Cargo workspace, if there is one in the project~~
```toml
[workspace]
members = [
"main",
"new-crate" # this would get added automatically by the action
]
```

ACT: add context menu action to create a new Cargo (sub)crate

---

src/191/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt

The platform VFS uses more precise last-modified file attribute
than java default. We should use `FileSystemUtil.getAttributes()`
or after refresh we will think that expansion files are changed

MACRO: fix file attributes in VFS batch

---

prettyPrinters/gdb_lookup.py
prettyPrinters/gdb_providers.py
pretty_printers_tests/tests/hash_map.rs

DBG: Add HashMap/HashSet formatter for gdb

---

prettyPrinters/gdb_lookup.py
prettyPrinters/gdb_providers.py
prettyPrinters/rust_types.py
pretty_printers_tests/tests/enum.rs

Hi, using the latest versions of Rust and the bundled GDB (Rust 1.34 and GDB 8.2), enums are visualized in a weird way in the synthetic debugger view (it basically prints the discriminant and then all of the possible variants as children). I changed the output so that only the correct enum variant is printed.
The name of the variant is outputted as a child field, since to change the type name of the enum variable itself I would have to change its type and I don't know how to do that (if it's even possible in the GDB API, doesn't seem like so).
Code:
Original output:
New output:
So far I only added support for GDB and there are no tests, I'd like to know what you think about this change and if I implemented it correctly before I go forward. From the code it looked like it already tried …

DBG: add support for printing Enums directly in debugger

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
src/test/resources/org/rust/ide/folding/fixtures/macro.rs
src/test/resources/org/rust/ide/folding/fixtures/macro2.rs

Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>
Before folding:
After completely fold everything:
Only fold `MacroExpansion` blocks:
Before:

TYPE: Fold Macro/MacroExpansion/Macro2

---

build.gradle.kts

Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>
This PR:
+ Fixed a deprecated issue
+ Use `main` instead of `getByName("main")` because it's now added to gradle.kts API back

GRD: General improvements

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
src/main/kotlin/org/rust/ide/inspections/RsFieldInitShorthandInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt

Hi,
I implemented support for smart pointers, Default impl and shorthand init syntax using local variables with same name and type for the Add struct fields fix (https://github.com/intellij-rust/intellij-rust/issues/2311), .
It would be also nice to auto-import the smart pointers if they are not in scope (if we prefill `Rc::new(0)` and `Rc` is not in scope, the user will have to use autoimport after the fix). Any hint on how could I do that? I guess I could run the autoimport action after the fix, but that seems like a heavyweight solution to me.

INT: add support for smart pointers, Default implementation, struct init shorthand and local variable to Add struct fields fix

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

Works for 
```rust
use std::f64;
fn main() {
let a = f64::INFINITY;
}              //^ ...num/f64.rs
```
Fixes #2667

RES: fix disambiguating primitive type qualified paths

---

build.gradle.kts
gradle.properties

It should speed up CI tests and local builds

DBG: disable `buildSearchableOptions` by default

---

src/main/kotlin/org/rust/ide/folding/RsCodeFoldingOptionsProvider.kt
src/main/kotlin/org/rust/ide/folding/RsCodeFoldingSettings.kt
src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/main/kotlin/org/rust/ide/folding/impl/RsCodeFoldingSettingsImpl.kt
src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
src/test/resources/org/rust/ide/folding/fixtures/raw_identifiers.rs

Signed-off-by: ice1000 <ice1000kotlin@foxmail.com>
Before:
After:

TYPE: fold the `r#` in raw-identifiers

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt

```rust
const FOO: i32 = 0;
//^ should be highlighted
```

ANN: fix highlighting of const/static

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt

The bug is introduced in #3705.
It's hard to reproduce right now, but it affects #3640
bors r+

MACRO: fix getExpandedFrom for in-memory expansions

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
src/test/kotlin/org/rust/lang/core/type/RsArithmeticOpsTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

This now works:
```rust
fn main() {
let a = String::new();
let b = String::new();
let c = a + &b;
c;
} //^ String
```
TODO:

TY: better type inference for overloaded binops

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: Fix OOM when expanding incorrect macro with group if `vis`

---

src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt

<details><summary>Fixed issue. Thanks to @vlad20012 and his PR #3804</summary>Currently, for reasons I believe are unrelated to my changes, it only works with the leftmost element of the self parameter (see gif below). I tried to figure out the reason for this, and so far I've discovered that the `getSymbolTypeDeclaration` function is not even invoked for elements other than the leftmost one. I'd appreciate some help on this.
</details>
This closes #3665.

ACT: Added self parameter support to type declaration provider

---

src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt

This PR adds a notification panel that warns about files which are not included in any module tree.
Currently the file has to be re-opened for the notification bar to update.
Corresponding issue: https://github.com/intellij-rust/intellij-rust/issues/1675

TYPE: display notification panel when a file is not included in the module tree

---

src/main/kotlin/org/rust/ide/search/RsReadWriteAccessDetector.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/search/RsReadWriteAccessDetectorTest.kt

This enables read/write categorization of variable usages:
(look at red/green icons next to each usage)

Implement ReadWriteAccessDetector

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBinding.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedFieldDecl.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsStructItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTupleFieldDecl.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RustLifetimeParameterElement.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsAssocTypeBindingReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsExternCrateReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLabelReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLifetimeReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMetaItemReferenceContributor.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsModReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

1. First, by tuning `Rs*ReferenceImpl.isReferenceTo` we say: "this reference is definitely can't be resolve to this element" without resolving the reference. This optimizes find usages of any elements because now we should resolve less references.
2. Optimize "find usages" of type/lifetime parameters by using local scopes. I'd say it was a bug that local scope wasn't used before because of obvious local nature of such parameters.
3. Take into account item visibility. This significantly speeds up "find usages" of private items (**UPD**: only inside modules without child modules for now) and items declared in local scope (i.e. in function bodies, etc)
I don't know how to write tests for it, and I tested performance rather than correctness, so it should be reviewed intently.

PERF: significantly optimize "find usages" (in the broad sense)

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/inspections/checkMatch/Constructor.kt
src/main/kotlin/org/rust/ide/utils/BooleanExprSimplifier.kt
src/main/kotlin/org/rust/lang/core/psi/RsLiteralKind.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLitExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/kotlin/org/rust/lang/utils/evaluation/ExprValue.kt
src/main/kotlin/org/rust/lang/utils/evaluation/RsConstExprEvaluator.kt
src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt

* Save values of literals into stubs when needed. It's useful not only for const expr evaluation but for `include` macro support in future
* Provide common API for const expr evaluation
* Drop confusing `compareTo` method from `ExprValue` public API

Literal stubs & const expr evaluation

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

Fixes resolve of prelude items (e.g. `Some`&`None`) in doctests located in the `core` (stdlib part).
bors r+

LI: fix doctest prelude in libcore

---

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectStructure.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectStructureTree.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt

1. CLEAN: change TargetKind to follow [cargo internal structure](https://github.com/rust-lang/cargo/blob/5a0c31d81/src/cargo/core/manifest.rs#L157)
2. LI: disable doctest injection for not doctestable libs (fixes false-positives inside rust-lang/rust)

LI: disable doctest injection for not doctestable libs

---

src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/parser/util.kt
src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt

This is reasonable for 2015 edition doctests that contain `extern crate` declarations. Previously, such doctests worked due to accident combination of bugs (sic!) but this bug balance was (intentionally) broken in #3768

LI: fix doctests with existing "main" function

---

src/main/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsAction.kt
src/main/kotlin/org/rust/ide/refactoring/RsConvertToNamedFieldsProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferencesSearchExtensionImpl.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt

This is implementation for #3180. I wasn't sure what exactly i was expected to do because no one has answered me in the issue, so I have implemented it in the way i thought would be best. I think usages conversion should not harm but I have added checkbox to disable it. For now i have done only conversion to block struct. And if you like my implementation, I will add other way conversion later.
When I thought that it might be better to implement it as refactoring, I found that there was already a draft implementation in `RsConvertToNamedFieldsAction.kt`. So I just extended it.

REF/INT:add refactoring to convert struct and its usages between block and tuple representation

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementTypeBase.kt
src/main/kotlin/org/rust/lang/core/psi/RsExprCodeFragmentElementType.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

This PR introduces `RsCodeFragment` to be used in `Add format string argument` intention, `Evaluate expression`, and other future stuff.

PSI: Introduce RsCodeFragment

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/runconfig/filters/HighlightFilterTestBase.kt
src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt
src/test/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactoryTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2018.kt
src/test/kotlin/org/rust/stdext/BothEditions.kt

Fixes such hyperlinks in 2018 edition crates or crates containing "-" in the name

 RUN: fix backtrace hyperlinks on 2018 edition

---

debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerEditorsExtension.kt

Add resolve/inference/completion support for `Evaluate expression` and `New watch`.
Merge after #3753

 DBG: Use code fragment instead of plain text

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

CARGO: set 2018 edition for std crates with latest rust versions

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitRef.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt

"resolve" is a verb and so I think function style is better

CLEAN: refactor `resolveTo(Bound)Trait` into function

---

CONTRIBUTORS.txt
toml/src/main/kotlin/org/rust/toml/CratesIoApi.kt

As per [crates.io's crawler policy](https://crates.io/policies#crawlers), all bots must provide a user agent identifying themselves. While sending "Java/1.8.0_202-release" is technically following the policy, it makes it difficult for us to identify the impact this plugin's traffic has on our service, or contact you if we have potential improvements that could be made or changes we need you to make.

Provide a User Agent to crates.io

---

src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/main/kotlin/org/rust/lang/doc/psi/RsDocKind.kt
src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
src/test/kotlin/org/rust/lang/doc/RsDocRemoveDecorationTest.kt

Block documentation comments without `*` infix, e.g.
``` rust
/*!
foo
bar
*/
```
were incorrectly handled by quickdoc and doctest injection. See added tests for particular cases that failed before.

QDOC/LI: fixed block doc comments without infix in quickdoc and doctest

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt

Traits can't be aliased for now, so we can weed out irrelevant
traits by name, without resolving them.
I measured about 5% speedup of highlighting

PERF: filter traits by name before resolve in trait selection

---

src/main/kotlin/org/rust/ide/hints/RsAsyncParameterInfoHandler.kt
src/main/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandler.kt
src/main/kotlin/org/rust/ide/hints/RsParameterInfoHandler.kt
src/test/kotlin/org/rust/ide/hints/RsGenericParameterInfoHandlerTest.kt
src/test/kotlin/org/rust/ide/hints/RsParameterInfoHandlerTest.kt
src/test/kotlin/org/rust/ide/hints/RsParameterInfoHandlerTestBase.kt

Another hack to make "parameter info handler"s asynchronous. Also, gets rid of "Preparing parameter info..." popup
F'ixes #3900

Make parameter info handler asynchronous

---

src/main/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsReassignImmutableInspection.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/test/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/fixes/AddMutableFixTest.kt

INSP: Don't check mutability of expr with unknown type

---

src/main/kotlin/org/rust/ide/intentions/FillMatchArmsIntention.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/ide/intentions/FillMatchArmsIntentionTest.kt

1. Support match ergonomics (`match &Some(1) {}`)
2. Support custom enums with variant names in the scope. Previously only Option/Result was supported this way.
```rust
mod foo {
enum E { A, B }
}
use foo::E;
use foo::E::A;
fn foo(x: &E) {
match x/*caret*/ {}
}
```
=>
```rust
match x {
A => {},
E::B => {},
}
```

Improve "fill match arms" intention

---

src/main/kotlin/org/rust/lang/core/resolve/Processors.kt

These lists almost always consist of 0 or 1 elements. It's a typical case for SmartList

PERF: micro-optimization: use SmartList in `collectResolveVariants`

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

TY&RES: disambiguate trait associated items by scope & trait bounds

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt

Fixes #3925
Works for:
```rust
trait Bound {}
trait Tr {
fn foo(&self) {}
}    //X
impl<A: Bound> Tr for A {}
fn foo<B: Bound>(b: B) {
b.foo();
}   //^
```

TY: fix find free impls for type parameter

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/resolve/RsClosuresResolveTest.kt

Works with:
```rust
fn foo(impl Trait Fn(i32)) {}
fn bar() {
foo(|x| { x })
}
```

TY: fix closure type inference with "impl Trait" parameters

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt

Looks like we should check whether a trait should be
imported or not only when insertion performs, not when
building a completion list

PERF: optimize method completion

---

src/main/kotlin/org/rust/lang/core/stubs/RsPlaceholderStub.kt
src/main/kotlin/org/rust/lang/core/stubs/RsStubElementType.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
src/test/kotlin/org/rust/lang/core/stubs/RsStubTest.kt

```rust
//- main.rs
mod foo;
fn main() {
foo::S.baz();
}        //^ foo.rs
//- foo.rs
pub struct S;
fn foobar() {
if true {
impl S {
pub fn baz(&self) {}
}
} else {
struct S;
}
}
```
Works when `foo.rs` is stubbed

STUB&RES: fix scoped resolve inside stubbed fn body

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Revert #3918. I forget that traits can be aliased with use items :(
bors r+

Revert #3918 "PERF: filter traits by name before resolve in trait selection"

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

Fixes [this](https://github.com/intellij-rust/intellij-rust/blob/96bc6a1321233acf8c0a857a12b7686ffc078581/src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt#L385) assertion failure. In production env it could lead to crashes in other places

Fix possible crash in type inference

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt

The deleted code fragment currently doesn't matter. Try (`?`) checking will be landed later with #2819

Fix false-positive E0308 with `?` expr in lambda with error conversion

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt
src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt

LI: don't inject doctests in targets with `doctest=false` in Cargo.toml

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

Fixes #3948
Looks like we just forgot to adjust autoimport to work with unified paths #3768.
I don't sure how autoimport should work with unified paths. For now, I just add `crate::` prefix to any local path (i.e. use anchored path fashion)

INSP: fix autoimport on 2018 edition

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Fixes #3975
The bug is introduced in #3905
The PR fixes the crash only. I'll fix type inference for this case later.
bors r+

Fix crash in type inference on `Self()` expr

---

src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt

Method `RsReference.isReferenceTo` is mostly untested, but with #3831 it becomes heavily overrode.
This PR adds additional `isReferenceTo` check to all resolve tests. I.e. if some reference "r" is resolved to element "e", `r.isReferenceTo(e)` must be true

T: add checks for `isReferenceTo` implementation to resolve tests

---

src/main/kotlin/org/rust/ide/inspections/RsDropRefInspection.kt

This false-positive unlikely to occur in the real world, but
it's relevant for our unit tests. So this is mostly internal fix
bors r+

Fix false-positive DropRefInspection at unresolved function with no_std

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt

(in the real worlds it's relevant for `cfg`ed trait methods)

INSP: fix false-positive "unresolved reference" if multiple method defs

---

debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt
debugger/src/main/resources/META-INF/debugger-only.xml
src/main/kotlin/org/rust/lang/RsDebugInjectionListener.kt
src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt

DBG: Use RsCodeFragment for gdb/lldb console injection

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

#3932 was implemented wrongly,  so it introduces some bugs. Trying to fix it.
It looks like a rare case but at least it affects some Iterator implementations, e.g. `Iterator.take()`

TY&RES: fix UFCS-like assoc types resolve (`Iterator.take()`)

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
toml/src/test/kotlin/org/rust/toml/CargoTomlKeyResolveTest.kt

Add initial support of `include!` macro. It brings all common code insight features (like name resolution, code completion, etc.) in both including and included files. Also, it should fix false positive editor notification for included files.
Restrictions:
* only string literals are supported as arguments
* `include` macro call should be located only in a module. At this moment, if `include` macro is called in a function, it won't be indexed and as a result, won't be found via the corresponding index. So the current implementation works only with instances of `RsMod`
Fixes #3563
Fixes problems described in #771 and #1078 in certain cases
The initial step of #1908

MACRO&RES: initial version of include macro support

---

clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt
src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/folding/RsCodeFoldingOptionsProvider.kt
src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt

The `ListCellRendererWrapper` deprecation warning is still there :(
The alternative (`SimpleListCellRenderer`) is introduced in 2019.2.

Fix compilation warnings on 2019.1

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt

Initially I've tried to support [`#[macro_export(local_inner_macros)]`](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-using-local_inner_macros) (#3750), but implementation was too slow, so I've tried to cache macro resolution better and accidentally sped it up 3 times... 
`local_inner_macros` is implemented in a separate RP #3750

 PERF: optimize macro resolve

---

.travis.yml

Looks like default Ubuntu version on Travis is Xenial now. And you can't install oraclejdk8 anymore (https://github.com/travis-ci/travis-ci/issues/10290)
Let's use openjdk
Fixes #4018

CI: use openjdk on travis

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/actions/RsCreateFileAction.kt

Hello,
I have updated the caption in `RsCreateFileAction.kt` to Rust File from New Rust File in order to match the rest of the New menu.
This is a very minor change and I think it will be accepted gradually
Before:
After:
Thank you!

[Simple/Enhancement] Rust file caption

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

Clicking `Ctrl+B` on bang proc macro `use` item resulted in duplicating definitions like this: 
This is due to the fact that bang proc macro definitions are counted as macro imports (since #3455), and at the same time the definition itself is a function and seen as a function by resolve 
Proc macro crates cannot import anything other than proc macro definitions, so I've added extra for crate type to prevent dupliaction (but I may be wrong about the way to fix this)

RES: fix duplicating definitions for `use` with bang proc macros

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

The bug was introduced in #3749 - I forgot about completion =/
Also, do not insert extra parens when completing `fo/*caret*/!()` to foo!(/*caret*/)
bors r+

COMP: fix crash during macro completion

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt

Fixes #4036
The bug was introduced in #3935 - not it's forbidden to access `PsiElement.context` in the dumb mode

Fix IndexNotReadyException when typing in the dumb mode

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Previously was implemented in #3473, but then was reverted in #3647.
Fixes #3999, fixes #3470

TY: fix default type parameters

---

src/main/kotlin/org/rust/ide/notifications/DetachedFileNotificationProvider.kt
src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
src/main/kotlin/org/rust/ide/notifications/RsNotificationProvider.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/ide/notifications/DetachedFileNotificationProviderTest.kt
src/test/kotlin/org/rust/ide/notifications/RsNotificationProviderTestBase.kt

Extract "File is not included in module tree, ..." notification introduced in #3826 to separate notification provider and allow to disable such notifications (https://github.com/intellij-rust/intellij-rust/issues/771#issuecomment-496451670)

UI: introduce detached notification provider

---

src/main/kotlin/org/rust/ide/navigation/goto/RsGeneratedSourcesFilter.kt
src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/openapiext/utils.kt
src/main/kotlin/org/rust/stdext/Collections.kt
src/main/kotlin/org/rust/stdext/io.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt

Now we know which element in macro call is expanded to which (real) element in expansion.
Currently it is used only to provide more precise navigation target when navigating to something expanded from a macro:
But soon I'll use it to support go-to-declaration from macro call #2898 (and for other navigation actions), and then this will be used to support hygiene (and so type inference for custom expression-like macros), and in the future this will allow to support highlighting and completion inside macro calls!
This works only if new macro expansion engine is enabled (see #3628 for details).

MACRO: add range mappings between macro call and expansion

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMetaItemReferenceContributor.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

This PR is based on @vlad20012 [draft](https://github.com/intellij-rust/intellij-rust/files/3156357/RES__resolve_derive_macros.patch.zip) for this functionality, and on #3690 
NB: there are problems with resolving proc macro definitions inside proc-macro crates themselves; there are two ignored tests in `RsPackageLibraryResolveTest.kt` that should pass when this will be resolved

MACRO&RES: resolve attribute and custom derive proc macros to their defenitions

---

src/main/kotlin/org/rust/ide/template/RsContextType.kt
src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt

Disable live templates in macro calls and definitions (they shouldn't and anyway previously they worked very weird)
Completion in macro calls will start to work with #4060

Disable live templates in macro definitions

---

src/main/grammars/RustLexer.flex
src/test/kotlin/org/rust/lang/core/lexer/RsRestartLexingTestCase.kt

Make RustLexer support restarting to utilize platform's incremental re-lexing.
@vlad20012 after #3865 I have checked and you were right - our lexer was actually not incremental. So I have fixed it
Here is execution times for highlighting pass on ~200kb file before and after my changes:

PERF:make lexer incremental

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/macros/MacroGraph.kt
src/main/kotlin/org/rust/lang/core/macros/MacroGraphWalker.kt
src/main/kotlin/org/rust/lang/core/macros/Matcher.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementType.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
src/main/kotlin/org/rust/lang/utils/Graph.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroGraphBuilderTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroGraphWalkerTest.kt

This PR adds new completion provider for incomplete macro calls. The provider suggests variants based on possible kinds (`expr`, `ty` and so on) of the fragment under the cursor. If there are several possible kinds, all suitable completions are suggested.

COMP: Add completion in partial macro call arguments

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Reference: rust-lang/rust#60732

Support for arbitrary enum discriminants

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/macros/MacroGraph.kt
src/main/kotlin/org/rust/lang/core/macros/Matcher.kt
src/main/kotlin/org/rust/openapiext/ast.kt

`substituteMacro` now works 2x faster, but it doesn't bring measurable changes to the overall expansion time.

PERF: micro-optimize macro expansion: traverse AST directly

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt

Fixes
```
java.lang.ClassCastException: class org.rust.lang.core.psi.RsFile cannot be cast to class org.rust.lang.core.psi.ext.RsNameIdentifierOwner (org.rust.lang.core.psi.RsFile and org.rust.lang.core.psi.ext.RsNameIdentifierOwner are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @a482658)
at org.rust.ide.annotator.fixes.MakePublicFix.invoke(MakePublicFix.kt:39)
at com.intellij.codeInspection.LocalQuickFixAndIntentionActionOnPsiElement.invoke(LocalQuickFixAndIntentionActionOnPsiElement.java:42)
at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.invoke(IntentionActionWithTextCaching.java:179)
at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.lambda$invokeIntention$4(ShowIntentionActionsHandler.java:2 …
```

INT: Fix `Make public fix` for mod decl

---

.github/ISSUE_TEMPLATE.md
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
src/main/resources/META-INF/plugin.xml
src/test/kotlin/org/rust/RsTestBase.kt

Now it's possible to open Github "new issue" page just from IDE.
It automatically fills info about the environment like IDE, IntelliJ Rust and Rust toolchain versions.
Also, if you have selected code in `.rs` file, it substitutes it into `Steps to reproduce` section

ACT: create new issue action

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsFullMacroArgumentCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/Utils.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
src/test/kotlin/org/rust/lang/core/completion/RsMacroCallBodyCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt

If a macro is successfully expanded we follow element under the caret to the macro expansion and invoke completion there. It allows performing completion taking into account the context of expansion. If a macro isn't expanded (e.g. there is a very incomplete code) completion from #4001 will be used.

COMP&MACRO: advanced completion inside macro call bodies

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt

Fixes
```
java.lang.IllegalStateException: Unrecognized range expression
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferRangeType(TypeInferenceWalker.kt:1043)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:161)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:100)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType$default(TypeInferenceWalker.kt:95)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferIfExprType(TypeInferenceWalker.kt:876)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:152)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:100)
at …
```

TY: Don't throw exception on unbounded inclusive range

---

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
src/test/kotlin/org/rust/lang/core/stubs/RsStubTest.kt

STUB: Fix include indexing

---

src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt

Otherwise, `Create New Issue` produces incorrect markdown text

ACT: add new line after code snippet

---

src/main/kotlin/org/rust/cargo/runconfig/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/RsRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/RsTestRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/3707. Fixes https://github.com/intellij-rust/intellij-rust/issues/3860.
Fixes:
```
java.lang.Throwable: [Cargo Test]: Illegal nodeId: TestSuiteStartedEvent{name='0', id='0', parentId='0', locationUrl='cargo:test://0', running=true}
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:323)
at com.intellij.execution.testframework.sm.runner.GeneralTestEventsProcessor.logProblem(GeneralTestEventsProcessor.java:309)
at com.intellij.execution.testframework.sm.runner.GeneralIdBasedToSMTRunnerEventsConvertor.validateAndGetNodeId(GeneralIdBasedToSMTRunnerEventsConvertor.java:375)
at …
```

RUN: Support doc-tests by test runner

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: detect invalid usages of `impl Trait`(E0562, E0666, E0667)

---

src/test/kotlin/org/rust/MinRustcVersion.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt
src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt

Now it can be used in inheritors of `RsTestBase`. Previously, it was supported only by `RsWithToolchainTestBase`

T: improve `MinRustcVersion` annotation

---

src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
src/main/kotlin/org/rust/openapiext/CommandLineExt.kt

Really #4142 is a [platform bug](https://youtrack.jetbrains.com/issue/IDEA-218430) and I just fixed it in the platform, but I don't know when it will be upstreamed. This PR is a hotfix.
Fixes #4142

Fix freeze with rustfmt on 2019.2 & some rustfmt cleanup

---

src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

TY: Fix inference of full RsPatField and RsPatWild

---

src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt
src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt

Fix comment processing in RsStatementUpDownMover

---

build.gradle.kts
src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementType.kt

Now we don't have any rules with `IFileElementType` except `File` so everything (including `*CodeFragment`s) should parse successfully

Update Grammar-Kit to 2019.2

---

prettyPrinters/gdb_lookup.py
prettyPrinters/gdb_providers.py
prettyPrinters/lldb_lookup.py
prettyPrinters/lldb_providers.py
pretty_printers_tests/tests/hash_map.rs

Pretty-printers for LLDB and GDB: hashbrown's HashMap support

---

prettyPrinters/gdb_lookup.py

Hotfix of #4155. Just disables the `EnumProvider` in case of the invalid discriminant.
@Kobzol I haven't found the proper way to print such enums yet, so I would be really grateful if you would investigate this problem too!

Pretty-printers for GDB: Disable EnumProvider in case of invalid discriminant

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt
src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt
src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/utils/CargoProjectCache.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/kotlin/org/rust/stdext/Cache.kt

Fixes #3544
Currently, we use global `ProjectCache` to cache trait selection results. This leads to bugs when there are multiple cargo projects inside one IDEA project or when we open a file without a cargo project (e.g. virtual file in git diff window).
This PR introduces `CargoProjectCache` (in addition to `ProjectCache`).

Fix #3544 crash in type inference

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt

I found this place in the recent performance investigation. This speeds up type inference performance up to 15% (!!!)

PERF: cache crate root of RsFiles

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt

I forgot to split cache key for macro/non-macro resolve cases in #4179. I think I should make some abstraction to prevent such mistakes in the future...
bors r+

Fix crate root cache

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementType.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt

Simplifies path handling. Also, now it's possible to pass namespaces
to `RsCodeFragmentFactory.createPath`

REF: introduce RsPathCodeFragment, use it in RsCodeFragmentFactory

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

- replace some asserts with `testAssert`s (in hot places)
- avoid unnecessary PSI tree traverse
- remove one useless `PSI.isValid` (looks like it can't be invalid in this place)

PERF: name resolution micro-optimization

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

I found this place during the recent performance investigation. This speeds up type inference up to 30% (!!!) (the baseline is before #4179)

PERF: introduce `RsCachedImplItem`

---

build.gradle.kts
gradle.properties

See https://www.jetbrains.org/intellij/sdk/docs/plugin_repository/api/plugin_upload.html

GRD: use token instead of username/password while plugin publishing

---

.idea/runConfigurations/Test.xml
.idea/runConfigurations/Test_Performance.xml
.idea/runConfigurations/Test_Slow.xml

For some reason, our test run configurations don't work with IDEA 2019.2. It requires to select "intellij-rust.test" module.

Update run configuration for our unit tests

---

src/main/kotlin/org/rust/cargo/runconfig/test/CargoBenchRunConfigurationProducer.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt

This speeds up highlighting up to 5% (the baseline is before #4179)
The approach is similar to #4182 - make more things accessible by one cache key and retrieve them together to reduce **PSI** (in the case of this PR) and cache access in very hot code.

 PERF: reduce PSI tree access in very hot item resolution

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4233.

ANN: Fix E0562 inspection for nested functions

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsModificationTrackerOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt

Previous (default) `strict = true` value really isn't needed, and just slows down performance in the case of `RsModDecl` reference cache

PERF: use `strict = false` in `RsResolveCache`

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt

This speeds up highlighting up to 5% (the baseline is the latest 103 release)

PERF: create `ImplLookup` lazy when resolving paths

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

COMP: move caret insice '()' after method completion in UFCS

---

src/main/kotlin/org/rust/ide/navigation/goto/RsNavigationContributorBase.kt

Until now we used a pretty old API. New API provides more precise
search scopes and implemented in async fashion, so it
can be more responsive

Use new API for go to class/symbol contributors

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFix.kt
src/main/kotlin/org/rust/ide/intentions/AddStructFieldsPatIntention.kt
src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/resources/META-INF/core.xml
src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/after.rs.template
src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/before.rs.template
src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/description.html
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFixTest.kt
src/test/kotlin/org/rust/ide/intentions/AddStructFieldsPatIntentionTest.kt

In this pull request I intend to do the following:
1) Create E0023 and E0027 error classes and implement analysis for them.
2) Create fix for those errors.
3) Create intention for struct fields expansion.
4) Create a module with shared code for using it in the fix and intention.
Once these steps are complete I will squash all the commits and #3928 should be closed after merge.

INT & ANN: Implement intention and fix for struct fields expansion instead of `..`

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/main/kotlin/org/rust/lang/core/psi/RsWithMacroExpansionsRecursiveElementWalkingVisitor.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsStmt.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroBodyReferenceDelegateImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/main/kotlin/org/rust/openapiext/psi.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt

Now we take into account any custom macros in type inference

TY&RES: implement hygiene & infer types in macros

---

src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
src/test/kotlin/org/rust/lang/core/type/RsShortTypeRenderingTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt

This works for ADTs only (struct/enum types). 
Note that I intentionally included `aliasedBy` field in equals/hashCode of TyAdt b/c otherwise there can be caching issues and incorrect types can be shown. However this can bring some bugs with intentions/etc where incorrect type comparison used. If you run into such issue, consider using unification instead of `==`.

Show type alias names in type hints for TyAdt

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

... causing randomly unresolved references
I measured about 2% performance regression. I think it's pretty well.

RES: fix incorrect recursion guard usages

---

src/main/kotlin/org/rust/cargo/CfgOptions.kt
src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTupleFieldDecl.kt
src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
src/main/resources/META-INF/core.xml
src/test/kotlin/org/rust/MockAdditionalCfgOptions.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt
src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt

This PR is based on #2166 (but does not include #2840 and #3031) and adds [cfg attributes](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg-attribute) support to our name resolution. 
Part of #1191
@kumbayo thank you so much for your contribution! We are really sorry that we didn't merge your original PRs at a reasonable time. We've decided to merge the initial part of cfg support (related only to name resolution, without any UI changes) via this PR. So reviewing other cfg-related changes will become more convenient after this PR is merged.
Co-authored-by: Peter Oberndorfer <kumbayo84@arcor.de>

RES: Initial support of cfg attributes

---

src/main/kotlin/org/rust/ide/navigation/goto/RsNavigationContributorBase.kt

Note that looks like I already enabled search for items expanded from macros in the case of "All places" scope in #4275. But this PR enables it correctly for all scopes (e.g. project/library files)

Make "Navigate Class/Symbol" works with items expanded from macros

---

src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt

It calls `guessAndSetupRustProject` function that slows down tests and can break some tests (I ran into such issue recently)

Disable `MissingToolchainNotificationProvider` in tests

---

src/main/kotlin/org/rust/cargo/CfgOptions.kt
src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt

See #4232
Since cargo features should be additive, we can just enable them all for now. At least it should work better than disabling them all.

RES: enable all cfg features by default

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

Fixes this corner case:
```rust
//- trans-lib/lib.rs
pub struct Foo;
//- dep-lib/lib.rs
pub use trans_lib;
//- lib.rs
use dep_lib_target::trans_lib::Foo;
type T = Foo;
//^ trans-lib/lib.rs
```

RES: fix re-exported crate via use item on 2018 edition

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt

Enables support for [`#[macro_export(local_inner_macros)]`](https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-using-local_inner_macros). Works only with the new macro expansion engine (see #3628).
Part of #3611

Support `#[macro_export(local_inner_macros)]`

---

src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
toml/src/main/kotlin/org/rust/toml/CargoTomlGotoSuperHandler.kt
toml/src/main/resources/META-INF/toml-only.xml
toml/src/test/kotlin/org/rust/toml/CargoTomlGotoSuperHandlerTest.kt

ACT: Go to Cargo.toml when invoking "Go to super" in a crate root

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt

The bug was introduced in #4094 (because we used a stubbed statement list) and led to the fact that sometimes all types in some file was not inferred until you type some text there

TY: fix random type inference fails caused by STUB usage instead of AST

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/main/kotlin/org/rust/cargo/toolchain/RustChannel.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/test/kotlin/org/rust/cargo/runconfig/CargoTestRunStateTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/3994
This requires this patch for rust (hopefully in 1.38?): https://github.com/rust-lang/rust/pull/62600
This is work in progress because it doesn't work yet, I'm looking for some help here:
The problem is you can't run `rustVersion()` in the UI thread and I'd really like to have this behavior as default if the compiler is new enough.
What's the best way to achieve this? Fallback would be to make this an option for the run configuration, but that would be a little bit annoying since virtually everyone would want to enable this?
Edit: changed the code to hardcode 1.38 as Rust version passed to `patchArgs` because I'm using this branch ;) Looking for a good way to get the Rust version here.

RUN: enable --show-output when executing tests

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsPatField.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: fix false-positive E0026 on a struct pattern with a raw identifier

---

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt

The bug was introduced in #3750 (not released yet)

Fix switch to AST when resolving nested macro with the new engine

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/macros/Matcher.kt
src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
src/main/kotlin/org/rust/lang/core/psi/LazyElements.kt
src/main/kotlin/org/rust/lang/core/psi/MacroBraces.kt
src/main/kotlin/org/rust/lang/core/psi/RsWithMacroExpansionsRecursiveElementWalkingVisitor.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/openapiext/psi.kt

PoC implementation of lazy parsing, Most likely this doesn't affect users anyhow.
Part of #4355

PERF&GRAM: make macros lazy parseable & reparseable

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

Looks like in #4334 (not released yet) or maybe even in #4190 I made `RsFile.cachedData` "too recursive" (maybe infinite sometimes, don't sure), i.e. access to `RsFile.cachedData` of one file forces computing of `RsFile.cachedData` of a lot of other files, that can impact performance significantly.
Example of a thread dump: [threadDump-20190905-031534.txt](https://github.com/intellij-rust/intellij-rust/files/3584276/threadDump-20190905-031534.txt)

Fix too recursive `RsFile.cachedData`

---

src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt

Generate `IntelliJ IDEA 2019.2.2 Preview Ultimate Edition (IU-192.6603.8)` name and version instead of `IU-192.6603.8`

ACT: improve ide name and version value

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt

Previously, we didn't provide link to external documentation for non-stdlib items because we can't check that the corresponding link exists. But due to https://docs.rs/ automatically builds documentation of crates from crates.io and we already provide links for extern crate items by `RsCrateDocLineMarkerProvider`, I think it's ok always provide such link for all items from non-local dependencies
Closes #4112

QDOC: provide link to external documentation for non stdlib items

---

src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt

Also, add some tests of rustc version parsing
Fixes #4372

CARGO: fix NPE while parsing of rustc commit date

---

README.md

Changes in Readme introduced by this commit:
- 'Status' removed
- 'Installation & Usage': instructions on installing from the IDE and project opening corrected, a link to QSG added
- 'FAQ' removed
- 'Compatible IDEs': rephrased
- 'Contributing': minor wording changes

Update/cleanup in Readme

---

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4345.

TY: Fix type inference for await

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt

Prevents infinite recursive macros.
(More generic fix for #4375)

MACRO: check macro expansion depth during type inference

---

src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
src/main/kotlin/org/rust/ide/typing/assist/SemicolonFixer.kt
src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt

COMP: do not add semicolons to other lines

---

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
src/main/kotlin/org/rust/ide/actions/CargoEditSettingsAction.kt
src/main/resources/META-INF/core.xml

Various improvements of Cargo tool window:
* "Expand All" and "Collapse All" buttons
* ~"Toggle Offline Mode" action / button~
* "Cargo Settings" action / button
Cargo tool window
* Before
* After
For comparison, Gradle tool window:

ACT & UI: Cargo tool window enhancments

---

src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt

If it is not dumb-aware, the notification persists until the end
of indexation. This is a source of confusion
bors r+

Make "missing toolchain" notification dumb-aware

---

.github/workflows/test-plugin.yml

The main goal is to try github actions with our project.
For now, it launches only on linux and the corresponding checks are not included to bors mandatory checklist

CI: init github actions

---

src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt
src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
src/main/kotlin/org/rust/ide/intentions/FillMatchArmsIntention.kt
src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/kotlin/org/rust/openapiext/utils.kt
src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/FillMatchArmsIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Auto-import unresolved types in intentions:
- Implement members
- Specify type explicitly
- Fill match arms
- Add remaining patterns
- Use destructuring declaration
This PR doesn't affect:
- Add missing fields / Recursively add missing fields
- Initialize with a default value
because `RsDefaultValueBuilder.buildFor` can't use unresolved types.
Based on https://github.com/intellij-rust/intellij-rust/pull/3099.
Closes https://github.com/intellij-rust/intellij-rust/issues/3586. Closes https://github.com/intellij-rust/intellij-rust/issues/3495.
Relates to https://github.com/intellij-rust/intellij-rust/pull/3520.

INT: Auto-import unresolved types in generated code

---

src/main/kotlin/org/rust/cargo/CfgOptions.kt
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/utils/CfgUtils.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
src/test/kotlin/org/rust/MockAdditionalCfgOptions.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt
src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt

Related to #1191. Some cfg options cannot be evaluated to `True` or `False` in IDE (e.g. `test` option), so now they are evaluated to `Unknown` according to [three-valued logic](https://en.wikipedia.org/wiki/Three-valued_logic).

RES: Use three-valued logic in cfg evaluation

---

src/main/resources-nightly/META-INF/experiments.xml

Relates to #1191
This PR enables [cfg attributes support](https://github.com/intellij-rust/intellij-rust/pull/4232) in nightly versions of IntelliJ Rust. This affects type inference, navigation, code completion, and other features. Also, conditionally disabled code is [greyed out](https://github.com/intellij-rust/intellij-rust/pull/4342).
Only a few cfg options can be evaluated to `true` or `false`:
* debug_assertions
* unix
* windows
* target_arch
* target_env
* target_family
* target_feature
* target_os
* target_pointer_width
* target_vendor
Other cfg options are considered as `unknown` and don’t affect name resolution. Note that `test` cfg option is considered as `unknown` too:
* `cfg(test)` cannot be `false`, because then all the tests in your code are grey
* `cfg(test)` cannot be …

Enable cfg attributes support on nightly

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt

Relates to the new macro expansion engine #3628. `extract()` is basically fast, but may access indices. When accessing indices, an index may rebuild stubs for unsaved files, which is slow. Slow read actions should be wrapped with a cancellable section

PERF&MACRO: cancellable extraction step (better editor responsiveness)

---

CONTRIBUTORS.txt
intellij-toml/src/192/main/kotlin/org/toml/lang/TomlFileTypeDetector.kt
intellij-toml/src/193/main/kotlin/org/toml/lang/TomlFileTypeDetector.kt
intellij-toml/src/main/kotlin/org/toml/lang/TomlFileTypeDetector.kt
intellij-toml/src/main/kotlin/org/toml/lang/TomlFileTypeDetectorBase.kt

I suspect TOML plugin to be responsible for numerous IDE freezes due to our poor file type matching API. Namely, all FileTypeDetectors which do not implement `getDetectedFileTypes` take part in all `isFileOfType` checks by eating loading file content, which is loaded lazily.
This PR fixes the behaviour.

Use performance optimizations provided by FileTypeDetector API not to slow down IDEs using TOML plugin

---

src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt

After some refactoring action id was changed in plugin.xml but wasn't changed in `MissingToolchainNotificationProvider`. That leads to IllegalStateException because the corresponding action cannot be found by old id
Fixes #4503

ACT: fix IllegalStateException in `Attach` action

---

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsModificationTrackerOwner.kt

... that forces to rebuild stubs synchronously (in the EDT!) and affects editor responsiveness

PERF: fix index access during PSI event processing

---

src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt
src/main/kotlin/org/rust/ide/wordSelection/RsMacroCallSelectionHandler.kt
src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/resources/META-INF/core.xml
src/test/kotlin/org/rust/ide/wordSelection/RsSelectionHandlerTestBase.kt

Now `Extend Selection` and `Type Info` actions should work properly for code inside macro calls
Extend selection:
Type provider:
(note that this works only with the new macro expansion engine enabled)

Macro type provider and extend selection

---

src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt
src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherIntegrationTest.kt
src/test/kotlin/org/rust/cargo/project/model/impl/testCargoProjects.kt

The main reason is absence of test code in plugin archive.
It leads to `ClassNotFoundException` in tests of other plugins that use IntelliJ Rust as a dependency

T: move `TestCargoProjectsServiceImpl` from test source root to main one

---

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt

QDOC: render `async` keyword for async functions in quick doc

---

src/test/kotlin/org/rust/lang/core/completion/RsFullMacroArgumentCompletionTest.kt

Rename `RsMacroCallBodyCompletionTest` to `RsFullMacroArgumentCompletionTest` (like `RsPartialMacroArgumentCompletionTest`)

Rename RsMacroCallBodyCompletionTest according to provider

---

src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt

Don't annotate 2018 edition keywords inside cfg-disabled code

---

src/192/main/kotlin/org/rust/openapiext/compatUtils.kt
src/193/main/kotlin/org/rust/openapiext/compatUtils.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
src/main/kotlin/org/rust/openapiext/utils.kt
src/main/resources-nightly/META-INF/experiments.xml
src/main/resources-stable/META-INF/experiments.xml
src/test/kotlin/org/rustSlowTests/cargo/runconfig/RsIncludeMacroResolveTest.kt

Recently supported name resolution for included files uses `cargo build --build-plan` to fetch value of `OUT_DIR` environment variable (see #4542).
Found out that `cargo build --build-plan` force next `build` command to recompile whole project (including dependencies).
See https://github.com/rust-lang/cargo/issues/5579#issuecomment-546760770.
At this moment it is part of refresh, i.e. it is invoked on each `Cargo.toml` change, project reopening, etc. So this command is invoked quite frequently.
It can be rather unexpected for large project to make full compilation after each project reopening
So we decided to disable it by default until it will be fixed from cargo side or we'll find better way to get `OUT_DIR` value

MACRO: disable name resolution for include with env("OUT_DIR") by default

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiTreeChangeListener.kt
src/main/kotlin/org/rust/openapiext/Testmark.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt

The problem: there is `RsMacroCall` and `ExpandedMacroInfo`.
We want reliably link them to each other.
Previous solution:
- `ExpandedMacroInfo` holds stub index (aka `ID`) of a macro call
and a `SoftReference` to the macro call
- there is `rebind` function that fills in such soft references
- we use such soft references in most cases
- if we detect that references was lost (GCed), we do `rebind` again
- *sometimes* we dump stub indices (aka `ID`s) from macro calls
(accessed trough sort references)
Issues with that solution:
- it's not clear when to call `rebind`. `SoftReference`s can
be GCed at any time. We should detect it and call `rebind`
in this case. It's difficult to make it reliable.
- it's not clear when we should dump stub indices (IDs).
We should do it before PSI unloads (soft …

MACRO: rework macro-to-expansion linkage

---

src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/RsIncludeMacroResolveTest.kt

The main reason of SO Error was the following construction:
```rust
//- some_name.rs
include!(concat!(env!("OUT_DIR"), "/some_name.rs"))
```
In this case, we start to process `some_name.rs` while processing `include!` macro call and fall into an endless loop. Of course, it's just the simplest example
Fixes #4579

MACRO: prevent stackoverflow while name resolution for include macro

---

src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsDeprecationInspectionTest.kt

INSP: Ignore `Self` identifier in RsDeprecationInspection

---

src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt

(work with the new macro expansion engine only)

RES: fix impls selection for impl Trait when impl is inside a macro

---

common/src/test/kotlin/com/intellij/ide/annotator/AnnotationTestFixtureBase.kt
common/src/test/kotlin/com/intellij/ide/annotator/TestSeverityProvider.kt
intellij-toml/src/main/kotlin/org/toml/ide/TomlHighlighter.kt
intellij-toml/src/main/kotlin/org/toml/ide/annotator/TomlHighlightingAnnotator.kt
intellij-toml/src/main/kotlin/org/toml/ide/colors/TomlColorSettingsPage.kt
intellij-toml/src/main/kotlin/org/toml/ide/colors/TomlColors.kt
intellij-toml/src/main/resources/META-INF/plugin.xml
intellij-toml/src/main/resources/org/toml/ide/colors/highlighterDemoText.toml
intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestBase.kt
intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlHighlightingAnnotatorTest.kt
src/main/kotlin/org/rust/ide/colors/RsColors.kt
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionHighlightingAnnotatorTest.kt

* Now it's possible to change toml colors via `Preferences | Editor | Color Scheme | Toml` settings
* Numbers, dates, and number/date-like keys are highlighted properly
|-|-|
| ![image](https://user-images.githubusercontent.com/2539310/68527267-170a9000-02f6-11ea-9b0a-9fa5f62fb29b.png) | ![image](https://user-images.githubusercontent.com/2539310/68527275-238ee880-02f6-11ea-91f2-e1abe12db172.png) |

TOML: provide color settings and proper numbers, dates and keys highlighting

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

TY: fix empty array type inference

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt

It simplifies profiling and stacktrace analysis

REF: use processors instead of sequences in impl lookup

---

src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
src/main/kotlin/org/rust/ide/intentions/ListIntention.kt
src/main/resources/META-INF/core.xml
src/main/resources/intentionDescriptions/ChopLiteralFieldListIntention/after.rs.template
src/main/resources/intentionDescriptions/ChopLiteralFieldListIntention/before.rs.template
src/main/resources/intentionDescriptions/ChopLiteralFieldListIntention/description.html
src/main/resources/intentionDescriptions/JoinLiteralFieldListIntention/after.rs.template
src/main/resources/intentionDescriptions/JoinLiteralFieldListIntention/before.rs.template
src/main/resources/intentionDescriptions/JoinLiteralFieldListIntention/description.html
src/test/kotlin/org/rust/ide/intentions/ChopLiteralFieldListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinLiteralFieldListIntentionTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/4322
I basically copy-pasted the tests from the struct fields and changed them to work with struct literal fields.
Note:
Test with a single line comment produces this formatting on a struct:
```rust
struct S {
x: i32,
// comment x
y: i32,
z: i32 // comment z
}
```
and this formatting with a literal:
```rust
struct S {  x: i32, y: i32, z: i32 }
fn foo() {
S {
x: 0, // comment x
y: 0,
z: 0 // comment z
};
}
```
Not sure if that's important. Should I investigate?
Also, should I add the same thing for Enum literals?

INT: add "Put struct literal fields on separate lines/one line" intention

---

src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4636.

RUN & INSP: Fix error span in rustc messages if the error comes from macro expansion

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferencesSearchExtensionImpl.kt

The bug was introduced in #4012. Fixes such artifacts:

Fix incorrect module search scope

---

src/main/kotlin/org/rust/cargo/CfgOptions.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt
src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt
src/test/kotlin/org/rustSlowTests/CargoProjectResolveTest.kt

Name resolution now takes into account which Cargo features are enabled when resolving items from dependency.
Note that only dependencies' features evaluation is supported so far. Workspace features will be supported later.
Fixes #4329. Part of #1191

CARGO&RES: Initial support of cargo features

---

src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt

Disable `#[cfg(test)]` in stdlib

---

.idea/codeStyles/Project.xml
gradle.properties

This reverts commit da1f8e78 (PR https://github.com/intellij-rust/intellij-rust/pull/4598).
The Kotlin official style guide should be applied to the project more carefully later because now it brokes our test formatting.

Revert "Use default formatting settings from kotlin official style guide"

---

src/main/kotlin/org/rust/openapiext/DelayedBackgroundableProcessIndicator.kt

Fixes (possible) non-fading progress bar:
bors r+

Fix infinite non-fading progress bar during macro expansion

---

CONTRIBUTING.md
build.gradle.kts
gradle-192.properties
gradle-193.properties
grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt
grazie/src/main/resources/META-INF/grazie-only.xml
grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
grazie/src/test/resources/META-INF/plugin.xml
plugin/src/main/resources/META-INF/plugin.xml
settings.gradle.kts
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt
src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt

Note, at this moment we use [`grazie`](https://plugins.jetbrains.com/plugin/12175-grazie/) plugin from `dev` channel because it's the first version where `grazie` doesn't depend on intellij rust (otherwise, there is cyclic dependency between these plugin and an IDE doesn't load both ones).
Stable version will be published soon

Add support of `Grazie` plugin

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt

Speeds up things like a completion in macros

PERF&MACRO: do not reset structure mod tracker on macro call change

---

src/main/kotlin/org/rust/ide/navigation/goto/RsGotoTargetRendererProvider.kt

Better when implementations are in the same file. Also corresponds to IDE behavior for other languages.
Not sure if there is a way to add a test for it, though.

ACT:Display impl block info in Go to Imlementations dialog

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt

when "ignoreWithoutQuickFix" is disabled.
(every `Self` was red if "ignoreWithoutQuickFix" is disabled)

INSP: fix false-positive unresolved reference `Self`

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt

Some time ago `rustc_reservation_impl` attribute was introduced to reserve some implementation (https://github.com/rust-lang/rust/issues/64631).
Such implementations mostly don't take part in code analysis.
Most notable (and maybe only one) impl with such attribute is `impl<T> From<!> for T`. This impl breaks type inference in some cases.
These changes just make type inference ignore such `impl` items

TY: skip impls with `rustc_reservation_impl` attribute while type inference

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: fix matching `$($ e:expr,)+` group

---

src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

This allows borrow checker to find move errors in some new cases. Also, these fixes will be necessary for liveness analysis.
Merge after #4686.

Fix control flow of some elements

---

src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

This allows borrow checker to find move errors caused by macro calls, and also to correctly process variable initialization generated by macro calls.
Merge after #4687.

Consider expanded macros in control flow and borrow checker

---

src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
src/test/kotlin/org/rust/ide/intentions/JoinArgumentListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinFieldListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinLiteralFieldListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinParameterListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinVariantListIntentionTest.kt

 INT: don't suggest "Put parameters/arguments/fields/variants on separate lines/one line" if comments are present

---

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt

Previously, when you open a popup with macro expansion (via alt+enter or a context menu action) it made full re-validation of expanded macros (which usually takes a few seconds)

MACRO: Fix full re-expand when showing macro expansion

---

src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

(Occurs in stdlib with standard traits and "derive" macros, e.g. Clone)
bors r+

ANN: fix false-positive E0428 with macro 2.0

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt

Fixes #4740, fixes #3288
Also fixes some other wrong type inference cases, false-positives in typechecker and false-negatives in borrow-checker

 TY: add predicates for derived traits & provide builtin `Clone`&`Copy` impls for tuples

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt

Works for e.g. functions in inherent impls or trait impls. Greatly speeds up find usages of `Foo::new` functions. Fixes #4222

PERF: optimize "find usages" of associated values

---

src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt

1. Make it unavailable in initializer (just like int Kotlin): `let a = /*caret*/b;` Useful in constructions like `let = if foo { /*caret*/ } else {};`
2. Make it work with complex patterns like `let (a, b) = ...`

INT: improve "specify type explicitly" intention

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsNamespaceResolveTest.kt

E.g. int this case `Foo` was incorrectly multi-resolved:
```rust
struct Foo { f: i32 }
//X
fn Foo() {}
fn main() {
let Foo { f } = Foo { f: 1 };
}     //^
```
bors r+

RES: fix pattern namespaces

---

.idea/dictionaries/matklad.xml
duplicates/src/test/kotlin/org/rust/ide/clones/RsDuplicateInspectionTest.kt
src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/resources/META-INF/core.xml
src/main/resources/inspectionDescriptions/RsLift.html
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt
src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt

INSP: lift inspection for return expression

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentElementType.kt

There were two classes named `RsReplCodeFragment`, and that's why plugin build fails sometimes. So now the generated classes will be `*CodeFragmentElement.java`.

PSI: Rename code fragments consistently

---

toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt

Make fair getting toml string literal value via new API. It correctly works with different types of quotes and support escapes symbols
Fixes #4791

TOML: fix crate doc links in toml

---

intellij-toml/src/main/kotlin/org/toml/ide/wordSelection/TomlStringLiteralSelectionHandler.kt
intellij-toml/src/main/kotlin/org/toml/lang/psi/ext/PsiElement.kt
intellij-toml/src/main/kotlin/org/toml/lang/psi/ext/TomlLiteral.kt
intellij-toml/src/main/resources/META-INF/plugin.xml
intellij-toml/src/test/kotlin/org/toml/ide/wordSelection/TomlSelectionHandlerTestBase.kt
intellij-toml/src/test/kotlin/org/toml/ide/wordSelection/TomlStringLiteralSelectionHandlerTest.kt
src/main/kotlin/org/rust/ide/wordSelection/RsBlockSelectionHandler.kt
src/main/kotlin/org/rust/ide/wordSelection/RsFieldLikeSelectionHandler.kt
src/main/kotlin/org/rust/ide/wordSelection/RsGroupSelectionHandler.kt
src/main/kotlin/org/rust/ide/wordSelection/RsStringLiteralSelectionHandler.kt
src/main/resources/META-INF/core.xml
src/test/kotlin/org/rust/ide/wordSelection/RsSelectionHandlerTestBase.kt
src/test/kotlin/org/rust/ide/wordSelection/RsStringLiteralSelectionHandlerTest.kt

Improve `Extend Selection` action for Rust and Toml literals:
* select whole string literal without quotes
* select escapes symbols
|-|-|
| ![2019-12-28 22 13 23](https://user-images.githubusercontent.com/2539310/71548454-56349380-29bf-11ea-8036-246692f11d5b.gif) | ![2019-12-28 22 12 04](https://user-images.githubusercontent.com/2539310/71548456-56cd2a00-29bf-11ea-9e59-105ada892c19.gif) |
| ![2019-12-28 22 12 29](https://user-images.githubusercontent.com/2539310/71548455-56cd2a00-29bf-11ea-896d-bfadbf86bf63.gif) | ![2019-12-28 22 09 46](https://user-images.githubusercontent.com/2539310/71548457-56cd2a00-29bf-11ea-989e-b8379d90cb4d.gif) |

TYPE: improve extend selection for Rust and Toml string literals

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Trait methods without a body can have `?Size` parameters

ANN: fix false-positive E0277

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/formatter/impl/indent.kt
src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt

Fixes #907
Note that this *only* fixes indentation. The plugin as is doesn't seem to enforce any particular bracket style (at least on any code posted in the issue), it was just messing up the indentation. I assume enforcement of brackets would be covered by #4576, so therefore #907 can be considered as fixed

FMT: Fix indenting of braces when on their own line

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt

It allows opening special help page about Cargo Command run configuration

CPP-18528: provide help id for cargo command configuration type in IDEA and CLion

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt

Now the plugin can infer type of `[0; 4].clone()` expression
Fixes type inference part of #4814
Fixes #4819

TY: provide `Copy` and `Clone` impls for array types

---

src/main/kotlin/org/rust/ide/search/RsImportFilteringRule.kt
src/main/resources/META-INF/core.xml

Used to filter out usages from `use` items

Add "import filtering rule" for "find usages"

---

src/main/kotlin/org/rust/cargo/project/model/AttachCargoProjectAction.kt
src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt
src/main/kotlin/org/rust/ide/notifications/RsNotificationProvider.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt

* provide `Attach Cargo Project` action for files (`Cargo.toml` and its parent dir) in project view
* provide editor notification that `Cargo.toml` doesn't belong to any cargo project with `Attach` action. The action creates new cargo project in project model without manual choice of directory
Related to #4813

ACT: improve `Attach Cargo Project` action

---

src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt

(it's internal API and its usage doesn't make sense)
bors r+

Avoid usage of `SyntaxTraverser.children`

---

src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
src/main/kotlin/org/rust/lang/core/psi/LazyElements.kt

Finish the work started in #4357 (using infrastructure from #4491). Most likely this doesn't affect users anyhow but can speed up completion in macro calls in large files

PERF: make macro call body reparseable

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/completion/RsMacroBracketCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt

Analyze documentation of macro definition and extract the most commonly used type of braces from it.
For example, it allows the plugin to insert `{}` while `thread_local` completion instead of `()`
It was originally implemented in https://github.com/rust-analyzer/rust-analyzer/pull/2039

COMP: guess proper type of braces while macro call completion

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

This cache was introduced before the latest optimization series and now is not actual.
I measured the impact of its removal and it is zero or even positive (some benchmarks works faster without the cache, lol)
But the main reason for its removal is (rare) `Non-idempotent computation` assert triggering. Unfortunately I didnt found the real reason of this

Drop processItemDeclarationsWithCache

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/4746
I tried to loosen up the matching of `#[test]` attributes, as described in https://github.com/intellij-rust/intellij-rust/issues/4746.
To support `tokio`'s `#[tokio::test(threaded_scheduler)]` (https://github.com/tokio-rs/tokio/blob/master/tokio-macros/src/lib.rs#L137), the check now tries to find any occurence of `test` inside the function attribute.

RUN: match test attributes more loosely to support custom attributes

---

src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Fixes #4750
This PR adds support for selecting the content of implemented trait functions so that it can be quickly modified. I adapted it from the source code of PyCharm.
I have two questions:
1. ~~I'm pretty sure that IntelliJ can create a "selection chain" (I don't know the correct terminology), where it selects a first item, after you press Enter, it selects another one and so on, until the user goes through all of them and/or presses Escape. Which API can I use for this? The current implementation only selects the last implemented function, which is far from ideal. Also now if I press Enter after the selection, the content is replaced by a newline, in the "chain" mode it should be just deselected.~~ EDIT: I found the API (`buildAndRunTemplate`) and used it.
2. How to test this, or at …

INT: select unimplemented after Implement members fix

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/resources/org/rust/lang/core/parser/fixtures/partial/fn.txt
src/test/resources/org/rust/lang/core/parser/fixtures/partial/impl_body.txt

This fulfills the second bullet-point of #4355. Now we do not re-parse the entire document when typing in a function body. Instead, we re-parse the only function in which the user is typing. I.e. parsing is now incremental. This can slightly speedup completion in large documents.
Merge after the end of 2019.2 support

PERF&GRAM: lazy parseable & reparseable code block

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt

Now, when we want e.g. to highlight a function name:
```rust
fn foo() {}
// ~~~ highlight this
```
we do it when Annotator.annotate is called with leaf (identifier) element argument, not the function element.
This is more proper usage of annotators API. Particularly, it fixes highlights blinking (most viewable on a dark theme).
Also:
1. fixed incorrectly highlighted "primitive" in this case:
```rust
let mut i32 = 1;
i32 = 2;
```
2. fixed literal highlighting in attributes: `#[foo("bar")]`

ANN&REF: add annotations to leafs when highlighting leafs

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt

The previous version of macro expansion engine processed all project files on the first step.
It led to a situation when a module was added to the module structure via macro call and at the same time, it had own macro calls.
It such cases we failed to expand module's macro calls because name resolution for macro calls didn't work properly.
These changes introduce pending files - project files that are not belong to the module tree.
Such files are postponed to expand their macro calls until they belong to module tree.
It should solve "File is not included into module tree" issue for some popular crates like `async-std` and `tokio`
Fixes the following issues when new macro expansion engine is enabled: 
* #4627
* #4679
* #4706
* #4714
* #4929

MACRO: process modules declared inside macro call better

---

src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/test/kotlin/org/rust/ide/hints/RsExpressionTypeProviderTest.kt

I replaced `toString()` with `insertionSafeTextWithAliases` to show aliases in the `Type Info` hint. I didn't find any tests for this, so I'm not sure if this is enough. @Undin thoughts?
Fixes https://github.com/intellij-rust/intellij-rust/issues/4366

INT: use text with aliases in Type Info intention

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/formatter/settings/RsCodeStyleSettingsProvider.kt
src/main/kotlin/org/rust/ide/formatter/settings/RsLanguageCodeStyleSettingsProvider.kt

Adds these options:
- Line comment at first column
- Add a space at comment start
- Block comment at first column
Dev build of plugin: https://github.com/SeekingMeaning/intellij-rust/releases/download/0.2.116.SNAPSHOT-193-dev/intellij-rust-0.2.116.SNAPSHOT-193-dev.zip
Screenshot:
All three options have been tested and confirmed working

Add Code Generation settings tab

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt

PERF&GRAM: replace `PathIdent` with external rule

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

See the corresponding [RFC](https://github.com/rust-lang/rfcs/blob/master/text/2338-type-alias-enum-variants.md)
Fixes #4923

RES&TY: support enum type aliases

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
src/main/kotlin/org/rust/ide/hints/RsDeclarationRangeHandler.kt
src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
src/test/kotlin/org/rust/lang/core/stubs/RsStubTest.kt
src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerformanceTest.kt
src/test/kotlin/org/rustSlowTests/RsLazyCodeBlockIsNotExpandedDuringStubBuildingTest.kt

Now during indexation, we only parse function bodies that can contain local items (that should be indexed). I measured that for most projects now only about 3% function bodies should be parsed, i.e. other 97% should not. This speeds up indexation by about 20%.
Closes #4355

PERF: don't parse function bodies during indexing

---

src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

This PR changes `RsTypeReference.substAndGetText` to support both lifetimes and aliases. It fixes alias generation in ImplementMembersFix, let's see what CI says about the rest of tests :)
Fixes: https://github.com/intellij-rust/intellij-rust/issues/3082

INT: add support for type aliases in ImplementMembersFix

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

1. Better resolve for `Self`-related paths in traits:
```rust
trait Foo {
fn foo() {}
}    //X
trait Bar {
fn bar() where Self: Foo {
Self::foo();
}        //^
}
```
2. Better type inference for trait-relative paths with type parameters (e.g. `Foo::<Bar>::baz()` where `Foo` is a trait)
3. Take into account blanket `impl<T> for T` impls when looking for trait object methods. Continuation of #4913
The PR is a result of [the discussion](https://github.com/intellij-rust/intellij-rust/pull/4913#discussion_r376583843).

RES: Don't use ImplLookup for trait-relative paths

---

src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt

TYPE: render type arguments of type aliases in inlay hints in proper way

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

Works for such case:
```rust
trait Foo {
fn foo(&self) {}
}     //X
trait Bar {
type Item;
}
fn foo<A, B>(b: B) 
where A: Bar<Item=B>, 
A::Item: Foo // `A::Item` is equivalent to `B`
{
b.foo()
}   //^
```

TY: normalize trait bounds

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt

It should prevent bugs with run configuration loading when display name of cargo run  configuration will be localized

RUN: introduce id for cargo configuration factory
