src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
src/test/resources/org/rust/ide/folding/fixtures/comments.rs

Fixes https://github.com/intellij-rust/intellij-rust/issues/4058.

TYPE: Fix folding of doc comments

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

(fixes iterators on the nightly rust)

MACRO: fix macro with arguments defined with another macro

---

gradle-192.properties

GRD: update 2019.2 EAPs

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsBreakExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsContExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLabelReferenceOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLooplikeExpr.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: Detect E0267, E0268: break/continue used outside of loop

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: Fix E0618: Type implementing a Fn trait is a function too

---

CONTRIBUTING.md
build.gradle.kts
coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
coverage/src/main/kotlin/org/rust/coverage/LcovCoverageReport.kt
coverage/src/main/kotlin/org/rust/coverage/RsCoverageAnnotator.kt
coverage/src/main/kotlin/org/rust/coverage/RsCoverageEnabledConfiguration.kt
coverage/src/main/kotlin/org/rust/coverage/RsCoverageEngine.kt
coverage/src/main/kotlin/org/rust/coverage/RsCoverageRunner.kt
coverage/src/main/kotlin/org/rust/coverage/RsCoverageSuite.kt
coverage/src/main/resources/META-INF/coverage-only.xml
settings.gradle
src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/Grcov.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/stdext/Utils.kt
src/main/resources/META-INF/plugin.xml

grcov [repo](https://github.com/mozilla/grcov)
Closes https://github.com/intellij-rust/intellij-rust/issues/1230.
TODO: add a GIF

RUN: Support code coverage via grcov

---

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt

ACT: fix "show macro expansion" action crash

---

src/main/kotlin/org/rust/ide/inspections/checkMatch/CheckMatchUtils.kt
src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt

INSP: Fix PatField sorting in RsMatchCheckInspection

---

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt

STUB: fix serialization for trait alias stub

---

src/main/kotlin/org/rust/ide/inspections/RsImplicitTraitObjectInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsImplicitTraitObjectInspectionTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4174.

INSP: Don't warn about missing 'dyn' for Self

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt

INSP: fix auto import inside pub inline module

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

PERF: optimize very hot `getExpandedFrom` method

---

.travis.yml
gradle-192.properties
gradle.properties

Update 2019.2 IDEA & CLion and make 192 platform default for development

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt

when extract method, i need to focus on nameField by hand.

REF: fix extract method not focus on nameField.

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

RES: Take into account namespaces when resolving const generics

---

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt

COMP: Const keyword completion for const generics

---

src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt

Use `--installed` flag and `--toolchain` option in `listComponents`

---

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt

Fix #4212 Error while indexing (RsExternCrateReexportIndex)

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4185.

COMP: Assoc functions have higher priority than methods

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt

The idea is that we have 4 things:
- cargo project
- cargo workspace
- cargo target
- crate root
that can be cheaply retrieved and cached all together.
This speeds up highlighting up to 5% (the baseline is before #4179)

REF&PERF: better cache cargo target for files

---

src/main/resources/postfixTemplates/DerefPostfixTemplate/before.rs.template
src/main/resources/postfixTemplates/DerefPostfixTemplate/description.html

TYPE: improve `deref` postfix completion description & example

---

src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
src/main/kotlin/org/rust/ide/utils/CallInfo.kt
src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt

COMP: Substitute types in completion variants

---

src/test/kotlin/org/rust/lang/core/resolve/RsNamespaceResolveTest.kt

Relates to https://github.com/intellij-rust/intellij-rust/pull/4202.

T: Tests for const generic namespaces

---

build.gradle.kts
gradle-191.properties
gradle-192.properties

GRD: PsiViewer plugin dependency

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/colors/RsColors.kt
src/main/resources/org/rust/ide/colors/RustDarcula.xml
src/main/resources/org/rust/ide/colors/highlighterDemoText.rs
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt

ANN: separate colors for function/method/assoc function calls

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt

Relates to https://github.com/intellij-rust/intellij-rust/pull/3926.
bors r+

RUN: Ignore `-q` option if using new build toolwindow

---

src/main/kotlin/org/rust/lang/core/DataFlow.kt
src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLabeledExpression.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/BorrowChecker.kt
src/main/kotlin/org/rust/lang/core/types/regions/Scope.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

Process break/continue in CFG and dataflow

---

src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt

Fixes https://github.com/intellij-rust/intellij-rust/pull/3926#issuecomment-521153046.
bors r+

RUN: Fix Build action when build toolwindow is disabled

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt

RUN: Show executed command line in build tool window

---

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt

COMP: keyword completion in trait and impl items

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4268.

RUN: Fix integration test debugging 

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsMacroCallBodyCompletionTest.kt

Also, make minor refactoring of function completion

COMP: extend keyword completion

---

src/main/kotlin/org/rust/ide/search/RsFunctionGroupingRuleProvider.kt
src/main/resources/META-INF/core.xml

Closes #4200.
Adds function/method name to usages tooltip.

Usages tooltip scope

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4279.

RUN: Debug runner correctly checks toolchain on Windows

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Fix declaration fields escaping and underscores in struct patterns

---

src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4256.

RUN: Fix exception in "Run/Debug Configurations" menu

---

src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4292.

RUN: Fix parsing option arguments

---

src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt

Revert: a5401a57
Fixes https://github.com/intellij-rust/intellij-rust/issues/4281.

Revert: Use `--installed` flag and `--toolchain` option in `listComponents` 

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

TY: fix expression type arguments with defaults

---

src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
src/main/resources/META-INF/core.xml
src/main/resources/intentionDescriptions/ChopFieldListIntention/after.rs.template
src/main/resources/intentionDescriptions/ChopFieldListIntention/before.rs.template
src/main/resources/intentionDescriptions/ChopFieldListIntention/description.html
src/main/resources/intentionDescriptions/JoinFieldListIntention/after.rs.template
src/main/resources/intentionDescriptions/JoinFieldListIntention/before.rs.template
src/main/resources/intentionDescriptions/JoinFieldListIntention/description.html
src/test/kotlin/org/rust/ide/intentions/ChopFieldListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinFieldListIntentionTest.kt

INT: add "Put fields on separate lines/one line" intentions

---

src/main/kotlin/org/rust/ide/intentions/ChopListIntention.kt
src/main/kotlin/org/rust/ide/intentions/JoinListIntention.kt
src/main/resources/META-INF/core.xml
src/main/resources/intentionDescriptions/ChopVariantListIntention/after.rs.template
src/main/resources/intentionDescriptions/ChopVariantListIntention/before.rs.template
src/main/resources/intentionDescriptions/ChopVariantListIntention/description.html
src/main/resources/intentionDescriptions/JoinVariantListIntention/after.rs.template
src/main/resources/intentionDescriptions/JoinVariantListIntention/before.rs.template
src/main/resources/intentionDescriptions/JoinVariantListIntention/description.html
src/test/kotlin/org/rust/ide/intentions/ChopVariantListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/JoinVariantListIntentionTest.kt

 INT: add "Put variants on separate lines/one line" intentions

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFix.kt
src/main/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralIntention.kt
src/main/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralRecursiveIntention.kt
src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt
src/main/resources/META-INF/core.xml
src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/after.rs.template
src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/before.rs.template
src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/description.html
src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/after.rs.template
src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/before.rs.template
src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/description.html
src/test/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/AddStructFieldsLiteralRecursiveTest.kt

INT: Implement struct literal fields expansion

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsFragmentSpecifierCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt
src/test/kotlin/org/rust/lang/core/completion/RsFragmentSpecifierCompletionTest.kt

COMP: provide fragment specifiers completion

---

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4271. Fixes https://github.com/intellij-rust/intellij-rust/issues/4276.

RUN: Fix parsing executable file path when debugging tests

---

src/main/kotlin/org/rust/lang/core/types/borrowck/BorrowChecker.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/gatherLoans/GatherMoves.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt

Borrow checker: Fix move analysis on slices

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt

Wrap some VFS usages into read actions

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Bugfix/arbitrary self types#4138

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt

See https://github.com/intellij-rust/intellij-rust/pull/4190#discussion_r310403923

Always use original crate root file

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt
src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/main/kotlin/org/rust/lang/core/parser/util.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt

MACRO: support doc comments in macro calls

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

For more info see https://github.com/intellij-rust/intellij-rust/pull/4305#issuecomment-524560326

ANN: Improve error messages for E0023 and E0027

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt

This speeds up highlighting up to 5% (the baseline is the latest 103 release)

PERF&REF: optimize/refactor `processAssociatedItems`

---

src/191/main/kotlin/org/rust/ide/hints/RsPlainTypeHint.kt
src/191/test/kotlin/org/rust/ide/hints/RsPlainInlayTypeHintsProviderTest.kt
src/192/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt
src/192/main/kotlin/org/rust/ide/hints/RsPlainTypeHint.kt
src/192/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
src/192/main/resources/META-INF/platform-core.xml
src/192/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
src/main/kotlin/org/rust/ide/hints/RsPlainParameterHint.kt
src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFnPointerType.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
src/test/kotlin/org/rust/ide/hints/RsPlainInlayHintsProviderTestBase.kt

TYPE: New interactive inlay type hints support

---

MAINTAINING.md
README.md
build.gradle.kts

Also:
* update `makeRelease` gradle tasks
* update links in readme according to latest changes in TeamCity configurations

Update docs about releases

---

MAINTAINING.md

DOC: add note about `to be documented` label

---

.idea/runConfigurations/Run.xml
.idea/runConfigurations/RunCLion.xml

Fix idea log path for Run and RunCLion run configurations

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt

RES: take into account cfg attributes when collecting impls

---

idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt
src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt
src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt

Also fixes https://github.com/intellij-rust/intellij-rust/issues/4294.

RUN: Always pass `--offline` / `-Zoffline` option to Cargo if "Offline mode" setting is enabled

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4392.

TY: Support async and try blocks in lambdas

---

.travis.yml
build.gradle.kts
clion/src/193/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt
clion/src/193/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
clion/src/193/main/resources/META-INF/platform-clion-only.xml
debugger/src/193/main/kotlin/org/rust/debugger/lang/RsEvaluatorBase.kt
debugger/src/193/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurator.kt
debugger/src/193/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
debugger/src/193/main/resources/META-INF/platform-debugger-only.xml
duplicates/src/193/main/kotlin/org/rust/ide/clones/RsDuplicateScope.kt
duplicates/src/193/main/resources/META-INF/platform-duplicates-only.xml
duplicates/src/193/test/kotlin/org/rust/ide/clones/RsDuplicateInspectionTest.kt
gradle-192.properties
gradle-193.properties
gradle.properties
src/193/main/kotlin/org/rust/cargo/project/toolwindow/StructureTreeModelWrapper.kt
src/193/main/kotlin/org/rust/cargo/runconfig/buildtool/UtilsExtra.kt
src/193/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
src/193/main/kotlin/org/rust/ide/actions/runAnything/RunAnythingCargoItem.kt
src/193/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt
src/193/main/kotlin/org/rust/ide/hints/RsPlainTypeHint.kt
src/193/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
src/193/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt
src/193/main/kotlin/org/rust/lang/core/resolve/ref/RecursionGuardWrapper.kt
src/193/main/resources/META-INF/platform-core.xml
src/193/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt
src/193/test/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoderTest.kt
src/193/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt
src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt

Support 2019.3 platform

---

src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt

T: Disable tests for CargoBuildManager

---

src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

Also auto-completion, usages search and highlighting works better for these variables.
Closes #4129

REF:full rename support for struct pattern variable bindings

---

src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt

related https://github.com/intellij-rust/intellij-rust/pull/4127#discussion_r325137633 I have implemented same behavior as for kotlin's destructure declaration.

ACT:better find usages for pattern bindings

---

gradle-193.properties
src/191/main/kotlin/org/rust/lang/core/completion/CompletionUtilsExt.kt
src/191/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
src/192/main/kotlin/org/rust/lang/core/completion/CompletionUtilsExt.kt
src/192/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
src/193/main/kotlin/org/rust/lang/core/completion/CompletionUtilsExt.kt
src/193/main/kotlin/org/rust/lang/core/psi/RsDocCommentImpl.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/RsDocCommentImplBase.kt

Fix incompatibilities with latest 2019.3 EAPs

---

src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt
src/main/kotlin/org/rust/ide/presentation/RsDescriptionProvider.kt
src/main/kotlin/org/rust/ide/refactoring/RsDirectoryRenameProcessor.kt
src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferencesSearchExtensionImpl.kt
src/main/resources/META-INF/core.xml
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

fixes #1859
also as side effect find usages for mod.rs modules started to work as well.

REF: improved rename for mod.rs and directories

---

debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerTypesHelper.kt
src/main/kotlin/org/rust/ide/inspections/checkMatch/Pattern.kt
src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt

Fix `Hash` trait autoimport on Rust nightly

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt

Better logs and try to recover in cases like #4370
bors r+

MACRO: better logs and try to recover on broken stub indices

---

src/main/grammars/RustParser.bnf

DOC: fix comments in the grammar

---

src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

Also, fixes some other tests with nightly rust
Fixes #4457
Part of #4404

Search Debug trait better

---

src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt

INT: `Specify type explicitly` take into account type alias

---

src/main/kotlin/org/rust/stdext/Profiling.kt
src/test/kotlin/org/rustPerformanceTests/RsCompletionPerformanceTest.kt
src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerformanceTest.kt
src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt

- warmup iterations
- calculate mean value (more stable results than min value)
- calculate standard deviation (helps to find out that results are
too unstable and should be considered)

T: improve performance tests statistics

---

src/main/resources/META-INF/core.xml

ACT: add `Create New Issue` to help menu

---

src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

REF: implement correct renaming of init value in shorthand struct literal

---

src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt

TYPE: Fix type hints navigation for alias

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt

RES: fix cfg inside macros

---

intellij-toml/src/192/main/kotlin/org/toml/lang/TomlFileTypeDetector.kt
intellij-toml/src/main/resources/META-INF/plugin.xml

TOML: update TOML changelog

---

build.gradle.kts

GRD: use publish token to publish toml plugin

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt

Probably fixes #4370. Also, adjust logs for such case

MACRO: Use PSI FileViewProvider modificationStamp instead of file/doсument

---

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
src/test/kotlin/org/rustSlowTests/CargoProjectStructureTest.kt

Fix https://github.com/intellij-rust/intellij-rust/issues/4452.

Fix copying text from a Cargo project tree

---

src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt
src/main/resources/META-INF/core.xml
src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/4442.

ACT: Support `Analyze Stack Trace` action

---

src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt

* stdlib crates are merged into single library
* version of external library is also rendered if possible
| Old | New |
|----|------|
| <img width="318" alt="Screen Shot 2019-10-11 at 16 28 45" src="https://user-images.githubusercontent.com/2539310/66655776-5be2ce80-ec45-11e9-932a-0b502925f7f7.png"> | <img width="302" alt="Screen Shot 2019-10-11 at 16 36 22" src="https://user-images.githubusercontent.com/2539310/66655775-5be2ce80-ec45-11e9-85ec-d96f997f6678.png"> |

CARGO: improve rendering of external libraries

---

src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt

RUN: don't show tool window if "Activate tool window" option is disabled

---

src/main/resources-stable/META-INF/experiments.xml

Relates to #1191.
For more information see #4488.

Enable cfg attributes support on stable

---

gradle-193.properties

Also, allow installing 193 builds on IDEs from master

GRD: update 2019.3 EAPs

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt

Fix cfg on nested macros

---

README.md

Fix typo in nightly build link

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4510.

ACT: Take into account async keyword when implementing missing fn

---

src/main/kotlin/org/rust/ide/presentation/RsPsiRendering.kt
src/main/kotlin/org/rust/ide/search/RsTraitOrImplGroupingRuleProvider.kt
src/main/resources/META-INF/core.xml

Closes https://github.com/intellij-rust/intellij-rust/issues/4428.

UI: Show trait/impl in usage tooltip

---

src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt

ANN: Make cfg-disabled edition 2018 keywords bold

---

CONTRIBUTORS.txt
README.md

DOC: minor fixes in docs

---

src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProviderTest.kt

COMP: Add completion inside cfg attributes

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsValueParameter.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/test/kotlin/org/rust/ide/hints/RsInlayParameterHintsProviderTest.kt
src/test/kotlin/org/rust/ide/hints/RsParameterInfoHandlerTest.kt

TYPE & STUB: Render RsValueParameter without mutability

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt
src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4465. Fixes https://github.com/intellij-rust/intellij-rust/issues/4554.

RUN & INSP: Fix file path in messages from rustc

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt

INSP: improve typecheck to detect mismatches of partially unknown types

---

.idea/codeStyles/Project.xml
gradle.properties

Now IDEA should format kotlin code according to official [style guide](https://kotlinlang.org/docs/reference/coding-conventions.html#formatting).

Use default formatting settings from kotlin official style guide

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt

fix some possible crashes introduced in #4522

MACRO: fix some possible crashes introduced in #4522

---

src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt

FIxes #4639.
(also refactored RsSmartEnterProcessor a bit)

Fix #4639 IllegalStateException in `RsSmartEnterProcessor`

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt

Previously, a file was sometimes not re-highlighted after a macro
call change (until caret move or some other action)

MACRO: fix re-highlighting after a macro call change (new engine)

---

intellij-toml/src/main/resources/META-INF/plugin.xml

TOML: changelog

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt
src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/ide/inspections/RsReassignImmutableInspectionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsMemoryCategorizationTest.kt

Ignore inconsistent BorrowReference adjustment in memory categorization

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerformanceTest.kt

T: get rid of `MacroExpansionManager.ensureUpToDate` calls

---

src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt
src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt
src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt

TYPE: Don't show default types in type hints

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt

Some optimizations here and there...
(mostly about latency)

PERF&MACRO: some optimizations of the new expansion engine

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyUsingFromTraitFixTest.kt

Fix ConvertToTyUsingFromTraitFix on types that cannot be paths

---

MAINTAINING.md
build.gradle.kts
gradle.properties

GRD: cleanup meaning of `patchVersion` property

---

gradle.properties

GRD: bump nightly plugin version

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt

MACRO: place even less parens around exprs

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt

 PERF&MACRO: remove empty SourceFile's (new engine)

---

src/main/kotlin/org/rust/ide/formatter/impl/utils.kt

Fix IndexNotReadyException if reformatting in dumb mode

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4697.

RUN: Show cached compilation warnings in Build Tool Window

---

gradle-192.properties
gradle-193.properties

GRD: use stable grazie plugin

---

build.gradle.kts

GRD: fix `makeRelease` task

---

build.gradle.kts
src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt

Also, update compiler features
bors r+

GRD: fix `updateCompilerFeatures` task

---

src/main/kotlin/org/rust/ide/refactoring/extractFunction/ExtractFunctionParameterTablePanel.kt
src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt

:)
Edited: relates to https://github.com/intellij-rust/intellij-rust/issues/2186

Allow to manually select arguments

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4691.

RUN: Pass `--edition=2018` to rustfmt if needed

---

.github/workflows/test-plugin.yml
.travis.yml

:arrow_up nightly

---

src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToWhereClauseIntentionTest.kt

INT: Fixed move type constraints intentions for default type parameters

---

build.gradle.kts

GRD: introduce makeReleaseBranch task

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Relates to https://github.com/intellij-rust/intellij-rust/issues/4438.

ANN: Support `unstable` attribute for items

---

src/main/kotlin/org/rust/lang/core/completion/AttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsFragmentSpecifierCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsFullMacroArgumentCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsTupleFieldCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTupleFieldDecl.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt

* Provide completion for tuple fields
* Make text of field completion item bold
* Fix absence of field icon for number field completion item
Closes #4747

COMP: improve field completion for tuples and tuple structs

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/type/RsAdjustmentTest.kt

This shouldn't affect our users anyhow. Will be used by next PRs

TY: fix deref adjustments

---

.github/workflows/test-plugin.yml
.travis.yml
appveyor.yml

CI: rust 1.40

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/inspections/RsDiagnosticBasedInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsWrongLifetimeParametersNumberInspection.kt
src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt

TY: Check type of const generic argument

---

src/test/kotlin/org/rust/ide/intentions/AddStructFieldsPatIntentionTest.kt

T: fix formatting

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt

TY: fixed type inference for Fn type parameter with multiple bounds

---

src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt

INT: do not suggest "Lift return out" on 'if' in 'else' branch

---

coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt

Fix type incompatibility with 2020.1

---

src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt
src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt

INT: don't combile pub and non-pub uses into one in "nest use statements"

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
src/main/resources/META-INF/rust-core.xml

Closes https://github.com/intellij-rust/intellij-rust/issues/3839.

CARGO: Hide Cargo tool window button for non-Rust/non-Cargo projects

---

src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt

The template incorrectly adds a comma to expression instead to match arm.
(this is something internal/most likely does not affect our users)

Fix PSI produced by PrintlnPostfixTemplate

---

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4853.

T: Fix external linter tests on 2020.1

---

src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt

Part of https://github.com/intellij-rust/intellij-rust/pull/2999.

T: Run all tests in directory

---

.idea/dictionaries/intellij_rust.xml
src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsLint.kt
src/main/kotlin/org/rust/ide/inspections/RsLintInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
src/main/kotlin/org/rust/lang/core/DataFlow.kt
src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/Liveness.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/CheckLoans.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/MoveData.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/gatherLoans/GatherLoans.kt
src/main/kotlin/org/rust/lang/core/types/infer/MemoryCategorization.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/inspectionDescriptions/RsLiveness.html
src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

INSP: Add liveness analysis

---

.github/workflows/test-plugin.yml
.travis.yml
appveyor.yml

CI: bump rust to 1.41

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/Evcxr.kt
src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt
src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
src/main/kotlin/org/rust/ide/console/RsConsoleExecuteActionHandler.kt
src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
src/main/kotlin/org/rust/ide/console/RsConsoleView.kt

Based on `--ide-mode` flag for evcxr (google/evcxr#82)
Fixes #4915

REPL: Don't add commands with errors to completion context

---

src/201/main/kotlin/org/rust/cargo/runconfig/RsDefaultProgramRunnerBase.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4905.

RUN: Fix code coverage runner on 2020.1

---

src/main/kotlin/org/rust/stdext/Profiling.kt
src/test/kotlin/org/rustPerformanceTests/RsParsingPerformanceTest.kt

T: add parser benchmark

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4865

ACT: Show cargo tool window after attaching a cargo project

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt

Fixes #3781
Fixes #4732
Fixes #4943

RES: resolve/completion for trait object inherent impl

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4808.

TY: Fix type checking for async blocks

---

src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

INT: fixed ImplementMembersFix for Fn type

---

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
src/main/kotlin/org/rust/ide/colors/RsColors.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt

Closes first part of #2256
Do i need to add more tests?

ANN:Format macros syntax support

---

src/main/kotlin/org/rust/ide/folding/RsCodeFoldingOptionsProvider.kt

It should fix NPE with some 2020.1 EAP builds
Fixes #4981

Provide correct title for code folding settings panel

---

build.gradle.kts

Now it doesn't commit anything in `intellij-rust.github.io` repo

GRD: simplify `makeRelease` task

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt

RUN: fix incorrect configuration factory id

---

src/main/kotlin/org/rust/ide/console/RsConsoleActions.kt
src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt

* Stop execution
* Toggle soft wrap
* Toggle scroll to end
* Print console content
Should be merged after #4879 (so "close repl console" action will work as expected)

REPL: Add more actions

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt
src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt

RES&MACRO: evaluate `cfg` in macro resolve

---

toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt

Fix #4840 crate documentation gutter blinking

---

.github/workflows/publish-rust-nightly.yml
build.gradle.kts
gradle.properties

Now nightly builds should be published by github workflow

CI: initial version of nightly publish workflow

---

src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

REF: use initialization shorthand after rename

---

.github/workflows/check.yml
.github/workflows/rust-nightly.yml

CI: rename workflows

---

.github/workflows/check.yml
.github/workflows/rust-nightly.yml

CI: specify fail strategy explicitly

---

README.md

DOC: fix readme link

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt

TY: better disambiguate inherent/trait methods & assoc items

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/test/kotlin/org/rust/common.kt

The bug was introduced in #4872

Fix possible crash during components save

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherIntegrationTest.kt

Also disable CargoTomlWatcher in most of tests

T: fix DisposalException in tests

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Relates to https://github.com/intellij-rust/intellij-rust/issues/4917.

ANN: Annotate slice patterns as experimental

---

gradle-201.properties
grazie/src/201/test/kotlin/org/rust/grazie/RsGrammarCheckingTestBase.kt
src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTest.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt

GRD: update 2020.1 EAPs

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt

https://doc.rust-lang.org/error-index.html#E0451

ANN: Detect E0451: constructing struct which has private field

---

intellij-toml/src/main/resources/META-INF/pluginIcon.svg
intellij-toml/src/main/resources/META-INF/pluginIcon_dark.svg

They should be rendered in plugin dialog and in marketplace

TOML: add plugin icons

---

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt

COMP: Provide completion for `union` keyword

---

.github/workflows/check.yml
.travis.yml
src/main/kotlin/org/rust/cargo/toolchain/Rustup.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt

CI: print rustc version in github workflow

---

src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt
src/main/kotlin/org/rust/ide/refactoring/RsInPlaceVariableIntroducer.kt
src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt
src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntentionTest.kt

INT: Temporarily disable "Extract enum variant" intention

---

src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt
src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5117

COMP: fix println postfix template for string variables

---

src/main/kotlin/org/rust/ide/typing/assist/CommaFixer.kt
src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt

COMP: Insert trailing comma in match after "Complete current statement"

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

Make `MacroExpansionFileSystem` extends `NewVirtualFileSystem`. It should prevent local history from watching events from macro vfs
Fixes #5178

Fix local history

---

build.gradle.kts
clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
gradle-201.properties
gradle.properties
grazie/src/201/test/kotlin/org/rust/grazie/RsGrammarCheckingTestBase.kt
src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
src/main/kotlin/org/rust/cargo/icons/CargoIcons.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
src/main/kotlin/org/rust/ide/icons/RsIcons.kt
src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt
src/main/kotlin/org/rust/ide/refactoring/introduceParameter/ui.kt
src/main/kotlin/org/rust/ide/template/RsLiveTemplatesProvider.kt
src/main/kotlin/org/rust/ide/todo/RsTodoApplicationComponent.kt
src/main/kotlin/org/rust/ide/update/UpdateComponent.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt

Also, update 2020.1 EAPs and enable tests with grazie

GRD: make 2020.1 main platform for development

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/Evcxr.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5070.

RUN: Set TERM variable and terminal's width if terminal emulation is enabled

---

src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt
src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
src/test/kotlin/org/rust/ide/inspections/RsExtraSemicolonInspectionTest.kt

Rebased version of #4912
Closes #4912

ANN: highlight exit points if last statement is loop

---

intellij-toml/src/main/resources/META-INF/plugin.xml

TOML: toml changelog

---

src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt
src/main/kotlin/org/rust/ide/inspections/fixes/AddWildcardArmFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt

Fix `Add _ pattern` and` Add remaining patterns` generated code being incorrect

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt

The bug was introduced in #5187. There were no notifications if no attached cargo projects.
(to be cherry-picked to 120)

Fix editor notifications if no cargo projects

---

.github/workflows/check.yml
.travis.yml
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt
src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTest.kt
src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestBase.kt
src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt

Add tests for REPL integration:
* Communication with Evcxr
* Completion in REPL console
(copy of #4920, for some reason that PR failed to merge)

T: REPL integration

---

src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt

INT: Fix SpecifyTypeExplicitlyIntention on `ref` pat bindings

---

src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTest.kt
src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestBase.kt
src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestFixture.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixture.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt

Refactor console completion tests to reuse code from completion test fixtures and avoid code duplication

T: introduce RsConsoleCompletionTestFixture

---

src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt
src/test/kotlin/org/rust/lang/core/type/RsPatternMatchingTest.kt

Relates to https://github.com/intellij-rust/intellij-rust/issues/4917.

TY: Type inference for subslice patterns

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt

Should fix issues like #5225
The proper fix should be done in platform. See https://youtrack.jetbrains.com/issue/IDEA-237376

Fix file type mapping for Rust file in IDEA 2020.1

---

src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt

Replaces `invokeLater` with `smartnvokeLater`

REPL: Fix IndexNotReadyException when execute command during dumb mode

---

src/main/kotlin/org/rust/ide/presentation/RsDescriptionProvider.kt

It will be used in conflicts view in move refactoring (#5181)

REF: Support RefactoringDescriptionLocation in DescriptionProvider

---

debugger/src/main/resources/META-INF/debugger-only.xml
src/main/resources/META-INF/rust-core.xml

Make all extension points of Rust plugin dynamic

---

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt

REF: don't remove empty lines in "Extract function"

---

src/main/grammars/RustParser.bnf
src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTest.kt

REPL: Fix parsing top-level statements

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5110.

ACT: Don't try to initialize Cargo Tool Window if it already initialized

---

src/main/kotlin/org/rust/ide/inspections/RsLint.kt
src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
src/test/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspectionTest.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/3844.

INSP: Provide suppress quick fixes for needless_lifetimes inspection

---

src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

INT: add support for `extern` keyword in ImplementMembersFix

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

The bug was introduced in #5245
bors r+

Fix macro expansion task cancellation

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt

It will be used in move refactoring (#5181)

REF: Support binding RsPath to RsMod

---

src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt

RUN: start build project in EDT

---

scripts/update-changelog-link.py

CI: don't miss leading zeros in changelog link

---

src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt
src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt
src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/Kind.kt
src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/test/kotlin/org/rust/ide/hints/RsExpressionTypeProviderTest.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5305.

TY: Trait object takes into account all trait bounds

---

src/main/kotlin/org/rust/ide/typing/assist/AfterSemicolonEnterProcessor.kt
src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt

* don't add new line by `complete current statement` action (`Cmd+Shift+Enter`) after `;` completion
* insert empty line by `complete current statement` action (`Cmd+Shift+Enter`) on empty line

TYPE: improve complete current statement action

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/stdext/io.kt

Fixes UI freezes during project save. 
Fixes #5198
Depends on #5245

MACRO: save MacroExpansionManager asynchronously

---

.github/workflows/check.yml

Preparation to make github actions default CI for the project

CI: use windows runners on github action to run tests

---

src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFix.kt
src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt
src/main/kotlin/org/rust/ide/hints/RsExpressionTypeProvider.kt
src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt
src/main/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntention.kt
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt
src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt

Get rid of predefined type renderers

---

build.gradle.kts

It should fix issue with dynamic plugin unloading

GRD: downgrade gradle intellij plugin

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt
src/test/kotlin/org/rust/ide/inspections/RsRedundantElseInspectionTest.kt
src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5353.

INSP: Fix false positive in refutability check

---

src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
src/main/kotlin/org/rust/ide/presentation/Utils.kt
src/test/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProviderTest.kt

Improve:
* block expr
* loop expr
* macro expr
* lambda expr
* if / else
* for
* while
* match / match arm
* test method
Fixed #5271

Improve breadcrumbs

---

src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

Fix control flow analysis of paren expression

---

coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt

https://github.com/mozilla/grcov#example-how-to-generate-gcda-files-for-a-rust-project
Fixes https://github.com/intellij-rust/intellij-rust/issues/5340.

RUN: Fix environment variables for Coverage runner

---

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5378

ANN: don't annotate unknown types in format macros

---

src/main/kotlin/org/rust/ide/intentions/ReplaceBlockCommentWithLineCommentIntention.kt
src/main/kotlin/org/rust/ide/intentions/ReplaceLineCommentWithBlockCommentIntention.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/intentionDescriptions/ReplaceBlockCommentWithLineCommentIntention/after.rs.template
src/main/resources/intentionDescriptions/ReplaceBlockCommentWithLineCommentIntention/before.rs.template
src/main/resources/intentionDescriptions/ReplaceBlockCommentWithLineCommentIntention/description.html
src/main/resources/intentionDescriptions/ReplaceLineCommentWithBlockCommentIntention/after.rs.template
src/main/resources/intentionDescriptions/ReplaceLineCommentWithBlockCommentIntention/before.rs.template
src/main/resources/intentionDescriptions/ReplaceLineCommentWithBlockCommentIntention/description.html
src/test/kotlin/org/rust/ide/intentions/ReplaceBlockCommentWithLineCommentIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/ReplaceLineCommentWithBlockCommentIntentionTest.kt

A completed version of #4856
Fixes #4719

INT: Add "Replace with block/EOL comment" intentions

---

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt

All inlay hint settings are located under `Preferences | Editor | Inlay Hints | Rust` and no need to duplicate these options

UI: drop hint options from rust project setting panel

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/stdext/io.kt

Fix crash during project save on PHPStorm

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5401.

RES: Fix struct field resolve when using type alias

---

src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5280.

RUN: Fix debug when terminal emulator is enabled

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

It looks like `PsiDirectory.getFiles()` is slow, so let's avoid it.
Slightly speeds up macro expansion.

PERF: optimize module declaration resolution

---

src/main/kotlin/org/rust/lang/core/macros/RsFileTypeOverriderForMacroExpansionFileSystem.kt
src/main/resources/META-INF/rust-core.xml

Slightly speeds up macro expansion

PERF&MACRO: FileTypeOverrider for macro expansions

---

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt

ANN: don't annotate format-like non-stdlib marcos

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt

StringBuffer was used unintentionally
bors r+

Replace StringBuffer to StringBuilder

---

src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt

DBG: advertise native debug plugin only for cargo run configurations

---

MAINTAINING.md

DOC: fix label links in MAINTAINING.md

---

src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt

Fix UI freezes caused by chain method hints

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/ide/refactoring/inline/RsInlineFunctionHandler.kt
src/main/kotlin/org/rust/ide/refactoring/inline/RsInlineFunctionProcessor.kt
src/main/kotlin/org/rust/ide/refactoring/inline/ui.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt

Rebased then fixed compilation issues with #3176 .
I had the exact compilation error with `suggestedNames()` as the CI server and was able to fix it, @sohich would be great if you could take a look at this

Ide refactoring inline method

---

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/4533

UI: sort packages and targets alphabetically in Cargo tool window

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt

T: fix RsRealProjectAnalysisTest

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5520

FIX: add unsafe now also works inside loops and conditions

---

src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt
src/test/kotlin/org/rust/ide/inspections/fixes/AddMainFnFixTest.kt

Improve quick fix introduced in #5481

INSP: navigate to created main function

---

.idea/runConfigurations/RunCLion.xml
.idea/runConfigurations/RunIDEA.xml

Fix log paths for RunIDEA and RunCLion run configurations

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: support E0435 error detection

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
src/main/resources/META-INF/rust-core.xml

Turn RsPsiManager into a service

---

src/main/kotlin/org/rust/ide/search/RsTraitOrImplGroupingRuleProvider.kt

The bug was introduced in #4480 
<details>
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type PATH (class org.rust.lang.core.stubs.RsPathStub$Type)
at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:79)
at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
at org.rust.lang.core.resolve.ref.RsResolveCache.refineDependency(RsResolveCache.kt:114)
at org.rust.lang.core.resolve.ref.RsResolveCache.resolveWithCaching(RsResolveCache.kt:95)
at …
```

Fix PsiInvalidElementAccessException in RsImplGroupingRule

---

src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt

<details>
```
com.intellij.psi.PsiInvalidElementAccessException: Element class com.intellij.psi.impl.source.tree.CompositeElement of type STRUCT_ITEM (class org.rust.lang.core.stubs.RsStructItemStub$Type)
at com.intellij.psi.PsiInvalidElementAccessException.createByNode(PsiInvalidElementAccessException.java:96)
at com.intellij.psi.impl.source.SubstrateRef$2.getContainingFile(SubstrateRef.java:101)
at com.intellij.extapi.psi.StubBasedPsiElementBase.getContainingFile(StubBasedPsiElementBase.java:253)
at com.intellij.extapi.psi.StubBasedPsiElementBase.getProject(StubBasedPsiElementBase.java:291)
at org.rust.lang.core.macros.RsExpandedElementKt.getExpandedFrom(RsExpandedElement.kt:49)
at org.rust.lang.core.macros.RsExpandedElementKt$findMacroCallExpanded …
```

Fix PsiInvalidElementAccessException in structure view

---

src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt

<details>
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:81)
at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:706)
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:656)
at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:525)
at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:381)
at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
at org.rust.lang.core.stubs.index.RsModulesIndex$Companion.getDeclarationFor(RsMo …
```

Fix IndexNotReadyException in RustfmtListener

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5572

FIX: correctly complete parentheses for Fn like traits

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/4733

ANN: fix false positive of impl Trait in associated type binding

---

src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt
src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5109

FIX: liveness analysis now takes into account destructured struct parameters

---

src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt

This PR fixes tuple struct constructor references replacing in `RsExtractEnumVariant`.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5269
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5565

REF: fix indirect tuple usage replacement in RsExtractEnumVariant

---

src/main/kotlin/org/rust/ide/actions/RsJoinLinesHandler.kt
src/main/kotlin/org/rust/ide/actions/RsJoinRawLinesHandler.kt
src/test/kotlin/org/rust/ide/actions/RsJoinLinesHandlerTest.kt

Fix unable to join doc comment lines

---

src/main/kotlin/org/rust/ide/inspections/RsDeprecationInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsLint.kt
src/main/kotlin/org/rust/ide/inspections/RsLintInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsLintLevel.kt
src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsNeedlessLifetimesInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsLintLevelTest.kt
src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt

* Associate annotation level with lint level
* Support for `forbid` attribute
Closed #5567

INSP: Improve lint check

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt

RES: take into account namespace during shadowing

---

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTestBase.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5366.

RUN: Unescape test output

---

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt

CLEAN: get rid of extra `itemKindName`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/RemoveReprValueFix.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/RemoveReprValueFixTest.kt

Support:
* `E0517`
* `E0552`
Closed #5566

ANN: Enhanced Repr error detection

---

.idea/vcs.xml

Provide issue/pr navigation in git log in IDE

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt

For some reason, it was broken when used with the new expansion engine

MACRO: fix `#[macro_export(local_inner_macros)]`

---

.idea/vcs.xml

Enable proofreading in commit messages

---

src/main/kotlin/org/rust/ide/annotator/RsHighlightingPassFactoryRegistrar.kt
src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt

Closes #3706
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/85294528-6b3e3b00-b4a7-11ea-838a-29d327a7d873.png) | ![image](https://user-images.githubusercontent.com/2539310/85294250-139fcf80-b4a7-11ea-8708-16eed07adab1.png) |

MACRO&ANN: enable advanced highlighting inside macro call bodies

---

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyWithDerefsRefsFix.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyWithDerefsRefsFixTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5519

INSP: add more specific text to ConvertToTyWithDerefsRefsFix

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt

This is a bit of a weird one.
It took me a bit to work out what was happening.
Basically, using a symlinked project caused one or two weird bugs.
Create a cargo project, symlink the folder, open intellij through the symlink.
We use `cargo metadata` to generate the metadata, and find the workspace root, but the problem is cargo doesn't know or care about the location from which the command was sent.  
It returns back the resolved path, not the symlinked path.
This caused some problems later when we need to resolve files against that directory.
Such as during the error reporting.
The `FileLocation`s are resolved against that root directory, and therefore use the non-symlink file.
Due to how intellij-rust does module detection, it determined that it wasn't a part of the module structure.

Correctly handle symlinked Cargo project directories.

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Fix false-positive E0015 in case of const parameter

---

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt

Fix: https://github.com/intellij-rust/intellij-rust/pull/5640#discussion_r446491580

FIX: Wrong xml escape replace order

---

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectTreeStructure.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt

`custom-build` is a target kind for `build.rs`

Add `custom-build` cargo target kind

---

src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt

Structure View: add alpha sorter

---

src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt

Fix `Lift return` inspection on empty match expr

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
src/main/resources-nightly/META-INF/experiments.xml
src/main/resources-stable/META-INF/experiments.xml

Fixes https://github.com/intellij-rust/intellij-rust/issues/5676.

RUN: Add an experimental feature to enable/disable Test Tool Window

---

coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt

Not sure if this fixes the problem, but let's try it.
cc @Undin

T: Fix tests for code coverage

---

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt

Relates to https://github.com/intellij-rust/intellij-rust/issues/5676.
Relates to https://github.com/intellij-rust/intellij-rust/issues/4583.
Relates to https://github.com/intellij-rust/intellij-rust/pull/5549#issuecomment-651993198.

RUN: Show cargo output in Test Tool window

---

debugger/src/main/kotlin/org/rust/debugger/lang/RsEvaluator.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt
src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/main/kotlin/org/rust/ide/inspections/fixes/SubstituteTextFix.kt
src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/RsAddFmtStringArgumentPopup.kt
src/main/kotlin/org/rust/ide/lineMarkers/RsRecursiveCallLineMarkerProvider.kt
src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
src/main/kotlin/org/rust/openapiext/utils.kt
src/test/kotlin/org/rust/FileTree.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoDependencyReferenceProvider.kt
toml/src/test/kotlin/org/rust/toml/CargoTomlGotoSuperHandlerTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/4208.

T: Fix jump from test results to doctest

---

.github/workflows/check.yml
.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml

* declare env variables via workflow syntax if possible
* check oldest IDE versions

CI: improve github workflows

---

coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt

T: Disable Coverage Runner tests on CI

---

clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5743

FIX: set expired Valgrind callback parameter to nullable

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt

INSP: support auto import with module reexports with aliases

---

intellij-toml/src/main/resources/META-INF/plugin.xml

Update toml changelog

---

src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt

Fix mod declarations with #[path = "mod.rs"] attribute

---

CONTRIBUTORS.txt
src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RsBoolCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/test/kotlin/org/rust/lang/core/completion/RsBoolCompletionTest.kt

Fixes #4443 (_"No true/false autocomplete for boolean values"_)

COMP: true/false completion for bool values

---

src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionWritingAccessProvider.kt
src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt

CLEAN: fix some deprecated API usages

---

src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerformanceTest.kt

T: fix the performance test

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

TY: fix self substitution in bounds

---

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt

[CARGO] Include RUSTC in environment

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

RES: fix private reexport with `crate::` path

---

src/main/kotlin/org/rust/ide/navigation/goto/RsGoToDeclarationRunningService.kt
src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt

Fixes #5531
The old hack doesn't work anymore, I invented a new one

Fix navigation to derive items in 2020.2

---

.github/workflows/check.yml
src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/5823.

RES: Fix stdlib source paths on nightly

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsPartialParseCompletionTest.kt

This PR reverts https://github.com/intellij-rust/intellij-rust/pull/5659, as discussed in https://github.com/intellij-rust/intellij-rust/issues/5875.

Revert "Merge #5659"

---

.github/workflows/check.yml
coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt

RUN: Show error message when trying to run with coverage on non-nightly channel

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

https://github.com/intellij-rust/intellij-rust/pull/5582#discussion_r443247691

ANN: Fix custom macro attr (name conflicts)

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

PERF: slightly optimize let bindings resolve

---

src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/5868

INSP: do not offer ChangeReturnTypeFix in lambdas without an explicit return type

---

src/main/kotlin/org/rust/ide/typing/assist/AfterFunctionOrStructEnterProcessor.kt
src/main/kotlin/org/rust/ide/typing/assist/FunctionOrStructFixer.kt
src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt
src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt

COMP: Support function and struct complete current statement

---

.github/workflows/check.yml

CI: use actions/checkout v2 instead of v1

---

MAINTAINING.md

Missing docs for changes made in #5946
bors r+

DOC: update doc about release branch creation

---

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt

E.g. when moving some struct, all its impls will be added to initial items to move

REF: Add related impls to initial items to move

---

src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandAction.kt
src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/Utils.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfigurationType.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/ui/WasmPackCommandConfigurationEditor.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/util/WasmPackCommandCompletionProvider.kt
src/main/kotlin/org/rust/cargo/toolchain/CargoCommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/WasmPackCommandLine.kt
src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
src/main/kotlin/org/rust/cargo/util/ParametersListLexer.kt
src/main/kotlin/org/rust/cargo/util/RsCommandCompletionProvider.kt
src/main/kotlin/org/rust/cargo/util/RsCommandLineEditor.kt
src/main/kotlin/org/rust/ide/actions/runAnything/RsRunAnythingItem.kt
src/main/kotlin/org/rust/ide/actions/runAnything/RsRunAnythingProvider.kt
src/main/kotlin/org/rust/ide/actions/runAnything/cargo/CargoRunAnythingProvider.kt
src/main/kotlin/org/rust/ide/actions/runAnything/cargo/RunAnythingCargoItem.kt
src/main/kotlin/org/rust/ide/actions/runAnything/wasmpack/RunAnythingWasmPackItem.kt
src/main/kotlin/org/rust/ide/actions/runAnything/wasmpack/WasmPackRunAnythingProvider.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/actions/runAnything/cargo/CargoRunAnythingProviderTest.kt
src/test/kotlin/org/rust/ide/actions/runAnything/wasmpack/WasmPackRunAnythingProviderTest.kt

Provides command completion in Run Anything and Run Configurations editor dialog.
Depends on #5745

RUN: Command completion for wasm-pack 

---

src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt
src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt

(via cargo-generatete template https://github.com/eupn/rust-procmacro-quickstart-template)

PRJ: Add Procedural Macro project template

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt

Disables expansion of cfg-disabled macro calls during full expansion (e.g. when new project is opened). In Cargo project it results in 50% reduction of total expanded calls (from 76973 to 34145) and about 35% reduction of total expansion time. I suppose main improvement in Cargo project comes from `winapi` crate ([example](https://github.com/retep998/winapi-rs/blob/0.3/src/um/mod.rs)).

PERF: Don't expand cfg-disabled macro calls

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt

RUN: Don't try to initialize Cargo Tool Window before project opened

---

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt

Fixes #5961
The bug was introduced in #5853

RES: fix issue #5961

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

This should not affect users anyhow, it's an internal change,
it will be used later in completion etc.
Now we fallback `expectedType` to its origin `TyTypeParameter`
instead of `TyUnknown`. It works for this:
```rust
fn foo<T>(t: T) {}
fn main() {
foo(foobar/*expectedType = T*/); // previously it was TyUnknown
}
```

TY: relax `expectedType` fallback

---

src/main/resources/META-INF/rust-core.xml
src/main/resources/intentionDescriptions/CreateFunctionIntention/after.rs.template
src/main/resources/intentionDescriptions/CreateFunctionIntention/before.rs.template
src/main/resources/intentionDescriptions/CreateFunctionIntention/description.html

Unblocks https://github.com/intellij-rust/intellij-rust/pull/6042

INT: add missing description and plugin registration for CreateFunctionIntention

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddPatRestFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddPatRestFixTest.kt

INT: introduce quick fix to add `..` to struct pattern that has missing fields

---

src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt

The bug was introduced in #5690 release-127
Fixes #5861, fixes #5962
_Probably we need a test for symlinked project_

Fix project under symlinked directory

---

build.gradle.kts
src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt

Also fix paths in `updateCompilerFeatures` grade task

Update compiler features

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfigurationType.kt

RUN: Rename "Cargo Command" run configuration to "Cargo"

---

src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

Adds additional tests related to resolve. These tests found some bugs in name resolution 2.0 implementation

T: Add additional resolve tests

---

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
src/main/resources/intentionDescriptions/CreateFunctionIntention/after.rs.template

I also noticed that the template for this intention had a typo. I think that it's a small enough change that we can bolt it onto this PR?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6098

INT: add missing title and fix typo in CreateFunctionIntention

---

.github/workflows/regressions.yml

tokio and amethyst projects are added by these changes

CI: extend list of real projects for regression testing

---

src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt

This PR adds support for detecting conflicts that can arise when bindings are renamed. The behaviour is inspired by the Kotlin/Java plugin, however I also added support for conflicts during renaming parameters (this doesn't happen in Kotlin/Java). I'm not sure if it's a good idea though.
The implementation uses `processLocalVariables` to find local bindings, so it only "sees" existing names that are available at the place of the binding which is being renamed.
```rust
fn test() {
let c/*rename to a*/ = 1;  // no conflict
let a = 1;
let b/*rename to a*/ = 1;  // conflict
}
```
I'm not sure what's the best behaviour here. Renaming `c` to `a` should be fine, but only if there is no usage of `c` that follows the declaration of the previous `a` binding. To support this scenario we would have …

REF: handle name conflicts after renaming bindings

---

debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt

DBG: properly update debugger after NativeDebug plugin update

---

src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt
src/test/kotlin/org/rust/RsTestBase.kt

REF: don't rename `src` dir

---

src/test/kotlin/org/rust/cargo/RustupTestFixture.kt

Should fix timeout issue in #5444

T: add cargo home to allowed roots

---

src/202/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt
src/202/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt
src/202/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt

T: Update Build tool window tests to 202

---

.github/workflows/check.yml
.github/workflows/regressions.yml
.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml
CONTRIBUTING.md
build.gradle.kts

It's required to build the plugin for 2020.3 platform

Use Java 11 to build and develop the plugin

---

CONTRIBUTING.md

DOC: fix typo

---

src/test/kotlin/org/rust/cargo/RustupTestFixture.kt

T: resolve symlink to Cargo home properly

---

src/main/kotlin/org/rust/cargo/toolchain/Grcov.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6169.

RUN: Fix `Run with Coverage` on nightly channel

---

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6175.

T: Show test result in the gutter

---

src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
src/test/kotlin/org/rustSlowTests/ide/lineMarkers/CargoTestLineMarkerStatusTest.kt

T: Fix tests for test status icon

---

.idea/vcs.xml
CONTRIBUTING.md

Enable commit message inspections

---

gradle-203.properties
src/main/kotlin/org/rust/ide/wordSelection/RsMacroCallSelectionHandler.kt

GRD: update 2020.3 EAPs

---

src/main/kotlin/org/rust/ide/intentions/RemoveDbgIntention.kt
src/test/kotlin/org/rust/ide/intentions/RemoveDbgIntentionTest.kt

INT: don't remove required parentheses in RemoveDbgIntention

---

build.gradle.kts

Now we use 0.5 gradle-intellij-plugin. See the corresponding [changes](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/CHANGES.md#050)

GRD: update gradle plugins

---

src/main/kotlin/org/rust/cargo/project/model/CargoProjectActionBase.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectsAction.kt
src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
src/main/kotlin/org/rust/openapiext/TaskResult.kt
src/main/kotlin/org/rust/stdext/Concurrency.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt

Show all major steps of project structure loading.
Also, provide a more convenient way to show errors for users
Part of #6104

CARGO: initial support for Sync tool window

---

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/pull/6221#discussion_r502271725.

INT: fix availability check in CreateFunctionIntention

---

src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt
src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunStateBase.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Evcxr.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Grcov.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/RsTool.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/WasmPack.kt
src/main/kotlin/org/rust/ide/actions/InstallComponentAction.kt
src/main/kotlin/org/rust/ide/actions/RustfmtCargoProjectAction.kt
src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
src/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt
src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/RustupTestFixture.kt

Refactor `tools` package

---

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesDialog.kt
src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTestBase.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveMultipleFilesTest.kt

[Move refactoring](https://github.com/intellij-rust/intellij-rust/issues/3531#issuecomment-643142894) improvements:
* Support move multiple files/directories
* Support move file to another crate
This pull requests mostly changes only move handler (it finds which exactly files should be moved). Actual implementation was added in #5736 and #6080

REF: Support move multiple files

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
toml/src/main/kotlin/org/rust/toml/Util.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlDependencyFeaturesReferenceProvider.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlNameResolution.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt
toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlDependencyFeaturesReferenceProviderTest.kt
toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProviderTest.kt
toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlResolveTestBase.kt

Completion and `find usages` will be done in a separate PRs.

RES: resolve cargo features in `Cargo.toml`

---

src/main/kotlin/org/rust/ide/utils/checkMatch/CheckMatchUtils.kt
src/main/kotlin/org/rust/ide/utils/checkMatch/Constructor.kt
src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt

INSP: Check that match on uninhabited type cannot be unexhaustive

---

src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt

Fix control flow of async blocks

---

.idea/vcs.xml

Fix spaces in vcs.xml

---

src/main/kotlin/org/rust/lang/core/completion/lint/RsLintCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsLintCompletionProviderTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/6311

COMP: do not complete lints for paths starting with leading ::

---

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveTraitMethodsProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt

REF: Add trait imports in move refactoring if necessary

---

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt

Show warning in move refactoring if target mod has an item with the same name

REF: Check if target mod has item with same name in move refactoring

---

src/main/kotlin/org/rust/ide/actions/runAnything/RsRunAnythingProvider.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6321.

RUN: Take into account execution context in Run Anything

---

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt
src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt
src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt

REF: Support references to generic items in move refactoring

---

src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt

COMP: add completion of track_caller attribute for functions

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt

Support resolve of attribute and bang proc macros in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217)
Depends on #6317

RES: Support resolve of attribute and bang proc macros in new resolve

---

src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt
src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt

PRJ: Use Task.Modal and ProcessAdapter in component downloading modals

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/6334

COMP: add completion for the non_exhaustive attribute

---

toml/src/202/test/kotlin/org/rust/toml/completion/CargoTomlCompletionEditionTestBase.kt
toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
toml/src/main/kotlin/org/rust/toml/Util.kt
toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyFeaturesCompletionProvider.kt
toml/src/main/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProvider.kt
toml/src/main/kotlin/org/rust/toml/completion/CargoTomlLookupElements.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlDependencyFeaturesReferenceProvider.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
toml/src/test/kotlin/org/rust/toml/completion/CargoTomlCompletionTestBase.kt
toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependencyFeaturesCompletionProviderTest.kt
toml/src/test/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProviderTest.kt

Continuation of #6204 - now with features completion in `Cargo.toml` !
Related to #4693

COMP: complete cargo features in `Cargo.toml`

---

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
src/test/kotlin/org/rust/NewResolve.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2018.kt
src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt

Add option to settings to enable [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217)
TODO: Prepare some text for changelog

RES: Add option to settings to enable new resolve

---

.github/workflows/regressions.yml

CI: use default platform version for regression tests

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt

Refactor & very slightly optimize `RsExpandedElement.getContextImpl` that affects highlighting and other analysis.
changelog: Slightly optimize highlighting

PERF: optimize `RsExpandedElement.getContextImpl`

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt
toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt
toml/src/main/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProvider.kt
toml/src/main/resources/META-INF/toml-only.xml
toml/src/test/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProviderTest.kt

RES: resolve cfg/cfg_attr features to Cargo.toml in Rust code

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt

This speeds up macro expansion up to 30% if the new name resolution is enabled (#6217 )

PERF&MACRO: optimize crate search in macro expansion with new resolve

---

clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6173.
Now, in case of no `perf` path specified in settings, "Perf executable path is not set" error will be shown with a link to configure the profiler settings (the way how it works in CLion with C/C++).

Validate perf profiler settings

---

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt

Fixes exception in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217) when we resolve import in shadowed mod (not accessible from `CrateDefMap` root because of some other mod with same `crateRelativePath`). We already ignore such imports if they are collected during collecting explicitly declared items. In this PR we also ignore imports added by macro expansion.
<details>
```
java.lang.AssertionError: Can't find ModData for process::imp::reap in crate tokio(lib)
at org.rust.lang.core.resolve2.CrateDefMap.doGetModData(CrateDefMap.kt:466)
at org.rust.lang.core.resolve2.CrateDefMap.getModData(CrateDefMap.kt:75)
at org.rust.lang.core.resolve2.CrateDefMap.tryCastToModData(CrateDefMap.kt:88)
at org.rust.lang.core.resolve2.PathResolutionKt.resolvePathFp(PathResolution.kt:67 …
```

RES: Fix exception when resolving import in cfg-disabled shadowed mod using new resolve

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

T: fix empty test fail if the test is `@ExpandMacros`

---

clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt

See https://github.com/intellij-rust/intellij-rust/pull/6323 for more details.
changelog: Validate DTrace profiler settings when running code with CPU profiler on macOS

Validate DTrace profiler settings

---

src/main/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspection.kt
src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTestBase.kt
src/test/kotlin/org/rust/lang/core/completion/RsLintCompletionProviderTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt

changelog: take into account `cfg_attr` attribute while attribute and lint attribute completion

COMP: take into account `cfg_attr` attribute while attribute completion

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt

Now, logic with `META_ITEM_ATTR` is encapsulated in single method

Refactor `rootMetaItem` pattern

---

src/main/kotlin/org/rust/ide/presentation/Utils.kt

Show cfg-disabled items grayed in structure view

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt

Fixes #6522
TODO measure performance impact
changelog: TODO

PERF: fix name resolution performance in large modules

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt

Support multiple macros with same name in same mod when using [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217)
changelog: Proper resolve textual scoped macros in new resolve

RES: Proper resolve textual scoped macros in new resolve

---

src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt
src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt

changelog: Properly handle rename of enum variant when using new resolve

RES: Fix DefMap updating when changing enum variant name

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6540.

RUN: Fix rendering of ANSI escape codes in Build view

---

common/src/test/kotlin/com/intellij/ide/annotator/AnnotationTestFixtureBase.kt
grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt
src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt
src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorToolchainTest.kt
src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
src/test/kotlin/org/rust/ide/annotator/RsWithToolchainAnnotationTestBase.kt
src/test/kotlin/org/rust/ide/annotator/RsWithToolchainAnnotatorTestBase.kt
src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt
src/test/kotlin/org/rust/ide/inspections/RsMultipleInspectionsTestBase.kt
src/test/kotlin/org/rust/ide/inspections/RsWithToolchainInspectionTestBase.kt
toml/src/test/kotlin/org/rust/toml/inspections/MissingFeaturesInspectionTest.kt

These new test infrastructure classes should simplify addition of new annotator/inspection tests that require actual toolchain

T: basic test classes for annotation checking with actual toolchain

---

src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
src/test/kotlin/org/rustPerformanceTests/RsBuildDefMapTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileBuildDefMapTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileResolveTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileTestBase.kt
src/test/kotlin/org/rustPerformanceTests/RsRealProjectTestBase.kt

These tests can be used to profile cpu and memory usage of new resolve

RES: Add performance tests for new resolve

---

src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt

Previously, the plugin downloaded stdlib dependencies (call `cargo vendor`) into src directory.
But such approach didn't take into account read-only file systems and stdlib updates properly.
Now, stdlib dependencies are downloaded into IDE system dir and its path depends on rustc version
Continuation of #6417
Fixes #6603
changelog: TODO

CARGO: download stdlib dependencies into system dir

---

src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/6677
changelog: Fix extracting selected statements into a function inside blocks.

REF: correctly extract selected statements inside blocks into a function

---

toml/src/main/kotlin/org/rust/toml/CargoTomlElementDescriptionProvider.kt
toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspection.kt
toml/src/main/kotlin/org/rust/toml/search/CargoTomlFindUsagesHandlerFactory.kt
toml/src/main/kotlin/org/rust/toml/search/CargoTomlUsageTypeProvider.kt

TOML: add missing TOML abi compatibility checks

---

src/main/kotlin/org/rust/ide/intentions/ListIntention.kt
src/test/kotlin/org/rust/ide/intentions/JoinParameterListIntentionTest.kt

INT: fix incorrect replacing when no space between parameters in JoinParameterListIntention

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceFeatureAttributeFixTest.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/6361.

ANN: Support `min_const_generics` feature

---

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt
src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt

INT: Support async function by create function intention

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt
src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt

TY&ANN: fix false-positive E0277

---

.gitignore

Add root bin dir to gitignore

---

.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml

CI: fix release workflows

---

src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/RsCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6292.
changelog: Show test hierarchy tree on the client when using "Code with me" plugin

RUN: Show test hierarchy tree on the client when using "Code with me" plugin

---

.github/workflows/release-branch.yml
scripts/github.py
scripts/make_next_milestone.py

changelog: Create new milestone automatically during new branch creation

CI: create new milestone during new branch creation

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Fixes #6610
changelog: Fix false-positive "Expected trait, found trait alias" error

ANN: Fix false-positive "Expected trait, found trait alias"

---

build.gradle.kts

- dropped unnecessary tasks and task dependencies
- update gradle plugins

GRD: minor build script improvements

---

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt
src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/6793
changelog: Apply `Change Signature` refactoring to the called function when invoked on function and method calls.

REF: allow applying the Change Signature refactoring to function calls

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Related: #6308, #6776, #886
changelog: Detect [E0117](https://doc.rust-lang.org/error-index.html#E0117) compiler error

ANN: Check E0117 "Trait impls orphan rules"

---

gradle/wrapper/gradle-wrapper.properties

GRD: update gradle

---

src/main/kotlin/org/rust/cargo/runconfig/Utils.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
src/test/kotlin/org/rust/cargo/runconfig/CargoTestRunStateTest.kt
src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6802.
changelog: Add implicit build arguments to the beginning of the command line

RUN: Add implicit build arguments to the beginning of the command line

---

src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
src/main/kotlin/org/rust/openapiext/utils.kt

Cancel def map build by write action when def maps are building from macro expansion task
bors r+

Fix def map build cancellation

---

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt

Bug introduced in https://github.com/intellij-rust/intellij-rust/pull/6591
As it turns out, both `Gson` and `Jackson` can't work with inside-function classes.
Citation from https://github.com/FasterXML/jackson-module-kotlin/issues/135:
> It sounds like inner class you use would be non-static (as per exception). Such classes can not be deserialized since there is no access to implicit this reference that would be needed, at least on regular Java. I don't know if Kotlin allows some way make inner class static from JVM perspective; if so, that would make things work fine.
`Gson` is returning `null` in this case without any hint of what could go wrong.
This PR fixes the parsing logic by moving `ParsedVersion` out from the function and uses Jackson as it gives more understandable messages and …

Fix crate version json parsing

---

debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt
debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
gradle-211.properties
js/src/main/kotlin/org/rust/js/RsWasmBindgenLineMarkerProvider.kt
src/203/main/kotlin/org/rust/ide/structure/compatUtils.kt
src/203/main/kotlin/org/rust/lang/core/psi/ext/compatUtils.kt
src/211/main/kotlin/org/rust/ide/structure/compatUtils.kt
src/211/main/kotlin/org/rust/lang/core/psi/ext/compatUtils.kt
src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
src/main/kotlin/org/rust/ide/search/RsUsageTypeProvider.kt
src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt
src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt
src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt
src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
toml/src/main/kotlin/org/rust/toml/search/CargoTomlUsageTypeProvider.kt

Update 2021.1 IDE and plugin dependencies

---

debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt

UI: fix ClassCastException in debugger settings of 2021.1

---

src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt
src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToTupleProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt
src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/6693
changelog: Correctly move where blocks when converting between structs and tuples.

REF: handle where blocks in tuple <-> struct conversion

---

src/main/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMover.kt
src/main/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMover.kt
src/test/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMoverTest.kt

Up/Down mover: move `match arm` in closure

---

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve2/RsMultipleDefMapsUpdateTest.kt

changelog: Slightly optimize name resolution with new engine

PERF: Slightly optimize RsFile.super

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt

It should prevent deadlocks during service initialization
changelog: Prevent a possible deadlock during project structure setup

Initialize services outside of write action

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericParameter.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameterList.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt

Partially fixes https://github.com/intellij-rust/intellij-rust/issues/6943 (except inlay type hints).
changelog: Fix type rendering with const generic parameters

Fix type rendering with const generic parameters

---

.github/workflows/check.yml
.github/workflows/milestones.yml
.github/workflows/regressions.yml
.github/workflows/release-branch.yml
.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml
src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt

I incorrectly used method `.remove` while it was expected to use `.removeAll`. It leads to some sort of memory leak after changing type of `fileIdToCrateId` from `Map` to `MultiMap` in #6861

RES: Fix updating file maps in new resolve

---

intellij-toml/src/main/resources/META-INF/plugin.xml

TOML: update TOML plugin changelog

---

.github/workflows/check.yml

CI: increase timeout for check workflow

---

src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTest.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt

These tests were originally created when move refactoring was developed, but for some reason haven't been merged together with other code

T: Additional tests for move refactoring

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6441.
changelog: Fix inspection and name resolution for in-band lifetimes

ANN & RES: Fix in-band lifetimes support

---

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt
src/main/kotlin/org/rust/lang/core/resolve2/util/PathUtil.kt

Previously we have the following pipeline:
* Expand macros and get stubs
* Traverse stubs and put `$crate`-related info into stubs copyable user data
* When we collect stubs (`ModCollectorBase`), we adjust `$crate` paths based on copyable user data
In order to implement direct cache (without stubs) for macro expansions in new resolve, we need to refactor this pipeline. Also @vlad20012 think it may be useful for proc macros (that's why I created separate PR for it)
After this PR we will have the following pipeline:
* Expand macros and get stubs
* When we collect stubs (`ModCollectorBase`), store offset in expanded file in our light classes (e.g. `MacroCallLight`)
* When we transform our light classes to usual classes (e.g. `MacroCallLight` → `MacroCallInfo`), use those offsets to adjust …

RES: Refactor handling `$crate` when expanding macros in new resolve

---

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt

In Move refactoring we store some data in `PsiElement#copyableUserData`, and use it after move to restore mapping between old (original) and new (moved) elements. This PR refactors use of `copyableUserData` so that any previous unsuccessful invocations of move refactoring will not affect current invocation. Fixes #6449
changelog: Fix exception in Move refactoring when it was first cancelled and then invoked again

REF: Refactor restoring outside references in Move refactoring

---

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt

Uses `origin/HEAD` instead of `origin/master` to fetch the branch of registry index.
changelog: Fix loading crates local index on nightly rust

Fix fetching registry index branch on nightly

---

src/main/kotlin/org/rust/lang/core/crate/Crate.kt
src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt
src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt
src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt
src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt

Fixes the issue that caused #7030

MACRO: fix expansion if proc macro is added as separate cargo project

---

src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt
src/test/resources/org/rust/ide/folding/fixtures/where.rs

Support fold `where`

---

src/main/resources/META-INF/rust-core.xml

Disables changes introduced in #6581

Temporarily disable structured nav bar for Rust files

---

src/main/kotlin/org/rust/ide/annotator/RsAnnotationHolder.kt
src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt
src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt
src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt
src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt

I somehow missed this in #7187

Clean: fix CfgUtils.kt package

---

src/main/kotlin/org/rust/ide/statistics/RsProjectUsagesCollector.kt

Anonymize any counts by rounding to next power of two reported by `RsProjectUsagesCollector`

Anonymize info collected by `RsProjectUsagesCollector`

---

build.gradle.kts

I suppose the release of the [new name resolution engine](https://github.com/intellij-rust/intellij-rust/pull/7140) is a good reason to bump plugin version

Increase plugin version to 0.4

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/6644.

RUN: Add sanity check for missing input file

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt
src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/cargo/runconfig/producers/RunConfigurationProducerTestBase.kt

Should add the corresponding API for #7236

T: provide workspace root virtual file in tests

---

src/main/kotlin/org/rust/ide/statistics/RsProjectUsagesCollector.kt
src/main/kotlin/org/rust/ide/statistics/RsToolchainUsagesCollector.kt

General:
- Don't report anything if a project doesn't contain cargo projects
Toolchain usage collector: 
- support wsl toolchains
- use `EventFields.Enum` for `type` event instead of `EventFields.String`
Project usage collector:
- use `crateGraph` to handle the same dependencies in different cargo projects
- collect direct dependency count in addition to all dependency count (including transitive)
- report `0` instead of `1` if the original value is `0`

Update usage collectors

---

src/main/kotlin/org/rust/ide/statistics/RsToolchainUsagesCollector.kt

Lower case for toolchain type event

---

src/211/main/kotlin/org/rust/cargo/toolchain/wsl/Utils.kt

See https://github.com/intellij-rust/intellij-rust/issues/1171#issuecomment-849840336
changelog: Fix toolchain validation on WSL

RUN: Fix toolchain validation on WSL

---

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringExecution.kt
src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringUI.kt
src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt

Follow-up to https://github.com/intellij-rust/intellij-rust/pull/7135, adds support for default values.
changelog: Add support for default values to suggested change signature refactoring.

REF: add default values to suggested change signature refactoring

---

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/RsTool.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7245.
changelog: Fix fetching of cfg-options on WSL

RUN: Fix fetching of cfg-options on WSL

---

.idea/runConfigurations/RunCLion.xml
.idea/runConfigurations/RunIDEA.xml

Drop log files for 203 platform from run configurations

---

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt
src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
src/main/kotlin/org/rust/cargo/toolchain/RsLocalToolchainProvider.kt
src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainFlavor.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7203
changelog: Auto-select WSL based toolchain when opening a project inside WSL FS

PRJ: Auto-select WSL based toolchain when opening a project inside WSL FS

---

src/main/kotlin/org/rust/ide/highlight/RsHighlightAwaitHandlerFactory.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/highlight/RsHighlightAwaitHandlerFactoryTest.kt

TYPE: highlight all 'await' when under the caret

---

src/main/kotlin/org/rust/ide/highlight/RsHighlightAwaitHandlerFactory.kt
src/test/kotlin/org/rust/ide/highlight/RsHighlightAwaitHandlerFactoryTest.kt

TYPE: highlight chained 'await'

---

src/main/resources/org/rust/ide/colors/highlighterDemoText.rs

This PR shows changes made in #7243 in color scheme setting panel

Update color schema demo

---

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7197.
changelog: Fix pretty printers if WSL toolchain is used

DBG: Fix pretty printers if WSL toolchain is used

---

src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt
src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/7400
changelog: Parenthesize inlined expressions in Inline Value refactoring if they could produce invalid or semantically different code after performing the refactoring.

FIX: parenthesize expressions where needed in Inline Value refactoring

---

plugin/src/main/resources/META-INF/plugin.xml

PR removes the unnecessary dependencies on `com.intellij.modules.lang` in `plugin.xml`

Remove unnecessary platform dependencies

---

scripts/make_changelog_pull_request.py

CI: don't create changelog PR for closed milestone

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

Similar feature exists in Intellij for Java/Kotlin.
Demonstration: 
Variants are only suggested if this enum's type is expected
There is already completions for independent variants with autoimport, but I find that feature a bit lacking as it clutters namespace and users may not even know beforehand what variants an enum has. 
changelog: display enums with variants in code completion popup when appropriate

COMP: Display enums with variants in code completion popup when appropriate

---

intellij-toml/core/src/main/kotlin/org/toml/ide/annotator/TomlAnnotator.kt
intellij-toml/core/src/test/kotlin/org/toml/ide/annotator/TomlAnnotatorTest.kt

TOML: fix false-positive in multi-line array in inline table

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt

Intellij-Rust plugin currently supports only one stdlib at a time. If there are different standard libraries in
different cargo projects, select and use the most recent of them.
A cargo project may have a different stdlib if there is a `rust-toolchain.toml` file,
or if it uses `rustup override`

Use single stdlib

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt

See https://github.com/intellij-rust/intellij-rust/issues/6772#issuecomment-770784560 for an explanation why it is so complicated :D
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6772
changelog: Correctly fill empty function call arguments.

ANN: correctly fill empty function call arguments

---

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt

Reset the last commit hash of the index if the index PersistentHashMap size is 0.
This will fix the issues when the index file has been deleted or did not move with the state, e.g. when the latest IDE release copied the state without index map

Reset crates local index state if index is empty

---

src/main/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryAction.kt
src/test/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryActionTest.kt

Fixes #7041
changelog: Correctly handle root modules in "Promote module to directory" refactoring

REF: Handle root modules in "Promote module to directory" refactoring

---

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/test/kotlin/org/rust/ide/intentions/AddImplIntentionTest.kt

Closes #7465 
changelog: fixed "Add impl block" intention for structures with const generic parameters

INT: const generic parameters handling by "Add impl block" intention

---

src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt

T: fix regression tests

---

build.gradle.kts
gradle-211.properties

changelog: Migrate to [gradle-intellij-plugin 1.0](https://lp.jetbrains.com/gradle-intellij-plugin/)

GRD: migrate to gradle-intellij-plugin 1.0

---

src/main/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMover.kt
src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
src/main/kotlin/org/rust/ide/formatter/impl/utils.kt
src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt

Up/Down mover: move vec macro arguments

---

src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt
src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt

changelog: Support method calls using type qualifier in unused import inspection

INSP: Fix method call using type qualifier in unused import inspection

---

src/test/kotlin/org/rust/ide/annotator/fixes/DoctestFixTest.kt

I fixed issue #6790 in #7512. Here I've extracted tests from #7486 (thanks, @afetisov!)
Closes #7486

T: add tests for template builder in doctest

---

src/main/kotlin/org/rust/ide/inspections/RsLiftInspection.kt
src/test/kotlin/org/rust/ide/inspections/RsLiftInspectionTest.kt

INSP: add comma to match arm if needed in "Lift return out"

---

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt

changelog: Add option to enable unused import inspection in doctests

INSP: Add option to enable unused import inspection in doctests

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt
src/main/kotlin/org/rust/ide/projectView/RsTreeStructureProvider.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/7424.
changelog: Show crate roots first in the project view

UI: Show crate roots first in the project view

---

src/main/kotlin/org/rust/ide/hints/parameter/RsGenericParameterInfoHandler.kt
src/test/kotlin/org/rust/ide/hints/parameter/RsGenericParameterInfoHandlerTest.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/7566.
changelog: Render const generics in "Parameter Info"

HINT: Render const generics in "Parameter Info"

---

src/main/kotlin/org/rust/ide/intentions/JoinWildcardsIntention.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/intentionDescriptions/JoinWildcardsIntention/after.rs.template
src/main/resources/intentionDescriptions/JoinWildcardsIntention/before.rs.template
src/main/resources/intentionDescriptions/JoinWildcardsIntention/description.html
src/test/kotlin/org/rust/ide/intentions/JoinWildcardsIntentionTest.kt

Closes #6409
changelog: Add intention to replace redundant wildcards with a single `..`

INT: Add intention for replacing multiple `_` wildcards into one `..`

---

CONTRIBUTING.md

Practice says this approach doesn't work, unfortunately :(

DOC: remove a paragraph about the worklist from `CONTRIBUTING.md`

---

coverage/src/main/kotlin/org/rust/coverage/LcovCoverageReport.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7580
changelog: Fix overflow when parsing coverage report

RUN: Fix overflow when parsing coverage report

---

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt

Fixes https://youtrack.jetbrains.com/issue/CPP-25983
changelog: Don't try to move non-rust items in move refactoring

REF: Don't try to move non-rust items in move refactoring

---

src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/6500.
It only works when Built Tool Window is enabled.
changelog: Set Cargo environment variables when debug/profile

RUN: Set Cargo environment variables when debug/profile

---

coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt

changelog: Enable Code Coverage runner on non-nightly toolchains

RUN: Enable Code Coverage runner on non-nightly toolchains

---

src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt

changelog: Fix WSL support on 2021.2 platform

RUN: Fix WSL support on 212

---

src/211/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
src/212/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt
src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt
src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/7466.
changelog:  Introduce setting to navigate to the first error in the editor

RUN: Introduce setting to navigate to first error in editor

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: detect E0121 in struct

---

clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceProfilerProcess.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7727
However, further refactorings on the CLion side should be done to reuse as much code as possible and to avoid such problems in the future.
changelog: Fix DTrace profiler integration with CLion 2021.2

Fix DTrace profiler integration with CLion 2021.2

---

src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt
src/test/kotlin/org/rust/ide/actions/RsMoveLeftRightHandlerTest.kt

changelog: Support move left/right action for predicates in where clause

TYPE: Support move left/right action for predicates in where clause

---

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt

Fixes #4520
changelog: Use existing impl block if possible in "Extract function" refactoring

REF: Use existing impl block in "Extract function" refactoring

---

src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/7812
(This is a continuation of https://github.com/intellij-rust/intellij-rust/pull/7804, so the changelog should be taken from it).

FIX: visit all type parameters in extract utils

---

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt
src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt
src/main/kotlin/org/rust/lang/core/resolve2/util/GlobImportGraph.kt
src/main/kotlin/org/rust/lang/utils/Graph.kt
src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt

TODO: Support text search inside macro expansions
changelog: Support finding usages in child modules in unused import inspection

INSP: Support child modules in unused import inspection

---

src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7871.
changelog: Reset "Standard library" on "Toolchain location" change in Rust settings

UI: Reset "Standard library" on "Toolchain location" change in Rust settings

---

src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7873.
changelog: Fix check if rustup is available on WSL

RUN: Fix check if rustup is available on WSL

---

src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt

Fixes exception (introduced in #7818)
<details>
```
java.lang.IllegalStateException: Can't use resolve while building CrateDefMap
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$getOrUpdateIfNeeded$1.invoke(FacadeUpdateDefMap.kt:45)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$getOrUpdateIfNeeded$1.invoke(FacadeUpdateDefMap.kt:44)
at org.rust.stdext.ConcurrencyKt.withLockAndCheckingCancelled$lambda-0(Concurrency.kt:114)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.computeWithLockAndCheckingCanceled(ProgressIndicatorUtils.java:339)
at org.rust.stdext.ConcurrencyKt.withLockAndCheckingCancelled(Concurrency.kt:114)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt.getOrUpdateIfNeeded(FacadeUpdateDefMap.kt:44)
at …
```

RES: Fix exception when building DefMaps

---

.github/workflows/check.yml
.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml
.idea/runConfigurations/RunCLion.xml
.idea/runConfigurations/RunIDEA.xml
build.gradle.kts
gradle-213.properties
gradle.properties
grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
src/212/main/kotlin/org/rust/ide/refactoring/changeSignature/compatUtils.kt
src/213/main/kotlin/org/rust/ide/refactoring/changeSignature/compatUtils.kt
src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt
src/main/kotlin/org/rust/ide/formatter/Util.kt
src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt
src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
src/test/kotlin/org/rust/cargo/project/model/CargoProjectsServiceTest.kt
src/test/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoderTest.kt
src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt
src/test/kotlin/org/rust/ide/formatter/RsFormatterTestBase.kt
src/test/kotlin/org/rust/ide/formatter/RsTrailingCommaFormatProcessorTest.kt
src/test/kotlin/org/rust/ide/todo/RsTodoTest.kt
src/test/kotlin/org/rust/lang/core/lexer/LexerTestCaseBase.kt
src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
src/test/kotlin/org/rust/lang/core/parser/RsParsingTestCaseBase.kt
toml/src/test/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceTest.kt

changelog: support new 2021.3 platform EAPs

Support 2021.3 EAPs

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

Continuation of #7914 for methods auto-import.
Meta issue: #7558
Fixes #5654
Fixes #6399
changelog: Improve traits auto-import for methods

New auto-import for trait methods

---

gradle.properties

This reverts commit 211b437155970d605f4f7081f242cf5c96885eab.
bors r+

Revert ":arrow_up: patch version"

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

ANN: Provide lifetime name check

---

src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt

Introduce variable: place new variable in lambda block when target expression is in lambda without braces

---

src/main/kotlin/org/rust/ide/intentions/MergeIfsIntention.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/intentionDescriptions/MergeIfsIntention/after.rs.template
src/main/resources/intentionDescriptions/MergeIfsIntention/before.rs.template
src/main/resources/intentionDescriptions/MergeIfsIntention/description.html
src/test/kotlin/org/rust/ide/intentions/MergeIfsIntentionTest.kt

changelog: Add "Merge `if`s" intention

INT: Add "Merge `if`s" intention

---

src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt
src/test/kotlin/org/rust/ide/intentions/DemorgansLawIntentionTest.kt

Fixes #8016
Depends on #8013
changelog: Fix DeMorgan's law intention for multiple boolean operators

Fix choosing expression in DemorgansLawIntention

---

src/main/kotlin/org/rust/ide/intentions/DemorgansLawIntention.kt
src/test/kotlin/org/rust/ide/intentions/DemorgansLawIntentionTest.kt

Fixes #8014
changelog: Fix omitting parens in DeMorgan's law intention

INT: Fix omitting parens in DemorgansLawIntention

---

src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt

This PR avoids the usage of resolve inside EDT, based on [this](https://github.com/intellij-rust/intellij-rust/pull/7959#discussion_r744779768) comment.
changelog: Avoid using potentially long-running computation inside the UI thread when invoking the [`Introduce constant`](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractconst-refactoring) refactoring.

Do not use resolve in EDT in RsIntroduceConstantHandler

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

changelog: Add label name check
Fixes #8110

ANN: Add label name check

---

src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt

changelog: Support "Invert if condition" without else branch

INT: Support "Invert if condition" without else branch

---

scripts/update_nightly.py

Fixes emoji in such PRs (e.g. https://github.com/intellij-rust/intellij-rust/pull/7832) generated by `update_nightly.py` script

CI: Fix :arrow_up: emoji in commit and PR titles

---

src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
src/main/resources/META-INF/rust-core.xml

Fixes #7937
changelog: Fix exception when expanding macros in parallel and enable it by default

RES: Fix parallel macro expansion

---

src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt

Fixes #8037
changelog: Fix auto-import in `include!`-ed files

Fix auto-import in `include!`-ed files

---

src/main/kotlin/org/rust/ide/annotator/fixes/EncloseExprInBracesFix.kt
src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt
src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeArgumentList.kt
src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprEvaluator.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/inspectionDescriptions/RsWrongGenericArgumentsOrder.html
src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt

changelog: Detect [E0747](https://doc.rust-lang.org/error-index.html#E0747) error

INSP: Detect E0747 error

---

src/main/kotlin/org/rust/cargo/project/RsToolchainPathChoosingComboBox.kt
src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt
src/main/kotlin/org/rust/ide/refactoring/RsMemberSelectionPanel.kt
src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt
src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitAction.kt
src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt
src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/openapiext/ui.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/messages/RsBundle.properties
src/test/kotlin/org/rust/ide/refactoring/RsExtractTraitTest.kt

Part of #8326
changelog: Add `Extract trait` refactoring

REF: Add `Extract trait` refactoring

---

.github/dependabot.yml
native-helper/Cargo.lock
native-helper/Cargo.toml

... and enable Dependabot.
Previous - #8278

Update ra_ap_proc_macro_srv to 0.0.87

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt

Also, fixes path for `ExecutionException`.
CC @vlad20012

Replace `FutureResult` with `CompletableFuture` in `CargoBuild*`

---

src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt
src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt

Fixes #8171
changelog: Fix handling comments in `Invert if condition` intention

INT: Fix handling comments in `Invert if condition` intention

---

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt

Fix cargo features inference with renamed packages with hyphens

---

README.md

DOC: proper minimal supported version

---

src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt
src/main/kotlin/org/rust/lang/core/resolve2/DetachedDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt

changelog: 1. Fix resolve of [macros 2.0](https://rust-lang.github.io/rfcs/1584-macros.html) in doctests 2. Resolve and expand attribute proc macros in doctests

RES: Use new resolve inside doctests

---

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt

Relates to https://github.com/intellij-rust/intellij-rust/pull/8441.

ANN: Fix stub for const block expressions

---

clion/src/main/kotlin/org/rust/clion/profiler/RsProfilerRunner.kt
clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
clion/src/main/kotlin/org/rust/clion/profiler/legacy/RsProfilerRunnerLegacy.kt
clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/7857.
changelog: Enable profiler for WSL toolchains

RUN: Enable profiler for WSL 2 toolchains

---

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/main/kotlin/org/rust/lang/core/resolve2/HangingModData.kt
src/main/kotlin/org/rust/lang/core/resolve2/util/RsBlockStubBuilder.kt
src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveInsideFunctionsTest.kt

changelog: Basic support for resolving [macros 2.0](https://rust-lang.github.io/rfcs/1584-macros.html) in local modules

RES: Add basic support of local modules in new resolve

---

.github/workflows/check.yml
.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml
.idea/runConfigurations/RunCLion.xml
.idea/runConfigurations/RunIDEA.xml
build.gradle.kts
clion/src/213/main/kotlin/org/rust/clion/valgrind/compatUtils.kt
clion/src/221/main/kotlin/org/rust/clion/valgrind/compatUtils.kt
clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
gradle-221.properties
gradle.properties
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt
src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestOutputEventSplitter.kt
src/test/kotlin/org/rustPerformanceTests/RsCompletionPerfTest.kt
src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerfTest.kt
src/test/kotlin/org/rustPerformanceTests/RsParsingPerfTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileBuildDefMapTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileCargoRefreshTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileResolveTest.kt
src/test/kotlin/org/rustPerformanceTests/RsProfileTestBase.kt
src/test/kotlin/org/rustSlowTests/RsCompilerSourcesPerfTest.kt
src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/8351.
Known issues:
* Two build actions in IDEA with Native Debugging support plugin: https://youtrack.jetbrains.com/issue/KT-51141
* Exception during debugging in IDEA with enabled Kotlin plugin: https://youtrack.jetbrains.com/issue/KTIJ-20915
* Wrong indents in new project settings: https://github.com/intellij-rust/intellij-rust/issues/8508
* Pretty printer tests don't work with 2022.1 builds: https://github.com/intellij-rust/intellij-rust/issues/8482
* Build tests hang sometimes with 2022.1 builds: https://github.com/intellij-rust/intellij-rust/issues/8511
changelog: Provide support for 2022.1 EAPs

Provide support for 2022.1 EAPs

---

src/main/grammars/RustParser.bnf
src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt
src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFix.kt
src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt
src/main/kotlin/org/rust/ide/hints/parameter/RsGenericParameterInfoHandler.kt
src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt
src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt
src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt
src/main/kotlin/org/rust/ide/inspections/fixes/RemoveGenericArguments.kt
src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt
src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt
src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodCall.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMethodOrPath.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeArgumentList.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameterList.kt
src/test/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFixTest.kt
src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt

* `Create lifetime parameter`
* `Elide lifetimes`
* `Un-elide lifetimes`
changelog: Take into account type arguments/parameters ordering and const generics in some intentions/fixes

INT: Take into account type arguments/parameters ordering and const generics in some intentions/fixes

---

src/main/kotlin/org/rust/ide/inspections/RsWrongGenericParametersNumberInspection.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/inspectionDescriptions/RsWrongGenericParametersNumber.html
src/test/kotlin/org/rust/ide/inspections/RsWrongGenericParametersNumberInspectionTest.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/8312
changelog: Detect [E0049](https://doc.rust-lang.org/error-index.html#E0049) (Implementation has wrong number of type or const parameters)

ANN: Detect E0049 (Implementation has wrong number of type or const parameters)

---

src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt

T: enable some disabled tests

---

src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt

ANN: Fix incorrectly providing `Add unsafe to function` in the main function

---

src/main/kotlin/org/rust/ide/statistics/RsProjectUsagesCollector.kt

Note, the statistics are collected only if you [explicitly allow](https://www.jetbrains.com/help/idea/settings-usage-statistics.html) it

FUS: collect info about workspace and dependency editions

---

src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt
src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt
src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt
src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractSuperTraitTest.kt
src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitBaseTest.kt
src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitFromImplTest.kt

Meta issue: #8326
Please see #8132 for general overview of the refactoring
changelog: Support `Extract trait` refactoring for traits

REF: Support Extract trait refactoring for traits

---

src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt
src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteToolchainTest.kt

Improvement of https://github.com/intellij-rust/intellij-rust/pull/7816.
(Changelog is omitted if this gets into the same release as #7816).

IDE: add derive to structs generated from JSON if `serde` is in dependencies

---

scripts/make_next_milestone.py

CI: update maintainers list

---

src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt

Allow files generated by the `build.rs` buildscripts up to 8 megabytes in size. Previously is was necessary to adjust the limit manually using `idea.max.intellisense.filesize` property.
I've tested this with `chrono-tz` crate that generates large `timezones.rs` file in IDEA with default `-Xmx768M`.
Cargo.toml:
```toml
[dependencies]
chrono-tz = "0.6.1"
```
main.rs:
```rust
use chrono_tz::Tz;
fn main() {
let a = Tz::US__Pacific;
}
```
| - | - |
| ![image](https://user-images.githubusercontent.com/3221931/160839601-1398f744-ab38-4ab8-bb68-e0f421ed927e.png) | ![image](https://user-images.githubusercontent.com/3221931/160839716-745f95ca-faf4-4aa1-b62f-25ac6962cda1.png) |
It works file until I open the large file. Then I see "Low memory" notification and the IDE starts …

Allow files generated by the buildscripts up to 8Mb in size

---

clion/src/main/kotlin/org/rust/clion/profiler/perf/RsPerfConfigurationExtension.kt
clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt
clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindRunner.kt
clion/src/main/kotlin/org/rust/clion/valgrind/legacy/RsValgrindRunnerLegacy.kt
src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/7975.
https://www.jetbrains.com/help/clion/memory-profiling-with-valgrind.html#valgrind-wsl
changelog: Enable [Valgrind on WSL](https://www.jetbrains.com/help/clion/memory-profiling-with-valgrind.html#valgrind-wsl) toolchains

RUN: Enable Valgrind for WSL toolchains

---

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/HangingModData.kt
src/test/kotlin/org/rust/lang/core/resolve/RsResolveInsideFunctionsTest.kt

Fixes #8682
changelog: Fix resolving variants of local enum brought into scope using glob import

RES: Fix glob imports from local enums

---

src/main/kotlin/org/rust/lang/core/resolve2/ResolveCommonThreadPool.kt

Fixes NoClassDefFoundError.
The bug was introduced in #8746

Don't use ThreadTracker in production code

---

CONTRIBUTING.md

DOC: update info about project modules in CONTRIBUTING.md

---

src/main/kotlin/org/rust/lang/core/types/infer/Expectation.kt

Drop redundant license comment

---

.github/workflows/check.yml
.github/workflows/rust-nightly.yml
.github/workflows/rust-release.yml
clion/src/222/main/kotlin/org/rust/clion/statistics/CargoProjectModelTypeProvider.kt
clion/src/222/main/kotlin/org/rust/clion/valgrind/compatUtils.kt
clion/src/222/main/resources/META-INF/platform-clion-only.xml
debugger/src/222/main/resources/META-INF/platform-native-debug-only.xml
gradle-222.properties
gradle.properties
src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt

changelog: Provide builds for 2022.2 major release

Initial support for 2022.2 major release

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

https://user-images.githubusercontent.com/2539310/169854821-560af889-5250-438a-8093-cbf696a55eda.mov
Related to #886
Fixes #8616
changelog: Annotate using `feature` attribute in non-nightly release channels ([E0554](https://doc.rust-lang.org/error-index.html#E0554) error)

ANN: annotate using `feature` attribute in non-nightly channels (E0554)

---

prettyPrinters/gdb_providers.py
prettyPrinters/lldb_providers.py

Fixes #8773.
The new `Unique` layout was introduced in rustc 1.62:
* Rust 1.33: `struct Unique<T: ?Sized> { pointer: *const T, ... }`
* Rust 1.62: `struct Unique<T: ?Sized> { pointer: NonNull<T>, ... }`
https://github.com/rust-lang/rust/commit/2a91eeac1a2d27dd3de1bf55515d765da20fd86f
changelog:  Update LLDB/GDB pretty-printers to render `Vec` in Rust 1.62 or higher

Update pretty-printers according to the new `Unique` layout

---

src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt
src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt
src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt

Fixes the bug that was introduced in https://github.com/intellij-rust/intellij-rust/pull/8796.
Fixes https://github.com/intellij-rust/intellij-rust/issues/8827.
changelog: Fix external linter on the fly on the nightly version of the plugin

RUN: Don't emulate terminal in some cases (build tool window, external linters, etc.)

---

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/utils/snapshot/Snapshot.kt

PERF: slightly speed up `canCombineTypes`

---

src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/8871.
Relates to https://github.com/intellij-rust/intellij-rust/issues/8844.
changelog: Get rid of toolchain validation in local inspections. This should improve performance under WSL 2

ANN: Get rid of toolchain validation in local inspections

---

.idea/runConfigurations/RunCLion.xml
.idea/runConfigurations/RunIDEA.xml

Adjust `RunIDEA` and `RunCLion` run configuration logs to new supported platforms

---

src/222/main/resources-stable/META-INF/platform-experiments.xml

CARGO: new project model import should be disabled in stable for now

---

src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt
src/main/kotlin/org/rust/lang/core/dfa/MemoryCategorization.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsIndexExpr.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsIndexExprReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/Extensions.kt
src/main/kotlin/org/rust/lang/core/types/infer/Autoderef.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
src/test/kotlin/org/rust/lang/core/dfa/RsMemoryCategorizationTest.kt
src/test/kotlin/org/rust/lang/core/type/RsAdjustmentTest.kt

Resurrected #4899. 
This shouldn't affect our users anyhow. Will be used by next PRs
changelog: implement type adjustments in the type system

TY: implement type adjustments

---

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt

Fixes a performance regression introduced in #8828
changelog: slightly speed up type inference

PERF: optimize `coerceUnsized` for equivalent types

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsBlock.kt

PERF: cache `expandedStmtsAndTailExpr`

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

PERF: cache `MacroExpansionManager.getExpandedFrom`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryQualificationsInspection.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

changelog: Detect [E0742](https://doc.rust-lang.org/error-index.html#E0742) compiler error

ANN: Check E0742 (visibilities can only be restricted to ancestor mods)

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

changelog: Detect [E0430](https://doc.rust-lang.org/error-index.html#E0430) compiler error

ANN: Detect E0430 error (multiple self imports in use group)

---

build.gradle.kts

The tests were temporarily disabled due to the problem with certain 2022.2 EAP builds.
Fixes #8482

T: Enable pretty-printers tests on 2022.2

---

toml/src/main/kotlin/org/rust/toml/CargoFeatureLineMarkerProvider.kt

Fixed #9066 
ref: https://youtrack.jetbrains.com/issue/IDEA-266993
changelog: Fixes exception on opening `Configure features` popup in Cargo.toml

IDE: Fix feature popup missing component for `DataContext`

---

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionStubsProvider.kt
src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt

Fix issue #9088 `java.io.FileNotFoundException`

---

gradle.properties

since we decided to postpone 176 release for a week
bors r+

Revert patch version increment

---

src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt

Fixes #8572
changelog: Fix auto-import when completing items in trait impl

COMP: Fix auto-import when completing impl trait items

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

Fixes #7856
changelog: Fix completion of qualified [macros 2.0](https://github.com/rust-lang/rfcs/blob/master/text/1584-macros.md)

COMP: Fix completion of qualified macros 2.0

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt

* Added out-of-scope completion for unqualified macro calls
* Support for 3-segments and longer macro calls
changelog: Improve top-level completion of macro calls

COMP: Improve top-level completion of macro calls

---

src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt
src/test/kotlin/org/rust/ide/inspections/lints/RsDoubleMustUseInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyUsingTryFromTraitFixTest.kt
src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
src/test/kotlin/org/rust/ide/refactoring/RsIntroduceParameterTest.kt
src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
src/test/kotlin/org/rust/lang/core/type/RsNumericLiteralTypeInferenceTest.kt
src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt

I extracted some tests from #8866

T: add more tests with normalizable associated types

---

.github/actions/preparations-for-updates/action.yml
.github/workflows/auto-updates.yml
scripts/update_compiler_features.py
scripts/update_nightly.py
scripts/updater.py

These changes:
- add `update-compiler-features` job to `auto-updates` workflow to automatically update compiler features. Previously, you should do it manually
- improve infrastructure (`preparations-for-updates` action, `Updater` class in `scripts`) to simplify future addition of similar auto update jobs/workflows

CI: automatically update compiler features

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/MakeAsyncFix.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunctionOrLambda.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/MakeAsyncFixTest.kt

changelog: Detect [E0728](https://doc.rust-lang.org/error-index.html#E0728) compiler error

ANN: Detect E0728 error (`await` outside `async` function)

---

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
src/main/kotlin/org/rust/lang/core/resolve2/HangingModData.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt

Now new resolve will be used for TMP mod (used e.g. in auto-import to check if path is resolved) and for cfg-disabled mod shadowed by cfg-enabled mod with same name. This should not affect users.
I will refactor `RsModInfoBase` and remove some old resolve code in next PR

RES: Use new resolve for remaining cases

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/fixes/AddAsyncAttributeFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsCodeFragmentFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddAsyncRecursionAttributeFixTest.kt

changelog: Detect [E0733](https://doc.rust-lang.org/error-index.html#E0733) compiler error

ANN: Detect E0733 error (recursive async function)

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt

Remove `findPreludeUsingOldResolve`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt

Simplify `RsCachedItems.imports`

---

src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt

T: add one more test for stack overflow in name resolution

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt

PERF: Speed up type parameters extraction in some places

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt

Related: https://github.com/intellij-rust/intellij-rust/pull/9290

Get rid of `ScopeEvent.STAR_IMPORTS`

---

src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt

For some reasons, requests performed by `HttpRequests` don't follow redirects. As a result, `Share in Playground` action didn't work previously.
Now `HttpClient` from JDK 11 is used to solve this issue
Fixes #9294
changelog: Fix `Tools | Rust | Share in Playgroud` action

ACT: fix `Share in Playground` action

---

.github/workflows/to-test-board.yml
scripts/add_to_board.py

This thing will automatically add all PRs with `fix` and `feature` labels on our to-test-board https://github.com/intellij-rust/intellij-rust/projects/1
Inspired by cases where developers forgot to add PR to the board, and as a result some new functionality was not checked by @intellij-rust/qa team.
If verification from the QA is definitely not needed, feel free to remove the card from the board :)

Add to-test-board updater

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt

Related: #9259, #9268
changelog: Complete custom derive proc macros

COMP: Complete derive proc macros

---

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt
src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt
src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt

Fixes #9230
changelog: Fix adding imports for default values in change signature refactoring

REF: Fix adding import for default value in change signature refactoring

---

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt

PERF: use `ModData` instead of `RsMod` in `VisibilityFilter`

---

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt

Reverts #9332
See #9486 for details

Revert "Suggest importing modules in completion"

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/pull/5651#issuecomment-1256815094
changelog: Fix false-positive [E0117](https://doc.rust-lang.org/error-index.html#E0117) in some cases

ANN: Fix handling auto-traits when checking orphan rules

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPathCachingRootTest.kt

Add additional unit tests for #9211

T: add RsPathCachingRootTest

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt

Fixes https://github.com/intellij-rust/intellij-rust/pull/9153#pullrequestreview-1110874247

Fix `AutoImportFix.startInWriteAction`

---

src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt

Related: #7134
changelog: Improve error message for [`E0407`](https://doc.rust-lang.org/error-index.html#E0407) error

INSP: Improve error message for E0407 (unknown member in trait impl)

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

MACRO: fix proc macro expansion PSI cache invalidation

---

src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
src/main/kotlin/org/rust/lang/core/crate/impl/FakeCrate.kt
src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt

Fixes #9405
changelog: Fix `Attach file to module` quick fix

INT: Fix "Attach file to module"

---

gradle.properties

Increase attempts to connect to repo and connection timeout

GRD: try to fix connection issues to Maven repo

---

.github/workflows/check.yml

CI: Update stable rust version

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
src/test/kotlin/org/rustSlowTests/RsGcSoftlyReachableObjectsCacheTest.kt

Fix issue #9468 random false-positive `Variable is never used`

---

src/main/kotlin/org/rust/lang/core/resolve2/util/RsBlockStubBuilder.kt
src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt

changelog: Fix expansion of attribute and derive procedural macros inside functions

MACRO: Fix expansion of attr and derive proc macros inside functions

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinitionBase.kt
src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
src/test/kotlin/org/rust/lang/core/completion/RsMacroBracketCompletionTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/pull/9313#discussion_r988070775
Related: #4812
changelog: Suggest the proper type of braces while a procedural macro call completion

COMP: Guess proper type of brackets while proc macro call completion

---

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt

Closes https://github.com/intellij-rust/intellij-rust/issues/9463.

RUN: Fix parsing of executable path in Test Tool Window

---

src/main/kotlin/org/rust/ide/navigationToolbar/RsNavBarModelExtension.kt
src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt

Fixes #9460
Please note that nav bar is currently disabled (see #9458)

Fix IndexNotReadyException in nav bar

---

src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/9061.
Fixes https://github.com/intellij-rust/intellij-rust/issues/9018.
changelog: Don't allow to use Run targets alongside with WSL toolchain

RUN: Don't allow to use Run targets alongside with WSL toolchain

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt

The goal of this PR is to refactor `QualifiedNamedItem` class, which was used previously in the old auto-import
---
This is internal change which should not affect users. It relates to the resolving links in (rendered) documentation in format:
```rust
/// [label]
/// [label]: mod1/mod2/struct.Foo.html
```

QDOC: Refactor resolve of links in documentation

---

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt

The bug has been introduced in #9469
If you invoke completion in a macro call several times in different places without typing in the macro call, it was possible that completion may stop working in the macro
changelog: Fix completion in a function-like macro call body

COMP: fix completion in function-like macros

---

src/main/kotlin/org/rust/ide/inspections/import/ui.kt
src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt
src/main/kotlin/org/rust/ide/utils/import/ImportCandidate.kt
src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt

Merge `QualifiedNamedItem2` into `ImportCandidate`

---

src/main/kotlin/org/rust/ide/utils/import/ImportCandidate.kt
src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
src/main/kotlin/org/rust/ide/utils/import/importUtils.kt

Refactor `ExternCrateImportInfo`

---

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt

Fixes #9743
changelog: Restore option `Fix all 'Unresolved reference' problems in file` which adds unambiguous imports. Note that there is also an option `Add unambiguous imports on the fly` which can be turned on in `Settings | Editor | General | Auto Import`
Support for ambiguous imports may be added in future PR

Restore option to add all unambiguous imports in file

---

src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt

Fixes #9748, fixes #9730 issues with `FnOnce` trait on nightly Rust.
changelog: Fix type inference in closures on nightly Rust

Fix `RsLangItemIndex`: pick only cfg-enabled lang items

---

src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt

Show [coerced](https://doc.rust-lang.org/reference/type-coercions.html) type in `type info` (`ctrl`+`shift`+`P`)
changelog: Show [coerced](https://doc.rust-lang.org/reference/type-coercions.html) type in `type info` (`ctrl`+`shift`+`P`)

 ACT: show coerced type in "type info" (ctrl+shift+P)

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt
src/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt

Changes in procedural macros should be considered as changes in the project model because the model contains paths to compiled proc macro libs, and when sources of these libs are changed, the plugin needs to recompile proc macro crates (project model reloading does it) to properly expand proc macros with new changes.
These changes add tracking for changes in crate roots of proc macro libs. Ideally, we need to track all changes including child modules, but it requires access to name resolution API which is undesirable to use here
changelog: Notify users about changes in crate roots of procedural macro libraries to reload project model. Otherwise, the plugin won't be able to properly expand procedural macro calls

CARGO: track changes in crate roots of procedural macro libraries

---

src/main/kotlin/org/rust/lang/core/completion/Utils.kt

COMP&MACRO: fix completion inside local macro calls in 2022.3

---

grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt

Fix NPE in RsGrammarCheckingStrategy on 2022.3

---

src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt

Fixes #8060
Fixes #8849
Fixes #9415
Add type hints inside attribute procedural macros:
changelog: Show type hints inside attribute procedural macros

HINT: Show type hints inside attribute procedural macros

---

README.md

DOC: update link for stable build status

---

scripts/update_compiler_features.py

CI: update assignee for PR with compiler features

---

README.md

Hi!
I've added "Run targets" to the features chart in readme.txt. 
changelog: Added info about Run targets to plugin description on GitHub.

Added info about Run targets to README.md (#6836)

---

build.gradle.kts

GRD: update link

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt
src/test/kotlin/org/rust/RustProjectDescriptors.kt
src/test/kotlin/org/rust/lang/core/resolve/ref/RsLiteralWebReferenceProviderTest.kt

Closed #9932
changelog: Support special attr to open GitHub issue page via web ref.

IDE: Support for Rust GitHub attr to generate web reference

---

.github/workflows/auto-updates.yml
build.gradle.kts
scripts/update_lints.py

Pull requests with updating the lists will be created automatically.
Example of work: https://github.com/neonaot/intellij-rust/pull/77/files

CI: add lints autoupdater

---

src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt

Fixes: https://github.com/intellij-rust/intellij-rust/issues/9970
changelog: Fixes incorrect macro expansions when block expression is involved

Add BLOCK_EXPR to USELESS_PARENS_EXPR

---

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt
src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt

Fixes #9634
changelog: Suggest in completion methods only from accessible traits

COMP: Suggest only methods from accessible traits

---

src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt

Continuation of: https://github.com/intellij-rust/intellij-rust/pull/9971
changelog: mention together with #9971

Add tests for USELESS_PARENS

---

.github/actions/preparations-for-updates/action.yml
.github/workflows/auto-updates.yml
scripts/update_stable.py

Written _very heavily based_ on the updater of the night version.

CI: add stable rust version updater

---

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
src/test/kotlin/org/rust/lang/core/resolve/RsPathCachingRootTest.kt

Continuation of #9334.
Also, I've improved `RsPathCachingRootTest` (from #9499) to also test stubbed PSI (hence now it tests `getRootCachingElementStub()` and `collectNestedPathsFromRootStub()`)

PERF: speed up `collectNestedPathsFromRoot()` using stubs

---

gradle.properties

:arrow_up: patch version

---

src/main/kotlin/org/rust/ide/security/RsTrustStateListener.kt

Fixes #10028
changelog: Part of #10002

Avoid deadlock during new project creation on 2023.1

---

build.gradle.kts

T: Fix pretty-printers tests on 2023.1

---

build.gradle.kts

changelog: Allow using new language features from Kotlin 1.8

GRD: increase kotlin language level to 1.8

---

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsMainWithGenericsTest.kt
src/test/kotlin/org/rust/ide/annotator/RsMultipleRelaxedBoundsTest.kt
src/test/kotlin/org/rust/ide/annotator/RsUnsafeInherentImplTest.kt

changelog:
* Add support for E0131
Error code reference: https://doc.rust-lang.org/error_codes/E0131.html
There's a feature that might be connected to this error code: https://github.com/rust-lang/rust/issues/29633
* Add support for E0197
Error code reference: https://doc.rust-lang.org/error_codes/E0197.html
* Add support for E0203
Error code reference: https://doc.rust-lang.org/error_codes/E0203.html
Compiler implementation: https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_analysis/src/astconv/mod.rs#L877

ANN: Add support for E0131, E0197, E0203

---

debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSteppingSettingsConfigurableUi.kt

UI: use kotlin UI DSL 2 for stepping settings

---

gradle-231.properties

GRD: bump sinceBuild for 231

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsMembers.kt
src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt

Fixes #9593
```rust
impl Foo {
#[foobar_macro]
pub fn foo(&self) {}
}
```
changelog: Take into account attribute procedural macros applied for an impl or trait member. Note that attribute procedural macros expansion is disabled by default

RES: take into account attr macros for impl/trait members

---

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsBreakExprInNonLoopTest.kt

changelog:
* Add support for E0571
Error code reference: https://doc.rust-lang.org/error_codes/E0571.html
Compiler implementation: https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/loops.rs#L132

ANN: Add support for E0571

---

gradle-231.properties
src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt

GRD: update IDE dependencies for 231

---

src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt
src/test/kotlin/org/rust/cargo/util/CargoArgsParserTest.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/8472.
changelog:  Fix parsing command line arguments

RUN: Fix parsing command line arguments

---

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt

Previously it returned null in the case of failed macro expansion as well. This change is needed for future use, but at the moment it shouldn't affect anything
I extracted this from #9834 because I need this for intention actions is macros as well.

Make `findExpansionElements()` return null only if outside a macro call

---

src/223/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
src/231/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
src/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt
src/main/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionContext.kt
src/main/kotlin/org/rust/ide/statistics/RsCodeVisionUsageCollector.kt
src/main/resources/META-INF/rust-core.xml
src/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt

Note, the statistics are collected only if you [explicitly allow](https://www.jetbrains.com/help/idea/settings-usage-statistics.html) it

FUS: Collect Code Vision data

---

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsAtLeastOneTraitForObjectTypeTest.kt

changelog: Add support for [E0224](https://doc.rust-lang.org/error_codes/E0224.html) error

ANN: Add support for E0224

---

src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/7665.
Fixes https://github.com/intellij-rust/intellij-rust/issues/9385.
changelog: Fix "Before launch" configurations for Cargo Command configurations

RUN: Fix "Before launch" configurations for Cargo Command configurations

---

.github/workflows/regressions-template.yml

Thanks to @ortem for investigating
Solution from https://github.com/actions/runner-images/issues/675#issuecomment-1461847624

CI: fix failing of regression tests

---

src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt
src/test/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProviderTest.kt

Related: #5276
changelog: Show hints for chained method calls inside attribute procedural macros

HINT: Add hints for chained method calls in attribute procedural macros

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsImplCopyRestrictionsTest.kt

changelog: Add support for [E0206](https://doc.rust-lang.org/error_codes/E0206.html)

ANN: Add support for E0206

---

.github/workflows/auto-updates.yml
.github/workflows/check.yml
scripts/update_repl.py

By request of @vlad20012 
PRs with version updates will be assigned to @dima74
Example of work:

CI: add repl updater

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt
src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsImplForDynTraitTest.kt

changelog: Add support for [E0785](https://doc.rust-lang.org/error_codes/E0785.html)

ANN: Add support for E0785

---

src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt
src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt

Fixes #10264
changelog: Don't show "Conditionally disabled code" in the `Problems` view

ANN: Don't show "Conditionally disabled code" in the `Problems` view

---

src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateEnumVariantIntention.kt
src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt
src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/intentionDescriptions/CreateEnumVariantIntention/after.rs.template
src/main/resources/intentionDescriptions/CreateEnumVariantIntention/before.rs.template
src/main/resources/intentionDescriptions/CreateEnumVariantIntention/description.html
src/test/kotlin/org/rust/ide/intentions/CreateEnumVariantIntentionTest.kt
src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt

Related: #6837
Related: #7137
changelog: Add intention to create an enum variant from usage

INT: Add intention to create an enum variant from usage

---

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt

Fixes #10275
changelog: Fix handling paths to associated constants in `Implement members` intention

INT: Fix handling associated types in `Implement members` intention

---

src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt

RES: Fix "Outdated stub in index" in new resolve

---

src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt

"Special" macro which syntax is hardcoded in our parser. For example, `vec![]`. We can skip their expansion since the plugin knows their syntax and semantic value without expansion

PERF: don't expand special macros in `RsLivenessInspection`

---

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
src/test/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionTest2.kt

Fixes #10333
changelog: Fix handling async function in `Inline function` refactoring

REF: Fix inlining async function

---

src/test/kotlin/org/rust/RsTestBase.kt
src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt

<details>
<summary>Test failure stacktrace example</summary>
```
org.rust.ide.inspections.RsWrongAssocTypeArgumentsInspectionTest > test fix E0220 redundant type remove comma after FAILED
com.intellij.testFramework.TestLoggerFactory$TestLoggerAssertionError: Already disposed: MessageBus(owner=Project(name=impl_argument, containerState=disposed temporarily, componentStore=C:\Users\runneradmin\AppData\Local\Temp\unitTest_impl_argument_2OPyThBk5ruDelvbb72QPkBSgdj\light_temp_2OPyTfdEstZMqqeUUWygD5pxxDa.ipr) (disposed), disposeState= 0)
at com.intellij.testFramework.TestLoggerFactory$TestLogger.error(TestLoggerFactory.java:400)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
at com.intellij.util.messages.impl.MessageBusImpl.checkNotDisposed$intellij_platform_core(MessageBusImpl …
```

T: Fix flaky tests caused by VcsInitialization

---

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
src/main/kotlin/org/rust/ide/ssr/RsStructuralSearchProfile.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/messages/RsBundle.properties
src/test/kotlin/org/rust/ide/ssr/RsSSRTestBase.kt

Following discussions in #6675, this PR makes it clear that SSR is a work in progress.
changelog: Added an experimental feature to enable Rust SSR, added errors in the SSR dialog for unsupported templates.

SSR: Experimental feature warnings

---

src/main/kotlin/org/rust/ide/projectView/RsTreeStructureProvider.kt
src/main/resources/META-INF/rust-core.xml

This reverts commit 7e062b2cbcb400d2d7710cba941362db9eec0c8a.
bors r+

Revert "UI: Alphabetical sort for all files in project view"

---

coverage/src/main/kotlin/org/rust/coverage/Grcov.kt
coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt
src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
src/main/resources-nightly/META-INF/experiments.xml
src/main/resources-stable/META-INF/experiments.xml

changelog: Add an experimental option to use source-based coverage
Issues: https://github.com/mozilla/grcov/issues/729

RUN: Add an experimental option to use source-based coverage

---

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/8753.
changelog: Fix running build if Cargo project in a subdirectory

RUN: Fix running build if Cargo project in a subdirectory

---

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt

Previously, if a commit hash of previous crate index scanning was missing in current crate git index, the plugin might throw `MissingObjectException` exception which prevented the plugin from building crate index. Unfortunately, such cases are possible. For example, git crate index is squashed to reduce its history from time to time. As a result, some commits disappear after such updates
Now, the plugin properly processes such cases and just rebuilds crates index from scratch
changelog: Properly build local crate index to provide completion of crate names and version in `Cargo.toml` after collapsing cargo git crate index into one commit

CARGO: don't fail on unknown crate index commit hash

---

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt

When using a package such as wasm-pack, you can install it like this:
```bash
cargo install --path ~/dev/wasm-pack
```
However, this fails to see that it's installed, as it returns the full path in the version string:
```
0.10.3 (/home/josh/dev/wasm-pack)
```
So, this is a workaround to remove everything before the (, then trim the string, as there will still be a space.
changelog: Allow cargo packages installed via `cargo install --path`

Add support for binary crates installed manually

---

src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt

Fixes #10391
changelog: merge with #10359

Fix #10391 Wrong message for attribute error

---

src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt
src/main/resources/META-INF/rust-core.xml

changelog: Collect project settings statistics

Collect project settings statistics

---

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsAsyncNonMoveClosureWithParametersTest.kt

changelog: Add support for E0708 error

ANN: Add support for E0708 error

---

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
src/main/kotlin/org/rust/ide/module/RsModuleBuilder.kt
src/main/kotlin/org/rust/ide/newProject/RsNewProjectWizard.kt
src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt
src/main/kotlin/org/rust/ide/newProject/Utils.kt
src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
src/main/resources/META-INF/rust-core.xml

Closes https://github.com/intellij-rust/intellij-rust/issues/8585.
changelog: Adjust new Rust project generator to new project wizard in IDEA

UI: Adjust new Rust project generator to new project wizard in IDEA

---

src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt

This is a minor internal refactoring.

Extract the Future output type inference into a separate function

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/fixes/ConvertMalformedCfgNotPatternToCfgAllPatternFix.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

changelog: Add support for E0536 error

ANN: Add support for E0536 error

---

src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt

Fixes #10420 ANN: Use RsAnnotationHolder instead of AnnotationHolder in RsAttrErrorAnnotator

---

src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt

changelog: Add support for E0777 error

ANN: Add support for E0777 error

---

src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt

This is a follow-up for #10393

Collect project settings statistics: remove `auto_update` and `offline`

---

src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt
src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt

ANN: fix false-positive `malformed input for #![feature()]`

---

src/test/kotlin/org/rust/cargo/project/RsExternalLinterProjectSettingsServiceTest.kt
src/test/kotlin/org/rust/cargo/project/RsProjectSettingsServiceTestBase.kt
src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
src/test/kotlin/org/rust/cargo/project/RustfmtProjectSettingsServiceTest.kt

- check actual state after loading
- don't pass service class in constructor and use reified generic instead

T: improve `RsProjectSettingsServiceTestBase`

---

src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
src/main/kotlin/org/rust/ide/fixes/ConvertToUnsuffixedIntegerFix.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/kotlin/org/rust/stdext/Utils.kt
src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt

changelog:
-  Add support for E0589 error
- Add support for E0693 error

ANN: Add support for E0589 and E0693 errors

---

src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt

Continuation of https://github.com/intellij-rust/intellij-rust/pull/10432.

Collect project settings statistics: add `offline`

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/main/kotlin/org/rust/lang/core/resolve/ref/RsLabelReferenceImpl.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt

Highlight unresolved labels as E0767 if labels beyond label barriers exists

---

src/main/kotlin/org/rust/ide/fixes/RemoveCastFix.kt
src/main/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspection.kt
src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/inspectionDescriptions/RsUnnecessaryCast.html
src/test/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspectionTest.kt

changelog: Add `unnecessary cast` inspection

INSP: Implement `unnecessary cast` inspection

---

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt

Fixes #10512
IntelliJ Rust can't run Rust tests anymore on Rust 1.70-beta (which will be released as 1.70 stable this week) because of https://github.com/rust-lang/rust/pull/109044 (Stable Rust test framework does not support `-Z unstable-options --format json` options anymore)
I managed only to disable the test tool window if a user has a toolchain version above 1.70-beta. So the user will see just a raw terminal instead of a test tree:
changelog: Fix running tests on Rust 1.70

Disable test tool window on toolchain version >= 1.70-beta

---

src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt
src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Analysis.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/BorrowSet.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Direction.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/GenKillAnalysis.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/ResultsVisitor.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/framework/Utils.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/impls/Borrows.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/impls/MaybeUninitializedPlaces.kt
src/main/kotlin/org/rust/lang/core/mir/dataflow/move/MovePaths.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirAbstractDomain.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirBorrowKind.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocal.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocalInfo.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirLocation.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirPlace.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirProjectionElem.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirSpan.kt
src/main/kotlin/org/rust/lang/core/mir/schemas/MirVisitor.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/lang/core/mir/MirPrettyPrinter.kt
src/test/kotlin/org/rust/lang/core/mir/dataflow/impls/BorrowsTest.kt

changelog: Initial support for [E0505](https://doc.rust-lang.org/error_codes/E0505.html) using MIR framework

MIR: Initial support for E0505 using MIR framework

---

src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
src/main/kotlin/org/rust/ide/actions/RustfmtCheckingFactory.kt
src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt
src/main/kotlin/org/rust/ide/settings/RsVcsConfiguration.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/messages/RsBundle.properties

changelog: Make `Run rustfmt` available as pre-commit action

FMT: Make `Run rustfmt` available as pre-commit action

---

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/completion/RsLookupElement.kt
src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionFromUnresolvedImportTest.kt

changelog: Provide unresolved imported items as completion items

COMP: Provide unresolved imported items as completion items

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/main/kotlin/org/rust/ide/fixes/ReplaceBoxSyntaxFix.kt
src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorWithToolchainOverrideTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceBoxSyntaxFixTest.kt

Closed https://github.com/intellij-rust/intellij-rust/issues/10276.
changelog: Deprecate `box` syntax

ANN: Unsupport `box` syntax

---

src/main/kotlin/org/rust/lang/core/macros/proc/ProMacroExpanderVersion.kt
src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
src/main/kotlin/org/rust/lang/core/macros/tt/FlatTree.kt
src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonTest.kt
src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt

Fixes #10566, fixes #10573
changelog: Fix proc macro expansion with nightly Rust toolchain

Support proc macro expander version 2

---

src/main/kotlin/org/rust/ide/utils/PsiInsertionPlace.kt
src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt
src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt

changelog: This fixes a lot of `Unresolved Reference` false-positives in `ruffle` project

Fix proc macro hygiene

---

gradle-232.properties
src/231/main/kotlin/org/rust/ide/navigation/compatUtils.kt
src/232/main/kotlin/org/rust/ide/navigation/compatUtils.kt
src/main/kotlin/org/rust/ide/inspections/import/ui.kt
src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt
src/main/kotlin/org/rust/ide/refactoring/introduceParameter/ui.kt

GRD: update 2023.2 IDE and plugin dependencies

---

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt
src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/ReplaceWithStdMemDropFixTest.kt

changelog: Detect E0061 for impl trait calls

Detect E0061 for impl trait calls. Fixes #5681

---

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt

This fixes the "Failed to get project sysroot" error when opening a project with `rust-toolchain.toml` file the first time and the toolchain is not installed
changelog: Fix `Failed to get project sysroot` error when opening a project with `rust-toolchain.toml` file the first time and the toolchain is not installed

Remove timeout and add progress when fetching rustc version 

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt

changelog: Add `as` keyword completion

COMP: Add `as` keyword completion

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt
toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
toml/src/main/kotlin/org/rust/toml/completion/CratesIoCargoTomlDependencyCompletionProviders.kt
toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviders.kt
toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependenciesCompletionTest.kt
toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependencyKeysCompletionProviderTest.kt
toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlCompletionTestBase.kt
toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt

changelog: Suggest keys inside TOML dependency

COMP: Suggest keys inside TOML dependency

---

src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsLiteralSuffixCompletionProviderTest.kt

changelog:  Add completion for literal suffixes

COMP: Add completion for literal suffix

---

clion/src/main/kotlin/org/rust/clion/debugger/RsCLionDebuggerDriverConfigurationProvider.kt
debugger/src/main/kotlin/org/rust/debugger/RsDebuggerDriverConfigurationProvider.kt
debugger/src/main/kotlin/org/rust/debugger/RsDefaultDebuggerDriverConfigurationProvider.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunParameters.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt
debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
src/main/kotlin/org/rust/cargo/runconfig/RsProcessHandler.kt

Fixes https://github.com/intellij-rust/intellij-rust/issues/9778.
Relates to https://github.com/intellij-rust/intellij-rust/issues/5070.
changelog: Support `Emulate terminal in output console` for Debug runner on 2023.1

RUN: Support `Emulate terminal in output console` for Debug runner

---

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt
src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt

changelog: Show the value of the constant in the completion list

COMP: Show the value of the constant in the completion list

---

src/main/kotlin/org/rust/ide/fixes/AddSelfFix.kt
src/main/kotlin/org/rust/ide/fixes/RemoveSelfFix.kt
src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt
src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddSelfTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/AddSelfToFunctionDeclarationTest.kt
src/test/kotlin/org/rust/ide/annotator/fixes/RemoveSelfFixTest.kt

changelog: Add quick fix for [E0185](https://doc.rust-lang.org/error_codes/E0185.html) and [E0186](https://doc.rust-lang.org/error_codes/E0186.html)

INT: Add quick fix for E0185 and E0186

---

src/main/kotlin/org/rust/ide/inspections/lints/RsPathStatementsInspection.kt
src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt
src/main/kotlin/org/rust/lang/core/types/infer/NeedsDrop.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/messages/RsBundle.properties
src/test/kotlin/org/rust/ide/inspections/lints/RsPathStatementsInspectionTest.kt
src/test/kotlin/org/rust/lang/core/type/RsNeedsDropTest.kt

changelog:
Add better support for path statements inspection and enable it by default

INSP: Enable path statements inspection by default

---

.gitignore
src/main/kotlin/org/rust/ide/inspections/RsAsyncMainFunctionInspection.kt
src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt
src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
src/main/resources/META-INF/rust-core.xml
src/main/resources/inspectionDescriptions/RsAsyncMainFunction.html
src/test/kotlin/org/rust/ide/inspections/RsAsyncMainFunctionInspectionTest.kt

https://doc.rust-lang.org/error_codes/E0752.html
Additionally added a simple quick fix to remove the async modifier from the function.
changelog: Added new inspection for when entry point is async E0752.

INSP: main function is async (E0752)

---

src/main/kotlin/org/rust/ide/typing/RsTypedHandler.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionLiteralSuffixAutoPopupTest.kt

changelog: Show completion auto-popup when literal suffix is typed

COMP: Show completion auto-popup when literal suffix is typed

---

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt
src/main/resources-nightly/META-INF/experiments.xml
src/main/resources-stable/META-INF/experiments.xml
src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt

Now it is separated from `org.rust.mir.borrow-check`

Add `org.rust.mir.move-analysis` experimental feature

---

src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonTest.kt
src/test/kotlin/org/rust/test/util/RsTestJsonPrettyPrinter.kt
src/test/kotlin/org/rustPerformanceTests/RustCompilerErrorComparisonTest.kt

This test runs our inspections against the Rust compiler's test suite and reports detected false negatives and false positives. You can find a verbose test report in `build/reports` directory.

T: add `RustCompilerErrorComparisonTest`

---

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt
src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt

changelog: Add completion for async keyword

COMP: Add completion for async keyword

---

src/main/kotlin/org/rust/lang/core/completion/RsBoolCompletionProvider.kt
src/test/kotlin/org/rust/lang/core/completion/RsBoolCompletionTest.kt

changelog:
Added completion for true/false in places when type is unknown

COMP: Improve completion for true/false

---

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt
src/test/kotlin/org/rust/lang/core/completion/RsAsNameCompletionTest.kt

changelog:
Add "as" completion to provide new names

COMP: Add "as" completion to provide new names

---

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt
src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
src/main/kotlin/org/rust/lang/core/psi/RsRawIdentifiers.kt
src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt

changelog: Suggest associated types in completion without Self:: prefix

Suggest associated types in completion without Self:: prefix
