intellij-rust/intellij-rust

src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
This PR fixes AddStructFieldsFix so that it doesn't fail for structs containing raw identifiers (for example `r#type`). Previously, the fix failed, because it tried to construct code like `{ type: 0 }`, which is not valid and thus the fix would just silently ignore that field.
The `name` attribute/function of both local variables (`RsPatBinding`) and struct fields (`RsFieldDecl`) with a raw identifier returns just the inner name after `r#`. I wasn't sure what's the correct way of getting the whole identifier, so I just used `item.identifier.text`. Please let me know if there's a better way.
Fixes #4861
=> INT: handle raw identifiers in AddStructFieldsFix

src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedElement.kt
It should simplify raw identifiers handling in code that creates new psi from text
=> PSI: introduce `escapedName` property

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
This PR adds support for raw identifiers to ImplementMembers Fix
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4976
=> INT: handle raw identifiers in ImplementMembersFix

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
```rust
trait Foo { fn foo(&self) {} }
//X
trait Bar where { type Item: Foo; }
fn bar<A: Bar>(_: A, b: A::Item) {
b.foo();
}   //^
```
=> TY&RES: support associated type bounds in traits

src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
=> RES: evaluate `cfg` when finding super module

src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt
=> REPL: Fix macro completion inside Rust Console

build.gradle.kts
Remove redundant dependency on java plugin.
Replace `compile` and `testCompile` with `implementation` and `testImplementation` respectively
=> GRD: cleanup build.gradle

src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt
This PR changes ConvertToNamedFields so that it doesn't try to convert all function calls to a named struct literal.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5017
=> INT: fix ConvertToNamedFields handling of function calls

src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
This PR builds default values for constants in ImplementMembersFix. Previously `unimplemented!()` was generated, which caused a compilation fail of the generated code .
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4884
=> INT: build default values for constants in ImplementMembersFix

src/main/kotlin/org/rust/ide/refactoring/generateConstructor/GenerateConstructorHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generateConstructor/ui.kt, src/test/kotlin/org/rust/ide/refactoring/GenerateConstructorActionTest.kt
This PR adds support for generating a constructor (a `new` associated function) for structs. The intention is not complete yet, it doesn't create lifetime/type parameters on the impl block (amongst other things).
I wanted to ask if this is the right direction to go and whether you want to add this intention at all.
Some questions to resolve:
- Offer this intention only on the Struct definition or also in an existing struct impl block?
- Detect if there is already a `new` associated function or a `Default` impl present and do not offer this intention in such a case?
- Detect if there is already an impl block present in the same file to avoid creating a new one?
- Is there an intention to merge impl blocks?
- The AddImplIntention does no such check.
- Should this be a simple intention or …
=> INT: AddConstructor intention

duplicates/src/main/kotlin/org/rust/ide/clones/RsDuplicateScope.kt, src/main/kotlin/org/rust/ide/search/RsWordScanner.kt, src/main/kotlin/org/rust/ide/todo/RsTodoIndexer.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
It should update the corresponding indices after lexer or parser changes.
Also, introduce separate lexer, parser and stub versions
=> Provide missing versions for indexers

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachesInvalidator.kt, src/main/kotlin/org/rust/stdext/Utils.kt, src/main/kotlin/org/rust/stdext/path.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
Fixes #3968
Expanded macros now are not stored on a disk as individual physical files. Instead, they are stored in a snapshot only (snapshot is an IntelliJ platform concept that means a copy of a part of filesystem stored in embedded DB in IntelliJ directory) with new `MacroExpansionVFS`.
Now macro expansion should occupy much less disk space. Also, this should speed up macro expansion because of fewer system calls (filesystem interaction).
=> PERF&MACRO: Introduce MacroExpansionVFS

clion/src/main/kotlin/org/rust/clion/valgrind/RsValgrindConfigurationExtension.kt, common/src/main/kotlin/com/intellij/openapiext/utils.kt, coverage/src/main/kotlin/org/rust/coverage/RsCoverageRunner.kt, debugger/src/main/kotlin/org/rust/debugger/RsBackendConsoleInjectionHelper.kt, src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt, src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt, src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt, src/main/kotlin/org/rust/ide/intentions/addFmtStringArgument/AddFmtStringArgumentIntention.kt, src/main/kotlin/org/rust/ide/navigation/goto/RsNavigationContributorBase.kt, src/main/kotlin/org/rust/ide/notifications/DetachedFileNotificationProvider.kt, src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/openapiext/DelayedBackgroundableProcessIndicator.kt, src/main/kotlin/org/rust/openapiext/ui.kt
Get rid of various old-fashioned `ApplicationManager` usages:
* Replace `ApplicationManager.getApplication().invokeLater` with `invokeLater`
* Replace `ApplicationManager.getApplication().invokeAndWait` with `invokeAndWaitIfNeeded`
* Introduce `isDispatchThread` and use instead of `ApplicationManager.getApplication().isDispatchThread` 
* Introduce `isInternal` and use instead of `ApplicationManager.getApplication().isInternal`
Get rid of potentially incorrect `GuiUtils` and `UIUtil` usages:
* Replace `GuiUtils.invokeLaterIfNeeded` with `runInEdt`
* Replace `UIUtil.invokeAndWaitIfNeeded` with `invokeAndWaitIfNeeded`
=> Cleanup `ApplicationManager` usages

src/main/kotlin/org/rust/lang/core/cfg/CFGBuilder.kt, src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt, src/test/kotlin/org/rust/lang/core/cfg/RsControlFlowGraphTest.kt
=> MACRO: Avoid infinite recursion in macros control flow

src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt
There are two problems with rust console on windows:
1. Colors not displayed correctly (#5058, #5046, #4883). It is related to `colored` crate (used by Evcxr) and will be fixed by adding `colored::control::set_virtual_terminal(true);` to Evcxr code
2. It is possible to run only one command (#5046, #4883). This is because we use `\u0001` and `\u0002` characters as special markers to determine whether the last command was successful. For some reason under windows these characters changes into some other characters. So we will use new marker characters `\u0091` and `\u0092`
=> REPL: Fix for windows (use new escape characters)

build.gradle.kts
Sometimes we don't see stacktraces for failed tests on CI. I think it should be fixed by `-XX:-OmitStackTraceInFastThrow` JVM property applied for tests. Also, I found that gradle allocate 512mb for test JVM which is too low and so can slow down test execution, so I bumped it to 2gb
=> GRD: disable OmitStackTraceInFastThrow in tests & set 2 Gb heap for tests

src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
This PR adds support for aliased types in DestructureIntention. The struct creation is a bit hacky, is there a better way?
I need to pass the type in the context because `ty.item.declaredType != ty` (the declared type has no alias).
For the destructured struct name, I need the base (possibly aliased) name of the struct. I tried to use `type.insertionSafeTextWithAliases`, but for a type with generics and/or lifetimes, it returns for example `S<i32, &str>`, which is not a valid name for a struct pat. Basically I want to get an alias of a type, but only the base name, without generics and lifetimes. I created a new monstrosity (`insertionSafeTextWithAliasesWithoutTypes`).
=> INT: support type aliases in DestructureIntention

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt, src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Now we have `RustSettingsChangedEvent` and can check what properties are changed by a user. For example, now we refresh a cargo project only if the Rust toolchain is changed in settings.
=> Track changed properties in settings change event

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml
This speeds up `cfg` attributes processing, which in turn speeds up name resolution & type inference
Required for #4936 to avoid performance regression
=> PERF&STUB: store `cfg` existence flags to stubs

src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt, src/test/kotlin/org/rust/ide/formatter/RsFormatterLineBreaksTest.kt
So this code
```rust
fn main() {
use mod1; use mod2; let foo = 1;
}
```
will be reformatted into
```rust
fn main() {
use mod1;
use mod2;
let foo = 1;
}
```
=> FMT: add newline between items inside function

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldLookup.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
This PR adds support for `async` function in `RsExtractFunction` refactoring.
Currently I try to find if the extracted elements from the function contain a (top-level) `.await`, and if yes, the extracted function will be `async` too and it's call will be `.await`ed in the original function. However I'm not sure how to correctly recognize if a block is async (I want to stop the `await` search at async blocks, nested awaits inside them are not intereseting). The same should happen for async closures.
We can also simplify this and if the original function is `async`, the extracted function could always be async.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4432
=> REF: handle async functions in ExtractFunction refactoring

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt
Now, if public method is located in private module, the plugin still generates external documentation link for it
Original issue was found for [`is_null` method](https://doc.rust-lang.org/std/primitive.pointer.html#method.is_null) for pointer type in stdlib of rust 1.43.0
=> QDOC: improve generation of external documentation links

src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/5027.
Applicable to functions, non-inherited methods, and closures.
=> INT: Add "Change return type" fix

src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
Fix that when extracting `7` to variable from this code:
```rust
let x1 = if true { 7 } else { 0 };
let x2 = 7;
```
it was transformed to 
```rust
let x1 = if true {
let i = 7;
i
} else { 0 };
let x2 = i;
```
while correct result would be
```rust
let i = 7;
let x1 = if true { i } else { 0 };
let x2 = i;
```
=> REF: Fix introduce variable when first expression is inside nested block

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Fixes #2778
```rust
struct X;
type Y = X;
impl Y { fn foo(&self) {} }
//X
fn main() {
X.foo();
}   //^
```
=> RES: support impls for aliased types

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt, src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
Previously, we didn't use the platform's refresh because of too large UI freezes. Since 2019.3 a part of the refresh process was extracted from EDT and now freezes duration seems acceptable. This speeds up macro expansion a bit
=> PERF&MACRO: use refresh-based VFS batch

build.gradle.kts
Maven Central servers are sometimes unavailable from Travis CI (see [issue](https://issues.sonatype.org/browse/MVNCENTRAL-4985)). I think it's reasonable to add [jcenter](https://bintray.com/bintray/jcenter) mirror as a fallback.
(at first, let's try to use jcenter *instead* of maven central to check that it ever works)
=> GRD: try jcenter instead of maven central

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt, src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/inspections/import/AutoImportHintFix.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Now it highlights only unresolved identifier instead of whole path.
Also, it can highlight unresolved items in the middle of path
Based on #4839
<details> <summary>code</summary>
```rust
mod foo {
pub mod bar {
pub struct Foo;
impl Foo {
pub fn foobar() {}
}
pub mod faz {
pub struct Baz;
pub mod qux {}
}
}
}
use no_foo::bar::{baz, faz};
use foo::no_bar::{baz, faz};
use foo::bar::{baz, faz::Baz};
use foo::bar::{faz::faz::Qux};
use foo::bar::{faz::qux::Qux};
fn main() {
bar::Foo::foobar();
foo::no_bar::Foo::foobar();
foo::bar::NoFoo::foobar();
foo::bar::Foo::no_foobar();
}
```
</details>
Closes #4839
=> INSP: improve unresolved reference inspection

src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/ExtractEnumVariantIntention/after.rs.template, src/main/resources/intentionDescriptions/ExtractEnumVariantIntention/before.rs.template, src/main/resources/intentionDescriptions/ExtractEnumVariantIntention/description.html, src/test/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntentionTest.kt
This PR adds intention for extracting an enum variant into a standalone struct and replaces usages of the old variant.
How should it handle visibility?
For example:
```rust
enum S {
V1(pub u32, pub(crate) u32, u32)
}
```
```rust
struct V1(pub u32, pub(crate) u32, u32);
enum S {
V1(??? V1)
}
```
Right now I select the "broadest" visibility level (`pub` > `crate` > `mod` > `private`).
TODO:
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5024
=> INT: add ExtractEnumVariantIntention

src/main/kotlin/org/rust/ide/console/RsConsoleActions.kt, src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/ide/console/RsConsoleOptions.kt, src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt, src/main/kotlin/org/rust/ide/console/RsConsoleVariablesView.kt, src/main/kotlin/org/rust/ide/console/RsConsoleView.kt, src/main/kotlin/org/rust/ide/presentation/Utils.kt, src/main/kotlin/org/rust/ide/structure/RsPsiStructureViewFactory.kt, src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/structure/RsStructureViewTest.kt
Add variables view to REPL console. It shows available variables, functions and structs (and their types)
=> REPL: Add variables view

src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fix false positive "Field is private" error for such code (introduced in #5120):
```rust
mod some_module {
pub enum Foo {
Foo1 { field: i32 },
}
}
fn main() {
let foo = some_module::Foo::Foo1 { field: 1 };
}
```
=> ANN: Fix false positive E0451 when constructing enum

src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntentionTest.kt
To preserve original comments and other things, I reuse the text of the original struct/tuple literals.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5136
=> INT: replace usages of struct literals and tuple constructors in ExtractEnumVariantIntention

src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt, src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt
Swaps `Display` with `Debug` in `PrintlnPostfixTemplate` as discussed in
https://github.com/intellij-rust/intellij-rust/pull/5149
=> COMP: prefer Display before Debug in PrintlnPostfixTemplate

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml
`REPL_TOOL_WINDOW` experimental feature is not used now (REPL was activated by default in #4879)
=> REPL: Remove experimental feature

src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/resources/META-INF/rust-core.xml
The ability was removed #5085. Looks like it was a mistake and it's still needed to disable cfg evaluation sometimes.
Now it can be disable via Registry (`ctr+shift+a` -> type "Registry" -> uncheck `org.rust.lang.cfg.attributes`).
=> Add ability to disable cfg attributes via Registry

src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt, src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt
This PR modifies `IfLetToMatchIntention` to avoid generating useless `_ => { ... }` arms if the match arm is already irrefutable. Before the generated code would right away contain a warning that the arms after the irrefutable arm can be removed.
It also removes the code from a potential else branch if the pattern is irrefutable, since the else was basically dead code.
=> INT: don't generate useless match arm for irrefutable patterns in IfLetToMatchIntention

src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
This PR stops `RsImportHelper` from importing types behind a type alias.
```rust
mod a {
pub struct A;
pub struct B;
pub struct R<T1, T2>(T1, T2);
pub type U = R<A, B>;
pub trait T {
fn f() -> U;
}
}
// use a::{T, A, B, U}; // <- before PR
use a::{T, U}; // <- after PR
struct S;
impl /*caret*/T for S {
fn f() -> U {  }
}
```
Fixes second half of https://github.com/intellij-rust/intellij-rust/issues/4979
=> INT: don't import inner types of type aliases in ImplementMembers intention

src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt, src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt
Adds support for `RsPat.isIrrefutable` for `RsPatConst`.
=> Recognize irrefutable constant patterns

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Fixes #5071 
During the fix process, the following problems were found:
- Enter `u`, `union` keyword without prompt
- ~There are still problems with `union` automatic fix~
- `Union` does not detect if it exists in an `unsafe` block
=> ANN: Fix union pattern match error

src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
We discussed with @ortem that shortcut for executing code in repl console can be changed from `Enter` to `Ctrl+Enter`. This fixes #4754
Also previously supposed shortcut for adding new line was Shift+Enter, which behaves a bit different from Enter. Now both Enter and Shift+Enter are available
=> REPL: Use Ctrl+Enter as shortcut for executing instead of Enter

src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsRedundantElse.html, src/test/kotlin/org/rust/ide/inspections/RsRedundantElseInspectionTest.kt
Adds inspection to find redundant else branches, as discussed in https://github.com/intellij-rust/intellij-rust/pull/4972.
Right now it doesn't work for these irrefutable patterns:
```rust
enum E { V1 }
fn main() {
let a = E::V1;
if let E::V1 = a {
} else { // <- this else should be redundant
}
}
```
because `let E::V1 = a` is `RsPatConst` and `RsPat.isIrrefutable` returns `false` for it. Should I change this?
Should the inspection's warning range cover only `else` or the whole block after the `else`?
It would be also nice if it recognized irrefutable conditions like `if true` or `if 5 == 5`, but we need some basic constant propagation for this to work (is there something like this in the plugin already)?
=> INSP: add RsRedundantElseInspection

.idea/inspectionProfiles/intellij_rust.xml, .idea/inspectionProfiles/profiles_settings.xml
It should help us to make plugin dynamic and avoid using of non dynamic API
Related to #4832
=> Enable `dynamic plugin verification` inspection for project

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Our analysis is broken on the latest nightly rustc (1.42.0) because "rustc" package was renamed to "rustc_middle" in https://github.com/rust-lang/rust/pull/70536 and now "rust-lang/rust" is not detected by the plugin.
=> Fix stdlib detection when working with rust-lang/rust project

src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingPassFactoryRegistrar.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt, src/main/resources/META-INF/rust-core.xml
To become a dynamic plugin someday, we should get rid of all project/application components. 
I refactored RustfmtWatcher and RsExternalLinterPassFactory. 
Remained UpdateComponent, RsTodoApplicationComponent, RsPsiManager, MacroExpansionManager
Part of #4832. Fixes https://github.com/intellij-rust/intellij-rust/issues/5230.
=> Get rid of some project/application components

src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt, src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
On 2020.1 platform there are strange borders in REPL console:
=> REPL: Remove border between current command and previous commands

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt, src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt, src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt
Update Evcxr to 0.5.1 (with https://github.com/google/evcxr/pull/111 merged)
This is second part of #5066
Fixes #5058, fixes #5046, fixes #4883
=> REPL: Fix for windows (update evcxr)

src/main/kotlin/org/rust/ide/commenter/RsCommenter.kt, src/test/kotlin/org/rust/ide/commenter/RsCommenterTest.kt
I used `CodeDocumentationAwareCommenter` to add support for completing block comments. Because line comments are handled separately and doc comments are pretty complex in Rust and can't be handled by `CodeDocumentationAwareCommenter` alone, I act as there are only block comments in Rust for the sake of completion provided by `CodeDocumentationAwareCommenter`.
Let's see what CI says about this change.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5171
=> COMP: add block comment suffix after enter

src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt, src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt
Provide proper spacing between `pub`/`pub(path)` and next token
=> FMT: better visibility formatting

src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt, src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt, src/main/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntention.kt, src/main/kotlin/org/rust/ide/refactoring/RsInPlaceVariableIntroducer.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/intentions/ExtractEnumVariantIntentionTest.kt
Bunch of fixes:
* Enable the intention.
* Get rid of `extractVisibility` and related staff since visibility qualifiers for enum variant's fields are not permitted ([E0449](https://doc.rust-lang.org/error-index.html#E0449)).
* Now generated struct has the same visibility qualifier as parent enum has.
* Since enum's fields have public visibility by default, add `pub` qualifier to all fields in generated struct if the corresponding field in the enum variant has no visibility qualifier.
* After replacing usages of the original enum variant, import the generated struct if needed.
* Fix struct renaming if an element with the same name already exists in the scope.
There is one more problem. `RsInPlaceVariableIntroducer` doesn't work if the element to rename has non-local use scope.
Closes #5024
=> INT: Fix and enable "Extract enum variant" intention

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/RsGeneratedSourcesFilter.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoPackageIndex.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt, src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt, src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt, src/main/kotlin/org/rust/ide/search/RsWithMacrosProjectScope.kt, src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsIndexableSetContributor.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionWritingAccessProvider.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
Also:
- `MacroExpansionManager` is not created for non-rust projects. Still will be created if you open `.rs` file
- Simplified `MacroExpansionManager` loading. No more Futures and awaits.
- Fix `RsMacroExpansionCachingToolchainTest` test on 2020.1 and on java 11.
Part of #4832
=> MACRO: turn MacroExpansionManager into a service

src/main/kotlin/org/rust/ide/hints/RsInlayParameterHintsProvider.kt
Adds support for blacklisting to parameter hints. The explanation HTML was largely adapted from the Java example shown by @ortem, with some adaptations for Rust (`std` module and `_` patterns in parameters).
Questions:
1) The type hint provider has a method which shows an example window in the settings. `InlayParameterHintsProvider` has `getSettingsPreview`, but even if I implement it it doesn't show any preview in the settings. Is this the correct method to implement?
2) Is there a way to test this?
3) Should we provide some special syntax for the local crate? For example we could put `$crate::module` syntax into the blacklist and then use this path for crate-local functions.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5167
=> Add support for blacklisting to RsInlayParameterHintsProvider

src/main/resources/META-INF/rust-core.xml
=> INSP: proper display name for `RsRedundantElseInspection`

build.gradle.kts
=> GRD: don't add channel suffix if channel is `stable`

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt
Now `RsExpandedElement.getContextImpl` looks more flat in the profiler. 
(this simplifies profiling rather than improves performance)
=> PERF: less recursive `RsExpandedElement.getContextImpl`

src/main/kotlin/org/rust/ide/refactoring/RsDirectoryRenameProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Otherwise, it may affect rename provided by other languages like renaming of Java packages.
Fixes https://youtrack.jetbrains.com/issue/IDEA-238958
=> REF: don't rename non rust directories

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt, src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt, src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
1. Now we take into account usages in files included to the project by `include!()` macro:
```
//- lib.rs
include!("foo.rs");
fn bar() {}
//^ find usages for this function
//- foo.rs
pub fn foo() {
bar(); // this usage will be found
}
```
2. Fixes #5265
3. T: better tests for search scopes. Now all name resolution tests also check search scopes of resolved items
=> Fix "find usages" action with `include!()` macros and `pub(crate)` items in crate root

src/main/kotlin/org/rust/ide/annotator/fixes/SurroundWithUnsafeFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeTest.kt
I modified SurroundWithUnsafeFix to find parent expression statements recursively, before it only looked one level up.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5285
=> FIX: search for parent expression recursively in SurroundWithUnsafeFix

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachesInvalidator.kt
Previously the "cache" (macro expansion data) directories were deleted immediately when "Invalidate caches & Restart" is performed.
Now we postpone it until the next IDE launch. This is how index/VFS invalidation works. It helps to keep things consistent until the restart.
Fixes #4497
=> MACRO: properly do "Invalidate caches & Restart"

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesDialog.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/main/resources/META-INF/rust-core.xml
Add handler for move refactoring (#5181). Handler checks if file can be moved, and find module which should become new parent module of moved file
Currently handler will always run default move processor (which just moves file). Handler code is split into separate PR in order to improve review process (main PR is somewhat too big)
Handler is disabled by default and can be enabled using `org.rust.ide.refactoring.move` experimental feature (in registry)
=> REF: Move single file (add handler)

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTestBase.kt
Closes #5126.
Added support of the cases I can predict. Implemented it simultaneously iterating over calculated types and written ones. If there is a better way, happy to know :)
=> TYPE: Add type hints to type placeholders

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, prettyPrinters/gdb_lookup.py, prettyPrinters/gdb_providers.py, prettyPrinters/lldb_lookup.py, prettyPrinters/lldb_providers.py, prettyPrinters/rust_types.py, pretty_printers_tests/src/test_runner.rs, pretty_printers_tests/tests/nonzero.rs
This PR adds support for pretty printing `NonZero` numbers from the standard library. So far I have implemented support for GDB, if you think that my approach is OK, let me know and I'll try to add support for LLDB.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5247
=> DBG: add support for pretty printing nonzero numbers

src/main/kotlin/org/rust/lang/core/types/borrowck/ExprUseWalker.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
=> Fix move analysis of struct literals with base expr

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
This PR adds completion for angle brackets for generic types, i.e.
```rust
let x: Ve/*caret*/
vvv
let x: Vec</*caret*/>
```
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4508
=> COMP: add completion of angle brackets for generic types

.idea/runConfigurations/RunCLion.xml, .idea/runConfigurations/RunIDEA.xml, CONTRIBUTING.md, build.gradle.kts
These changes should speed up some developer workflows related to IDE launch:
* platform version switch. Now we use different sandbox directories for different platform versions that should keep application data (like indices or expanded macros) when you change platform version. As a result, it eliminates unnecessary indexation when you want to check something with non-default platform version
* debugging. Now gradle script debugging is disabled for `RunIDEA` and `RunCLion` run configurations that speeds up IDE launch
Other changes:
* `Run` run configuration is renamed to `RunIDEA` to be consistent with `RunCLion`
* `configureCLion` task is dropped as redundant because now we provide explicit sandbox name
* `CONTRIBUTING.md` improvements and updates
=> GRD: improve developer workflows

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
This mostly affects `impl`s collecting.
#4335 was implemented a bit buggy, so `impl`s wasn't filtered from nested modules if a parent module is disabled by `#[cfg]` (see test).
=> Fix. Ignore entire mod subtree if disabled `#[cfg]`

src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt
This PR adds support for copying (a supported subset of) attributes from the parent enum to the generated struct in `RsExtractEnumVariant`. I added `derive` and `repr` to the set for now.
@Undin The generated code puts an empty line between the attributes and the struct, like this:
```rust
#[derive(Debug, Clone)]
#[repr(C)]
pub struct V1 { pub x: i32, pub y: i32 }
```
I'm not putting it there, it seems like it's done automatically by the formatter. How can I avoid the empty line?
Blocked by https://github.com/intellij-rust/intellij-rust/pull/5291
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5283
=> Copy enum attributes in RsExtractEnumVariant

src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
<details>
```
java.lang.AssertionError: file=FILE; tree=Element(FILE)
each of class class org.rust.lang.core.psi.impl.RsExternCrateItemImpl; valid=true; ref=com.intellij.psi.impl.source.SubstrateRef$StubRef@ba9737b
each of class class org.rust.lang.core.psi.RsFile; valid=true; same file=true; current tree= Element(FILE); stubTree=null; physical=false
each stub RsExternCrateItemStub
each stub RsFileStub{myFile=FILE, myInvalidationReason=null, myStubRoots=[RsFileStub], stubTree=null}
at com.intellij.extapi.psi.StubBasedPsiElementBase.notBoundInExistingAst(StubBasedPsiElementBase.java:226)
at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:139)
at com.intellij.extapi.psi.ASTDelegatePsiElement.findChildByType(ASTDelegatePsiElem …
```
=> Fix exception during stub indexing

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Speeds up this path in macro resolution:
After the PR:
=> PERF&MACRO: optimize macro resolve

src/main/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandler.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt
Fixes #3757 (fixes #2586) issues "E0603 module is private" when importing a module that is declared multiple times (has multiple `mod foo;` declarations, e.g. in `lib.rs` and `main.rs`). 
Also "Go To Super" action (ctrl+U) now allows choosing a declaration (if multiple):
Note that this is a **very** initial support of multiple module inclusions, i.e. now we can just know that a module is declared multiple times and e.g. suppress some inspections in this case.
=> Initial support of multiple module declarations of the same module

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt, src/test/kotlin/org/rust/ide/notifications/DetachedFileNotificationProviderTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Note, full support (name resolution and completion for code from including file in included one and correct module hierarchy recognition, i.e. absence of false positive "File is not included in module tree" editor notification), is available only when new macro expansion engine is enabled (#3628)
See https://github.com/intellij-rust/intellij-rust/issues/1908#issuecomment-593026377 for real world use case
Closes #5036
=> MACRO: support `include!` macro calls generated by another macro call

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Previously, if `org.rust.cargo.evaluate.build.scripts` feature was enabled and there was compilation error, fetching workspace data failed
Fixes #5016
=> CARGO: fetch cargo metadata even with compilation error

src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt, src/main/kotlin/org/rust/ide/refactoring/introduceConstant/ui.kt, src/main/kotlin/org/rust/ide/refactoring/introduceParameter/RsIntroduceParameterHandler.kt, src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
In this PR I'd like to tackle the Introduce constant refactoring. The current state is just a sketch, because I have a few questions:
- Should this work on arbitrary expressions (and types) or just literals?
- Where should the corresponding constant be generated? Maybe we should show the user a short dialog (similar to the Introduce parameter refactoring) to let him select? For example here:
```rust
//x
mod x {
//x
fn foo() {
//x
fn bar() {
//x
let x = 5;
}   
}
}
```
We could offer these 4 locations (inner function, outer function, inside module, outside module).
- Should literals with the same type and value in the given context (function/block) be extracted to use the newly created constant (same as with the Introduce Variable refactoring)?
Related issue: …
=> REF: introduce constant refactoring

src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
There were two problems:
* completion psi patterns use `PsiElement#getContext` method. But our implementation of `getContext` uses indices sometimes that leads to `IndexNotReadyException` because keyword completion may be called in dumb mode. Now we make index lookup only in smart mode
* `await` keyword completion uses type inference, i.e. uses indices sometimes as well => it should be called only in smart mode. The corresponding completion provider was moved from keyword completion contributor to be invoked only in smart mode (CC @mchernyavsky)
Tests improvements:
* `RsKeywordCompletionContributorTest` now check completion in dumb mode
* usages of deprecated `checkSingleCompletion` in `RsKeywordCompletionContributorTest` were replaced with `checkCompletion`
Fixes #5123
=> COMP: fix IndexNotReadyException while completion

src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
This PR modifies the `ExtractFunction` refactoring to omit needless type arguments which are the same as the default for its given type parameter.
~I had to create yet another type renderer to not mess with other places where types are rendered. I wonder if it would be possible to replace things like `Ty.insertionSafeTextWithAliasesAndLifetimes` with simply creating a type renderer in each individual place where it's needed? The callers could then specify exactly the properties for type rendering that they need. The `TypeRenderer` seems very cheap to create, but if it would be a perf. problem then some dynamic caching mechanism could be used.~
I think that skipping the default unchanged type arguments is pretty useful and could be used as a default for type rendering. But maybe there are …
=> REF: omit unchanged default type parameters of parameters in ExtractFunction

src/193/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsTestPlatformBase.kt, src/201/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsTestPlatformBase.kt, src/main/kotlin/org/rust/ide/hints/RsChainMethodTypeHintsProvider.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/hints/RsChainMethodTypeHintsProviderTest.kt, src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt, src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsTestBase.kt
This PR adds support for chained method hints.
Questions:
1) ~I copied the new (201) inlay tests from `RsInlayTypeHintsProviderTestBase`, should I also add support for 193?~ Turns out that CI won't pass without it, so I added it. Also I'm not sure that I understand the syntax for writing hint tests :-)
2) The preview text in settings does not seem to be affected by the hints. Maybe it misses the std types, can they be added somehow or do I have to prepare a standalone preview without std?
3) Should I add some settings?
4) I'm a bit confused about the difference between `RsPlainHint` and the various `InlayHintsProvider`s. Should I add support for this hint to `RsPlainHint`?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5190
=> HINT: add hints for chained method calls

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
This PR builds on top of https://github.com/intellij-rust/intellij-rust/pull/3869 and adds additional checks which look for missing or invalid parameters in format macros. After this check exists we can possibly add quick fixes to add missing parameters.
Questions:
- I need to check if a `Ty` implements a given trait. I tried to use `isTraitImplemented` from `ImplLookup`, but I had to make it public and it also doesn't seem to work in tests, I'm probably doing something wrong.
- Should this check be performed every time? Now I only do the check if there are not large errors in the format (for example missing `}`). If there is such a fundamental error, it will probably produce a lot of (false positive) parameter errors, so the parameter check should probably be skipped.
Fixes: …
=> ANN: check existence and type of parameters in format macros

src/main/kotlin/org/rust/RsProjectTaskQueueService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/openapiext/AsyncTasks.kt, src/main/kotlin/org/rust/stdext/Utils.kt
This makes macro expansion cancellation more fast in the case of cargo refresh (e.g. Cargo.toml editing)
Also:
1. macro expansion is now cancelled immediately if the new engine is disabled in the settings;
2. progress bar of macro expansion task is not shown until the end of the indexing
=> MACRO: use common task queue with cargo sync

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt
Some fixes for #4969
1. Suppress trait check in doctest injections (usually leads to false-positives due to some bugs in type inference)
2. Fix false-positive "Unknown format trait" if no cargo project/stdlib (e.g. a scratch file)
3. Enable most of checks except trait checks even if the old macro expansion engine is used (previously most of the checks were disabled)
c.c. @Kobzol
=> ANN: fix false-positives in RsFormatMacroAnnotator

CONTRIBUTORS.txt, src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
This PR changes the grammar used by the macro expander to match on `path` fragments. The Rust Reference [specifies](https://doc.rust-lang.org/stable/reference/macros-by-example.html#metavariables) that a path fragment should be parsed as a type-like path:
> * `path`: a _[TypePath](https://doc.rust-lang.org/stable/reference/paths.html#paths-in-types)_ style path
Before this PR value-like paths were used, which caused some macros to fail to expand.
Closes #5357
=> Use the proper grammar for path fragments in macro_rules!

src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/MacroGraphWalker.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt, src/main/kotlin/org/rust/lang/core/parser/util.kt
Some optimization in `FragmentKind.parse`: do less Grammar Kit stuff, use more lightweight parsing methods.
This slightly speeds up macro expansion
=> PERF&MACRO: slightly optimize macro matching

src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/ide/console/RsConsoleView.kt, src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt, src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTest.kt, src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestBase.kt, src/test/kotlin/org/rust/ide/console/RsConsoleCompletionTestFixture.kt
Fix #5214
Previously only `RsNamedElement` and `RsStmt` were added to context, so imports were ignored
=> REPL: Fix imports

src/main/kotlin/org/rust/lang/core/cfg/ControlFlowGraph.kt, src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
Added support for highlighting never types as function exit points.
Also fixes highlighting of macro expressions in tail position.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/1712
=> ANN: highlight never type exit points

src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5377
=> REF: fix auto-import in introduce constant refactoring

src/main/kotlin/org/rust/ide/hints/RsChainMethodTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/RsTypeHintsPresentationFactory.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/test/kotlin/org/rust/ide/hints/RsChainMethodTypeHintsProviderTest.kt, src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
Now any type that implements `Iterator` trait is rendered in inline hints as `impl Iterator<Item=...>` in chained method call hints (#5276). It can be enabled for usual type hints in the future.
Fixes #1803
c.c. @Kobzol
=> HINT: special case for `impl Iterator` types

src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt, src/201/main/resources/META-INF/platform-core.xml
Native Debugging Support plugin is required to debug Rust code in IDEA Ultimate.
These changes introduce fake debugger runner to show users that debugging in IDEA Ultimate is available but user should install plugin.
It should make debugging in IDEA more discoverable
Closes #5201
=> DBG: advertising of Native Debugging Support plugin

debugger/src/201/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt, debugger/src/201/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtilsExt.kt, debugger/src/201/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt, debugger/src/201/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
Now, if your debugger is not loaded or should be updated, the corresponding dialog and debugger loading don't interrupt debugger session and it continues after successful loading.
Also, there is option, to download/update debugger automatically, i.e. not show dialog at all
Closes #5202
=> DBG: don't interrupt debugging session if debugger is not loaded/update

src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt
It should explain the platform that it shouldn't use this constructor while creation extension instance
Fixes #5434
=> Mark RsBacktraceFilter constructor as non injectable

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/RsGlobalIndexFilterForMacroExpansionFileSystem.kt, src/main/resources/META-INF/rust-core.xml
This speeds up macro expansion up to 20%
I disabled IdIndex and TrigramIndex just because we don't use them (in the case of macro expansion) but they affect indexing performance significantly.
I also disabled FilenameIndex in order to exclude macro expansion files from file search.
Note that without IdIndex reference search doesn't work, so if you need searching references in macro expansions you should enable IdIndex again
See macro expansion indexing flame chart. Highlighted area contains stub tree building code, it doesn't change. To the right of it, there are IdIndex and TrigramIndex parts
Before:
After (now almost nothing but stub tree building :+1: ):
=> PERF&MACRO: disable some indices for macro expansions

src/main/kotlin/org/rust/ide/commenter/RsCommenter.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/ide/commenter/RsCommenterTest.kt
This PR solves https://github.com/intellij-rust/intellij-rust/issues/5388 with a pretty heavyweight solution of implementing `SelfManagingCommenter`. The implementation is pretty basic, but it passes all the original `RsCommenter` tests and some new ones that I have added.
It seems to work for basic use cases, if you can find some counter-examples where it breaks, let me know and I'll add them to the test suite.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5388
=> TYPE: implement SelfManagingCommenter

.github/workflows/rust-release.yml, MAINTAINING.md, scripts/Pipfile, scripts/release-actions.py
* use [click](https://click.palletsprojects.com/) library instead of argparse
* update command syntax. Now you don't need to pass `--command` flag to specify a command
* github token can be provided via `IR_GITHUB_TOKEN` environment variable
* added `--no-update-changelog` option for `stable-release` command to omit changelog link update. Useful for releases with hotfixes
=> CI: improve release actions script

src/main/kotlin/org/rust/ide/hints/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyInfer.kt, src/test/kotlin/org/rust/ide/hints/RsInlayTypeHintsProviderTest.kt
The bug was introduced in #5197
Fixes #5443, fixes #5428
=> HINT: fix inlay hints for type placeholders

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
This PR adds file system completion suggestions for string literals that are in a "path" context. A path context right now is:
1) `Path::new(<>)`
2) `PathBuf::from(<>)`
3) function argument of a call that is of type `AsRef<Path>`, e.g. `std::fs::canonicalize(<>)`
I think that this feature has been suggested to me by someone in some issue here (maybe @Undin ?), but maybe I'm wrong. Anyway, I think that it's a pretty nice feature, I know it for example from PyCharm and the `open` function. I'm not sure about the performance implications of filtering the path context string literals though. What do you think?
The change in `ElementPattern<I>.or` had to be made because `or` of `ElementPattern<I>` and `ElementPattern<I>` produced `ElementPattern<PsiElement>` and I needed to `or` three things, …
=> COMP: add file system completion for string literals in path context

src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt
The run icon is not displayed when `main function` is declared in a nested method.
=> TYPE: Fix run icon display

src/main/kotlin/org/rust/lang/core/macros/RsFileTypeOverriderForMacroExpansionFileSystem.kt
<details>
```
java.lang.UnsupportedOperationException: /Users/jasonmcpeak/projects/payrailz-app/packages/pz-ontrac/src/components/modules/paymentOps/BillerManagement/Automatch/Templates/Scopes/__stories__/ScopesAddEditCard.stories.js
at com.intellij.openapi.vfs.newvfs.impl.StubVirtualFile.unsupported(StubVirtualFile.java:212)
at com.intellij.openapi.vfs.newvfs.impl.StubVirtualFile.getFileSystem(StubVirtualFile.java:30)
at org.rust.lang.core.macros.RsFileTypeOverriderForMacroExpansionFileSystem.getOverriddenFileType(RsFileTypeOverriderForMacroExpansionFileSystem.kt:21)
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.lambda$getFileTypeByFile$13(FileTypeManagerImpl.java:575)
at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeI …
```
=> fix exception in RsFileTypeOverriderForMacroExpansionFileSystem

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt, src/main/kotlin/org/rust/lang/core/macros/VfsInternals.kt, src/main/kotlin/org/rust/openapiext/utils.kt, src/main/kotlin/org/rust/stdext/HashCode.kt, src/main/kotlin/org/rust/stdext/Utils.kt, src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt
We still have some unexplained bugs in the macro expansion engine. E.g. false-positive "Use of moved value" for i32 - this can be explained by unexplained disappearing of macro expansions =/
I failed to investigate it, so I just add more asserts, more logs and do more attempts to recover things if something got wrong. Maybe we'll catch the reason later.
=> MACRO: more consistency checks

src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml
It should affect only users with nightly builds
See #3628 for more details about new macro expansion engine
=> MACRO: enable new macro expansion engine in nightly builds

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt, src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt, src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ignored_test_is_run_with_ignored_option.xml
This PR adds `--ignored` to test run configurations created from a single test function that has a
`#[ignore]` attribute. I think that this behaviour is reasonable, i.e. if I test a directory or multiple files, ignored tests are ignored, but if I explicitly want to run a single ignored test, it will not be ignored.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5045
=> RUN: add --ignored to command line for ignored tests

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt, src/main/resources/postfixTemplates/ErrPostfixTemplate/after.rs.template, src/main/resources/postfixTemplates/ErrPostfixTemplate/before.rs.template, src/main/resources/postfixTemplates/ErrPostfixTemplate/description.html, src/main/resources/postfixTemplates/OkPostfixTemplate/after.rs.template, src/main/resources/postfixTemplates/OkPostfixTemplate/before.rs.template, src/main/resources/postfixTemplates/OkPostfixTemplate/description.html, src/main/resources/postfixTemplates/SomePostfixTemplate/after.rs.template, src/main/resources/postfixTemplates/SomePostfixTemplate/before.rs.template, src/main/resources/postfixTemplates/SomePostfixTemplate/description.html, src/test/kotlin/org/rust/ide/template/postfix/ErrPostfixTemplateTest.kt, src/test/kotlin/org/rust/ide/template/postfix/OkPostfixTemplateTest.kt, src/test/kotlin/org/rust/ide/template/postfix/SomePostfixTemplateTest.kt
Since all those are trivial, I basically just copy-paste-edited them from `dbg` postfix template, its tests and descriptions. If you think it'd be good to change something or add some specific tests, let me know. This is very lazy job, but it does the job 😄
fixes #5494 
Note: I signed the CLA in the past to contribute to Vue plugin, so I just added my name here.
=> Add postfix templates for Result/Option wrapping

README.md
Adds badge for GitHub action checks.
Also update links to TeamCity build badges. Actually I am not sure about TeamCity badges, probably we should remove them, because most TeamCity builds are paused now? And probably some other TeamCity build should be paused, e.g. [Upload Nightly 193](https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_Rust_Toml_UploadNightly193)
=> DOC: Add github actions badge to readme

src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddMainFnFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsMainFunctionNotFound.html, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/fixes/AddMainFnFixTest.kt
Closed #5477
<del>There is currently no way to quickly test `[[bin]]`, so I did not add a test. ;(</del>
=> ANN: check if the `main` function exists [E0601]

src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroCallIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsExternCrateReexportIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsFeatureIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsNamedElementIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsReexportIndex.kt, src/main/kotlin/org/rust/openapiext/utils.kt
Accessing indices during document committing (PSI event processing) forces to rebuild stubs synchronously (in the EDT!) and affects editor responsiveness, so let's assert that nobody does that.
Previous index access was fixed in #4487
=> Assert we do not access indices during document committing

src/main/kotlin/org/rust/ide/intentions/AddImplIntention.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
I.e. place the caret near T in `impl T {}` when navigating to this impl (e.g. from `Self`)
```rust
impl /*caret_after*/Foo { // <- navigates here
fn foo() -> /*caret_before*/Self {} // Ctrl + B
}
```
Note that this also works for "Go To Implementation" navigation from a trait:
```rust
trait T/*caret_before*/ { // Ctrl + Alt + B
fn test(&self);
}
impl T for /*caret_after*/() { // <- navigates here
fn test(&self) {}
}
```
=> Place the caret near a type when navigating to an impl

README.md
Adding info on the IDEA debugger: OS and LLDB limitations
=> Update in Reamde

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/ext/RsAssocTypeBinding.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoDeclarationTest.kt
Fixes "Go To Declaration" (Ctrl + B) action in this case on the 2020.2 platform
```rust
trait Foo { type Item; }
type T = dyn Foo</*caret*/Item = i32>;
``` 
Part of #5537
=> Fix go-to-declaration from assoc type binding on 2020.2

src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt
For files property `name` includes file extension, so property `modName` should be used instead
=> PSI: Fix `RsMod.getChildModule`

src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5541
=> INSP: do not trigger RsMainFunctionNotFoundInspection for files with a root error

src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
Improve quick repair to remove redundant content instead of all content.
=> Improve `RemoveTypeArguments`

src/main/kotlin/org/rust/ide/refactoring/extractFunction/ExtractFunctionParameterTablePanel.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
This PR adds mutability selection to the UI of `ExtractFunction`. I separated mutability from references, which should make it easier to add another option to choose "by value" or "by ref" parameters in the future.
There is a slightly weird interaction with `requiresMut` (formerly called `isMutableValue`), for example here:
```rust
fn test(mut v: Vec<i32>) {}
fn test2(v: &mut Vec<i32>) {}
fn foo() {
let mut vec = vec![1, 2, 3];
let mut vec2 = vec![1, 2, 3];
/*caret*/bar(vec, &mut vec2);
}
fn bar(mut vec: Vec<i32>, mut vec2: &mut Vec<i32>) {
test(vec);
test2(&mut vec2);
}
```
If I turn off the mutability of `vec2`, it switches from `mut vec2: &mut Vec<i32>` to `vec2: &Vec<i32>`. A better solution would be to not require `mut` there and just pass `vec2` to `test2` directly: `test2(vec2)`. …
=> REF: allow the user to select mutability of parameters in ExtractFunction

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBinding.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinitionBase.kt
```
macro foobar($i/*caret*/:tt) { // find usages here
$i
}
```
<details>
```
java.lang.IllegalStateException: Macro binding outside of a macro
at org.rust.lang.core.psi.ext.RsMacroBindingImplMixin.getUseScope(RsMacroBinding.kt:20)
at com.intellij.psi.impl.search.PsiSearchHelperImpl.getUseScope(PsiSearchHelperImpl.java:69)
at com.intellij.psi.search.searches.ReferencesSearch$SearchParameters.getEffectiveSearchScope(ReferencesSearch.java:111)
at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:54)
at com.intellij.psi.impl.search.CachesBasedRefSearcher.processQuery(CachesBasedRefSearcher.java:19)
at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:77)
at …
```
=> Fix exception during find usages in macro 2.0

src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt, src/test/resources/org/rust/ide/folding/fixtures/macro_brace_arg.rs
<details>
```
java.lang.IllegalArgumentException: Invalid range specified: (933, 917); 
at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:236)
at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:231)
at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:227)
at com.intellij.openapi.util.TextRange.<init>(TextRange.java:40)
at com.intellij.openapi.util.TextRange.<init>(TextRange.java:29)
at org.rust.ide.folding.RsFoldingBuilder$FoldingVisitor.foldBetween(RsFoldingBuilder.kt:128)
at org.rust.ide.folding.RsFoldingBuilder$FoldingVisitor.visitMacroArgument(RsFoldingBuilder.kt:98)
at org.rust.lang.core.psi.impl.RsMacroArgumentImpl.accept(RsMacroArgumentImpl.java:21)
at …
```
=> Fix exception during code folding of invalid macro calls

src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveRefFix.kt
<details>
```
kotlin.TypeCastException: null cannot be cast to non-null type org.rust.lang.core.psi.RsUnaryExpr
at org.rust.ide.inspections.fixes.RemoveRefFix.getText(RemoveRefFix.kt:26)
at com.intellij.codeInspection.LocalQuickFixOnPsiElement.getName(LocalQuickFixOnPsiElement.java:53)
at com.intellij.codeInspection.ex.QuickFixWrapper.getFamilyName(QuickFixWrapper.java:58)
at com.intellij.codeInspection.ex.QuickFixWrapper.getText(QuickFixWrapper.java:52)
at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching.<init>(IntentionActionWithTextCaching.java:53)
at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching.<init>(IntentionActionWithTextCaching.java:48)
at …
```
=> Fix possible NPEs in some LocalQuickFix.getText()

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
This PR changes error annotation to show a type error if you give an immutable reference where a mutable reference is expected, even if the type behind the reference is not fully resolved. I think that this is useful, because even if the types are unresolved, passing `&` where `&mut` is expected will be an error in any case and if we show the annotation (and solve it with a quick fix, that I'll send a separate PR for), it can help with actually resolving the type (this happens in the linked issue).
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4705
=> ANN: show type errors for references containing unknown types if mutability differs

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
<details>
```
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.lang.javascript.psi.impl.JSFileImpl #TypeScript JSX  because: different providers: com.intellij.lang.javascript.JSFileViewProviderFactory$JSFileViewProvider{vFile=file:///home/pepa/dev/pool@master/web-ui/packages/slushpool/app/root/modules/user/actions/auth.tsx, vFileId=89892, content=VirtualFileContent{size=6159}, eventSystemEnabled=true}(5e3c1e87); com.intellij.lang.javascript.JSFileViewProviderFactory$JSFileViewProvider{vFile=file:///home/pepa/dev/pool@master/web-ui/packages/slushpool/app/root/modules/user/actions/auth.tsx, vFileId=89892, content=VirtualFileContent{size=6159}, eventSystemEnabled=true}(2398b94d)
invalidated at: see attachment
at …
```
=> Fix PsiInvalidElementAccessException in RsExternalLinterPass

src/main/kotlin/org/rust/ide/inspections/fixes/ChangeRefToMutableFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeRefToMutableFixTest.kt
This PR adds a quick fix to convert an immutable reference to a mutable one:
The last test should be enabled if/after https://github.com/intellij-rust/intellij-rust/pull/5548 gets merged.
Umbrella issue: https://github.com/intellij-rust/intellij-rust/issues/1730
Fixes: https://github.com/intellij-rust/intellij-rust/issues/2472
=> INSP: add quick fix to convert immutable reference to mutable reference

src/main/kotlin/org/rust/ide/refactoring/RsDowngradeModuleToFile.kt, src/main/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryAction.kt
Both `RsDowngradeModuleToFile` and `RsPromoteModuleToDirectoryAction` refactorings were available on all Rust PsiElements all of the time, without checking if their corresponding file is valid for the refactoring. Invoking such refactoring could have a nasty effect, for example it could delete a whole (non-empty) source directory.
I modified them to only be available if the corresponding file in the editor is valid for the refactoring. We can also ban them altogether from the editor and only enable it from the Project tree.
=> FIX: disable downgrade module and promote to module refactorings for unavailable files in editor

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This PR adds inspection that checks if a supertrait is implemented:
```rust
trait A {}
trait C: A {}
struct S;
impl <error descr="the trait bound `[S]: A` is not satisfied [E0277]">C</error> for S {}
```
All supertraits of the trait are checked, but the check is not recursive (i.e. supertraits of supertraits are not checked). If you try to implement the missing trait, the recursive requirements will pop on that `impl`, so that should be fine.
I'm also thinking of adding a quick fix that would add `impl MissingTrait for Type` above the impl with the error and apply `ImplementMembersFix` right away. Do you agree?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5194
=> INSP: check if supertrait is implemented

src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt, src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
Irrefutable (let) patterns are no longer a hard compiler error, so I think that it's more useful for `MatchToIfLetIntention` to be available in cases where the input match or output let statements are irrefutable.
Related to: https://github.com/intellij-rust/intellij-rust/pull/4972
Fixes: https://github.com/intellij-rust/intellij-rust/issues/1287
=> INT: enable MatchToIfLetIntention for irrefutable patterns

src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveVariableFix.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
This PR adds a quick fix to remove an unused variable.
It is only offered on variables with a simple pattern binding (`RsPatIdent`):
```rust
let a/*caret*/ = 5; // offered
let S { a/*caret*/, b } = ...; // not offered
```
We can also support these more complex cases. For example for struct field bindings we can remove the whole binding if the only field was removed or add `..` to the end if the struct has multiple fields, but I'm not sure if it's worth the complexity.
Inspired by Kotlin, I use a very simple heuristic to check whether to also remove the variable expression or not. It's conservative and considers most things to be side effects, but it allows `BinaryExpr`s and `UnaryExpr`s if their arguments are side effect free. In most cases that should be safe, but if `*` or `+` is …
=> INSP: add remove variable quick fix to liveness inspection

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/inspections/checkMatch/RsMatchCheckInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsMatchCheckInspectionTest.kt
Fixes #4896 by checking if the enum was declared in the same crate or not. I'm not sure if using `crateRoot` is the right approach, so feedback is welcome!
=> INSP: Fix non_exhaustive false positive in same crate

src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt, src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt, src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt
Now it's enough to press Ctrl+Z single time to undo a refactoring (previously 2 was needed)
Works for `introduce constant`, `introduce parameter` and `introduce variable` refactorings
=> REF: do refactoring and inplace rename within a single write command

src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt
Looks like `TyTypeParameter.traitBounds` can be accessed from multiple threads (probably `TyTypeParameter` is cached and then a cached value is accessed from multiple threads), so we should use `LazyThreadSafetyMode.PUBLICATION`.
<details>
<summary>Otherwise it causes such exceptions</summary>
```
kotlin.KotlinNullPointerException
at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
at org.rust.lang.core.types.ty.TyTypeParameter.getTraitBounds(TyTypeParameter.kt)
at org.rust.lang.core.types.ty.TyTypeParameter.getTraitBoundsTransitively(TyTypeParameter.kt:37)
at org.rust.lang.core.resolve.ImplLookup.getEnvBoundTransitivelyFor(ImplLookup.kt:290)
at org.rust.lang.core.resolve.ImplLookup.assembleCandidates(ImplLookup.kt:641)
at org.rust.lang.core.resolve.ImplLookup.selectCandidate(ImplLookup.kt:564) …
```
=> Fix lazy's LazyThreadSafetyMode

src/main/kotlin/org/rust/ide/intentions/ConvertUFCSToMethodCallIntention.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/ConvertUFCSToMethodCallIntention/after.rs.template, src/main/resources/intentionDescriptions/ConvertUFCSToMethodCallIntention/before.rs.template, src/main/resources/intentionDescriptions/ConvertUFCSToMethodCallIntention/description.html, src/test/kotlin/org/rust/ide/intentions/ConvertUFCSToMethodCallTest.kt
This PR adds an intention that converts a UFCS to a method call.
The implemented self argument coercion is very basic, but it seems to work. If there is a better API that could support `Deref` implementations and any coercions that are not handled now, let me know.
Related: https://github.com/intellij-rust/intellij-rust/pull/5601
Fixes second part of https://github.com/intellij-rust/intellij-rust/issues/4451.
=> INT: convert UFCS to method call

src/main/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/ConvertMethodCallToUFCSIntention/after.rs.template, src/main/resources/intentionDescriptions/ConvertMethodCallToUFCSIntention/before.rs.template, src/main/resources/intentionDescriptions/ConvertMethodCallToUFCSIntention/description.html, src/test/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSTest.kt
This PR adds an intention that converts a method call to a UFCS call. I'll add the corresponding intention in the opposite direction in a future PR.
For trait methods, it seems that using `<dyn Trait>::method(...)` is pretty universal, although it's not super pretty. Should we include some heuristic that checks whether it can be replaced by something simpler, for example `Trait::method(...)` or `T::method(...)` for generic types?
Fixes first part of https://github.com/intellij-rust/intellij-rust/issues/4451.
=> INT: convert method call to UFCS

src/main/kotlin/org/rust/ide/inspections/RsLivenessInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveParameterFix.kt, src/test/kotlin/org/rust/ide/inspections/RsLivenessInspectionTest.kt
This PR adds a quick fix to remove an unused parameter, along with its usages in call sites. The call site arguments are removed without any checks for side effects, same as in the Kotlin plugin.
Should we ignore call sites with an incorrect number of arguments?
This PR is based on https://github.com/intellij-rust/intellij-rust/pull/5557 which introduced some common changes. I opened this one for discussion, but #5557 should be merged first, I'll rebase this one after/if it gets merged.
Part of https://github.com/intellij-rust/intellij-rust/pull/3163
=> INSP: add remove parameter quick fix to liveness inspection

src/main/kotlin/org/rust/ide/annotator/fixes/MakePublicFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
This PR fixes the `Make public`  quick fix to support tuple struct fields. Previously it was throwing an exception when used on a tuple struct field, because it was unconditionally casting the element to `RsNameIdentifierOwner`.
=> FIX: support tuple struct fields in MakePublicFix

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
Fixes #2473 (starting with 2020.2)
Fixes #5241 (starting with 2020.2)
Fixes #5598
=> Properly escape types in annotations for 2020.2

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This PR implements more precise tracking of missing/extraneous function arguments as proposed in https://github.com/intellij-rust/intellij-rust/issues/5606.
I think that this kind of highlighting is also more consistent with arguments that have a wrong type, as in that case also only the single argument is highlighted, and not the whole function call.
On top of this more fine-grained annotation we can add new quick fixes:
- fill missing arguments with defaults
- remove extraneous argument
- add missing parameter to function declaration
Even though all of them could be implemented even with the old, coarse annotation, I think that with this change the fixes would be easier to use for specific arguments.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5606
=> ANN: use more precise error annotations for missing/extraneous function call arguments

.github/workflows/rust-nightly.yml, build.gradle.kts, scripts/common.py, scripts/get_tag_commit.py, scripts/save_tag.py
The current changes:
* publish nightly builds of toml plugin together with rust plugin
* check if there are changes in repo that can affect particular plugin not to publish the same builds
* disable `buildSearchableOptions` tasks for all non-root gradle projects to speed up publishing. It doesn't affect final builds because result of `buildSearchableOptions` task of non-root gradle project is not included in final build
=> CI: release nightly toml from github actions

build.gradle.kts
Since we moved release actions to python scripts and in CI, they are not used anymore
=> GRD: drop release code from build.gradle.kts

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMemberSelectionPanel.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt, src/main/kotlin/org/rust/openapiext/ui.kt, src/main/resources/META-INF/rust-core.xml
Initial version of move refactoring for top-level items (#3531). Refactoring is activated by pressing F6, then dialog is shown where user selects items to move:
Current implementation just moves items, actual work (e.g. updating references) will be added in following pull requests
=> REF: Basic version of move top-level items refactoring

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
This PR changes the rendered output of local variables in quick documentation to include type aliases.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4365
=> QDOC: render aliased types for let bindings

src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt, src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt, src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt
I just took a look at Java's `IntroduceVariableIntentionAction` and found that our intention works incorrectly.
The intention should be available in fewer places than the refactoring.
Particularly, it should be available in free exprs like:
`2 + 2;` => `let i = 2 + 2;`.
It should never display expression chooser or work with selection (like the refactoring does)
=> INT: fix `Introduce Variable` intention

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
Previously we had cyclic dependencies between stdlib crates like `std -> core -> std -> core`.
This was a bug in our internal project model. Looks like it was not affected our users anyhow.
I fix it because stdlib dependencies stop us from doing topological sort of crates that in turn is needed for the new name resolution engine.
Also, I removed ancient stdlib parts.
=> Fix cyclic stdlib dependencies

src/main/kotlin/org/rust/lang/core/types/borrowck/MoveData.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Fixes #5394
* Check if path relates to union properly
* Consider field paths as precise
=> Fix move analysis of path assignments

src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt
Don't use `isValidProjectMember` if a single module found
=> PERF: slightly optimize `RsModulesIndex`

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt
`DepKind` is needed to distinguish `[dependencies]`, `[dev-dependencies]` (for tests) and `[build-dependencies]` (for `build.rs`)
=> Parse `DepKind` from `cargo metadata`

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherIntegrationTest.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt
Fixes #5621
For some reason, Cargo bumps modification time of Cargo.toml of `openid 0.4.0` dependency on each (not applied to other crates!) `cargo metadata` invocation. Let's ignore changes in `Cargo.toml`/`Cargo.lock` outside of a workspace
=> Fix infinite cargo refresh on openid 0.4.0

src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt
Fixed #5682
Bug introduced by https://github.com/intellij-rust/intellij-rust/pull/5506/commits/c24e3fb404811087cec9c308e2375df1cfc32928
=> Fix `AnnotationHolderImpl` not running in context

src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt, src/test/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntentionTest.kt
Since Rust now supports it, this PR modifies `ExtractInlineModuleIntention` to work for non-root module files. It also adds a test that checks that an existing module file is not overwritten.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4878
=> INT: allow extracting non-root modules in ExtractInlineModuleIntention

src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt, src/test/kotlin/org/rust/ide/docs/RsCodeHighlightingInQuickDocumentationTest.kt
* properly handle single `#` lines
* don't take into account spaces before `#`
Fixes #5631
=> QDOC: fix some corner cases in doc rendered

.github/workflows/release-branch.yml, .github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml
Did the same thing as I implemented in #5649 but for beta and stable builds
Also, fix the case when the latest meaningful commit modifies github workflow. Previously, it leads to fail of `save-commit` job because token generated for github workflow run by default doesn't have permissions to modify workflow files (including creation of tag for existent commit with workflow modification).
To avoid errors in such cases, our script should use custom github token with the corresponding (workflow) permissions
=> CI: release beta and stable toml builds from GitHub workflow

src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
Some Arch Linux users [install `rustup` from repositories](https://wiki.archlinux.org/index.php/rust#Arch_Linux_package) (instead of `curl sh.rustup.rs`). In that case toolchain location is `/usr/bin`, but binaries installed by `cargo install` will be in `~/.cargo/bin`. So we have to manually check `~/.cargo/bin` when searching for `evcxr` or `grcov` binaries
Fixes #5316
=> CARGO: Fix finding location of evcxr and grcov on arch linux

.github/workflows/check.yml, .travis.yml, appveyor.yml, coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt, coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt, src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
Fixes `Run with Coverage` on the latest versions of the plugin.
Also adds tests for the Coverage runner.
NB: For now, `cargo test` with coverage doesn't work on Windows if MSVC toolchain is used (https://github.com/mozilla/grcov/issues/462)
=> RUN: Fix environment variables for Coverage runner

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt
We have a minimal supported Rust toolchain version. Today it is `1.32.0` (but I want to bump it to `1.39.0` in #5690). An older toolchain can lead to random bugs, or the plugin can be totally unusable. For now, we don't notify a user about outdated toolchain. I propose such notification:
=> Notify user about unsupported toolchain version

src/main/kotlin/org/rust/cargo/toolchain/RustcMessage.kt
<details>
```
java.lang.IndexOutOfBoundsException: Wrong line: -1. Available lines count: 0
at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:198)
at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:179)
at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:996)
at org.rust.cargo.toolchain.RustcSpan$Companion.toOffset(RustcMessage.kt:99)
at org.rust.cargo.toolchain.RustcSpan.toTextRange(RustcMessage.kt:84)
at org.rust.ide.annotator.RsExternalLinterFilteredMessage$Companion.filterMessage(RsExternalLinterUtils.kt:242)
at org.rust.ide.annotator.RsExternalLinterUtilsKt.createAnnotationsForFile(RsExternalLinterUtils.kt:178)
at …
```
=> ANN: Fix exception with invalid rustc annotation

idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt, src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
Part of #4147
When creating a Rust project in CLion and other IDEs except IDEA, `RsDirectoryProjectGenerator#generateProject` is called on EDT without write action. Now `cargo init` is wrapped into `computeWithCancelableProgress` in this case.
When creating a Rust project in IDEA, `RsModuleBuilder#setupRootModel` is called on EDT under write action. This case should be handled somehow in the future, but so far it still causes the exception.
=> Fix `Synchronous execution on EDT` when creating new project (except IDEA)

toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt, toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
Fixes #5467. Fixes #5411.
Manages version modification to be compatable with docs.rs and fixes urls for crates with dashes.
Not sure how incorrect versions should be managed, with other issues of #5440 this could be improved.
=> TOML: Fix Cargo.toml dependencies docs urls

build.gradle.kts, src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt, src/main/resources-stable/META-INF/experiments.xml
Finally, new macro expansion is enabled by default!
Also, I think we need to mark this new epoch of the plugin with increasing of the major version to 0.3
Closes #3628
Fixes #955
Fixes #2128
Fixes #2383
Fixes #2625
Fixes #2787
Fixes #2902
Fixes #3006
Fixes #3087
Fixes #3155
Fixes #3238
Fixes #3259
Fixes #3468
Fixes #3487
Fixes #3560
Fixes #3587
Fixes #3590
Fixes #4063
Fixes #4153
Fixes #4224
Fixes #4310
Fixes #4328
Fixes #4340
Fixes #4519
Fixes #4627
Fixes #4826
Fixes #5088
Fixes #5127
Fixes #5154
Fixes #5248
Fixes #5278
Fixes #5300
Fixes #5346
Fixes #5461
Fixes #5686
=> Enable new macro expansion engine

src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/main/resources/META-INF/rust-core.xml
Add registry option to disable macro highlighting (introduced in #4640)
=> Add registry option to disable macro highlighting

src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveCacheTest.kt
Fixes possible `PsiInvalidAccessException` and wrong name resolution in some cases
=> Fix cache invalidation when editing function-local macro

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestConsoleProperties.kt
This PR uses `printExpectedActualHeader` to use `Left` and `Right` strings for test assertion differences, instead of `Actual` and `Expected`. The order and text is still incorrect when the diff is opened, but at least now the initial text is correct.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/3814
=> RUN: add custom text for assert test diff

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
This PR changes keyword completion so that `return` and `let` are not offered directly inside struct literals and struct pats.
Fixes first part of https://github.com/intellij-rust/intellij-rust/issues/4448
=> COMP: do not offer let and return inside struct literals and pats

src/main/kotlin/org/rust/ide/annotator/fixes/ConvertLetDeclTypeFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ConvertLetDeclTypeFixTest.kt
This PR adds a very simple quick fix that changes the type of a `let` declaration.
Umbrella issue: https://github.com/intellij-rust/intellij-rust/issues/1730
=> ANN: add quick fix to change local variable type

src/main/kotlin/org/rust/cargo/project/model/RsGeneratedSourcesFilter.kt, src/main/kotlin/org/rust/ide/navigation/goto/RsTargetElementEvaluator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoSuperHandlerTest.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt
Fix `go to type declaration` action (`Ctrl + Shift + B`) for macro-generated items.
Works for this case:
```rust
macro_rules! as_is { ($($ t:tt)*) => { $($ t)* }; }
as_is! { struct /*caret_after*/S; }
fn main() {
let /*caret_before*/a = S;
}
```
I used PsiElement.getNavigationElement() because it specially designed to get some "real" PSI from "fake" (macro-generated) PSI
=> Fix `go to type declaration` for macro-generated items

src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
https://github.com/intellij-rust/intellij-rust/pull/5521 fixed `AddUnsafeFix` to work with conditions and loops, but it added `unsafe` to the enclosing function in such cases, which is a bit too pessimistic.
This PR changes it to find the closest enclosing block.
=> INSP: improve AddUnsafeFix to find the closest enclosing block

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTest.kt, src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTestBase.kt, src/test/kotlin/org/rustSlowTests/RsCompilerSourcesLazyBlockStubCreationTest.kt
* handle `raw const` operator  and not to create stubs in this case
* extract common code of the corresponding tests into `RsLazyBlockStubCreationTestBase`
=> STUB: improve block stub creation

gradle-202.properties, gradle.properties
=> GRD: make 2020.2 default platform for development

gradle-202.properties, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
The Rust plugin is still not unloadable, but it doesn't crash at least.
Under the hood: `registerIndexableSet` isn't needed on the latest EAP, `IndexableSetContributor` is enough.
Part of #4832
=> Fix crash during the plugin unloading on 2020.2

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt
=> RES: properly handle `crate::macro_name!` calls while name resolution

intellij-toml/src/main/kotlin/org/toml/ide/formatter/TomlFmtBlock.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/TomlFmtContext.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/TomlFormattingModelBuilder.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/impl/indent.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/impl/spacing.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/impl/utils.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/settings/TomlCodeStyleSettings.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/settings/TomlCodeStyleSettingsProvider.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/settings/TomlLanguageCodeStyleSettingsProvider.kt, intellij-toml/src/main/kotlin/org/toml/ide/formatter/utils.kt, intellij-toml/src/main/resources/META-INF/plugin.xml, intellij-toml/src/test/kotlin/org/toml/TomlTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/formatter/TomlAutoIndentTest.kt, intellij-toml/src/test/kotlin/org/toml/ide/formatter/TomlFormatterTest.kt, intellij-toml/src/test/kotlin/org/toml/ide/formatter/TomlFormatterTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/typing/TomlTypingTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/wordSelection/TomlSelectionHandlerTestBase.kt, intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt, intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlPsiFactoryTest.kt
This PR implements an initial formatter for TOML. I copied the Rust formatter and stripped it down to only keep things that were required to implement basic spacing formatting.
The [official repository](https://github.com/toml-lang/toml) does not mandate any formatting style and I think that it is a bit inconsistent (space after `[` in outer array, but not in nested array, while for objects it uses spaces after `{` even for nested objects).
There is https://github.com/jumpscale7/python-pretty-toml/blob/master/sample-prettified.toml, but it's also not very specified.
Right now there is only a very basic spacing implementation. Some things are probably OK to enforce (space after `,`, space before and after `=`), but for controversial topics like space after `[`, we should probably introduce …
=> TOML: initial formatter implementation

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
I used another algorithm for group matching inspired by rust-analyzer. It should be more close to rustc's version, I hope.
The new algorithm also speeds up macro expansion a bit.
Fixes #5775
=> MACRO: fix groups substitution

gradle-202.properties
Previous versions of native debugger plugin contain wrong versions of lldb binaries
=> GRD: update native debugger plugin

src/main/kotlin/org/rust/ide/inspections/import/RsImportHelper.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesConflictsDetector.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMovePathHelper.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt, src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/after/lib.rs, src/test/resources/org/rust/ide/refactoring/move/fixtures/grandparent_module_under_reexport/before/lib.rs
Improve updating references to moved file when it is under reexport
We use `RsImportHelper` for finding new paths. Please see comment for `RsMovePathHelper` for detailed description.
---
Some background from #5181:
> Currently move refactoring doesn't work well with reexports (examples are in `RsMoveFileReexportTest`). Main issue is that we replace old paths to moved file with absolute path to new moved file location (`crateRelativePath`). It can cause visibility problems if for example new parent module is private, but grandparent module publicly reexports all items from parent module (I think those kinds of reexports are common in libraries). This issue will be solved in future PRs by using `RsImportHelper` for finding new paths.
=> REF: Support reexports in move single file refactoring

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumVariant.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt
Changes `RsVisible.isPublic` to not use `RsVisible.visible`, and instead just check `RsVisibilityOwner.vis`
This potentially could speed up [`expandedItemsCached`](https://github.com/intellij-rust/intellij-rust/blob/637cdc69ba611a95818516c89d01df527b60b116/src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt#L70) a bit
=> Avoid resolve in `RsVisible.isPublic` for restricted visibility

src/201/resources/META-INF/platform-core.xml, src/202/main/kotlin/org/rust/ide/dynamic/RsDynamicPluginListener.kt, src/202/main/resources/META-INF/platform-core.xml, src/main/resources/META-INF/rust-core.xml
On the 2020.2 platform the Rust plugin can't be loaded again after dynamic unloading (see #4832), so let's disable unloading in order to not confuse our users.
"internal" because the change is not viable for users: the plugin is not actually unloadable today
=> Disallow dynamic plugin unloading

.github/workflows/check.yml
* Use 60 min timeout for `check-plugin` job instead of default value (360 for now)
* Cancel previous jobs on `push` event. Unfortunately, GitHub Actions can't cancel previous runs on the same workflow by default so do it ourselves
=> CI: improve check workflow

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/PackageOrigin.kt, src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/inspections/import/ui.kt, src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/main/kotlin/org/rust/lang/core/crate/Crate.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt
This PackageOrigin kind was very confusing
and buggy because one package may look like
transitive or not from different points of view.
=> Get rid of `PackageOrigin.TRANSITIVE_DEPENDENCY`

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/macros/RsErrorChainMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Fixes resolution of `$crate` from macros came from transitive dependencies
Part of #5714
=> MACRO: resolve `$crate` via hygiene

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Support nightly feature `#![feature(associated_type_bounds)]` ([RFC 2289](https://github.com/rust-lang/rfcs/blob/master/text/2289-associated-type-bounds.md)). 
This enables correct type inference for associated type bounds like this:
```rust
fn foo<T: Iterator<Item: Debug>>(i: T) {
}
```
Related to PRs #4974 and #4478
Part of #4476, also a part of #5714
=> TY: support associated type bounds in paths

src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
This fixes `Pin<&mut impl Future<Output=i32>>` awaiting:
```rust
async fn foo<T: Future<Output=i32>>(p: Pin<&mut T>) {
let a = p.await;
a;
} //^ i32
```
=> TY: fix nested projections normalization

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
No such artifacts anymore:
Now `IntellijRustDollarCrate` is replaced with a crate name prefixed by `::`, e.g. `::foobar`
=> ACT: replace `IntellijRustDollarCrate` with a crate name in `show macro expansion` action

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/intentions/AddImportIntention.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/AddImportIntention/after.rs.template, src/main/resources/intentionDescriptions/AddImportIntention/before.rs.template, src/main/resources/intentionDescriptions/AddImportIntention/description.html, src/test/kotlin/org/rust/ide/intentions/AddImportIntentionTest.kt
This PR adds intention that imports a part of a complex path.
I'm not very sure about the used import machinery, is it correct? I also looked at `ImportContext`, but this has worked so far. Especially joining parts of the path to put into the use statement seems a bit nasty.
A reverse intention (fully qualify a path) could probably also be useful.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4006
=> INT: add Import for intention

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPartialParseCompletionTest.kt
This PR adds `: ` after completed struct field literal if no matching (same name and same type) local binding is found.
There were 2 failing tests (`RsPartialParseCompletionTest#test struct field 1` and `RsPartialParseCompletionTest#test struct field 2`). If I used `foobar:` or `foobar: ` as the target completion, they still failed. I changed them to use `doSingleCompletion`.
Fixes second part of https://github.com/intellij-rust/intellij-rust/issues/4448
=> COMP: add colon after struct literal field if no matching binding is found

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
This PR adds support for inferring try expressions (`<expr>?`) where the type of `<expr>` is not `Result` nor `Option`, but it implements the `core::ops::try::Try` trait. The fast path for results and options is kept in the code.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5731
=> TY: infer Try impl for try expressions

src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt, src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
https://github.com/intellij-rust/intellij-rust/pull/5490 added a quick fix to attach a file to a nearby module. However, for `mod.rs` files it offered only crate root files (`lib.rs`, `main.rs`) and not parent modules. So in this case:
```rust
//- foo/mod.rs
/* nothing to see here */
//- foo/bar/mod.rs
/* caret*/
```
The quick fix wasn't offered at `/*caret*/`.
After this PR, the quick fix is offered and the example code is transformed into this:
```rust
//- foo/mod.rs
mod bar;
//- foo/bar/mod.rs
```
=> INSP: attach module without a parent to a parent module in AttachFileToModuleFix

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
This PR filters out unnecessary completions offered in struct pats.
It also adds `..` to completion, but I'm not sure if that's the right way to do it, so it's in a separate commit.
Fixes third part of https://github.com/intellij-rust/intellij-rust/issues/4448
=> COMP: offer only struct fields in struct pat

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
This PR adds `unsafe` to functions extracted from `unsafe` functions. Currently the `unsafe` is added unconditionally, should I improve that?
The extracted statements would have to be scanned for unsafe operations that are not inside an `unsafe` block. Since pretty much the same code is already in `RsUnsafeExpressionAnnotator`, it should be refactored somehow to share the logic.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5814
=> REF: add unsafe modifier to functions extracted from unsafe functions

src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
`RsWrongTypeArgumentsNumberInspection` previously did not work for trait refs, for example `dyn Trait` or `impl Trait`. This PR adds support for these cases.
TODO:
=> INSP: add support for trait refs in RsWrongTypeArgumentsNumberInspection

src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsStructPatRestCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsStructPatRestCompletionTest.kt
This PR adds completion of `..` in struct patterns, as discussed in https://github.com/intellij-rust/intellij-rust/pull/5660.
Fixes https://github.com/intellij-rust/intellij-rust/issues/4448
=> COMP: offer rest in struct pats

src/main/kotlin/org/rust/ide/inspections/RsNamingInspection.kt, src/test/kotlin/org/rust/ide/inspections/naming/RsFunctionNamingInspectionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4274
=> INSP: suppress snake_case naming lint for #[no_mangle] functions

src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
We don't support negative impls for now (e.g. `impl !Sync for Bar`), but previously we wrongly treated them as usual impls (without `!`). Now just ignore them
Fixes #5575 false-positive because now there is `impl<T: ?Sized> !Clone for &mut T {}` in the stdlib
=> TY: exclude negative impls from type inference

common/src/test/kotlin/com/intellij/ide/annotator/AnnotationTestFixtureBase.kt, common/src/test/kotlin/com/intellij/ide/annotator/BatchMode.kt, common/src/test/kotlin/com/intellij/utils.kt, grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt, intellij-toml/src/main/kotlin/org/toml/ide/annotator/TomlHighlightingAnnotator.kt, intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotationTestFixture.kt, intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlAnnotatorTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/annotator/TomlHighlightingAnnotatorTest.kt, src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestFixture.kt, src/test/kotlin/org/rust/ide/annotator/RsAnnotatorTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt, src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/inspections/RsInspectionsTestBase.kt, src/test/kotlin/org/rust/ide/inspections/RsMultipleInspectionsTestBase.kt
It prevents empty items in `Inspection Result` tool window
Also, improve highlighting tests of 2018 edition keywords and format string literal
Fixes #3034
Fixes #5776
=> Don't provide color highlighting in batch mode

src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt
`ImmediateConfigurable` has `cases` property to provide info about options of particular hints provider.
It allows us to use a more declarative way to provide necessary options and avoid custom UI creation
As a result, settings UI has the same layout as other options
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/88392299-692c0c80-cdc4-11ea-9f33-9ac739bfd43e.png) | ![image](https://user-images.githubusercontent.com/2539310/88392198-4699f380-cdc4-11ea-87d3-2faf53442d0c.png) |
=> Don't create checkboxes in inlay hint settings manually

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Previously, `foo?` expr was sometimes inferred to `<unknown>` type even if `foo` is fully inferred as `Result<...>` or `Option<...>`.
This works for
```rust
let a = vec![Some(42)].into_iter().next()??;
```
=> TY: fix `?` try expr for complex types

CONTRIBUTORS.txt, src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
w: intellij-rust/src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt: (142, 13): Condition 'workspaceRoot == null' is always 'false'
=> [CARGO] Silence always-false condition warning

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
E.g. correctly infer `B` from `A: Foo` in this case:
```rust
trait Foo {
type Item;
}
fn foo<A, B>(a: A) -> B
where A: Foo<Item = B>
```
Fixes #4505 type inference for `Iterator.cloned()`
=> TY: infer type parameters from assoc type bindings

src/main/kotlin/org/rust/ide/spelling/RsNameIdentifierOwnerTokenizer.kt, src/test/kotlin/org/rust/ide/spellchecker/RsSpellCheckerTest.kt
These changes fix text extraction from lifetime identifiers for spell checking and fix false-positive typo annotations in lifetimes like `'static`
Fixes #5551
=> Properly check spelling in lifetimes

src/main/kotlin/org/rust/cargo/runconfig/filters/FilterUtils.kt, src/main/kotlin/org/rust/cargo/runconfig/filters/RegexpFileLinkFilter.kt, src/main/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilter.kt, src/main/kotlin/org/rust/ide/console/RsConsoleFolding.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/console/RsConsoleFoldingTest.kt, src/test/kotlin/org/rust/ide/console/RsConsoleFoldingTestBase.kt
This PR adds folding for non-project related stacktraces:
The implementation needs some refactoring, I first wanted to do a sanity check if you think that this approach is valid.
The console folder is a non-dynamic extension, is there a dynamic alternative?
Related issue: https://github.com/intellij-rust/intellij-rust/issues/4514
=> RUN: fold external stack traces

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
Name resolution filters items by their visibility, however in the case of the mentioned issue, it is too late. Trait methods are filtered too deeply if an inherent method exists with the same name.
This PR changes it so that inherent methods are not preferred if they are not visible, thus fixing the previously given false positive.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/3436
=> COMP: prefer trait methods before private inherent methods

src/main/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/after.rs.template, src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/before.rs.template, src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/description.html, src/test/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntentionTest.kt
This PR adds an intention to substitute an associated type with its value.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/2766
=> INT: add intention to substitute an associated type

src/main/kotlin/org/rust/ide/refactoring/extraxtExpressionUtils.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
This PR modifies `findOccurrences` in `extraxtExpressionUtils.kt` so that it can find a corresponding context even if the extracted item is outside a function.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5844
=> REF: find occurrences for introduce constant/variable outside functions

src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHintsProviderTest.kt
If `Show only smart hints` option is enabled, don't show parameter hints for lambda argument if it is the only argument of the function.
This works for `Iterator.map()` method, i.e. no such artifacts anymore:
=> HINT: don't show a hint for single lambda param

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMovePathHelper.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt
Update references in [move items refactoring](https://github.com/intellij-rust/intellij-rust/issues/3531#issuecomment-643142894):
* Inside references (to moved items - both from old mod and from other mods)
* Outside references (from moved items - both to old mod and to other mods)
---
Please see comment for `RsMoveCommonProcessor` for detailed description
I will add tests later (after merging #5665), but anyway all existing tests can be found [here](https://github.com/intellij-rust/intellij-rust/blob/diralik/move/src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt)
=> REF: Update references in move items refactoring

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Fixes this exception:
<details>
```
java.lang.NoSuchMethodError: 'void com.intellij.util.io.PathKt.createFile(java.nio.file.Path)'
at org.rust.lang.core.macros.MacroExpansionManager$Companion.invalidateCaches(MacroExpansionManager.kt:92)
at org.rust.lang.core.macros.RsMacroExpansionCachesInvalidator.invalidateCaches(RsMacroExpansionCachesInvalidator.kt:13)
at com.intellij.ide.actions.InvalidateCachesAction.actionPerformed(InvalidateCachesAction.java:91)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:311)
at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281) …
```
=> Fix `invalidate caches / restart` on 203

src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/parser/util.kt
Possibly fixes this exception during macro completion:
<details>
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 256
at gnu.trove.TIntArrayList.get(TIntArrayList.java:234)
at com.intellij.lang.impl.MarkerProduction.getStartMarkerAt(MarkerProduction.java:122)
at com.intellij.lang.impl.PsiBuilderImpl.error(PsiBuilderImpl.java:889)
at com.intellij.lang.impl.PsiBuilderAdapter.error(PsiBuilderAdapter.java:100)
at com.intellij.lang.parser.GeneratedParserUtilBase.reportError(GeneratedParserUtilBase.java:807)
at com.intellij.lang.parser.GeneratedParserUtilBase.reportFrameError(GeneratedParserUtilBase.java:825)
at com.intellij.lang.parser.GeneratedParserUtilBase.enter_section_(GeneratedParserUtilBase.java:462)
at …
```
=> Fix ArrayIndexOutOfBoundsException in macro completion

src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt, src/main/kotlin/org/rust/ide/navigation/goto/RsImplsSearch.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsLineMarkerProviderTestBase.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsMethodLineSeparatorProviderTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProviderTest.kt
This is a revival of an old PR by @kumbayo (https://github.com/intellij-rust/intellij-rust/pull/2163), which allows navigation from functions/constants/associated types to their corresponding implementations.
The corresponding implementation place is rendered as `<Trait for Type>::function`.
Closes: https://github.com/intellij-rust/intellij-rust/pull/2163
Fixes: https://github.com/intellij-rust/intellij-rust/issues/2122
Part of: https://github.com/intellij-rust/intellij-rust/issues/2849
=> NAV: allow navigation from RsAbstractable to its implementations

src/main/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
This PR adds a quick fix that adds missing type arguments to generic argument lists that are missing some required (non-defaulted) parameters. In a follow-up PR I'll improve the quick fix to also include associated types.
- Should the parameters be filled with `_` or the type parameter names from the resolved type (i.e. `K`, `V` in a hash map)? The first one should play better with inference, the latter provides more guidance to the user on what to use for the actual type arguments (although the type parameter names are often very short and lack context). Right now the implementation uses the latter.
=> INSP: add AddTypeArguments quick fix to RsWrongTypeArgumentsNumberInspection

idea/src/main/kotlin/org/rust/ide/idea/CargoConfigurationWizardStep.kt, idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt, src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt, src/main/kotlin/org/rust/ide/newProject/ConfigurationData.kt, src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt, src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt, src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt, src/main/kotlin/org/rust/ide/newProject/Utils.kt, src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt, src/main/kotlin/org/rust/ide/ui/layout.kt
Currently, it is project generation using cargo-generate merged with standard cargo templates.
Additionally:
Closes #5746
=> PRJ: Project generation with cargo-generate

src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt, src/test/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProviderTest.kt
This PR changes the special case for iterators in `RsChainMethodTypeHintsProvider`. Now the top-level type of something that implements `Iterator` is changed to `impl Iterator` so that consecutive special.cased iterator types can be folded. Before only the rendering was changed, so consecutive types were not properly folded if they implemented the same `Iterator<Item=X>`.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5433
=> HINT: allow comparison of consecutive iterator special case types in chain method hints

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt
When a user types `(` while completion, platform `com.intellij.codeInsight.completion.DefaultCharFilter` invokes completion with selected item.
And if the plugin inserts `()` for the item (for example, function), a user gets double parentheses.
These changes disable insertion of typed `(` in described cases
Fixes #5783
=> COMP: don't insert double parentheses

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsConstNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsModuleNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTraitNamingInspectionTest.kt
It's new name for `bad_style` attribute
Related to #5888
=> INSP: support `nonstandard_style` attribute for naming inspections

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsWhileTrueLoopInspection.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/inspections/lints/RsWhileTrueLoopInspectionTest.kt
After this change, the plugin will be able to provide all features described in #5888 for "while true" inspection, i.e. automatic suppression by `#[allow(while_true)]` and suppression quick fixes
Depends on #5889
Part of #5888
=> INSP: convert while true inspection into lint one

.idea/dictionaries/intellij_rust.xml, src/main/kotlin/org/rust/cargo/runconfig/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt, src/main/kotlin/org/rust/cargo/runconfig/ui/WorkingDirectoryComponent.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfigurationType.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunState.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunStateBase.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/ui/WasmPackCommandConfigurationEditor.kt, src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/RustToolchain.kt, src/main/kotlin/org/rust/cargo/toolchain/WasmPack.kt, src/main/resources/META-INF/rust-core.xml
wasm-pack is a tool that provides building and bundling WebAssembly binary generated by Cargo and wasm-bindgen. It gives developers the ability to seamlessly interop between Rust and JS code.
This request aims to provide an option to run wasm-pack commands as run configuration.
Currently, it supports basic command execution within Run Configurations and installation if it doesn't exist in the system.
=> RUN: Implement wasm-pack run configuration

src/main/kotlin/org/rust/ide/newProject/state/RsUserTemplatesState.kt, src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt, src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt, src/main/resources/META-INF/rust-core.xml
Provides support for persistent user templates URLs in the New Project wizard.
Depends on #5715
=> PRJ: Project generation with custom user templates

src/main/kotlin/org/rust/ide/actions/runAnything/CargoRunAnythingProvider.kt, src/test/kotlin/org/rust/ide/actions/runAnything/CargoRunAnythingProviderTest.kt
=> RUN: Add autocompletion for partial `cargo` word in Run Anything

src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt
`PsiFileFactory.createFileFromText` returns `PsiPlainTextFile` instead of `RsFile` if expanded text is too large, which may lead to `ClassCastException`
=> MACRO: Fix potential exception when expanded text is too large

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedTypeAlias.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
A set of name resolution/type inference optimizations. I measured about 10% highlighting speedup.
1. Get rid of some `getContext()` invocations. `getContext()` is slower than `getParent()`
2. Invoke `mod.super` lazy. 
3. Optimize `RsExpandedElement.getContextImpl`. `getContextImpl` is very hot. Ridding of extra `stubParent` call should slightly speed it up.
4. use `CachedValueImpl` in `RsCachedImplItem`. `CachedValueImpl` seems more lightweight and faster than `RsResolveCache`. Use it in very hot `RsCachedImplItem.forImpl` method.
5. Introduce `RsCachedTypeAlias`. It's used the same way as `RsCachedImplItem`. Such optimization become reasonable after #4936.
=> PERF: set of name resolution optimizations

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
Implements `suggestedName()` for `CargoCommandConfiguration` to provide a configuration name suggestion.
Currently, it is just capitalized cargo command. I'm not sure if we need to add anything else there.
=> RUN: Suggest configuration name from command

idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfigurationType.kt, src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt, src/main/kotlin/org/rust/ide/newProject/RsProjectTemplate.kt, src/main/kotlin/org/rust/ide/newProject/Utils.kt, src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
Makes default run configurations for projects when generating from built-in templates.
Uses these commands:
* `cargo run` for binary
* `cargo test` for library
* `wasm-pack build` for WebAssembly
=> PRJ: Create default run configuration after project generation

.github/workflows/release-branch.yml, scripts/check_release_branch_date.py
These changes add cron trigger for `release-branch.yml` to create release branch on a schedule.
The implementation looks at next milestone each day and if there are less than 7 days before new release, it creates new release branch from master
=> CI: create a release branch on a schedule from CI

src/main/kotlin/org/rust/ide/newProject/RsPackageNameValidator.kt, src/test/kotlin/org/rust/ide/newProject/RsProjectNameValidationTest.kt
Cargo's package name validation has changed since it was initially implemented in the plugin. This PR updates the validation to the current Cargo implementation.
* Update keywords and binary blacklists
* Check if the name is Windows reserved
=> Update package name validation during new project creation

src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt, src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
This PR adds a simple heuristic to `AttachFileToModuleFix` that tries to find a good place where to insert the `mod` item. If it finds an existing mod items in the file, it will append the new item after the last one. Otherwise, it will skip comments and attributes at the beginning of the module.
If there was a mod item before an attribute in the target module, it could still fail to compile after the fix, but in such case it would also fail to compile before the fix, so I think that is an edge case that we don't have to deal with.
I copied the `firstItem` implementation and changed it slightly so that it also works for empty modules. I can also check if the module is empty and do not use `firstItem` in such case.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5903
Fixes: …
=> INSP: select a better location for attaching file to modules

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt
Now any modifications of project settings don't change content roots.
It allows avoiding exceptions like this:
<details><summary>stacktrace</summary>
```stacktrace
CompositeException (2 nested):
------------------------------
[0]: null
[1]: Virtual pointer 'temp:///src/src' hasn't been disposed: --------------Creation trace: 
java.lang.Throwable
at com.intellij.openapi.util.TraceableDisposable.<init>(TraceableDisposable.java:31)
at com.intellij.openapi.vfs.impl.VirtualFilePointerImpl.<init>(VirtualFilePointerImpl.java:40)
at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.getOrCreate(VirtualFilePointerManagerImpl.java:340)
at com.intellij.openapi.vfs.impl.VirtualFilePointerManagerImpl.create(VirtualFilePointerManagerImpl.java:219)
at …
```
=> T: improve light tests

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Support reexports in [move items refactoring](https://github.com/intellij-rust/intellij-rust/issues/3531#issuecomment-643142894). Reexports are handled using `RsMovePathHelper` (introduced in #5484)
---
=> REF: Support reexports in move items refactoring

.github/workflows/regressions.yml, build.gradle.kts, gradle.properties, scripts/calculate_regressions.py, src/test/kotlin/org/rustPerformanceTests/CustomRealProjectAnalysisTest.kt, src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Currently, each developer can launch `org.rustPerformanceTests.RsRealProjectAnalysisTest` to analyze if they introduce some new false-positive errors. It works somehow but has a lot of cons:
- a developer may forget to launch regression tests
- these tests should be launched locally that consumes CPU and a lot of time
- there no way to get diff between the previous set of errors and the current one. It's important since the plugin produces some false positives (unfortunately) and you have to compare previous results with new ones manually
This PR introduces new `regressions` GitHub workflow that should automate the launch of regression tests and help us to identify regressions earlier. This implementation includes:
- new `CustomRealProjectAnalysisTest`. It can be configured via set of …
=> CI: initial regression testing

src/main/kotlin/org/rust/lang/core/resolve/RsCachedTypeAlias.kt
The bug was introduced in #5926. I used `alias.getOwner` incorrectly =(
<details>
```
java.lang.IllegalStateException: unreachable
at org.rust.lang.core.resolve.RsCachedTypeAlias$isFreeAndValid$2.invoke(RsCachedTypeAlias.kt:57)
at org.rust.lang.core.resolve.RsCachedTypeAlias$isFreeAndValid$2.invoke(RsCachedTypeAlias.kt:24)
at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
at org.rust.lang.core.resolve.RsCachedTypeAlias.isFreeAndValid(RsCachedTypeAlias.kt)
at org.rust.lang.core.resolve.indexes.RsTypeAliasIndex$Companion.findPotentialAliases(RsTypeAliasIndex.kt:40)
at org.rust.lang.core.resolve.ImplLookup.processTyFingerprintsWithAliases(ImplLookup.kt:490)
at org.rust.lang.core.resolve.ImplLookup.assembleImplCandidates(ImplLookup.kt:675)
at …
```
=> Fix "unreachable" exception

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Changes order in which macros are processed: macros from imports first, then macros from crate root scope
=> RES: Macro from local import should shadow macro from crate root

src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt
Fixes #5957
By default, cargo-generate convert project names with underscores to names with hyphens. This behavior can be disabled with `--force` flag, therefore it should present in the `generate` command invocation when creating a new project.
=> PRJ: Force cargo-generate to skip name conversion

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
Fixes this exception:
<details>
```
kotlin.UninitializedPropertyAccessException: lateinit property processHandler has not been initialized
at org.rust.cargo.runconfig.buildtool.CargoBuildContext.getProcessHandler(CargoBuildContext.kt:43)
at org.rust.cargo.runconfig.buildtool.CargoBuildManager$execute$1$1.run(CargoBuildManager.kt:148)
at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170) …
```
=> RUN: Fix exception on build cancel

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTestBase.kt
Checks that target of any reference remains accessible after move (in [move items refactoring](https://github.com/intellij-rust/intellij-rust/issues/3531#issuecomment-643142894)) and otherwise shows warning dialog. These cases are checked:
- `RsPath`
- struct/enum field (plain access / struct literal / destructuring)
- struct/trait method call
=> REF: Check visibility conflicts in move top-level items refactoring

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
This PR modifies `RsFormatMacroAnnotator` to ignore format string arguments that are not string literals.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5994
=> ANN: ignore string format parameters that are not string literals

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Previously, the plugin shows it when you call trait method via UFCS, trait name was not in the scope and trait is used via a qualified path
Fixes #5965
=> INSP: fix false positive unresolved reference error

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt, src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsSelectionTest.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTestBase.kt
Use selected in the editor items as initial items to move.
Also we now always use Move Items when refactoring is performed from editor (previously we used Move File if refactoring is performed from editor and cursor is at empty line). Most other languages has same behaviour (Kotlin, C++, JavaScript).
=> REF: Handle selection in move top-level items refactoring

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
This is a king of performance fix - don't expand macros that aren't needed (similar to #5989). Previously the new macro expansion engine was (unintentionally) expand macros in constants & statics (that are stubbed).
=> MACRO: don't use new expansion engine for non top-level macros

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
https://github.com/rust-lang/rust uses `build` directory instead of `target`. So let's exclude `build` as well as `target`
=> Exclude "build" dir from index in rustc project

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
Expected user-visible change is additional roots of stdlib. `core_arch` and `std_detect` on stable and additionally `backtrace` on nightly. Also, now navigation actions like `Select Opened File` in Project view should properly navigate you if you open any file from described directories of stdlib
=> Index `stdarch` & `backtrace` stdlib parts

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/inlineFunction/ui.kt, src/main/kotlin/org/rust/ide/refactoring/inlineUtils.kt, src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueHandler.kt, src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/inlineValue/ui.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt
This PR adds support for inlining variables and constants. Right now the original variable is inlined and removed. If it does not have any usages, an error is reported. In Kotlin, there is an additional dialog that asks if the original expression should be kept or not, should I also include it here?
I wasn't sure which test infrastructure to use as it's not a classic refactoring, so I added some manual test functions, but it's not a lot of code.
~Functions could also be inlined, should that be handled inside this refactoring?~
Fixes: https://github.com/intellij-rust/intellij-rust/issues/1095
=> REF: add inline value refactoring

idea/src/main/kotlin/org/rust/ide/idea/RsModuleBuilder.kt, src/main/kotlin/org/rust/cargo/toolchain/Cargo.kt, src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt, src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt, src/main/kotlin/org/rust/ide/newProject/Utils.kt
Related to #5922
Fixes the first part of the issue. Now cargo package name for a new project will be actually the project name and not the root dir.
Also, fixes the problem of generating projects with custom templates when the project name and the root dir are different.
=> PRJ: Use project name instead of root dir in IDEA when generating project

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt, src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt
This PR adds a quick fix to `RsUnresolvedReferenceInspection` which creates a new function for unresolved function call. I took inspiration from a similar quick fix present in the IntelliJ Kotlin plugin.
It also copies over generic parameters of the call parameters and their bounds:
Currently, the fix is offered only on function calls (not method calls) to avoid potential false positives for methods generated by procedural macros. The fix is also only offered if the parent module of the path exists (i.e. for `a::b::function`, `a::b` must resolve to an existing module) and is part of the workspace (so that it won't try to create a function in `stdlib`).
There are several things left to resolve:
1) When the function is created in a different module, it will need to be visible from the …
=> INT: add intention to create a function from an unresolved function call

src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsNamedFieldDecl.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTupleFieldDecl.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
These changes fixes documentation rendering for fields of enum variant and macro 2.0.
Fixes #5984
=> QDOC: improve documentation rendering

src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Fixes name resolution of nested modules in modules
liked to a project with path attributes from
another directories, e.g.
```rust
#[path = "../foo/foo.rs"]
mod foo;
```
Closes #5917
=> RES: fix mod path attributes to another dirs

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
With #5929, fixes #5922.
When the root is not a package (e.g. with [virtual manifest](https://doc.rust-lang.org/cargo/reference/workspaces.html)), falls back to root directory name.
=> CARGO: Use package name for cargo project if possible

src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStaticConstNamingInspectionTest.kt
=> INSP: don't apply RsStaticConstNamingInspection for extern statics

src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt
This also enables automatic project discovery when opening `Cargo.toml` file
=> Show "missing toolchain" notification in Cargo.toml

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
This PR improves the `CreateFunctionIntention` introduced in https://github.com/intellij-rust/intellij-rust/pull/5505 to guess the expected return type of the created function. A lot of edge cases aren't handled (otherwise this could get quite complex), but I think that's fine, as long as the most obvious situations are working.
This functionality was mentioned in https://github.com/intellij-rust/intellij-rust/issues/3904.
=> INT: add support for guessing return type in CreateFunctionIntention

src/main/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntention.kt, src/test/kotlin/org/rust/ide/intentions/SubstituteAssociatedTypeIntentionTest.kt
`SubstituteAssociatedTypeIntention` has also worked for type aliases. It is OK in basic cases, but for generic type aliases (which cannot occur currently for associated types on stable - this is the infamous GAT feature) it doesn't work properly. There are some issues with propagating type arguments and also with handling the alias itself - it's only properly supported for ADTs currently. So for now I think that we should disable this intention for type aliases. 
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6030
=> INT: disable SubstituteAssociatedTypeIntention for type aliases

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/5768.
Fixes https://github.com/intellij-rust/intellij-rust/issues/5703.
Fixes https://github.com/intellij-rust/intellij-rust/issues/5974.
Fixes https://github.com/intellij-rust/intellij-rust/issues/5985.
=> T: Don't unescape test output

src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt
This PR fixes `RsInlineValue` so that it properly supports shorthand field init. Inspired by https://github.com/rust-analyzer/rust-analyzer/pull/5888.
=> REF: handle struct field shorthand init in RsInlineValue

src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt, src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
=> INT: fix FlattenUseStatementsIntention flattens nested `use` statements correctly

src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/GenerateAccessorHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/getter/GenerateGetterHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/setter/GenerateSetterHandler.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateSetterActionTest.kt
This PR adds an action to generate a setter for a struct, mirroring the recently added generate getter action (https://github.com/intellij-rust/intellij-rust/pull/5352).
It also introduces several improvements like better copy type handling, support for type aliases, finding existing impl blocks and navigation to the generated method. Since these are directly applicable to both getters and setters, I included them in this PR, but if you want, I can split them into a separate PR.
Currently, if the action is invoked inside an `impl`, I filter out attributes that would conflict with an existing method:
```rust
struct S { a: u32 }
impl S {
fn a(&self) {}
/*caret*/ <- a is not offered, because `a` method exists
}
```
However, if the action is invoked on the struct, all (non-pub) fields are …
=> REF: generate setter action

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt, src/main/resources/postfixTemplates/DbgrPostfixTemplate/after.rs.template, src/main/resources/postfixTemplates/DbgrPostfixTemplate/before.rs.template, src/main/resources/postfixTemplates/DbgrPostfixTemplate/description.html, src/test/kotlin/org/rust/ide/template/postfix/DbgrPostfixTemplateTest.kt
Hi there!
I think it would be useful to convert a value to a reference right away when using `dbg` postfix completion .
Otherwise, we won't be able to use the value in the next line.
```rust
// Old behaviour:
fn foo(slice: &[i32]) {
let first = slice[0];
dbg!(first);
do_something(first); // It won't work
}
// New behaviour:
fn foo(slice: &[i32]) {
let first = slice[0];
dbg!(&first);
do_something(first); // It will work
}
```
=> COMP: Add `dbgr` postfix completion

.github/workflows/milestones.yml, scripts/check_release_branch_date.py, scripts/github.py, scripts/set_milestone.py
We use milestones to mark pull requests that are included into the corresponding release.
We use it:
- for changelog template creation
- to get our users full list of release changes
- while regression investigation in published release builds
But we have to set milestones manually. As a result, a developer can forget to do it (and it actually happens).
These changes provides new GitHub workflow to set current milestone to each merged PR automatically if it doesn't have it yet
=> CI: set PR milestone automatically

src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt
According to the [cargo docs](https://doc.rust-lang.org/cargo/commands/cargo-check.html) it should have a `--bench` option, which we have with `targetBench()` to use a specific bench target and `--benches` to use all bench targets.
=> RUN: Fix benches flag in cargo command completion

src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
This PR adds a test to all intentions that they have proper description and templates (inspired by a similar test in inspection test base class).
Blocked on https://github.com/intellij-rust/intellij-rust/pull/6050
=> T: add test that intentions have descriptions and templates

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Previously, stdlib macros like `println` were successfully resolved even if `#![no_std]` was present, this PR changes that.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5431
=> RES: do not resolve std macros when no_std is present

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Make moved items public if needed (e.g. they are used in old parent mod) in [move items refactoring](https://github.com/intellij-rust/intellij-rust/issues/3531#issuecomment-643142894).
Also change restricted visibility scope of moved items if needed (common parent mod of old scope and new parent mod is used).
=> REF: Make moved items public if needed

src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Previously, real project tests checked only unresolved reference annotations visible for user by default.
It should help us to detect errors in name resolution/type inference
=> T: highlight all unresolved references in real project tests

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
[`RsImportHelper` can find private path](https://github.com/intellij-rust/intellij-rust/issues/4000), so we have to explicitly check accessibility of such paths
=> REF: Add explicit visibility check in move refactoring

.github/workflows/check.yml
This PR caches `evcxr` so that it is not recompiled in every `check` workflow. This should hopefully reduce the runtime of this workflow on Ubuntu by about 2 minutes (~ 10% of the total runtime).
I also tried to cache the `Download` task, but I'm not sure what does it download. When I cached the `deps` folder, it still took a long time to run the download task (it probably also downloads some gradle stuff?).
=> CI: cache evcxr in check workflow

src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt
* `std` [no longer depends](https://github.com/rust-lang/rust/blob/5a6b426e3471382c0385c11b09c2d6b37f70ac49/library/std/Cargo.toml#L13-L36) on `build_helper` (removed in [this commit](https://github.com/rust-lang/rust/commit/8d500572fa8f4110033fa3bc5e925831f6bbd18e#diff-1a7024d46c31d728a04d5e0cafd98df8L47))
* `proc_macro` [no longer depends](https://github.com/rust-lang/rust/blob/5a6b426e3471382c0385c11b09c2d6b37f70ac49/library/proc_macro/Cargo.toml#L7-L8) on `syntax` (removed in [this commit](https://github.com/rust-lang/rust/commit/8cf463bcffea8b6582fec170841b22ae0d6c77ea#diff-08f7810b7aec61ec35fd3dcb7bb0b8f9L11))
=> Remove build_helper from std dependencies

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
This PR adds support for creatng methods in `CreateFunctionIntention`. Also I previously forget to register the intention and add a description, since it was originally a quick fix, so this PR also fixes that.
=> INT: add support for creating methods in CreateFunctionIntention

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt
This PR attempts to sort methods in completion based on mutability of `self`. If a method call is performed on a const reference or a non-mut binding,`&mut self` methods will be deprioritized.
The implementation needs additional work that I wanted to discuss here. I needed to somehow pass the method call (`RsFieldLookup`) to `ScopedBaseCompletionEntity::getBasePriority` (I didn't know how else to get it from there). `ImplLookup` was already being passed down the completion chain, so I just slapped the element to the lookup, which is not optimal. Is there an easier way of passing down the element? Should I add it to the `RsCompletionContext` and pass it down the completion chain of methods and processors?
The implementation now uses a very simple heuristic for deciding if the method should …
=> COMP: Deprioritize completion of &mut self methods for const references and bindings

.github/workflows/regressions.yml, scripts/calculate_regressions.py
Extends great [regression workflow](https://github.com/intellij-rust/intellij-rust/pull/5932) by showing number of regressions as [github messages](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message), so it will be possible to quickly inspect number of regressions for all crates (cargo, tokio and amethyst) on single page. [Example messages](https://github.com/intellij-rust/intellij-rust/actions/runs/257629920) (for this pull request).
Also:
* Swap order of annotations (`introduced` first, then `fixed`) - I think `introduced annotations` are more useful
* Checkout back to tested commit before calculating regressions, so it will be easier to test changes to `calculate_regressions.py`
=> CI: Show number of regressions as github messages

src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt, src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/SerializationUtils.kt, src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt, src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt, src/main/kotlin/org/rust/ide/formatter/RustfmtExternalFormatProcessor.kt, src/main/kotlin/org/rust/ide/formatter/processors/RsPostFormatProcessor.kt, src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/cargo/RustupTestFixture.kt, src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt, src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt, src/test/kotlin/org/rust/ide/formatter/RsTrailingCommaFormatProcessorTest.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/5191. c.c. #1087
In this implementation, `Rustfmt` can be used **only** when formatting the **whole file** by: 
1. `Code | Reformat Code` (`Ctrl + Alt + L`) action **without text selection**
2. `Code | Reformat File ...` (`Ctrl + Alt + Shift + L`) action with `Whole file` option
E.g. `Rustfmt` can't be used when committing to git with `Reformat code Before Commit` option (it doesn't clear how to achieve this).
By default, the built-in formatter is still ALWAYS used. `Rustfmt` can be enabled in `Settings | Languages & Frameworks | Rust | Rustfmt`.
NB: rustfmt has an unstable option to restrict reformatting to specific sets of lines (https://github.com/rust-lang/rustfmt/issues/3397).
=> FMT: Add an option to use rustfmt instead of build-in formatter

src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt, src/main/kotlin/org/rust/cargo/toolchain/Rustfmt.kt, src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt
This option does nothing for a long time. Finally, get rid of it.
=> Get rid of `Don't reformat child modules` option

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Fix for #5999. Looks like `runAfterOpened` can run outside of EDT.
<details>
```
Access is allowed from event dispatch thread with IW lock only.
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@6d984235
Current thread: Thread[ApplicationImpl pooled thread 11,4,Idea Thread Group] 1697154984
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1894364389
at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1061)
at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1043)
at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(Too …
```
=> Fix exception in the cargo toolwindow init

src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt, src/test/kotlin/org/rust/RsTestBase.kt
RsPath can't be replaced with `RsExpr`. Instead, parent `RsPathExpr` should be replaced.
Typical stacktrace ends with this:
```
java.lang.Throwable: 10
parent=let b = 10;
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:284)
at org.rust.lang.core.psi.impl.RsPathExprImpl.getPath(RsPathExprImpl.java:43)
```
Also, I enhanced tests in order to catch such bugs in the future.
c.c. @Kobzol
=> Fix exception `PsiElementBase.notNullChild` after variable inlining

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
The bug was introduced in #5690
<details>
```
java.lang.Throwable: Incorrect CachedValue use: same CV with different captured context, this can cause unstable results and invalid PSI access.
Field this$0 in class org.rust.lang.core.psi.RsFile$declarations$1 has non-equivalent values:
FILE (org.rust.lang.core.psi.RsFile) and
FILE (org.rust.lang.core.psi.RsFile)
Either make `equals()` hold for these values, or avoid this dependency, e.g. by extracting CV provider into a static method.
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
at com.intellij.util.CachedValueStabilityChecker.complain(CachedValueStabilityChecker.java:163)
at com.intellij.util.CachedValueStabilityChecker.checkFieldEquivalence(CachedValueStabilityChecker.java:130)
at …
```
=> Fix "Incorrect CachedValue use" exception in RsFile

src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt, src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
This PR generalizes the Unelide lifetimes intention to work with generic types.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/769
=> INT: add support for generic types to unelide lifetimes intention

src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt
This PR enhances `TypeRenderer` to render (fully) qualified names for types when needed. This is basically only needed when two types are displayed together to disambiguate them if their name is the same, but they are different types. Two instances of this scenario that I found is in the type mismatch diagnostic and in `ChangeReturnTypeFix`, so I changed both of them to use the qualified name type renderer in this PR.
Fixes https://github.com/intellij-rust/intellij-rust/issues/3223, fixes https://github.com/intellij-rust/intellij-rust/issues/5452.
=> FIX: render types with a fully qualified name when needed

src/main/kotlin/org/rust/ide/inspections/checkMatch/RsNonExhaustiveMatchInspection.kt, src/main/kotlin/org/rust/ide/inspections/checkMatch/RsUnreachablePatternsInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt, src/main/kotlin/org/rust/ide/intentions/AddRemainingArmsIntention.kt, src/main/kotlin/org/rust/ide/intentions/AddWildcardArmIntention.kt, src/main/kotlin/org/rust/ide/utils/checkMatch/CheckMatchUtils.kt, src/main/kotlin/org/rust/ide/utils/checkMatch/Constructor.kt, src/main/kotlin/org/rust/ide/utils/checkMatch/Pattern.kt, src/main/kotlin/org/rust/ide/utils/checkMatch/PatternKind.kt, src/main/kotlin/org/rust/ide/utils/checkMatch/Usefulness.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/AddRemainingArmsIntention/after.rs.template, src/main/resources/intentionDescriptions/AddRemainingArmsIntention/before.rs.template, src/main/resources/intentionDescriptions/AddRemainingArmsIntention/description.html, src/main/resources/intentionDescriptions/AddWildcardArmIntention/after.rs.template, src/main/resources/intentionDescriptions/AddWildcardArmIntention/before.rs.template, src/main/resources/intentionDescriptions/AddWildcardArmIntention/description.html, src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/AddWildcardArmIntentionTest.kt
Restores functionality to add missing patterns in `match` expression inside match block that was removed in #5720. Previously, this feature was provided by `Fill match arms` intention. New intentions work exactly the same as `Add remaining patterns` and `Add _ pattern` but in different places. As a result, new intentions support more cases than old `Fill match arms` which supported only enums and only empty `match` expression
Closes #6124
=> INT: add remaining arms and add wildcard arm intentions

src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt, src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
This will be used in new resolve to improve performance (instead of iterating all items in scope, only item with specified name will be processed).
Potentially it can be used in other places, e.g. in [`processModDeclResolveVariants`](https://github.com/intellij-rust/intellij-rust/blob/e2d8902505475453db2ddc9629b3cd2ec9b68ee9/src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt#L226)
=> RES: Add name to RsResolveProcessor

build.gradle.kts
It allows viewing kotlin stdlib source code with comments.
It was already [added before](https://github.com/intellij-rust/intellij-rust/pull/2312/files), and then [removed](https://github.com/intellij-rust/intellij-rust/pull/2738/files#diff-392475fdf2bc320d17762ed97109a121L135) because it caused problems when running tests using JPS (instead of Gradle). I don't find any problems now when using JPS with this compile only dependency, so let's try add it again.
=> Add compile only dependency on kotlin stdlib

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Improves #3779 & #3856, related to #6146.
1. If there is no `Rustup` in the toolchain, use `$(rustc --print sysroot)/lib/rustlib/src/rust` path to stdlib even if explicit path (in the plugin settings) is set to null
2. In the plugin settings UI, when saving the settings, set explicit stdlib path to null if it equals to `$(rustc --print sysroot)/lib/rustlib/src/rust` (or if there is `Rustup` in the toolchain, as before)
So, if a user doesn't have `Rustup` and doesn't change the stdlib path in the plugin settings, the plugin will **follow** `$(rustc --print sysroot)/lib/rustlib/src/rust` path.
User-visible change: Cargo project structure loading (aka Cargo Refresh) with project opened via `Open` action successfully sets up stdlib path when `rustup` doesn't exist but `$(rustc --print …
=> Follow `rustc --print sysroot` stdlib path without Rustup

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/psi/RsStubElementTypes.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsEnumItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsUseSpeck.kt, src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/stdext/HashCode.kt
Added helper methods for stubs which will be used in new resolve.
Also:
* Added `hasColonColon` flag to `RsUseSpeckStub` to distinguish `use {aaa, bbb};` and `use ::{aaa, bbb};`
* Added `bodyHash` to macro and macro call stubs as an optimization
=> STUB: Add helper methods for new resolve

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
The regression was introduced in #4700.
This can slightly speed up code highlighting after `cargo refresh`.
It's mostly invisible to users, I guess.
bors r+
=> PERF&MACRO: Take heavy process latch only if there are macros to expand

src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Fixes bug introduced in #6166
**Before:**
**After:**
=> UI: move download link to proper place

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
Use `pub` visibility instead of `pub(crate)` when creating function or method in other crate using great [CreateFunctionIntention](https://github.com/intellij-rust/intellij-rust/pull/5505)
=> INT: Use public visibility when creating function in other crate

coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt, coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/5973.
=> RUN: Don't use `-Cpanic=abort` when `Run with Coverage`

src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt
I reckon the scrollbar started to appear after recent UI changes. The scrollbar scrolls to nothing, but taking too much space and focus on the right of the form in default non-resizable CLion wizard window.
This PR makes templates pane height fixed to 125px which allows to show 4 default template items and 2 user ones if they have any without scrollbar in the pane itself.
| ------- | ----- |
| ![](https://user-images.githubusercontent.com/6342851/94624632-8ea32e00-02bf-11eb-869c-25f5aab64ec2.png) | ![](https://user-images.githubusercontent.com/6342851/94624639-9236b500-02bf-11eb-9155-8084ce0e86aa.png) |
=> UI: Get rid of scrollbar in project creation dialog in CLion

src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt, src/main/kotlin/org/rust/cargo/project/configurable/RsConfigurableBase.kt, src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt, src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
These changes:
* use embedded checkbox label
* use inline text help (comments) instead of Swing tooltips
* use more features of platform UI DSl that allows dropping mutable variables to keep intermediate state, implement `reset`, `isModified` and `apply` methods almost automatically
Also, these changes introduce mutable `RustProjectSettingsService.settingsState` property to make usage of binding related UI DSL methods convenient
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/94463156-30922000-01c5-11eb-9a39-561af7cc76a3.png) | ![image](https://user-images.githubusercontent.com/2539310/94463356-78b14280-01c5-11eb-9790-d0a747839f27.png) |
| ![image](https://user-images.githubusercontent.com/2539310/94463598-dc3b7000-01c5-11eb-8f81-e206242eb611.png) …
=> UI: use recommended guidelines for settings UI

build.gradle.kts, grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt, grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
These changes:
* Fix incorrect proofreading annotations on raw and binary string literals. The bug can be reproduced only in 2020.3
* Properly support domain options (`String literals`, `Comments` and `Documentation`) in `Preferences | Editor | Proofreading | Grammar`
* Provide source code of Grazie plugin while development when `baseIDE` in `gradle.properties` is `idea`. Previously, IDE always shows only class files
=> INSP: improve integration with Grazie plugin

src/test/kotlin/org/rust/cargo/RustupTestFixture.kt
`File#canonicalPath` cannot resolve Windows symlinks properly. So `Path#toRealPath` is used
Yet another attempt to fix tests in #5444
=> T: resolve cargo home symlinks on Windows properly

scripts/calculate_regressions.py, src/test/kotlin/org/rustPerformanceTests/CustomRealProjectAnalysisTest.kt, src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
These changes:
- use 1-based indices for line/column in regression annotation to be compatible with editor UI and `Go to Line/Column` action
- sort regression annotations
=> CI: improve presentation of regression annotations

src/main/kotlin/org/rust/cargo/runconfig/filters/RegexpFileLinkFilter.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/HighlightFilterTestBase.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterCargoTest.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsConsoleFilterTest.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsPanicFilterTest.kt
This PR adds support for resolving source code links to stdlib and crate files in backtraces. Is there a way to test this properly? The Rust toolchain is `null` in tests and the test file system doesn't see absolute paths from the user's `.cargo` and `.rustup` folders.
Fixes part of https://github.com/intellij-rust/intellij-rust/issues/4514
=> RUN: resolve stdlib and Cargo source code hyperlinks in backtrace

src/202/main/kotlin/org/rust/lang/core/macros/compatUtils.kt, src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt, src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionStubsProvider.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt, src/main/kotlin/org/rust/stdext/HashCode.kt, src/main/kotlin/org/rust/stdext/path.kt, src/main/resources/META-INF/rust-core.xml
Introduce persistent (stored on disk, in the real file system) cache for macro expansion text and stubs. The cache is shared between different IDEA projects.
The cache is essential for `name resolution 2.0`, but I measured that it doesn't bring significant performance improvements right now (but uses disk storage), so I decided to disable it by default. It can be enabled via `Registry` option `org.rust.lang.macros.persistentCache`. So, the change doesn't affect users for now.
=> MACRO: introduce shared persistent cache for macro expansion

src/test/kotlin/org/rust/ide/console/RsConsoleFoldingTest.kt
Since today these tests fail on CI for some reason
=> T: disable RsConsoleFoldingTest on CI

intellij-toml/src/main/grammars/TomlParser.bnf, intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.toml, intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.txt
Better TOML parser recovery in the case of broken array literals. Needed for completion inside arrays
=> TOML: recover parser on errors in arrays

build.gradle.kts, gradle-202.properties, gradle-203.properties, src/202/main/kotlin/org/rust/lang/core/resolve/ref/compatUtils.kt, src/203/main/kotlin/org/rust/lang/core/resolve/ref/compatUtils.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsResolveCache.kt
* Updates IDE dependencies for 2020.3 EAPs. Makes plugin compatible with 203.4449 EAPs, e.g. fixes `java.lang.NoSuchMethodError: 'void com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.<init>(int, float, int, gnu.trove.TObjectHashingStrategy)'`
* Update IDE dependencies for 2020.2
Fixes #6225
=> GRD: update IDE dependencies

src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt
Now it's possible to test that an intention is available only in some text range and unavailable outside.
c.c. @Kobzol
=> T: introduce tests for intention scope

src/main/kotlin/org/rust/lang/core/macros/FragmentKind.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
The bug(s) was introduced in #6177 (not released yet)
=> MACRO: fix float literals in macros

intellij-toml/src/main/kotlin/org/toml/ide/TomlBraceMatcher.kt, intellij-toml/src/test/kotlin/org/toml/lang/TomlParserTest.kt, intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.toml, intellij-toml/src/test/resources/org/toml/lang/parse/fixtures/invalid.txt
A continuation of #6202
1. Fix TOML parser tests (was needed to manually register `TomlBraceMatcher` in the parser test)
2. Recover on `key = [invalid, {valid = 2}]` case
=> TOML: improve parser recovery on errors

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectsTree.kt
Today it's possible to run `main` target by doubleclicking `main` using any mouse button (e.g. right mouse button):
Let's allow only the left mouse button
=> Allow only LMB double-click for `targets` in the cargo tool window

src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt
=> UI: `Setup toolchain` action shows Rust settings dialog instead of configurable

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This PR inspects struct pats to check if there are not fields bound multiple times.
Related: https://github.com/intellij-rust/intellij-rust/issues/886
TODO:
=> INSP: check if struct fields are not bound multiple times in struct pats [E0025]

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, prettyPrinters/rust_types.py, pretty_printers_tests/tests/nonzero.rs
The `NonZero` types moved from `core::num` to `core::num::nonzero` in Rust `1.48`, this change makes the regexes compatible with both the old and the new versions.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6200
=> DBG: make NonZero printers compatible with Rust 1.48+

prettyPrinters/gdb_lookup.py, prettyPrinters/gdb_providers.py, prettyPrinters/lldb_lookup.py, prettyPrinters/lldb_providers.py, pretty_printers_tests/tests/hash_map.rs
Fixes https://github.com/intellij-rust/intellij-rust/issues/6198
The corresponding PRs in rustc:
https://github.com/rust-lang/rust/pull/76458
https://github.com/rust-lang/rust/pull/70052
Besides these changes from the upstreamed pretty-printers, I've added `GetTypedefedType` (LLDB) and `strip_typedefs` (GDB) calls to resolve key and value types completely. Without these calls, LLDB doesn't show the actual type and so CLion fails to show the content of key/value pairs.
For example,
with `GetTypedefedType`:
```
(lldb) frame variable hm[0]
((i32, alloc::string::String)) hm[0] = { ... }
```
and without:
```
(lldb) frame variable hm[0]
(T) hm[0] = { ... }
```
**Before merge, test on**:
**Does not work on Windows + MSVC LLDB** due to the lack of native Rust support patches
**After merge**
=> Update HashMap/HashSet pretty-printers to Rust 1.47

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt
Fixes work with https://github.com/rust-lang/rust repo. The bug was introduced in (#5189 not released yet).
The real problem is that we don't take into account real stdlib packages (hence their dependencies and features) in rust-lang/rust. We should fix this later
bors r+
=> Disable checkFeaturesInference

build.gradle.kts
Currently, it's possible to run 2020.2 IDEs with java8 runtime. These changes help to avoid exception while plugin loading.
Fixes https://youtrack.jetbrains.com/issue/CPP-22452
=> GRD: generate code compatible with java 8 runtime

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Currently item is moved together with succeeding whitespace. It creates following problems:
* when moving last item from file, after move source file will have double newline at the end
* when moving non-last item from file, after move target file will have double newline at the end
This pull request fixes it by moving item together with preceding whitespace
=> REF: Improve newline handling in move items refactoring

src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt, src/main/kotlin/org/rust/ide/console/RsConsoleView.kt
Clear [REPL console variables view](https://github.com/intellij-rust/intellij-rust/pull/4998) after `:clear` command (supported by evcxr)
=> REPL: Clear variables view after :clear command

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
Previously, when cargo features was modified (#5189),
inlay hints was not updated, so some old state remained
in en editor
bors r+
=> Refresh inlay hints when modifying cargo features

src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/RustcVersion.kt, src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt
It also fixes stdlib's version string in `External Libraries`:
(`beta.2` instead of just `beta`)`
=> Simplify rustc version parsing

README.md, debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacyBase.kt, debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt, src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Continuation of #5200 and #5535
Restrictions:
* supported IDEs: IDEA Ultimate and RubyMine
* requires [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin for IDEA Ultimate
* only LLDB
* only Rust MSVC toolchain
* debugger is not bundled and has to be downloaded. Also, debugger binaries should be updated after IDE/[Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin update
See #5632 for details about the status of MSVC LLDB support/restrictions 
Fixes #5610
=> DBG: support debugging on Windows outside of CLion

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Now external linter (`cargo check` or `clippy`) takes into account workspace features configuration (from #5189):
I made some changes in external linter invocation mechanics:
1. Pass `--no-default-features` and `--features` options to `cargo check` invocation
2. In a workspace, instead of invoking `cargo check` in a workspace root with `--package foo` option, now we execute `cargo check` in a **package root** without package option. It's needed because it's not possible to pass `--features` option in a workspace root if the workspace consists of multiple packages.
3. Pass concrete `target` to `cargo check` invocation, e.g. `--bin foo`, `--lib`, `--test foo`. This is not strictly needed, but it makes the code simpler, and also it should speed up the linting.
=> ANN: take into account workspace features in external linter

src/main/kotlin/org/rust/ide/utils/checkMatch/CheckMatchUtils.kt
Get rid of `exprType` and `matchedExprType` variables duplication
bors r+
=> Cleanup matched expression type validation in `CheckMatchUtils.kt`

src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
Previously, action produced incorrect version for beta and nightly rustc like `1.47.0-beta.9-beta` because of #6251
=> ACT: provide proper rustc version by "Create New Issue" action

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Fixes possible false-positive "DummyDir should not be touched" assertion fails in tests
=> T: run macro cleaning task synchronously in tests

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsInvalidReexportErrorAnnotatorTest.kt
The implementation differs from rustc in that the error annotation doesn't include the reexport alias, if there is any:
```rust
mod foo {
mod bar {}
pub use <error>bar as baz</error>; // rustc annotation
pub use <error>bar</error> as baz; // plugin annotation
}
```
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5759
TODO:
=> INSP: add inspection for E0364/E0365 errors

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/inspections/RsCastToBoolInspection.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsCastToBool.html, src/test/kotlin/org/rust/ide/inspections/RsCastToBoolInspectionTest.kt
This PR aims to implement an inspection for rust error [E0054](https://doc.rust-lang.org/error-index.html#E0054) *It is not allowed to cast to a bool.*
If this is merged, I am also interested in implementing an intent to "compare with zero instead", as the error index (and compiler) suggests.
Part of #886
=> INSP: It is not allowed to cast to a bool. (E0054)

src/main/kotlin/org/rust/ide/intentions/AddWildcardArmIntention.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt, src/test/kotlin/org/rust/ide/intentions/AddWildcardArmIntentionTest.kt
Shows "Add wildcard pattern" intention only if `match` is not empty. I think it is not reasonable to use "Add wildcard pattern" intention on empty `match` because resulting code will be similar to `if true { ... }`.
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/6505554/95209940-99941c00-07f3-11eb-956f-aedcd78a1425.png) | ![image](https://user-images.githubusercontent.com/6505554/95210724-774ece00-07f4-11eb-8fa9-185c87881e81.png) |
=> INT: Don't show "Add wildcard pattern" for empty match

src/main/kotlin/org/rust/ide/annotator/fixes/CompareWithZeroFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/fixes/CompareWithZeroFixTest.kt
Builds on #6318.
This PR adds a fix to *Compare with zero instead* when a cast of a numerical type to bool is attempted.
Part of #886
=> INT: Compare with zero instead when casting numerical to bool

src/main/kotlin/org/rust/ide/refactoring/move/RsMemberSelectionPanel.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveMemberSelection.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsHandler.kt
Add hierarchical view to [move items refactoring](https://github.com/intellij-rust/intellij-rust/issues/3531#issuecomment-643142894) dialog  (impls for a struct are located in a tree hierarchy under the struct). It makes it easier to move struct with all its impls when there are a lot of impls. Thanks @Kobzol for the [suggestion](https://github.com/intellij-rust/intellij-rust/pull/5455#issuecomment-634628733)!
=> REF: Group structs and traits with related impls in move items dialog

src/main/kotlin/org/rust/cargo/toolchain/impl/BuildScriptsInfo.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
If project directory is `source` which is a symlink to `target` directory, then `cargo metadata` command inside `source` directory produces output with `target` paths. [`CargoMetadata.Project.workspace_root`](https://github.com/intellij-rust/intellij-rust/blob/12b71cbd08c3c79282cedec71abcdd6dba61d9d5/src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt#L56-L59) was already replaced to use `source` paths in #4868. This PR replaces other fields, such as [`CargoMetadata.Package.manifest_path`](https://github.com/intellij-rust/intellij-rust/blob/12b71cbd08c3c79282cedec71abcdd6dba61d9d5/src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt#L85-L88), to use `source` paths.
Main purpose of this PR is to have [`Crate.rootModFile`](https://github.com/intellij-rust/intellij-rust/b …
=> CARGO: Replace paths to symlink source in cargo metadata

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/inspections/RsDuplicatedTraitMethodBindingInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsDuplicatedTraitMethodBinding.html, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/inspections/RsDuplicatedTraitMethodBindingInspectionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6191
=> INSP: allow duplicate parameter bindings for trait methods without a body [E0415]

src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/NewResolve.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
Continuation of #6079
Also add special annotation `@UseNewResolve` to mark tests which are expected to work only with [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217)
=> T: Add additional resolve tests

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveConflictsDetector.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
- An implementing type must be defined within the same crate as the original type definition
- https://doc.rust-lang.org/reference/items/implementations.html#inherent-implementations
- https://doc.rust-lang.org/error-index.html#E0116
We should check:
- When moving inherent impl: check that implementing type is also moved
- When moving struct/enum: check that all inherent impls are also moved
- Orphan rules: https://doc.rust-lang.org/reference/items/implementations.html#orphan-rules
- https://doc.rust-lang.org/error-index.html#E0117
We should check (denote impls as `impl<P1..=Pn> Trait<T1..=Tn> for T0`):
- When moving trait impl:
- either implemented trait is in target crate
- or at least one of the types `T0..=Tn` is a local type
- When moving trait: for each impl of this trait which …
=> REF: Check impls in move refactoring when moving to other crate

.github/workflows/check.yml, .github/workflows/regressions.yml, common/src/main/kotlin/com/intellij/openapiext/Testmark.kt, src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/test/kotlin/org/rust/NewResolve.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTestBase.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2018.kt, src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Add another job into `check` workflow to run tests with [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217) enabled.
Also add annotation `@IgnoreInNewResolve` to temporary disable few tests if running with new resolve.
=> Run tests with new resolve on CI

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/ide/docs/RsDocumentationProviderTest.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/docs/RsQuickNavigationInfoTest.kt
Previously, the plugin failed to find file with documentation when you tried to get quick documentation for primitive types from stdlib sources
=> QDOC: show quick documentation for primitive types in stdlib

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
The bug was introduced in #6212, but the cache was not enabled by default, so this bug most likely affects nobody. 
The stub cache must be consistent with SerializationManager.
Otherwise it leads to exceptions like this:
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'root' of com/intellij/psi/stubs/StubSerializationUtil.brokenStubFormat must not be null
at com.intellij.psi.stubs.StubSerializationUtil.$$$reportNull$$$0(StubSerializationUtil.java)
at com.intellij.psi.stubs.StubSerializationUtil.brokenStubFormat(StubSerializationUtil.java)
at com.intellij.psi.stubs.StubSerializationHelper.reportMissingSerializer(StubSerializationHelper.java:390)
at com.intellij.psi.stubs.StubSerializationHelper.instantiateSerializer(StubSerializationHelper.java:379)
at …
```
=> MACRO: fix MacroExpansionSharedCache

src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateCreateNewFileTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateTestBase.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsMultipleDefMapsUpdateTest.kt
Add tests for updating `CrateDefMap` in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217):
* `RsDefMapUpdateChangeSingleFileTest` - tests whether or not `CrateDefMap` should be updated after file modification
* `RsDefMapUpdateCreateNewFileTest` - tests whether or not `CrateDefMap` should be updated after creation of new file
* `RsMultipleDefMapsUpdateTest` - tests which exactly `CrateDefMap`s are updated when we modify some crate and then run resolve in some other crate
=> T: Add tests for updating CrateDefMap in new resolve

CONTRIBUTING.md, build.gradle.kts, js/src/main/kotlin/org/rust/js/RsWasmBindgenLineMarkerProvider.kt, js/src/main/resources/META-INF/js-only.xml, js/src/test/resources/META-INF/plugin.xml, plugin/src/main/resources/META-INF/plugin.xml, settings.gradle.kts
Expected workflow: navigating from Rust statement to JS one. Then having the ability to navigate to JS parts related to it.
=> Introduce line marker for wasm_bindgen attributes in WebAssembly projects

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoEventService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt, src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt, src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt, src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt, src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherTest.kt
Doesn't trigger the loading of Cargo projects structure on the first external change in `Cargo.lock` file after `cargo metadata` call because this change is performed  `cargo metadata` command itself.
It should reduce the loading of cargo projects. It may be essential if/when loading takes a long time
Part of #6104
=> CARGO: doesn't load Cargo project structure twice

src/main/resources/META-INF/rust-core.xml
Enable the cache from #6212 by default.
The cache is essential for [`name resolution 2.0`](https://github.com/intellij-rust/intellij-rust/issues/6217).
Right now it brings slightly (about 20%) macro expansion speedup in the case of a second expansion of the same macros (e.g. when you open a second project that shares the same libraries).
It still can be disabled using `org.rust.lang.macros.persistentCache` registry key.
=> MACRO: enable macro expansion cache by default

src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/RsDefMapSoftReferenceTest.kt
Memory optimization for [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217): store `CrateDefMap`s under soft references, so they will be cleared if IDE is low on memory. If `CrateDefMap` is cleared, then it will be rebuild next time it is needed.
=> RES: Store CrateDefMap under soft reference

prettyPrinters/gdb_providers.py, pretty_printers_tests/tests/btree.rs
Update `BTreeMap`/`BTreeSet` GDB pretty-printers to the recent rustc's version.
* Fixes #5722
* Handle zero-sized keys or values https://github.com/rust-lang/rust/pull/77788
I also added a fix to the original commit from rustc: `gdb.parse_and_eval("()")` instead of simple `"()"` in `children_of_node` method. This is needed because GDB treats `"()"` as a Rust array of two characters, not as a unit
After merge:
=> DBG: Update BTreeMap/BTreeSet GDB pretty-printers

.github/workflows/regressions.yml, scripts/calculate_regressions.py, scripts/fetch_projects.py, src/test/kotlin/org/rustPerformanceTests/CustomRealProjectAnalysisTest.kt, src/test/kotlin/org/rustPerformanceTests/RsRealProjectTestBase.kt
It should reduce common overhead for downloading/compilation and reduce numbers of CI instances required to run regression tests. I've checked in my own fork and all three tests took less than 35 min (currently, every single run takes about 17 minutes)
Note, now regression tests use 203 platform because I use junit 4 to generate all necessary tests in runtime and 202 platform is not compatible with junit 4 tests.
=> CI: batch regression tests

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Macro resolution impovements in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217):
* Fix resolve of macros inside imports when using new resolve
* Fix resolve of macro reexported as macro 2 when using new resolve. It doesn't affect macro expansion, where we use different code to resolve macro call, and it already works
=> RES: Fix resolve of macros inside imports and reexported macros when using new resolve

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt
Works for sequential groups starting with the same token, e.g. `$(: foo)? $(: bar)?`
Fixes #6379
=> MACRO: fix macro group matching

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt
Fix name of [option to enable new resolve](https://github.com/intellij-rust/intellij-rust/pull/6378)
bors r+
=> RES: Fix name of option in settings to enable new resolve

build.gradle.kts, clion/src/202/main/resources/META-INF/platform-clion-only.xml, clion/src/203/main/resources/META-INF/platform-clion-only.xml, clion/src/main/resources/META-INF/clion-only.xml, gradle-203.properties, gradle.properties
Also makes 203 platform default for development
changelog: 2020.3 platform is default for development now
=> GRD: update 2020.3 EAPs

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/AddAttrParenthesesFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddAttrParenthesesFixTest.kt
Adds a new error for when a `repr` attribute does not have `RsMetaItemArgs` (thus, no pair of parentheses)
Fixes #6336
changelog: Show error if `repr` attribute doesn't have parentheses and provide quick-fix to add them
=> INSP: Add error for `repr` without parentheses

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionError.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/stdext/RsResult.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt
`MacroExpander.expandMacroAsText`  returned a nullable value for a long time. I made something like Rust's `Result` and return some kind of `Err(MacroExpansionError(...))` instead of `null`. This simplifies `MacroExpander` debugging (e.g. #6380)
=> T: improve error messages in `RsMacroExpansionTest`

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This PR extends the inspection for fixing an incorrect amount of arguments passed to a function to work for closures as well. This corresponds to rust error [E0057](https://doc.rust-lang.org/error-index.html#E0057).
This PR might clash with #6318 as both modify the same enum, on the same line.
Part of #886
changelog: Detect [E0057](https://doc.rust-lang.org/error-index.html#E0057) in some cases
=> INSP: Extend function argument count check to work for closures (E0057)

.github/workflows/check.yml, .github/workflows/regressions.yml, src/test/kotlin/org/rust/RustProjectDescriptors.kt
`set-env` command was deprecated because of security vulnerability.
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ for more details
=> CI: use environment files to set env variables in GitHub workflows

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Works for `let a: foo!() = ...`
Fixes #6290
=> TY&MACRO: Support macro types

src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Support resolving macro call to expanded macro def in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217) when using PSI. Resolve without PSI already works, so this change doesn't affect macro expansions.
Fixes https://github.com/intellij-rust/intellij-rust/issues/6379#issuecomment-725364423
=> REF: Support resolve macro call to expanded macro def using PSI

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt
It slightly optimizes [CrateDefMap](https://github.com/intellij-rust/intellij-rust/issues/6217) building
=> PERF: Store dollar crate indices in macro expansion cache

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
It significantly reduces total memory usage of `DefMapService` (1.5-2 times):
* From 146MB to 92MB on rustc
* From 206MB to 96MB on amethyst
Should be merged after #6398
=>  PERF: Use custom HashMap for visibleItems in new resolve

src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt
Replaces call of `RsFile.edition` to `Crate.edition`
<details>
```
Caused by: java.lang.IllegalStateException: Check failed.
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$getOrUpdateIfNeeded$1.invoke(FacadeUpdateDefMap.kt:44)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$getOrUpdateIfNeeded$1.invoke(FacadeUpdateDefMap.kt)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(FacadeUpdateDefMap.kt)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.computeWithLockAndCheckingCanceled(ProgressIndicatorUtils.java:326)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt.withLockAndCheckingCancelled(FacadeUpdateDefMap.kt:249)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt.withLockAndCheckingCancelled$default(Fac …
```
=> RES: Fix exception when resolve is called during building CrateDefMap

src/202/main/kotlin/org/rust/lang/core/macros/compatUtils.kt, src/203/main/kotlin/org/rust/lang/core/macros/compatUtils.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
`FileAttributes` has `caseSensitivity` property on 203.
Default value `CaseSensitivity.UNKNOWN` leads to errors in logs
=> Fix 2020.3 compatibility

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt, toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt
This "foo" was resolved as a cargo feature, although it shouldn't:
```
#[cfg_attr(foobar, foobar(feature = "foo"))]
```
=> Fix wrong resolve of cargo feature in `cfg_attr`

src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt, src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
This fixes potential `PsiInvalidAccessException` exceptions or not updated highlighting (or similar problems like "IDE doesn't see my change") after applying some actions that delete PSI elements
changelog: can be omitted in the changelog
=> Fix rust structure modification increment after remove a PSI element

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt
This reduces memory needed during building CrateDefMap (up to 100MB on big crates like amethyst)
changelog: Reduce memory consumption when using new name resolution engine
=> RES: Store fromGlobImport flag inside VisItem in new resolve

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt, toml/src/test/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProviderTest.kt
Resolve cargo features in [`#[doc(cfg())]`](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html) attributes. They are used e.g. in `tokio`.
```rust
#[doc(cfg(feature = "foo"))]
fn foo() {}        //^ Cargo.toml
```
Continuation of #6276, related to #4693
changelog: Provide name resolution for cargo features in [`#[doc(cfg())]`](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html) attributes
=> RES: resolve cargo features in `#[doc(cfg(feature = "foo"))]` attributes

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt, toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt, toml/src/test/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProviderTest.kt
Real world example is tokio's
```rust
#[cfg_attr(docsrs, doc(cfg(feature = "macros")))]
fn foo() {}
```
here "macros" will be resolved as a cargo feature.
This works for any `cfg_attr` nesting, e.g. for
```rust
#[cfg_attr(windows, cfg_attr(foobar, cfg(feature = "foo")))]
fn foo() {}
```
Continuation of #6432, related to #4693
changelog: Provide name resolution for cargo features in conditional attributes like `#[cfg_attr(docsrs, doc(cfg(feature = "macros")))]`
=> RES: resolve cargo features in conditional attributes under `cfg_attr`

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt, src/main/resources/META-INF/rust-core.xml
Adds `Before launch` task for `wasm-pack` run configurations. Emulates the first part of wasm-pack process — executing `cargo build` with specific arguments like `--target wasm32-unknown-unknown`.
Provides a way to show cargo build tool window before `wasm-pack` packing instead of raw printing in the terminal.
The implementation is mostly similar to `CargoBuildTaskProvider`.
=> RUN: Add build task for wasm-pack configurations

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTest.kt, src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTestBase.kt
Original issue was found in [gimli](https://github.com/gimli-rs/gimli/blob/d36fcf11c878c8ebfb4da4cad300773869b5b5e4/examples/simple.rs#L38-L41) project that now is part of stdlib sources (stdlib dependency).
Also, print file url in `RsLazyBlockStubCreationTestBase` tests. It may help to find file with problem code and even open it in your IDE if it's located in local file system.
Fix the corresponding test in #6374 and #6417
=> STUB: create stubs for lifetime parameters only if needed

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
E.g. when moving `fn foo() { crate::mod2::bar(); }` to `mod2`, we can replace absolute path `crate::mod2::bar` with just `bar`
changelog: Use unqualified path for references to target mod in move items refactoring
=> REF(MOVE): Use unqualified path for references to target mod if possible

src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Currently private items are excluded from completion in both stable and [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217). And items which are public, but still can't be used (e.g. because they are privately reexported), are excluded in stable resolve only. So this PR excludes such items in new resolve too, for consistency with stable resolve.
changelog: Exclude private items from completion when using new resolve
=> RES: Exclude private items from completion when using new resolve

src/main/kotlin/org/rust/ide/inspections/fixes/RemoveParameterFix.kt, src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
It is needed for better imports handling in move refactoring.
changelog: Remove empty use groups when optimizing imports
=> INT: Remove empty use groups in import optimizer

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProviderTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt, toml/src/main/kotlin/org/rust/toml/completion/RsCargoTomlIntegrationCompletionContributor.kt, toml/src/main/kotlin/org/rust/toml/completion/RsCfgFeatureCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/test/kotlin/org/rust/toml/completion/RsCfgFeatureCompletionProviderTest.kt
Related to #4693
changelog: Provide completion for cargo features in `#[cfg()]` attributes
=> COMP: add completion for cargo features in cfg attributes

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Adds support for checking the `E0416` error, which occurs if the same identifier is found more than once in the same pattern.
Related: https://github.com/intellij-rust/intellij-rust/issues/886
=> INSP: check if pattern identifiers are not bound multiple times [E0416]

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/MakePublicFix.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsInvalidReexportErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
These changes:
- make range of `Item is private` annotation narrower
- provide `Make public` quick-fix available for items with restricted visibility in case of `Item is private` error
- fix `Make public` quick-fix for items with restricted visibility in case of `Item is private, and cannot be re-exported` error
- don't allow providing `Make public` quick-fix for unsupported cases
changelog: Make `Item is private` error highlighting more precisely; Provide `Make public` quick-fix for items with [restricted visibility](https://doc.rust-lang.org/reference/visibility-and-privacy.html#pubin-path-pubcrate-pubsuper-and-pubself) like `pub(crate)`
=> ANN: improve "Item is private" annotation and "Make public" fix

.github/ISSUE_TEMPLATE.md, src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
Adds information about resolve engine (stable/experimental) and macro engine (disabled/old/new) to the issue template when creating issue using "Help | Create New Issue" action. Hopefully this will help a bit when addressing new issues.
=> Provide information about macro and resolve engine when creating issue

src/main/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspection.kt, src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt, src/test/kotlin/org/rust/ide/inspections/RsAttrWithoutParenthesesInspectionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt, toml/src/main/kotlin/org/rust/toml/resolve/RsCargoTomlIntegrationReferenceContributor.kt
An improvement for #6413: take into account attributes in `#[cfg_attr(foobar, ...)]`
c.c. @zeroeightysix
changelog: Detect attributes that require parentheses but have no parentheses, and suggest Add parentheses quick-fix for attributes under #[cfg_attr]
=> INSP: improve `AttrWithoutParentheses`: take into account `cfg_attr

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProviderTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Extends #4492 to `#[cfg_attr()]` and `#[doc(cfg())]`
changelog: Add cfg options and operators completion inside `#[cfg_attr()]` and `#[doc(cfg())]` attributes
=> COMP: complete cfg options and operators in `cfg_attr` and `doc(cfg())`

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/ext/RsAttr.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/test/kotlin/org/rust/lang/core/psi/RsAttributeTest.kt
The change about `RsAttr.owner` most likely doesn't affect users because today it is used exactly in the cases where it works perfectly.
Take into account trait inner attributes like
```rust
trait Foo {
#![allow(deprecated)]
}
```
=> Fix trait inner attributes and `RsAttr.owner`

src/main/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCfgAttributeCompletionProviderTest.kt
Improves #4492, a continuation of https://github.com/intellij-rust/intellij-rust/pull/6436#discussion_r530843956, related to #4693
changelog: Complete `feature = ""` in `#[cfg()]` attributes and then invoke autocompletion with available feature list
=> COMP: complete `feature =""` in `cfg` attributes

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Make resolve and complete works for `derive()` inside `cfg_attr`: `#[cfg_attr(foobar, derive(...))]`
=> RES&COMP: resolve and complete derive attributes under `cfg_attr`

src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt
Return a token set containing all possible rust string literals (raw string literals, byte-literals).
I'm not sure what behavior this actually fixes or how it affects a user. One thing that I know is that typing inside string literals skips some complex stuff in `TypedHandler`, so this could be considered as performance improvement
=> Fix `RustParserDefinition.getStringLiteralElements`

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Complete: `type_length_limit`, `windows_subsystem`, `panic_handler`, `must_use` `ignore`, `used`, `global_allocator`
Don't complete: `plugin`, `macro_reexport`, `plugin_registrar`, `rustc_on_unimplemented`, `unsafe_destructor_blind_to_params`
See [built-in attributes index](https://doc.rust-lang.org/reference/attributes.html#built-in-attributes-index)
changelog: Provide completion for more attributes: `type_length_limit`, `windows_subsystem`, `panic_handler`, `must_use` `ignore`, `used`, `global_allocator`
=> COMP: complete more attributes, don't complete outdated ones

src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RsMacToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RsSysPathToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RsToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RsUnixToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RsWinToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RustupToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/util/ToolchainUtil.kt, src/main/kotlin/org/rust/stdext/Utils.kt, src/main/resources/META-INF/rust-core.xml
This can be useful for integration with a plugin that can suggest toolchain paths. For example, WSL integration would suggest something like this:
```
\\wsl$\Ubuntu\home\misha\.cargo\bin
```
Part of https://github.com/intellij-rust/intellij-rust/pull/5529.
=> Add an extension point for toolchain path suggestion

intellij-toml/src/main/kotlin/org/toml/ide/search/TomlFindUsagesProvider.kt, intellij-toml/src/main/kotlin/org/toml/lang/psi/Psi.kt, intellij-toml/src/main/kotlin/org/toml/lang/psi/impl/Psi.kt, intellij-toml/src/main/resources/META-INF/plugin.xml, src/main/kotlin/org/rust/ide/search/RsWordScanner.kt, toml/src/main/kotlin/org/rust/toml/CargoTomlElementDescriptionProvider.kt, toml/src/main/kotlin/org/rust/toml/Util.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt, toml/src/main/kotlin/org/rust/toml/search/CargoTomlFindUsagesHandlerFactory.kt, toml/src/main/kotlin/org/rust/toml/search/CargoTomlUsageTypeProvider.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/test/kotlin/org/rust/toml/search/CargoTomlFindUsagesTest.kt
Usage search works for Rust and TOML code. Related to #4693
With `ctrl + B`:
With `alt + F7`:
Usage highlighting:
There is a **bug** with usage highlighting - now any key in any TOML file is highlighted as some definition when under the caret. But I've checked that YAML plugin has the same bug (or a feature?), so I don't think it's critical. I also found that this bug (feature?) can be fixed with a new `Symbol` API that is available on 2020.3 platform.
=> Support `Find Usages` action for Cargo features

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFixTest.kt
... and `Add missing fields` quick fix.
Improves #3996 to better work with fields under `#[cfg]`
changelog: Fix `cfg` attributes support in `E0023` detection and a corresponding quick fix.
=> ANN: support fields under `cfg` attribute in E0023 detection

src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt, src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/AddSelfFix.kt, src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/introduceParameter/impl.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddSelfTest.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHintsProviderTest.kt, src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt, src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceParameterTest.kt, src/test/kotlin/org/rust/lang/core/type/RsCfgAttrTypeInferenceTest.kt
Fixes #6148
Correctly handle function parameters under `cfg` attributes in type inference and annotators. Works for:
```rust
fn foo(
#[cfg(foo)]      a: u8,
#[cfg(not(foo))] a: i8,
) {}
```
Note that it doesn't works `implement members` quick fix/action because it doesn't support any attributes at all. it should be fixed separately.
`self` parameter can also be under cfg. This case is not covered.
There is `RsFunction.valueParameters` that resturns function parameter list after `cfg` evaluation and  should be used in type inference/inspections/annotatos/etc, and there is `RsFunction.rawValueParameters` that resturns function parameter list **without** `cfg` evaluation and should be used in PSI manipulations
changelog: Support function parameters under `#[cfg()]` attributes
=> Support function parameters under cfg attributes

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt, src/main/kotlin/org/rust/cargo/util/RustCrateUtil.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/main/kotlin/org/rust/openapiext/utils.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Previously, we always used hardcoded info about stdlib: its packages and their relationships.
But it prevented us from getting actual info about stdlib packages: dependencies, edition, features, etc.
As a result, some code in stdlib that depends on third-party crates (like `cfg-if`) cannot be properly taken into account while name resolution and type inference.
These changes introduce an option (as an experimental feature for now) to fetch actual info about stdlib packages.
Due to the fact that stdlib sources contain `Cargo.toml`, it's possible just to run `cargo metadata` to get all necessary info.
It allows us to get proper info about:
- edition. When stdlib started to use `2018` edition, plugin name resolution was broken in some places because of it. See #3835. We solved this issue by …
=> CARGO: fetch actual info about stdlb

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
The `CreateFunctionIntention` checks that the target module is from the user's workspace, but this check was missing for creating methods. This PR fixes that.
changelog: Create method intention is no longer offered for types from external or std crates.
=> FIX: do not offer create method intention on foreign types

src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileReexportTest.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt, src/test/resources/org/rust/ide/refactoring/move/fixtures/rename_outside_references/after/mod2/foo.rs
E.g. when moving `foo` from `mod1` to `mod2`, changing `use mod1::{foo, bar};` to `use mod2::foo; use mod1::bar;` is now supported.
changelog: Support changing references in use groups in `Move` refactoring (<kbd>F6</kbd>)
=> REF(MOVE): Change references in use groups

src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/NamingNotationsTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsArgumentNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsAssocTypeNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsConstNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsEnumNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsEnumVariantNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsFieldNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsFunctionNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsLifetimeNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsMacroNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsMethodNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsModuleNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStaticConstNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsStructNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTraitNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTypeAliasNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsTypeParameterNamingInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt
The PR provides detection for non-ASCII naming and suppresses `CamelCase`, `SnakeCase`, `UpperCase` detection if case is not supported.
CamelCase rules from https://github.com/rust-lang/rust/blob/master/compiler/rustc_lint/src/nonstandard_style.rs
Fixed #6480
=> ANN: Provides case-checking for non-ascii name

build.gradle.kts, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, toml/src/main/kotlin/org/rust/toml/completion/CargoNormalizedNamesPrefixMatcher.kt, toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexCachesInvalidator.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt, toml/src/main/kotlin/org/rust/toml/crates/local/completion/DependencyCratesLocalCompletionProvider.kt, toml/src/main/resources/META-INF/toml-only.xml
Initial implementation of crates local index inside the plugin.
It gives the ability to retrieve crate names, versions, and features right from the crates index stored on disk and generated from the local cargo registry index. This way code analysis can be performed faster and with better quality and more complete results.
changelog: Added experimental `Cargo.toml` dependency completion based on local cargo registry index. It can be enabled with `org.rust.crates.local.index` experimental flag
=> CARGO: Implement crates local index based on cargo registry index

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
This PR adds a quick fix that fills missing arguments in function calls with default values.
I also wanted to support generic type parameter substitution, like this:
```rust
struct S<T>(T);
impl<R> S<R> {
fn foo(&self, t: R) {}
}
fn foo(s: S<u32>) {
s.foo(/*caret*/);
vvv
s.foo(0);
}
```
But I don't know how to substitute the type parameters (my naive attempt doesn't work). @vlad20012 is there a straightforward way of doing that?
=> ANN: add quick fix to fill missing arguments in function call

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorToolchainTest.kt
This PR adds support to the format macro annotator for `log`, `debug!`, `error!` etc. macros. Originally I wanted to add support for `tracing` too, but it's... [complicated](https://docs.rs/tracing/0.1.21/tracing/macro.event.html).
changelog: Enable format macro highlighting for `log` macros
=> ANN: inspect logging macros of the log crate

src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Do not annotate or offer cfg-disabled trait items for [E0046](https://doc.rust-lang.org/error-index.html#E0046) and `Generate members`.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/1470
changelog: Better handle cfg-disabled items when checking [E0046](https://doc.rust-lang.org/error-index.html#E0046).
=> ANN: do not annotate unimplemented cfg-disabled trait items

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt
Currently it replaces function parameters with the function arguments.  Still need to make sure arguments will be resolved in the same order were they not inlined by creating variables for them before the main inline. Here's a Kotlin example:
That's the original file. We'll inline `foo()`
```kotlin
var count = 1
private fun main() {
val a = foo(bar())
}
private fun foo(number: Int): Int {
return number * bar() + number
}
private fun bar(): Int {
return count++
}
```
The original code should get `2 * 3 + 2` inside foo.
My code currently inlines the values directly, like so:
```kotlin
var count = 1
private fun main() {
val a = bar() * bar() + bar()
}
private fun bar(): Int {
return count++
}
```
Which leads the calculation to be `2 * 3 + 4`, because the function will be called an additional …
=> Inline function arguments correctly

src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt, src/main/kotlin/org/rust/cargo/runconfig/RsAnsiEscapeDecoder.kt, src/main/kotlin/org/rust/cargo/runconfig/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildEventsConverter.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/main/kotlin/org/rust/openapiext/JsonUtils.kt, src/main/resources-nightly/META-INF/experiments.xml, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt, src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/pull/3926.
Fixes https://github.com/intellij-rust/intellij-rust/issues/4288.
Fixes https://github.com/intellij-rust/intellij-rust/issues/4898.
Note: `CARGO_TERM_PROGRESS_WHEN` and `CARGO_TERM_PROGRESS_WIDTH` variables were stabilized in the 1.48.0 release.
=> RUN: Support for ANSI colors in build tool window

toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt, toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/completion/CratesIoCargoTomlDependencyCompletionProviders.kt, toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/completion/TomlKeyValueCompletionProviderBase.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexCachesInvalidator.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
Previously, we set up dependency completion providers (via local registry index or via crates.io API) in `CargoTomlCompletionContributor`'s constructor based on `RsExperiments.CRATES_LOCAL_INDEX` feature value.
But the platform creates a single object of `CargoTomlCompletionContributor` on plugin loading and doesn't recreate it on `RsExperiments.CRATES_LOCAL_INDEX` feature changes. So it wasn't possible to switch completion provider without IDE restart
These changes register new completion provider that can switch a completion way dynamically (i.e. without IDE restart)
=> COMP: switch dependency completion provider for Cargo.toml on the fly

src/main/resources-stable/META-INF/experiments.xml
=> RUN: Enable Build Tool Window by default

src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt
Fixes #6508
| - | - |
| <img src="https://user-images.githubusercontent.com/2539310/102648855-4c301580-4179-11eb-8432-c127817758e8.png"> | <img src="https://user-images.githubusercontent.com/2539310/102648848-476b6180-4179-11eb-9080-e6895a48d497.png"> |
changelog: Improve popup of `Has implementations` gutter icon by items sorting and allowing to open results in `Find` tool window
=> Improve popup of `Has implementations` gutter icon

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Now you don't need to think about escaping while introducing new diagnostic.
All messages in problems tool window and in editor should be properly escaped automatically.
In particular, it solved wrong escaping in E0277 error message
changelog: Properly render generic types in [`E0277`](https://doc.rust-lang.org/error-index.html#E0277) error message
=> ANN: fix escaping in annotation messages

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt, src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlStdTest.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/docs/RsStdlibResolveLinkTest.kt
Current changes allow opening quick documentation for [keyword](https://doc.rust-lang.org/stable/std/#keywords) like elements.
But for `self`, `super`, `crate` and `Self` documentation won't be shown if they are part of a path. I suppose documentation for the referenced element is more important than documentation about keywords in such cases
Note, currently, if documentation contains a link to a keyword, the plugin can't open the corresponding quick doc. Will be fixed in separate PR.
changelog: show [quick documentation](https://www.jetbrains.com/help/idea/viewing-reference-information.html#inline-quick-documentation) for [keyword](https://doc.rust-lang.org/stable/std/#keywords) like elements like `fn`, `enum`, `async`, etc.
=> QDOC: show documentation for keyword like elements

CONTRIBUTING.md, build.gradle.kts, ml-completion/src/203/main/kotlin/org/rust/ml/RsCompletionFeaturesPolicy.kt, ml-completion/src/203/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt, ml-completion/src/203/main/kotlin/org/rust/ml/RsMLRankingProvider.kt, ml-completion/src/203/main/resources/META-INF/ml-completion-only.xml, ml-completion/src/203/test/kotlin/org/rust/ml/RsElementFeatureProviderTest.kt, ml-completion/src/203/test/kotlin/org/rust/ml/RsModelMetadataConsistencyTest.kt, ml-completion/src/203/test/resources/META-INF/plugin.xml, plugin/src/main/resources/META-INF/plugin.xml, settings.gradle.kts
Part of https://github.com/intellij-rust/intellij-rust/issues/6411
This PR adds a new module `ml-completion` to the project. This module provides the ML-based code completion ranking support for Rust. Currently, it consists of:
* `RsCompletionFeaturesPolicy` enabling Ngram model for future models
* `RsElementFeatureProvider` providing Rust-specific features to train future models, with tests
* `RsMLRankingProvider` providing an initial ranking model (trained without the stuff above, therefore not very intelligent so far)
Thanks to @bibaev for help!
The new ranking model can be enabled in `Editor | General | Code Completion | Machine Learning-Assisted Completion` settings (see [help](https://www.jetbrains.com/help/idea/auto-completing-code.html#ml_completion) for more details). However, at …
=> Provide ML completion ranking for Rust

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.rs, src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.txt
As discussed in https://github.com/intellij-rust/intellij-rust/pull/6404#issuecomment-748450945. Can be considered as a continuation of #6285.
Provides better syntax error messages in the case of an incomplete path like this:
```rust
use ::;
type T = <Foo as Bar>::;
```
c.c. @msmorgan
changelog: Improve parser recovery and syntax error messages in the case of incomplete paths
=> GRAM: parse `::` as an incomplete path

src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt, src/test/resources/org/rust/lang/core/parser/fixtures/partial/paths.txt, src/test/resources/org/rust/lang/core/parser/fixtures/partial/shifts.txt
In addition to #6541 let's show `identifier expected, got ';'` message instead of `Self, crate, identifier, self or super expected, got ';'`. This is a bit closer to `rustc`'s messages
changelog: Improve syntax error messages in the case of incomplete paths
=>  GRAM: simplify syntax error messages on incorrect paths

.github/workflows/regressions.yml, scripts/fetch_projects.py, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rustPerformanceTests/RsRealProjectAnalysisTest.kt
Note, I've created a new batch in regression tests workflow because analysis is quite slow currently for `core_arch` module in `std`.
But #6526 should significantly improve the performance (from 17 to 3 minutes on my machine) of stdlib test, so it's probably worth to merge both batches into a single one after #6526
changelog: provide regression testing for stdlib packages on CI
=> CI: provide regression testing for stdlib

.github/workflows/milestones.yml
Allows setting a milestone for merged PR even if PR was made from fork.
Previously, it didn't work for PRs from forks because of read-only permissions that Github grant to workflow with `pull_request` event not to execute arbitrary code with write permissions in our repo. But `pull_request_target` event allows us to have a token with write permissions even in fork PR because everything is executed in context of the base of the pull request. See more details [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request_target)
Continuation of #6051.
changelog: Set milestone automatically for pull requests from forks. Previously, it worked only for pull requests in original repository
=> CI: set milestone automatically for PRs from forks

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
=> ANN: highlight arguments of panic macro

src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Fix `StackOverflowError` in case when both parent and grandparent mod of expanded macro def has `macro_use` attribute (Introduced in #6543)
=> RES: Fix propagation expanded macro def to grandparent mod

src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Fixup for #6558. For some reason, bors has merged commit, even though tests [don't pass](https://github.com/intellij-rust/intellij-rust/pull/6558#issuecomment-751242039)
=> T: Fix propagate expanded macro test

toml/src/main/kotlin/org/rust/toml/CargoTomlPsiPattern.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlReferenceContributor.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlUrlReferenceProvider.kt, toml/src/test/kotlin/org/rust/toml/CargoTomlPsiPatternTest.kt, toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlUrlResolveTest.kt
This PR adds support for resolveing URLs in `git`, `homepage`, `repository` and `documentation` attributes in `Cargo.toml`. I didn't know how to test web references, so I just added tests for their corresponding PSI patterns.
I also refactored the TOML PSI patterns a bit to introduce a method that can be used to find any dependency attribute.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6552
changelog: Resolve URLs in Cargo.toml (e.g. in dependency `git` links).
=> CARGO: resolve URL references in some package and dependency attributes

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt, src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt, src/test/kotlin/org/rust/common.kt, src/test/kotlin/org/rust/ide/actions/RsCreateCrateActionTest.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsDowngradeModuleToFileTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryActionTest.kt, src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
Also, search all actions in tests via ids instead of creating action objects manually. It should check that tested actions are registered in `plugin.xml`
Fixes #6565
=> Properly render Refresh Cargo Projects action in Sync view

src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsExternCrateItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsModDeclItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt, src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsLangItemIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsMacroIndex.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsModulesIndex.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProviderTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsCfgAttrTypeInferenceTest.kt
Now `cfg_attr` is mostly transparent for the plugin. The support includes (but is not limited to) these attributes:
* `derive` (`#[cfg_attr(windows, derive(Clone))]`, #3683 case)
* `path` (`#[cfg_attr(windows, path="win.rs")] mod foo;`, #5458 case)
* `cfg` (yes, `cfg` under `cfg_attr`: `#[cfg_attr(feature = "foo", cfg(feature = "bar"))]`)
* `proc_macro`, `proc_macro_attribute`, `proc_macro_derive`
* `test`, `bench`
* `no_std`, `no_core`
* `macro_use`, `macro_export`
* `no_main`, `may_dangle`, `non_exhaustive`, `doc(hidden)`, `deprecated`
* `lang`, `repr`, `unstable`
Documentation under `cfg_attr` is not supported for now (e.g. `#[cfg_attr(windows, doc = "...")]`).
`RsDocAndAttributeOwner.queryAttributes` now yields meta items after `cfg_attr` expansion.
We often store attribute values to …
=> Support `cfg_attr` attributes

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Fixes resolve of qualified macro calls inside items in some cases, e.g.:
```
fn main() {
futures::join!();
}
```
changelog: Fixes resolve of qualified macro calls inside items in some cases when using new resolve
=> RES: Use new resolve for not top level macro calls

src/main/kotlin/org/rust/ide/inspections/fixes/RemoveParameterFix.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6513
changelog: RemoveParameter quick fix no longer removes some references of the modified function.
=> INSP: do not remove function references in remove parameter quick fix

src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringSupport.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/refactoring/suggested/RsRenameSuggestedRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
This PR adds support for the new suggested refactoring. Since change signature refactoring is not implemented for Rust yet, I only added basic support for renaming local bindings.
I copy-pasted the test infrastructure from the Kotlin plugin, because I couldn't get `com.intellij.refactoring.suggested.BaseSuggestedRefactoringTest` to work, as it couldn't autoload some Java `PsiElementFactory` class during runtime. However, even after copying the tests, they do not work. When I perform a change in the test file text and commit it, the refactoring suggestion intention is not offered. Yet when I do the exact same change in the IDE, it works fine. Any hints on what I could be missing?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5909
=> REF: add suggested rename refactoring

src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/PathUtil.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
Fix handling restricted visibility with path from crate root in [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217). E.g.:
```rust
mod inner1 {
mod inner2 {
mod inner3 {
pub(in crate::inner1) fn foo1() {}
pub(in crate::inner1::inner2) fn foo2() {}
}
}
}
```
Previously items with such visibility were considered as `pub(crate)`
changelog: Fix handling items with restricted visibility with absolute path in new resolve
=> RES: Fix restricted visibility in new resolve

.idea/codeStyles/Project.xml
Some time ago intention "Put parameters on separate lines" converted this function:
```kt
fun function1(parameter1: Int, parameter2: Int, parameter3: Int) {}
```
into this:
```kt
fun function1(
parameter1: Int,
parameter2: Int,
parameter3: Int
) {}
```
Recently this intention started to instead convert function to
```kt
fun function1(parameter1: Int,
parameter2: Int,
parameter3: Int) {}
```
Since all our code use first variant, I guess it makes sense to adjust code style settings to continue using it (for consistency purpose)
=> Adjust multiline functions code style

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Fixes  #6136 and #6486 with [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217)
changelog: Support `#![macro_use]` attribute at file level when using new name resolution engine
=> RES: Support file level macro_use attribute in new resolve

intellij-toml/src/main/kotlin/org/toml/lang/psi/TomlVisitor.kt, intellij-toml/src/main/kotlin/org/toml/lang/psi/impl/Psi.kt, intellij-toml/src/test/kotlin/org/toml/lang/psi/TomlVisitorTest.kt
This PR adds a simple visitor for TOML elements. I think that it is useful enough to warrant a PR even without a specific usage.
It can be used e.g. in https://github.com/intellij-rust/intellij-rust/pull/6457, https://github.com/intellij-rust/intellij-rust/pull/3787, https://github.com/intellij-rust/intellij-rust/pull/6535 and if it's merged, I suppose that it will be used in many future Cargo.toml inspections, now that the local index is finally working.
=> TOML: add TomlVisitor

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt, toml/src/main/kotlin/org/rust/toml/Util.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt
changelog: Fix cargo features inference with renamed packages
=> Fix cargo features inference with renamed packages

toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt
Implements incremental updates of crates local index on `Cargo.toml` changes.
To incrementally update the crates local index, it gets the previous indexed commit from the state and finds the changed files with the current head in the cargo registry repo. Then, the changed files are getting reloaded from the head state.
In a case when there is no previous indexed commit or it hasn't been found, it refreshes the index with all changes.
Part of https://github.com/intellij-rust/intellij-rust/issues/6463
changelog: Update experimental [local crates index](https://github.com/intellij-rust/intellij-rust/pull/6390) incrementally. This speeds up the experimental `Cargo.toml` dependency completion and will affect other new code insight based on this index in the future. Note, the corresponding …
=> CARGO: Make crates local index updates incremental

src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
Use `Map` instead of `MutableMap` that was used by accident and not necessary here
=> Make `RsInferenceResult` immutable

src/main/kotlin/org/rust/cargo/CfgOptions.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspaceData.kt, src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt, src/main/kotlin/org/rust/lang/core/crate/Crate.kt, src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt, src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/test/kotlin/org/rust/MockAdditionalCfgOptions.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
For a long time, we did consider _unknown_ `cfg` options and unknown cargo features as enabled and disabled at the same time.
For example, both `foo` were enabled here:
```rust
#[cfg(unknown_cfg_option)]
fn foo() {}
#[cfg(not(unknown_cfg_option))]
fn foo() {}
```
What means "unknown"? Well, we had a list of known `cfg` options. It contained `debug_assertions`, `unix`, `windows` named options and `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_os`, `target_pointer_width`, `target_vendor` key-value options.
In the case of cargo features, we considered as "unknown" features that are not mentioned in `[features]` table of `Cargo.toml`.
Why? Why not just consider these `cfg` options as disabled (just like `rustc` does)?
There are two reasons:
1. We use …
=> Evaluate unknown cfg options to false if no `build.rs` in a package

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsCfgNotTestIndex.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/stubs/index/RsCfgNotTestIndexTest.kt
Consider a code under `#[cfg(test)]` disabled in external dependencies (I.e. outside of a cargo workspace). Previously it was considered "enabled and disabled simultaneously", i.e. a code under `#[cfg(test)]` and `#[cfg(not(test))]` both was enabled.
The issue is that `#[cfg(test)]` sometimes used to mock something for testing:
```rust
#[cfg(test)]
mod foo {
// Some mocks here
}
#[cfg(not(test))]
use foobar::foo; // Import the production variant of `foo`
```
So, we need `cfg(test)` to be disabled in order to provide correct name resolution.
But more often `cfg(test)` is used placed on test modules like this:
```rust
#[cfg(test)]
mod test {
#[test]
fn some_test() {}
}
```
So, if we disable `cfg(test)`, we make all tests grayed out!
The question "what to do with `cfg(test)`" was discussed …
=> Disable `cfg(test)` in external dependencies if there is `cfg(not(test))`

src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
Fixes exception in `RsRealProjectAnalysisTest#test analyze juniper`:
<details>
```
com.intellij.diagnostic.PluginException: Reported element PsiElement(identifier) is not from the file '/src/main.rs' the inspection 'RsTraitImplementation' (class org.rust.ide.inspections.RsTraitImplementationInspection) was invoked for. Message: '<html>Method `bar` is not a member of trait `T` [<a href='https://doc.rust-lang.org/error-index.html#E0407'>E0407</a>]<br></html>'.
Element containing file: FILE
Inspection invoked for file: FILE
at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:335)
at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
at …
```
=> INSP: Ignore expanded members in `Trait implementation` inspection

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Previously, the plugin added several `Self` items in nested `impl` blocks that broke name resolution (because of multi resolve) and duplicated items during completion
Fixes #6600 
changelog: Fix name resolution and completion of `Self` keyword for nested structs, enums and `impl` blocks
=> RES&COMP: don't duplicate `Self` while name resolution and completion

.github/workflows/check.yml, coverage/src/main/kotlin/org/rust/coverage/GrcovRunner.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorWithToolchainOverrideTest.kt, src/test/kotlin/org/rustSlowTests/cargo/RustupOverrideTest.kt
Previously, we didn't specify the working directory during fetching `rustc` version. As a result, the plugin always got version of default toolchain.
But a user can [override](https://rust-lang.github.io/rustup/overrides.html) toolchain via `rustup` for a specific toolchain for a specific directory. And the plugin didn't handle such overrides
Now we pass the working directory and can get the proper toolchain version even it's overridden
Project with `nightly` as overridden toolchains and 1.48 as default toolchain:
| - | - |
| ![](https://user-images.githubusercontent.com/2539310/103315101-b24c5080-4a35-11eb-957d-e925a0f90aca.png) | ![](https://user-images.githubusercontent.com/2539310/103315092-abbdd900-4a35-11eb-90dd-1c57067e3b82.png) |
Fixes #5560
Fixes #6561
Should …
=> CARGO: basic support for rustup override

intellij-toml/src/main/kotlin/org/toml/ide/folding/TomlFoldingBuilder.kt, intellij-toml/src/main/resources/META-INF/plugin.xml, intellij-toml/src/test/kotlin/org/toml/TomlTestBase.kt, intellij-toml/src/test/kotlin/org/toml/ide/folding/TomlFoldingBuilderTest.kt, intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/array.toml, intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/array_table.toml, intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/custom_regions.toml, intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/inline_table.toml, intellij-toml/src/test/resources/org/toml/ide/folding/fixtures/table.toml
This PR adds a folding provider for TOML.
Since there is no `TomlVisitor`, I just used `PsiTreeUtil.processElements` to go through all PSI elements recursively.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6083
changelog: Provide folding in TOML files. Currently, it supports tables, arrays, and custom folding regions
=> TOML: add folding builder

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/openapiext/utils.kt
Remove usage of `FileBasedIndex.registerIndexableSet` and `FileBasedIndex.removeIndexableSet`.
We don't actually use it anymore (it was used before 2020.2 because of bug in the platform) and these methods are dropped in 2021.1
=> Drop using old API

src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
This PR adds basic support for closures to `FillFunctionArgumentsFix` (introduced in https://github.com/intellij-rust/intellij-rust/pull/5644) and also resolves function types with substituted types.
The substitution doesn't yet work properly for method calls (see https://github.com/intellij-rust/intellij-rust/pull/5644#discussion_r555034800). 
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6612
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6645
changelog: Enable the new "Fill function arguments" quick-fix for closures and take generic arguments into consideration when filling default values.
=> ANN: improve fill function arguments fix

src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/utils/CfgUtils.kt, src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
A little improvement for #6497: highlight disabled `cfg_attr`s as conditionally disabled code:
Nested `cfg_attr`s (e.g. `#[cfg_attr(foo, cfg_attr(bar, foobar))]`) are not highlighted (and why someone needs to write them?)
changelog: Gray out disabled `#[cfg_attr()]` attributes
=> ANN: gray out disabled cfg_attr attributes

src/main/kotlin/org/rust/lang/core/CompilerFeature.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsFeatureIndex.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Previously, the corresponding annotations took into account only top-level `feature` attributes.
Now, they correctly expand `cfg_attr` attribute
Continuation of #6497
Fixes #6631
changelog: Take into account `cfg_attr` attribute during experimental compiler features annotation
=> Take into account cfg_attr during experimental compiler features annotation

src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Recent implementations of `Box` (since 1.49) and `Vec` (latest nightly) provide new allocator API.
So now these items contain additional type parameter for allocator type with some default value.
Previously, we didn't infer type of allocator type parameter for `box` patterns and `vec!` macro.
Now it works as expected
Note, I haven't added any new test since all necessary cases are covered with existing tests. So this PR fixes some failed test with new Rust versions (see #6604)
changelog: Adjust type inference to infer type of allocator type parameter for `Box` and `Vec` items. See the corresponding [RFC](https://rust-lang.github.io/rfcs/1398-kinds-of-allocators.html) about allocator API
=> TY: infer type of default type parameters for known stdlib items

toml/src/main/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspection.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/inspectionDescriptions/CargoTomlCyclicFeature.html
Closes #6523
<image width="600" src="https://user-images.githubusercontent.com/6342851/103595146-cac3db80-4f0b-11eb-8bad-79f696e6cdb4.png">
changelog: Add inspection to check whether a feature has a cyclic dependency on itself
=> INSP&COMP: Improve cyclic feature dependencies handling

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixture.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionFromIndexTest.kt
Previously, we filter out secondary import candidates for the same item from completion suggestions, as a result, if a library (e.g. async-std) re-exports some item from another library/stdlib, completion shows only single suggestion per item.
Now, we show all suggestions that can be imported - the same items as in `Auto Import` quick-fix
Fixes #5415
changelog: Show all re-exports of the same item in completion list. Previously, the plugin shows only one suggestion per item that hid alternative ways to import the item.
=> COMP: show all re-exports of the same item in completion

scripts/common.py, scripts/github.py, scripts/set_milestone.py
#6538 changed event when milestone workflow triggered. Most important part of this change is that now we use base commit of each PR to determine milestone.
It allows us to launch the workflow for any PR (even from forks) but at the same time it works incorrectly because now the workflow look on old version of `gradle.properties` files to get proper milestone version.
These changes get actual content of `gradle.properties` via downloading it via http instead of using potentially outdated local version
=> CI: set milestone properly from CI

src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Fixes #6605
changelog: Fix endless go-to-declaration for invalid self-containing structs
=> Fix endless go-to-declaration for invalid self-containing structs

src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/4535.
=> RUN: Don't activate Build Tool Window if "Activate tool window" option is disabled

src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Continuation of https://github.com/intellij-rust/intellij-rust/pull/6678.
I could special case it for `RsBlockExpr`/`RsExprStmt`, since blocks are probably the only place where this could happen, but I realized that the actually important thing is the containment within an expr/stmt. So I removed the explicit check for `RsBlockExpr`.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6683
=> REF: correctly extract selected statements inside exprs into a function

src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt, src/test/kotlin/org/rust/ide/intentions/visibility/MakePrivateIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/visibility/MakePubCrateIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/visibility/MakePubIntentionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6577
changelog: Fix `ChangeVisibilityIntention` so that it is not offered in trait impl blocks.
=> INT: do not offer ChangeVisibilityIntention in trait impl blocks

src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
This PR enables `CreateFunctionIntention` for associated methods.
changelog: Enable `CreateFunctionIntention` also for associated methods.
=> INT: add support for associated functions in CreateFunctionIntention

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5166
=> ANN: annotate wrong return type for empty functions

coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/6583.
changelog: Support `Build` tool window for `cargo check` and `clippy`
=> RUN: Support Build tool window for cargo check and clippy

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
changelog: make items from std appear first when auto import
when have `async-std` as dependency, auto import `Arc` should use `std::sync::Arc` instead of `async_std::sync::Arc`
=> INSP: make items from std appear first when auto import

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoDependencyReferenceProvider.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/5414
(works only if `org.rust.cargo.build.tool.window` is enabled)
changelog: Fix working directory when run `cargo test` in debug mode
=> RUN: Fix working directory when run `cargo test` in debug mode

src/main/kotlin/org/rust/ide/utils/CallInfo.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHintsProviderTest.kt
```rust
fn test() -> Result<(), ()> {
Ok(/*T: */())
}
```
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4601
changelog: Show type parameters in inlay hints for generic enum variants
=> HINT: add type parameter name to non-smart parameter hints of generic enum variants

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildSessionsQueueManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
Currently, if you are using the new Build View and try to build a second project while building the first project, the second build will hang with the "Waiting for another build to finish" message.
changelog: Allow building different projects simultaneously
=> RUN: Allow to build different projects simultaneously

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt
Improves the #5661 fix: now resolve it to visible trait impl instead of private inherent impl:
```rust
use foo::{Foo, Trait};
mod foo {
pub struct Foo;
impl Foo {
// Private
fn get(&self) { println!("struct"); }
}
pub trait Trait {
fn get(&self);
}
impl Trait for Foo {
fn get(&self) { println!("trait"); }
}    //X
}
fn main() {
let f = foo::Foo;
f.get();
//^
}
```
c.c. @Kobzol
=> RES: prefer trait methods before private inherent methods

src/main/kotlin/org/rust/ide/annotator/fixes/AddMutableFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveParameterFix.kt, src/main/kotlin/org/rust/ide/refactoring/RsRefactoringSupportProvider.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt, src/main/kotlin/org/rust/ide/refactoring/functionSignature.kt, src/main/kotlin/org/rust/ide/search/RsFindUsagesProvider.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
This PR adds the `Change signature` refactoring.
The current implementation has basic functionality.
- ~How should the user be able to enter the name and type of parameters? I suggest that we use `RsPat` for name and `Ty` or `RsTypeReference` for types instead of plain strings, so that after the user enters something, we try to parse it and if it fails, we will not allow the dialog to proceed.~
- ~Currently, if a new parameter is added, it will not be filled with a default value at call sites, so that the user will not forget to update the call sites. This mirrors the behaviour of Kotlin.~
- ~Should the dialog offer things like `async`, `unsafe`, `extern` or variadic args? If yes, we need to let the user enter any possible value for these attributes. I think that it's worth to do it only …
=> REF: add basic implementation of change signature refactoring

src/main/kotlin/org/rust/ide/console/RsConsoleFolding.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Fix #6607
From issue:
> When a test is unsuccessful, the whole IDE becomes unresponsive temporarily.
When test is unsuccessful, there is backtrace, and we process backtrace in `RsConsoleFolding` and `RsBacktraceFilter`. Both services try to resolve absolute paths from backtrace for *each* crate, including e.g. test/bench dependencies crates. We do not currently build DefMap for such crates, and log error message in new resolve if we try to use resolve in such crates. That's the cause of issue: error message was logged too many times (and e.g. each time it has to calculate java stacktrace). Btw `RsConsoleFolding` runs on EDT (so IDE freezes) and `RsBacktraceFilter` runs in background.
This PR:
* Optimizes error message logging by replacing `LOG.error` to `LOG.warn`
* Removes resolve from …
=> PERF: Optimize backtrace filter and folding when using new resolve

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Fixes part of #6670, when cursor is located in the middle of macro path:
```
asse/*cursor*/rt_!();
```
changelog: Fix completion of unqualified macro calls in new resolve in some cases
=> RES: Fix completion of unqualified macro calls in new resolve

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Works for
```rust
trait Foo { type Item: Bar; }
trait Bar: Baz {}
trait Baz {
fn baz(&self) {}
}    //X
fn foobar<T: Foo>(a: T::Item) {
a.baz();
}   //^
```
=> TY: fix assoc type bounds with supertrait

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
E.g. try changing function return type to `FooStruct`:
```rust
mod mod1 {
pub struct FooStruct {}
}
fn foo() {}
```
changelog: Fix auto-import in change signature refactoring dialog when using new resolve
=> REF: Fix types auto import in change signature dialog with new resolve

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
This PR adds a quick fix that lets the user quickly remove a redundant function argument. This fix is inspired by a similar one that exists for Kotlin (and probably also for other languages).
I wanted to implement this right after https://github.com/intellij-rust/intellij-rust/pull/5612, but I kind of forgot about it. Another option (instead of removing the argument) is to add a new parameter, but that is blocked on https://github.com/intellij-rust/intellij-rust/pull/5944.
I didn't inherit from `RemoveElementFix`, because I would have to override all of its functions anyway. Currently, whitespace/comments next to the removed argument are preserved, not removed, I'm not sure which is better.
changelog: Add a quick fix to remove redundant function call arguments.
=> ANN: add quick fix to remove redundant function call arguments

clion/src/202/main/kotlin/org/rust/clion/cargo/CidrBuildConfigurationProvider.kt, clion/src/202/main/resources/META-INF/platform-clion-only.xml, clion/src/203/main/kotlin/org/rust/clion/cargo/CidrBuildConfigurationProvider.kt, clion/src/203/main/resources/META-INF/platform-clion-only.xml, clion/src/main/kotlin/org/rust/clion/cargo/CargoBuildConfigurationProvider.kt, clion/src/main/resources/META-INF/clion-only.xml, gradle-203.properties
Fixes #6752
changelog: fix `Build` action in CLion 2020.3.2
=> GRD: update 2020.3 IDE and plugin dependencies

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Please see #5955 for details why `name` is needed
changelog: Fix performance regression in name resolution for large modules
=> Fix passing item name through RsResolveProcessor

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexStartupActivity.kt, toml/src/main/resources/META-INF/toml-only.xml
After opening a project, `CratesLocalIndexStartupActivity` tries to get an instance of the service. This initializes the service's `Cargo.toml` watcher and PersistentHashMap before performing any inspection or completion.
=> Initialize crates local index service on startup

toml/src/main/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProvider.kt, toml/src/test/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProviderTest.kt, toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspectionTest.kt
Implemented simple test cases for inspection and another one for completion, checking that there is only one suggestion in the scope.
Improvement of #6535
=> T: Add cyclic feature dependency inspection & completion tests

.github/workflows/check.yml, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/resources-nightly/META-INF/experiments.xml
This allows us to gather more feedback and find potential issues
Should be merged after #6719
changelog: Enable new name resolution engine on the nightly plugin channel by default
=> RES: Enable new name resolution engine on nightly by default

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Support macros with 3 or more segments ([example](https://github.com/amethyst/amethyst/blob/e60f89fe4a08dd43313402b3b04dccfedd9318cc/amethyst_assets/src/loader.rs#L462))
changelog: Support resolve multi-segment macro paths in new resolve
=> RES: Support resolve multi-segment macro paths in new resolve

src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6781
changelog: Fix processing of `break`/`continue` inside block expression during control-flow analysis
=> Fix control flow of break/continue inside block expression

.github/workflows/rust-release.yml
=> CI: drop builds for 202 platform and start building for 211 by release workflow

src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rust/cargo/project/CargoProjectOpenProcessorTest.kt, src/test/kotlin/org/rust/cargo/project/model/AttachCargoProjectActionTest.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcherIntegrationTest.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt, src/test/kotlin/org/rust/ide/annotator/RsWithToolchainAnnotationTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt, src/test/kotlin/org/rustSlowTests/CargoProjectServiceTest.kt, src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt, toml/src/test/kotlin/org/rust/toml/inspections/MissingFeaturesInspectionTest.kt, toml/src/test/kotlin/org/rust/toml/search/CargoTomlFindUsagesTest.kt
Now, `Open` action properly sets up Cargo project if the selected file is a directory contained `Cargo.toml`.
Previously, you had to open Cargo tool window to detect top-level `Cargo.toml` and load project structure
Also, in the case of several variants how to open a project, IDE suggests choosing the desired type of project a user.
Fixes https://youtrack.jetbrains.com/issue/CPP-23725
changelog: improve `File | Open` action to set up project structure of Cargo project if a project is opened via directory with `Cargo.toml`
=> CARGO: improve project opening

src/main/kotlin/org/rust/ide/inspections/fixes/RemoveTypeArguments.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongTypeArgumentsNumberInspectionTest.kt
The `RemoveTypeArguments` fix was introduced in https://github.com/intellij-rust/intellij-rust/pull/1305 and for some reason it ignored types with lifetimes (I hadn't found why in the PR description. @farodin91 do you recall? :D ). I suppose that it shouldn't be a problem, so I removed the condition to fix https://github.com/intellij-rust/intellij-rust/issues/6620. If you are aware of any issues that might arise from this, let me know.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6620
changelog: Allow removing redundant type arguments from types with lifetimes
=> ANN: allow removing redundant type arguments from types with lifetimes

toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexCachesInvalidator.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt, toml/src/main/kotlin/org/rust/toml/crates/local/TestCrateResolverService.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/inspectionDescriptions/CrateNotFound.html, toml/src/test/kotlin/org/rust/toml/inspections/CrateNotFoundInspectionTest.kt
This PR add more basic infrastructure to TOML, based on the new local crate index. The first commit introduces a simple inspection which checks crates in `Cargo.toml` that do not exist (=were not found in the index). It uses the new TOML visitor (https://github.com/intellij-rust/intellij-rust/pull/6578) and also the dependency visitor from https://github.com/intellij-rust/intellij-rust/pull/3787. After another inspection is added, this dependency visitor should be extracted into a separate file.
The second commit then introduces tests for the inspection, which however require a lot of new infrastructure. Mainly it adds a service interface and a test implementation for the local crate index (taken from https://github.com/intellij-rust/intellij-rust/pull/5988).
Closes: …
=> INSP: add inspection that checks non-existent crates

src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/test/kotlin/org/rust/NewResolve.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt, src/test/kotlin/org/rustPerformanceTests/RsBuildDefMapTest.kt, src/test/kotlin/org/rustPerformanceTests/RsProfileBuildDefMapTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
As a consequence of #6731, [new resolve](https://github.com/intellij-rust/intellij-rust/issues/6217) was enabled by default on CI and for local development. There are few tests which are currently not supported by new resolve, so it makes sense to force use old resolve for them (instead of ignoring them in new resolve)
=> T: Replace `@IgnoreInNewResolve` with `@UseOldResolve`

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Related: #6308, #6777, #886
changelog: Detect [E0116](https://doc.rust-lang.org/error-index.html#E0116) compiler error
=> ANN: Check E0116 "Inherent impls should be in same crate"

toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/TomlLocalInspectionToolBase.kt
Otherwise, the inspection may throw exceptions when PSI in TOML plugin is changed
Also, introduce `TomlLocalInspectionToolBase` not to forget to check TOML plugin compatibility.
=> TOML: check TOML plugin compatibility in CrateNotFoundInspection

debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
changelog: show missing Rust block in `Preferences | Build, Execution, Deployment | Debugger` settings on Windows in IntelliJ IDEA
=> DBG: show missing Rust debugging settings on Windows

build.gradle.kts
Failed test will be retried at most 3 times. This is needed to mitigate flaky tests. If there are more then 20 failed test, no test will be retried. Implemented by [`test-retry-gradle-plugin`](https://github.com/gradle/test-retry-gradle-plugin).
=> CI: Retry failed tests

prettyPrinters/gdb_lookup.py, prettyPrinters/gdb_providers.py, pretty_printers_tests/tests/enum.rs
Fixes https://github.com/intellij-rust/intellij-rust/issues/6746
The new enum representation was introduced in https://github.com/bminor/binutils-gdb/commit/9c6a1327ad9a92b8584f0501dd25bf8ba9e84ac6
To test:
changelog: Fix enum rendering while debugging with GDB in CLion 2021.1
=> Fix enum rendering while debugging with GDB in CLion 2021.1

src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6784
changelog: Take `cfg` attributes into account during control-flow analysis
=> Take `cfg` attributes into account in control flow

CONTRIBUTORS.txt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
We need to inherit from this configuration in EduTools plugin.
That will allow us to create configurations with redirecting input,
it is useful for some cases, e.g. Codeforces support.
<!--
Hello and thank you for the pull request!
We don't have any strict rules about pull requests, but you might check
https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md
for some hints!
Note that we need an electronic CLA for contributions:
https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTING.md#cla
After you sign the CLA, please add your name to
https://github.com/intellij-rust/intellij-rust/blob/master/CONTRIBUTORS.txt
Also, please write a short description explaining your change in the following format: `changelog: %description%`
This description will help a lot …
=> Make CargoCommandConfiguration open

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt
Currently it searches for imports that are children of the file, and deletes them if they match the assumed use speck textuallty. It should instead delete based on `usageReference`, which doesn't work right now.
changelog: Fix inlining of functions that reside in a different module.
=> inline function from different module

src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt, src/main/kotlin/org/rust/ide/actions/InstallTargetAction.kt
Fixes #6714
In wasm-pack configuration before launch Build step checks if `wasm32-unknown-unknown` target is installed and suggests installing it if It is not.
=> RUN: Suggest to install wasm32 target in wasm-pack configuration

src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Recent version of GoLand 2021.1 supports Rust debugging via [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin so let's suggest installing it
changelog: Advertise [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin in GoLand
=> DBG: suggest to install Native Debugging Support plugin in GoLand

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/pull/6776#discussion_r570127570
Produces [E0116](https://doc.rust-lang.org/error-index.html#E0116) in code like:
```rust
impl dyn ForeignTrait {}
```
changelog: Support detecting [E0116](https://doc.rust-lang.org/error-index.html#E0116) for impls for trait objects
=> ANN: Support E0116 for impls for trait objects

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This fixes false-positive duplicate annotation when there are multiple underscore imports, e.g.
```Rust
use std::fmt::Debug as _;
use std::hash::Hash as _; // False-positive: A second item with name '_' imported 
```
Note, there was a similar problem with `RsConstant`  after implementing underscore constants parsing: https://github.com/intellij-rust/intellij-rust/pull/4724. But that problem was solved in a quite different way – by introducing `nameLikeElement` to distinguish the actual name from the underscores.
However, in this case, looks like it's enough to just ignore the underscore names during duplicates detection in order to keep untouched all the existing logic in the name resolution and auto import. Thanks to @dima74 for finding this out!
Fixes #5067
=> Ignore underscore names during duplicates detection

src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
E.g.
```rust
#[cfg(false)]
mod my {
fn bar() {}
//X
fn t() {
bar();
} //^
}
```
changelog: Fix resolve inside cfg-disabled inline mod in new resolve
=> RES: Fix resolve inside cfg-disabled inline mod in new resolve

src/main/kotlin/org/rust/ide/utils/CfgUtils.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
E.g. now such macro will not be expanded in new resolve (we don't expand cfg-disabled macros):
```rust
#![cfg(false)]
...
some_macro!();
```
Potentially this should slightly speed up [winapi crate](https://github.com/retep998/winapi-rs/blob/2f76bdea3a79817ccfab496fbd1786d5a697387b/src/lib.rs#L6)
changelog: Support file level cfg attributes in new resolve
=> Support file level cfg attributes in new resolve

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
E.g.
```rust
mod m {}
mod m {}
fn main() {
m::func();
} //^
```
changelog: Support basic multiresolve of inline modules in new resolve
=> RES: Support basic multiresolve of inline modules in new resolve

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/stubs/index/RsIncludeMacroIndex.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
E.g.:
```rust
// main.rs
() => {};
}
include!("foo.rs");
// foo.rs
foo!();
//^
```
Related: #6236 - [`Token` macro in `syn` crate](https://github.com/dtolnay/syn/blob/133a053fe67d5f360c0ad24370216e0052624dfc/src/token.rs#L882)
changelog: Fix resolve macro calls inside file included by `include!` macro when using new resolve
=> RES: Fix resolve macro calls inside included file when using new resolve

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Previously, `TyFunction` was considered as non-Copy and non-Clone type in terms of our type inference. Although there was a special case in `Ty.isMovesByDefault` to handle `TyFunction` properly during move analysis, it did not work in case of `TyFunction` used as a type parameter.
Now `TyFunction` is considered as `Copy` & `Clone` type so the special case in `Ty.isMovesByDefault` has been removed.
More information in Rust docs: [builtin `Clone` impls](https://doc.rust-lang.org/std/clone/trait.Clone.html#additional-implementors) and [builtin `Copy` impls](https://doc.rust-lang.org/std/marker/trait.Copy.html#additional-implementors).
Fixes https://github.com/intellij-rust/intellij-rust/issues/5165
changelog: Fix false-positive move errors on a function pointer type used as a type parameter
=> Provide builtin Clone & Copy impls for TyFunction

scripts/github.py, scripts/make_next_milestone.py
Previously, to get collect the latest milestones, we didn't specify `sort` and `direction` query params.
And GitHub API had might return milestones without the latest one (since GitHub uses pagination).
And as a result, "make next milestone" step on CI had might create next milestone without due_on date and with an incorrect release manager
Now both parameters are specified to make GitHub return the latest milestones by `due_on` property
=> CI: fix next milestone creation

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Because currently we don't build [DefMaps](https://github.com/intellij-rust/intellij-rust/issues/6217) for such crates in new resolve (for performance reasons)
changelog: Use old resolve in test/bench non-workspace crates
=> RES: Use old resolve in test/bench non-workspace crates

scripts/make_next_milestone.py
If during the last 5 milestones (= number of maintainers - 1) someone was a release manager twice or more times - `make_next_milestone.py` will raise `ValueError` [trying to remove](https://github.com/intellij-rust/intellij-rust/blob/e420b1949879e3e2a1ea9b05c3e243ceb1986f5d/scripts/make_next_milestone.py#L50) this person from the list of maintainers multiple times.
I guess it might happen when the release manager for a given release was manually altered (as the default assignee was sick, on vacation, etc.).
The fix should also cover the case when the release manager is someone outside of the regular `maintainers` list. That's probably would be a rare usecase if ever, but still.
Feel free to discard (or request changes) if `try / except` is not an ideal solution or you think the denoted …
=> CI: Skip already removed maintainer

src/test/kotlin/org/rust/ide/lineMarkers/LineMarkerTestHelper.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsLineMarkerProviderTestBase.kt, toml/src/main/kotlin/org/rust/toml/CargoFeatureLineMarkerProvider.kt, toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt, toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt, toml/src/test/kotlin/org/rust/toml/CargoTomlLineMarkerProviderTestBase.kt
The bug was introduced in #6623.
Also, these changes introduce `LineMarkerTestHelper` to avoid code duplication related to line marker tests
Fixes #6828
=> Properly change state of optional dependencies in Cargo toml

src/main/kotlin/org/rust/openapiext/RsPathManager.kt
Found out all binaries of native-helper lose executable permissions in two places: during uploading/downloading artifacts on CI and during unzipping plugin archive. As a result, all features that may use native helper (fetching info about items generated by build scripts and future proc macro support #6564) don't work
These changes restore executable permissions manually.
changelog: Fix fetching info about items generated by build scripts. Note, the corresponding feature work only when `org.rust.cargo.evaluate.build.scripts` experimental feature is enabled
=> Make native helper binary executable

src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6873.
changelog: TODO
=> REF: Omit unchanged default type argument only if the next type argument is already ommited

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
I started working on suggested refactoring for functions using the new change signature refactoring, but I realized that it's not that useful without default value parameters, so first I'll begin with this PR.
Unresolved questions:
1) What about error checking? Should we somehow check that the default value expression's type is compatible with the parameter type? Or just do a basic sanity check that the expression should be parsed?
2) What to do about importing types from the default value expression? The trick with storing the type reference from the parameter type code fragment no longer works here, because the type reference created in the dialog has its context set to the refactored function. We need a type reference with a context set to each specific function call for it to work, …
=> REF: allow choosing default values for new parameters in ChangeSignature

src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
The recent version of PyCharm Pro 2021.1 supports Rust debugging via [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin so let's suggest installing it
changelog: Advertise [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin in PyCharm Pro
=> DBG: advertise native debugging support plugin in PyCharm Pro

.github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml
Previously, we Rust plugin was published before TOML plugin. As a result, Marketplace launched its compatibility verification task for Rust plugin with old TOML plugin and had might produce false positive warnings in case of incompatible changes in TOML plugin and the corresponding changes in Rust plugin.
For example, for 140 release Marketplace produces the following:
Now, TOML plugin is published before Rust one to avoid such situations
=> CI: change publish order of TOML and Rust plugins

src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringSupport.kt, src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsRenameSuggestedRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
Previously, `RsSuggestedRefactoringSupport.isDeclaration` checked that pat binding is not constant that required name resolution and consequently index info. But `isDeclaration` can be called during indexing that led to `IndexNotReadyException`.
Now, rename refactoring is suppressed by `RsSuggestedRefactoringAvailability` that can perform name resolution
Fixes #6833
changelog: Don't throw an exception on changing name of local variable during indexing
=> REF: don't throw exception on changing name of local variable during indexing

src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt, src/main/resources/META-INF/rust-core.xml
Here is comparison of resolve times (all references in all files of crate) for different crates:
**New resolve**:
project | default threshold | no threshold | difference
-- | -- | -- | --
juniper | 22312 | 22147 | -0.01
diesel | 17459 | 17548 | 0.01
mysql_async | 4298 | 4368 | 0.02
amethyst | 1850 | 2110 | 0.14
tokio | 7198 | 7548 | 0.05
xi_editor | 311 | 414 | 0.33
Cargo | 11356 | 12068 | 0.06
clap | 4744 | 5010 | 0.06
nalgebra | 25836 | 29719 | 0.15
winapi | 4754 | 5260 | 0.11
**Old resolve**:
project | default threshold | no threshold | difference
-- | -- | -- | --
juniper | 22064 | 23433 | 0.06
diesel | 17263 | 17663 | 0.02
mysql_async | 4472 | 5018 | 0.12
amethyst | 1924 | 3218 | 0.67
tokio | 7983 | 8371 | 0.05
xi_editor | 397 | 884 | 1.23
Cargo | 12763 | 13134 | 0.03
clap | 4856 | …
=> RES: Disable type aliases threshold in new resolve

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Fix cases like:
```rust
#[cfg(not(intellij_rust))]
mod mod1 {
pub fn func() {}
}
mod mod2 {
pub fn func() {}
}        //X
#[cfg(not(intellij_rust))]
use mod1::func;
use mod2::*;
fn main() {
func();
} //^
```
changelog: Fix that cfg-enabled glob import should override cfg-disabled named import when using new name resolution engine
=> RES: Fix that cfg-enabled glob import overrides cfg-disabled named import

CONTRIBUTORS.txt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt, src/main/kotlin/org/rust/cargo/runconfig/RsCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt
changelog: if run configuration returns non-empty `SMTRunnerConsoleProperties`, Code With Me client treats it as tests and reserves test toolwindow for it. The suggested fix ensures that properties are provided only for the case when test toolwindow  is shown on host
https://youtrack.jetbrains.com/issue/CWM-2044
=> avoid empty test tool window on the Code With Me client (CWM-2044)

src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt
This removes extra files from search.
Additionally, `libc-test` exclusion fixes some test failures on the old Rust 1.32.0.
=> Exclude more stdlib parts from the index

intellij-toml/src/main/resources/META-INF/plugin.xml, intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt
Fixes #6884
changelog: Toml syntax highlighting is now available in `Cargo.toml.orig` files
=> Associate `Cargo.toml.orig` files with TOML file type

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
changelog: Omit unchanged default type parameters of return type in `Extract Function` refactoring
=> REF: Omit unchanged default type parameters of return type in ExtractFunction

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Based on the comments in #6390.
1. Made `CratesLocalIndexState`'s field immutable
2. Clarified `isReady` by a doc comment, not sure what's the better name for it can be
=> Improve CratesLocalIndexService internals

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/FeatureGraph.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/test/kotlin/org/rust/common.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
This also fixes `regressions-1` CI workflow.
changelog: Fix cargo features state inference on renamed packages
=> Fix cargo features state inference on renamed packages

src/main/kotlin/org/rust/lang/core/macros/DocsLowering.kt, src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/doc/psi/RsDocKind.kt, src/main/kotlin/org/rust/lang/utils/RsEscapesUtils.kt, src/test/kotlin/org/rust/lang/core/macros/DocsLoweringTest.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsErrorChainMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/doc/RsDocRemoveDecorationTest.kt, src/test/kotlin/org/rust/lang/utils/RsEscapesUtilsTest.kt
Rustc replaces doc comments like `/// foo` to attributes `#[doc = "foo"]` before macro expansion. We did it a bit wrongly, but it was not a problem because we were able to generate quick docs from them ourselves. But recently we started to support proc macros, and proc macros can see these lowered docs. This sometimes leads to expansion failures because a proc macro can expect some specific lowering. Now we lower docs correctly, I hope.
Also, I tweaked docs undecoraing so that it understands such lowering.
This should not appear in changelog if it merged into the same release as proc macro.
=> MACRO: fix doc comments lowering

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes #6774
changelog: Fix false-positive [E0252](https://doc.rust-lang.org/error-index.html#E0252) "A second item with name ... imported" error for textual vs scoped macro
=> ANN: Fix E0252 false-positive for scoped vs textual macros

src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReference.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/types/BoundElement.kt, src/main/kotlin/org/rust/lang/core/types/infer/PatternMatching.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Adds methods `resolveIfVisible` and `multiResolveIfVisible` to `RsPathReference` class (works only with new resolve; with old resolve they are equivalent to `resolve` and `multiResolve`). They can be used in refactorings and intentions, e.g. to fix "A second item with name ... imported" false-positive:
```rust
mod mod1 {
fn foo() {}
pub struct foo {}
}
mod mod2 {
pub fn foo() {}
}
use mod1::foo;  // foo func is private, so no conflict with `mod2::foo`
use mod2::foo;
```
changelog: Fix false-positive [E0252](https://doc.rust-lang.org/error-index.html#E0252) "A second item with name ... imported" error for private items
=> RES: Add method to RsPathReference to resolve only public items

build.gradle.kts
It was included into plugin archive by accident in #6847.
Note, we shouldn't include kotlin stdlib jar files into the plugin because the platform already contains all necessary kotlin runtime and own kotlin stdlib libs can conflict with platform ones
bors r+
=> GRD: exclude kotlin-stdlib-common jar from the plugin

src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt, src/main/kotlin/org/rust/stdext/BitFlagsBuilder.kt
Internal. Simplifies bitmask creation and makes it less error-prone. 
How we crated bitmasks before:
```kotlin
companion object {
private val NAMESPACE_TYPES_MASK: Int = makeBitMask(0)
private val NAMESPACE_VALUES_MASK: Int = makeBitMask(1)
private val NAMESPACE_MACROS_MASK: Int = makeBitMask(2)
}
```
And how we can create them now:
```kotlin
companion object : BitFlagsBuilder(Limit.BYTE) {
private val NAMESPACE_TYPES_MASK: Int = nextBitMask()
private val NAMESPACE_VALUES_MASK: Int = nextBitMask()
private val NAMESPACE_MACROS_MASK: Int = nextBitMask()
}
```
Also, it's possible to "extend" another bitmask:
```kotlin
object Foo : BitFlagsBuilder(Limit.BYTE) {
private val ONE: Int = nextBitMask() // 0
private val TWO: Int = nextBitMask() // 1
}
object Bar : BitFlagsBuilder(Foo, Limit.BYTE) { …
```
=> Simplify bit flags creation

src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroData.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt, src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActionsTest.kt
Initial groundwork for built-in macros support (like `concat!()`).
Now these macros are not expanded as "{}" (as before)
changelog: INTERNAL: Add initial infrastructure for builtin macro expansion, FIX: Do not expand builtin macros as "{}"
=> Do not expand builtin macros as "{}"

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6454.
changelog: Take into account const generics in inspections about generic parameters/arguments ordering
=> ANN: Take into account const generics in inspections about generic parameters/arguments ordering

gradle.properties
changelog: Use 2021.1 platform as a default for development
=> GRD: use 211 as default platform for development

src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/formatter/RsAutoIndentTest.kt
Initial:
```rust
fn main() {
let a = [/*caret*/];
}
```
<enter> typed, before this PR:
```rust
fn main() {
let a = [
/*caret*/];
}
```
<enter> typed, now:
```rust
fn main() {
let a = [
/*caret*/
];
}
```
changelog: auto-indent line when typing <enter> inside an array literal
=> TYPE: auto-indent line when typing <enter> inside an array literal

build.gradle.kts
It should also fix jbr loading by `runIde` gradle task for 211 platform
bors r+
=> GRD: update gradle-intellij plugin

src/main/kotlin/org/rust/ide/formatter/RsFormattingModelBuilder.kt, src/main/kotlin/org/rust/ide/formatter/blocks/RsMacroArgFmtBlock.kt, src/test/kotlin/org/rust/ide/formatter/RsAutoIndentMacrosTest.kt
Previously there was absolutely no auto-indentation in macro (call&def) bodies. Now there is a simple syntax tree-based auto-indentation (based on a token tree `{}`/`()`/`[]` nesting).
changelog: auto-indent line when typing `<enter>` in macro bodies
=> TYPE&FMT: auto-indent line when typing <enter> in macro bodies

src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Store correct `mixHash` for proc macros
changelog: should not be mentioned in changelog if merged into release-143
=> Fix crashes on 2021.1 when proc macros are enabled

debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt, src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt, src/main/kotlin/org/rust/debugger/utils.kt
Current restrictions:
- the support works starting 2021.1 EAPs
- only [Rider for Unreal Engine](https://www.jetbrains.com/lp/rider-unreal/) is supported for now
- only LLDB
Part of #5422
changelog: Provide debugging in [Rider for Unreal Engine](https://www.jetbrains.com/lp/rider-unreal/) 2021.1
=> DBG: debugger support for Rider for Unreal Engine 2021.1

src/main/kotlin/org/rust/lang/core/CompilerFeature.kt
changelog: Fix false-positive [E0658](https://doc.rust-lang.org/error-index.html#E0658) in stdlib
=> ANN: fix false positive E0658 in stdlib

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
Fixes #6883
changelog: Don't show `` Redundant `::` `` warning for expressions inside length of array types
=> ANN: fix false-positive redundant `::` annotation in array types

src/main/kotlin/org/rust/ide/actions/RsMoveLeftRightHandler.kt, src/test/kotlin/org/rust/ide/actions/RsMoveLeftRightHandlerTest.kt
Part of #3985
changelog: support `Move Element Right/Left` actions for const generic parameters
=> ACT: support `Move Element Right/Left` actions for const generic parameters

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
| - | - |
| ![](https://user-images.githubusercontent.com/2539310/111044077-72eba880-8457-11eb-840d-7496723212a2.png) | ![](https://user-images.githubusercontent.com/2539310/111044079-77b05c80-8457-11eb-9f3c-d5d18d6486fb.png) |
Part of #3985
changelog: Properly render const generics in signature of top-level items
=> QDOC: properly render const generics in signature of top-level items

src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Fixes #6186
Depends on https://github.com/intellij-rust/intellij-rust/pull/6948.
changelog: Don't insert default type parameters by `Implement Member` actions
=> REF: Don't insert default type parameters by Implement Member actions

src/main/resources/META-INF/rust-core.xml
There are `RsSimplifyBooleanExpressionInspection` and `SimplifyBooleanExpressionIntention`. Inspection is offered only for pure expressions, and intention is always offered. Inspection was disabled in e0962ec008e9ed9f8031ecd3d12ca57be1b20fbb because of bug which however was fixed in #1001
changelog: Enable by default "Simplify boolean expression" inspection
=> ANN: Enable by default "Simplify boolean expression" inspection

pretty_printers_tests/lldb_batchmode.py
Method `time.clock()` was removed in Python 3.8
=> T: Fix pretty printer tests on Python 3.8

src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt, src/main/kotlin/org/rust/ide/actions/mover/RsMatchArmUpDownMover.kt, src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt, src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt
Fixes #6710
changelog: Do not move the entire `match` arm in [`Move Statement Up/Down`](https://www.jetbrains.com/help/idea/working-with-source-code.html#move-statements) action (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Up</kbd>/<kbd>Down</kbd>) invoked on the statement inside the arm body
=> Up/Down mover: move statements in match arm body

src/main/kotlin/org/rust/cargo/runconfig/command/CompositeCargoRunConfigurationProducer.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6646.
=> RUN: Ignore environment variables when comparing Cargo run configurations

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveRetargetReferencesProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Fixes #5952
changelog: Support import aliases in Move refactoring (<kbd>F6</kbd> or `Refactor | Move`)
=> REF: Support import aliases in Move refactoring

.github/workflows/check.yml, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Extract compilation of native helper into separate job on CI with the corresponding cache. It allows:
- create closer to production environment for tests
- reducing total execution time of `check` workflow because now we compile native helper for each supported target (three currently) only once instead of compilation in each `check-plugin` job. Caching of native helper artifact also decrease compilation time
=> CI: speed up check workflow

.github/workflows/check.yml, prettyPrinters/gdb_lookup.py, prettyPrinters/gdb_providers.py, prettyPrinters/lldb_lookup.py, prettyPrinters/lldb_providers.py, pretty_printers_tests/src/main.rs, pretty_printers_tests/src/test_runner.rs, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/RsToolchain.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt, src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt, src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
And drop all (or almost all) code for rustic below 1.41
changelog: Increase minimal supported rustc version to 1.41.0
=> Increase minimal supported rustc version to 1.41.0

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/lang/core/macros/ExpandedMacroStorage.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/test/kotlin/org/rust/MockCargoFeatures.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroCallUnderCfgTest.kt
Fixes a bug: when a nested cfg-disabled macro calls becomes cfg-enabled (for example, when a user enables some Cargo feature that previously was disabled), the macro call remains unexpanded (disabled)
=> Fix macro calls under cfg

src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6963.
changelog: Use the default Project Rust toolchain when creating a new project
=> Use the default Project Rust toolchain when creating a new project

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
changelog: Import unresolved types from the function signature after `Extract Function` refactoring
=> REF: Import types after Extract Function refactoring

src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsWrongGenericArgumentsNumber.html, src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/5753.
changelog: Support const generics in [E0107](https://doc.rust-lang.org/error-index.html#E0107) inspection
=> ANN: Support const generics in E0107 inspection

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/UnwrapToMatchIntention.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/resources/intentionDescriptions/CreateFunctionIntention/after.rs.template, src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/after.rs.template, src/main/resources/intentionDescriptions/SubstituteAssociatedTypeIntention/before.rs.template, src/main/resources/intentionDescriptions/UnwrapToMatchIntention/after.rs.template, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/UnwrapToMatchIntentionTest.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
=>  Use todo!() instead of unimplemented!() in generated bodies of implemented members.

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
=> TY: fix unification with `!` in match arms

src/main/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplate.kt, src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt, src/main/kotlin/org/rust/ide/template/postfix/surrounderBasedPostfixTemplates.kt, src/main/kotlin/org/rust/ide/template/postfix/utils.kt, src/test/kotlin/org/rust/ide/template/postfix/DerefPostfixTemplateTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6964.
changelog: Don't suggest postfix templates inside string literals
=> COMP: Don't suggest postfix templates inside string literals

intellij-toml/src/main/kotlin/org/toml/ide/inspections/TomlUnresolvedReferenceInspection.kt, intellij-toml/src/main/resources/META-INF/plugin.xml, intellij-toml/src/main/resources/inspectionDescriptions/TomlUnresolvedReference.html, toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlUnresolvedPathReferenceInspectionTest.kt
This PR adds an inspection for annotating unresolved references in `TOML` files.
Closes: https://github.com/intellij-rust/intellij-rust/pull/5439
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4144
changelog: Add inspection that annotates invalid references in `TOML` string literals. The inspection can be extended by other plugins. For example, Rust plugin provides file references to local dependency, build script and workspace paths in `Cargo.toml` as well as references to Cargo [features](https://doc.rust-lang.org/cargo/reference/features.html) and the inspection highlights all unresolved ones. Additionally, it provides a quick-fix to create a non-existent file from the corresponding file reference.
=> TOML: add TomlUnresolvedReferenceInspection

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
changelog: Don't import default type parameters by `Extract Function` refactoring (`Refactor | Extract | Method` or <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>M</kbd>)
=> REF: don't import default type parameters by `Extract Function` refactoring

src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
This test was changed in #6721 and actually since then it should fail with old resolve (at least it fails if I try locally). Not sure why it started to fail on CI only now. This test was originally created for new resolve only, so lets run this test only with new resolve.
=> T: Fix "test import to mod shadowed by expanded mod"

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6942.
changelog: Annotate wrong order of const generic parameters without `const_generics` feature
=> ANN: Annotate wrong order of const generic parameters without `const_generics` feature

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Fixes #7009
changelog: fix array indexing on Rust 1.50.0
=> TY: hotfix array indexing on Rust 1.50.0

src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
=> Fix control flow of break/continue expanded from a macro

.idea/dictionaries/intellij_rust.xml, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspection.kt, src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsUnreachableCode.html, src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
This PR introduces `Unreachable code` inspection to detect and remove unreachable code.
Note that now it might produce some false-positive warnings due to https://github.com/intellij-rust/intellij-rust/issues/6749 and https://github.com/intellij-rust/intellij-rust/issues/6797, so probably it's better to try fixing these issues before merging this. 
Some implementation details:
* Based on the control-flow graph which is already used for several inspections (move analysis, liveness analysis)
* Found unreachable elements are cached by `org.rust.lang.core.types.ExtensionsKt#CONTROL_FLOW_KEY` as well as the  graph itself
* Does not highlight each unreachable element separately, but merges their text ranges instead in order to highlight the widest range
Part of …
=> INSP: Implement unreachable code detection

toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt, toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProviderTest.kt
changelog: Make dependencies completion in `Cargo.toml` more intuitive and faster when using crates local index. Note, this feature is disabled by default for now. To use it, enable `org.rust.crates.local.index` experimental feature
=> COMP: Improve dependency completion when using crates local index

src/main/kotlin/org/rust/ide/annotator/fixes/AddAsTyFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToStrFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingFromTraitFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTraitFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyUsingTryFromTraitFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ConvertToTyWithDerefsRefsFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToBorrowedTyFixTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToBorrowedTyWithMutFixTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToMutTyFixTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToRefTyFixTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyUsingFromTraitFixTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ConvertToTyUsingTraitMethodFixTestBase.kt
These changes:
- refactor `Convert to type` quick-fixes. All common code is extracted into a single place, new base `ConvertToTyFix` class.
Also, now you can only pass `RsExpr` to the corresponding quick-fixes instead of any psi object
- omit default type parameters in a quick-fix text
changelog: Omit default type parameters in a `Convert to type` quick-fix text
=> Improve `Convert to type` quick-fixes

.github/workflows/check.yml
It slows down workflow execution (especially on Windows). Now `verifyPlugin` task is launched only once per platform version
=> CI: don't run `verifyPlugin` task in each matrix job of check workflow

src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Fix exception when macro with `local_inner_macros` expands to `extern crate`
```
java.lang.IllegalArgumentException: Array has more than one element.
at kotlin.collections.ArraysKt___ArraysKt.single(_Arrays.kt:2775)
at org.rust.lang.core.resolve2.DefCollector.resolveImport(DefCollector.kt:112)
at org.rust.lang.core.resolve2.DefCollector.resolveImports(DefCollector.kt:84)
at org.rust.lang.core.resolve2.DefCollector.collect(DefCollector.kt:69)
at org.rust.lang.core.resolve2.FacadeBuildDefMapKt.buildDefMap(FacadeBuildDefMap.kt:31)
```
No entry in changelog since it is a hotfix for #7014
=> RES: Fix macro with `local_inner_macros` expanded to `extern crate`

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
Implements basic multiresolve at module scope in new resolve, e.g. for explicitly declared item vs imported item with same name. This is needed mostly for cases when `evaluate build scripts` option is disabled, so there are a lot of items with same name with `unknown` cfg status, which is treated as `enabled`.
There are a lot of regressions in tokio crate, but actually its OK because:
* Old resolve has proper multiresolve => when something multiresolves, we have proper error
* New resolve didn't have proper multiresolve => when something multiresolves, random item was chosen, so we don't have errors
* After this PR we have basic multiresolve in new resolve => when something multiresolves, we have proper error
changelog: Basic multiresolve at module scope in new resolve
=> RES: Basic multiresolve at module scope in new resolve

build.gradle.kts, src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt
changelog: Now it's possible to use stdlib API appeared in Kotlin 1.4
=> Bump kotlin api version to 1.4

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Bug introduced by changes in #6898. Using `val` for a state field doesn't make it possible to serialize and save it, so it was being ignored.
changelog: Fix unnecessary reload of crates local index after IDE restart.
=> Fix crates local index state updates

src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt
When `org.rust.cargo.fetch.actual.stdlib.metadata` feature is enabled, we know that stdlib crates have build scripts.
Previously, we tried to evaluate unknown cfg options that led to unresolved references in some cases.
For example, `panic!` macro has two versions with `cfg(bootstrap)` and `cfg(not(bootstrap))` on 1.51.0 and in combination with the current name resolution engine, it cannot be resolved.
Now the plugin doesn't evaluate unknown options (at least temporarily) in stdlib crates.
changelog: Fix name resolution of items in standard library with `cfg` attribute in some cases
=> Do not evaluate unknown cfg to false in stdlib crates

build.gradle.kts, toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt, toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlCompletionTestBase.kt, toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt
Gives the ability to compare crate versions using semantic versioning and sort them this way instead of the default in index version uploading date order. That's useful for completion and inspections in the future.
Related: #6463
changelog: Use semantic versioning to improve version sorting in dependencies when using experimental local crates index
=> CARGO: Use semver to sort crate versions

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Filters out cfg-disabled items in completion and ignores them in resolve. Note that it currently doesn't apply to out-of-scope items added to completion using auto-import
changelog: Exclude some cfg-disabled items from completion when using new name resolution engine
=> RES: Filter out cfg-disabled items during resolve and completion in new resolve

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsModItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPathReferenceElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/stubs/StubInterfaces.kt, src/main/kotlin/org/rust/lang/core/stubs/common/PsiOrStubInterfaces.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLintLevelTest.kt
Internal. Now `QueryAttributes` can be used without PSI
=> Implement stub-only `QueryAttributes` API

src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt
In the case of language injection, crate information may not be present in the context.
Fixed #7044
=> ANN: If no `crate` exists, no check is performed

toml/src/main/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyCompletionProvider.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt
Part of #6463
Fixes #6812
Check for the readiness of the crates local index before performing completions and inspections. This should reduce the number of false-positives happening while the index is not ready yet.
=> INSP&COMP: Use exceptions to check whether index is updating

src/main/kotlin/org/rust/ide/intentions/RunCargoExpandIntention.kt
The change makes IDE place the intention below other general intentions in the intention list.
Also, now the intention isn't launched under write action because it doesn't change code
| - | - |
| ![](https://user-images.githubusercontent.com/2539310/114149005-175fee00-9923-11eb-8baa-ad9176934d5e.png) | ![](https://user-images.githubusercontent.com/2539310/114149032-1fb82900-9923-11eb-8d14-957392021716.png) |
changelog: place `Show the result of macro expansion` intention lower in the intention list
=> INT: make `Show the result of macro expansion` intention low priority

src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7075
changelog: Correctly place function visibility after attributes in Change signature refactoring.
=> FIX: correctly place visibility in ChangeSignature with attributes

src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt, src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt, src/main/kotlin/org/rust/ide/refactoring/RsMultipleVariableRenamer.kt, src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt, src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/resources/intentionDescriptions/DestructureIntention/after.rs.template, src/main/resources/intentionDescriptions/DestructureIntention/before.rs.template, src/test/kotlin/org/rust/ide/intentions/DestructureIntentionTest.kt
This is a revival of an older PR by @fan-tom (https://github.com/intellij-rust/intellij-rust/pull/4095). It adds support for replacing usages of field/tuple bindings after performing `DestructureIntention`. Both field lookup replacement (`s.0 -> _0`) and whole item replacement (`foo(s) -> foo((_0, _1))`) is supported. Method calls on the original binding are ignored, as the user probably doesn't want to transform them to
`S { x, y }.foo()`.
To rename multiple introduced bindings at once, I needed something that combines TemplateBuilder (renames multiple things in a single editing session) and `RsInPlaceVariableIntroducer` (renames occurrences of a renamed item). I created `RsMultipleVariableIntroducer`, which invokes the `RsInPlaceVariableIntroducer` repeatedly. It's probably a horrible …
=> INT: replace usages in DestructureIntention

src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7077
changelog: Do not needlessly import default type arguments in ChangeSignature refactoring
=> FIX: do not import default type arguments in ChangeSignature refactoring

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Fix resolve of macros with absolute paths, e.g. `::test_package::foo!()`
Fixes #7010
changelog: Fix resolve of macros with absolute paths with new name resolution engine
=> RES: Fix resolve of macros with absolute paths in new resolve

src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt, toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt, toml/src/main/kotlin/org/rust/toml/intentions/TomlElementBaseIntentionAction.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/after.rs.template, toml/src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/before.rs.template, toml/src/main/resources/intentionDescriptions/ExpandDependencySpecificationIntention/description.html, toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt, toml/src/test/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntentionTest.kt
Related to #4869
changelog: Add intention to expand dependency specification in `Cargo.toml`
=> INT: Introduce expand dependency specification intention

src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt, src/main/kotlin/org/rust/ide/formatter/impl/spacing.kt, src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt, src/test/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFixTest.kt, src/test/kotlin/org/rust/ide/formatter/RsFormatterLineBreaksTest.kt, src/test/kotlin/org/rust/ide/formatter/RsFormatterTest.kt, src/test/kotlin/org/rust/ide/formatter/RsTrailingCommaFormatProcessorTest.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractEnumVariantTest.kt, src/test/resources/org/rust/ide/formatter/fixtures/expressions_after.rs, src/test/resources/org/rust/ide/formatter/fixtures/issue569_after.rs, src/test/resources/org/rust/ide/formatter/fixtures/items_after.rs
This PR forces a line break after a left opening brace in struct blocks. This should bring struct block formatting closer to rustfmt. This change will probably ruin more tests, let's see what CI says.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/5282
=> FMT: add line break after opening brace in struct blocks

src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt, src/main/kotlin/org/rust/ide/intentions/ShareInPlaygroundIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/ShareInPlaygroundIntention/after.rs.template, src/main/resources/intentionDescriptions/ShareInPlaygroundIntention/before.rs.template, src/main/resources/intentionDescriptions/ShareInPlaygroundIntention/description.html, src/test/kotlin/org/rust/ide/actions/ShareInPlaygroundActionTest.kt, src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt, src/test/kotlin/org/rust/ide/intentions/ShareInPlaygroundIntentionTest.kt
It should promote the corresponding feature because `Alt`+`Enter` is one of the most popular shortcuts in IntelliJ IDEs
changelog: provide `Share in Playground` intention to share selected Rust code on [Rust Playground](https://play.rust-lang.org)
=> INT: provide `Share in Playground` action as intention for selected Rust code

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
`ChangeSignature` had a bug where it was incorrectly producing a name conflict between e.g. modules and the refactored function, which is incorrect. I found out about it randomly while testing it.
I was aware of this imperfection while implementing the refactoring, but I thought that because functions and types (like structs) have different naming conventions, it should not be a big deal. Well, turns out that modules kind of break that assumption :) Now it should be working properly.
```rust
mod foo {}
fn foo/*caret*/() {}
```
Running the refactoring on this function should not produce name visibility conflicts after this PR.
changelog: Fix some false positives in name conflict detection in ChangeSignature refactoring.
=> FIX: check namespaces in ChangeSignature name conflict detection

CONTRIBUTORS.txt, intellij-toml/src/main/resources/META-INF/plugin.xml, intellij-toml/src/test/kotlin/org/toml/lang/TomlFileTypeTest.kt
changelog: Consider poetry.lock as TOML file
=> Associate `poetry.lock` files with TOML file type

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt, src/main/kotlin/org/rust/ide/intentions/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Initial preparation for 2021 edition. It should only support parsing `2021` edition from cargo metadata. All user-visible features should be the same as for `2018` edition
Part of #6902 
changelog: Introduce `2021` edition variant in the plugin and adjust the corresponding code
=> Introduce EDITION_2021

.gitignore, build.gradle.kts, gradle.properties, settings.gradle.kts
From [Gradle docs](https://docs.gradle.org/current/userguide/build_cache.html):
> The Gradle build cache is a cache mechanism that aims to save time by reusing
> outputs produced by other builds. The build cache works by storing build outputs
> and allowing builds to fetch these outputs from the cache when it is determined
> that inputs have not changed, avoiding the expensive work of regenerating them.
In short, now we have a directory `build-cache` where Gradle puts all
(intermediate) build outputs it ever produces and reuses them if possible, 
so frequent git branch switching or IntelliJ platform version switching 
does not cause long build times.
In order to prevent constant growth of `build-cache` there is a mechanism that
removes cached entries that have not been accessed for 30 …
=> GRD: enable Gradle Build Cache

src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/ToggleFeatureIntention/after.rs.template, src/main/resources/intentionDescriptions/ToggleFeatureIntention/before.rs.template, src/main/resources/intentionDescriptions/ToggleFeatureIntention/description.html, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
This PR adds a simple intention that toggles feature state. It can be invoked from `cfg` feature attributes.
I needed an intention test with a toolchain, so the test inherits from `RsWithToolchainTestBase` and reimplements a small amount of logic from `RsIntentionTestBase`.
Related issue: https://github.com/intellij-rust/intellij-rust/issues/4693
changelog: Add intention that toggles feature state from a cfg attribute
=> INT: add intention to toggle feature state from cfg attribute

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CustomTargetCfgResolveTest.kt
Now the plugin use `cargo rustc --print cfg` instead of raw `rustc --print cfg` that allows taking [Cargo config](https://doc.rust-lang.org/cargo/reference/config.html) into account, i.e. fetch cfg options for custom build target, `RUSTFLAGS`, etc.
As a result, evaluation of `cfg` attributes also takes such custom options into account and users can set up them.
Note, `cargo rustc --print cfg` option is available only since Rust 1.52. With older toolchain, the plugin uses host `cfg` options
Fixes #5183
Part of #6104
Related to https://github.com/rust-lang/cargo/issues/9342
changelog: Now the plugin takes [Cargo config](https://doc.rust-lang.org/cargo/reference/config.html) into account during evaluation of `cfg` conditions. Note, it works since Rust 1.52.0
=> CARGO: fetch cfg options according to Cargo config

src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt, src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt
Some improvements to #6845
1. make `ToggleFeatureIntention` a high priority action. Since the intention has a lower availability scope (a feature meta item only) I think it should have a higher priority than intentions with wider scope:
2. extend availability range of `ToggleFeatureIntention`
The intention is now available in the entire meta item, not only in the feature name:
```
#[cfg(feature = "foo")]
//    ~~~~~~~~~~~~~~~
```
changelog: should not be mentioned in the changelog if placed in the same release as #6845
=> INT: prioritize `ToggleFeatureIntention` and extend its availability range

src/main/kotlin/org/rust/cargo/project/model/impl/CargoTomlWatcher.kt
The bug was introduced in #5679. Editing `Cargo.toml` in a workspace root did not caused refresh of the Cargo project
=> Refresh Cargo project when workspace `Cargo.toml` is changed

src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7092
changelog: Remove false positive in RsNeedlessLifetimesInspection when the lifetime is used in where clause.
=> FIX: better check where clause in RsNeedlessLifetimesInspection

src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt
Fixed #7058 
Fixed #4401
changelog: Support for `imports` and `method bodies` options in `Code Folding - General` settings
=> Support for `imports` and `method bodies` options in `Code Folding`

src/main/kotlin/org/rust/ide/navigationToolbar/RsNavBarModelExtension.kt, src/main/resources/META-INF/rust-core.xml
While working on something else, I noticed that IDEA has these cool new breadcrumbs directly inside the navigation bar. So I looked at the Kotlin to find inspiration and implemented it also for the Rust plugin, by reusing the implementation of the breadcrumbs provider.
The Kotlin plugin [disables](https://github.com/JetBrains/kotlin/blob/master/idea/src/org/jetbrains/kotlin/idea/codeInsight/BreadcrumbsProviderCompatBase.kt#L14) classic breadcrumbs when the navigation bar model is enabled, but I suppose it doesn't hurt to show both?
changelog: Introduce navigation bar breadcrumbs.
=> IDE: add support for navbar breadcrumbs

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Fixes this case:
```
fn main() {
let foo = 62;
//X
let _ = UnknownStruct { foo };
}                          //^
```
changelog: fix name resolution of field shorthand to a local variable in the case of unresolved struct literal
=> RES: fix resolve of field shorthand in unknown struct literal

src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/CreateStructIntention/after.rs.template, src/main/resources/intentionDescriptions/CreateStructIntention/before.rs.template, src/main/resources/intentionDescriptions/CreateStructIntention/description.html, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt
This PR adds an intention to create a struct from an unresolved struct literal (similar to https://github.com/intellij-rust/intellij-rust/pull/5505).
I'm not sure what template to offer the user after the struct is created. In the intention for creating functions, we create a template builder that allows the user to change the name and type of each parameter. However, here a template builder is not good enough, because if the user decides to rename the field, the usage from which the struct was created would suddenly contain an invalid field name. Therefore, I borrowed `RsMultipleVariableRenamer` from https://github.com/intellij-rust/intellij-rust/pull/5650 to propagate the field name changes to the struct literal. But with this, it doesn't allow the user to change the field type.
Should …
=> INT: add intention to create a struct

src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
This PR changes how `CreateFunctionIntention` treats function call expressions with unknown expected return types. Previously, it collapsed them to `TyUnit`, so the created function didn't have any return type. This was problematic in scenarios like this:
```rust
let foo = bar(42i8); // missing return type
```
as noted by @lancelote (https://github.com/intellij-rust/intellij-rust/issues/6978).
After inspecting the issue, I realized that this can happen in more cases:
```rust
let foo: UnknownType = bar(); // let decl with unknown type
fn baz(a: UnknownType) {}
baz(bar());  // argument with unknown type
```
In all these cases, the user will most likely want to enter the return type right away. Therefore I created a general heuristic that tries to guess if the user will want to enter the …
=> INT: use template for unknown return type in CreateFunctionIntention

grazie/src/main/kotlin/org/rust/grazie/RsGrammarCheckingStrategy.kt, grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
Also, don't use yet another deprecated API
Fixes #7024
changelog: Fix false-positive proofreading warnings for sentences written in several sequential Rust comments. Note, you can enable/disable proofreading in Rust files in `Preferences | Editor | Proofreading | Grammar` settings
=> INSP: properly proofread single sentence in sequential Rust comments

src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
The feature was an initial attempt to support `include` macro with `OUT_DIR` variable.
It has two major issues:
- invocation of Cargo with `--build-plan` option forces Cargo to recompile everything from the scratch next time
- the option is supposed to be [removed](https://github.com/rust-lang/cargo/issues/7614).
Also, there is a more powerful feature - `org.rust.cargo.evaluate.build.scripts` that allows plugin to know about all generated `cfg` options and environment variables (including `OUT_DIR`).
So I think we can drop `--build-plan` support since it has major cons and can be superseded by `org.rust.cargo.evaluate.build.scripts` feature
changelog: Drop support of `org.rust.cargo.evaluate.build.scripts` experimental feature. Use `org.rust.cargo.evaluate.build.scripts` instead if you …
=> CARGO: drop `org.rust.cargo.fetch.out.dir` feature

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Now the plugin should correctly resolve this:
```rust
#[foo::bar] // Resolve `foo::bar`
fn baz() {}
```
Fixes #4481
changelog: correctly resolve qualified attribute proc macro paths (like `#[foo::bar]`)
=> RES: resolve qualified attribute proc macro paths

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoProjectDeduplicationTest.kt
There are 2 kinds of cargo project duplication:
1. Direct duplication: when there are 2 projects with the same
`CargoProject.manifest` value. Looks like it's impossible to
make such duplication without editing `workspace.xml`.
2. Duplication of workspace members: when there is a project
with cargo workspace consist of several packages and one of them
is also added as a separate `CargoProject`. It's possible to
make such duplication: initially, there should be 2 independent
`CargoProject`s, but then, one of them should become a workspace
member of the other project (a user can do this by modifying
`Cargo.toml`)
Let's remove duplicated projects during `CargoSyncTask`
=> Deduplicate cargo projects

toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt, toml/src/main/kotlin/org/rust/toml/Util.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CrateVersionRequirement.kt, toml/src/main/kotlin/org/rust/toml/inspections/CargoDependencyCrateVisitor.kt, toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlCyclicFeatureInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/CargoTomlInspectionToolBase.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateNotFoundInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspection.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/inspectionDescriptions/CrateVersionInvalid.html, toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlCrateInspectionTestBase.kt, toml/src/test/kotlin/org/rust/toml/inspections/CrateNotFoundInspectionTest.kt, toml/src/test/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspectionTest.kt
This PR adds a TOML inspection that checks if dependency version requirements match any known versions. It can also possibly detect yanked versions (or it could be in a separate inspection).
Since this is the second "crate-level" inspection (after https://github.com/intellij-rust/intellij-rust/pull/6591), I separated the crate dependency visitor and introduced shared abstractions for Cargo.toml inspections (and their tests) in separate commits.
For parsing the version requirements, I use the same library as in https://github.com/intellij-rust/intellij-rust/pull/6599. I created a lot of basic tests to check that it works correctly. It mostly seems to work, but sadly, there are (at least) two cases where its behaviour differs from Cargo:
```
1.2.*
Cargo does not accept 1.3.0
Semver4J …
```
=> TOML: add CrateVersionInvalidInspection

clion/src/main/kotlin/org/rust/clion/profiler/dtrace/RsDTraceConfigurationExtension.kt
Fixes https://youtrack.jetbrains.com/issue/CPP-24532
The bundled `osx-starter` lib is located in `bin/profiler/mac` directory [since](https://youtrack.jetbrains.com/issue/CPP-23530) CLion 211.6693.66
changelog: Fix `Can't find process starter` error when running DTrace profiler with CLion 2021.1
=> Update DTrace profiler integration to CLion 2021.1

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This PR adds error annotations for unknown `cfg` predicates.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7096
changelog: Annotate unknown cfg attributes. This corresponds to the E0537 compiler error.
=> ANN: annotate unknown cfg predicates [E0537]

build.gradle.kts
It should allow using project dependencies instead of IDE dependencies during compilation and test running without ugly fragile hacks with classpath
=> GRD: sort dependency artifacts

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
Now the corresponding annotation is provided by `Unresolved reference` inspection instead of annotator and, as a result, it can be suppressed and even turned off if the corresponding inspection is disabled.
Also, only identifier is highlighted not to highlight a lot of other code. Highlighting style was changed to "unknown symbol" to be more consistent with other unresolved references annotations
| Before| After |
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/113852675-7b5ca800-97a5-11eb-9e01-cc8279220b55.png) | ![image](https://user-images.githubusercontent.com/2539310/113853324-35ecaa80-97a6-11eb-9874-7c33a58112a5.png) |
changelog: Now `Can't find crate` annotation can be suppressed, highlights only unknown identifier and highlighting style is `unknown symbol` …
=> INSP: improve `Can't find crate` annotations

build.gradle.kts
Kotlin to 1.4.32
Grammar-Kit to 2021.1.2
=> GRD: update gradle plugins

src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsAttributeProcMacroReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsDeriveTraitReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsMacroPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
Support basic resolve of macros 2.0:
```rust
pub macro foo() {
...
}
```
Rust 1.51 added two such macros, `addr_of` and `addr_of_mut`.
Note that importing macros 2.0 using `#[macro_use] extern crate ...` is not supported by this PR.
changelog: Support basic resolve of macros 2.0 (`pub macro name() { ... }`) with new name resolution engine
=> RES: Basic resolve of macros 2.0 with new resolve

src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Fixes #7143
changelog: Fix changing crate name when using new name resolution engine
=> RES: Fix changing crate name when using new name resolution engine

src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Fixes exception in new resolve after removing crate from workspace:
```java
java.lang.Throwable: DefMapHolder must have latest stamp right after DefMap(baz(bin)) was updated. 5 vs 90
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:161)
at org.rust.lang.core.resolve2.DefMapHolder.checkHasLatestStamp(DefMapService.kt:70)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$getOrUpdateIfNeeded$1.invoke(FacadeUpdateDefMap.kt:49)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt$getOrUpdateIfNeeded$1.invoke(FacadeUpdateDefMap.kt)
at org.rust.stdext.ConcurrencyKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(Concurrency.kt)
at com.intellij.openapi.progress.util.ProgressIndicatorUtils.computeWithLockAndCheckingCanceled(ProgressIndicatorUtils.java:330)
at …
```
=> RES: Fix exception when removing crate from workspace in new resolve

src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsMultipleDefMapsUpdateTest.kt, src/test/kotlin/org/rustPerformanceTests/RsBuildDefMapTest.kt, src/test/kotlin/org/rustPerformanceTests/RsProfileCargoRefreshTest.kt
Previously because of mistake we collect in new resolve unmodified files after cargo refresh. It is unneeded work and causes some performance impact. It actually works because most (if not all) of file modifications also generates PSI event which we also handle.
changelog: Slightly optimize cargo refresh when using new name resolution engine
=> PERF: Fix which files are checked for modification after cargo refresh

src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7155.
changelog: Take into account enum's lifetimes in `Needless Lifetimes` inspection
=> ANN: Take into account enum's lifetimes in `Needless Lifetimes` inspection

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt, src/main/resources-stable/META-INF/experiments.xml, src/main/resources/messages/RsBundle.properties
Enable [new name resolution engine](https://github.com/intellij-rust/intellij-rust/issues/6217) by default. There are still some corner cases unsupported, but I think that overall improvement from new resolve is big enough to enable it by default
Here is regressions tests comparison: [with build scripts evaulation](https://github.com/dima74/intellij-rust/actions/runs/745483458), [without build scripts](https://github.com/dima74/intellij-rust/actions/runs/745549334)
changelog: Enable new name resolution engine by default
Fixes #4093
Fixes #4811
Fixes #4887
Fixes #5007
Fixes #5146
Fixes #6236
Fixes #6243
Fixes #6270
Fixes #6302
Fixes #6355
Fixes #6452
Fixes #6486
Fixes #6863
=> RES: Enable new name resolution engine by default

src/main/kotlin/org/rust/ide/annotator/RsAnnotationHolder.kt, src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingMutableAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt, src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt, src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt, src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt
At the moment, `existsAfterExpansion` is equivalent to `isEnabledByCfg`,
so this commit is just a rename. In the future, `existsAfterExpansion`
will return `false` for elements under attribute procedural macros
=> Introduce `existsAfterExpansion`, use it instead of `isEnabledByCfg`

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/NameSuggestionFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Improves https://github.com/intellij-rust/intellij-rust/pull/7102 by adding a quick fix to correct invalid cfg name.
Note that I couldn't just use `RenameFix`, because this fix has to work on `RsPath` in the case of `cfg` predicates. And in this way the fix is general and it can be used in more places.
changelog: Add quick fix to correct the name of an invalid cfg predicate.
=> ANN: Add quick fix to correct invalid cfg predicates

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt, src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt, src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
Fixes #4283
I think we got issues with Clippy (https://github.com/rust-lang/rust-clippy/issues/3890) due to a simple reason: sometimes we miss the file descriptor to running Cargo/Clippy process, hence we never kill it and don't read its output. The result is that such missed process hangs on writing to stdout because nobody actually read its output.
The fix is that, well, now we don't miss the process. Also, now we use SIGKILL instead of SIGTERM.
changelog: Cancel external linter (cargo check) immediately when some file is changed
=> Cancel external linter (cargo check) on PSI any change

src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
This is an internal refactoring (needed for attribute proc macros support)
=> RES2: split ItemLight into SimpleItemLight and ModOrEnumItemLight

build.gradle.kts, src/main/kotlin/org/rust/ide/statistics/RsProjectUsagesCollector.kt, src/main/kotlin/org/rust/ide/statistics/RsToolchainUsagesCollector.kt, src/main/resources/META-INF/rust-core.xml
Provides statistic state collectors to gather info about user toolchains and some general project characteristics.
Note, the corresponding statistics are collected only if `Send usage statistics` option in `Preferences | Appearance & Behavior | System Settings | Data Sharing` settings is enabled. See more about usage statistics politic [here](https://www.jetbrains.com/help/idea/settings-usage-statistics.html)
=> Initial version of state collectors

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustc.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt, src/main/kotlin/org/rust/cargo/util/CargoCommandCompletionProvider.kt, src/test/kotlin/org/rust/cargo/util/CargoCommandCompletionProviderTest.kt, src/test/kotlin/org/rust/cargo/util/CargoWithToolchainCommandCompletionProviderTest.kt
Adds completion for the `--target` flag in cargo run configuration and run anything action.
If a user will try to run the configuration without chosen target installed, there will be a prompt to install it.
changelog: Suggest target triples in command for Cargo run configuration and run anything dialog. Suggest installing the target if it is not yet installed
=> Complete and suggest to install target in cargo run configuration

src/test/kotlin/org/rust/ide/MockBrowserLauncher.kt, toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
These changes provide test infrastructure (including `MockBrowserLauncher`) to check documentation url that the plugin uses to open in browser.
Required for #7224
=> T: check urls for crate documentation line markers

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt
I'm not sure what this fixes for uses, but obviously this method was just missed
=> PSI: implement missed getContext() for macro definitions

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPsiPatternTest.kt
Both `continue` and `break` are expressions, so they should be completed in expression contexts. I'm not too sure about the "expression location" pattern that I have used, but it seems to work.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6524
changelog: Complete `continue` and `break` statements inside expression contexts in loops.
=> COMP: complete continue and break in expression context inside loops

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsNonShorthandFieldPatterns.html, src/test/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspectionTest.kt
Part of #5888
changelog: Detect and provide quick-fix for [non-shorthand-field-patterns](https://doc.bccnsoft.com/docs/rust-1.36.0-docs-html/rustc/lints/listing/warn-by-default.html#non-shorthand-field-patterns) compiler lint
=> INSP: Introduce non-shorthand field patterns lint

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSignaturePresentationBuilder.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringAvailability.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringExecution.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringStateChanges.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringSupport.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringUI.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsRenameSuggestedRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
This PR adds support for the suggested refactoring for function signature changes. Originally it was added in https://github.com/intellij-rust/intellij-rust/pull/5913 just for simple binding renames.
I took inspiration from the Kotlin implementation and tried to reduce it to be as small as possible. So for example default values for parameters are not implemented in this PR.
changelog: Add suggested refactoring support for changing function signatures.
=> REF: add suggested refactoring support for function change signature

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/utils/checkMatch/Pattern.kt, src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt
`AddRemainingArmsIntention` doesn't print enum names and variants correctly when they are escaped reserved Rust keywords. 
Here is example after activating `AddRemainingArmsFix`. And after that goes the same example with my tiny fix
Before: 
After:
=> FIX: AddRemainingArms intention incorrectly prints enum names and variants if they are escaped rust keywords

src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt, src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt, src/main/resources/postfixTemplates/MatchPostfixTemplate/after.rs.template, src/test/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplateTest.kt
This PR changes `match` postfix template to generate all match arms instead of just a single wildcard.
Currently, no template is used, the caret is just moved after the left brace of the first arm. Should there be some template to rename things from the generated arms? If yes, what should it rename?
Fixes https://github.com/intellij-rust/intellij-rust/issues/6630
Fixes https://github.com/intellij-rust/intellij-rust/issues/4727
changelog: `match` postfix template now generates all missing match arms by default.
=> COMP: add all remaining arms match postfix template

src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadataException.kt, src/test/kotlin/org/rust/cargo/project/model/CargoStdlibPackagesTest.kt
Previously, if stdlib dependencies were already downloaded but the corresponding directory was corrupted for some reason, the plugin showed an error to users and broke almost all code insight.
Now, the plugin:
- removes corrupted dependencies and tries to download them again
- fallbacks to hardcoded stdlib structure if all previous attempts failed
Note, all changes are related to `org.rust.cargo.fetch.actual.stdlib.metadata` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) that is disabled for now by default it stable builds
Should fix #6819
Should fix #7212
changelog: Try to recover corrupted stdlib dependencies when `org.rust.cargo.fetch.actual.stdlib.metadata` [experimental …
=> CARGO: recover corrupted stdlib dependency directory

src/main/kotlin/org/rust/cargo/runconfig/CargoRunStateBase.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt
Now plugin logs every Cargo command executed through Cargo run configurations (including Build, Run, Debug, Test).
This might be useful when investigating a reported problem related to building, running, and debugging Rust code.
Note, to enable this _debug-level_ logging in IDE, `#org.rust.cargo.runconfig` should be entered into `Help | Diagnostic Tools | Debug Log Settings`.
=> RUN: Add Cargo commands logging

src/211/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchainFlavor.kt, src/main/kotlin/org/rust/cargo/toolchain/flavors/RsSysPathToolchainFlavor.kt, src/main/kotlin/org/rust/stdext/Utils.kt
During toolchain detection, the plugin checks `PATH` variable and tries to convert its parts to `java.nio.file.Path`.
But if a user appended something illegal into the variable, the conversion fails with `InvalidPathException` exception.
Previously, we did nothing with it and it broke the UI. Now, we log such cases and skip illegal paths
Fixes #7202
Fixes #7264
changelog: Don't throw exceptions on illegal paths in `PATH` environment variable during toolchain detection
=> Don't throw exception on invalid user-created paths

.github/workflows/check.yml, .github/workflows/regressions.yml
Recently, GitHub [announced](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/) a `concurrency` [feature](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency) to run only single workflow/job for provided concurrency group. In combination with the `cancel-in-progress: true` flag, it also allows canceling already running tasks for the same concurrency group via builtin GitHub feature.
As a result, we can replace hacky `styfle/cancel-workflow-action` action that we used before to cancel outdated workflow runs (that actually worked not quite well when all available GitHub runners were busy) with the native GitHub feature.
changelog: Improve cancellation of outdated CI runs
=> CI: cancel previous ci runs via native `concurrency` feature

src/main/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsEdition2018KeywordsAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7214.
changelog: Don't annotate `async` as a reserved keyword in attributes
=> ANN: Don't annotate `async` as a reserved keyword in attributes

build.gradle.kts
It fails because of `NoClassDefFoundError`
=> GRD: temporarily disable `buildSearchableOptions` task for 212 platform

.github/workflows/check.yml
Recent 0.10.0 version doesn't work with IDE integration.
https://github.com/intellij-rust/intellij-rust/issues/7295
=> CI: use evcxr_repl 0.9 in tests

src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt, src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
Fixes #7291
changelog: Properly construct external links for [`unions`](https://doc.rust-lang.org/reference/items/unions.html) and [`trait aliases`](https://rust-lang.github.io/rfcs/1733-trait-alias.html)in [quick documentation](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-code-reference-info.html#quick-docs)
=> QDOC: support unions and trait aliases

src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
FIxes #4709
Fixes #5030
Fixes https://github.com/intellij-rust/intellij-rust/issues/7204
changelog: Don't reset project toolchain after project creation
=> PRJ: Don't reset project toolchain after project creation

toml/src/main/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntention.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/after.rs.template, toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/before.rs.template, toml/src/main/resources/intentionDescriptions/ExtractDependencySpecificationIntention/description.html, toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt, toml/src/test/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntentionTest.kt
Depends on #6960
Part of #4869
Introduces intention to extract dependency specification written as an inline table to a separate table below. 
changelog: Add intention to extract dependency specification in a separate table in `Cargo.toml`
=> INT: Introduce extract dependency in a separate table intention

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
Fixes #7238
changelog: Fix method duplication issue in completion list
=> COMP: deduplicate method completion variants by name and trait

.github/workflows/check.yml, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/console/RsConsoleCommunication.kt, src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt
Evcxr prints special markers `\u0091` and `\u0092` after each command, so that we can distinguish successful and failed commands. Evcxr executes special hidden command `:load_config` at startup, so in version 0.9 such marker was printed also after startup. In version 0.10 they reworked config loading, so such marker is no longer printed after startup
Fixes #7295
changelog: Fix [Rust REPL](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-repl-console.html) for latest [evcxr](https://github.com/google/evcxr) version 0.10.0
=> REPL: Fix for Evcxr 0.10.0

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt
Fixes https://github.com/intellij-rust/intellij-rust/pull/7239.
TODO: Fix sanity check for missing input file in the Run Configuration settings.
=> RUN: Fix validation of input file

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
This PR adds a quick fix that lets the user add new function parameters to a function from a function call, using the new Change signature refactoring. So far it only works for function and method calls and not tuple struct constructors. The behaviour of the fix is heavily inspired by a similar fix in the Kotlin plugin.
There are two TODOs in the code, which I'm not sure how to resolve:
- How to name parameters? `p0`, `p1`, etc.? Or continue counting from the existing parameter count? Also the fix should probably make sure that it doesn't generate collisions in parameter binding names.
- How to get the correct type reference from the argument expression type? That is especially important for import to work. I tried to use a type reference fragment, that sort-of works, but it imports the …
=> ANN: add quick fix to add function parameter from function call

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTest.kt, src/test/kotlin/org/rust/lang/core/stubs/RsStubTest.kt
We need this because `RsItemsOwner.itemsAndMacros` should
behave identically on stubs and on AST. Otherwise, it leads to
weird flaky bugs. This fixes the regression in #7194
Also, macro definitions should be available in symbol search as well as other
items. So they should be stubbed and indexed, even local ones
changelog: FEATURE: Add local macro definitions to `symbol search`. FIX: Fix possible flaky false positives around local macro calls
=> STUB: stub macro definitions and stub macro calls in code blocks if the block is stubbed 

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsUnknownCrateTypes.html, src/test/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspectionTest.kt
[The lint in the rustc book](https://doc.rust-lang.org/rustc/lints/listing/deny-by-default.html#unknown-crate-types)
[`Linkage` section in the Rust Reference](https://doc.rust-lang.org/reference/linkage.html)
Part of https://github.com/intellij-rust/intellij-rust/issues/5888
changelog: Detect `unknown_crate_type` compiler lint
=> INSP: Implement `unknown_crate_types` lint

src/main/kotlin/org/rust/cargo/project/RsToolchainPathChoosingComboBox.kt, src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/7196.
changelog: Extend toolchain path field to have an opportunity to choose a suggested path
=> UI: Extend toolchain path field to have an opportunity to choose a suggested path

src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt
Fixes the issue with doctests:
https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/483
(see the conversation in #6100)
changelog: Fix weird highlighting of doctests if [rainbow-brackets](https://plugins.jetbrains.com/plugin/10080-rainbow-brackets) plugin is installed
=> Fix interop with `rainbow-brackets` plugin

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, prettyPrinters/rust_types.py, pretty_printers_tests/tests/string.rs
In LLDB without native Rust support (e.g. MSVC LLDB currently), `&str` type is represented as `str*`.
Both `&str` and `str*` are now treated as string slices by the pretty-printers.
Part of #5632.
Fixes #7331
changelog: Render `&str` string slices content when debugging using MSVC toolchain on Windows
=> DBG: Treat `str*` as `&str` in pretty-printers

src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt
Fixes exception mentioned in https://github.com/intellij-rust/intellij-rust/issues/7280#issuecomment-859505965
changelog: Fix exception in debugger advertiser in 2021.2 versions of IntelliJ IDEA Ultimate, GoLand and PyCharm Pro
=> Fix NPE in debugger advertising runner in 2021.2 IDEs

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7292
changelog: Fix links to Clippy lints in documentation
=> ANN: Fix links to Clippy lints

gradle-211.properties
`211.6305.21-EAP-SNAPSHOT` doesn't exist anymore in marketplace for some reason
bors r+
=> GRD: update psi viewer plugin version

src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt, src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/3181
changelog: Keep existing comments when using `Nest use statements` intention.
=> INT: keep existing comments in NestUseStatementsIntention

src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/CreateTupleStructIntention/after.rs.template, src/main/resources/intentionDescriptions/CreateTupleStructIntention/before.rs.template, src/main/resources/intentionDescriptions/CreateTupleStructIntention/description.html, src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
This PR extends https://github.com/intellij-rust/intellij-rust/pull/6837. It adds a new intention which allows creating tuple structs from unresolved usage.
I decided to use a simple heuristic to offer the intention. It is offered for an unresolved function call if:
1) The target of the call is a module (so associated function calls are ignored).
2) The name of the called function is in CamelCase.
3) The expected return type of the function call is unknown or missing. i.e. the intention is not offered in this case:
```rust
let x: u32 = Foo/*caret*/(1, 2);
```
Because the code would not compile after the tuple struct would be created and it seems like its not what the user wants.
I'm not sure if 3) is needed, we can also skip it.
changelog: Add an intention to create a tuple struct from an …
=> INT: add intention to create a tuple struct

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Previously, log-like macros were hardcoded in type inference to have type `TyUnit`. This PR changes it so that they are inferred properly.
Some notes:
1) I included some code that special cases the inference for `log` macros. However, with the new macro engine, it seems that they are correctly inferred as-is. Is it even worth it to keep the special case?
2) If yes, the commented code is not completely correct, since I use the name of the crate (not the name of the crate as a dependency), so it might not work correctly for renamed `log` dependency. But that should be rare and the macro is inferred properly in any case...
3) I didn't find any (macro) type inference tests that would use toolchain so that I could test this with the `log` crate. It it worth it? I think that the main point is …
=> TY: infer expression type of log-like macros

src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Apply highlighting from #3869 and #4969 to custom macro bodies (#4640)
changelog: Provide highlighting of [format string literals](https://doc.rust-lang.org/std/fmt/) in any macros that expand to macros like println, write, format, etc
=> ANN: highlight format templates in custom macros

src/main/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/colors/RsColors.kt, src/main/resources/org/rust/ide/colors/RustDarcula.xml, src/main/resources/org/rust/ide/colors/RustDefault.xml, src/main/resources/org/rust/ide/colors/highlighterDemoText.rs, src/test/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotatorTest.kt
Depends on #6502
highlight *\*emphasis\** and **\*\*strong emphasis\*\*** text in rustdocs.
I'm not sure what color scheme should be used by default for *\*emphasis\** text. It's assumed to be *italic*, but both default Light and Darcula themes highlight all doc comments as italic, hence plain italic *\*emphasis\** would be indistinguishable from a regular doc text. I've used a scheme from #3739 where **\*strong emphasis\*** is highlighted as **bold** and *\*emphasis\** is highlighted as _italic and **bold**_ simultaneously.
Closes #3739
changelog: highlight *\*emphasis\** and **\*\*strong emphasis\*\*** text in rustdocs
=> ANN: highlight emphasis and strong emphasis in rustdocs

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/main/kotlin/org/rust/ide/colors/RsColors.kt, src/main/resources/org/rust/ide/colors/highlighterDemoText.rs, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorToolchainTest.kt
As discussed in https://github.com/intellij-rust/intellij-rust/pull/7243#issuecomment-863359497, rename `FORMAT_SPECIFIER` color to `FORMAT_PARAMETER` and introduce `FORMAT_SPECIFIER` color
https://user-images.githubusercontent.com/3221931/122535107-e63f2080-d02b-11eb-9554-b525f69b9690.mp4
=> ANN: introduce a color for `std::fmt` format specifiers

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/intentions/GenerateDocStubIntention.kt, src/main/kotlin/org/rust/ide/intentions/GenerateDocstringStubIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/GenerateDocStubIntention/after.rs.template, src/main/resources/intentionDescriptions/GenerateDocStubIntention/before.rs.template, src/main/resources/intentionDescriptions/GenerateDocStubIntention/description.html
changelog: Added an editor intention that generates a documentation stub as demonstrated in: https://doc.rust-lang.org/beta/rust-by-example/meta/doc.html and https://github.com/rust-lang/rust/issues/57525
I'm not sure if the current implementation is robust enough, as the RustCommenter lacks the functionality that was used for IntelliJ Javadocs and Pycharm docstring implementations. So this implementation has to manually create the comments by inserting strings.  I was also not able to parse the function context like in intellij to see whether a function was being declared or just being referenced, or already had a doc, so I had to implement it. 
Feedback is very welcome
=> INT: Generate documentation stub

src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt, src/main/kotlin/org/rust/stdext/Utils.kt, src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
This PR adds more cases to `RsSelfConventionInspection`, useful for getters/setters and the builder pattern.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/1323
changelog: Extend RsSelfConvention inspection with new method prefixes (get, set and with).
=> INSP: extend RsSelfConventionInspection with get, set and with

.github/workflows/release-branch.yml, .github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml, scripts/common.py, scripts/make_release_branch.py, scripts/save_tag.py, scripts/update_changelog_link.py
Previously, we tried to push into repo via `https://{actor}:{token}@github.com/{repo}.git` url. Found out that it doesn't work as expected and token provided in `actions/checkout` is used instead.
Now we:
- set proper token during checkout
- use [intellij-rust-bot](https://github.com/intellij-rust-bot) [machine account](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements) to generate PAT and push such changes into repo
=> CI: properly push changes in repository

src/main/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsDoctestAnnotator.kt, src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt, src/main/kotlin/org/rust/lang/doc/psi/Psi.kt, src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt, src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
This fixes several issues with doctests:
1. The plugin now understands doctests in markdown
code fences with more than 3 backticks ("`````")
or with tildes ("~~~")
2. Apply correct indentation for indented code fence
changelog: Support [doctests](https://doc.rust-lang.org/rustdoc/documentation-tests.html) in code fences wrapped in different number of backticks or tildes
=> LI: Use the new RsDoc PSI for doctest injections

src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/decl/FragmentKind.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt
Fixes #7372
Support [`:pat_param`](https://blog.rust-lang.org/2021/05/11/edition-2021.html#or-patterns-in-macro_rules) `macro_rules!` matcher (from Rust 1.53.0)
Fix `:pat` matcher - now it should not parse `or patterns` (this behavior should be changed on [2021 edition](https://blog.rust-lang.org/2021/05/11/edition-2021.html#or-patterns-in-macro_rules))
changelog: FEATURE: Support [`:pat_param`](https://blog.rust-lang.org/2021/05/11/edition-2021.html#or-patterns-in-macro_rules) `macro_rules!` matcher (from Rust 1.53.0), FIX: Fix `:pat` matcher - now it should not parse `or patterns`
=> MACRO: support `:pat_param` `macro_rules!` matcher, fix `:pat` matcher

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/colors/RsColors.kt, src/main/kotlin/org/rust/ide/highlight/RsHighlighter.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/docs/RsCodeHighlightingInQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/docs/RsRenderedDocumentationTest.kt
step1 for #5397, can't figure out how to do step2 (implementing the missing option)
changelog: rename syntax highlighting option "variables -> default" to "identifier" since that's what the option has been doing the whole time (the actual option for default variables has yet to be implemented)
=> fix highlighting variables//default to actually highlight variables only

src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/main/kotlin/org/rust/ide/template/postfix/editable/RsEditablePostfixTemplate.kt, src/main/kotlin/org/rust/ide/template/postfix/editable/RsPostfixTemplateEditor.kt, src/main/kotlin/org/rust/ide/template/postfix/editable/RsPostfixTemplateExpressionCondition.kt, src/test/kotlin/org/rust/ide/template/postfix/editable/RsEditablePostfixTemplateTest.kt
Short demonstration:
Basically, it's the same as custom postfix templates in IDEA for Java or in Goland for Go. You can select several types (bool, number, reference, etc) for an expression which the template would be applicable to. You can also enter the type yourself (like "Vec", "String", or with full path "sdl2::event::Event" ("sdl2" is a crate name). Type parameters are ignored so "Vec" type would be the same as "Vec\<String\>" or "Vec\<Vec\<u32\>\>". In addition, if the type list is empty (it is by default), the template will be applicable to an expression of any type.
There is a limited support for user variables ($val$ in the gif) inside the template text. You can simply 'tab' through them but cannot choose the order. 
Unfortunately, there are no such nice things as "Live Template …
=> COMP: add custom postfix templates

src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt, src/main/kotlin/org/rust/ide/refactoring/RsNamesValidator.kt, src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt, src/test/resources/org/rust/cargo/runconfig/producers/fixtures/use_raw_identifier_for_module_named_with_keyword.xml
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7387
changelog: Support modules named after Rust keywords in `cargo test` configurations.
=> CARGO: escape keywords in cargo test command invocations

src/main/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntention.kt, src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt
This PR changes `FlattenUseStatementsInspection` so that it works properly on all places inside a use group.
Before, the intention was looking for the use speck to flatten using `ancestorStrict`. That meant that if you have invoked the intention on some element that wasn't a use speck inside a use group, e.g. here:
```rust
use self::{
foo::{
a,/*caret*/
b
},
bar::baz,
};
```
the `useSpeckOnCursor` variable was set to `foo::` instead of `a` or `b`. Therefore the intention produced invalid code. Now the intention first looks for siblings located at caret to find the proper use speck to replace.
I suppose that the same thing should be done for `NestUseStatementsIntention`, I can do it in another PR.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7396
changelog: The intention to …
=> INT: considers siblings near caret in FlattenUseStatementsIntention

toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt, toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
Fixes #7223
Closes #7224
changelog: Properly escape crate urls produced by line markers in Cargo.toml. should fix exception by clicking on the corresponding icon if you use [IntelliJ Projector](https://blog.jetbrains.com/blog/2021/03/11/projector-is-out/) with IntelliJ Rust plugin on backend
=> Properly escape crate urls produced by line markers in Cargo.toml

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/BoundElement.kt, src/main/kotlin/org/rust/lang/core/types/Substitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Internal. It's now possible to get `Substotution` of `RsMethodCall` or `RsPathExpr`.
I promised that [here](https://github.com/intellij-rust/intellij-rust/pull/5644#issuecomment-683338917) :)
Note that this doesn't work correctly for `refined` paths (see `test infer method arg with multiple impls of the same trait` or `test resolve UFCS method call with multiple impls of the same trait`). I'll fix it later
=> Add API to get inferred method type and substitution

src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt
Improves https://github.com/intellij-rust/intellij-rust/pull/6613, as discussed [here](https://github.com/intellij-rust/intellij-rust/pull/5644#discussion_r555088815).
Changelog: Correctly resolve generic types when invoking "Fill function arguments fix" on generic methods.
=> ANN: substitute generic method arguments in FillFunctionArgumentsFix

.github/workflows/create-changelog.yml, scripts/common.py, scripts/fetch_projects.py, scripts/get_tag_commit.py, scripts/git.py, scripts/github.py, scripts/make_changelog_pull_request.py, scripts/make_release_branch.py, scripts/save_tag.py, scripts/update_changelog_link.py
These changes introduce a new `create changelog` workflow that should create a pull request with release changelog template in https://github.com/intellij-rust/intellij-rust.github.io repo and assign it to the corresponding release manager (according to the corresponding milestone). The workflow creates a changelog template by running `changelog.py` script from `intellij-rust.github.io` repo sometime before the release (currently, it's 5 days, i.e. usually on Wednesday morning).
The goals of this change are to remind release managers about changelog creation and automate some of their routine work.
=> CI: create changelog pull request automatically

.github/workflows/check.yml, .github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml, build.gradle.kts, src/main/kotlin/org/rust/openapiext/RsPathManager.kt
Part of #6908
changelog: Support [procedural macro](https://doc.rust-lang.org/reference/procedural-macros.html) expansion on Apple Silicon machines. Note:
- you should use `aarch64-apple-darwin` toolchain to make procedural macro expansion work
- the proc macro expansion is still disabled by default. To turn it on, enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental features](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)
=> CI&MACRO: expand proc macros on Apple Silicon machines

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Crates local index keeps info related to local user state. It's not supposed to be shared between different machines, so let's use `other.xml` file not to share it
changelog: Don't allow sharing/exporting data of crate local index
=> Save persistent data of crate local index in workspace.xml

scripts/github.py, scripts/make_changelog_pull_request.py, scripts/make_next_milestone.py
Previously, it failed if previous milestone was closed (i.e. workflow was invoked after release but before new release branch creation)
Also, applied some suggestions from https://github.com/intellij-rust/intellij-rust/pull/7377#issuecomment-868684096
=> CI: fix `create changelog` workflow

src/main/kotlin/org/rust/ide/refactoring/generate/getter/GenerateGetterHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/setter/GenerateSetterHandler.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateSetterActionTest.kt
changelog: Do not expand type aliases when generating getters and setters.
=> REF: add support for type aliases in getter/setter generation

build.gradle.kts
=> GRD: enable `buildSearchableOptions` task for 2021.2 builds

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexStartupActivity.kt, toml/src/main/kotlin/org/rust/toml/crates/local/TestCratesLocalIndexServiceImpl.kt
Part of #6463
changelog: Crates local index for dependencies completion and inspections is now being updated on project changes. Note, currently this feature is experimental and can be enabled with `org.rust.crates.local.index` option in `Experimental Features` dialog.
=> Invoke crates local index update on on cargo registry repository changes

src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/main/kotlin/org/rust/openapiext/ui.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
This PR adds completion for types, constants and functions in `impl Trait for Foo` blocks.
I'm not sure what should be done with the caret/selection after the completion. Using `RsInPlaceVariableIntroducer` is probably not right in completion? But without it if I select the completed value and the user presses enter, it will be overwritten.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/6282
=> COMP: add completion for impl trait items

src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
Improves https://github.com/intellij-rust/intellij-rust/pull/6342 by reusing the `MembersGenerator` class.
=> COMP: reuse MembersGenerator in RsImplTraitMemberCompletionProvider

src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt, src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7419
changelog: The intention to create structs from unresolved usage now creates the structs outside if invoked from inside an impl block.
=> FIX: create structs outside if invoked from inside an impl block

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsUseItem.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsUnusedImport.html, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
This PR adds basic support for detecting unused `use` imports. I did not know which platform machinery should be used to implement this, so I took a little inspiration from the Kotlin plugin and implemented something that made sense to me to get the ball rolling. If it should be implemented in a different way, please let me know.
~Currently, the inspection does not seem to run after every code change, I'm not sure what should be changed in the caching implementation, any hints?~
There are currently some false negatives (see last commented test), but these should be rare and I think that we can solve these in a future PR. If this gets merged, I'll add a quick fix to remove the unused use speck and then try to integrate this into the import optimizer to automate the process.
Related issues: …
=> INSP: add unused imports inspection

src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTest.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveMultipleFilesTest.kt
Moving directory was not working in 212 platform, because of change in method `PsiTreeUtil#filterAncestors` behaviour. This [was fixed](https://upsource.jetbrains.com/intellij/revision/c31b8b4707e12c18c295dfab6b08d723ae56eabd) in platform in 212.4535
=> T: Enable move directory tests for 212 platform

build.gradle.kts
`testOutput` contains references to test classes of the corresponding modules. Allows specifying dependency between tests in different gradle modules
=> GRD: provide `testOutput` configuration in all gradle modules

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
I'm trying to implement proper completion of visibility qualifiers (`pub(crate)` - https://github.com/intellij-rust/intellij-rust/issues/5025), but before that there are several smaller things that can be improved, so I'll send them in separate PRs.
changelog: Only complete ancestor mods in visibility restriction paths (`pub(in <...>)`).
=> COMP: only complete ancestor mods in vis restriction paths

intellij-toml/core/src/main/kotlin/org/toml/ide/annotator/TomlAnnotator.kt, intellij-toml/core/src/test/kotlin/org/toml/ide/annotator/TomlAnnotatorTest.kt, intellij-toml/src/main/resources/META-INF/plugin.xml
changelog: Annotate trailing commas in TOML inline tables as errors
=> ANN: Annotate trailing comma in toml inline table

src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt, src/test/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplateTest.kt
This PR improves https://github.com/intellij-rust/intellij-rust/pull/6825 by letting the user change the generated wild patterns (`_`) with a template builder. Based on a suggestion by @Sherlock-Holo (https://github.com/intellij-rust/intellij-rust/pull/6825#issuecomment-858216675).
changelog: Allow filling pats after generating match arms with `.match` postfix template.
=> COMP: use template builder to fill wild pats in MatchPostfixTemplate

pretty_printers_tests/src/test_runner.rs, pretty_printers_tests/tests/nonzero.rs, pretty_printers_tests/tests/string.rs, pretty_printers_tests/tests/vec.rs
Fix pretty-printers tests on 2021.2 platform.
After updating LLDB bundle to version 12 (since CLion 212.4535-EAP), LLDB is unable to resolve a breakpoint location by a file name. Fortunately, breakpoints configured with (full or relative) file paths seem to work fine. So now pretty-printers tests provide a path instead of just a file name.
For example, a previously used command
```
(lldb) breakpoint set --file 'nonzero.rs' --line 27
```
is now replaced with
```
(lldb) breakpoint set --file './tests/nonzero.rs' --line 27
```
Fixes #4527
Fixes #7453
Fixes #7454
=> T: Fix pretty printers tests on 2021.2

toml/src/main/kotlin/org/rust/toml/crates/local/CrateVersionRequirement.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateVersionInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/NewCrateVersionAvailableInspection.kt, toml/src/main/kotlin/org/rust/toml/inspections/UpdateCrateVersionFix.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/inspectionDescriptions/NewCrateVersionAvailable.html, toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlCrateInspectionTestBase.kt, toml/src/test/kotlin/org/rust/toml/inspections/NewCrateVersionAvailableInspectionTest.kt
This PR adds a TOML inspection that uses a weak warning to notify the user that there might be a more recent version of a dependency available (inspired by https://github.com/mibac138/intellij-rust/commit/c8960b23adeb70deac77aab3d5b6a4edbb7fa700). It also provides a quick fix that replaces the version requirement with the newest crate version.
Currently, the inspection is only offered if there is a non-yanked, stable version of the dependency which is not matched by the provided version requirement. This means that if the maximum version is e.g. `3` and the user requires `4`, the inspection will trigger, which might be a bit weird, but this situation should be very rare. I didn't know how else to implement it, since I didn't find a way how to compare versions with version requirements. …
=> TOML: add inspection that offers an update to a newer dependency version

.github/workflows/check.yml, gradle-211.properties, src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt, src/main/kotlin/org/rust/ide/actions/RefreshCargoProjectsAction.kt, src/main/kotlin/org/rust/ide/inspections/RsDetachedFileInspection.kt, src/main/kotlin/org/rust/ide/notifications/MissingToolchainNotificationProvider.kt, src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt, src/main/kotlin/org/rust/ide/notifications/RsUntrustedNotificationProvider.kt, src/main/kotlin/org/rust/ide/notifications/Utils.kt, src/main/kotlin/org/rust/ide/security/RsTrustChangeNotifier.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties
Show [untrusted project](https://www.jetbrains.com/help/idea/2021.1/project-security.html) dialog to ensure that project is safe to invoke rust tools like `cargo`/`rustc`/`rustfmt` that can be overridden to execute arbitrary (probably malicious) code and execute build scripts/procedural macros that also can contain arbitrary code
In the case of "Preview in Safe Mode" choice, the plugin won't load any info about a project by default like `cargo metadata`, `rustc -V`, `rustc --cfg`, etc.
The plugin shows editor notification in Rust and Cargo.toml files
Also, for some dangerous actions (not all) the plugin now shows the following dialog to continue execution
Currently, it's implemented only for `Build` and `Refresh Cargo Projects` actions. For other actions it will be implemented in separate …
=> Confirm loading untrusted Cargo project

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
This PR makes path completion more precise inside trait refs. The various path filters were nested quite deeply, so I changed the implementation to apply them in a cycle.
changelog: Only complete traits in paths that must resolve to traits (e.g. `impl <...> for type` or `T: <...>`).
=> COMP: only complete paths that resolve to traits in trait refs

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsVisRestrictionCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsVisRestrictionCompletionTest.kt
This PR adds completion for things that can be put inside a visibility restriction (`self`, `super`, `crate` or `in`).
Partially resolves https://github.com/intellij-rust/intellij-rust/issues/5025
changelog: Add completion for items inside visibility restrictions (`pub(<...>)`).
=> COMP: complete possible options inside visibility restriction

toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFileReferenceProvider.kt, toml/src/test/kotlin/org/rust/toml/inspections/CargoTomlUnresolvedPathReferenceInspectionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7402
changelog: Ignore paths with wildcards in TOML to avoid false positives.
=> TOML: ignore path references with wildcards to avoid false positives

src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt, src/test/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplateTest.kt
This PR adds a special case for `String` in `MatchPostfixTemplate`,  as mentioned [here](https://github.com/intellij-rust/intellij-rust/pull/6825#issuecomment-858592723), because the default is not very useful. This could possibly be applied to other types too, for example `&str`.
It also adds simple infrastructure for adding custom match generation for selected types.
changelog: Add special case for Strings in MatchPostfixTemplate.
=> COMP: add special case for String in MatchPostfixTemplate

toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
minor: replace `WithStdlibAndDependencyRustProjectDescriptor` to `WithDependencyRustProjectDescriptor` to `CargoCrateDocLineMarkerProviderTest` since stdlib isn't needed there
=> T: don't use stdlib in toml tests

src/main/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/CreateLifetimeParameterFromUsageFixTest.kt
changelog: fixed "Create lifetime parameters from usage" for items with const generic parameters
=> INT: fixed "Create lifetime parameter from usage" with const generics

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
I noticed that the local crate index takes a while to load, so I tried to profile it to see what's going on. I made two changes in two separate commits:
1) The object mapper for deserializing JSON was being created time and time again. It takes some instructions to initialize it and (most importantly), if it's created from scratch each time, it cannot leverage any proper caching of deserializers. This change reduces the time to run the `test tokio features` test from ~45s to ~22s on my notebook.
Before:
After:
2) Since loading and deserializing the versions take a lot of time, I tried to parallelize it, by first walking the tree to collect all object IDs, then deserializing them in parallel. This cut the time further from ~22s to ~10s on my notebook with 4 cores (8 hyper-threads). It used …
=> PERF: optimize local crate index parsing

build.gradle.kts
changelog: Use Kotlin 1.5 for plugin compilation. So now it's possible to use [sealed interfaces](https://kotlinlang.org/docs/whatsnew15.html#sealed-interfaces) and place subclasses of sealed classes in [different files](https://kotlinlang.org/docs/whatsnew15.html#package-wide-sealed-class-hierarchies). Note, the new stdlib API is still unavailable in the project since the plugin may be launched in IDE with 1.4 runtime
=> GRD: use kotlin 1.5.20

src/main/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMover.kt, src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt, src/main/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMover.kt, src/test/kotlin/org/rust/ide/actions/mover/RsStatementUpDownMoverTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7376
changelog: Allow moving up/down in block expressions inside comma-separated lists.
=> IDE: allow moving up/down in block expressions in comma-separated lists

src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt, src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Expand format macros like `writeln` in `RsWithMacrosRecursiveElementWalkingVisitor`, so that unused import inspection can correctly handle needed imports (`std::io::Write`) for them
changelog: Correctly handle `writeln!` macro in unused import inspection
=> INSP: Fix handling `writeln!` macro in unused import inspection

src/main/resources-nightly/META-INF/experiments.xml, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/WithoutExperimentalFeatures.kt, toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependenciesCompletionTest.kt
changelog: Crates local index feature is now enabled on nightly by default
=> Enable by default crates local index for nightly users

src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt, src/main/kotlin/org/rust/openapiext/Template.kt, src/test/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplateTest.kt
An improvement to #7328: place the caret to the first arm after finishing the template
https://user-images.githubusercontent.com/3221931/124749393-d630a780-df2c-11eb-8f2d-ee0c3f282a35.mp4
=> COMP: always place caret into the first arm in MatchPostfixTemplate

src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt, src/main/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandler.kt, src/main/kotlin/org/rust/ide/utils/CallInfo.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandlerTest.kt
I'm not sure about using types vs type references for function/method calls.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4308
changelog: Substitute generic parameters in `Parameter Info`.
=> HINT: Substitute generic parameters in Parameter info

src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Take into account macro paths when traversing modules in `PathUsageAnalysis`. Previously macros were intentionally ignored in inspection because of this
changelog: Support declarative macros in unused import inspection
=> INSP: Support declarative macros in unused import inspection

grazie/src/211/main/resources/META-INF/platform-grazie-only.xml, grazie/src/211/test/kotlin/org/rust/grazie/compatUtils.kt, grazie/src/212/main/resources/META-INF/platform-grazie-only.xml, grazie/src/212/test/kotlin/org/rust/grazie/compatUtils.kt, grazie/src/main/resources/META-INF/grazie-only.xml, grazie/src/test/kotlin/org/rust/grazie/RsGrammarCheckingTest.kt
Grazie plugin enables proofreading inspection for all languages by default in 2021.2 release. Since we actually haven't checked it properly yet (Grazie plugin was significantly changed recently).
So we decided to disable it for now, check properly, fix potential bugs and enable it by default again
changelog: Temporarily disable proofreading checks from [Grazie plugin](https://plugins.jetbrains.com/plugin/12175-grazie) for Rust language in 2021.2 IDEs
=> ANN: disable Grazie proofreading for Rust language in 2021.2 IDEs

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt
The bug was explained @Kobzol in [the comment](https://github.com/intellij-rust/intellij-rust/pull/7480#issuecomment-878633497)
The full completion list isn't shown when completing in an empty place because unfiltered completion (without a prefix) would be quite slow. But the bug is that the full completion list isn't loaded after typing the first letter.
=> COMP: fix autoimport-aware completion after completion at empty place

src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt, src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Adjust visitor usage so that we don't abort processing when encounter cfg-disabled code
changelog: Fix handling cfg-disabled code in unused import inspection
=> INSP: Fix handling cfg-disabled code in unused import inspection

src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt, src/main/kotlin/org/rust/ide/utils/template/RsTemplateBuilder.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionTest.kt
This PR adds completion for lambds in expression positions that expect a function (`&dyn Fn`, `F: Fn`, `impl Fn`, `fn`). The check for `|` already being present is quite hacky, but I didn't know how else to do it, since the `|` in e.g. `foo(|)` is not parsed as an expression nor as an identifier.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/3830
changelog: Add completion for lambdas in expression positions that expect a function.
=> COMP: complete lambdas in function expression position

src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt, src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/AddImplTraitIntention/after.rs.template, src/main/resources/intentionDescriptions/AddImplTraitIntention/before.rs.template, src/main/resources/intentionDescriptions/AddImplTraitIntention/description.html, src/test/kotlin/org/rust/ide/intentions/AddImplTraitIntentionTest.kt
This PR attempts to implement (a part of) https://github.com/intellij-rust/intellij-rust/pull/5339 in a more "atomic" way. The idea is to create an intention that will generate an impl block for a given type, let the user type a trait name and then automatically implement all members of that trait. Dealing with required supertraits will be left for another quick fix.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4123
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7342
Closes: https://github.com/intellij-rust/intellij-rust/pull/5339
changelog: Add intention to implement a trait for a struct or enum.
=> INT: add intention to implement a trait for an ADT type

src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryActionTest.kt
Made `RsPromoteModuleToDirectoryActionTest` usual test (without toolchain), because tests with toolchain are very slow. Thanks @vlad20012 for pointing this out
=> T: Optimize `RsPromoteModuleToDirectoryActionTest`

build.gradle.kts, settings.gradle.kts
Previously, the corresponding module was excluded from 2021.2 builds because of https://github.com/JetBrains/gradle-intellij-plugin/issues/674 that was fixed in 1.1.3
changelog: Enable [Go to generated declaration](https://plugins.jetbrains.com/plugin/8182-rust/docs/wasm-projects-support.html#goto-wasm-bindgen) line marker in WASM projects for 2021.2 platform
=> Enable js module for 2021.2 builds

src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/main/kotlin/org/rust/ide/template/postfix/WrapTypePathPostfixTemplate.kt, src/main/kotlin/org/rust/ide/template/postfix/utils.kt, src/main/resources/postfixTemplates/WrapTypePathPostfixTemplate/after.rs.template, src/main/resources/postfixTemplates/WrapTypePathPostfixTemplate/before.rs.template, src/main/resources/postfixTemplates/WrapTypePathPostfixTemplate/description.html, src/test/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateTest.kt, src/test/kotlin/org/rust/ide/template/postfix/WrapTypePathPostfixTemplateTest.kt
Recently I needed to wrap several types inside `Mutex` and I thought that a postfix template that wraps a type in another type could be nice.
To make it practical for repeated wrapping, it would be nice if the caret moved to the end of the wrapped type, instead of moving after its name. But I didn't find how to do this with the `Template` API. I could probably override and completely re-implement `expandForChooseExpression` to use a template builder, but I'm not sure if that's the right way to do it.
For some reason autoimport in the template used by the postfix completion doesn't work in tests. It works in the IDE though.
changelog: Add postfix template named `.wrap` that wraps an existing type with another type.
=> COMP: add postfix template for wrapping a type with another type

src/main/kotlin/org/rust/ide/inspections/fixes/RemoveImportFix.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/main/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntention.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsUseGroup.kt, src/test/kotlin/org/rust/ide/inspections/fixes/RemoveImportFixTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt, src/test/kotlin/org/rust/ide/intentions/RemoveCurlyBracesIntentionTest.kt
This PR adds a quick fix to remove an unused import. To make this fix more usable, I first changed the warning annotation range of `RsUnusedImportInspection`. This slightly deviates form the text displayed by `rustc`, but I think that it's more obvious for the user to see what is actually unused. And it will also allow the user to remove multiple unused use specks with a single quick fix.
The annotation is now checked only once per each use item, so some of the checks will not be performed per each use speck. This new annotation works in two steps. First I collect the usage (used/unused) of each use speck, and then I traverse them from the top and try to mark as large ranges as possible (i.e. if a group has two unused children, the group itself will also be marked as unused).
Before: …
=> INSP: add quick fix to remove an unused import

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
It's common to include more imports than needed in doctest sample code, so I think it makes sense to disable inspection there
=> INSP: Disable unused import inspection in doctests

src/main/kotlin/org/rust/ide/icons/RsIcons.kt, src/main/kotlin/org/rust/ide/structure/RsMacroExpandedFilter.kt, src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/structure/RsMacroExpandedFilterTest.kt, src/test/kotlin/org/rust/ide/structure/RsStructureViewModelTest.kt, src/test/kotlin/org/rust/ide/structure/RsStructureViewTestBase.kt, src/test/kotlin/org/rust/ide/structure/RsStructureViewToggleableActionTest.kt
changelog: added a new filter to the Structure View panel, which toggles whether macro-generated items should be included in the Structure View.
The reason to add this filter is that it is common to produce boilerplate structures and trait implementations using macros. For example, if we introduce a new trait which should be implemented for all primitive numbers, then there will likely be 12 implementations which are derived by a single macro (signed and unsigned with 8, 16, 32, 64, 128, and `size` bits). Similarly, it is common in crates which don't use const generics to implement traits for 32 or more different array sizes separately, and crates which need generically sized tuples (like `itertools` or `warp`) often implement traits for all tuples up to a certain size.
Such boilerplate …
=> TYPE: added filter for items expanded from macros to Structure View

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Fixes #7124
changelog: Fix false-positive [E0603](https://doc.rust-lang.org/error-index.html#E0603) "Module is private" when using new name resolution engine
=> RES2: Fix resolve crate when importing private module with same name

src/main/kotlin/org/rust/ide/template/RsContextType.kt, src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
changelog: don't offer live templates (like `p` that inserts `println!()`) in patterns
=> COMP: don't offer live templates in patterns

src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt, src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionTest.kt
This PR attempts to improve lambda completion by re-using the existing `RsExpr.suggestedNames()` code for initial parameter names.
Related to #3830
Based on #7487
changelog: improve lambda's parameter name suggestion
=> COMP: Use suggestedNames() in lambda completion
