src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsInlineFunctionTest.kt
changelog: Allow inlining functions (using `Inline Function` refactoring) with diverging exit points (like `panic!()`).
=> Feature inline diverging function

src/main/kotlin/org/rust/ide/typing/RsTypedHandler.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/typing/RsTypedHandlerTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
An improvement to #7487 - automatically show completion popup when typing `|`.
=> TYPE: show autocompletion popup when typing `|`

src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Fixes false-positives related to unresolved method calls - if method call is unresolved, then we consider import of trait which has method with same name as used
changelog: Fix false-positives related to unresolved method calls in unused imports inspection
=> INSP: Handle unresolved method calls in unused imports inspection

toml/src/main/kotlin/org/rust/toml/intentions/SimplifyDependencySpecificationIntention.kt, toml/src/main/resources/META-INF/toml-only.xml, toml/src/main/resources/intentionDescriptions/SimplifyDependencySpecificationIntention/after.rs.template, toml/src/main/resources/intentionDescriptions/SimplifyDependencySpecificationIntention/before.rs.template, toml/src/main/resources/intentionDescriptions/SimplifyDependencySpecificationIntention/description.html, toml/src/test/kotlin/org/rust/toml/intentions/SimplifyDependencySpecificationIntentionTest.kt
changelog: Suggest simplify dependency specification for inline tables in Cargo.toml dependencies
=> INT: Implement simplify dependency specification intention

src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt, src/test/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntentionTest.kt
This PR fixes the behaviour of `ImplTraitToTypeParamIntention` when there are already existing const parameters. It also reworks the insertion logic so that it better supports trailing commas.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7382
changelog: Fix intention to convert an `impl trait` parameter to a generic parameter when the corresponding function already has const parameters.
=> FIX: support const parameters and trailing commas in ImplTraitToTypeParamIntention

src/main/resources/META-INF/rust-core.xml
changelog: move `Unused import` inspection into `Rust/Lints` inspection group in settings
=> INSP: move `Unused import` inspection into `Rust/Lints` inspection group

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
Fixes that cfg-disabled import can be removed even if there is cfg-disabled usage
changelog: Ignore cfg-disabled imports when removing unused imports
=> IDE: Ignore cfg-disabled imports when removing unused imports

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/ConvertClosureToFunctionIntention/after.rs.template, src/main/resources/intentionDescriptions/ConvertClosureToFunctionIntention/before.rs.template, src/main/resources/intentionDescriptions/ConvertClosureToFunctionIntention/description.html, src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionTest.kt
Since this is my first PR on this project, I'd be very grateful for detailed feedback on how I approached this issue.
One thing I'm still not sure about is the way I'm generating the context in `findApplicableContext()`. The way it currently checks whether the intention is applicable, is pretty broad. The caret could be somewhere in the lambda/function body as well and the intention would still be available. I didn't find any general guidelines on how intention availability is defined, would appreciate directions here. 
Also, regarding tests: I am not sure what I can test here exactly. I added tests for the basic "positive" cases and also a test for the edge case that the lambda is bound to `let _`, which would result in an invalid function name. Any other good test case hints would be …
=> INT: Convert from lambdas to local named functions

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsReprCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsReprCompletionProviderTest.kt
Closes #6365 
changelog:
Add completion for layouts in `repr` attributes.
=> COMP: Repr attribute layouts

src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt, src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/lang/core/type/RsShortTypeRenderingTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
This is an attempt to implement `aliasedBy` for (almost) all types, attempt number 2.
I wanted `aliasedBy` to be optional, so that you can first create a type without it and then "bolt" it onto the type later. This makes implementing `inferTypeReferenceType` much simpler, because the alias can be added "from the outside".
There are probably two ways of implementing the attribute itself:
1) Create an `aliasedBy` field directly inside `Ty`
- (meh) each type will need to implement a `copy` method so that it can re-create itself with an alias
- (bad) it's not really possible to pass the `aliasedBy` field from child constructor of data classes to `Ty`. So you couldn't create these classes directly with an alias. So e.g. in `superFoldWith` you would need to create the folded type and then …
=> TY: lift aliasedBy from TyAdt to Ty

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
This PR improves the UX of completion inside impl trait.
1) Template builder is used instead of just selecting the generated element. Therefore you can change the generated item and if you click on Enter after the completion, the element will remain (before it would delete it and create a newline, which was weird).
2) Complete items that are after an abstractable keyword (`fn`, `const`, `type`). Also use the keyword to filter the corresponding items (i.e. after `fn`, only functions will be suggested).
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7533
changelog: Improve completion of items inside impl trait.
=> COMP: improve completion inside impl trait

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/Utils.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildManagerTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/CargoBuildTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/TestBuildViewManager.kt, src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
These changes:
- fix deadlock introduced in #7432
- get rid of some hack in `CargoBuildManager` made for tests like `CargoBuildManager.testBuildId` and `CargoBuildManager. mockBuildProgressListener`
- introduce dsl to check build event hierarchy, including a way to mark some events as unordered. Note, now we don't take into account events id in tests
- enable the corresponding tests on CI
Closes #6532
=> T: fix build tests

src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProviderTest.kt
While using the new impl trait item completion, I noticed that it does not generate proper code if a generated constant has multiple lines or if the generated function is nested (i.e. if you impl a trait inside a function). The implement members fix does not have this problem.
Types do not need to be reformatted, as they are generated with `()`.
Before:
After:
changelog: Fix formatting of completed trait items in trait impls.
=> COMP: reformat completed impl trait items after insertion

toml/src/main/kotlin/org/rust/toml/completion/CargoTomlDependencyFeaturesCompletionProvider.kt, toml/src/test/kotlin/org/rust/toml/completion/CargoTomlDependencyFeaturesCompletionProviderTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7537
changelog: Filter out existing features in dependency features completion
=> COMP: Remove duplicate features in dependency features completion

src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsVisibilityCompletionTest.kt
While working on https://github.com/intellij-rust/intellij-rust/issues/3830, I noticed that the function `RsCompletionTestBase::checkCompletion` does not behave correctly. If no testmark is passed to the function, it basically won't do anything, therefore the test will always succeed.
I changed `checkCompletion` so that it actually does something even without a testmark. It now also throws an error if the passed lookup string is not found.
There were a few tests that used `checkCompletion` without a testmark, so they passed even though they were actually failing. I tried to fix them.
=> COMP: fix RsCompletionTestFixtureBase::checkCompletion

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Related to #3985, fixes (partially, except `Extra error` case) #7420
=> TY&RES: support const arguments that looks like type arguments

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/resources/META-INF/rust-core.xml
Relates to https://github.com/intellij-rust/intellij-rust/issues/6505#issuecomment-853227324.
changelog: Provide an experimental feature to add `--nocapture` flag to `cargo test` command
=> RUN: Provide an registry key to add `--nocapture` flag to `cargo test` command

src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt, src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
changelog: Support usages in derive proc macros in unused imports inspection
=> INSP: Support usages in derive proc macros in unused imports inspection

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
This PR adds basic support for the `format_args_capture` unstable feature, just so that we avoid false positives.
Later we can add proper support for resolving format macro arguments with a reference contributor that would resolve arguments either to named parameters or to local bindings. It would also display unresolved reference errors if no argument is found when `format_args_capture` is enabled.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7332
changelog: Do not warn about missing format macro arguments if `format_args_capture` feature is enabled.
=> ANN: fix false-positive highlighting on implicit named arguments in format macro annotations

src/main/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMover.kt, src/main/kotlin/org/rust/ide/formatter/processors/RsTrailingCommaFormatProcessor.kt, src/test/kotlin/org/rust/ide/actions/mover/RsCommaListElementUpDownMoverTest.kt
=> Up/Down mover: add a trailing comma even when there are multiple elements in the last line

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFix.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/ide/utils/ExtractUtils.kt, src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFixTest.kt
This PR implements the second part of https://github.com/intellij-rust/intellij-rust/pull/5339 by creating a quick fix to implement missing supertrait(s).
I wasn't sure how to solve deep type parameter replacing (see `test recursive generics`). When using normal `Substitution`, the type parameters are replaced correctly, but then we lose type alias information and rendering the resulting trait type will add `dyn`, which we don't want. We can fix the first problem with https://github.com/intellij-rust/intellij-rust/pull/7521 and the second by parametrizing the renderer, but I wonder if there's a way of doing this with `RsPsiSubstitution` instead.
Currently I do use `RsPsiSubstitution`, but it doesn't use recursive type substitution, since I suppose it's not implemented? I wasn't sure how …
=> ANN: add quick fix to implement missing supertrait(s)

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
changelog: Take into account the CARGO_HOME environment variable when using crates local index
=> Take into account CARGO_HOME environment variable in Crates Local Index

.github/workflows/check.yml
Recently released evcxr 0.11 requires at least stable-1.53 or nightly-2021-05-01
=> CI: Disable evcxr tests on nightly-2021-03-24

src/main/kotlin/org/rust/lang/core/psi/RsPsiImplUtil.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
This is also needed for #7550
changelog: Slightly optimize "Find usage" inside files with child modules
=> PERF: Optimize search scope for files with child modules

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt
Now auto-import should not suggest importing `pub(crate)` items from other crates
=> Take into account `pub(crate)` visibility in auto-import

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Fixes:
```rust
use test_package::assert_eq;
fn main() {
assert_eq!();
}
```
changelog: Fix importing macro with same name as macro in prelude
=> RES: Fix imported scoped macro vs textual macro from `extern crate`

src/main/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntention.kt, src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToParameterListIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/MoveTypeConstraintToWhereClauseIntentionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7586.
changelog: Take into account const generics in `Move type constraint to parameter list` quick fix
=> FIX: Take into account const generics in `Move type constraint to parameter list` quickfix

src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7590
changelog: "Add unsafe" quick fix now also supports `impl` items.
=> FIX: add impl support to AddUnsafeFix

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/test/kotlin/org/rust/MockCargoFeatures.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoFeaturesModificationTest.kt, src/test/kotlin/org/rust/cargo/project/model/impl/CargoProjectDeduplicationTest.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterCargoTest.kt, src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixture.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsFragmentSpecifierCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt, src/test/kotlin/org/rustSlowTests/CargoProjectServiceTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt, toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt
1. Cache `RustcInfo` and `StandardLibrary` instances in rust project descriptors.
2. Don't change rust edition for stdlib dependencies by `@MockEdition` (this makes sense only for `WithActualStdlibRustProjectDescriptor`)
3. Use a different macro expansion caching key for `WithActualStdlibRustProjectDescriptor` tests. Now macros in stdlib dependencies will not be re-expanded every time.
4. Some optimization here and there
Points 1-3 make `WithActualStdlibRustProjectDescriptor` tests almost as cheap as `WithStdlibRustProjectDescriptor`.
=> T&PERF: improve tests performance

CONTRIBUTORS.txt, toml/src/main/kotlin/org/rust/toml/completion/CargoTomlCompletionContributor.kt
This commit further implements Rust 2021 Edition support for IntelliJ Rust.
Part of: #6902
Tasks:
changelog: add the value `2021` for autocompletion in the `edition` field of `Cargo.toml`
=> The Rust 2021 Edition Autocompletion

native-helper/Cargo.lock, native-helper/Cargo.toml
Just update ra_ap_proc_macro_srv to `0.0.66`. It works with both 1.54/nightly and older compilers (1.47-1.53)
changelog: fix proc macro expansion with Rust 1.54 and Rust nightly
=> MACRO: fix proc macro expansion with Rust 1.54

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/annotator/fixes/ChangeReturnTypeFix.kt, src/main/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactory.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunctionOrLambda.kt, src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
Fixes #6309
https://user-images.githubusercontent.com/3221931/127149231-385c6eb3-b314-463b-a6dc-72c6c98d7149.mp4
changelog: Highlight function or lambda exit points when the caret at `fn` or `->` token
=> Highlight exit points when the caret at `fn` or `->` token

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/macros/RsMacroData.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinitionBase.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacro2ExpansionTest.kt, src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
Related to #2419
changelog: Provide initial support for `macro 2.0` (like `std::ptr::addr_of`)
=> MACRO: expand macro 2.0

src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7621.
changelog: Take into account `start` feature in `Main function not found` inspection
=> INSP: Take into account `start` feature in `Main function not found` inspection

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
This PR modifies the Extract function refactoring so that it respects aliases. Same as with [`skipUnchangedDefaultTypeArguments`](https://github.com/intellij-rust/intellij-rust/pull/7570), I think that `useAliasNames` should default to `true`.
changelog: Respect type aliases in Extract function refactoring.
=> REF: use aliases in Extract function refactoring

src/main/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspection.kt, src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsCrateTypeAttrCompletionProvider.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspectionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCrateTypeAttrCompletionProviderTest.kt
changelog: `crate_type` attribute now has completion and quick-fix for typos
=> INSP&COMP: Add completion and quick-fix for `crate_type` attribute

src/main/kotlin/org/rust/ide/icons/RsIcons.kt, src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt, src/main/kotlin/org/rust/ide/structure/RsVisibilitySorter.kt, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/structure/RsVisibilitySorterTest.kt
changelog: added "Sort by Visibility" option to Structure View
This is part of an effort to clarify the public APIs of modules. "Sort by Visibility" is a standard option in IDEA plugins, allowing to get a clear view of the public API both at the level of modules and at the level of nested items with more restricted visibility. The main benefit compared to a filter for private items is that one has a clear view of the public API (since those items are sorted to the top), but at the same time keeps the navigation aid for the private API.
=> TYPE: added "Sort by Visibility" option to Structure View

src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Fixes PSI rendering, Ty rendering, and type hints
Fixes #7642
changelog: Fix code generation and type hints related to tuples of size 1 (for example `(i32,)`)
=> Fix rendering tuples of size 1

src/211/main/kotlin/org/rust/ide/inspections/import/RsImportCandidateCellRenderer.kt, src/212/main/kotlin/org/rust/ide/inspections/import/RsImportCandidateCellRenderer.kt, src/main/kotlin/org/rust/ide/inspections/import/ui.kt
Previously, item renderer had a state that kept an instance of `ImportCandidate` for the corresponding psi element. And when `PsiElementListCellRenderer` became asynchronous, it was broken.
Now, we wrap `ImportCandidate` into `FakePsiElement` and get rid of state in psi renderer
Fixes #7609
changelog: Fix item rendering by popup of `Import` quick-fix on 2021.2 IDEs
=> ANN: fix auto-import popup rendering on 212

src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddTypeArguments.kt, src/main/kotlin/org/rust/ide/refactoring/generate/setter/GenerateSetterHandler.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/kotlin/org/rust/lang/doc/psi/impl/RsDocCommentImpl.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoCommandLineTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddTurbofishFixTest.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandlerTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoTypeDeclarationTest.kt, src/test/kotlin/org/rust/ide/structure/RsMacroExpandedFilterTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
* Removed unused imports.
* Removed redundant semicolon.
* Changed `if (v.isNotEmpty()) v else { f}` into more idiomatic `v.ifEmpty { f }`.
* Fixed typos in test names, variable names, function names and strings.
* In AddTurbofishFixTest.kt, `test should not be applied`, the test that an intention doesn't fire includes a typo ("carret" instead of "caret") which makes the test always pass. Fixed the typo.
=> minor typo & style fixes

src/main/kotlin/org/rust/ide/structure/RsStructureViewModel.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt, src/test/kotlin/org/rust/ide/structure/RsStructureViewModelTest.kt
1. Provide visibility icons for macro 2.0 items
2. Show macro 2.0 items in Structure view (`Ctrl` + `F12`)
Also, make `structure view` forward-compatible for possible new kinds of Rust items
c.c. @afetisov
changelog: Show macro 2.0 items in structure view (`Ctrl` + `F12`)
=> Show unstable macro 2.0 items in structure view

src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandConfiguration.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/7595.
TODO: add tests
changelog: Allow removing `Build` step in Cargo Command configurations
=> RUN: Allow removing "Build" step in Cargo Command configurations

src/main/kotlin/org/rust/ide/intentions/visibility/ChangeVisibilityIntention.kt, src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
I noticed that the `Make public fix` has incorrect behaviour when applied to trait impl methods:
The fix could in theory make the whole trait public, but that would be inconsistent with its normal behaviour and it might be weird if the user was calling a method and the fix was offering to make a trait public. So as a first attempt I just disabled the fix in this case.
Btw, when the fix was performed and the method got a `pub(crate)` modifier, the error disappeared from its usage, which is wrong (the visibility should probably be ignored on impl trait methods).
changelog: Do not offer the Make public quick fix on method calls from trait impls.
=> ANN: disable Make Public fix for trait impl methods

intellij-toml/core/src/main/kotlin/org/toml/ide/intentions/TomlElementBaseIntentionAction.kt, intellij-toml/core/src/main/kotlin/org/toml/ide/intentions/TomlExpandInlineTableIntention.kt, intellij-toml/core/src/main/kotlin/org/toml/lang/psi/TomlPsiFactory.kt, intellij-toml/core/src/main/resources/META-INF/toml-core.xml, intellij-toml/core/src/main/resources/intentionDescriptions/TomlExpandInlineTableIntention/after.toml.template, intellij-toml/core/src/main/resources/intentionDescriptions/TomlExpandInlineTableIntention/before.toml.template, intellij-toml/core/src/main/resources/intentionDescriptions/TomlExpandInlineTableIntention/description.html, intellij-toml/core/src/test/kotlin/org/toml/ide/intentions/TomlExpandInlineTableIntentionTest.kt, intellij-toml/core/src/test/kotlin/org/toml/ide/intentions/TomlIntentionTestBase.kt, intellij-toml/src/main/resources/META-INF/plugin.xml, toml/src/main/kotlin/org/rust/toml/intentions/ExpandDependencySpecificationIntention.kt, toml/src/main/kotlin/org/rust/toml/intentions/ExtractDependencySpecificationIntention.kt, toml/src/main/kotlin/org/rust/toml/intentions/RsTomlElementBaseIntentionAction.kt, toml/src/main/kotlin/org/rust/toml/intentions/SimplifyDependencySpecificationIntention.kt
Part of #7180 
Provides an intention for a superset of key-values already covered by `Extract dependency specification` intention for `Cargo.toml`. Also implements a test base for intention actions tests in Toml plugin
* It can be convenient to create an interface which will include both `TomlKeyValueOwner` and `TomlHeader`
* Maybe we should reduce the intention availability range to `TomlInlineTable` only
=> INT: Implement intention to expand inline tables into full ones

toml/src/main/kotlin/org/rust/toml/intentions/RsTomlElementBaseIntentionAction.kt
Fixes Rust plugin incompatibility with Toml `0.2.153.4056-212` introduced in https://github.com/intellij-rust/intellij-rust/pull/7646.
Fixes https://github.com/intellij-rust/intellij-rust/issues/7684
=> Fix `RsTomlElementBaseIntentionAction` for compatibility with non-latest Toml plugin

src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt, src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt
https://github.com/intellij-rust/intellij-rust/pull/7521 somehow regressed inlay type hints, as described in https://github.com/intellij-rust/intellij-rust/issues/7689. I suppose that associated type aliases should be unwrapped to provide more meaningful information for the user. In this PR I did it in a quite heavy way, by outright not setting `aliasedBy` for associated type aliases. We can also just ignore it in selected places (e.g. for inlay type hints [here](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt#L35)).
I have some issues with tests though. Namely, the added `test iterator iter` succeeds even without the change from this PR, even though in the IDE it shows the associated type alias without …
=> TY: ignore associated type aliases

src/main/kotlin/org/rust/ide/utils/checkMatch/Pattern.kt, src/test/kotlin/org/rust/ide/intentions/AddRemainingArmsIntentionTest.kt
This PR fixes a bug discovered in https://github.com/intellij-rust/intellij-rust/pull/7635. Rendering `match` patterns didn't respect type aliases, so it could produce wrong code.
changelog: The intention to add remaining match arms now respects type aliases.
=> INT: support aliases in AddRemainingArmsIntention

src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
This PR adds import of unresolved types after using `CreateFunction/Struct/Tuple struct` intentions.
changelog: Import types after invoking create function/struct/tuple struct intentions.
=> INT: import types in create function/struct/tuple struct intentions

src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
Should help to avoid unnecessary error logs during fetching stdlib metadata (enabled by `org.rust.cargo.fetch.actual.stdlib.metadata` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features))
=> CARGO: handle stdlib crates without Cargo.toml

.github/ISSUE_TEMPLATE.md
When issues contain only screenshots of code, it's tedious to write the code into the editor by hand, so I thought that we could add this little nudge to the issue template.
=> DOC: update GH issue template

src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
The last PR that changed `RsSelfConventionInspection` (https://github.com/intellij-rust/intellij-rust/pull/6842) introduced some false positives. Based on discussion in https://github.com/intellij-rust/intellij-rust/issues/7475, in this PR I tried to align the inspection better with [Clippy](https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention).
What has changed:
- `with` convention now allows functions without any `self` (`Vec::with_capacity` etc.)
- `to` convention now allows `self` or `&self`
- `to_*_mut` convention now allows `&mut self`
- `get_*_mut` convention now allows `&mut self`
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7475
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7520
changelog: Reduce amount of false positives …
=> INSP: remove some false positives from RsSelfConventionInspection

.github/workflows/auto-updates.yml, scripts/common.py, scripts/git.py, scripts/github.py, scripts/update_nightly.py
Currently, nightly rustc version is updated manually and not regularly, which leads to an outdated version of nightly compiler.
These changes introduce new GitHub workflow to update this version automatically from CI.
The schedule is set up to invoke this workflow each Monday for now
=> CI: automatically update nightly rustc version from CI

src/main/resources/META-INF/rust-core.xml
Fixes #7701
Also fixes #7325
| Keyword | Before | After |
|---|---|---|
| `let` | ![before](https://user-images.githubusercontent.com/4854600/129868692-e3d36981-999e-44d1-ab0c-7b838911463b.gif) | ![after](https://user-images.githubusercontent.com/4854600/129868683-d717fb72-c0d0-4a22-81ab-ca853999b851.gif) |
| `else` | ![before2](https://user-images.githubusercontent.com/4854600/129868704-33111ee5-c3db-4de9-a160-ee0216892ca6.gif) | ![after2](https://user-images.githubusercontent.com/4854600/129868701-e4bfb659-a886-40ea-95a3-c385787d12d9.gif) |
This PR also affects the completion variants order. For example, now keywords might be prior to local variables in some cases when they were behind before. However, this particular PR does not change completion variants priority: the order is …
=> Optimize Rust completion contributors order to collect keywords first

src/main/kotlin/org/rust/ide/annotator/fixes/SurroundWithUnsafeFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
Fixes #7634
changelog: "Surround with unsafe" inspection now works identically inside statements and tail expressions
=> INT: Handle tail expressions in "Surround with unsafe" inspection

README.md
Let's rearrange the content in 'Installation & Usage' to look like this:
> For installation options, see the [Quick Start Guide](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-update). If you want to jump straight in, open Settings > Plugins > Marketplace in your IDE, search for Rust and install the plugin. To open an existing project, use File | Open and point to the directory containing Cargo.toml. For creating projects, use the Rust template.
> 
> All the plugin's features are described in [documentation](https://plugins.jetbrains.com/plugin/8182-rust/docs/). New features are regularly announced in [changelogs](https://intellij-rust.github.io/thisweek/).
=> Correcting the 'Installation & Usage' section in readme

.github/workflows/check.yml
Found out that caches created in `branch_A` are available from `branch_B` only of `branch_A` is a base branch for `branch_B`, `branch_A` == `branch_B` or `branch_A` is default branch, i.e. `master` in our case (see https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache for more details). In combination with the fact that we usually don't run `check` workflow for `master` branch (see #7162), it leads to "no caches" situation for the first run of `check` workflow for most pull requests
These changes set up a schedule to run `check` workflow every day to create/update caches from `master` branch and speed up other runs
=> CI: speed up check workflow for pull requests

coverage/src/test/kotlin/org/rust/coverage/RsCoverageTest.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/buildtool/TestBuildViewManager.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTestBase.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/utils.kt
In the beginning (before `Build View`), there wasn't a significant difference between the previous implementation and the current one.
But `Build View` introduced a separate build task that should be executed before the actual running of run configuration. Found out that build task wasn't launched in run configuration tests because of two reasons:
- `RunProfileState.execute` doesn't invoke build tasks at all
- `ExecutionManagerImpl` doesn't run build tasks in tests if `ExecutionManagerImpl.forceCompilationInTests` is `false`
So now we set `ExecutionManagerImpl.forceCompilationInTests` to true and use `ProgramRunner.execute()` (actually, `ExecutionEnvironmentBuilder.buildAndExecute()` but it calls `ProgramRunner.execute()` under the hood)
Note, I've also started to use new approach in …
=> T: improve run configuration tests

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/inspections/RsMissingElseInspection.kt, src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt, src/main/kotlin/org/rust/ide/intentions/IfLetToMatchIntention.kt, src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt, src/main/kotlin/org/rust/ide/intentions/SplitIfIntention.kt, src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithIfExpSurrounder.kt, src/main/kotlin/org/rust/ide/surroundWith/expression/RsWithWhileExpSurrounder.kt, src/main/kotlin/org/rust/ide/utils/ExprUtils.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt, src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt, src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.rs, src/test/resources/org/rust/lang/core/parser/fixtures/partial/exprs.txt
Fixes #7249
Don't show a completion popup automatically when typing a `let binding` identifier starting with a lowercase letter. You still can invoke the completion explicitly (using `ctrl`+`enter`, for example).
https://user-images.githubusercontent.com/3221931/127017258-40e10085-f531-4dc7-a615-7243c28e2906.mp4
If the identifier is uppercase, the user probably wants to type a destructuring pattern (`let Foo { ... }`), so we show the completion popup in this case. In `match`, `if let` and `while let` constructions completion popup is shown as before.
changelog: Don't show a completion popup automatically when typing a `let binding` identifier starting from a lowercase letter. You still can invoke the completion explicitly (using `ctrl`+`enter`, for example).
=> COMP: don't show popup for let binding starting with a lowercase char

src/main/kotlin/org/rust/lang/doc/RsDocPipeline.kt, src/test/kotlin/org/rust/ide/docs/RsRenderedDocumentationTest.kt
Info about that type of links can be found [there](https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html#implied-shortcut-reference-links). In short, string `[ABC]` should be rendered as `<a html="psi_element://ABC">ABC</a>` if there are no references (such as `[ABC]: www.github.com`) and `ABC` looks like valid Rust identifier or path. So it's essentially the same as `[ABC](ABC)` but a little bit shorter.
As far as I know it's not a part of any markdown standard, but it's extensively used in rust docs and worth implementing I think.
Below is one example before/after. The links are clickable
changelog: Display implied shortcut reference links in quick documentation
=> QDOC: Display implied shortcut reference links in quick documentation

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyAdt.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyArray.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyFunction.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyPointer.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyReference.kt, src/main/kotlin/org/rust/lang/core/types/ty/TySlice.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprBuilder.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Advanced type alias support in the type system (#4243, #7521) introduced a challenge: `==` can't be used for type comparison (because it takes into account type aliases) and there's no handy way to check that types are equivalent from the Rust perspective (a non-handy and slow way is `ImplLookup.relativeTo(psi).ctx.canCombineTypes(ty1, ty2)`).
In this PR I introduce `Ty.isEquivalentTo(Ty)` that does the thing. I've used it wherever I can find incorrect `==` for `Ty`s. It looks like I fixed several bugs.
changelog: Introduce `Ty.isEquivalentTo(Ty)` for `Ty`s comparison. Unlike `== `, it ignores `aliasedBy`
field.
=> TY: introduce `Ty.isEquivalentTo` that should replace `==` for `Ty`s

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt
In [rustc](https://github.com/rust-lang/rust) project, we use project crates as stdlib so we don't need to do anything special to get proper metadata for them. Otherwise, it may break our analysis
Note, we still have a lot of false-positive errors in rustc project but it looks like they are not related to stdlib metadata machinery and they should be fixed separately
Related to #6104
changelog: Don't fetch stdlib metadata for `rustc` project since it's already fetched during project structure setup
=> CARGO: don't fetch stdlib metadata for rustc project

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Closes #7722 
Previously the plugin either printed no visibility qualifiers in the quick documentation (for private items with no visibility specified), or always printed "pub", even for items with restricted visibility. That's confusing: you invoke completion and pick a function from the list looking at the documentation, but the function turns out private to some module, even though it was listed as public. It's also confusing to get a "cannot use private item" error from the compiler while the item is "pub" in the docs.
I have changed it to print the actual qualifiers specified in the source code. Benefits:
* It doesn't provide false information (e.g. `pub(crate)` items printed as if they are public);
* It faithfully represents the visibility specified in the code, which may be …
=> QDOC: print actual visibility for items with restricted visibility

src/main/kotlin/org/rust/ide/presentation/Utils.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt
Fixes #7749
changelog: Properly render negative `impl` items in `Go to implementation` popup
=> Render negative `impl`s properly

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, MAINTAINING.md
Signing CLA is not needed because of GitHub Terms of Service:
> 6. Contributions Under Repository License
> Whenever you add Content to a repository containing notice of
> a license, you license that Content under the same terms, and
> you agree that you have the right to license that Content
> under those terms. If you have a separate agreement to license
> that Content under different terms, such as a contributor
> license agreement, that agreement will supersede.
>
> Isn't this just how it works already? Yep.
> This is widely accepted as the norm in the open-source
> community; it's commonly referred to by the shorthand
> "inbound=outbound". We're just making it explicit.
https://docs.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license
=> DOC: Drop CLA requirement

src/main/kotlin/org/rust/cargo/project/model/ProcessProgressListener.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
The main goal is to show the user what went wrong during project structure setup (if it happened). Also, it may help to catch some tricky cases that we haven't caught yet, since now warnings/errors are visible for users
Note, currently there is no way to show an error in `Sync View` and not to add an error icon for parent nodes
changelog: Show warning/errors during fetching info about stdlib in [Sync View](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-cargo-tool-window.html)
=> CARGO: show warning/error during stdlib metadata fetching in Sync View

ml-completion/src/main/kotlin/org/rust/ml/RsMLRankingProvider.kt
This PR enables the new ML-based code completion ranking by default. See https://github.com/intellij-rust/intellij-rust/pull/6419 for more information on this feature.
In case of any issues, the new ranking model can be disabled in `Editor | General | Code Completion | Machine Learning-Assisted Completion` settings. 
Part of #6411
changelog: Enable by default code completion ranking for Rust based on machine learning. Now the completion suggestions are sorted by their relevance based on the rules learned from data we have gathered anonymously during our EAPs. Note that we have not collected any source code, only information about your interactions with the code completion UI. In case of any issues, you can disable the new ranking model via `Editor | General | Code Completion | Machine …
=> Enable by default ML code completion ranking for Rust

src/main/resources-stable/META-INF/experiments.xml
Fixes #3957
Fixes #4960
Fixes #5881
Fixes #6081
Part of #6104
changelog: Enable fetching actual info about stdlib packages like dependencies, [edition](https://doc.rust-lang.org/edition-guide/editions/index.html), Cargo [features](https://doc.rust-lang.org/cargo/reference/features.html) by default. It should help the plugin better understand stdlib structure, for example, provide proper completion and navigation for items defined in `std::os` module. In case of any issue, you can turn this feature off via `org.rust.cargo.fetch.actual.stdlib.metadata` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)
=> CARGO: enable fetching actual stdlib metadata

build.gradle.kts, src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspectionTest.kt
Fixes: #3681
changelog: Deprecated item inspection now correctly handles items that will be deprecated in a future version.
=> INSP: Using a function that is going to be deprecated should warn

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Fixes #7788
changelog: Generate [const generics](https://rust-lang.github.io/rfcs/2000-const-generics.html) by `Implement Members` quick-fix properly
=> ANN: generate const generics by `Implement Members` quick-fix properly

src/main/kotlin/org/rust/ide/inspections/checkMatch/RsUnreachablePatternsInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLintHighlightingType.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsWhileTrueLoopInspection.kt
Decouple `RsLint` enum and highlighting type, and introduce `RsLintHighlightingType`.
It allows customizing highlighting for any lint even if you need different highlighting in different situations (see #3790 as an example) for the same lint in the same way in a single line. Previously, you had to override `RsLint#toHighlightingType` method and/or pass anonymous function
=> INSP: simplify lint inspection API

src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/RustcMessage.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/wsl/RsWslToolchain.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/openapiext/RsPathManager.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt, src/test/kotlin/org/rustSlowTests/console/RsEvcxrTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt
changelog: Fix macros and generated items support for WSL toolchains
Fixes
```
2021-07-11 21:11:39,418 [71319350]   WARN - st.cargo.toolchain.tools.Cargo - Execution failed (exit code 101).
C:\WINDOWS\system32\wsl.exe --distribution Ubuntu --exec /bin/sh -c "export PATH=\"/home/misha/.cargo/bin:$PATH\" && export RUST_BACKTRACE=short && export RUSTC_WRAPPER=/mnt/c/Users/Mikhail/IdeaProjects/intellij-rust/plugin/build/clion-sandbox-212/plugins/intellij-rust/bin/windows/x86-64/intellij-rust-native-helper.exe && export TERM=ansi && cd /mnt/c/Users/Mikhail/CLionProjects/untitled8 && /home/misha/.cargo/bin/cargo check --message-format json"
stdout : error: failed to join search paths together
Does $LD_LIBRARY_PATH have an unterminated quote character?
Caused by:
failed to join path array: …
```
=> RUN: Fix macros and generated items support for WSL toolchains

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
I have combined the API for filtering generic parameters and PSI rendering, inspired by `AddMissingSupertraitFix`. It would be nicer if there was some generic API that would support scenarios like "create a reasonable impl item from the context of an existing impl item".
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7801
changelog: Generate generic bounds and where clauses when creating inherent impl items in `Extract function` refactoring.
=> REF: create generics and where clauses for inherent impl items in RsExtractFunctionHandler

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2021.kt
Fixes #7796
Related: https://github.com/rust-analyzer/rust-analyzer/pull/9097
changelog: Use correct prelude for 2021 edition
=> RES: Fix injecting prelude in 2021 edition

src/main/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroGraphWalkerTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Fixes #7785
changelog: Fix resolving [`asm!`](https://doc.rust-lang.org/beta/unstable-book/library-features/asm.html) macro on nightly rust
=> RES: Fix resolving macros 2 from prelude

src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt
While checking `rustc` sources, I noticed that the plugin wrongly shows E0046 (methods missing in trait impl) for negative impls. This PR fixes that. 
changelog: Do not show the E0046 error for negative trait impls.
=> INSP: do not show E0046 for negative trait impls

src/main/kotlin/org/rust/lang/core/dfa/ControlFlowGraph.kt, src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt
Fixes #7833
| - | - |
| ![image](https://user-images.githubusercontent.com/3221931/133041657-913a9793-3e46-4082-a043-41234607ea32.png) | ![image](https://user-images.githubusercontent.com/3221931/133063298-58917a18-6015-459a-8e3f-3a709d3c6733.png) |
changelog: Don't highlight string literals in macros as exit points
=> Don't highlight string literals in macros as exit points

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
Strictly speaking, this fixes the case when several mod declarations point to the same file:
```rust
#[cfg(foo)]
mod foo; // foo.rs
#[cfg(not(foo))]
mod foo; // foo.rs, as well
```
changelog: Fix incorrect resolve in some cases when there is both cfg-disabled and cfg-enabled mod with the same name
=> RES: Fix that cfg-disabled mod can affect cfg-enabled mod with same name

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
* Improve rendering of macro 2.0 header
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/132830513-373d1273-b83b-4248-bc0c-ed0686787714.png) | ![image](https://user-images.githubusercontent.com/2539310/132830488-cb36e934-719d-4870-81be-f5ee231e5b73.png) |
* Properly generate external links if a macro has parent modules, for example, `std::prt::addr_of`
* Improve documentation link resolution if a macro has parent modules. Note, these changes do nothing with [intra-doc links](https://doc.rust-lang.org/rustdoc/linking-to-items-by-name.html)
Also, I've added some missing tests for macro 1.0
changelog: Improve documentation rendering for [macro 2.0](https://rust-lang.github.io/rfcs/1584-macros.html) as well as external link generation and resolution
=> QDOC: improve macro 2.0 documentation

src/main/kotlin/org/rust/lang/core/completion/RsCompletionConfidence.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionAutoPopupTest.kt
Fixes #7789
The bug was introduced in #7582
```
let /*typing mut here*/foo = 1;
```
changelog: Fix showing completion autopopup when typing `let mut` with existing ident (`let /*typing mut here*/foo = 1;`)
=> Show completion autopopup when typing let mut with existing ident

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacro2.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroDefinitionBase.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsMacroBracketCompletionTest.kt
Use the same rules that we use for macro 1.0, i.e.:
- add `!` to item in completion list
- insert `;` if complete item in `use` statement and `!` otherwise
- insert proper braces (based on documentation) outside of use items
changelog: Improve completion of [macro 2.0](https://rust-lang.github.io/rfcs/1584-macros.html), i.e. insert `!` and proper braces (based on documentation) if needed
=> COMP: improve macro 2.0 completion

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsUseResolveTest.kt
Fixes #7233
changelog: Fix that glob import can override named item in some cases
=> RES: Fix that glob import can override named item in some cases

src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/main/kotlin/org/rust/ide/utils/import/UseItemWrapper.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/main/kotlin/org/rust/stdext/Collections.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt, src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Previously import was added after all existing imports. Now import will be added at correct location (according to order used by "Optimize imports" action). This is also needed for #7660
changelog: Insert import at correct location during auto-import
=> INSP: Insert import at correct location during auto-import

src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
This [issue](https://github.com/intellij-rust/intellij-rust/issues/7830) produced an interesting situation. In the following code (which has a syntax error in the reference lifetime):
```rust
fn foo(a: &u32) {}
fn main() {
let a = 1;
foo(&'static a);
}
```
the `foo` call is parsed as having two arguments. Therefore the `RemoveRedundantFunctionArgumentsFix` shows up, which tries to remove the argument `a`, along with its surrounding whitespace and comments. The code that handles this is `RsElement.deleteWithSurroundingCommaAndWhitespace` in `RsElement.kt`:
```kotlin
fun RsElement.deleteWithSurroundingCommaAndWhitespace() {
while (nextSibling?.isWhitespaceOrComment == true) {
nextSibling?.delete()
}
while (prevSibling?.isWhitespaceOrComment == true) {
prevSibling?.delete()
} …
```
=> ANN: fix infinite loop when invoking a quick fix on an element with a syntax error

.idea/runConfigurations/Generate_Parser.xml
The configuration was broken in #7828 because of TOML plugin source removal
=> Fix `Generate Parser` run configuration

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/main/kotlin/org/rust/openapiext/utils.kt, src/main/kotlin/org/rust/stdext/CompletableFuture.kt
Now we expand macros in new resolve using following pipeline:
* Resolve all macros (single thread)
* Expand macros in batches (multithread). Usually [macro cache](https://github.com/intellij-rust/intellij-rust/pull/6212) is used here
* Add expanded elements from all macros to DefMap (single thread)
Most performance impact will be on crates with lots of procedural macros (such as [`web-sys`](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/web-sys)) or when we expand macros first time (without cache).
Here is performance comparison on my 8-core machine with code from #7194 (note that currently we use at most 4 processes to expand procedural macros):
project | macro cache? | single-thread | multi-thread | difference
------- | ------------ | ------------- | ------------ | …
=> PERF: Expand macros in parallel during CrateDefMap building

src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/ide/intentions/SpecifyTypeExplicitlyIntentionTest.kt
changelog: Fix inserting import at the correct location when importing an item from the different crate
=> RES: Fix inserting import to different crate at correct location

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsBreakOnPanicConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerGeneralSettingsConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerUiComponent.kt
This PR adds the option to break the debugger on any rust panic.
I had to slightly modify the debugger configurable implementation. Previously, only the toolchain options were inside the general debugger settings. I could not add another configurable, because it would have a duplicated `Rust` header, so I had to add the `break on panic` setting to the existing configurable that is used inside the general settings.
To keep the individual settings separate, I split them into separate classes so that they are not all mixed up. I also created a new base class (`RsDebuggerUiComponent`), because I didn't know how to compose `JComponent`s of multiple objects inside a single `panel` in the `getComponent` method in `RsDebuggerGeneralSettingsConfigurableUi`.
Fixes: …
=> DBG: automatically break on panic inside debugger

src/main/resources/META-INF/rust-core.xml
Closes #1171
Depends on https://github.com/intellij-rust/intellij-rust/pull/7279, https://github.com/intellij-rust/intellij-rust/pull/7217, https://github.com/intellij-rust/intellij-rust/pull/7316, https://github.com/intellij-rust/intellij-rust/pull/7285, https://github.com/intellij-rust/intellij-rust/pull/7506, https://github.com/intellij-rust/intellij-rust/pull/7501.
changelog: Enable WSL toolchains by default
=> RUN: Enable WSL toolchains by default

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7866.
changelog: Show error when defaults for const parameters are used in `fn`s or `impl`s
=> ANN: Show error when defaults for const parameters are used in `fn`s or `impl`s

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesDialog.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesHandler.kt
Previously you can use drag-and-drop to move file to same directory, and receive error "File with same name already exists". This PR prevents moving file to same directory using drag-and-drop, and a bit improves error message (in case user tries to move file to same directory using shortcut)
Fixes #7712
cc @neonaot 
changelog: Don't offer to move file to same directory in file tree
=> REF: Don't offer to move file to same directory

native-helper/Cargo.lock, native-helper/Cargo.toml
Just update ra_ap_proc_macro_srv to `0.0.70`. It works with both 1.56/nightly and older compilers (1.47-1.55)
changelog: fix proc macro expansion with Rust 1.56 and Rust nightly
=> MACRO: fix proc macro expansion with Rust 1.56

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt, src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/actions/RsToggleNewResolveAction.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/NewResolve.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
We plan to gradually remove ability to use old resolve. As a first step option from settings is removed. Users can still disable new resolve using `org.rust.resolve.new.engine` registry option.
changelog: We gradually deprecate old name resolution engine. As a first step we remove option "Use new name resolution engine" from settings. Please fill an issue if you encounter any problems with new resolve engine.
=> RES: Move option to disable new resolve from settings to registry

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveTraitMethodsProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Fixes #7781
Related: #6301
E.g. when moving
```rust
use std::str::FromStr;
fn func() {
Foo::from_str("");
}
```
when `Foo` implements `FromStr`, then import for `FromStr` will be added to target mod.
changelog: Add trait imports for UFCS trait method calls in move refactoring if necessary
=> REF: Add trait imports for UFCS in move refactoring if necessary

.github/workflows/rust-release.yml
=> CI: drop temporary 211 builds from release workflow

src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt, src/test/kotlin/org/rust/ide/intentions/CreateStructIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/CreateTupleStructIntentionTest.kt
This PR adds a template builder to fill in unknown types in `CreateStructIntention` and `CreateTupleStructIntention`.
Structs:
Tuple structs:
It seems that the hacky `RsMultipleVariableRenamer` is no longer needed with the new template API, I'll try to remove it in another PR.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7672
changelog: Intentions to create structs and tuple structs will now let the user fill in unknown field types.
=> INT: use template to fill unknown field types in Create(Tuple)StructIntention

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/RemoveRedundantFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureHandler.kt, src/main/kotlin/org/rust/stdext/Utils.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt
This PR improve the `Change signature` quick fix. It now also allows changing parameter types and removing extraneous parameters at the end of the signature (in addition to adding new parameters, which it could do before. A discussion of this feature is present [here](https://github.com/intellij-rust/intellij-rust/pull/6745#issuecomment-858554947).
changelog: Improve the `Change signature` quick fix. It can now also change parameter types and remove extraneous parameters from the end of the signature.
=> ANN: improve Change function signature fix 

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTestEdition2018.kt
changelog: Fixes that some stdlib crates (e.g. `alloc`) can be resolved without corresponding `extern crate` declaration
=> RES: Fix that `alloc` crate can be resolved without `extern crate`

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Consider import adds item to scope of module. Previously in new resolve visibility of added scope entry will be same as visibility of import. Actually its visibility should be intersection of import visibility and item visibility
changelog: Fix visibility of publicly reexported item with restricted visibility
=> RES: Fix visibility of reexported item with restricted visibility

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoProjectsTree.kt, src/test/kotlin/org/rustSlowTests/CargoProjectStructureTest.kt, src/test/kotlin/org/rustSlowTests/CargoProjectsTreeTest.kt
New names are the same as line markers provide. Also, it's less likely that they conflict (and replace) existing ones because of more specific names
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/134887330-62bd2ca7-2b80-4ea9-875b-d17ec8630d44.png) | ![image](https://user-images.githubusercontent.com/2539310/134889473-3713cda0-b352-472f-ba3e-77ed8eef038d.png) |
changelog: Generate proper names for run configurations provided by Cargo tool window to be consistent with run configurations created from line markers
=> RUN: generate proper names for run configurations provided by Cargo tool window

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt
Previously, build manager showed build error balloon over `Messages` tool window tab for some reason.
But the plugin doesn't interact with this tool window at all and prints all build output to `Build` tool window.
Moreover, in most cases `Messages` tool window doesn't have any active tab and a user can't even open it. It's rather confusing
After these changes, the plugin will show build error balloon over `Build` tool window tab to be consistent with build output and not confuse users
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/132104584-2b8087cc-e33f-4bb6-9063-4434bcce06f5.png) | ![image](https://user-images.githubusercontent.com/2539310/132104582-5140ac9a-a38d-46e4-a594-a59daa453dfe.png) |
changelog: Show build error balloon over `Build` …
=> RUN: show build error balloon over proper tool window

src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt
Fixes a typo from #2719 which may lead to incorrect PSI creation when macro is in type context, e.g. `type X = foo!();`
=> Fix RsMacroType stub

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt
changelog: Fix some cases when cfg-disabled glob-import affects cfg-enabled one
=> RES: Fix some cases when cfg-disabled glob-import affect cfg-enabled one

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/intentions/RunCargoExpandIntention.kt
Fixes #7762
changelog: Make `Show the result of macro expansion (cargo expand)` intention use dark theme for output if IDE is under dark theme
=> INT: use dark theme for `cargo expand` if IDE uses dark theme

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapter.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildAdapterBase.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildContext.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
These changes use code to parse Cargo build messages and show them in Build View to show compilation errors in build scripts during project loading.
For example, compilation error in build script code
or even compilation-time panics from build script launches
Fixes #4699
changelog: Show build script evaluation errors in Sync View when `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) is enabled. It should simplify diagnostics why features based on compile-time information don't work as expected
=> CARGO: show build script errors in Sync View

src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeParser.kt, src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt
Fixes #8019
changelog: Fix expansion of procedural macros that contain `_` in the macro body
=> MACRO: parse `_` as an identifier in proc macro bodies

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Fixes #7865
I found that it's possible to use `<T as Trait>` syntax in type aliases when `T` does not have the corresponding bound `Trait`.
```rust
trait Trait {
type Item;
}
type Alias<T> = <T as Trait>::Item;
```
Previously, `<T as Trait>::Item` was unresolved.
changelog: Fix name resolution of explicit type-qualified associated types in type aliases (like `type Alias<T> = <T as Trait>::Item;`). This fixes type inference in `hecs` crate
=> TY&RES: resolve explicit type-qualified associated types in type aliases

src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
... if `org.rust.macros.proc` experimental feature is enabled
changelog: Enable `unresolved reference` inspection for attribute macros if `org.rust.macros.proc` experimental feature is enabled
=> INSP: Enable unresolved reference inspection for attr macros 

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt
It was quite annoying that the `Update function signature` fix was above `Import` quick fix. This change moves the import quick fix to the top priority, as I suppose that in most cases it will be the most important fix on a given element.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7929
changelog: Show the `Import` quick fix higher in intention list.
=> ANN: use top priority for AutoImportFix

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Fixes #7502.
Fixes #7695.
Previously type inference incorrectly treated nested expression blocks as nested loops, which would mean that breaks with no specified label from within nested blocks was treated as a non-returning break from a nested loop, so that the break value type was correctly propagated only when explicitly breaking by label.
changelog: Fixed type inference for breaks out of the loop nested within expression blocks
=> TY: fix type inference for break from a nested expression block

src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt, src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt, src/main/kotlin/org/rust/ide/refactoring/RsNameSuggestions.kt, src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt, src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt
This PR adds basic handling of name collisions in `RsIntroduceConstantHandler`.
@dima74 Is there a better way to get all bindings/names at a given place?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7957
changelog: Handle name collisions in Introduce Constant refactoring.
=> REF: handle name collisions in RsIntroduceConstantHandler

src/main/kotlin/org/rust/ide/inspections/fixes/AddRemainingArmsFix.kt, src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
Fixes #7759
```kotlin
enum E { A, B, C }
fn test(e: E, i: i32) {
match e
match i
match {}
}
```
↓
=> "Add remaining patterns" quickfix: add patterns even if no `match` body

src/main/kotlin/org/rust/ide/inspections/RsConstantConditionIfInspection.kt, src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt, src/main/kotlin/org/rust/ide/inspections/RsRedundantElseInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsConstantConditionIf.html, src/test/kotlin/org/rust/ide/inspections/RsConstantConditionIfInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/RsRedundantElseInspectionTest.kt
We have `RedundantElseInspection` which works for irrefutable patterns and always true `if`-conditions. This PR adds new inspection which works for both always true and always false `if`-conditions. And `RedundantElseInspection` now checks only irrefutable patterns. 
changelog: Add "simplify if with constant condition" inspection
=> INSP: Add "simplify if with constant condition" inspection

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/MakePublicFixTest.kt
I noticed that E0451 (struct field is private) wasn't being applied for shorthand field literals. This PR fixes it.
changelog: Support the E0451 compiler error for struct field literals using shorthand init.
=> ANN: support E0451 for shorthand struct field literals

src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt, src/main/kotlin/org/rust/lang/core/psi/RsProcMacroPsiUtil.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAttrProcMacroOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsStructOrEnumItemElement.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapMacroIndexConsistencyTest.kt, testData/test-proc-macros/src/lib.rs
Depends on #7194
changelog: Take into account all kinds of items generated by custom derive procedural macros. Previously only `impl` blocks were accounted. Please, note that procedural macro expansion is experimental. If you want to try it, enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` experimental features
=> MACRO&RES: support arbitrary items expanded from custom derive

src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringAvailability.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt
Do not show `Update ... to reflect signature changes` if only a parameter type was changed (as that cannot be reflected by the refactoring anyway).
changelog: The `Change signature` refactoring is no longer offered automatically on function parameter type changes.
=> REF: ignore parameter type changes in suggested change signature refactoring

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt
We do not allow this refactoring on functions with any cfg-disabled parameters, so it should not change anything.
It was causing the following exception:
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:110)
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:754)
at com.intellij.psi.stubs.StubIndexImpl.getContainingIds(StubIndexImpl.java:501)
at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:305)
at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:51)
at …
```
=> REF: do not use resolve in RsChangeFunctionSignatureConfig::create

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/ext/RsIndexExpr.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsIndexExprReferenceImpl.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIndexExprResolve.kt
This PR adds reference to `Index` trait implementation from the left bracket of indexing expressions. I'm not sure how to also add support for the right bracket though. The `referenceNameElement` property allows returning only a single element and I cannot set `rangeInElement`, because the bracket ranges are disjoint.
The only thing that comes to mind is to implement something like `RsIndexExprImplMixin1` and `RsIndexExprImplMixin2`, where each will provide a reference for one of the brackets. But it seems like there should be an easier way.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7895
changelog: Resolve references to `Index` trait implementations for brackets (`[`, `]`) inside indexing expressions.
=> RES: add reference to Index trait for bracket indexing expressions

src/main/kotlin/org/rust/ide/inspections/RsConstantConditionIfInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsConstantConditionIfInspectionTest.kt
#8030 generates correct text with invalid PSI in some cases (e.g. `RsExprStmt` inside `RsExprStmt`), which may lead to exceptions. This PR fixes generated PSI.
<details>
```
java.lang.Throwable
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:284)
at org.rust.lang.core.psi.impl.RsExprStmtImpl.getExpr(RsExprStmtImpl.java:33)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.processStatement(TypeInferenceWalker.kt:151)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferType(TypeInferenceWalker.kt:108)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferTypeCoercableTo(TypeInferenceWalker.kt:101)
at org.rust.lang.core.types.infer.RsTypeInferenceWalker.inferFnBody(TypeInferenceWalk …
```
=> INSP: Fix "simplify if with constant condition" generated PSI

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Previously, if root `Cargo.toml` defined both package and workspace, the plugin compiled only package. As a result, the plugin knew nothing about items generated in other workspace packages.
Now, we pass `--workspace` flag to compile all packages in workspace and get info about generated items in all packages
Should fix #5878
changelog: Fix build script evaluation in [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html). Note, build script evaluation is disabled by default. To turn it on, enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)
=> CARGO: fix build script evaluation in workspace

src/main/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntention.kt, src/test/kotlin/org/rust/ide/intentions/UnwrapSingleExprIntentionTest.kt
I noticed that `UnwrapSingleExprIntention` does not work for blocks with a single statement. I suppose that if a block contains exactly a single statement, no tail expressions, and that statement is a `RsExprStmt` statement with type `()`, then the intention should be available for it.
For example:
```rust
match foo {
// here the intention should be able to turn this into `V1 => println!("foo")`
V1 => { println!("foo");/*caret*/ }
}
```
I'm not sure if `expandedStmtsAndTailExpr` is necessary or if it's fine to just use `stmtList`.
changelog: The intention for removing braces from a single expression now also works for blocks that contain a single statement.
=> INT: generalize UnwrapSingleExprIntention to support single statement expressions

build.gradle.kts
No major changes. A version file `version.txt` has been added to the metadata.
=> Update Rust ML ranking provider to 0.2.3

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8050.
changelog: Render parentheses for type references in `Implement Members` refactoring
=> ACT: Render parentheses for type references in `Implement Members` refactoring

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/util/TestUnitTestRustcCacheService.kt, src/main/kotlin/org/rust/cargo/util/UnitTestRustcCacheService.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/cargo/util/TestUnitTestRustcCacheService.kt
I suppose that `sysroot`, a `list of targets`, `--print cfg` and `stdlib` are not changed until the version of rustc is changed, so we can cache these values for all tests. The cache significantly speeds up heavy tests with a full toolchain (`RsWithToolchainTestBase`), in my case it is 30% speedup for `rustSlowTests`.
=> T&PERF: speed up toolchain tests by caching some values from rustc

src/main/kotlin/org/rust/cargo/project/workspace/RsAdditionalLibraryRootsProvider.kt, src/main/kotlin/org/rust/lang/core/indexing/RsIndexableSetContributor.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
In #8012 we started using `IndexableSetContributor` to provide locations that should be indexed. But this solution changes the scope of generated files. As a result, any code that uses index search with `GlobalSearchScope.allScope(project)` or `RsWithMacrosProjectScope` scopes doesn't process code from generated files. For example, it breaks `impl` block search during type inference
These changes use `AdditionalLibraryRootsProvider` to create a fake library from generated code. It restores the previous search scope for generated code and makes index search work as before
Fixes #8057
Since it's a fix of #8012, no changelog section here
=> RES: fix search scopes for generated code

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/Substitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsNumericLiteralTypeInferenceTest.kt
Fixes #7302
Fixes #4475
Fixes #6547
Fixes #5897
Fixes #3987
Fixes #5483
Consider this code:
```rust
pub trait Trait<T> { 
type Item; 
}       //X
struct S;            
impl Trait<i32> for S { 
type Item = (); 
}
impl Trait<u8> for S { 
type Item = ();
}
pub type Alias<T> = <S as Trait<T>>::Item;
//^
```
Previously we had multiresolve on `<S as Trait<T>>::Item` path. Now we just resolve it to the trait. The `impl` will be selected later during type inference (in a place where the concrete impl is really needed for type inference).
This also fixes the same as #8033 (#7865), but in a different way
=> TY&RES: resolve an associated type to a trait if we're unsure about the impl

src/main/resources-stable/META-INF/experiments.xml, toml/src/main/resources/META-INF/toml-only.xml
Enable `org.rust.crates.local.index` experimental feature for all users on stable and disable version-related inspections for now due to false positives
changelog: Enable crates local index on stable to provide analysis for dependencies inside `Cargo.toml` manifest. Currently, it offers completions for `crates.io` dependencies' names and versions, inspections for non-existent packages in the index, and automatically updates with cargo crates index updates
=> TOML: Enable crates local index on stable

src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt, src/main/kotlin/org/rust/ide/security/trustedProjectUtils.kt
Project trusted API will be changed in coming IDE versions (2021.3.1 and 2021.2.4).
Two main changes:
- IDE will ask if users trust project on the first project opening for every project so we don't need to do it in the plugin
- some corresponding API will be changed so we shouldn't call it at all to avoid runtime errors
These changes introduce `isOldTrustedProjectApiAvailable` property to indicate if old API is available and adjust `CargoProjectOpenProcessor` implementation
changelog: Prevent future runtime errors during project opening because of incompatibility changes in future IDE versions
=> CARGO: prevent some runtime errors in future IDE versions

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringAvailability.kt, src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringExecution.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringTest.kt
Follow-up and partial revert of https://github.com/intellij-rust/intellij-rust/pull/8042 (based on [this](https://github.com/intellij-rust/intellij-rust/pull/8042#issuecomment-967006776) comment).
I included some comments in the code that explain why some more changes needed to be made.
changelog: Enable suggested signature refactoring when a type of a trait method parameter changes.
=> REF: Enable suggested signature refactoring for trait methods

src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt, src/main/kotlin/org/rust/ide/refactoring/introduceVariable/RsIntroduceVariableHandler.kt, src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt, src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt, src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt
This involves a change to the tests. The old behaviour was breaking code since it changed the returned value of the block from T to (), and breaking code is bad. It's also trivially easy to change the returned value after refactoring to a more complex expression, since only a single identifier should be returned.
This commit also includes a fix for extracting several occurrences of an expression. Previously if we extracted an RsExprStmt, then the logic would short-circuit and extract only it, ignoring the possibility of other occurrences.
Fixes #8099
Fixes #8095
Fixes #8082
Fixes #8091
changelog: fix ["Extract variable"](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractvar-refactoring) refactoring on expression statements and return values
=> REF: fix extract variable on RsExprStmt and last expr in block

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/lang/core/crate/Crate.kt, src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt, src/main/kotlin/org/rust/lang/core/crate/impl/DoctestCrate.kt, src/main/kotlin/org/rust/lang/core/crate/impl/FakeDetachedCrate.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt, src/main/kotlin/org/rust/lang/core/resolve2/DetachedDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/main/kotlin/org/rust/openapiext/utils.kt, src/test/kotlin/org/rust/lang/core/resolve/RsNonPhysicalFileResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapMacroIndexConsistencyTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
changelog: Use new name resolution engine inside detached files (without crate root). This e.g. allows resolving [macros 2.0](https://rust-lang.github.io/rfcs/1584-macros.html) in such files
=> RES: Use new resolve inside detached files

debugger/src/main/resources/META-INF/native-debug-only.xml
Provide default implementation of `cidr.debugger.languageSupport` extension point.
CLion relies on the existence of default implementation of this EP. And it exists in CLion.
But in IDEA with Native Debugging Support plugin, there is no such implementation by default, so we can get NPE if the platform tries to do something with non-Rust stack frame.
This change is a hack just to avoid NPE. A proper solution will be landed as a fix of https://youtrack.jetbrains.com/issue/CPP-27382
Fixes #8122
changelog: Fix exception during debugging in IDEA 2021.3
=> DBG: fix NPE in debugger support in IDEA

src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt
Discussed in https://github.com/intellij-rust/intellij-rust/pull/7841.
=> Collect surrounding whitespace and comments before deleting them in `deleteWithSurroundingCommaAndWhitespace`

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
changelog: Annotate [macro 2.0](https://rust-lang.github.io/rfcs/1584-macros.html) definitions as experimental and provide quick-fix to add `decl_macro` feature on nightly toolchain
=> ANN: annotate macro 2.0 definitions as experimental

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
Relates to https://github.com/intellij-rust/intellij-rust/pull/7897.
=> Fix warnings in logs due to incorrect check for `Eq` trait implementation

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
changelog: Take into account const generic parameters while `<>` completion
=> COMP: Take into account const generic parameters while `<>` completion

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Fixes #7394
changelog: Use absolute import path in auto-import when the scope has child mod with the same name as extern crate
=> Auto import: use absolute path for extern crate if needed

src/main/kotlin/org/rust/lang/core/resolve2/FileModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapUpdateChangeSingleFileTest.kt
changelog: Fixes caching of resolve when adding or removing `#![no_std]` attribute
=> RES: Fix updating DefMap when adding `#![no_std]`

src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
For now, usages are searched in the current mod only
Meta issue: #2158
changelog: Support usages in attribute proc macros in unused imports inspection
=> INSP: Support usages in attr proc macros in unused imports inspection

.github/workflows/check.yml
Improves #7778
The bug is that `Install cargo-generate` step takes about 8m in every CI run on windows
=> CI: fix `cargo-generate` binary caching on Windows CI

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Continuation of #8029 for auto-import traits for UFCS.
Meta issue: #7558
changelog: Improve traits auto-import for [UFCS](https://doc.rust-lang.org/1.7.0/book/ufcs.html) methods
=> INSP: New auto-import for UFCS trait methods

.github/dependabot.yml
Setup [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates) that will update `ra_ap_proc_macro_srv` in `native-helper/Cargo.toml`.
Hence we will receive updates quicker and keep compatibility with nightly Rust.
=> CI: setup Dependabot for updating `ra_ap_proc_macro_srv`

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReturnTypeFixTest.kt
Depends on #8054
Meta issue: #7558
changelog: Improve paths generation in refactorings and inspections
=> New auto-import for refactorings and inspections

src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
The `self` convention inspection had a lot of annoying false positives with the `get`, `set` and `with` patterns (https://github.com/intellij-rust/intellij-rust/issues/7475#issuecomment-976434220, https://github.com/intellij-rust/intellij-rust/issues/7475). These patterns are used in pretty much all `self` scenarios in the wild, as found out by @afetisov (https://github.com/intellij-rust/intellij-rust/pull/7557#issuecomment-883506073, https://github.com/intellij-rust/intellij-rust/pull/7557#issuecomment-884224559). I already wanted to remove them in the last PR that modified the convention (https://github.com/intellij-rust/intellij-rust/pull/7557#issuecomment-884227697), but didn't get to it.
This PR removes all `get`, `set` and `with` patterns from the convention. Now the convention …
=> Remove get, set and with patterns from RsSelfConventionInspection

gradle-213.properties, gradle.properties
changelog: Make 2021.3 platform default for development
=> GRD: make 2021.3 platform default for development

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8109.
Relates to https://github.com/intellij-rust/intellij-rust/issues/6633.
changelog: Update inspections for Type Aliases
=> ANN: Update inspections for Type Aliases

src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
```rust
struct N;
//X
fn bar<T>() {}
fn foo<const N: i32>() {
bar::<N>();
}       //^
```
=> RES: Correctly disambiguate unit struct vs const to struct

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Fixes #8143
changelog: Fix false-positive unresolved reference for UFCS path inside trait impl when using unnamed trait import
=> INSP: Fix false-positive unresolved reference for UFCS

src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
```rust
struct u8;
let a: u8; // this is a struct "u8", not a primitive type "u8"
```
This also fixes several "Use of moved value" inspection false positives. 
Previously, this code contained a false positive "Use of moved value" for the second use of `a` because our trait engine thought that there is an ambiguous impl of trait `Copy` for a primitive type `f64`. But actually, it is not an impl for the primitive type.
```rust
struct f64;
impl Copy for f64 {} // An impl for "struct f64", NOT for a primitive type "f64"
fn main123() {
let a = 1.0;
let b = a;
let c = a; // <-- no move here
}
```
Fixes #7755
Fixes #4858
Fixes #7246
changelog: 1) Fix several "Use of moved value" inspection false positives (for example, in `bevy` crate). 2) Correctly infer a type of a struct/enum with the same …
=> TY: correctly infer type of struct with the same name as primitive type

src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt
=> CLEAN: Pass stub to `getProcMacroAttributeWithoutResolve`

src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
Now "Create New Issue" action provides additional (disabled by default in stable release) experimental features enabled by user.
changelog: Provide enabled experimental features by `Help | Create New Issue` action which allows opening issue in our [tracker](https://github.com/intellij-rust/intellij-rust/issues/) right from your IDE
=> ACT: Provide experimental features by "Create New Issue" action

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt
Fixes #8172
I can't make a test because the bug is under `if (!isUnitTestMode)` condition
changelog: Fix analysis in `sixtyfps` crate
=> RES: fix exception in name resolution

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Fixes #7464
```rust
trait Trait { type Foo; }
impl<T> Trait for T { type Foo = (); }
enum E {
Foo {},
Bar {}
}
fn main() {
let a = E::Foo {}; // This Foo is a enum variant
if let E::Foo {} = a {} // This Foo is a enum variant
} 
```
```rust
trait Trait { fn Foo(a: i32); }
impl<T> Trait for T { fn Foo(a: i32) {} }
enum E {
Foo(i32),
Bar()
}
fn main() {
let a = E::Foo(1); // This Foo is a enum variant
if let E::Foo(_) = a {} // This Foo is a enum variant
}
```
=> RES: prefer enum variant over associated items

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Fixes #8178
changelog: Fixes resolve of proc macros from [`yew`](https://docs.rs/yew/latest/yew/) crate, such as `yew::html!`
=> RES: Fix identity attribute proc macro on another proc macro definition

build.gradle.kts
They fail because of incompatibility caused by the fix of [IDEA-281472](https://youtrack.jetbrains.com/issue/IDEA-281472)
=> T: temporarily disable some tests on 2021.3 platform

gradle-213.properties
It should prevent `java.lang.NoClassDefFoundError: com/intellij/application/options/IndentOptionsEditorBase` after fix of [IDEA-281472](https://youtrack.jetbrains.com/issue/IDEA-281472)
=> GRD: bump since build for 213 builds

src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/ide/notifications/RsUntrustedNotificationProvider.kt, src/main/kotlin/org/rust/ide/security/RsTrustChangeNotifier.kt, src/main/kotlin/org/rust/ide/security/trustedProjectUtils.kt
Coming versions of IntelliJ IDE (more specifically 2021.2.4 and 2021.3.1) will bring changes in untrusted editor notification.
Now, if a project is opened in safe mode, IDE will show the corresponding editor notification in all files itself. That leads to double editor notification since the plugin shows its own notification as well.
These changes prepare the plugin for platform changes, and now the editor notification about untrusted project will be shown only once. Also, they fix `trust project` action in the notification that doesn't work with stable plugin builds because of changes in the platform (`TrustChangeNotifier` was renamed to `TrustStateListener`)
changelog: Prepare plugin for upcoming changes in untrusted editor notification
=> Fix untrusted notifications in Cargo projects

src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt, src/main/kotlin/org/rust/ide/settings/RsCodeCompletionOptions.kt, src/main/resources/messages/RsBundle.properties
| - | - |
| ![image](https://user-images.githubusercontent.com/2539310/143849368-6e772e55-ec1f-44c7-8b34-1a2b730387f0.png) | ![image](https://user-images.githubusercontent.com/2539310/143849491-490459bf-b10a-4633-9562-bb1bd8ccc0c1.png) |
Also:
- simplify `RsCodeCompletionConfigurable` and `RsAutoImportOptions` using `ConfigurableBuilder` API
- extract user visible strings to message bundle from `RsCodeCompletionConfigurable` and `RsAutoImportOptions
changelog: Fix Rust code completion settings layout
=> UI: fix Rust code completion settings layout

src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt
Just skip `#[async_trait]` proc macro expansion and treat it as some unknown attribute.
Fixes #8053
Fixes #8026
Fixes #8072
Fixes #8181
Fixes #8093
But brings #7863 false-positive again :(
changelog: Do not expand `async_trait` procedural macro if proc macro expansion is enabled. This fixes several issues with `async_trait`.
=> MACRO: add `async_trait` to the list of hardcoded proc macros

src/main/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntention.kt, src/test/kotlin/org/rust/ide/intentions/IntroduceLocalVariableIntentionTest.kt
"Introduce variable" intention (invoked via Alt+Enter) is a lightweight version of "Introduce variable" refactoring (Invoked via Ctrl+Alt+V). Intention is needed for better discoverability of the feature, and is expected to work in fewer places than refactoring (#5637). This PR fixes intention inside simple match arm, so now arm expression is extracted (and not whole match arm)
```rust
fn func() -> i32 {
match f {
true => 1/*caret*/,
false => 0,
}
}
```
cc @neonaot 
changelog: Fix "Introduce variable" intention inside match arm
=> INT: Fix "Introduce variable" intention inside match arm

src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeParser.kt, src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt
=> MACRO: fix expansion of proc macros with a float literal in a body

build.gradle.kts, pretty_printers_tests/src/main.rs
Fixes #8028.
Previously, relative paths were used when adding breakpoints in LLDB (by `breakpoint set --file PATH --line LINE` command), leading to unresolved breakpoints and corresponding "Unable to resolve breakpoint to any actual locations" warnings (only on 213 builds, presumably after LLDB upgrade). Now canonical paths are used instead.
=> T: Fix and enable pretty-printers tests for 213 builds

.github/workflows/check.yml
`cargo install` doesn't respect `Cargo.lock` by default (see https://github.com/rust-lang/cargo/issues/7169). And after `proc-macro2 1.0.33` release, we started to use it to compile `cargo-generate`. And because of combination of "old" nightly that we used on CI and some bug in `proc-macro2 1.0.32` that was fixed in `proc-macro2 1.0.33`, compilation of `cargo-generate` started to fail
I've just added `--lock` flag to respect `Cargo.lock`
=> CI: respect Cargo.lock of installed binaries

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Previously, the plugin showed [E0277](https://doc.rust-lang.org/error-index.html#E0277) even if the type is not fully known (or even unknown at all).
For example,
```rust
trait Foo {}
trait Bar: Foo {}
impl Bar for S {} // <-- `S` is unknown here
```
It contradicts with compiler errors. The compiler produces something like `` error[E0412]: cannot find type `S` in this scope ``. Moreover, it creates quite weird error messages with `?` in type
Now, the plugin checks that all trait bound is implemented only for fully known types.
changelog: Don't produce [E0277](https://doc.rust-lang.org/error-index.html#E0277) errors for non fully-known types
=> ANN: don't produce super trait is not implemented (E0277) for non fully known types

src/main/kotlin/org/rust/ide/utils/SearchByOffset.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Fixes #7104
changelog: Fix [`Extract function`](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractmethod-refactoring) refactoring (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd>) for argument of `println!` macro
=> REF: Fix extract function refactoring for argument of `println!` macro

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/DollarCrateUtil.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Fixes exception
<details>
```
java.lang.IllegalArgumentException: srcOffset should be >= 0; got: -2169
at org.rust.lang.core.macros.MappedTextRange.<init>(RangeMap.kt:100)
at org.rust.lang.core.resolve2.util.DollarCrateHelper.getRangeMap(DollarCrateUtil.kt:91)
at org.rust.lang.core.resolve2.ModCollector.collectProcMacroCall(ModCollector.kt:318)
at org.rust.lang.core.resolve2.ModCollectorBase.collectCustomDeriveProcMacroCall-18vbGDs(ModCollectorBase.kt:272)
at org.rust.lang.core.resolve2.ModCollectorBase.collectElement(ModCollectorBase.kt:76)
at org.rust.lang.core.resolve2.ModCollectorBase.collectElements(ModCollectorBase.kt:52)
at org.rust.lang.core.resolve2.ModCollectorBase.access$collectElements(ModCollectorBase.kt:31)
at org.rust.lang.core.resolve2.ModCollectorBase$Companion.collectMod( …
```
=> RES: Fix handling $crate inside detached files

src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Fixes #8236
The issue occurs when there is an impl for some type and that type also used in an associated type projection in the trait ref:
```rust
impl Trait1<<S as Trait2>::Item> for S {}
//^                     //^
```
In particular, the PR fixes completion of `foo` in this case:
```rust
struct S;
struct X;
trait Trait { type Item; }
impl Trait for S { type Item = X; }
trait Bound<A> {}
impl Bound<<S as Trait>::Item> for S {}
struct Wrap<B>(B);
impl<C, D> Wrap<C> where C: Bound<D> {
fn foo(&self) -> D { todo!() }
}
fn main() {
let a = Wrap(S);
a./*caret*/;
}
```
=> TY: fix #8236

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTuple.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ConvertToSizedTypeFixTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Fixes #6991
Fixes #2530
Previously we had a false positive E0277 in this example:
```rust
struct Foo<T>(T);
impl<T: ?Sized> Foo<T> {
fn foo() -> T where T: Sized { unimplemented!() }
}
```
This fixes 40 false-positives in stdlib and 21 false-positives in tokio
changelog: 1) Fix false positive E0277 `trait bound Sized is not satisfied` 2) Take into account `Sized`/`?Sized` trait bounds during name resolution and completion
=> TY&ANN: Fix false positive E0277 `Sized` is not satisfied

src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/tt/MappedSubtree.kt, src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeParser.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt, testData/test-proc-macros/src/lib.rs
This fixes the expansion of `yew::html` macro.
Fixes #7049
=> MACRO: fix expansion of proc macros that weirdly mix token spans

debugger/src/main/kotlin/org/rust/debugger/lang/RsDebuggerEditorsExtension.kt, src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/main/kotlin/org/rust/lang/core/psi/RsCodeFragment.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/psi/RsCodeFragmentCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/psi/RsDebuggerExpressionCodeFragmentCompletionTest.kt, src/test/kotlin/org/rust/lang/core/psi/RsExpressionCodeFragmentCompletionTest.kt
Fixes #8067.
* Introduce `RsDebuggerExpressionCodeFragment` for debugger code fragments used in Evaluate Expression and LLDB/GDB Console. Previously, more generic `RsExpressionCodeFragment` was used instead
* Do not filter out private items when completing code in the debugger
* Do not annotate usages of private items as errors in the debugger
* Add tests to check that private items are suggested in debugger code fragments completion
changelog: Suggest private items when completing code in the debugger
=> DBG: Suggest private items when completing code in the debugger

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt, src/main/kotlin/org/rust/lang/core/types/Substitution.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
changelog: Take into account const generics defaults in const evaluation
=> TY: Take into account const generics defaults in const evaluation

src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt
Fixes #8238
`sqlx` macros write files to `target/sqlx` directory by a relative path. It expects that PWD is set to the directory with `target` (and `Cargo.toml`) file. In this PR I hotfixed it by setting `CARGO_TARGET_DIR` env var. I also set PWD to a temporary directory (it's not currently possible to set PWD to different directories for different proc macros, this required changes in rust-analyzer).
changelog: Fix expansion of `sqlx` procedural macros with `offline` feature
=> Fix `sqlx` macro expansion: set working directory for proc macro expander process

.github/dependabot.yml, native-helper/Cargo.lock, native-helper/Cargo.toml
We should update ra_ap_proc_macro_srv in order to fix macro expansion on nightly Rust.
But the fix is not yet published on crates.io, so let's temporarily switch to a version from github.
```toml
[dependencies.ra_ap_proc_macro_srv]
git = "https://github.com/rust-analyzer/rust-analyzer"
package = "proc_macro_srv"
rev = "791722b70ad08641a48f96faedffdda6d2880366"
```
I also temporary disabled Dependabot
Fixes #8270
changelog: Fix proc macro expansion on Rust nightly
=> Update ra_ap_proc_macro_srv - use a version from github

src/main/kotlin/org/rust/ide/refactoring/introduceVariable/impl.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt
Closes #8229 
Previously refactoring didn't consider whether the extracted subexpression of a closure is also used somewhere outside of the closure. This lead to the binding created within the scope of the closure, while the occurrences were replaced regardless of the scope. We move the binding inside of the closure body only if all extracted expressions are within its scope.
changelog: "Introduce local variable" no longer moves the new binding into closure bodies if it is used outside of them
=> REF: fix Extract Variable interaction with closures

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
Related: #8284
Now only `std`, `core` and `alloc` crates are always included in auto-import. Other stdlib crates such as `proc_macro`, `test`, `unwind` are included in auto-import only if there is explicit `extern crate` for them. Note that proc-macro crates has explicit dependency on `proc_macro`, so it is also always included in auto-import.
changelog: Don't show auto-import from auxiliary stdlib crates such as `unwind`
=> INSP: Don't show auto-import from auxiliary stdlib crates such as unwind

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt
changelog: Fix auto-import from `alloc` crate when using [`#![no_std]`](https://docs.rust-embedded.org/book/intro/no-std.html)
=> RES: Add `extern crate alloc;` in auto-import if needed

src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8296.
Relates to https://github.com/intellij-rust/intellij-rust/pull/5354.
changelog: Fix default parameters handling in `Wrong number of type arguments` inspection
=> INSP: Fix default parameters handling in `Wrong number of type arguments` inspection

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Fixes #8224
changelog: Fix type inference if dependencies have names as stdlib crates
=> TY: fix type inference if dependencies have names as stdlib crates

coverage/src/main/kotlin/org/rust/coverage/LcovCoverageReport.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/util/ToolchainUtil.kt, src/main/kotlin/org/rust/lang/core/CompilerFeature.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/RustcVersion.kt, src/test/kotlin/org/rust/cargo/runconfig/CargoTestRunStateTest.kt, src/test/kotlin/org/rust/cargo/toolchain/RustcVersionParsingTest.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/stubs/RsLazyBlockStubCreationTestBase.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CustomTargetCfgResolveTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7896.
changelog: Fix `Run with Coverage` for projects located on WSL file system
=> RUN: Fix Coverage runner for projects located on WSL file system

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/test/kotlin/org/rustSlowTests/ide/actions/RsBuildActionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7548.
Fixes https://github.com/intellij-rust/intellij-rust/issues/7723.
changelog: Don't hang on build when an incorrect path is used with `Redirect Input from` option
=> RUN: Don't use `Redirect Input from` when building

src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/test/kotlin/org/rust/NewResolve.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/RustcVersion.kt, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt, src/test/kotlin/org/rust/ide/formatter/RsFormatterTestBase.kt, src/test/kotlin/org/rust/utils.kt, src/test/kotlin/org/rustSlowTests/RsUnusedImportWithToolchainInspectionTest.kt
Now `serde` macros `Serialise` and `Deserialize` are expanded with proc macro expander and not hardcoded. This allows to support usages of imports in serde string attributes like [`#[serde(default = "path")]`](https://serde.rs/field-attrs.html#default--path)
```rust
#[derive(serde::Deserialize)]
struct Foo {
#[serde(default = "func")]
field: i32,
}
```
For now, usages are searched in the current mod only
Meta issue: #2158
changelog: Support usages in `serde` string attributes like [`#[serde(default = "path")]`](https://serde.rs/field-attrs.html#default--path) in unused imports inspection
=> Unused imports inspection: support usages in serde attribute strings

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt, src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt, src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt
Fixes #8212
changelog: Fix resolve of imports inside detached files
=> RES: Use 2018 edition for detached files

src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt, src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Fixes #8162
changelog: Fix `Invert if condition` intention when there is `return`/`continue` without semicolon
=> INT: Fix "Invert if condition" when `return`/`continue` has no semicolon

src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/match/RsNonExhaustiveMatchInspectionTest.kt
...without any wildcard arm, as it doesn't have any effect:
The changelog sentence will be a mouthful :D
changelog: Do not offer the `Add remaining patterns fix` when pattern matching on an enum marked with `#[non_exhaustive]` if there are no wildcard arms in the `match` expression.
=> Do not offer `Add remaining patterns` fix when matching a non exhaustive enum

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
These changes update:
- gradle to 7.3.2
- `org.jetbrains.intellij` to 1.3.0
- kotlin plugin to `1.6.10`. In addition to this change, kotlin language version was updated to 1.6 and API version to 1.5. So now we can use new language features from [Kotlin 1.6](https://kotlinlang.org/docs/whatsnew16.html) and all API added in Kotlin 1.5
changelog: Update Kotlin language version to 1.6 and API version to 1.5. So now we can use new language features from [Kotlin 1.6](https://kotlinlang.org/docs/whatsnew16.html) and all API added in Kotlin 1.5
=> GRD: update gradle and gradle plugins

build.gradle.kts, src/main/kotlin/org/rust/RsProjectTaskQueueService.kt, src/main/kotlin/org/rust/lang/core/crate/Crate.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAttrProcMacroOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFieldDecl.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPathReferenceElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsReferenceElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt, src/main/kotlin/org/rust/lang/core/stubs/common/PsiOrStubInterfaces.kt
Since [kotlin 1.4-M3](https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/) it's possible to apply `@JvmDefault` behavior to all default methods using `-Xjvm-default=all` compiler option.
Now all default methods are "JVM default" methods
changelog: Always generate Java-compatible byte code for interface methods with default implementation without `@JvmDefault` annotation
=> GRD: use `-Xjvm-default=all` and get rid of `@JvmDefault`

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt
changelog: Expand proc macros from `dev-dependencies`. Note, procedural macro expansion is still under development, and it's disabled by default for now. To turn it on, enable `org.rust.cargo.evaluate.build.scripts` and `org.rust.macros.proc` [experimental features](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)
=> MACRO: expand proc macros from [dev-dependencies]

src/main/kotlin/org/rust/ide/inspections/fixes/RenameFix.kt, src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt, src/main/kotlin/org/rust/openapiext/utils.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsModuleNamingInspectionTest.kt
Fixes #8120
changelog: Fix renaming mod declaration by "Module naming convention" inspection
=> INSP: Fix renaming mod declaration by "Module naming convention"

src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
This PR does not enable proc macro expansion in doctests, but it does some preparations for it
=> MACRO: prepare for attribute/derive macro expansion in doctests

src/main/kotlin/org/rust/ide/refactoring/generate/StructMember.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7739
See https://github.com/intellij-rust/intellij-rust/issues/7739#issuecomment-915375161.
changelog: Handle qualified field paths correctly in `Generate constructor` refactoring.
=> REF: support qualified paths in Generate Constructor refactoring

src/main/kotlin/org/rust/ide/inspections/RsConstReferStaticInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsConstReferStatic.html, src/test/kotlin/org/rust/ide/inspections/RsConstReferStaticInspectionTest.kt
This PR aims to implement an inspection for rust error [E0013](https://doc.rust-lang.org/error-index.html#E0013) *A const variable cannot refer to a static variable.*
Covering the following [const contexts](https://doc.rust-lang.org/reference/const_eval.html#const-context):
Part of #886
=> INSP: Constants cannot refer to statics. (E0013)

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsPartialMacroArgumentCompletionTest.kt
Since auto-import is "blazing fast", we can allow completing out-of-scope items at an empty position.
This is effectively a list of all importable names in the project
https://user-images.githubusercontent.com/3221931/147351567-90b82234-ada5-4ff4-8cad-a78cded4e76d.mp4
=> COMP: Allow completing out of scope items at empty path

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsTupleFieldCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
An improvement to #3664
Take into account the fact that some types can be implicitly coerced to a different type.
```rust
struct X;
fn foo1() -> &X {}
fn foo2() -> &i32 {}
fn foo3() -> &mut X {}
fn foo4() -> &&X {}
fn bar() {
accept(foo/*caret*/) // Completion variant should be sorted as `foo1`, `foo3`, `foo4`, `foo2` 
}                        // because `&mut X` and `&&X` are coercable to `&X`
fn accept(_: &X) {}
```
changelog: Take into account expected expression type coercability in completion sorting
=> COMP: Take into account expected expression type coercability in completion sorting

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
```rust
fn main() {
foo::func();
}
```
When there is multiply auto-import variants for `foo`, we will sort first variants for which `foo::func` become resolved.
changelog: Improve sorting of auto-import variants
=> INSP: Sort resolved paths first in auto-import

src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RsInlineValueTest.kt
Turns out that I have missed a few cases that require parentheses in `RsInlineValueProcessor`.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8267
changelog: Correctly parenthesize block-like expressions (e.g. `match`) in Inline Value refactoring.
=> INT: correctly parenthesize block-like expressions in Inline Value refactoring

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
The bug was introduced in #8167. When some IDEA project is marked as trusted, `cargo refresh` action is performed in all other opened projects. This also lead to flaky tests
https://user-images.githubusercontent.com/3221931/147363985-9ea94a7a-6449-4f96-bdeb-4a17d1f84124.mp4
=> Don't perform cargo refresh when another IDE project become trusted

src/main/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntention.kt, src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntentionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8258
changelog: Infer generic parameter types in Convert closure to function intention.
=> INT: infer generic parameter types in ConvertClosureToFunctionIntention

src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Consider a case when we want a completion for `Rc::`, but `Rc` is not imported:
```rust
fn main() {
let a = Rc::/*caret*/
}
```
With this PR, the plugin will show
completion for all possible `Rc` that can be imported.
After selecting a variant, the import will be inserted:
```rust
use std::rc::Rc;
fn main() {
let a = Rc::new()
}
```
https://user-images.githubusercontent.com/3221931/146943940-82765d30-7855-4987-bbd2-17d3f8d9b3a7.mp4
=> COMP: complete 2nd path segment if the first segment is unresolved but can be imported

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveCommonProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Fixes #7884
changelog: Support indirect self-references in [`Move` refactoring](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#move-refactoring) (`Refactor | Move` or <kbd>F6</kbd>)
=> REF: Support indirect self-references in move refactoring

src/main/kotlin/org/rust/lang/core/CompilerFeatures.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
As a result, the plugin takes into account new state compiler features stabilized recently like `format_args_capture `
Fixes #8341
changelog: Do not produce a false-positive error about missing format macro arguments without `format_args_capture` feature starting with 1.58
=> Update compiler features

.github/dependabot.yml
changelog: Set up [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically) to update gradle dependencies automatically
=> CI: set up dependabot for gradle dependencies

src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
In addition to #6013, now most of the inspections are disabled in cfg-disabled files
=> Do not run inspections on cfg-disabled files

src/main/kotlin/org/rust/cargo/toolchain/impl/BuildMessages.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/RsProcMacroExpansionResolveIntegrationTest.kt
Previously, the plugin didn't parse compiler messages if a build script evaluation process returned a non-zero error code.
As a result, if the workspace host code couldn't be compiled (for example, because of a broken build script) or executed (for example, because of panic in build script), the plugin stopped processing any generated by build scripts item and expanding any proc macro call.
Now, if a proc macro lib is successfully compiled or a library's build script is successfully executed during build script evaluation (even if build script evaluation fails eventually), the plugin will process generated items and expand proc macros call from such libraries
changelog: Process available items generated by build script and expand available procedural macro calls even if the whole project …
=> CARGO: parse available compiler messages even if build script evaluation fails

src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
```rust
mod foo {
fn foo() {}
}
mod foo {
fn bar() {}
}
fn main () {
foo::bar();
}
```
Previsouly: 
Now:
The error about multiresolved `foo` should be reported by another inspection (it's not implemented yet)
=> Suppress `Unresolved reference` inspection if the path qualifier is multiresolved

src/main/kotlin/org/rust/ide/status/RsExternalLinterWidget.kt, src/main/resources/META-INF/rust-core.xml
Fixes some minor issues introduced in #8018
Previously, there were two issues:
- when a project didn't have attached cargo projects at the project opening (including new project creation case), the widget wasn't shown
- after detaching all cargo projects the widget was still shown, although it didn't make sense
Now the plugin updates widget on changes in cargo project set
=> Update External Linter widget properly

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/HangingModData.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveInsideFunctionsTest.kt
Fixes #8394
changelog: Fix expansion of `pin_project_lite::pin_project` macro inside function bodies
=> RES: Fix resolve of macros inside functions using new resolve

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyPrimitive.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Previously, `str::trim` was unresolved in this example:
```rust
mod str {
pub fn foo() {}
}
fn main () {
str::foo();
str::trim("123");
}
```
Now it is resolved to a method in impl for `str`. `str` segment in `str::trim` path is still resolved to `mod str`, unfortunately :(
=> RES: fix primitive vs mod

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Fixes #8107
changelog: Fix "Find usages" when usage is in module with relative path attribute
=> Fix "Find usages" for modules with relative path attribute

src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt
I'm not sure that it's proper IDE behavior but it won't be fixed in 212 and 213, let's try to avoid it from the plugin side
Fixes #8371
changelog: Fix `IllegalStateException` during new project creation after dynamic plugin loading
=> Fix `IllegalStateException` during new project creation after dynamic plugin loading

src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsPatFixTest.kt
Fixes #8370
changelog: Make `Add missing fields` quick-fix work properly with raw identifiers
=> ANN: Make `Add missing fields` quick-fix work properly with raw identifiers

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
For example,
```toml
[dependencies]
serde_derive = "*"
```
```rust
use serde_derive::{self};
```
previously, this `self` was considered unresolved:
=> RES: resolve `self` in `use proc_macro_crate::{self}`

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
As a result, the plugin now knows the proper type of `addr_of!` and `addr_of_mut!` macro calls from stdlib
Fixes #8405
changelog: Infer type of `&raw const` and `&raw mut` [operators](https://rust-lang.github.io/rfcs/2582-raw-reference-mir-operator.html). As a result, the plugin now knows the proper type of `addr_of!` and `addr_of_mut!` macro calls from stdlib
=> TY: infer type of `&raw const` and `&raw mut` operators

src/main/kotlin/org/rust/ide/intentions/AddImportIntention.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt
Removes use of `ImportCandidate` class in `AddImportIntention`. This is needed for removing the old auto-import code which we will do soon
=> Remove use of old auto-import code in AddImportIntention

src/main/kotlin/org/rust/cargo/project/model/RsTestSourcesFilter.kt, src/main/resources/META-INF/rust-core.xml
| - | - |
| ![image](https://user-images.githubusercontent.com/3221931/150124870-8eedd9a3-6bcc-4e72-82e1-80f63b78b7e7.png) | ![image](https://user-images.githubusercontent.com/3221931/150124642-ccffe895-cb38-40e8-9637-3965bfc5b554.png) |
| ![image](https://user-images.githubusercontent.com/3221931/150124970-ca218d33-05ec-4eb9-a91a-d0d824ea36cb.png) | ![image](https://user-images.githubusercontent.com/3221931/150124659-028e4fb6-7cc8-4cba-94b2-14510494389f.png) |
changelog: Mark usages in [doctests](https://doc.rust-lang.org/rustdoc/documentation-tests.html) as "Test usages"
=> Mark usages in doctests as "Test usages"

src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspection.kt, src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveGenericArguments.kt, src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsNumberInspectionTest.kt, src/test/kotlin/org/rust/ide/intentions/AddImplTraitIntentionTest.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/8144 and https://github.com/intellij-rust/intellij-rust/pull/8145.
changelog: Take into account const generics in `Wrong generic arguments number` inspection and corresponding quick fixes
=> INSP&ACT: Take into account const generics in `Wrong generic arguments number` inspection and corresponding quick fixes

scripts/check_release_branch_date.py
i.e. usually on Monday morning.
It should help QA to make test planning more precise
changelog: Create a release branch one day earlier, i.e. usually on Monday morning one week before release
=> CI: create release branch one day earlier

src/main/kotlin/org/rust/ide/refactoring/extractEnumVariant/RsExtractEnumVariantProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/extractStructFields/RsExtractStructFieldsProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/introduceConstant/RsIntroduceConstantHandler.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractTraitTest.kt
Consider there was method in `impl Struct` which after refactoring was extracted to `trait Trait`. Then we need to add an import for `Trait` to modules that use the method.
Meta issue: #8326
changelog: Fix adding trait imports for usages in "Extract Trait" refactoring
=> REF: Fix adding trait imports for usages in "Extract Trait" refactoring

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/inspections/RsDetachedFileInspectionTest.kt
Fixes #8445
changelog: Properly add new module declaration by `Attach file to module` quick-fix if a new module has a keyword-like name
=> ANN: escape module name if needed in `Attach to module` quick-fix

debugger/src/main/kotlin/org/rust/debugger/RsDebuggerDriverConfigurationProviderImpl.kt, debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerGeneralSettingsConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt, debugger/src/main/resources/META-INF/debugger-only.xml, plugin/src/main/resources/META-INF/plugin.xml
Part of #5422
Previous attempt: #6907
Fixes #7201
After #6907, Rider for Unreal Engine has changed the inner structure of plugins related to native debugging. Previously, it contained bundled [Native Debugging Support](https://plugins.jetbrains.com/plugin/12775-native-debugging-support) plugin with bundled debugger binaries. Now, it contains the same plugin `com.intellij.cidr.debugger` as CLion (that's why it didn't work with initial implementation), so we don't need to invent a way how to determine if IDE contains bundled debugger binaries and we can just use `LLDBDriverConfiguration.hasBundledLLDB()`
Current restrictions:
- only [Rider for Unreal Engine](https://www.jetbrains.com/lp/rider-unreal/) is supported for now
- only LLDB
changelog: Provide debugging in [Rider for Unreal …
=> DBG: second attempt to support debugging in Rider for Unreal Engine

.github/workflows/rust-release.yml
It's needed to build all necessary builds (212 and 213) for 164 release
=> Temporarily return 212 builds to release workflow

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/runconfig/RsCapturingProcessHandler.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt, src/main/kotlin/org/rust/ide/actions/RsCreateCrateAction.kt, src/main/kotlin/org/rust/ide/actions/RustfmtCargoProjectAction.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/main/kotlin/org/rust/ide/formatter/RustfmtFormattingService.kt, src/main/kotlin/org/rust/ide/module/RsModuleBuilder.kt, src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt, src/main/kotlin/org/rust/ide/newProject/Utils.kt, src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt, src/main/kotlin/org/rust/openapiext/CommandLineExt.kt, src/main/kotlin/org/rust/openapiext/RsProcessResult.kt, src/main/kotlin/org/rust/stdext/RsResult.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoProjectGenerationTest.kt
Use `RsResult<ProcessOutput, RsProcessExecutionException>` instead of `@Throws(ExecutionException::class)`
=> Refactor process running code: use RsResult instead of exceptions

src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsBacktraceFilterTest.kt, src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/highlight/RsHighlightExitPointsHandlerFactoryTest.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsGenericParameterInfoHandlerTest.kt, src/test/kotlin/org/rust/ide/inspections/RsExperimentalChecksInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt, src/test/kotlin/org/rust/ide/intentions/IfLetToMatchIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/SplitIfIntentionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsCfgAttrResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
An example of warning: `Name contains characters which can cause problems on Windows`
=> T: fix test names that cause compilation warnings

native-helper/Cargo.lock, native-helper/Cargo.toml, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt, src/main/kotlin/org/rust/lang/core/macros/proc/Request.kt
This update consists of https://github.com/rust-analyzer/rust-analyzer/pull/11365, https://github.com/rust-analyzer/rust-analyzer/pull/11353 and https://github.com/rust-analyzer/rust-analyzer/pull/11356 PRs
Fixes #7709
Fixes #8238 in a proper way (#8271 was a hacky hotfix)
changelog: Don't fill up disk space by proc macro DLLs on Windows
=> Update `ra_ap_proc_macro_srv` to `0.0.94`, fix disk usage, fix pwd

src/main/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
The bug:
changelog: don't highlight format templates in cfg-disabled code
=> ANN: don't highlight format templates in cfg-disabled code

src/main/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsDocHighlightingAnnotatorTest.kt
The bug:
changelog: don't highlight documentation elements in cfg-disabled code
=> ANN: don't highlight documentation elements in cfg-disabled code

toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt, toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/6856#issuecomment-826134752
I guess we can close that issue with this fix.
changelog: Provide correct URLs for `Cargo.toml` dependencies with quoted names
=> TOML: Fix doc urls for quoted dependencies names

src/main/kotlin/org/rust/ide/refactoring/generate/getter/GenerateGetterHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/setter/GenerateSetterHandler.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateSetterActionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8354
changelog: Handle qualified field paths correctly in `Generate getter/setter` (`Code | Generate | Getter/Setter`) refactoring.
=> REF: support fields with qualified type paths in Generate getter/setter

src/main/kotlin/org/rust/ide/inspections/RsSelfConventionInspection.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/inspections/RsSelfConventionInspectionTest.kt
I fixed the corresponding issue, but it seems to me that explicit `Self` types should be better supported by type inference. For example here:
```rust
struct Foo;
impl Foo {
fn is_awesome(self: &mut Self) {}
}
fn main() {
let foo = Foo;
foo.is_awesome();
}
```
`foo.is_awesome()` is not underline as not being mutable, so probably `self: &mut Self` is not treated in the same way as `&mut self`.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8352
changelog: Support artbitrary and explicit self types in `Self convention inspection`.
=> INSP: handle arbitrary and explicit self parameter in RsSelfConventionInspection

src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt, src/main/kotlin/org/rust/openapiext/RsProcessResult.kt, src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeJsonTest.kt
The main reason is to make errors uniform with #8494. Also, we moving towards ridding of Gson. Also, Jackson should have a better performance, but this is not measured and this is not the goal in this case.
=> Use jackson (instead of Gson) for Cargo metadata deserialization

src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateSetterActionTest.kt
The generate getter, setter and constructor refactorings can be invoked on two places: ADT or an impl block. If invoked on an impl block, the generated item(s) will be created in that impl item, but if they are invoked on an ADT, a new impl block is always created.
Even though it might be difficult to always exactly find all impl blocks (e.g. blocks in another file/module, block containing complex generics), I think that in the most simple case this should be a bit smarter and try to find a "near" impl block.
Maybe also the generate constructor refactoring shouldn't be available if it finds a "near" impl block that already contains a `new` function?
changelog: The Generate getter/setter/constructor refactoring actions will now try to use existing impl blocks instead of creating a new one. …
=> REF: try to find existing impl in Generate refactoring in simple cases

src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt, src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
changelog: Fix an exception in `Un-elide lifetimes` intention while processing nested ADTs
=> ACT: Fix an exception in `Un-elide lifetimes` intention while processing nested ADTs

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/main/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFix.kt, src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6529.
Also, now the plugin suggests only [machine-applicable](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/enum.Applicability.html) quick fixes when External Linter inspection runs in batch mode.
changelog: Don't suggest multi-part quick fixes from External Linter
=> ANN: Don't suggest multi-part quick fixes from External Linter

src/main/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongGenericArgumentsOrderInspectionTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/pull/8144.
Closes https://github.com/intellij-rust/intellij-rust/issues/8306.
Note: in some cases, this inspection produces more errors, than the corresponding lint in rustc. For example:
```rust
struct S<'a, T>(&'a T);
impl<'a, T> S<T, 'a> {}
```
For the code above the plugin reports two errors:
```
struct S<'a, T>(&'a T);
impl<'a, T> S<T, 'a> {}
^   ^
|   | _ _ Lifetime provided when a type was expected
|
| _ _ _ _ Type provided when a lifetime was expected
```
But rustc reports only the first error.
changelog: Support lifetimes in `Wrong generic arguments order` inspection
=> ANN: Support lifetimes in `Wrong generic arguments order` inspection

src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt
Auto-import options (`Settings | Editor | General | Auto Import`) doesn't work in 2022.1.
Thanks @neonaot for finding this.
The fix is to replace deprecated `UiDslConfigurable` with `UiDslUnnamedConfigurable`.
changelog: Fix auto-import options for 2022.1 platform
=> Fix auto-import options for 2022.1

ml-completion/src/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt, src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsBoolCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsFragmentSpecifierCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsLookupElement.kt, src/main/kotlin/org/rust/lang/core/completion/RsPrimitiveTypeCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsReprCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsTupleFieldCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsVisRestrictionCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsVisibilityCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/lint/RsLintCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/sort/RsCompletionWeigher.kt, src/main/kotlin/org/rust/lang/core/completion/sort/RsCompletionWeighers.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
This PR changes nothing for the end-user (i.e. the new sorting should work exactly like the old one).
For us, this tidies up completion variants sorting. Please read docs for `RS_COMPLETION_WEIGHERS`
=> Refactor completion variants sorting: use weighers

ml-completion/src/main/kotlin/org/rust/ml/RsCompletionFeaturesPolicy.kt, ml-completion/src/main/kotlin/org/rust/ml/RsContextFeatureProvider.kt, ml-completion/src/main/kotlin/org/rust/ml/RsElementFeatureProvider.kt, ml-completion/src/main/resources/META-INF/ml-completion-only.xml, ml-completion/src/test/kotlin/org/rust/ml/RsElementFeatureProviderTest.kt, src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt, src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/completion/RsLookupElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsExpr.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt
Related to #6411
New element features:
- IS_OPERATOR_METHOD
- IS_BLANKET_IMPL_MEMBER
- IS_UNSAFE_FN
- IS_ASYNC_FN
- IS_CONST_FN_OR_CONST
- IS_EXTERN_FN
New context features:
- IS_UNSAFE_CONTEXT
- IS_ASYNC_CONTEXT
- IS_CONST_CONTEXT
=> #6411: Provide context features and more element features for ML-completion

src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
`LiftShorterItemsClassifier` aka "liftShorter" is a completion variants sorter ("classifier") that does a text-based sorting that is hard to explain in words. Let's look at the picture:  
Here grayed variants should have been at the end of the list, but they were upped by liftShorter. Why? Well, because they are prefixes of their previous variants! For example, `is_equal` is a prefix of `is_equal_private`, so `is_equal` variant is placed after `is_equal_private`. Why? Well, I heard that it helps in Java: "liftShorter" places interfaces near their implementations, e.g. places an interface `Foo` after `FooImpl` if `FooImpl` is prioritized for some reason. Why does liftShorter work in all languages by default? I have no idea. We decided to disable liftShorter in Rust because we can't find …
=> Disable "liftShorter" completion classifier on 221 platform

src/main/kotlin/org/rust/ide/refactoring/generate/constructor/GenerateConstructorHandler.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
I find it to be more idiomatic. Rust analyzer also follows this convention.
And finally, it solves the constructor qualified path problem (https://github.com/intellij-rust/intellij-rust/pull/8357#issuecomment-1028145343) :D I'll send another PR that fixes it for getter/setter and constructor parameters.
changelog: Use `Self` when generating constructor in the `Generate Constructor` refactoring action.
=> Use `Self` for constructor expression in `GenerateConstructor` action

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsLocalDebugProcess.kt
In IDEA 221 in CidrDebugProcess there will be a filtering functionality for frames with unavailble sources. See https://youtrack.jetbrains.com/issue/CPP-28132
For Rust this approach introduces some not very usefull button since library sources are availble.
Just in case: 
- review  https://jetbrains.team/p/ij/reviews/19787/timeline 
- commit: https://jetbrains.team/p/ij/repositories/intellij/revision/43d15360d0e679b741d241455bd8560fb99b2308
=> DBG: Hide filtering button

debugger/src/213/main/resources/META-INF/platform-native-debug-only.xml, debugger/src/221/main/resources/META-INF/platform-native-debug-only.xml, debugger/src/main/resources/META-INF/native-debug-only.xml
It was introduced as workaround for https://github.com/intellij-rust/intellij-rust/issues/8122
Now, it's fixed in 221 platform so we don't need this workaround anymore
=> GRD: drop default `languageSupport` extension for 221

clion/src/213/main/resources/META-INF/platform-clion-only.xml, clion/src/221/main/kotlin/org/rust/clion/statistics/CargoProjectModelTypeProvider.kt, clion/src/221/main/resources/META-INF/platform-clion-only.xml, clion/src/main/resources/META-INF/clion-only.xml
Note, the statistics are collected only if you [explicitly allow](https://www.jetbrains.com/help/idea/settings-usage-statistics.html) it
=> CPP-28240: provide statistics about Cargo project model in CLion projects in 2022.1

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/ui.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/6633.
changelog: Render generic parameters for associated types in `Implement Members`
=> REF: Render generic parameters for associated types in `Implement Members`

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8575.
Relates to https://github.com/intellij-rust/intellij-rust/pull/8436.
changelog: Don't suggest multi-span quick fixes from External Linter
=> ANN: Don't suggest multi-span quick fixes from External Linter

src/main/kotlin/org/rust/ide/module/CargoConfigurationWizardStep.kt
It's a temporary workaround. The proper solution should be done as part of https://github.com/intellij-rust/intellij-rust/issues/8585
| - | - |
| <img width="889" alt="Screen Shot 2022-02-21 at 15 58 18" src="https://user-images.githubusercontent.com/2539310/154959839-c43eb073-2a8d-46d0-b206-ad9d62cde61b.png"> | <img width="890" alt="Screen Shot 2022-02-21 at 15 55 52" src="https://user-images.githubusercontent.com/2539310/154959488-26d3712a-5ca6-4451-b6ae-cd8edfa08d41.png"> |
Fixes #8508
changelog: Fix wrong indents in UI during creation of a new Rust project in IDEA
=> UI: fix wrong indents in new project panel with new project wizard

src/main/kotlin/org/rust/ide/typing/paste/JsonStructParser.kt, src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
This PR adds a copy paste processor that tries to convert pasted JSON-like text to a Rust struct (according to the `serde` data model). Currently it does not actually implement any `serde` things on the struct to keep this PR simpler (but it's easy to add `Serialize/Deserialize` derive to the struct using existing intentions and completion).
It currently works like this:
Improvements (possibly for follow-up PRs):
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7783
changelog: You can now paste JSON objects into Rust files and convert them to a Rust struct.
=> IDE: convert JSON object to Rust struct after paste

src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
We add a dummy CFG edge from the discriminant of the match to its output in this case, since adding a match arm with basically any return type would make the above CFG path possible. This avoids spurious "unreachable expr/stmt" warnings when the user types a new match block.
If the user adds at least one explicit arm, then the dataflow will be analysed properly (it's possible to add first a noreturn arm, while the other arms would be expected to return a value, but this is an easily understandable rare edge case which I don't think requires any special treatment).
The only case when a match with no arms is valid and indeed signifies unreachability is when the discriminant has the type with no values (e.g. ! or `enum Foo {}`), but this case can only be properly handled after type …
=> INSP: remove spurious unreachable warnings for match exprs with no arms

src/main/kotlin/org/rust/cargo/runconfig/command/CargoExecutableRunConfigurationProducer.kt, src/main/kotlin/org/rust/debugger/runconfig/RsDebugAdvertisingRunner.kt, src/main/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFix.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoExecutableRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsLineMarkerProviderTestBase.kt, toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt
Also:
- introduce a proper API to check if the function is `main` one. Use it in `AddUnsafeFix` to support all cases and not to depend on `org.rust.cargo.runconfig` package
- don't show run line marker for `main` function in file with `no_main` attribute
Improvement of #8571
changelog: Don't show run line marker for `main` function in file with [`no_main`](https://doc.rust-lang.org/reference/crates-and-source-files.html#the-no_main-attribute) attribute
=> ANN: don't suggest adding `unsafe` to main function in build scripts

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskProvider.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/2165#issuecomment-922349293.
changelog: Correctly handle `+toolchain` at the beginning of Cargo command line
=> RUN: Correctly handle `+toolchain` in Cargo command configuration

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
changelog: Add `--respect-source-config` to `cargo vendor` command  to respect `[source]` config in `.cargo/config`.
This fixes the problem when using another source of cargo registry but still stuck in 'updating crates.io index'
=> add --respect-source-config to Cargo vendor

build.gradle.kts, gradle-221.properties
Note, since 221.4906, CLion has bundled TOML plugin so we don't need to download TOML plugin from Marketplace anymore
=> GRD: update 2022.1 IDE dependencies

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
Previously, the plugin filtered out only constants and const parameters but did nothing with other elements from values namespace
Fixes #8635
Closes #8638
changelog: Improve ambiguity resolution for type parameters between types and values with same names
=> RES: improve ambiguity resolution for type parameters between types and values with same names

src/main/kotlin/org/rust/ide/presentation/PresentationInfo.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/6633.
changelog: Render generic parameters for type aliases / associated types in UI
=> UI: Render generic parameters for assoc types if any

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustup.kt, src/main/kotlin/org/rust/cargo/util/TestUnitTestRustcCacheService.kt, src/main/kotlin/org/rust/cargo/util/UnitTestRustcCacheService.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoTest.kt
Previously, the plugin used a toolchain related to stdlib source directory to get info about stdlib (dependencies, edition, etc.). And usually, it's a default toolchain from `rustup` point of view.
But if a user [overrides](https://rust-lang.github.io/rustup/overrides.html) toolchain for the project, the plugin didn't use it for stdlib that sometimes produced errors like https://github.com/intellij-rust/intellij-rust/issues/8517
Now, the plugin retrieves the actual toolchain name (from `rustup` point of view) and passes it to all commands used to get stdlib info
Fixes #8517
changelog: Use the project toolchain to retrieve info about stdlib. Previously, the plugin used the default toolchain for it that sometimes produced errors
=> CARGO: use the same project toolchain to get info about stdlib as project uses

src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties
Improvement of https://github.com/intellij-rust/intellij-rust/pull/7816.
I couldn't find any documentation for the AdvancedSettings and didn't even find many usage examples, so I'm not sure if I'm using it properly. But mainly I don't know how to recognize the situation when the setting wasn't set yet - do we really have to use a tri-state enum for this? I would expect that there would be some API that would give me "unset"/"set true"/"set false".
=> IDE: add Don't ask again option to JSON to Rust conversion

src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitAction.kt
changelog: Fix that "Extract trait" refactoring can be offered in non-Rust files
=> REF: Offer "Extract trait" refactoring only in Rust files

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/inlineFunction/ui.kt
Fixes #8257
Fixes #8249
Meta: #5511
Inline function dialog has three options:
1. Inline all  + remove function
2. Inline all  + keep function
3. Inline this + keep function
Now it works as follows:
* If there is one usage, we don't show option (2)
* If the function is recursive, only option (3) is available
* If the function is read-only, only options (2) and (3) are available
changelog: 1. Fix handling of recursive functions in "Inline function" refactoring 2. Fix "Inline function" refactoring for single occurence
=> REF: Fix inline function dialog

src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsVisibility.kt, src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractSuperTraitTest.kt, src/test/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitFromImplTest.kt
Fixes #8468
changelog: Fix visibility of created trait in "Extract trait" refactoring
=> REF: Create public trait if needed in "Extract trait" refactoring

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt
This change should fix exception on 221 platform
Fixes #8602
changelog: Fix exception during Cargo tool window initialization on 2022.1 platform
=> Do not initialize Cargo tool window too early

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Previously, the plugin didn't build example and bench targets. But if a crate didn't contain any lib, bin or test target, build scripts were not built and run at all and as a result - the plugin didn't know about generated items
Now, the plugin compiles all targets (i.e. passes `--all-targets` flag)
Fixes #8620
changelog: Properly evaluate build scripts even if a crate doesn't contain binary or library targets. Note, build script evaluation is disabled by default. To turn it on, enable `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features)
=> CARGO: build all targets during build script evaluation

toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceImpl.kt
Fixes parsing errors happening during crates local index update because of created `.github/` dir in [crates.io-index](https://github.com/rust-lang/crates.io-index) repository.
This PR adds a condition to skip all the paths starting with dots.
changelog: Fix parsing errors when updating crates local index
=> CARGO: Ignore parsing for directories starting with dot

gradle.properties
changelog: Make 2022.1 platform default for development
=> GRD: make 2022.1 platform default for development

src/main/kotlin/org/rust/ide/refactoring/generate/constructor/GenerateConstructorHandler.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateConstructorActionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8534
changelog: The `Generate constructor` action will now place the cursor after the generated constructor.
=> REF: move cursor after generated constructor in GenerateConstructor action

debugger/src/main/kotlin/org/rust/debugger/debuggingIntegration.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunner.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/legacy/RsDebugRunnerLegacy.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt
After #8265 the plugin provides debugger integration for Rider. But Rider 2021.3 has basic debugging classes only in Rider 4UE edition. But the platform doesn't take into account additional dependencies in optional dependency manifest. As a result, debugging optional dependency is loaded in common Rider edition as well that leads to `NoClassDefFoundError` in some places
These changes add runtime checks for the necessary plugins not to load debugger classes in Rider 2021.3
Fixes #8622
changelog: Fix `NoClassDefFoundError` exceptions in Rider 2021.3 and show debugger settings properly
=> DBG: avoid `NoClassDefFoundError` in Rider 2021.3

build.gradle.kts
It should fix `java.lang.NoClassDefFoundError: com/intellij/openapi/util/SystemInfoRt` during parser generation.
Also, drop hack with `bomConfiguration` because it was deleted from the plugin
=> GRD: update `org.jetbrains.grammarkit` to `2021.2.2`

src/main/kotlin/org/rust/cargo/runconfig/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/filters/RsDbgFilter.kt, src/test/kotlin/org/rust/cargo/runconfig/filters/RsDbgFilterTest.kt
Closes #8676
changelog: Provide file links in terminal for dbg! macro output
=> RUN: provide file links in terminal for dbg! macro output

src/main/kotlin/org/rust/ide/typing/paste/JsonStructParser.kt, src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt, src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
The improvement comes from this comment: https://github.com/intellij-rust/intellij-rust/pull/7816#issuecomment-1054181347.
=> IDE: unify optional fields of struct arrays in paste after JSON import

build.gradle.kts
It should fix the bootstrap error caused by `java.lang.NoClassDefFoundError: com/intellij/openapi/util/SystemInfoRt` with latest 2022.1 builds during `runIde` task
=> GRD: update gradle-intellij-plugin to 1.5.2

src/main/kotlin/org/rust/openapiext/CommandLineExt.kt
After e210aa0b9da7ad73c624a98eaa8d30f8f4399d32 only one implementation of `GeneralCommandLine.execute` prints logs
This change fixes adds logs into the second version of the method
=> Add missing logs

src/main/kotlin/org/rust/ide/newProject/RsDirectoryProjectGenerator.kt
Previously, if new project name contained `.` in the name, the plugin validated only name prefix before `.`
Fixes #8680
changelog: Properly validate new Rust project names with `.` symbol
=> PRJ: properly validate new Rust project name in minor IDEs

src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt, src/main/kotlin/org/rust/lang/doc/psi/Psi.kt, src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt, src/test/kotlin/org/rust/ide/annotator/RsDoctestAnnotatorTest.kt
A workaround. The real bug is that we considering each doc comment independently when parsing markdown.
````rust
/// ```
/// let a = 0;
//  <-- two slashes here!
/// let b = a;
/// ```
/// not a doctest
/// ```
/// a doctest
fn foo() {}
````
| - | - |
| ![image](https://user-images.githubusercontent.com/3221931/160899573-22c3fb22-a1bc-4d31-a255-f2c0018b28b2.png) | ![image](https://user-images.githubusercontent.com/3221931/160899757-9f221d0d-512f-4b0a-b9c8-80370e694f40.png) |
=> LI: Dont inject doctests if there are unbalanced code fences in prev doc

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt
Fixes #8737
The fix is copied from `com.intellij.codeInsight.hint.ImplementationViewComponent` (as initial implementation)
changelog: Don't try to release editor of macro expansion view twice
=> Don't release editor of macro expansion view twice

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Fixes #8660
changelog: Fix type inference of associated types that are referenced from a cast to a supertrait.
Consider the following code:
```rust
trait Mascot {
type Species;
fn get_species(&self) -> Self::Species;
fn get_species_name(&self) -> &'static str {
std::any::type_name::<Self::Species>()
}
}
trait LanguageMascot : Mascot {}
#[derive(Debug)]
struct Crab;
struct Ferris;
impl Mascot for Ferris {
type Species = Crab;
fn get_species(&self) -> Self::Species {
Crab
}
}
impl LanguageMascot for Ferris {}
fn crab_language_mascot() -> impl LanguageMascot<Species = Crab> {
Ferris
}
fn main() {
let crab = crab_language_mascot().get_species();
println!("{:?}", crab);
}
```
The compiler successfully infers that `crab` has type `Crab`, but previously intellij-rust resolved its type to `<impl …
=> TY: infer associated types on supertraits if possible

.github/workflows/check.yml, src/main/kotlin/org/rust/cargo/RustfmtWatcher.kt, src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/RustfmtProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt, src/main/kotlin/org/rust/ide/actions/RustfmtEditSettingsAction.kt, src/main/kotlin/org/rust/ide/formatter/RustfmtFormattingService.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt, src/test/kotlin/org/rust/cargo/project/RustProjectSettingsServiceTest.kt, src/test/kotlin/org/rust/cargo/project/RustfmtProjectSettingsServiceTest.kt, src/test/kotlin/org/rust/ide/formatter/RsTrailingCommaFormatProcessorTest.kt
Also, shows rustfmt errors in a ballon.
Closes https://github.com/intellij-rust/intellij-rust/issues/4024.
Closes https://github.com/intellij-rust/intellij-rust/issues/6061.
Closes https://github.com/intellij-rust/intellij-rust/issues/7422.
changelog: Allow to configure addition arguments and other options for Rustfmt
=> RUN: Allow to configure addition arguments and other options for Rustfmt

src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/ide/actions/runAnything/RsRunAnythingProvider.kt, src/main/kotlin/org/rust/ide/actions/runAnything/cargo/CargoRunAnythingProvider.kt, src/main/kotlin/org/rust/ide/actions/runAnything/wasmpack/WasmPackRunAnythingProvider.kt, src/main/resources/messages/RsBundle.properties
Previously, the Cargo and wasm-pack commands invoked from `Run Anything` popup ignored given executor and always use `run` mode
Now, they respect run/debug modes (if possible)
Closes #8696
changelog: Respect run/debug modes in [Run Anything](https://www.jetbrains.com/help/idea/running-anything.html) by Cargo commands
=> RUN: support Cargo command debugging from `Run Anything` popup

build.gradle.kts
It should help statistics automation set a proper minimal IDE version for new event rules
=> GRD: provide `buildNumber` in `eventScheme.json`

.github/workflows/check.yml
cargo-generate 0.13.1 depends on `kstring` crate that requires at least rustc 1.59 for compilation
=> CI: fix cargo-generate installation on CI

src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt, src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
Suggested by @dima74 in https://github.com/intellij-rust/intellij-rust/pull/8596#issuecomment-1069230235.
changelog: Use `#[serde(rename)]` attribute for fields that do not use snake_case convention when converting from JSON.
=> IDE: use #[serde(rename)] attribute for fields when converting from JSON

src/main/kotlin/org/rust/ide/inspections/lints/RsNamingInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt, src/test/kotlin/org/rust/ide/inspections/lints/naming/RsVariableNamingInspectionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
1.
```rust
struct Foo;
//X
fn main() {
match Foo {
Foo => {}
//^
}
}
```
2. Treat patterns like `let Foo = Foo;` as irrefutable
3. Don't trigger naming warning for let declarations that refers to a unit struct like `let Foo = Foo;`
=> RES: resolve RsPathBinding to a unit structs

src/main/kotlin/org/rust/ide/inspections/lints/RsDoubleMustUseInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsDoubleMustUse.html, src/main/resources/inspectionDescriptions/RsUnusedMustUse.html, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt, src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsDoubleMustUseInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspectionTest.kt
This PR introduces `unused_must_use` and `clippy::double_must_use` lints and quickfixes for them.
Closes #7549 ("_Implement unused-must-use lint"_)
changelog: Add unused_must_use and clippy::double_must_use inspections and quick-fixes
=> INSP: Add unused_must_use and double_must_use warnings

src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
Fixes #3129
changelog: Don't highlight safe [intrinsics](https://doc.rust-lang.org/std/intrinsics/index.html) as unsafe
=> ANN: don't highlight safe intrinsics as unsafe

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapsBuilder.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/ResolveCommonThreadPool.kt
Previously we have static thread pool in `MacroExpansionService` which was used in name resolution, and sometimes we create new thread pool for name resolution. Now single thread pool will be used always.
=> PERF: Reuse single thread pool in name resolution

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8541.
Fixes https://github.com/intellij-rust/intellij-rust/issues/8698.
changelog: Fix external linter when more than one file opened
=> RUN: Fix external linter when more than one file opened

src/main/resources/org/rust/ide/colors/highlighterDemoText.rs, src/test/kotlin/org/rust/ide/colors/RsColorSettingsPageTest.kt
Fixes #8734
Also add test to verify all colors have examples in color setting page if it's possible
changelog: Add missing example of cfg disabled code in Rust color settings page (`Settings/Preferences | Editor | Color Scheme | Rust`)
=> Add highlighting example of cfg disabled code in color settings

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Not the plugin should support these cases:
```rust
fn foo(f: &&fn() -> i32) {
let a = f();
a;
} //^ i32
```
and
```rust
use std::rc::Rc;
fn foo(f: Rc<fn() -> i32>) {
let a = f();
a;
} //^ i32
```
and
```rust
struct S();
impl S {
fn new() {
let a = Self();
a;
} //^ S
}
```
Also, I moved E0618 implementation into the type inference engine, so it should work more precisely. 
Fixes #6682
Fixes #8311
=> TY: improve type inference around call expressions

src/main/kotlin/org/rust/openapiext/utils.kt
Unfortunately, experimental features are not configured via system properties like registry values. It can be important when you want to use IDE-based tool (like Qodana) that runs IDE in headless mode, and you can't configure it using UI
These changes add a small hack to force values of experimental features used by Rust plugin via system properties - just pass `-D%experimental.feature.key%=%value%` to jvm process
=> Allow configuring experimental features for Rust plugin via Java properties

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml
changelog: Enable `Emulate terminal in console` option by default in the nightly version of the plugin on macOS and Linux
=> RUN: Enable `Emulate terminal in console` option by default in nightly plugin on macOS and Linux

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsCrateDocLineMarkerProvider.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt, toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt, toml/src/test/kotlin/org/rust/toml/CargoCrateDocLineMarkerProviderTest.kt
This PR adds a configurable URL which serves as a base for external documentation links (for `extern crate` doc links and for the documentation provider). Maybe we could also add a similar option for `stdlib` documentation links?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/3594
changelog: You can now set a custom base URL for external documentation using the `org.rust.external.doc.url` Advanced setting. The default value is `https://docs.rs/`.
=> DOC: add option to choose external documentation base URL

src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/test/kotlin/org/rust/cargo/runconfig/command/TestCargoCommandConfiguration.kt
Make `CargoCommandConfiguration` open not to break [EduTools](https://plugins.jetbrains.com/plugin/10081-edutools) plugin integration with Rust plugin that was broken in #6836
Also add `TestCargoCommandConfiguration` child class to prevent similar bugs in the future
changelog: Fix integration of [EduTools](https://plugins.jetbrains.com/plugin/10081-edutools) plugin with Rust plugin
=> Fix integration with EduTools plugin

src/main/kotlin/org/rust/lang/core/stubs/index/RsCfgNotTestIndex.kt
<details>
```
java.lang.AssertionError: file=FILE; tree=Element(FILE)
each of class class org.rust.lang.core.psi.impl.RsBlockImpl; valid=true; ref=com.intellij.psi.impl.source.SubstrateRef$StubRef@135b2bf9
each of class class org.rust.lang.core.psi.impl.RsBlockImpl; valid=true; ref=com.intellij.psi.impl.source.SubstrateRef$StubRef@e8579b5
each of class class org.rust.lang.core.psi.impl.RsFunctionImpl; valid=true; ref=com.intellij.psi.impl.source.SubstrateRef$StubRef@5fe21154
each of class class org.rust.lang.core.psi.impl.RsMembersImpl; valid=true; ref=com.intellij.psi.impl.source.SubstrateRef$StubRef@49911eb6
each of class class org.rust.lang.core.psi.impl.RsImplItemImpl; valid=true; ref=com.intellij.psi.impl.source.SubstrateRef$StubRef@3dff09e
each of class …
```
=> Fix exception during indexing in RsCfgNotTestIndex

src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
changelog: Take into account line breaks in `rustfmt` errors
Before:
After:
=> UI: Take into account line breaks in rustfmt errors

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/types/BoundElement.kt, src/main/kotlin/org/rust/lang/core/types/infer/Expectation.kt, src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Fixes #5141, fixes #6484, fixes #4578
changelog: Implement value unsizing in type inference. This fixes false-positive errors like type mismatch between `Box<[u8]>` and `Box<[u8; 4]>`
=> TY: implement unsizing

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt, src/test/kotlin/org/rust/lang/core/resolve/ref/RsLiteralWebReferenceProviderTest.kt
https://user-images.githubusercontent.com/2539310/167897081-df1f4bf8-b13c-4486-ba35-78190045bf81.mov
changelog: Highlight urls in string literals and allow opening them in browser from the editor
=> RES: provide web references for plain text urls in string literals

src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt
Fixes the bug introduced in #6492
Fixes #8732
changelog: Don't throw `NullPointerException` during quick documentation generation in some cases
=> QDOC: avoid NPE during documentation generation

.github/workflows/check.yml
This fixes CI builds on Rust nightly
=> CI: stick cargo-generate version to 1.13.1

src/main/kotlin/org/rust/cargo/runconfig/CargoRunState.kt, src/main/kotlin/org/rust/cargo/runconfig/RsProcessHandler.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/console/CargoConsoleBuilder.kt, src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt, src/main/kotlin/org/rust/cargo/runconfig/wasmpack/WasmPackCommandRunState.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/1973.
Closes https://github.com/intellij-rust/intellij-rust/issues/6867.
The `Emulate terminal in output console` options is taken into account only for simple runs. In other words, it does not affect Build/Test tool windows or Run Targets.
changelog: Use proper terminal if `Emulate terminal in output console` option is enabled. Also, this option is now available on Windows.
=> RUN: Use proper terminal if `Emulate terminal in output console` option is enabled

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8858.
changelog: Fix rendering of assoc type bindings in `Implement members` action
=> ACT: Fix rendering of assoc type bindings in `Implement members` action

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Fixes #8804
changelog: Fix resolve of procedural macro when there is other item with same name in scope
=> RES: Fix resolve of macros when other item with same name is in scope

src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RustProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/project/settings/impl/RustProjectSettingsServiceImpl.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/inspections/RsAssertEqualInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/RsAssignToImmutableInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt, src/test/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceConstantTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsIntroduceVariableHandlerTest.kt, src/test/kotlin/org/rust/ide/refactoring/generate/GenerateGetterActionTest.kt, src/test/kotlin/org/rust/ide/template/postfix/IterPostFixTemplateTest.kt, src/test/kotlin/org/rust/ide/template/postfix/LetPostfixTemplateTest.kt, src/test/kotlin/org/rust/ide/template/postfix/PrintlnPostfixTemplateTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
I think the new macro expansion now works perfectly and I can't imagine a case where the old engine is usable. These is still an option to disable macro expansion at all.
I need to remove it because there are some hacks in type inference (hardcoded impls) that hinder type inference engine development
Some kind of "old" macro expansion is still used in our tests (until `@ExpandMacros` annotation is used) due to performance reasons. 
changelog: Remove Old Macro Expansion Engine option.
=> MACRO: Remove Old Macro Expansion Engine

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
This name is a bit more convenient for debug log settings
=> Rename `org.rust.macros` logger to `#org.rust.macros`

build.gradle.kts, src/221/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt, src/221/main/resources-nightly/META-INF/platform-experiments.xml, src/221/main/resources-stable/META-INF/platform-experiments.xml, src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAware.kt, src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt, src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt, src/222/main/resources-nightly/META-INF/platform-experiments.xml, src/222/main/resources-stable/META-INF/platform-experiments.xml, src/222/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt, src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt, src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/resources/META-INF/rust-core.xml
These changes introduce a new approach to detect potential project model changes and notify users about it.
Previously, the plugin had only file listener that was triggered by changes in VFS and it checked if changes were "interesting"  -  any changes in config files like `Cargo.toml` and creation/deletion of implicit crate roots like `main.rs`, `lib.rs`, `build.rs`, files in `tests`, `benches` and `examples` directories. 
And it mostly works, but the implementation has some disadvantages:
- your changes should be saved to VFS, i.e. if you type something in `Cargo.toml`, the plugin won't know about it until IDE saves a new version of `Cargo.toml` with your changes. And you have to save files manually (which is quite weird in IntelliJ world) or wait when the IDE saves your change in some …
=> CARGO: support common approach for project model reloading for Cargo via `ExternalSystemProjectAware`

src/main/kotlin/org/rust/ide/typing/paste/JsonStructParser.kt, src/test/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteTest.kt
Suggested [here](https://github.com/intellij-rust/intellij-rust/pull/8629#issuecomment-1091781655).
changelog: Better support arrays containing nulls in JSON to Rust conversion.
=> IDE: add support for unifying structs in arrays containing nulls

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/BoundElement.kt, src/main/kotlin/org/rust/lang/core/types/Kind.kt, src/main/kotlin/org/rust/lang/core/types/infer/Declarations.kt, src/main/kotlin/org/rust/lang/core/types/infer/Expectation.kt, src/main/kotlin/org/rust/lang/core/types/infer/Fold.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt, src/main/kotlin/org/rust/openapiext/Testmark.kt, src/main/kotlin/org/rust/stdext/Collections.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
It should now look more like the Rustc version.
This PR also changes `?T: Sized` trait selection (now it follows Rustc version), so it should become compatible with #8866.
=> Refactor `ImplLookup.assembleCandidates`

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt
```rust
trait Bound1 {}
trait Bound2 {}
trait Trait1 { fn foo(&self) {} }
trait Trait2 { fn bar(&self) {} }
impl<T: Bound1> Trait1 for T {}
impl<T: Bound2> Trait2 for T {}
struct S;
impl Bound1 for S {}
fn foo(a: &S) { a./*caret*/ } // `foo` must be in the completion list
```
changelog: Complete more methods when autoderef occurs
=> COMP: fix method completion filtering by trait bounds with autoderef

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/core/types/TyFingerprint.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Fixes #8947, fixes #8945
Such methods now will be resolved:
```rust
struct S;
() => { S };
}
impl foo!() {
fn bar(self) {}
}    //X
fn main() {
S.bar();
}   //^
```
changelog: take into account impls for macro types. For example, `impl foo!() { fn bar(&self) {} }`
=> TY&RES: take into account impls for macro types

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt
`TraitImplSource` instances are extensively cached, so they bloat old generation heap space a lot
=> PERF: reduce memory usage by `TraitImplSource` instances

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt
Depends on #8902
This is a first step in implementing auto traits like `Sync` or `Send`. By definition, an auto trait is automatically implemented for primitive types and for composite data types if all their constituent types implement that auto trait. Hence, the only way to "unimplement" an auto trait is using a negative impl.
changelog: Consider negative impls (e.g. `impl !Sync for T {}`) in type inference
=> TY: take into account negative impls

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/generate/BaseGenerateHandler.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsImplIndex.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsTypeAliasIndex.kt, src/main/kotlin/org/rust/lang/core/types/infer/Fulfillment.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionFilteringTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPreciseTraitMatchingTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsImplicitTraitsTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Fixes #8084
```rust
trait Foo { fn foo(self); }
struct S;
impl<'a> Foo for &'a S {
fn foo(self) { }
}    //X
fn bar(s: S) {
s.foo();
}   //^
```
changelog: Consider methods in impls for a reference (`&Foo`) when the receiver is not a reference type
=> TY&RES: consider methods in impls for a ref when receiver is not a ref

clion/src/main/kotlin/org/rust/clion/debugger/RsCLionDebuggerDriverConfigurationProvider.kt, debugger/src/main/kotlin/org/rust/debugger/RsDefaultDebuggerDriverConfigurationProvider.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunParameters.kt, src/main/resources/META-INF/rust-core.xml
Add registry flag to enable native Rust support in MSVC LLDB on Windows. The flag is disabled by default and operates as follows:
- when disabled, MSVC LLDB uses Clang-based implementation and treats Rust types and expressions as C++ types and expressions (same as it was before);
- when enabled, MSVC LLDB detects if a PDB file corresponds to Rust source code, and in that case, the new Rust-aware implementation is used to manipulate debug information, types and expressions.
This functionality is available for MSVC LLDB bundled with CLion 2022.2 since 222.2889 build. Note, the Rust-aware implementation at this point is experimental and might cause LLDB crashes in certain cases.
Part of #5632.
changelog: Add registry flag to enable native Rust support in MSVC LLDB on Windows. Note, the …
=> DBG: Add registry flag to enable native Rust support in MSVC LLDB

src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt, src/222/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt, src/main/kotlin/org/rust/cargo/CargoConstants.kt
Now the plugin watches changes in [Cargo config](https://doc.rust-lang.org/cargo/reference/config.html) and [rust-toolchain](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) files and updates/suggests updating the project model in the same way as it already does with `Cargo.toml`
Note, this change works only with new project model auto import (can be enabled via `org.rust.cargo.new.auto.import` registry key) which is available since 2022.2 major IDE release
See #8114
Part of #6424
changelog: Update or suggest updating the project model on changes in [Cargo config](https://doc.rust-lang.org/cargo/reference/config.html) and [rust-toolchain](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) files using new project model auto import
=> CARGO: watch changes in cargo config and rust toolchain files

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
Fixes method resolve in this case:
```rust
struct S<T>(T);
trait T1 { fn foo(self: Box<Self>); }
trait T2 { fn foo(self: Rc<Self>); }
impl<T> T1 for S<T> { fn foo(self: Box<Self>) {} }
//X
impl<T> T2 for S<T> { fn foo(self: Rc<Self>) {} }
fn main() {
Box::new(S(0i32)).foo();
}                    //^
```
changelog: fix method picking by self type when self type is arbitrary
=> TY&RES: fix method picking by self type when self type is arbitrary

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
changelog: Detect [E0429](https://doc.rust-lang.org/error-index.html#E0429) and [E0431](https://doc.rust-lang.org/error-index.html#E0431) compiler errors
=> ANN: Check E0429 and E0431 (self imports)

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt
=> PERF: slightly speed up `canCombineTypes` (2nd attempt)

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionVfsBatch.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt, src/main/kotlin/org/rust/openapiext/utils.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
When creating/deleting macro expansion files, we look that if we need to create one file and delete one file, then instead we move the file that needs to be deleted to the place where we want to create a new one, and write new text there. Thanks to this, we do not go into the Dumb Mode (we always get into it when creating files on a VFS), which already helps not to clear some platform caches (seemingly). And then we don't bump the structure modification tracker again (well, if the change in the expansion happens somewhere in the body of the function, for example). It remains only not to bump it for the first time (a kind of this is implemented in #8978).
This, unfortunately, does not help with recursive macros, but it can help with procedural ones, which are usually expands in one step …
=> PERF&MACRO: edit single macro without entering the dumb mode

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiManager.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedTypeAlias.kt, src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt, src/test/kotlin/org/rustPerformanceTests/RsHighlightingPerfTest.kt
Introduce a separate modification tracker for changes in external dependencies. Now any changes in workspace rust files does not increment that modification tracker, hence does not invalidate any caches that depend on that tracker.
=> PERF: introduce dependencies modification tracker

src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt
We started to increment the rust structure modification tracker on changes in macro call bodies since #8647, but this seems to be not actually needed.
changelog: Invalidate less caches after changes in macro call bodies. This speeds up completion&highlighting performance when typing in macro invocations.
=> PERF: Don't increment rust structure mod tracker on change in macro call

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt, src/main/kotlin/org/rust/lang/core/macros/errors/ResolveMacroWithoutPsiError.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
It looks like error messages has been a bit broken since #8647.
Fixes #8953
changelog: Fix error messages explaining why some (procedural) macro has not been expanded
=> MACRO: fix macro expansion error messages, add tests for them

src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAware.kt, src/222/main/kotlin/org/rust/cargo/project/model/impl/CargoSettingsFilesService.kt, src/222/test/kotlin/org/rust/cargo/project/model/impl/CargoExternalSystemProjectAwareTest.kt, src/main/kotlin/org/rust/cargo/CargoConstants.kt
Note, these changes take into account only crate root of build script target not to involve name resolution in project model updates. But such cases are quite rare - I found only 15 crates with modules in build scripts among 2000 top downloaded crates on crates.io
Part of #6424
changelog: Detect changes in build scripts and notify users about it using new project model auto import API
=> CARGO: detect changes in build scripts and notify users about it

src/main/kotlin/org/rust/lang/core/macros/errors/MacroExpansionError.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt, testData/test-proc-macros/src/lib.rs
Currently, if you use `println!("{{}}")` in a proc macro, an exception will be logged (see #8939). It is (unfortunately) expected behavior and it is not touched by this PR.
But there is a bug in `ProcMacroExpansionError` serialization - if you use `println!("{{}}")` in a proc macro, it actually breaks `MacroExpansionSharedCache`, hence it breaks all macros in the project. The PR fixes this bug
=> MACRO: fix `ProcMacroExpansionError.IOExceptionThrown` deserialization

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt, src/main/resources/META-INF/rust-core.xml
Disabling `MacroExpansionSharedCache` actually breaks the plugin, so it shouldn't be possible to disable it
=> Remove registry option to disable `MacroExpansionSharedCache`

src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroBinding.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsReferenceBase.kt, src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Fixes #8880
changelog: Support rename refactoring for macro metavariables
=> REF&MACRO: fix macro metavar renaming

build.gradle.kts, src/main/kotlin/org/rust/ide/inspections/lints/RsDeprecationInspection.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CrateVersionRequirement.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexService.kt, toml/src/main/kotlin/org/rust/toml/inspections/NewCrateVersionAvailableInspection.kt, toml/src/main/resources/org.rust.toml.xml, toml/src/test/kotlin/org/rust/toml/completion/LocalCargoTomlDependencyVersionCompletionTest.kt, toml/src/test/kotlin/org/rust/toml/inspections/CrateVersionInvalidInspectionTest.kt
This PR replaces `semver4j` with [kotlin-semver](https://github.com/z4kn4fein/kotlin-semver) lib as a more appropriate variant that solves the problems we've had with pre-release sections parsing as we were converting versions into npm ones.
In fact, the replacement fixes #7600, and provides correct order for pre-release versions in completion. So, it also enables version-related inspections by default
Closes #7600
Related to #6463
changelog: Handle correctly pre-release dependencies' versions parsing and enable `Invalid crate version` and `New crate version availaible` inspections for `Cargo.toml` by default
=> INSP: Use kotlin-semver to avoid false-positives in version comparison & enable version inspections

gradle-222.properties, gradle.properties
Update 2022.2 dependencies. Since the latest platform EAP reached beta state, let's make 222 platform default for development
changelog: Make 2022.2 platform default for development
=> GRD: make 2022.2 platform default for development

src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt, src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt, src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/inlineValue/RsInlineValueProcessor.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsStructLiteralField.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/test/kotlin/org/rust/ide/hints/type/RsExpressionTypeProviderTest.kt
Ctrl+shift+P
changelog: Support "type info" with field shorthand syntax. You can invoke "type info" using `Ctrl`+`shift`+`P` shortcut
bors r+
=> ACT: support "type info" with field shorthand

build.gradle.kts
=> GRD: exclude kotlin dependencies from plugin provided by `io.github.z4kn4fein:semver`

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/test/kotlin/org/rust/lang/core/macros/RsUndoAfterTypingInMacroTest.kt
The bug was introduced in #8977.
It turned out that undo merger stopped working when typing in a macro.
That is, if you type, say, `foo` outside a macro call and invoke `Undo` action, the entire `foo` is undone.
But if you type it in a macro call, then it undoes only the last typed symbol - `o`, so `fo` remains in the document
changelog: Should not be mention in the changelog if released with #8977
=> Fix `Undo` (Ctrl+Z) action after typing in a macro call

.github/workflows/check.yml
Evcxr was recently updated to 0.13 which requires Rust 1.59. We currently use Rust 1.58 on CI, so lets use evcxr 0.12 on CI for now.
bors r+
=> REPL: Use Evcxr 0.12 on CI

src/main/kotlin/org/rust/lang/core/dfa/liveness/Liveness.kt, src/test/kotlin/org/rust/lang/core/dfa/RsLivenessTest.kt
Now `RsInferenceContextOwner#liveness` can be used to get the last usages of a certain variable (in terms of the execution flow). The usage is considered last if there is no execution path such that the variable is accessed after this usage.
This PR does not change anything from the user's perspective. The new code information will be used later for `Inline Function` refactoring.
=> Collect last usages of variables in liveness analysis

src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
Another approach could be simply to only allow removing the variable if the parent is a `LetDecl` :thinking: I'm not sure which is more robust (maybe I missed some cases?).
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8941
changelog: Do not offer to remove unused variables in places where they are required.
=> INSP: do not offer to remove unused patterns if they are required

src/main/kotlin/org/rust/lang/core/macros/MacroCallBody.kt, src/main/kotlin/org/rust/lang/core/macros/MappedText.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroSyntaxFixupTest.kt
Follows https://github.com/rust-lang/rust-analyzer/issues/11014 discussion
=> MACRO: try to fix up rust syntax before calling an attribute proc macro

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
Incrementing the modification tracker without a write action can lead to a cache incoherence, but I can't name a specific issue for now
=> Increment modification tracker in write action in `MacroExpansionTask`

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Compute `getIncludingMod` only if mod declaration for the file is not found.
This is useful because mod declaration search is usually performed anyway, and including macro search may be omitted if there is a mod declaration
=> PERF: speed up `getIncludingMod` usages

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsStdlibErrorAnnotatorTest.kt
If there are multiple definitions with the same name, we show an error to the user. Here are possible errors:
* [`E0428`](https://doc.rust-lang.org/error-index.html#E0428) - item            vs    item
* [`E0255`](https://doc.rust-lang.org/error-index.html#E0255) - item            vs    import
* [`E0260`](https://doc.rust-lang.org/error-index.html#E0260) - item            vs    extern crate
* [`E0252`](https://doc.rust-lang.org/error-index.html#E0252) - import          vs    import
* [`E0254`](https://doc.rust-lang.org/error-index.html#E0254) - import          vs    extern crate
* [`E0259`](https://doc.rust-lang.org/error-index.html#E0259) - extern crate    vs    extern crate
Currently plugin supports E0428, E0255 (shown as E0252) and E0252. This PR adds support for remaining error codes. …
=> ANN: Rework duplicate definition errors

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/ui.kt, src/main/kotlin/org/rust/ide/refactoring/inlineUtils.kt, src/main/kotlin/org/rust/ide/refactoring/inlineValue/ui.kt
Implement `RsInlineFunctionDialog::ignoreOccurrence` to ignore occurrences in imports. This affects the situation when a function has single usage in another module. Please see #8563 for details
changelog: Fix ["Inline function"](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractmethod-refactoring) refactoring dialog when function has single usage in another module
=> REF: Fix counting number of occurrences in inline function refactoring

debugger/src/main/kotlin/org/rust/debugger/settings/RsBreakOnPanicConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerDataViewConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerGeneralSettingsConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerUiComponent.kt, src/main/kotlin/org/rust/cargo/project/configurable/CargoConfigurable.kt, src/main/kotlin/org/rust/cargo/project/configurable/RsExternalLinterConfigurable.kt, src/main/kotlin/org/rust/cargo/project/configurable/RsProjectConfigurable.kt, src/main/kotlin/org/rust/cargo/project/configurable/RustfmtConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/ui/RustProjectSettingsPanel.kt, src/main/kotlin/org/rust/cargo/runconfig/target/RsLanguageRuntimeConfigurable.kt, src/main/kotlin/org/rust/cargo/runconfig/ui/CargoCommandConfigurationEditor.kt, src/main/kotlin/org/rust/cargo/runconfig/ui/WasmPackCommandConfigurationEditor.kt, src/main/kotlin/org/rust/ide/actions/ui/CargoNewCrateDialog.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt, src/main/kotlin/org/rust/ide/module/CargoConfigurationWizardStep.kt, src/main/kotlin/org/rust/ide/newProject/RsProjectGeneratorPeer.kt, src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt, src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/ui.kt, src/main/kotlin/org/rust/ide/refactoring/extractStructFields/ui.kt, src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt, src/main/kotlin/org/rust/openapiext/ui.kt, src/main/resources/messages/RsBundle.properties
These changes replace all usages of Kotlin UI DSL v1 to v2 since the first version is deprecated
More precisely, it refactors:
- Cargo command editor in Cargo Command run configuration dialog
- Wasm pack command editor in Wasm pack run configuration dialog
- Cargo settings (`Preferences | Build, Execution, Deployment | Build Tools | Cargo` / `Preferences | Languages & Frameworks | Rust | Cargo`)
- Rustfmt settings (`Preferences | Languages & Frameworks | Rust | Rustfmt`)
- External linter settings (`Preferences | Languages & Frameworks | Rust | External Linters`)
- Rust settings (`Preferences | Languages & Frameworks | Rust`)
- New Rust project dialog (both versions in IDEA and minor IDEs like CLion)
- `Add custom template` dialog invoked from new Rust project UI
- Rust section in …
=> UI: migrate Kotlin UI DSL to second version

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt
The bug was introduced in #8977 by adding `@Synchronized` to `FSItem.name`, but actually the bug has been triggered only by #8986 because of bumping `ProcMacroExpander.EXPANDER_VERSION` (see #9088)
<details>
<summary>Deadlocked threads dump</summary>
```
"Indexing" prio=0 tid=0x0 nid=0x0 blocked
java.lang.Thread.State: BLOCKED
on org.rust.lang.core.macros.MacroExpansionFileSystem$FSItem$FSFile@453d9c44 owned by "Indexing" Id=32
at org.rust.lang.core.macros.MacroExpansionFileSystem$FSItem$FSFile.getName(MacroExpansionFileSystem.kt:381)
at org.rust.lang.core.macros.MacroExpansionFileSystem$FSItem$FSDir.findChild(MacroExpansionFileSystem.kt:314)
at org.rust.lang.core.macros.MacroExpansionFileSystem.convert(MacroExpansionFileSystem.kt:166)
at …
```
=> Fix deadlock in MacroExpansionFileSystem

src/main/resources/META-INF/rust-core.xml
Since #8927 the plugin accept any recursion limit specified by `#![recursion_limit]` attribute. But we use several recursive algorithms when working with macros, hence pure unlimited `recursion_limit` may lead to a stack overflow. By this hotfix I limit the maximal recursion depth to 1000, but in the future we can get rid of such recursive algorithms and then remove the limit
changelog: Restore maximal `#![recursion_limit]` to 1000 when expanding macros. This fixes possible stack overflow
=> MACRO: limit maximal recursion depth to 1000

src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt
`Use` items lowering is now needed rarely needed so we can make it lazy
changelog: Slightly optimize name resolution
=> PERF: optimize `expandedItemsCached`

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionErrorTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroErrorTest.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt
1. Show message "the macro call is conditionally disabled with a `#[cfg()]` attribute" in the case of cfg-disabled macro call that refers to a declarative macro. Previously there was some other unrelated error message. For example "procedural macro expansion is not enabled" if  `org.rust.cargo.evaluate.build.scripts` and/or `org.rust.macros.proc` experimental features are disabled.
```rust
() => { fn foo() {} }
}
#[cfg(not(intellij_rust))]
foo! {}
```
2. Show message "the procedural macro is not compiled successfully" when `org.rust.cargo.evaluate.build.scripts` and/or `org.rust.macros.proc` experimental features are disabled. Previously the error was "the procedural macro is not compiled successfully"
Also add tests for these cases.
changelog: Fix error messages about …
=> MACRO: Fix macro expansion error messages in several cases

src/main/kotlin/org/rust/ide/annotator/AnnotationSessionEx.kt, src/main/kotlin/org/rust/ide/annotator/RsAnnotationHolder.kt, src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/main/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/main/kotlin/org/rust/ide/presentation/Utils.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt
changelog: 1. Slightly speed up highlighting 2. Speed up appearance of inlay hints
=> PERF: reduce usages of `existsAfterExpansion` in annotators

src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Prefers `Future::Output` over `IntoFuture::Output`, not sure if it's possible to have both
Fixes #9051 
changelog: support `.await`ing types that implement `IntoFuture` and resolve the output type
=> TY&COMP: support `.await`ing `IntoFuture`

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Fixes #8559
changelog: Fix resolve of macros declared in `include!`-ed files in some cases
=> RES: Fix propagation of `include!`-ed macros to child modules

src/main/kotlin/org/rust/ide/refactoring/RsRenameProcessor.kt, src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
Fixes #9115
changelog: Fix rename of constant used in struct literal field shorthand
=> REF: Fix rename of item used in struct literal field shorthand

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureConfig.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureDialog.kt, src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
This PR adds additional checks to `Change signature` refactoring to:
1) Disallow using `self`, `&self` and other invalid patterns for parameter names
2) Make sure that if the parameter cannot be created, the refactoring silently fails rather than crashes and removes all parameters.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/9147
changelog: Fix handling of `self` parameters in `Change signature` refactoring.
=> REF: increase robustness of handling self parameters in Change Signature refactoring

src/main/kotlin/org/rust/ide/statistics/RsConvertJsonToStructUsagesCollector.kt, src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt, src/main/resources/META-INF/rust-core.xml
Inspired by `GoGenerateTypeFromJsonUsageCollector`
Note, any statistics are collected only if `Send usage statistics` option in `Preferences | Appearance & Behavior | System Settings | Data Sharing` is enabled
See #7816
=> IDE: Collect statistics when converting json to struct on paste

src/main/kotlin/org/rust/ide/console/RsConsoleRunner.kt
Fixes: #8903
changelog: You can now change execute shortcut for [Rust REPL](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-repl-console.html) using `Execute Current Statement in Multiline Console` option in keymap
=> REPL: Inherit execute action shortcut from `Console.Execute.Multiline`

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoConfigTest.kt
Currently, it doesn't affect users anyhow since the plugin doesn't use the corresponding info yet
=> CARGO: properly extract build target if there isn't cargo config file

.idea/runConfigurations/Generate_compiler_features.xml, attributes-info/rust-toolchain.toml, attributes-info/rustc_span/src/symbol.rs
These changes:
- fix `attribute-info` compilation by using `sync::LazyLock` instead of `lazy::SyncLazy`
- force using nightly toolchain (including IDE integration) via `rust-toolchain.toml`
- fix `Generate compiler features` run configuration
changelog: Fix `attribute-info` crate compilation which is used to update the compiler features
=> Fix `attribute-info` compilation

src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Fixes #6850
changelog: Fix that auto-import may corrupt existing unnamed import
=> Fix auto-import grouping with existing unnamed import

src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixture.kt, toml/src/main/kotlin/org/rust/toml/jsonSchema/CargoTomlJsonSchemaProviderFactory.kt, toml/src/main/resources/org.rust.toml.xml, toml/src/test/kotlin/org/rust/toml/completion/CargoTomlCompletionTestBase.kt
TOML plugin has a feature to provide completion/documentation based on the corresponding JSON scheme. Previously, it didn't affect any completion because there weren't such schemes. But now there is https://json.schemastore.org/cargo.json and the feature started to affect us. As a result, some unexpected completion variants appear in the suggestion list
These changes provide our own scheme for Cargo.toml to use it instead of remote https://json.schemastore.org/cargo.json. It's empty for now that leads to no completion variants based on JSON scheme completion (including unexpected ones). It's supposed to be replaced with an actual scheme when completion is fixed
Fixes #9116
changelog: Don't suggest unexpected/duplicate completion variants in Cargo.toml
=> TOML: suppress completion in Cargo.toml based on JSON scheme

src/main/kotlin/org/rust/lang/core/completion/RsMacroCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Fixes #7780
changelog: Fix redundant macro completion in mod item name
=> COMP: Fix redundant macro completion in mod item name

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Fixes #8614
Related: #7156 (but that is for mod declaration in `include!`-ed file )
changelog: Fix resolve of items from nested `include!`-ed files in some cases
=> RES: Fix nested `include!`-ed files in different directory

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Currently when toggle ["Expand macros" option](https://github.com/intellij-rust/intellij-rust/pull/9127), we have two problems:
* `CrateDefMap`s don't rebuild
* `structureModificationTracker` doesn't increment if option was disabled but becomes enabled
---
This may lead to problems like (thanks @neonaot):
```rust
macro_rules! gen {
() => { fn func() {} }
}
gen!();
fn main() {
func();
}
```
* Disable "Expand macros" - `func` is unresolved (good)
* Enable "Expand macros" - `func` is still unresolved (bad)
changelog: Fix cache invalidation after toggle "Expand macros" settings
=> RES: Fix cache invalidation after toggle "Expand macros" settings

src/main/kotlin/org/rust/lang/core/resolve/Namespace.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Fixes #8092
changelog: Fix resolve of enum variants in match pattern in some cases
=> RES: Fix resolve of enum variants in match pattern in some cases

src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/PathResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt
Fixes #8651
changelog: Fix resolve of reexported macro in some cases
=> RES: Fix resolve of macro without `macro_export` reexported as macro 2.0

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroResolveTest.kt
Fixes #8768
Fixes #9141
changelog: Fixes resolve of items with `#[async_trait]` in some cases
=> RES: Fix glob import of item with identity proc macro

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
Fixes #9110
#9021 leads to a stack overflow through `RsExpandedElement.getContextImpl` and `RsModulesIndex.getDeclarationsFor`.
I think the proper fix is stopping using `RsModulesIndex` in `RsFile.doGetCachedData`, I'll do it later
changelog: Fix possible Stack overflow introduced in the previous release of the plugin
=> Hotfix #9110 by reverting #9021

toml/src/main/kotlin/org/rust/toml/completion/RsTomlKeysCompletionProvider.kt
Updated the Cargo.toml schema to the currently supported list of keys.
changelog: extended list of key completions in `Cargo.toml`
=> COMP: update list of autocompleted keys in Cargo.toml

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, prettyPrinters/gdb_lookup.py, prettyPrinters/gdb_providers.py, prettyPrinters/lldb_lookup.py, prettyPrinters/lldb_providers.py, prettyPrinters/rust_types.py, pretty_printers_tests/tests/slice.rs
Add GDB/LLDB pretty-printers to show the contents and the size of Rust slices.
Fixes #8519.
changelog: Add debugger pretty-printers to show the contents and the size of Rust slices
=> Add slice pretty-printers

src/main/kotlin/org/rust/ide/refactoring/changeSignature/RsChangeSignatureUsageProcessor.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMod.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/THashMapBase.kt, src/main/kotlin/org/rust/lang/utils/evaluation/CfgEvaluator.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsDefMapMacroIndexConsistencyTest.kt
=> PERF: reduce cfg evaluation in `expandedItemsCached` and cache `CfgEvaluator` for a crate

src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/main/kotlin/org/rust/ide/annotator/format/RsFormatMacroAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/format/impl.kt, src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt, src/main/kotlin/org/rust/lang/core/macros/MappedText.kt, src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorToolchainTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsBuiltinMacroExpansionTest.kt
This is an attempt to implement the method for supporting implicit format arguments mentioned [here](https://github.com/intellij-rust/intellij-rust/pull/8561#issuecomment-1187276428). Currently, it fixes false positives in the liveness inspection.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/8417
changelog: Remove false positive "unused variable" warnings for implicit format arguments used in macros like println.
=> MACRO: support liveness inspection for implicit args in `format_args`

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt, src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
Fixes #9172
Fixes #9159
You can read the full story [here](https://fasterthanli.me/articles/proc-macro-support-in-rust-analyzer-for-nightly-rustc-versions). Long story short, since 01.08.2022 there is a binary `$sysroot/libexec/rust-analyzer-proc-macro-srv` shipped within `rustc` rustup component in the nightly channel. This binary can be used as a drop-in replacement for our own `intellij-rust-native-helper` in the case of macro expansion. Of course it is always compatible with rustc version it shipped with, so now macro expansion will work fine on every nightly version.
In this PR I use `rust-analyzer-proc-macro-srv` instead of `intellij-rust-native-helper` if it is available (exist). This likely obsoletes #8930.
Note that `intellij-rust-native-helper` is still used as a rustc wrapper …
=> MACRO: Use `rust-analyzer-proc-macro-srv` from toolchain if available

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/test/kotlin/org/rust/lang/core/resolve2/TestAllStdlibFilesAreIndexed.kt
Add new stdlib parts to index, also add a test that checks that all stdlib files are indexed. Since `portable-simd` is an unstable part of stdlib, this most likely does not affect users except in terms of performance.
Also, new stdlib parts are now visible in "External Libraries":
=> PERF: Index new stdlib parts `portable-simd`

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
Fixes #9023
changelog: Fixes possible `java.io.IOException` during typing in a macro call
=> Fix `java.io.IOException` during typing inside a macro call

src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/main/kotlin/org/rust/ide/inspections/CargoCommandLineInspectionProjectConfigurator.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties
Provide implementation of `CommandLineInspectionProjectConfigurator` EP to properly configure project model for cargo-based projects for running inspection from [command line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) or via [Qodana](https://www.jetbrains.com/qodana/)
changelog: properly configure cargo-based projects for running inspection from [command line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) or via [Qodana](https://www.jetbrains.com/qodana/)
=> INSP: configure project to run inspections from command line

src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Reduces `getModInfo` and `ModData.toRsMod()` calls. 
=> PERF: speed up prelude processing using new resolve

prettyPrinters/gdb_providers.py, prettyPrinters/lldb_providers.py, pretty_printers_tests/tests/cell.rs
Since Rust 1.63.0, `Ref` and `RefMut` use `value: NonNull<T>` instead of `value: &T`. Accidentally, we did not have the corresponding tests to catch this, so this PR also adds them.
changelog: Update debugger pretty-printers to render `Ref` and `RefMut` properly
=> DBG: Update `Ref`/`RefMut` pretty-printers to Rust 1.63 and add tests

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/PsiElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt
Now `RsElement.containingCrate` uses `containingFile` which is much faster than `contextualFile` it used previously. Each `RsFile` (even a macro expansion) now has a correct `CachedData` (with a `Crate`, `isDeeplyEnabledByCfg`, etc.)
=> PERF: speed up `containingCrate` and similar properties

src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionSharedCache.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFileInternals.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsBuiltinMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/psi/RsPsiFileInternalsTest.kt
Depends on #9188
This actually fixes a performance regression introduced in #8647. In that PR we started to expand macro calls inside impl blocks (`impl Foo { bar!(); }`) to temporary in-memory files `LightVirtualFile` (like we do with local macro calls). A side-effect of in-memory files usage is the fact that PSI constructed from such in-memory files does not use stubs. As a result, we waste CPU parsing the content of expansions and waste memory for full AST of such expansions. This could be not a big problem if macro calls inside impls are rarely used, but they're actually used in stdlib, in impls for primitive files :)
In this PR I found a way to specify a stub for a PsiFile. However, this way involves reflection usage. The stub is extracted from the macro expansion cache, as in the …
=> PERF&MACRO: use stubs for expansions of macro calls inside `impl`s

src/main/kotlin/org/rust/cargo/CargoConfig.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoConfigTest.kt
Previously, the plugin expected `forced` field instead of `force`.
Also, now parsing doesn't fail on unknown fields
Fixes #9212
changelog: Properly parse environment variables in [cargo config](https://doc.rust-lang.org/cargo/reference/config.html#env)
=> CARGO: properly parse env variable in cargo config

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, prettyPrinters/gdb_lookup.py, prettyPrinters/gdb_providers.py, prettyPrinters/lldb_lookup.py, prettyPrinters/lldb_providers.py, prettyPrinters/rust_types.py, pretty_printers_tests/tests/range.rs
Add summary pretty-printers for range types:
* `core::ops::range::Range`
* `core::ops::range::RangeFrom`
* `core::ops::range::RangeInclusive`
* `core::ops::range::RangeTo`
* `core::ops::range::RangeToInclusive`
Fixes #7760.
changelog: Provide debugger pretty-printers to render range types (e.g. `core::ops::range::Range`)
=> DBG: Add summary pretty-printers for range types

src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/test/kotlin/org/rust/lang/core/resolve/RsIncludeMacroResolveTest.kt
Simplified version of the #7156. This doesn't touch `RsMod#getOwnedDirectory` and `processModDeclResolveVariants` since they are quite complex and I think we should rewrite them using `CrateDefMap`. So resolve of mod declaration itself (#6472) and some other features like "go to super mod" will not work, but the main problem - resolve to items inside the module - will be fixed.
Fixes #7147
Fixes #9032
Related: #9132
changelog: Fix resolve of items inside module declared in `include!`-ed file
=> RES: Fix module declaration in `include!`-ed file

build.gradle.kts
Since G1GC is a default for all IDEs
=> GRD: Use G1GC for IDEs run from Gradle

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Fix cargo features inference in the case of a dependency duplicated with rename, where these dependencies have different required features and only one dependency is actually enabled (see example in tests).
The bug could be reproduced with `mysql_async` crate:
```toml
[dependencies]
mysql_async = "=0.30.0"
```
In this case, the `bigdecimal` dependency of `mysql_async` must not have `serde` feature (optional dependency) enabled.
changelog: Fix cargo feature state inference in several cases
=> Fix cargo features inference

src/main/kotlin/org/rust/cargo/project/model/impl/CargoPackageIndex.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefMapService.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeUpdateDefMap.kt, src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt, src/test/kotlin/org/rust/lang/core/psi/RsRustStructureModificationTrackerTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStubOnlyResolveTest.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt
Slightly speeds up name resolution. This is also a proper fix for #9110. 
=> PERF: stop using `RsModuleIndex` in `RsFile.doGetCachedData`

src/main/kotlin/org/rust/lang/core/psi/RsFile.kt
#9021 has been reverted in #9169 because of #9110. Now it can be enabled again because we got rid of recursion in `RsFile.getCachedData()` in #9171
changelog: Enable again [the optimization](https://github.com/intellij-rust/intellij-rust/pull/9021) reverted in the previous release. Slightly speed up name resolution
=> PERF: re-revert #9021 speed up `getIncludingMod` usages

prettyPrinters/gdb_providers.py
Fixes the issue described in https://github.com/intellij-rust/intellij-rust/pull/9203#issuecomment-1220719461, concerning Rust version 1.62 or earlier.
In contrast to LLDB, GDB's pretty-printing API does not allow access to non-existing child members.
=> DBG: Fix `Ref`/`RefMut` GDB pretty-printers on Rust 1.62

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Fixes #6765
changelog: Show error message in Sync tool window if project directory does not exist
=> CARGO: show error msg in Sync tool window if project dir does not exist

native-helper/src/rustc_wrapper.rs, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoGeneratedItemsResolveTest.kt
Fixes #9198, fixes #9227.
Based on https://github.com/rust-lang/rust-analyzer/pull/13010 and discussion in https://github.com/rust-lang/rust-analyzer/issues/12973.
intellij-rust-native-helper in `RUSTC_WRAPPER` role unconditionally succeeds `cargo check` invocations tripping up build scripts using `cargo check` to probe for successful compilations. To prevent this from happening the `RUSTC_WRAPPER` now checks if it's run from a build script by looking for the `CARGO_CFG_TARGET_ARCH` env var that cargo sets only when running build scripts.
changelog: Fix broken `anyhow` compilation when `org.rust.cargo.evaluate.build.scripts` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) is enabled
=> Do not unconditionally succeed RUSTC_WRAPPER when run by build scripts

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/lang/core/resolve2/util/PerNsHashMap.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Fixes #9263
The `Error` trait [was recently moved](https://github.com/rust-lang/rust/commit/bf7611d55ee6e24647aefc4d1c82b1dba0164536#diff-ea30f57e78f3b861b784ae315b3ac31358b7cea2aa14a668084ad412de12e586R306) to the `core` crate, so we started to show two variants of auto-import for `error` mod. Technically this is not a bug, but I think it make sense to filter only std variant in such cases.
changelog: Fix auto-import variants for `error::Error` path on nightly toolchain
=> Filter single mod in auto-import when root path resolves to same item

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
changelog: Fix auto import of attr proc macro with the same name as crate
=> Fix auto import of attr proc macros

src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt
It seems like local (located inside function bodies) derive/attr procedural macros and attr macros located inside `impl` bodies are almost ignored for now. Furthermore, they lead to weid bugs:
```toml
[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
```
```rust
use serde::Serialize;
fn main() {
#[derive(Serialize)] // Try to see the expansion
struct Foo;
println!("Hello, World");
}
#[derive(Serialize)]
struct Bar;
```
If you try to see the expansion of the derive for `struct Foo`, you will actually see the expansion of the derive for  `struct Bar`!
This PR fixes basic proc macro expansion. Interesting that name resolution still doesn't work in most cases.
This PR fixes @HolgerGottChristensen's case from https://github.com/intellij-rust/intellij-rust/issues/8966#issueco …
=> MACRO: fix local proc macro expansion

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/project/model/CargoPackagesTest.kt, src/test/kotlin/org/rust/cargo/project/model/CargoStdlibPackagesTest.kt
`cargo metadata` gathers (including downloading) info about dependencies for all targets. As a result, the plugin always took into account all dependencies including [platform-specific](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) ones before these changes.
Now, the plugin passes proper build target via `--filter-platform` flag to get dependencies only for the given platform.
It should reduce the time of some operations (like indexing) since the plugin will process less code now.
These changes affect almost all users since it makes plugin analyze fewer dependencies even for stdlib (although in the case of stdlib the effect is not significant)
| - | - |
| <img width="358" alt="Screen Shot 2022-06-21 at 09 12 53" …
=> CARGO: invoke `cargo metadata` only for current platform

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Fixes #9001
Nested or-patterns were [stabilized](https://github.com/rust-lang/rust/pull/79278) in Rust 1.53. The final design allows leading vertical bar `|` in nested or-patterns, just like toplevel or-patterns. This was previously an explicit error, also implemented in the plugin.
This PR reverts the deprecated error on nested patterns.
changelog: allow leading | in nested or-patterns
=> ANN: allow leading | in nested or patterns

src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Related: #9259
changelog: Complete out-of-scope proc macros in attributes
=> COMP: Complete out-of-scope proc macros in attributes

src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
Fixes #9286
changelog: Always reload the project model after changes in settings which affect the model
=> CARGO: reload the project model after changes in toolchain settings

build.gradle.kts, src/222/main/kotlin/org/rust/cargo/project/model/impl/compatUtils.kt
Building of searchable options was broken by migration to new plugin model (#8709).
As a result, `Find Action` dialog and settings search cannot find options provided by the plugin.
These changes fix Gradle `buildSearchableOptions` task
| - | - |
| <img width="716" alt="Screenshot 2022-09-03 at 17 17 07" src="https://user-images.githubusercontent.com/2539310/188277053-c0333e4c-cb54-4dcb-adf8-d0cd796e2bd0.png"> | <img width="716" alt="Screenshot 2022-09-03 at 17 07 17" src="https://user-images.githubusercontent.com/2539310/188277059-5ece0e97-4905-4dc6-ae67-c3324f1e11fe.png"> |
| <img width="1012" alt="Screenshot 2022-09-03 at 17 17 17" src="https://user-images.githubusercontent.com/2539310/188277069-7002bcd7-33c0-4873-9e89-5869a04fa9d4.png"> | <img width="1094" …
=> GRD: fix searchable options building

src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt, src/test/resources/org/rust/ide/folding/fixtures/crates.rs, src/test/resources/org/rust/ide/folding/fixtures/mods.rs, src/test/resources/org/rust/ide/folding/fixtures/uses.rs, src/test/resources/org/rust/ide/folding/fixtures/where.rs
Closes #8982
Examples of displayed foldings (pipes denote boundaries of replacement strings):
```
|/* uses */|   -->  uses |...|;
|/* mod */|    -->  mod |...|;
|/* crates */| -->  extern crate |...|;
fn f() |/* where */| {}   -->   fn f() where |...| {}
```
This should make folded code blocks more distinct from folded block comments (even though the latter
are almost never used in the wild).
Unfortunately, this means that folding cannot be invoked on unfolded tokens (i.e. `use`, `mod`, `where`,
`extern crate` and `;` in the examples above). This can be mildly confusing, but at the moment I have no
better solution.
This feature has a precedent in Kotlin, which also folds imports in a way which leaves `import ...` with `import` being an unfolded keyword. Kotlin also doesn't have a solution …
=> TYPE: change folded regions to look more like unfolded ones

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTestBase.kt
This includes `target_feature`, `proc_macro`, `proc_macro_derive` and `proc_macro_attribute`. The latter three are provided only insides proc macro crates. These attributes require a function with specific signature, but imho checking the signature is too hard and too brittle for the gain. Providing these attributes in more cases also makes them slightly more discoverable, although it likely won't matter in practice.
changelog: update completions for function attributes
=> COMP: add new attribute completions

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Other crates can't depend on binary crates, so `pub` reexports in binary crates are effectively `pub(crate)` and can be marked unused if so.
changelog: Support "Unused imports" inspection for public reexports in binary crates
=> Mark unused public reexports in binary crates

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
It seems like when we have to choose one containing crate for a file from multiple variants, we choosing it in a non-deterministic manner, i.e. randomly. This can lead to flaky tests and difficulties in reproducing bugs. Let's choose some deterministic strategy for choosing a containing crate
=> Deterministically select RsFile containing crate if there are multiple

src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt
Option to use old resolve was removed in #9187, and option to use old macro expander was removed in #8900, so I guess it make sense to update github issue template
=> ACT: Remove resolve engine info from "Create new issue" action

src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt, src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
This PR generalizes `MatchToIfLetIntention` so that it now works for almost all match expressions.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7409
changelog: The intention to convert a match expression to a series of if let statements is now offered in more situations.
=> INT: generalize MatchToIfLetIntention to arbitrary arm count

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionDialog.kt
When refactoring is invoked on reference, we may show different options [based on number of usages](https://github.com/intellij-rust/intellij-rust/pull/8563):
* One usage - two options (inline all and remove, inline this only)
* Two and more usages - three options (inline all and remove, inline all and keep, inline this only)
In some cases number of occurrences may be unknown. In such case we should show all three options, but because of bug we showed only two.
Meta: #5511
changelog: Fix ["Inline function"](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractmethod-refactoring) dialog when number of occurrences is unknown
=> REF: Fix "Inline function" dialog when number of occurrences is unknown

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionDialog.kt, src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionHandler.kt, src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt
Inline function dialog may look [strange](https://user-images.githubusercontent.com/6505554/188288463-5494af27-3736-4c47-afe5-cce7572778f4.png) for functions with a large number of parameters, so it is better to use just function name there
Meta: #5511
changelog: Improve UI of ["Inline function"](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractmethod-refactoring) dialog for functions with a large number of parameters
=> REF: Use function name instead of signature in "Inline function" dialog

src/main/kotlin/org/rust/ide/refactoring/RsDowngradeModuleToFile.kt, src/main/kotlin/org/rust/ide/refactoring/RsPromoteModuleToDirectoryAction.kt
This includes RsDowngradeModuleToFile and RsPromoteModuleToDirectoryAction.
The human-readable name provides a nice name in the undo stack, instead of "Undo Undefined".
| - | - |
| <img width="352" alt="Screenshot 2022-09-07 at 14 13 30" src="https://user-images.githubusercontent.com/2539310/188875701-4fb715a9-57ff-45ce-8124-45a93c8c4742.png"> | <img width="356" alt="Screenshot 2022-09-07 at 14 06 51" src="https://user-images.githubusercontent.com/2539310/188874694-3f24c2b7-e3eb-4329-8b45-52b35b01643b.png"> |
| <img width="353" alt="Screenshot 2022-09-07 at 14 13 38" src="https://user-images.githubusercontent.com/2539310/188875738-500c1101-f42b-4150-a13b-f40056c566ab.png"> | <img width="351" alt="Screenshot 2022-09-07 at 14 06 59" …
=> TYPE: provide human-readable name to some refactorings

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/resolve/RsPathResolveResult.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/types/BoundElement.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt
Resolve and cache all nested paths at once, so `Foo<Foo<Foo<Foo>>>` resolution costs `O(1)` instead of `O(4)`.
This is particularly helpful in the case of `typenum` crate where there are a lot of types like this:
```rust
pub type U50 = UInt<UInt<UInt<UInt<UInt<UInt<UTerm, B1>, B1>, B0>, B0>, B1>, B0>;
```
changelog: Speed up name resolution of large nested paths like `Foo<Foo<Foo<Foo<...>>>>`
=> PERF: resolve nested paths at once

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
=> PERF: speed up `RsResolveProcessor.lazy()`, get rid of `LazyScopeEntry`

src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Since Rust 1.62 Cargo has an unstable option [`--keep-going`](https://github.com/rust-lang/cargo/issues/10496).
By default, cargo stops the build immediately if one rustc instance or buildscript instance fails, even if it would be possible to compile other crates that does not depends on the error crate.
The option `--keep-going` instructs cargo to continue building even if the compilation of some crate fails or the evaluation of some buildscript fails. This behavior is exactly what we need in the case of buildscript evaluation - as an IDE, we need to compile&evaluate as much as possible.
=> CARGO: Use `--keep-going` when building and evaluating buildscripts

src/221/main/resources/META-INF/platform-experiments.xml, src/222/main/resources-nightly/META-INF/platform-experiments.xml, src/222/main/resources-stable/META-INF/platform-experiments.xml, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
changelog: Enable build script evaluation in nightly plugin builds for 2022.2 platform
=> CARGO: enable build script evaluation in nightly plugin builds

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/RemoveElementFixTest.kt
- Check if the custom attr override is used by `findInScope`
- Add new error code `E0774`, which should be part of #886
changelog: Fix detection of  [E0774](https://doc.rust-lang.org/error-index.html#E0774) compiler error
=> ANN: Check if the custom attr override is used by `findInScope`

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/RsPsiSubstitution.kt
... and use it only for default type parameter values.
The only purpose of that recursion guard is to prevent infinite recursion in such cases:
```
pub trait Foo<A=Foo> {
type Output = Self;
}
type T = Foo;
```
(see `test no stack overflow when trait type parameter default value refers to the trait name`)
The PR is a further optimization of "resolve nested paths at once", see #9211.
=> PERF: move recursion guard out of `advancedResolve`

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt
Further optimization of "resolve nested paths at once", see #9211.
=> PERF: optimize `getRootCachingElement` for stub-based case

src/main/kotlin/org/rust/ide/annotator/format/impl.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
Although this is not clearly documented [here](https://doc.rust-lang.org/std/fmt/#precision), the precision in a formatting string is allowed to be empty. Arguably this is not useful, but it is still valid code:
```rust
// these two are equivalent:
println!("{:.}", 0.45);
println!("{}", 0.45);
```
The plugin used to incorrectly reject this code with the error _Invalid format string_.
This PR fixes that, by changing the regex used to parse format parameters. The capture groups work out such that both cases above give the exact same regex parse result, ensuring no differences in (future) behavior are introduced.
I don't really think this is important enough to include this in the changelog, but just in case:
changelog: Allow empty precision in formatting parameter
=> (INSP): Allow empty precision in string formatting parameter

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8936.
Closes #9246
changelog: Fix URLs in messages from external linters
=> DOC: Fix urls in messages from external linters

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Fixes that auto-import fix is suggested for `Output` in code `impl Future<Output=i32>`. The fix should be suggested only for `Future`
changelog: Don't suggest auto-import fix for assoc type binding
=> Don't suggest auto-import fix for assoc type binding

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/completion/RsExternCrateCompletionTest.kt
This is simplified version of #4300 for workspace crates
Fixes #4780
changelog: Complete crates from workspace in `extern crate`
=> COMP: Complete crates from workspace in `extern crate`

build.gradle.kts
Otherwise, the task can't remove old files
=> GRD: use relative paths in `GenerateParserTask`

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsRedundantSemicolonsInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsRedundantSemicolons.html, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/inspections/lints/RsRedundantSemicolonsInspectionTest.kt
Based on https://github.com/rust-lang/rust/blob/673d0db5e/compiler/rustc_lint/src/redundant_semicolon.rs
Part of #5888 (_"Compiler lints support"_)
changelog: Add [redundant_semicolons](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#redundant-semicolons) inspection and quick-fix for it
=> INSP: Add redundant_semicolons inspection and fix

src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeParameter.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsLitExprReferenceContributor.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt
Fixes #8905
changelog: Fix name resolution of an associated type of a type parameter inside a trait bound, in the case where the type parameter is declared on a level other than the bound
=> RES: resolve assoc type in where pred with generic decl on upper level

src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8913.
TODO: Come up with a minimal reproducible example for tests
changelog: Don't erase the file content while formatting if `#![cfg_attr(rustfmt, rustfmt_skip)]` attribute is presented
=> RUN: Don't erase the file content while formatting if `#![cfg_attr(rustfmt, rustfmt_skip)]` attribute is presented

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/fixes/MakeAsyncFixTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/pull/9251#pullrequestreview-1095715405
changelog: Don't show fix to make function async when function returns `impl Future`
=> ANN: Don't show fix to make function async for function returning Future

src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
changelog: Don't auto-import usual items in derive attribute
=> Filter derive proc macros when auto-import in derive attribute

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
* Complete bang proc macros with `!`
* Use macro icon for bang and attr proc macros
* Don't show parameters like `TokenStream` for bang and attr proc macros
|:------:|:-----:|
| ![image](https://user-images.githubusercontent.com/6505554/188512966-8c1c4871-5807-4650-8f7c-9943a070fc9f.png) | ![image](https://user-images.githubusercontent.com/6505554/188513591-f7c53d52-30a0-48d6-9d71-8ee3a28946eb.png) |
changelog: Complete function-like proc macros with `!`
=> COMP: Improve completion of proc macros

src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt, src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
This reverts commit c93070167222fed81e2c10dab812a61133ea1e33.
After changes introduced in #7435, the `MatchToIfLetIntention` intention may produce code that cannot be compiled
CC @Kobzol @dima74 @mili-l
=> Revert "INT: generalize MatchToIfLetIntention to arbitrary arm count"

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoProjectImpl.kt, src/test/kotlin/org/rustSlowTests/RsContentRootsTest.kt
Previously, if some directory from default project layout (for example, `examples`) was marked as excluded, the plugin marked them as source directory after each project model reloading.
After these changes all already added folders (source and excluded ones) won't be overridden
Fixes https://youtrack.jetbrains.com/issue/CPP-29807
changelog: Don't override folder settings on project model reloading if the folder is manually marked as excluded or as source folder
=> CARGO: don't override content entries

src/main/kotlin/org/rust/ide/inspections/RsWrongAssocTypeArgumentsInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddAssocTypeBindingsFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt, src/main/kotlin/org/rust/ide/inspections/fixes/RemoveAssocTypeBindingFix.kt, src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/psi/RsPsiFactory.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsWrongAssocTypeArguments.html, src/test/kotlin/org/rust/ide/inspections/RsWrongAssocTypeArgumentsInspectionTest.kt
This PR adds an inspection and two quick fixes (add missing associated types, remove unknown associated types) that handle missing/erroneous associated type bindings.
There is some very similar code between `AddAssocTypeBindingsFix` and `AddTypeArgumentsFix`, which handles inserting new items into type arguments. Should it be extracted? If yes, where?
Related: https://github.com/intellij-rust/intellij-rust/issues/886
=> INSP: add inspection to check associated type bindings

.github/workflows/build-plugin.yml, .github/workflows/check.yml, .github/workflows/regressions.yml, .github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml, .idea/runConfigurations/RunCLion.xml, .idea/runConfigurations/RunIDEA.xml, CONTRIBUTING.md, build.gradle.kts, debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt, gradle-223.properties, gradle.properties, src/222/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt, src/222/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt, src/223/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessor.kt, src/223/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt, src/main/kotlin/org/rust/cargo/project/CargoProjectOpenProcessorBase.kt, src/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilderBase.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt, src/main/kotlin/org/rust/ide/navigation/goto/RsNavigationContributorBase.kt, src/main/kotlin/org/rust/ide/newProject/ui/RsNewProjectPanel.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/test/kotlin/org/rust/ide/inspections/import/RsReferenceImporterTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingToolchainTest.kt
The most interesting internal thing is migration to JDK 17. Now, you should use JDK 17 for development.
The reason is that 2022.3 is compiled with JDK 17, i.e. almost all classes have 61.0 bytecode version including kotlin ones. As a result, you should use the same (or above) JDK version as libraries use to call kotlin inline functions from these libraries.
But since 2022.2 still uses JDK 11, the plugin uses different target java versions for different platforms:
- java 11 for 222
- java 17 for 223
And not to introduce unncessesary compatibility problems, you can't use new features or API from Java 17 yet. But it doesn't look like even minor problem since we mostly use Koltin
changelog: Support 2022.3 platform. Internal: Use Java 17 for development
=> Support 2022.3 platform

src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/utils.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt
changelog: Support `Create associated function` intention for path `Self::func()`
=> INT: Support "Create associated function" for path `Self::func()`

src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Fixes #9292
changelog: Fix adding imports in `Change signature` refactoring
=> REF: Fix adding imports in "Change signature" refactoring

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/intentions/AddImportForPatternIntention.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/intentionDescriptions/AddImportForPatternIntention/after.rs.template, src/main/resources/intentionDescriptions/AddImportForPatternIntention/before.rs.template, src/main/resources/intentionDescriptions/AddImportForPatternIntention/description.html, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt, src/test/kotlin/org/rust/ide/intentions/AddImportForPatternIntentionTest.kt
Fixes #7815
Consider match arm:
```rust
match ... {
Foo => {}
_ => {}
}
```
Here `Foo` can be constant or enum variant if any is in scope, otherwise it will be name of variable (irrefutable pattern). Therefore we don't show unresolved reference error for `Foo`, though user actually may want `Foo` to be constant but doesn't import it yet. This PR adds `Import` intention for such cases.
changelog: Add an intention to import constants in match arms
=> INT: Add an intention to import constants in match arms

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/annotator/format/impl.kt, src/main/kotlin/org/rust/ide/refactoring/RsNamesValidator.kt, src/main/kotlin/org/rust/lang/core/lexer/utils.kt, src/main/kotlin/org/rust/lang/core/macros/builtin/BuiltinMacroExpander.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/builtin/RsBuiltinMacroExpansionTest.kt
=> MACRO: fix `format` macro expansion when param name is keyword (`self`) or there is a syntax error in param name

src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt, src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt, src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rust/ide/typing/paste/RsAddImportOnCopyPasteTest.kt
This PR adds a copy/paste postprocessor that tries to import unresolved items from the pasted code. There is also some crude support for selecting between ambiguous imports.
I took inspiration from the Kotlin plugin, mainly with the data flavor thing, I'm not sure how that's supposed to work.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7241
changelog: Automatically import unresolved items after copy/pasting Rust code.
=> IDE: add imports after pasting code

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
An internal change which should not affect users. Needed for https://github.com/intellij-rust/intellij-rust/pull/9312#pullrequestreview-1110876747
Macro path in resolve is always `RsPath` after #9156 (previously it can be `PsiElement(identifier)`)
=> RES: Refactor `MacroResolver.isAttrOrDerive`

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
Fixes #6979
TODO: Fix priority of `std::vec` crate and `vec!` macro, etc (#8984)
changelog: Suggest importing modules in completion
=> Suggest importing modules in completion

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
When I worked on #9433 I found a weird behavior: the plugin prioritizes functions that return `!` type (e.g. "panic()" function). It is clearly visible when ML-assisted completion is disabled:
changelog: don't prioritize functions that return `!` type (e.g. `panic()`)
=> COMP: don't prioritize functions that return `!` type (e.g. panic)

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/completion/RsTupleFieldCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt
E.g. in this case the `vec![]` macro will be prioritized in the completion list (because it returns a `Vec` type and that type is expected):
```rust
fn vec() -> i32 { 0 }
fn main() {
let v: Vec<i32> = ve/*caret*/
}
```
Macros taken into account: `format`, `vec`, `addr_of`, `addr_of_mut`, `env`.
changelog: Take into account some stdlib macro types in completion sorting. For example, Now `vec![]` will be bubbled up in the completion list if expected expression type is `Vec`
=> COMP: Take into account some stdlib macro types

src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/miscExtensions/RsNavBarTest.kt
Looks like there are still some unsupported cases [e.g. with pat bindings](https://user-images.githubusercontent.com/6505554/193650079-8c746a9e-f3e5-408e-a62f-d26c4401e8dc.png) (thanks @mili-l for finding this)
I will fix them in separate PR
See #6581 for details
=> Temporarily disable structured nav bar

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Fixes such a case:
```rust
struct A;
const B: i32 = 1;
struct C;
struct Foo<A, const B: i32, C>(A, C);
fn main() {
let foo: Foo<A, B, C> = Foo(A, C);
let bar = foo; // should have `Foo<A, 1, C>` type, previously was `Foo<A, ?, ?>`
}
```
changelog: fix inference of types with mixed type/const type arguments
=> TY: fix mixed type/const type arguments

src/main/kotlin/org/rust/lang/core/crate/impl/CargoBasedCrate.kt, src/main/kotlin/org/rust/lang/core/crate/impl/CrateGraphServiceImpl.kt, src/test/kotlin/org/rustSlowTests/RsGcSoftlyReachableObjectsCacheTest.kt
Fixes #9432. See technical explanation [here](https://github.com/intellij-rust/intellij-rust/issues/9432#issuecomment-1267546685).
Actually, the bug is a wrong (missing) implementation of CargoBasedCrate.equals/hashCode.
changelog:
=> Fix issue #9432 random false-positives caused by GC activity

src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/test/kotlin/org/rust/common.kt, src/test/kotlin/org/rustSlowTests/lang/resolve/CargoProjectResolveTest.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProvider.kt, toml/src/main/kotlin/org/rust/toml/resolve/CargoTomlNameResolution.kt, toml/src/test/kotlin/org/rust/toml/CargoFeatureLineMarkerProviderTest.kt, toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlFeatureDependencyReferenceProviderTest.kt
Support cargo feature values inference for [new features syntax](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features).
Unfortunately, this implementation already has a known bug - #9476.
You can refresh knowledge about Cargo Features in [Cargo Book](https://doc.rust-lang.org/cargo/reference/features.html) and in [the CLion blog post](https://blog.jetbrains.com/clion/2020/10/intellij-rust-new-functionality-for-cargo-features/) about our support of cargo features.
In this (simple old-fashion) case, there is an implicit feature `foo` of the optional dependency `foo`:
```toml
[dependencies]
foo = { path = "./foo", optional = true }
```
In this (again old-fashion) case, there is an explicit feature `feature_foo` that depends on implicit feature `foo` of the …
=> CARGO: support new Cargo features syntax from 1.60.0

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Atm name resolution doesn't take label shadowing into account and returns all the definitions:
changelog: Fix nested labels shadowing
=> RES: Fix nested labels shadowing

src/222/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt, src/223/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilder.kt, src/main/kotlin/org/rust/ide/lineMarkers/ImplsGutterIconBuilderBase.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt, src/test/kotlin/org/rust/ide/lineMarkers/LineMarkerTestHelper.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt
Previously, when you pressed on `Has implementation` line marker to see all implementations of struct/enum, trait or trait item, the search was performed in EDT. As a result, if the search was long, your IDE froze for this time
Now, this search query is performed in background thread, and the loading icon is shown during the search. So, no more freeze in case of looking for implementations
Fixes #9457
changelog: Fix IDE freezing on searching implementation via `Has Implementation` line marker in gutter
=> Make implementation query async

src/main/kotlin/org/rust/lang/core/RsPsiPattern.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsStaticLifetimeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsStaticLifetimeCompletionTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/9435
changelog: Complete `'static` lifetime.
=> COMP: complete `'static` lifetime

src/main/kotlin/org/rust/lang/core/CompilerFeature.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Continuation of #7640. Previously, `wasm` abi was missed because the plugin didn't know about the corresponding compiler feature for some reason
changelog: Annotate usage of `wasm` abi as experimental
=> ANN: annotate usage of `wasm` abi as experimental

src/main/kotlin/org/rust/ide/refactoring/changeSignature/impl.kt, src/test/kotlin/org/rust/ide/refactoring/RsChangeSignatureTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/pull/9293#issuecomment-1266699804
changelog: Fix adding imports for return type in [`Change signature`](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#change-sign) refactoring
=> REF: Fix import references from return type in "Change signature"

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt
Fixes #9186
changelog: Improve auto-import of items from same crate in some cases
=> Don't use private reexport in crate root in auto-import

src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/resources/META-INF/rust-core.xml
Parallel macro expansion was introduced in #7947 along with experimental feature `org.rust.resolve.new.engine.macros.parallel` to turn it off in case of any errors. Since there are no related error reports, I guess it makes sense to remove the experimental feature
=> RES: Remove `org.rust.resolve.new.engine.macros.parallel`

src/main/kotlin/org/rust/lang/core/macros/MacroCallBody.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt, testData/test-proc-macros/src/lib.rs
Fixes #9445
changelog: Fix handling of [`$crate`](https://doc.rust-lang.org/reference/macros-by-example.html#hygiene) in procedural macros in some cases
=> RES: Fix passing paths with $crate to derive proc macro

src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt
Fixes #9498
This should not affect users (problems with `INFORMATION` level are filtered out in batch mode anyway)
=> INSP: Don't register problems with `INFORMATION` level in batch mode

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Fixes #9355
changelog: Fix `todo!()` macro type inference
=> TY: fix `todo!()` macro type inference

src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/2259#issuecomment-1260799649
changelog: Don't reorder reexports of legacy macros when optimizing imports
=> Don't reorder reexports of legacy macros when optimizing imports

src/main/kotlin/org/rust/ide/folding/RsFoldingBuilder.kt, src/test/kotlin/org/rust/ide/folding/RsFoldingBuilderTest.kt, src/test/resources/org/rust/ide/folding/fixtures/extern.rs
Fixes: https://github.com/intellij-rust/intellij-rust/issues/9497
changelog: Foreign mod declarations (`extern "C" { ... }`) arenow folded by the plugin.
=> IDE: fold foreign mods (extern blocks)

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/resources-stable/META-INF/experiments.xml
Fixes #4631
Fixes #6135
Fixes #7145
FIxes #8007
Fixes #6539
Fixes #9093
Fixes #9535
Closes #9402
changelog: Enable [build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html) evaluation by default. Now the plugin builds and executes all build scripts in the project (including build scripts in external dependencies) during project model loading to create source code generated during compilation and collect information about generated environment variables and `cfg` options. A typical use case is to generate some code by a build script and include it via `include!(concat!(env!("OUT_DIR"), "/path_to_generated_file.rs"))`. Now the plugin understands where generated code is located and includes them into its own analysis.
Under the hood, build script evaluation uses `cargo …
=> Enable build script evaluation by default

src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector2.kt, src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsOutOfScopeItemsCompletionTest.kt
|:------:|:-----:|
| ![image](https://user-images.githubusercontent.com/6505554/188499390-869de748-feb2-4f84-8f1d-e31e8419542c.png) | ![image](https://user-images.githubusercontent.com/6505554/188499464-e0c64760-9ffa-4d83-b25c-31d7116f9d3b.png) |
changelog: Filter out attr and derive proc macros in usual macro calls completion
=> Filter not bang proc macros in completion

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTestFixtureBase.kt, src/test/kotlin/org/rust/lang/core/completion/RsExternCrateCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
Fixes #9543
changelog: Fix resolve of absolute path when there is `extern crate` with alias
=> RES: Fix resolve absolute paths for aliased crate in extern prelude

src/main/kotlin/org/rust/ide/miscExtensions/RsBreadcrumbsInfoProvider.kt
Fixes exception when cursor is inside tail expr block in dumb mode:
```rust
fn main() {
{ /* cursor */ }
}
```
<details>
```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:67)
at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:62)
at org.rust.openapiext.UtilsKt.checkIsSmartMode(utils.kt:130)
at org.rust.lang.core.resolve2.FacadeUpdateDefMapKt.getOrUpdateIfNeeded(FacadeUpdateDefMap.kt:48)
at org.rust.lang.core.resolve2.FacadeResolveKt.findModDataFor(FacadeResolve.kt:666)
at org.rust.lang.core.psi.RsFile.doGetCachedData(RsFile.kt:143)
at …
```
=> Fix IndexNotReadyException in breadcrumbs

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/type/RsStdlibExpressionTypeInferenceTest.kt
Fixes #9201
Fixes #9542
changelog: Properly infer type of custom macros which shadow built-in macros
=> TY: properly infer type of custom macros which shadow built-in macros

src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt, src/test/kotlin/org/rust/ide/typing/paste/RsAddImportOnCopyPasteTest.kt
Looks like ["Insert imports on paste"](https://github.com/intellij-rust/intellij-rust/pull/7597) may be slow (https://youtrack.jetbrains.com/issue/VIM-2769, https://github.com/intellij-rust/intellij-rust/pull/9441#discussion_r996454390), so lets disable it by default for now
=> IDE: Temporary disable adding imports after pasting code

CONTRIBUTORS.txt, src/main/kotlin/org/rust/ide/inspections/RsSortImplTraitMembersInspection.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddDefinitionToTraitFix.kt, src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitProcessor.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/fixes/AddDefinitionToTraitFixTest.kt
This PR adds one of the quick fixes listed under E0407 in #886 (the most useful one that I have missed a couple of times already). Generates trait members with no default implementation, which is the behavior I would expect from this. Maintains the member order if the order of existing trait and impl members matches.
https://user-images.githubusercontent.com/998408/115119582-7370e500-9fa9-11eb-84b8-c4046ab98938.mp4
Currently, the E0437 and E0438 (the `type` and `const` versions of E0407, respectively) rustc errors are also classified as E0407 by the plugin, and this quick fix solves all three of them.
The current implementation duplicates `RsFunction.getSignatureText()` from the "implement members" fix/refactor. I am not sure what is the best place to move this (if it's even a good idea). …
=> ANN: Add a quick fix to add missing trait definitions

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Introduced in #9312
cc @mili-l 
changelog: Fix procedural macro completion in imports
=> COMP: Fix proc macro completion in imports

build.gradle.kts, gradle-223.properties, settings.gradle.kts
Also, temporarily use snapshot version of gradle-intellij-plugin because it contains fixes to properly launch the atest 2022.3 IDEs
=> GRD: update IDE and plugin dependencies for 223 builds

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Fixes #9565
The type inference bug existed since a while, but it escalated to a stack overflow after one of these PRs: #9211, #9337, #9338
changelog: Fix possible stack overflow during type inference
=> Fix #9565 stack overflow when dyn trait used as Self ty in where clause

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
cc @mili-l 
changelog: Fix duplicate completion of attribute procedural macros when it is imported locally
=> COMP: Fix duplicate completion of proc macros when there is local import

src/main/kotlin/org/rust/lang/utils/evaluation/ConstExprBuilder.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4738
changelog: Improve type inference of array sizes.
=> TY: improve inference of references to constants in const evaluation

src/main/resources/inspectionDescriptions/RsUnnecessaryQualifications.html
To make it in-line with Rust docs: doc.rust-lang.org/reference/paths.html#qualified-paths
Also previous form doesn't seem to be correct english word.
=> Replace qualificated with qualified

src/main/kotlin/org/rust/ide/annotator/fixes/AddFeatureAttributeFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt, src/main/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntention.kt, src/main/kotlin/org/rust/ide/intentions/ToggleFeatureIntention.kt
I disable intention preview in cases when intention creates new files or does something else not related to code, thus showing intention preview is not possible
Fixes #9560
Meta: #9561
changelog: Fix `Create module file` quick-fix in 2022.3
=> Disable intention preview for some intentions

build.gradle.kts, plugin/description.html
Since https://github.com/JetBrains/gradle-intellij-plugin/pull/1092, `gradle-intellij-plugin` checks "unacceptable warnings" and doesn't allow you to publish plugin to Marketplace with them.
One of such warnings is about the length of plugin description. 40 symbols is the minimal plugin description length required by JetBrains Marketplace. And previously, our description was shorter
This change will affect description in https://plugins.jetbrains.com/plugin/8182-rust and in plugin card in  `Plugins` settings in IDE
=> Fix plugin publication to Marketplace

src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt
Implicit run configurations are used in:
- `Run Anything` for cargo and wasm-pack
- Launch a target from Cargo Tool Window
- `Run Cargo Expand` intention
- `Build` button if Build Tool Window is disabled (except for `Test` command)
- Installing `cargo-expand`, `evcxr_repl`, `wasm-pack` or `grcov` via plugin's notification
You can turn it on / off in `Experimental features` - `org.rust.cargo.emulate.terminal`
changelog: Fix emulating terminal in output console in some cases
=> RUN: Emulate terminal for implicit run configurations by default on the nightly version of the plugin

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/types/TraitRef.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyAnon.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTraitObject.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyTypeParameter.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Fixes #7685, fixes #7729, fixes #8583
Fixes several bugs in type inference. First of all, this fixes annoying `trait bound is not satisfied E0277` false-positives usually observable when implementing `Ord`/`Eq` types:
```rust
struct Box<T>(T);
impl<T: PartialEq> PartialEq for Box<T> {}
impl<T: Eq> Eq for Box<T> {} // No false-positives now!
```
On a lower level, now we correctly infer a type of `a` in such cases:
```rust
trait Foo<T: ?Sized> {}
trait Bar: Foo<Self> {} // `Self` in trait inheritance!
fn bar<T: Bar>(t: T) {
let a = foo(t);
a;
} //^ T
fn foo<A: Foo<B>, B>(t: A) -> B { todo!() }
```
And similarly for `impl Trait`:
```rust
trait Tr1<A> {}
trait Tr2: Tr1<Self> + Sized {}
fn new() -> impl Tr2 { unimplemented!() }
fn foo<B, C>(_: B) -> C where B: Tr1<C> { unimplemented!() }
fn …
```
=> TY: fix `Self` substitution in the case of trait inheritance

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt
Fixes #9564
```rust
pub struct S<const N1: usize>;
pub const C: usize = 42;
fn main() {
let a = S::<{ C }> {};
a;
} //^ S<42>
```
=> Ty: infer const arguments in struct literal paths

src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/doc/psi/impl/Psi.kt
Extracted from #7353 for easier review
=> Simplify `.containingMod` and `.crateRoot` of `RsElement`

src/main/kotlin/org/rust/ide/inspections/fixes/AttachFileToModuleFix.kt, src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/main/kotlin/org/rust/ide/refactoring/move/RsMoveFilesOrDirectoriesProcessor.kt, src/main/kotlin/org/rust/ide/template/RsContextType.kt, src/main/kotlin/org/rust/ide/utils/import/importUtils.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/doc/psi/RsDocComment.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveFileTest.kt
This is needed for #7353 for resolving paths inside doc links (see [`walkUp`](https://github.com/intellij-rust/intellij-rust/blob/36320712696a5628fe3c62eb6a5be85d3042db2e/src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt#L1793) implementation)
I extracted it to separate PR for easier review
=> Make `RsDocComment` inherit `RsElement`

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPath.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPackageLibraryResolveTest.kt
|:------:|:-----:|
| ![image](https://user-images.githubusercontent.com/6505554/196056972-df1432e9-a45e-410b-a97f-8f0f13d54f62.png) | ![image](https://user-images.githubusercontent.com/6505554/196057073-8d1b7c2a-c2dc-4a6d-90b9-8a5bef534b8e.png) |
(`if { ... }` and `match { ... }` also should be removed in this case)
changelog: Don't resolve and complete macros after `::`
=> RES&COMP: Don't resolve and complete macros after `::`

src/main/kotlin/org/rust/cargo/runconfig/test/CargoBenchRunConfigurationProducer.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestLocator.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt, src/main/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributor.kt, src/test/kotlin/org/rust/cargo/runconfig/producers/TestRunConfigurationProducerTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt, src/test/resources/org/rust/cargo/runconfig/producers/fixtures/doctest.xml, src/test/resources/org/rust/cargo/runconfig/producers/fixtures/ignored_doctest.xml, src/test/resources/org/rust/cargo/runconfig/producers/fixtures/library_top-level_doctest.xml, src/test/resources/org/rust/cargo/runconfig/producers/fixtures/module_top-level_doctest.xml
This PR adds line markers and run configurations for doctests. The `isDoctest` parameter is a bit of a hack, but I wasn't sure how to solve it more elegantly. I would like to change the `kind` of the passed target e.g. to `Unknown`, so that no other flag like `--lib` or `--bin` is passed to `cargo test`, since it must contain only `--doc`.
Tests work fine, but in the IDE it behaves in a strange way. If I click on the test gutter of a doctest, it creates and runs the test correctly. But then if I add a normal `#[test]` function to the same file and execute that, from that moment on the gutters on the doctests go crazy and behave like if they were the main function or something like that, they offer me to profile them etc. Any idea what might be causing that? :) Maybe the test locator URL? …
=> DOC: add line marker and test run configuration provider for doctests

.github/actions/preparations-for-updates/action.yml, .github/workflows/check.yml, .github/workflows/create-changelog.yml, .github/workflows/milestones.yml, .github/workflows/notify-doc.yml, .github/workflows/regressions.yml, .github/workflows/release-branch.yml, .github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml
We use such scripts only on ubuntu runners which already have preinstalled python. Also, we didn't care about updating either version of `actions/setup-python` action or python version.
At the same time, we have quite simple python scripts which don't use the latest features from python, so I think it's ok to use preinstalled pythin version
All preinstalled software can be found [here](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md)
=> CI: don't install custom python to run python scripts on CI

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Fixes #9031
```rust
use self::foo::break
```
The original content of the above error caused the PSI element to escape from `USE_ITEM`
changelog: Fix raw identifier in `use declarations` not complete
=> COMP: Fix raw identifier in `use` cannot be complete

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt, src/main/kotlin/org/rust/lang/core/psi/RsProcMacroPsiUtil.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt, src/main/kotlin/org/rust/lang/core/resolve/KnownItems.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateModificationTracker.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt, src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Namely,
- `org.rust.macros.proc.function-like`
- `org.rust.macros.proc.derive`
- `org.rust.macros.proc.attr`
`org.rust.macros.proc` still exists and equivalent to enabling all these 3 features
=> MACRO: split `org.rust.macros.proc` experimental feature into 3 features

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Fixes #9521.
Examples:
```rust
struct S;
struct X;
trait Foo { type Item; }
impl Foo for S { type Item = X; }
trait Bar<T> {}
impl Bar<<S as Foo>::Item> for S {}
fn foo<A: Bar<B>, B>(_: A) -> B { todo!() }
fn bar(a: S) {
let b = foo(a);
b;
} //^ X
```
```rust
struct S;
struct X;
trait Foo { type Item; }
impl Foo for S { type Item = X; }
trait Bar<T = <Self as Foo>::Item> {}
impl Bar for S {}
fn foo<A: Bar<B>, B>(_: A) -> B { todo!() }
fn bar(a: S) {
let b = foo(a);
b;
} //^ X
```
=> Ty: normalize associated type in `impl` item trait ref

build.gradle.kts
In #9349 the plugin started to use `antlr` Gradle plugin to generate parser for debugger. But the corresponding changes used `plugin { antlr }` construction at the top-level of gradle script (it can be used only at top level) that led to application of `antlr` plugin for root module. But we need the plugin only in `debugger` module
These changes drop usage of `antlr` plugin from root module. As a result:
- no more unexpected `generateGrammarSource` task in root module
- we don't need to exclude antlr compilation time dependencies in root module
- no more implicit task dependencies in unexpected places. In expected places, they are declared explicitly more properly now
=> GRD: use `antlr` plugin only in `debugger` module

src/main/resources-nightly/META-INF/experiments.xml, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
changelog: Enable [function-like](https://doc.rust-lang.org/reference/procedural-macros.html#function-like-procedural-macros) procedural macro expansion in [nightly plugin builds](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly).
=> MACRO: enable function-like procedural macro expansion in nightly plugin builds

src/main/kotlin/org/rust/cargo/runconfig/test/CargoBenchRunConfigurationProducer.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducer.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestRunConfigurationProducerBase.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt
changelog: Don't show line markers for tests in dependence crates
=> RUN: Don't show line markers for tests in dependence crates

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt, src/test/kotlin/org/rust/common.kt
Previously, the plugin passed `RUSTC_BOOTSTRAP=1` only if its own native helper binary was used that broke evaluation with stable toolchain when native helper wasn't used (for example, because it wasn't found for some reason)
Now it properly set `RUSTC_BOOTSTRAP` variable regardless usage of native helper
Currently, I know two options how to reproduce initial issue:
- turn off `org.rust.cargo.evaluate.build.scripts.wrapper` registry option manually (artificial way)
- use the plugin on the platform where we don't have native helper binary. For example, Windows ARM
changelog: Don't fail build script evaluation without native helper binary
=> CARGO: don't fail build script evaluation without native helper

.github/workflows/check.yml, src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt
It should "fix" tests with old compiler version.
A combination of the following facts:
- stdlib 1.41.0 depends on `cmake` crate
- `cmake` crate switched from `2018` edition to 2021` in recent patch version
- cargo from `1.41.0` toolchain knows nothing about `2021` edition
caused test failures with 1.41.0
Probably, it's possible to fix it properly without increasing a minimal supported version of rustc, but 1.41 is **too** old version of the compiler and only very small part of users use such old compiler, I think it's more efficient just update a minimal supported version. 1.56 was chosen as the first version with support for 2021 edition
Now users will see notification if they still use old compiler
I intentionally didn't fix the corresponding `BACKCOMPAT: Rust *` comments since I want …
=> Increase minimal supported version of rustc to 1.56

build.gradle.kts, pretty_printers_tests/lldb_batchmode.py
Fixes #9554.
The problem with `UnicodeEncodeError` presumably appeared after upgrading to Python 3.10 (see https://youtrack.jetbrains.com/issue/CPP-30260). Particularly, this error occurred when the test runner tried to print the children nodes of Unicode strings, i.e. single Unicode characters. Unicode strings summaries provided by our pretty-printers were printed fine though. This allows us to safely use `.encode('utf-8', errors='replace').decode('utf-8')` workaround, leaving the corresponding tests valid: the tests will still properly compare the summaries containing only valid Unicode characters.
=> T: Fix pretty-printers tests for Unicode strings on Windows

src/main/kotlin/org/rust/ide/presentation/Utils.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsExternCrateCompletionTest.kt, toml/src/test/kotlin/org/rust/toml/resolve/CargoTomlKeyResolveTest.kt
Changes `nameIdentifier` of derive proc macros. As a result rename and search for references now works for them
changelog: Support renaming derive procedural macros
=> REF: Support renaming derive procedural macros

src/main/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionProcessor.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/ide/refactoring/inlineFunction/RsInlineFunctionTest2.kt
Related: #9429
Meta: #5511
changelog: Substitute `Self` in [`Inline function`](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-refactorings.html#extractmethod-refactoring) refactoring
=> REF: Substitute `Self` in "Inline function" refactoring

src/222/main/resources/META-INF/platform-rust-core.xml, src/223/main/resources/META-INF/platform-rust-core.xml, src/main/resources/META-INF/rust-core.xml
Part of #5632.
MSVC LLDB bundled with 2022.2.2+ builds includes several fixes that make the native Rust support more stable. Since the plugin still supports earlier 222 builds (such as 2022.2.1), this commit only enables it by default in 223 builds.
In general, the native Rust support in MSVC LLDB works as follows:
- when disabled, MSVC LLDB uses Clang-based implementation and treats Rust types and expressions as C++ types and expressions;
- when enabled, MSVC LLDB detects if a PDB file corresponds to Rust source code, and in that case, the new Rust-aware implementation is used to manipulate debug information, types and expressions.
From the user's perspective, the native Rust support in MSVC LLDB currently improves a few things:
- Rust primitive type names are displayed properly, such as …
=> DBG: Enable native Rust support in MSVC LLDB in 2022.3 builds

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystem.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionCachingTest.kt
Continuation of #8977 - now we can handle modification of up to 19 macros (for example, a struct with up to 19 custom derive macros or a deep recursive macro). See #8977 description for more info.
changelog: FIX: Show completion autopopup when typing in a recursive macro call. PERF: Don't enter Dumb Mode when typing in a recursive macros
=> MACRO: do not trigger dumb mode when changing small quantity of macros

src/main/kotlin/org/rust/lang/core/psi/ext/RsQualifiedNamedElement.kt, src/test/kotlin/org/rust/ide/docs/RsExternalDocUrlTest.kt, src/test/kotlin/org/rust/ide/docs/RsResolveLinkTest.kt
Closes #9353
changelog: fix docs.rs documentation hyperlinks for proc macros
=> QDOC: fix doc urls for proc macros

.github/workflows/check.yml, .github/workflows/regressions.yml, .github/workflows/release-branch.yml, .github/workflows/rust-nightly.yml, .github/workflows/rust-release.yml
`::set-output` command is deprecated now. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for details
=> CI: use new syntax to put value into outputs

src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt
Previously, exceptions occurred during fetching were suppressed by accident
It should help in cases like #7912 or #9414 to continue to work instead of breaking the whole analysis with stdlib
changelog: Fallback to hardcoded stdlib structure if fetching of stdlib structure failed for some reason
=> CARGO: fallback to hardcoded stdlib structure if fetching metadata fails

src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/test/kotlin/org/rust/ide/refactoring/RenameTest.kt
This is a fix for #7353
Currently rename adds unnecessary newlines and whitespace for paths in doc links, thus breaking the doc comment
=> Fix rename of paths inside doc links

src/main/kotlin/org/rust/ide/inspections/CargoCommandLineInspectionProjectConfigurator.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTaskListener.kt
Improves #8944
changelog: await finish of macro expansion task when running inspection from [command line](https://www.jetbrains.com/help/idea/command-line-code-inspector.html) or via [Qodana](https://www.jetbrains.com/qodana/)
=> Await macro expansion in `CargoCommandLineInspectionProjectConfigurator`

src/main/kotlin/org/rust/lang/core/psi/RsDefaultValueBuilder.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddStructFieldsFixTest.kt
=> "Add missing fields" quickfix: add trailing comma if needed

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
Previously, the plugin logged only if `cargo check` couldn't be launched at all and ignored all other errors. I made investigation of problems related to building script evaluation difficult.
Now the plugin writes a warning for any failure
=> CARGO: log any failure during build script evaluation

src/main/resources-nightly/META-INF/experiments.xml, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
changelog: Enable [derive](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macros) procedural macro expansion in [nightly plugin builds](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly).
=> MACRO: enable derive proc macro expansion in nightly plugin

src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsFullMacroArgumentCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsTypeAwareCompletionTest.kt
Fixes #9465
Improves completion in the case when the caret is placed in the middle of an identifier like `foo/*caret*bar`.
~Unfortunately, it breaks some tests, e.g. `test no completion for function after extern`. @Kobzol, maybe you could suggest a possible fix of the test?~
changelog: improve completion when the caret is placed in the middle of an identifier
=> COMP: improve completion in the middle of identifier

src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/kotlin/org/rust/ide/utils/import/ImportContext.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt
Related: #7558
I don't rename `QualifiedNamedItem2` since I will refactor it in follow-up PR
=> Rename `ImportCandidatesCollector2` to `ImportCandidatesCollector`

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/inspections/RsDiagnosticBasedInspection.kt, src/main/kotlin/org/rust/lang/core/dfa/borrowck/BorrowChecker.kt, src/main/kotlin/org/rust/lang/core/dfa/liveness/Liveness.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt, src/test/kotlin/org/rust/lang/core/type/RsStubOnlyTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeInferenceCachingTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Fixes #9685, fixes #8150
changelog: fix type inference of const arguments in a path qualifier type arguments
=> Ty: infer const arguments in a path qualifier type arguments

src/223/main/kotlin/org/rust/ide/inspections/import/RsReferenceImporter.kt, src/main/kotlin/org/rust/openapiext/utils.kt
Fixes https://github.com/intellij-rust/intellij-rust/pull/9585#discussion_r1020455833
changelog: Don't create separate undo entry when adding unambiguous import on the fly
=> Don't create separate undo entry when adding unambiguous import

src/main/resources-stable/META-INF/experiments.xml
If you came to this PR because your issue just has been closed, note the plugin including PR will be released only in early December. If you can't wait to try it now, you can use the nightly IntelliJ Rust plugin channel (see [instructions](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-quick-start.html#install-nightly)).
Derive macros support:
Fixes #4629
Fixes #5468
Fixes #5478
Fixes #5728
Fixes #5954
Fixes #6036
Fixes #6489
Fixes #6880
Fixes #7158
Fixes #7848
Fixes #8193
Fixes #8415
Fixes #8581
Fixes #8610
Fixes #8847
Fixes #8856
Fixes #9133
Fixes #9216
Fixes #9226
Fixes #9682
Fixes #7707
Fixes #7365
Fixes #6482
Function-like macros support:
Fixes #4707
Fixes #6367
Fixes #6983
Fixes #7090
Fixes #7242
Fixes #7608
Fixes #7699
Fixes #8049
Fixes #8785
Fixes #9266
changelog: Enable …
=> Enable `function-like` and `derive` proc macro expansion by default

src/main/kotlin/org/rust/ide/intentions/UnElideLifetimesIntention.kt, src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt
Fixes #9734
changelog: Don't offer `Un-elide lifetimes` intention when there is no input lifetimes
=> INT: Don't offer `Un-elide lifetimes` intention when no input lifetimes

src/main/kotlin/org/rust/ide/intentions/NestUseStatementsIntention.kt, src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt
Closes #9284
The intention code is quite hacky, parsing and replacing strings instead of working with proper PSI elements and respecting the code style & formatting. I'm considering reworking it in a different PR, but here I'm following the already used hacks,
changelog: fix nesting of renamed imports
=> INT: fix nesting of renamed imports

gradle.properties
changelog: Make 2022.3 platform default for development
=> GRD: make 2022.3 platform default for development

src/main/kotlin/org/rust/lang/core/psi/ext/RsPatBinding.kt, src/test/kotlin/org/rust/ide/search/RsFindUsagesTest.kt
Now find usages work in such cases:
```rust
macro_rules! foo { ($($ t:tt)*) => { $($ t)* }; }
fn main() {
foo! {
let a = 2;
}     //^ invoke find usages here
let _ = a; // - this should be found
}
```
changelog: fix find usages for variables defined by macros
=> MACRO: fix find usages for pat bindings defined by macros

src/main/kotlin/org/rust/lang/core/macros/RsMacroCallData.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroCallDataWithHash.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt
Now the plugin sets these environment variables when expands a proc macro during completion: `RUST_IDE_PROC_MACRO_COMPLETION=1`
`RUST_IDE_PROC_MACRO_COMPLETION_DUMMY_IDENTIFIER=IntellijIdeaRulezzz`
changelog: Experimentally set `RUST_IDE_PROC_MACRO_COMPLETION` and `RUST_IDE_PROC_MACRO_COMPLETION_DUMMY_IDENTIFIER` environment variables for procedural macro when invoking them during completion. The idea is that authors of proc macros could use these variables and based on them change behavior of the macro to provide a better (possible custom) completion for IDE users
=> MACRO&COMP: let a proc macro know if it is invoked during completion

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/psi/ext/RsPat.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroCallReferenceDelegationTest.kt
Fixes go-to-declaration, highlighting, completion and other features in function-like macros used in the pattern context:
```rust
const X: i32 = 0;
//X
($($ i:tt)*) => { $( $ i )* };
}
fn main() {
match 0 {
foo!(X) => {}
//^ this
_ => {}
}
}
```
changelog: Fixes `Go To Declaration`, highlighting, completion and other features in function-like macros used in the pattern context
=> MACRO: fix `getContext()` for elements expanded from macros in pat ctx

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt
It's a follow-up change to enabling procedural macro support for function-like and derive macros (#9729). Now, `Create New Issue` action doesn't add these features into issue description if they are enabled
=> Mark `org.rust.macros.proc.function-like` and `org.rust.macros.proc.derive` enabled in stable

src/main/kotlin/org/rust/ide/actions/mover/RsLineMover.kt
Closes #9668
changelog: fix move item/statement/etc editor action being incorrectly disabled with some IDE configurations
=> TYPE: fix unavailable move item action

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionTask.kt
This leads to properly removal of stale macro expansion after for performing "Invalidate Caches and Restart" without checking any checkbox
Fixes #9592
=> MACRO: refresh `MacroExpansionFileSystem` after project reopening

src/main/kotlin/org/rust/ide/notifications/NoCargoProjectNotificationProvider.kt
changelog: Don't show `File does not belong to any known Cargo project` warning for scratch files
=> Don't show "File does not belong to Cargo project" for scratch files

src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareResolveTest.kt
Fixes this case:
```rust
mod a {
pub struct X;
pub type Y = X;
impl Y { pub fn foo(&self) {} }
}
mod b {
pub struct X;
pub type Y = X;
impl Y { pub fn foo(&self) {} }
//X
}
mod c {
pub struct X;
pub type Y = X;
impl Y { pub fn foo(&self) {} }
}
fn main() {
b::X.foo();
}      //^
```
Previously, `foo` was unresolved
changelog: fix impl search when there are multiple type aliases with same names
=> TY: fix impl search when there are multiple type aliases with same name

src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/test/kotlin/org/rust/ide/hints/type/RsExpressionTypeProviderTest.kt, testData/test-proc-macros/src/lib.rs
Previously that action has never worked in attr proc macros before. A user always saw the message "Select an expression!":
Now it should work fine.
changelog: Fix `type info` action (`Ctrl`+`Shift`+`P`) inside attribute procedural macro calls
=> Fix `type info` action inside attribute procedural macro calls

src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/tt/MappedSubtree.kt, src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt, src/test/kotlin/org/rust/ide/hints/type/RsExpressionTypeProviderTest.kt
changelog: Improve [Extend selection](https://www.jetbrains.com/idea/guide/tips/extend-selection/) and [Type info](https://www.jetbrains.com/help/idea/viewing-reference-information.html#type-info) actions inside macro calls
=> MACRO: Don't add whitespace between tokens adjacent in macro call body

src/main/kotlin/org/rust/ide/actions/macroExpansion/MacroExpansionViewUtils.kt, src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt, src/main/kotlin/org/rust/lang/core/psi/RsFile.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeMetaInfo.kt, src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsMacroTypeInferenceTest.kt
Previously, this code immediately triggered a stack overflow exception:
```rust
($ i:ident) => { foo!($ i) };
}
fn main() {
let _ = foo!(a);
}
```
=> MACRO: properly limit max depth of im-memory macro expansions

src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitOrImpl.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt, src/test/kotlin/org/rust/lang/core/resolve/RsPathCachingRootTest.kt, src/test/kotlin/org/rust/lang/core/type/RsExpressionTypeInferenceTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Continuation of #9211. Now we resolve nested paths at once in cases like `type T = (Foo, Foo, Foo, Foo, ...)`. Previously, all `Foo`s was resolved independently.
=> PERF: move path caching root to a root type reference

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsSelfConventionInspection.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/inspections/RsInspectionSuppressorTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsSelfConventionInspectionTest.kt
See here for description of attribute: https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention
changelog:
- Respect `#[allow(clippy::wrong_self_convention)]` attribute,
avoiding the need to use `//noinspection RsSelfConvention` anymore
=> Respect #[allow(clippy::wrong_self_convention)]

.github/workflows/check.yml, .github/workflows/get-rust-versions.yml, scripts/update_nightly.py
Historically, we had identical versions of the rust toolchain hardcoded in several places, which complicated their uniformity and automatic updating.  
This PR moves all used versions to one new workflow, and this workflow returns versions in output. 
And small update of nightly-version updater due to the above changes.
=> CI: move used rust version to one place

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/main/kotlin/org/rust/lang/core/CompilerFeature.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPatRange.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsRangeExpr.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/9824.
Closes https://github.com/intellij-rust/intellij-rust/issues/9780.
Includes:
- Annotate half-open ranges patterns as experimental before 1.66
- Annotate inclusive ranges without end for range patterns
- Annotate syntactically invalid range patterns
changelog: Annotate syntactically invalid range patterns / Annotate half-open ranges patterns as experimental before 1.66 / Annotate inclusive ranges without end for range patterns
=> ANN: Annotate range patterns

src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToNamedFieldsProcessor.kt, src/main/kotlin/org/rust/ide/refactoring/convertStruct/RsConvertToTupleProcessor.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToNamedFieldsRefactoringTest.kt, src/test/kotlin/org/rust/ide/refactoring/ConvertToTupleRefactoringTest.kt
Fixes #5851
changelog: Convert `Self` usages in `Convert struct to tuple` refactoring
=> REF: Convert `Self` usages in "Convert struct to tuple" refactoring

src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt, src/main/kotlin/org/rust/ide/navigation/goto/RsTypeDeclarationProvider.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/completion/RsAwaitCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAssocTypeBinding.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsGenericDeclaration.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/core/types/RsPsiTypeImplUtil.kt, src/main/kotlin/org/rust/lang/core/types/Substitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/kotlin/org/rust/lang/core/types/ty/TyProjection.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/RsTypeCheckInspectionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsTypeAwareGenericResolveTest.kt, src/test/kotlin/org/rust/lang/core/type/RsGenericExpressionTypeInferenceTest.kt
Relates to https://github.com/intellij-rust/intellij-rust/issues/6633.
Depends on https://github.com/intellij-rust/intellij-rust/pull/8542.
changelog: Provide initial type inference support for [GATs](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html)
=> TY: Support type inference for GATs

src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsInferenceContextOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve/RsCachedImplItem.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInference.kt, src/test/kotlin/org/rust/lang/core/resolve/RsDoctestInjectionResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsMacroExpansionResolveTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt
Fixes #6164
Note that because of technical limitations `impl`s are accounted only when performing type inference within the same function
changelog: 1. Take into account `impl`s expanded from macro calls inside function bodies. 2. Take into account `impl`s located in doctests
=> TY: take into account `impl`s expanded from macro calls inside function bodies and `impl`s from doctests

src/main/kotlin/org/rust/ide/icons/RsIcons.kt
Closes #9426
The icon rendering (or affine transformation implementation) in AWT is broken: they have tried to special-case ±90° turns (for performance), but ended up with erratic shifts in composed transformations, which lead to jumps of linter icon during its animation. Fortunately, since the gear icon is 6-fold symmetric, we can use only 0, 15, 30 and 45 degrees to reproduce the whole animation correctly.
I have fixed the animation and added a warning to the documentation of `Icon.rotated`.
changelog: fix flickering of external linter icon in the status bar during scans
=> UI: fix erratic jumps of linter icon during scan

src/main/kotlin/org/rust/ide/inspections/lints/RsPathUsageAnalysis.kt, src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
The main changes are:
* Ignore resolving `$crate` (turns out it is slow, probably need to optimize it)
* Fix `RsWithMacrosRecursiveElementWalkingVisitor` - previously in some cases it could traverse (unexpanded) body of attribute macro call
Meta: #2158
changelog: Slightly optimize `Unused imports` inspection
=> INSP: Optimize "Unused imports" inspection

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspection.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
Fixes #9857
changelog: Don't remove unused imports marked with `#[allow(unused_imports)]`
=> Don't remove unused imports marked with `#[allow(unused_imports)]`

src/main/kotlin/org/rust/lang/core/psi/ext/CfgUtils.kt, src/test/kotlin/org/rust/lang/core/psi/RsCodeStatusTest.kt
Fixes #9855
changelog: I don't think it deserves to be included in the changelog, but it fixes issue #9855
=> Fix `CFG_UNKNOWN` vs `ATTR_PROC_MACRO_CALL` code status

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsTypeParamsInExternAnnotatorTest.kt
reference: [implementation in the compiler](https://github.com/rust-lang/rust/blob/30117a1dbb843da1d5ab1258e89a3ed0b1940475/compiler/rustc_hir_analysis/src/check/check.rs#L618)
changelog: Add support for [E0044](https://doc.rust-lang.org/error_codes/E0044.html)
=> INSP: Add support for E0044

src/main/kotlin/org/rust/ide/refactoring/RsImportOptimizer.kt, src/test/kotlin/org/rust/ide/refactoring/RsImportOptimizerTest.kt
Fixes #9316
changelog: Now unused imports are removed inside functions if [corresponding inspection](https://github.com/intellij-rust/intellij-rust/issues/2158) is enabled
=> Remove unused imports inside functions

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/CompilerFeature.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPatRange.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/9873.
changelog: Annotate exclusive range patterns as experimental
=> ANN: Annotate exclusive range patterns as experimental

src/main/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFix.kt, src/test/kotlin/org/rust/ide/annotator/fixes/CreateStructFieldFromConstructorFixTest.kt
Fixes #9651
changelog: Support `Create field` quick-fix for struct literals with `Self`
=> Support "Create field" quick-fix for struct literals with `Self`

src/223/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt, src/main/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionContext.kt, src/main/resources/META-INF/rust-core.xml
I looked into `intellij-community` implementation of author code vision for Kotlin and there don't seem to be any tests (and it would be probably quite complicated to test this), so there are no test here.
Relevant issue: https://github.com/intellij-rust/intellij-rust/issues/9427
changelog: Add support for displaying source control author Code Vision.
=> IDE: add version control author Code Vision

src/main/kotlin/org/rust/ide/inspections/fixes/QualifyPathFix.kt, src/main/kotlin/org/rust/ide/inspections/import/AutoImportFix.kt, src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt, src/test/kotlin/org/rust/ide/typing/paste/RsAddImportOnCopyPasteTest.kt
This is an improvement of https://github.com/intellij-rust/intellij-rust/pull/7597. Changes:
- Fixes proper import of non-trivial paths (like `a::b`).
- Unimportable paths are now fully qualified (if the items are in the same crate).
changelog: Fully qualify paths from the local crate that cannot be imported after paste.
=> IDE: qualify unimportable elements in import after paste

src/main/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFix.kt, src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt, src/main/kotlin/org/rust/ide/refactoring/implementMembers/impl.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFixTest.kt, src/test/kotlin/org/rust/ide/intentions/AddImplTraitIntentionTest.kt
Extracted from #5651 for easier review
This affects `Implement missing supertrait` quick-fix and `Implement trait` intention. Now after the invocation of the action, in the editor the placeholder (e.g. `todo!()`) will be selected
No changelog since this is rather minor change mostly needed for #5651
=> REF: Improve `generateMissingTraitMembers`

src/223/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt, src/223/main/resources/META-INF/platform-rust-core.xml, src/223/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt, src/223/test/kotlin/org/rust/ide/hints/codeVision/RsVcsCodeVisionTestCase.kt, src/main/resources/messages/RsBundle.properties
Inspired by the corresponding Java implementation.
Relevant issue: https://github.com/intellij-rust/intellij-rust/issues/9427
changelog: Add support for showing reference usages Code Vision. Note, these hints are available starting with 2022.3 and are currently disabled by default. You can turn it on via `Registry... | org.rust.code.vision.usage`
=> IDE: add references Code Vision hint

native-helper/src/rustc_wrapper.rs, src/main/kotlin/org/rust/cargo/toolchain/RsToolchainBase.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/project/model/impl/SyncToolWindowTest.kt
Since #9176 the plugin passes `RUSTC_BOOTSTRAP=1` environment variable to `cargo check` call to compiler and run as much as possible during build script evaluation phase (it's experimental feature of cargo that's why we need `RUSTC_BOOTSTRAP=1` here). But this variable also is passed to `rustc` calls launched by cargo during compilation. And it may affect compilation. For example, compilation and evaluation of `thiserror` crate produce different results with different value of `RUSTC_BOOTSTRAP`.
Actually, we don't want to provide `RUSTC_BOOTSTRAP` to `rustc` invocations. So now the plugin stores original value of `RUSTC_BOOTSTRAP` in `INTELLIJ_ORIGINAL_RUSTC_BOOTSTRAP` (if it existed) environment variable and native helper passes it to `rustc`. It allows us to avoid some unexpected …
=> Don't pass `RUSTC_BOOTSTRAP` to rustc during build script evaluation

src/main/kotlin/org/rust/cargo/project/model/CargoProjectActionBase.kt, src/main/kotlin/org/rust/cargo/runconfig/command/RunCargoCommandActionBase.kt, src/main/kotlin/org/rust/ide/actions/CargoEditSettingsAction.kt, src/main/kotlin/org/rust/ide/actions/RsBuildAction.kt, src/main/kotlin/org/rust/ide/actions/RsToolsActionGroup.kt, src/main/kotlin/org/rust/ide/actions/RustfmtCargoProjectAction.kt, src/main/kotlin/org/rust/ide/actions/RustfmtFileAction.kt, src/main/kotlin/org/rust/ide/actions/ShareInPlaygroundAction.kt, src/main/kotlin/org/rust/ide/actions/ToggleExternalLinterOnTheFlyAction.kt, src/main/kotlin/org/rust/ide/actions/diagnostic/CreateNewGithubIssue.kt, src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionActions.kt, src/main/kotlin/org/rust/ide/actions/macroExpansion/RsShowMacroExpansionGroup.kt, src/main/kotlin/org/rust/ide/console/RunRustConsoleAction.kt, src/main/kotlin/org/rust/ide/spelling/RsSpellCheckerGenerateDictionariesAction.kt, src/test/kotlin/org/rust/cargo/commands/RustfmtTest.kt
Also simplify `RustfmtFileAction`. Now it looks for editor using only `AnActionEvent.getData(CommonDataKeys.EDITOR)` (like common refactor action does). More complex search was introduced when Cargo toolwindow contained this action. But it was replaced with `RustfmtCargoProjectAction` action there long ago, so we don't need such complex logic anymore
Fixes #8720
Closes #8752
changelog: Check if any plugin action is available in the current context in background thread to prevent possible UI freezes in some cases
=> ACT: use background thread for Rust action `update`

src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
changelog: Suggest `Elide lifetimes` fix in cases when a function has `fn` pointer parameters
=> INSP: Fix handling fn pointer in `Needless lifetimes`

src/main/kotlin/org/rust/ide/inspections/fixes/ElideLifetimesFix.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
changelog: Suggest `Elide lifetimes` fix in case `self` parameter has reference type like `Box<&Self>`
=> INSP: Fix handling reference-like `self` parameter in `Needless lifetimes`

src/main/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsMainFunctionNotFoundInspectionTest.kt
Previously, the inspection didn't take into account cfg-disabled items as well as items expanded from macros. After this change, it does
Fixes false positive described in #5975 only if `org.rust.macros.proc.attr` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) is enabled
changelog: Properly process top-level items by `Main function not found` inspection. Now it takes into account `cfg` attributes and items expanded from macros. Note, you need to enable attribute macro expansion via `org.rust.macros.proc.attr` [experimental feature](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#experimental-features) to fix false positive `Main function not found` with [rocket](https://rocket.rs/) library
=> INSP: properly process items by `Main function not found`

src/main/kotlin/org/rust/ide/icons/RsIcons.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsForeignModItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/resources/icons/unsafeMark.svg
Mark all icons of unsafe items (including functions in `extern` blocks) with the unsafety marker. This allows to easily see unsafe methods (which are usually avoided) in autocomplete popup and symbol search.
changelog: changed icons for unsafe items, in Structure View and search.
=> UI: add marker to icons of unsafe items

src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/types/Substitution.kt, src/main/kotlin/org/rust/lang/core/types/infer/TyLowering.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt
Examples:
```rust
struct Foo;
struct Bar<A = Foo, B = A>(A, B);
fn foo(a: Bar) {
let b = a.1;
}     //^ must have type `Foo`
```
```rust
struct Bar<const A: usize = 1, const B: usize = A>([i32; A], [i32; B]);
fn foo(a: Bar) {
let b = a.1;
}     //^ must have type `[i32; 1]`
```
Previously these types were inferred incorrectly.
Fixes #9473
changelog: fix default generic arg subst if it refers to another generic param, for example `struct Bar<A = Foo, B = A>`
=> TY: fix default generic arg subst if it refers to another generic param

src/main/kotlin/org/rust/ide/refactoring/move/common/RsMovePathHelper.kt, src/main/kotlin/org/rust/ide/refactoring/move/common/RsMoveUtil.kt, src/main/kotlin/org/rust/ide/typing/paste/RsImportCopyPasteProcessor.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt
Related: #9664
Closes #9768
Fixes performance issue that we can process the same `PsiElement` multiple times.
No changelog since this is the first optimization step before the feature can be enabled by default
=> Optimize `Insert imports on paste`

src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/openapiext/psi.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedImportInspectionTest.kt
Fixes #9915
changelog: Fix resolve of custom macros with the same name as in prelude
=> RES: Fix resolve of custom macros with same name as in prelude

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTabOutTest.kt
Fixes #8948
Fixes #9575
changelog: Fix jumping outside closing bracket/quote with `Tab` when typing
=> COMP: Fix jumping outside closing bracket/quote with Tab when typing

src/test/kotlin/org/rust/ide/lineMarkers/CargoBenchRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoExecutableRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/CargoTestRunLineMarkerContributorTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/LineMarkerTestHelper.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProviderTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsRecursiveCallLineMarkerProviderTest.kt, src/test/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProviderTest.kt, src/test/kotlin/org/rust/ide/navigation/goto/RsGotoImplementationsTest.kt
Interesting that most of line markers providers work with attribute macros because they just ignore the existence of a proc macro attribute (as well as `cfg` attributes)
=> T: add test for line markers (gutter icons) inside attr proc macros

intelliLang/src/test/kotlin/org/rust/ide/intentions/InjectLanguageIntentionTest.kt, src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/ide/injected/RsMacroCallManipulator.kt, src/main/kotlin/org/rust/ide/injected/RsStringLiteralManipulator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMacroCall.kt, src/main/resources/META-INF/rust-core.xml
Fixes #9943
1. It's now possible to use `Inject language or reference` intention to make a language injection into macro invocation body:
https://user-images.githubusercontent.com/3221931/212474368-9172849d-a25c-4a0d-98f1-17f4b0bea447.mp4
2. Plugin developers now can make automatic language injections into some macro invocation bodies.
Example of a language injector that injects JSON language into a macro call that refers to a macro "json" in crate "rs_test":
```kotlin
class RsMacroCallJsonInjector : MultiHostInjector {
override fun elementsToInjectIn(): List<Class<out PsiElement>> =
listOf(RsMacroCall::class.java)
override fun getLanguagesToInject(registrar: MultiHostRegistrar, context: PsiElement) {
if (context !is RsMacroCall || !context.isValidHost) return
val macroArgumentRange = …
```
=> LI: allow injecting languages into macro calls

src/main/kotlin/org/rust/ide/structure/RsNavBarModelExtension.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAbstractable.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsConstant.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTypeAlias.kt, src/main/kotlin/org/rust/lang/core/stubs/StubIndexing.kt
Fixes #10011
The bug was initially introduced by #6581. It seems like a default navbar implementation retrieves an icon for a PSI element from EDT without a cancellable progress indicator. At the same time, `getIcon()` implementations of PSI element that can be trait/impl members (function, constant, type alias) access a `DefMap` of their crate in order to handle a specific case where an item is inside a file included to a trait/impl body via include macro (and hence such item should have icon marks about being trait/impl members). Accessing `DefMap` without a cancellable progress may lead to a UI freeze for the duration of `DefMap` building.
I decided to ignore this specific case and don't use such icons marker in the navbar in the case of a included file. This fixes the freeze. …
=> Fix a UI freeze caused by navbar

src/main/kotlin/org/rust/ide/actions/ui/CargoNewCrateDialog.kt, src/main/kotlin/org/rust/ide/newProject/ui/AddUserTemplateDialog.kt, src/main/kotlin/org/rust/openapiext/ui.kt
Fixes #9968.
changelog: Trim template name and URL when creating a new project using a [custom cargo-generate template](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-new-cargo-projects.html#cargo-generate)
=> PRJ: Trim template name and URL when creating new project

src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Fixes #10020
No changelog since it is hotfix for #9842
=> INSP: Fix handling Fn trait with path lifetimes in `Needless lifetimes`

src/main/kotlin/org/rust/ide/annotator/AnnotationSessionEx.kt, src/main/kotlin/org/rust/ide/annotator/RsAttrHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsHighlightingAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/main/kotlin/org/rust/lang/core/psi/AttrCache.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt
Previously we highlighted macro expansion and then mapped annotations to a macro call body. It was slow due to several reasons:
1. macro expansions are usually larger than macro calls (in terms of tokens);
2. In general, Annotators are more lazy - they first highlight a visible part of the code and then the rest of the file. On the opposite, `RsMacroExpansionHighlightingPass` is not lazy - it highlights the entire file and only then shows highlighting.
Now we do the same for most of the annotators except `RsHighlightingAnnotator` which now uses a reverse approach - it maps a token from a macro call to a macro expansion and then figures out how they should be highlighted there.
=> PERF: speed up syntax highlighting in macro calls

src/main/kotlin/org/rust/ide/icons/RsIcons.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsImplItem.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/resources/icons/unsafeMark.svg
Reverts #9802.
#9802 was accidentally merged without a proper discussion with the rest of the IntelliJ Rust team. @afetisov, we're sorry for that.
After the discussion we came to the conclusion that we have complaints about this design and decided to revert the PR.
1. The icon looks similar to a well-known warning sign, which can make users think something is wrong somewhere.
2. The new UI does not use icon marks at all, so we will likely drop all the marks in the new UI in the future.
But note that I think highlighting unsafe items is very important at least in the completion list, so we just need to come up with a better UI solution. This can be not only playing with icons, but also playing with text style and in general with `LookupElementPresentation`. I'll try to ask JetBrains' UX …
=> Revert "UI: add marker to icons of unsafe items"

README.md
Hi! I added links to the IJ Rust features listed in the table in readme.txt. @Undin  Please take a look.
I also mentioned IJ-based IDEs in the footnote. Is it ok? I think, when it comes to footnotes, we really must be precise.
Once we merge this, I'll update the Marketplace docs accordingly.
changelog: Added links to docs for IJ Rust features in readme.txt.
=> Added links to docs for IJ Rust features in readme.txt

src/main/kotlin/org/rust/ide/settings/RsAutoImportOptions.kt, src/main/kotlin/org/rust/ide/settings/RsCodeInsightSettings.kt, src/main/kotlin/org/rust/ide/settings/RsPathsExcludeTable.kt, src/main/kotlin/org/rust/ide/settings/RsProjectCodeInsightSettings.kt, src/main/kotlin/org/rust/ide/utils/import/ImportCandidatesCollector.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/WithExcludedPaths.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixStdTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsStdlibCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsTraitMethodCompletionTest.kt
Fixes #5805
Fixes #8044
Fixes #8971
Fixes #9099
Fixes #9157
Added option to exclude specific paths from auto-import and completion. By default `std::borrow::Borrow`, `core::panicking` and `std::intrinsics::unreachable` are excluded
There are two types of exclusions:
* `Only methods` - used for `std::borrow::Borrow`, it will exclude methods of the trait from auto-import, but the trait itself can be imported
* `Always` - will exclude both methods (if item is trait) and item itself
changelog: Allow to exclude specific paths from auto-import
=> Allow to exclude specific paths from auto-import

src/main/kotlin/org/rust/ide/inspections/RsWrongLifetimeParametersNumberInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsWrongLifetimeParametersNumberTest.kt
Fixes #2767
changelog: Annotate missing lifetimes in function signature
=> INSP: Annotate missing lifetimes in function signature

js/src/main/kotlin/org/rust/js/RsWasmBindgenLineMarkerProvider.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsCrateDocLineMarkerProvider.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsImplsLineMarkerProvider.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsRecursiveCallLineMarkerProvider.kt, src/main/kotlin/org/rust/ide/lineMarkers/RsTraitItemImplLineMarkerProvider.kt, src/main/resources/messages/RsBundle.properties, toml/src/main/kotlin/org/rust/toml/CargoCrateDocLineMarkerProvider.kt
Now, it's possible to enable/disable line markers provided Rust plugin via `Preferences | Editor | General | Gutter Icons` settings
Fixes #10036
Note, because of [platform bug](https://youtrack.jetbrains.com/issue/IDEA-311515), IDE may show several groups with the same name. For Rust line markers as well. It's already fixed in the platform master and will be landed with 2023.1 EAP 3
Note 2: I intentionally didn't add option for gutter icons in Cargo.toml to change Cargo feature state (`CargoFeatureLineMarkerProvider`) since it's an essential feature of the plugin, from my point of view. I consider it doesn't make sense to allow users to disable it. Otherwise, it would be impossible to change the state of Cargo features
changelog: Add a way to disable gutter icons provided by the plugin …
=> Provide options for Rust line markers

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, prettyPrinters/rust_types.py, pretty_printers_tests/tests/slice.rs
Fixes #9961.
In addition to `&[T]` and `&mut [T]` types, LLDB and GDB pretty-printers now render `*const [T]` and `*mut [T]` types on any supported OS.
Note, `mut slice<T>` is now excluded from `STD_MSVC_SLICE_REGEX` because rustc 1.56+ (IntelliJ Rust minimal supported Rust version) does not emit it anymore.
changelog: Show the contents of raw slice pointers (`*const [T]`, `*mut [T]`) in the debugger
=> #9961: Support raw slice pointers in debugger pretty-printers

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInForeignFunctionTest.kt, src/test/kotlin/org/rust/ide/annotator/RsPatternArgumentInFunctionWithoutBodyTest.kt, src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
changelog:
Add support for E0130, and E0642.
Replace the old code for E0642, since it catches only tuple destructions and doesn't consider whether a function has a body or not:
```[rust]
denyType<RsPatTup>(param.pat, holder, "${fn.title} cannot have tuple parameters", param)
```
This approach might lead to a false positive, for example, the next code compiles, but we got an error from IDE: 
```
trait Foo {
fn baz((a, b): (i32, i32)) {}
}
```
E0130 reference: https://doc.rust-lang.org/error_codes/E0130.html
E0642 reference: https://doc.rust-lang.org/beta/error_codes/E0642.html
Compiler reference: https://github.com/rust-lang/rust/blob/30117a1dbb843da1d5ab1258e89a3ed0b1940475/compiler/rustc_ast_passes/src/ast_validation.rs#L1471
=> ANN: Add support for E0130, E0642

.github/workflows/check.yml
It uses Node.js 16 instead of deprecated Node.js 12
=> CI: use `actions/checkout@v3` instead of `v2`

src/main/kotlin/org/rust/ide/inspections/lints/RsLivenessInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsLivenessInspectionTest.kt
Fixes #9733
changelog: Don't suggest to remove unused parameter in trait methods and procedural macro definitions
=> Don't suggest removing unused parameter in trait methods and proc macros

debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSteppingSettingsConfigurableUi.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsStepFilterSettings.kt, debugger/src/main/resources/messages/RsDebuggerBundle.properties
This PR adds an option to not step into stdlib sources. In the future, it could be extended with a table for adding custom paths to be ignored (like what e.g. Python offers).
Currently, it doesn't work inside LLDB, because it does not use full paths for functions (e.g. `Vec::clear` is `example_project'clear<i32,alloc::alloc::Global>` instead of `alloc::vec::Vec::clear`). @ortem Do you have an idea how this could be fixed?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/4764
https://user-images.githubusercontent.com/4854600/216394673-4292c396-1dd3-4531-b608-368cd592c8ad.mov
For QA: this feature is supposed to work
* with GDB on Linux and Windows
* with LLDB on macOS and Linux since CLion 2023.1 EAP 231.6471.1
* with MSVC LLDB on Windows
changelog: Add debugger option to not …
=> DBG: add option to not step into stdlib sources

.github/workflows/get-rust-versions.yml, debugger/src/main/antlr/RsTypeName.g4, debugger/src/main/kotlin/org/rust/debugger/lang/RsMSVCTypeNameDecoratorVisitor.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, debugger/src/test/kotlin/org/rust/debugger/lang/RsFrameTypeDecoratorTest.kt, debugger/src/test/kotlin/org/rust/debugger/lang/RsTypeNameParserTest.kt, prettyPrinters/lldb_lookup.py, prettyPrinters/rust_types.py, pretty_printers_tests/tests/string.rs
Depends on #9962.
Fixes #7935.
Fixes #9769.
changelog: Update debugger pretty-printers and type name decorators for MSVC to Rust 1.67. Now the debugger renders `str` and slice types properly
=> DBG: Update MSVC pretty-printers and type name decorators to Rust 1.67

src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/ItemResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/main/kotlin/org/rust/lang/core/resolve/RsPathResolveResult.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsMethodCallReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/test/kotlin/org/rust/lang/core/completion/RsLookupElementTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsConstArgumentResolveTest.kt
Fixes #9878
Also slightly speeds up name resolution because of less calls to `RsNamedElement.namespaces`
=> RES: fix namespace shadowing for a path in a type argument position

src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt
Related: #5989
changelog: Skip expansion of cfg-disabled macro calls inside functions
=> PERF: Don't expand cfg-disabled macro calls inside functions

src/main/kotlin/org/rust/ide/annotator/fixes/AddTypeFix.kt, src/main/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddAssocTypeBindingsFix.kt, src/main/kotlin/org/rust/ide/inspections/fixes/AddGenericArguments.kt, src/main/kotlin/org/rust/ide/inspections/fixes/InitializeWithDefaultValueFix.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspection.kt, src/main/kotlin/org/rust/ide/intentions/AddImplTraitIntention.kt, src/main/kotlin/org/rust/ide/intentions/ConvertClosureToFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/DestructureIntention.kt, src/main/kotlin/org/rust/ide/intentions/ImplTraitToTypeParamIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateFunctionIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateStructIntention.kt, src/main/kotlin/org/rust/ide/intentions/createFromUsage/CreateTupleStructIntention.kt, src/main/kotlin/org/rust/ide/template/postfix/MatchPostfixTemplate.kt, src/main/kotlin/org/rust/ide/template/postfix/WrapTypePathPostfixTemplate.kt, src/main/kotlin/org/rust/ide/typing/paste/RsConvertJsonToStructCopyPasteProcessor.kt, src/main/kotlin/org/rust/ide/utils/StructFieldsExpander.kt, src/main/kotlin/org/rust/ide/utils/template/EditorExt.kt, src/main/kotlin/org/rust/ide/utils/template/RsTemplateBuilder.kt, src/main/kotlin/org/rust/lang/core/completion/RsImplTraitMemberCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsLambdaExprCompletionProvider.kt
This slightly simplifies `RsTemplateBuilder`. Now it's not needed to wrap all PSI elements being replaced with pointers (but elements used in a callback still have to be wrapped). But the real motivation for these changes is preparing for intentions & quick-fixes inside macros.
changelog: Slightly simplifiy `RsTemplateBuilder` API
=> CLEAN: simplify `RsTemplateBuilder` API

src/main/kotlin/org/rust/ide/console/RsConsoleCodeFragmentContext.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsDeriveCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemElement.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Continuation of #9879
Replace most of the lambda-based `RsResolveProcessorBase` implementation to named classes
=> Refactor resolve processors more

src/main/kotlin/org/rust/lang/core/completion/RsAttributeCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsAttributeCompletionTest.kt
Fixes #10058
changelog: Don't complete built-in attributes for qualified path
=> COMP: Don't complete built-in attributes for qualified path

src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt, src/main/kotlin/org/rust/lang/core/macros/RangeMap.kt, src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt, src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsTestBase.kt
Fixes #8214
Fixes #8374
Related: #9803
Depends on #10095
Add type hints inside function-like macro calls:
changelog: Show type hints inside macro calls
=> HINT: Show type hints inside macro calls

src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt
Fixes #10109
Related: #10014
no changelog since the exception should not be visible to users
=> Fix IndexNotReadyException in NavBar

src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt
Fixes #10015
`tokio::test` resolves to either `tokio_macros::test` or `tokio_macros::test_rt` depending on tokio features enabled (`rt-multi-thread` vs `rt`). Cause of the original issue was that we do expand `tokio_macros::test_rt` to invocation of `std::prelude::v1::test` macro which probably also should be treated as identity.
changelog: Fix handling of attribute macro `tokio::test` in some cases
=> Add `tokio_macros::test_rt` to list of hardcoded macros

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/psi/RsStability.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsDocAndAttributeOwner.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt
Fixes #8836, fixes #4437, 
changelog: Don't show unstable stdlib items in completion list when using stable or beta Rust compiler
=> COMP: don't complete unstable stdlib items when on stable or beta

src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt
This should not affect users. In theory this could improve performance, but very slightly
=> RES: Skip lambda argument processing when walking upward from arg list

src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/tt/MappedSubtree.kt, src/main/kotlin/org/rust/lang/core/macros/tt/TokenTreeParser.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt, testData/test-proc-macros/src/lib.rs
`syn`-based procedural macros tend to discard spans (token ids) from `TokenTree.Leaf.Punct` tokens and subtree `Delimiter`s. In this PR I introduce a routine that tries to recover them using a simple heuristic: if a token without a mapping (with id == -1) follows a token *with* a mapping, then it most likely should be mapped with the next token in the source. The only thing should be checked is that its type and text is equal to the token in the source.
This is mostly needed to improve error highlighting in attribute procedural macros (#10037) and for intention actions and quick fixes in macros
=> MACRO: recover PUNCT and delimiter token mappings discarded by a proc macro

attributes-info/Cargo.lock, attributes-info/rustc_feature/Cargo.toml
Mostly to fix GitHub security alerts. From a user point of view, it changes nothing since this package is used only to generate list of compiler features during plugin building
=> Update dependencies for `attributes-info` package

src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsNonShorthandFieldPatternsInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsRedundantSemicolonsInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsSelfConventionInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnknownCrateTypesInspection.kt
#6013 introduces the concept of `syntax-only` inspections - lightweight inspections which don't require resolve and can be run on detached files (files outside valid rust project). But some inspections was marked `syntax-only` by a mistake. Currently, all `RsLintInspection` are considered `syntax-only`, but actually some of them use name resolution (e.g. `RsUnusedImportInspection`). This PR makes the following inspections **not** `syntax-only`, so they will not be run on detached files:
* `RsBareTraitObjectsInspection`
* `RsDeprecationInspection`
* `RsDoubleMustUseInspection`
* `RsLivenessInspection`
* `RsNeedlessLifetimesInspection`
* `RsUnnecessaryQualificationsInspection`
* `RsUnreachableCodeInspection`
* `RsUnreachablePatternsInspection`
* `RsUnusedImportInspection`
* …
=> Do not run inspections which uses resolve on files outside valid project

src/main/kotlin/org/rust/ide/inspections/RsTraitImplementationInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitItem.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/RsTraitImplementationInspectionTest.kt, src/test/kotlin/org/rust/lang/core/ext/RsPsiStructureTest.kt
changelog: Annotate mismatched members in trait impl ([E0323](https://doc.rust-lang.org/error_codes/E0323.html), [E0324](https://doc.rust-lang.org/error_codes/E0324.html), [E0325](https://doc.rust-lang.org/error_codes/E0325.html))
=> INSP: Annotate mismatched members in trait impl (E0323, E0324, E0325)

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotatorTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/10129
changelog: Highlight that `_` can only be used on the left-hand side of an assignment
=> ANN: Highlight that `_` can only be used on the left-hand side of an assignment

src/main/kotlin/org/rust/lang/core/dfa/CFGBuilder.kt, src/main/kotlin/org/rust/lang/core/dfa/ExprUseWalker.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnreachableCodeInspectionTest.kt, src/test/kotlin/org/rust/lang/core/dfa/RsControlFlowGraphTest.kt
fix: #9681 (cc: @ortem)
Follow-up for #7798
This pull request addresses issue #9681 by correctly handling the else block of let-else statements in the construction of the ControlFlowGraph.
Due to issues with my environment, not all tests could be executed. I apologize if any failures occurred.
changelog: Fix false-positive detection of unreachable code with [`let else`](https://rust-lang.github.io/rfcs/3137-let-else.html) syntax
=> support let-else statement for CFG

pretty_printers_tests/Settings_linux.toml, pretty_printers_tests/Settings_macos.toml, pretty_printers_tests/Settings_windows.toml, pretty_printers_tests/src/main.rs, pretty_printers_tests/src/test_runner.rs, pretty_printers_tests/tests/cell.rs, pretty_printers_tests/tests/ffi_strings.rs, pretty_printers_tests/tests/hash_map.rs, pretty_printers_tests/tests/nonzero.rs, pretty_printers_tests/tests/range.rs, pretty_printers_tests/tests/rc_arc.rs, pretty_printers_tests/tests/slice.rs, pretty_printers_tests/tests/string.rs, pretty_printers_tests/tests/tuple.rs, pretty_printers_tests/tests/vec.rs, pretty_printers_tests/tests/vec_deque.rs
Previously, the pretty-printers tests only checked how the variables' values were rendered. Now, pretty-printers tests for LLDB also check the variables' types according to the debugger. This aims to help us catch specific changes in the Rust debug information that can break pretty-printers and MSVC type decorators.
Currently, the pretty-printers test runner cannot check the output depending on the Rust version, so the types that have different names on Rust stable and Rust nightly are not being checked yet (`[...]` wildcard is used instead).
In addition, now the LLDB pretty-printers tests use `frame variable` command instead of the previously used `print` command. This allows removing Windows-specific checks written only because `print` outputs an index instead of a variable name.
=> T: Check type names in pretty-printers tests

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/main/kotlin/org/rust/ide/inspections/RsWithMacrosInspectionVisitor.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/main/kotlin/org/rust/lang/core/macros/RsMacroDataWithHash.kt, src/main/kotlin/org/rust/lang/core/psi/AttrCache.kt, src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt, src/main/kotlin/org/rust/lang/core/psi/ProcMacroAttribute.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsAttrProcMacroOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsItemsOwner.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMembers.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsPossibleMacroCall.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/kotlin/org/rust/lang/core/resolve2/CrateDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/DefCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeBuildDefMap.kt, src/main/kotlin/org/rust/lang/core/resolve2/FacadeResolve.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollector.kt, src/main/kotlin/org/rust/lang/core/resolve2/ModCollectorBase.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionRangeMappingTest.kt, src/test/kotlin/org/rust/lang/core/macros/RsMacroExpansionTestBase.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsProcMacroExpansionResolveTest.kt, testData/test-proc-macros/src/lib.rs
We have [a hardcoded list of attribute macros](https://github.com/intellij-rust/intellij-rust/blob/97f47d412d72801dbdaa7f2f769e5ca699804313/src/main/kotlin/org/rust/lang/core/psi/HardcodedProcMacroProperties.kt#L16) that the plugin does not expand. This list usually contains macros that does not make sense to expand because they do almost nothing from the IDE perspective and so can be treated as built-in attributes.
Rust allows to apply several attribute macros to an item. In this case, they are applied sequentially.
It is possible that one of the macros macros is present in our hardcoded list, but another is not. In this case, currently there is a bug - the plugin will not expand both of the macros. This PR changes this behavior. Now if any of the macros should be expanded, the plugin …
=> RES: Improve support for identity attribute proc macros

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/fixes/AddModuleFileFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt, src/test/kotlin/org/rust/ide/annotator/RsAnnotationTestBase.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddMissingSupertraitImplFixTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ChangeFunctionSignatureFixTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/DoctestFixTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/FillFunctionArgumentsFixTest.kt, src/test/kotlin/org/rust/ide/annotator/fixes/RemoveFunctionArgumentFixTest.kt
Use it for `AddMissingSupertraitImplFix`, `ChangeFunctionSignatureFix`, `FillFunctionArgumentsFix`, `RemoveRedundantFunctionArgumentsFix` quick-fixes (E0277, E0060, E0061, E0057 errors).
Previously these we registered multiple annotations for the same error in order to adjust a quick fix availability range: one annotation with error message and text attributes and one silent annotation without an error message (but with a quick fix). This resulted to fun bugs, for example blank lines after a batch inspection run:
(actually it's not some special blank line, it is an error annotation without a message)
The platform is actually allows to adjust availability range of a quick fix, so there's no reason to add an extra annotation.
changelog: (i'm not sure it worth to add it to a changelog) …
=> ANN: add `RsDiagnostic`-based API for quick-fixes with arbitrary ranges

src/main/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHints.kt, src/main/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProvider.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsInlayParameterHintsProviderTest.kt, src/test/kotlin/org/rust/ide/hints/type/RsChainMethodTypeHintsProviderTest.kt
changelog: Show parameter hints inside attribute procedural macros
=> HINT: Show parameter hints in attribute procedural macros

src/main/kotlin/org/rust/ide/intentions/InvertIfIntention.kt, src/test/kotlin/org/rust/ide/intentions/InvertIfIntentionTest.kt
Fixes #10251
changelog: Fix `Invert if condition` intention when there is another `if` after current one
=> INT: Fix `StackOverflowError` in `Invert if condition` intention

intelliLang/src/test/kotlin/org/rust/ide/intentions/InjectLanguageIntentionTest.kt, src/main/kotlin/org/rust/cargo/project/workspace/CargoWorkspace.kt, src/test/kotlin/org/rust/RsJUnit4ParameterizedTestRunner.kt, src/test/kotlin/org/rust/RsJUnit4TestRunner.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/SkipTestWrapping.kt, src/test/kotlin/org/rust/TestWrapping.kt, src/test/kotlin/org/rust/ide/intentions/AddImportForPatternIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/AddImportIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/ConvertMethodCallToUFCSIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/CreateFunctionIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/ExtractInlineModuleIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/FlattenUseStatementsIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/NestUseStatementsIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/RemoveDbgIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt, src/test/kotlin/org/rust/ide/intentions/RsShowMacroExpansionIntentionBaseTest.kt, src/test/kotlin/org/rust/ide/intentions/ShareInPlaygroundIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/UnElideLifetimesIntentionTest.kt, src/test/kotlin/org/rust/ide/previewUtils.kt, toml/src/test/kotlin/org/rust/toml/intentions/CargoTomlIntentionTestBase.kt
Set up tests for an intention action inside an attr proc macro using JUnit4 parameterized tests. 
The idea is that we have many tests for intention actions, and we can re-use them in the context of a macro call. I've called this approach "test wrapping".
Since now, every intention action test (in descendants of `RsIntentionTestBase` class) will run twice - first time without wrapping (as before), and second one with "wrapping":
"wrapped with `#[attr_as_is]` macro" (see the screenshot) means that we run basically the same test, but it's code sample is slightly modified to become a macro invocation, that is, "wrapped" inside a macro invocation of `#[attr_as_is]` macro.
For example, the test `AddRemainingArmsIntentionTest.test empty match`:
```rust
enum E { A, B, C }
fn main() {
let a = …
```
=> T: set up tests for an intention action inside an attribute macro

src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
Show E0133 when accessing union field outside unsafe block
=> ANN: Show E0133 when accessing union field outside unsafe block

src/main/kotlin/org/rust/ide/annotator/RsExpressionAnnotator.kt, src/main/kotlin/org/rust/ide/fixes/RemoveStructLiteralFieldFix.kt, src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsExpressionAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsUnionExprWithWrongFieldCountTest.kt
changelog: Improve support for [E0784](https://doc.rust-lang.org/error_codes/E0784.html) ("A union expression does not have exactly one field.")
=> ANN: Improve E0784 (union expr does not have exactly one field)

clion/src/main/kotlin/org/rust/clion/cargo/CargoCleanTaskRunner.kt, clion/src/main/resources/org.rust.clion.xml, src/main/kotlin/org/rust/cargo/runconfig/Utils.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Rustfmt.kt
Now `Rebuild` actions run `cargo clean` for the corresponding cargo project before build and `Clean` action just runs `cargo clean` for all cargo projects.
changelog:  Support `Rebuild ...` and `Clean` actions
=> RUN: Support `Rebuild ...` and `Clean` actions

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/main/kotlin/org/rust/ide/fixes/RemovePolyBoundFix.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsTooManyLifetimeBoundsOnTraitObjectTest.kt
changelog: Add support for [E0226](https://doc.rust-lang.org/error_codes/E0226.html) ("More than one explicit lifetime bound was used on a trait object.")
=> ANN: Add E0226: Too many lifetime bounds on traitobj

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedLabelsInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsUnusedLabels.html, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedLabelsInspectionTest.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/9374 (_"RES: Fix nested labels shadowing"_)
Part of #5888 (_"Compiler lints support"_)
changelog: Add [labels](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#unused-labels) inspection and quick-fixes for it
=> INSP: Add unused_labels warning and fix

src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/psi/RsTokenType.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/macros/tt/TokenTreeParserTest.kt
Fixes #10296
Rust currently has 9 reserved keywords - `abstract`, `become`, `do`, `final`, `override`, `priv`, `typeof`, `unsized` and `virtual`. Each reserved keyword token must be parsed as an identifier when passed to a declarative or procedural macro.
Declarative macro example:
```rust
($i:ident) => { fn foo () { let _ = stringify!($i); }};
}
foo!(final);
```
Previously, the plugin couldn't expand the macro:
You can find example with a proc macro in #10296.
changelog: Fix expansion of macros that contain reserved keywords (e.g. `do`) in their body
=> MACRO: parse reserved keywords as identifiers in macro matching

.github/workflows/release-branch.yml, scripts/make_next_milestone.py, scripts/make_release_branch.py, scripts/release_managers_common.py
TODO:
Add secrets in this repo ✅ 
Set up workflow on the Slack side  (it sends in my private channel now) ✅ 
Possible TODO:
Check that the release branch exists. (In the current workflow, the message won't be sent if previous steps failed, but who knows...) 
Set up a notification if branch creation fails. 
other ideas?
Example:
=> CI: add Slack notification about release branch

.idea/inspectionProfiles/intellij_rust.xml
Add an internal Kotlin inspection for IntelliJ Rust developers (based on [Structural Search and Replace](https://www.jetbrains.com/help/idea/creating-custom-inspections.html)). The inspection warns about anonymous LocalQuickFix class implementations (`object : LocalQuickFix {}`):
Anonymous LocalQuickFix creates the risk of accidentally capturing a variable, so it's better to use a named non-inner class instead.
The SSR template:
=> Add internal SSR inspection that finds anonymous LocalQuickFix classes

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsNestedQuantificationOfLifetimeBoundsTest.kt
changelog: Add support for [E0316](https://doc.rust-lang.org/error_codes/E0316.html) ("A where clause contains a nested quantification over lifetimes")
=> ANN: Add E0316 "nested quantification over lifetimes"

src/main/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsDialog.kt, src/test/kotlin/org/rust/ide/refactoring/move/RsMoveTopLevelItemsTest.kt
Fixes #10297
changelog: Don't add mod declaration for crate root if it was created by move refactoring (`Refactor | Move` or <kbd>F6</kbd>)
=> REF: Don't add mod declaration for crate root in move refactoring

src/main/kotlin/org/rust/ide/refactoring/extractTrait/RsExtractTraitHandler.kt
Fixes possible flaky `RsExtractTraitBaseTest` test ([example](https://github.com/intellij-rust/intellij-rust/actions/runs/4617099684/jobs/8163087816?pr=10311))
=> T: Don't use `RsExtractTraitDialog` in tests

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsPathStatementsInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsPathStatements.html, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/inspections/lints/RsPathStatementsInspectionTest.kt
Based on https://github.com/rust-lang/rust/blob/1f12ac872/compiler/rustc_lint/src/unused.rs#L328-L377
Part of #5888 (_"Compiler lints support"_)
The inspection is disabled by default because of #9555.
=> INSP: Add path_statements warning and fix

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsTraitRef.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
changelog:
-  add support for [E0183](https://doc.rust-lang.org/error_codes/E0183.html)
- show experimental features errors:
- The precise format of `Fn`-family traits' type parameters is subject to change
- Parenthetical notation is only stable when used with `Fn`-family traits
=> ANN: Support for E0183, fn* traits related experimental features errors

toml/src/main/kotlin/org/rust/toml/RsTomlBundle.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexUpdater.kt, toml/src/main/kotlin/org/rust/toml/crates/local/CratesLocalIndexWaker.kt, toml/src/main/resources/messages/RsTomlBundle.properties, toml/src/main/resources/org.rust.toml.xml, toml/src/test/kotlin/org/rust/toml/crates/local/CratesLocalIndexServiceTest.kt
Starting with 1.68, cargo stabilized [sparse](https://doc.rust-lang.org/cargo/reference/registries.html#registry-protocols) protocol to reduce the duration of fetching info about external dependencies.
Unfortunately, the new API doesn't allow getting the whole index. As a result, the plugin may fail to build crates index for crates completion/annotation in Cargo.toml configs
These changes introduce `CratesLocalIndexUpdater` service that is supposed to force cargo to update old git crate index periodically and eventually, update plugin's crate index
Under the hood, the service just creates the simplest Cargo project and forces cargo to update crates registry it using `git` protocol
Fixes #10199
Fixes #10060
This is a workaround (not sure if it is temporary) for #10267
changelog: Provide …
=> CARGO: fix building local crate index

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterPass.kt, src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/main/kotlin/org/rust/ide/inspections/RsExternalLinterInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsLintInspection.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt
Closes https://github.com/intellij-rust/intellij-rust/issues/8794.
changelog: Provide lint-based suppress quick-fixes for external linter annotations
=> ANN: Provide lint-based suppress quick-fixes for external linter annotations

debugger/src/main/kotlin/org/rust/debugger/RustcNatvisFileProvider.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurationHelper.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugProcessConfigurator.kt, debugger/src/main/resources/org.rust.debugger.xml
Now, when using MSVC toolchain on Windows, the plugin searches for NatVis files in `$sysroot/lib/rustlib/etc` directory and loads them when:
1. `Enable NatVis renderers for LLDB` is set in `Data Views | C/C++` (enabled by default);
2. `LLDB renderers` option is set to "Rust compiler's renderers";
3. Experimental Rust MSVC support in LLDB is disabled manually.
Note, if only (2) is met, the plugin now does not load any pretty-printers since the MSVC toolchain does not provide regular Python pretty-printers. Previously, the plugin was wrongly trying to load the missing Python pretty-printers.
Also note that (3) is required because NatVis renderers heavily use C++ syntax, which conflicts with the Rust parser used by MSVC LLDB inside Rust frames when experimental Rust MSVC support is enabled. …
=> DBG: Allow loading NatVis files from Rust MSVC toolchain on Windows

src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionConfig.kt, src/main/kotlin/org/rust/ide/refactoring/extractFunction/RsExtractFunctionHandler.kt, src/main/kotlin/org/rust/ide/surroundWith/utils.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsLambdaExpr.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsStmt.kt, src/test/kotlin/org/rust/FileTree.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt
Here is an overview of supported control flow and how refactoring works with them:
| Extracted control-flow       | Extracted type | Resulted return type         | Resulted invocation                                     |
|------------------------------|----------------|------------------------------|---------------------------------------------------------|
| None                         | stmt           | `()`                         | `f();`                                                  |
| None                         | expr           | `T`                          | `let x = f();`                                          |
| return/break/continue   | stmt           | `bool`                       | `if f() return;`                                        |
| return/break/continue …
=> REF: Support control flow in `Extract function` refactoring

src/main/kotlin/org/rust/cargo/runconfig/CargoCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/CargoTestCommandRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/RsExecutableRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildManager.kt, src/main/kotlin/org/rust/cargo/runconfig/buildtool/RsBuildEventsConverter.kt, src/main/kotlin/org/rust/cargo/runconfig/command/CargoCommandConfiguration.kt, src/main/kotlin/org/rust/cargo/runconfig/legacy/RsAsyncRunner.kt, src/main/kotlin/org/rust/cargo/runconfig/test/CargoTestEventsConverter.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/cargo/util/CargoArgsParser.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/RunConfigurationTestBase.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestNodeInfoTest.kt, src/test/kotlin/org/rustSlowTests/cargo/runconfig/test/CargoTestRunnerTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/8878.
https://youtrack.jetbrains.com/issue/CPP-30242/Profiling-Support-for-Rust-cargo-bench-profile-dev
Note: default bench profile doesn't contain debug info. You have to use, for example, dev profile (add `--profile=dev` to your command).
changelog: Enable Debugger, Profiler, Valgrind, Code Coverage, and Build/Test tool windows for `bench` command
=> RUN: Enable Debugger, Profiler, Valgrind, Code Coverage, and Build/Test tool windows for `bench` command

src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsExpressionTypeProvider.kt, src/main/kotlin/org/rust/ide/hints/type/RsTypeHintsPresentationFactory.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/ide/presentation/TypeRendering.kt, src/main/kotlin/org/rust/ide/utils/import/RsImportHelper.kt, src/main/kotlin/org/rust/lang/core/types/ty/Ty.kt, src/test/kotlin/org/rust/ide/docs/RsQuickDocumentationTest.kt, src/test/kotlin/org/rust/ide/hints/type/RsInlayTypeHintsProviderTest.kt, src/test/kotlin/org/rust/ide/refactoring/RsExtractFunctionTest.kt, src/test/kotlin/org/rust/ide/refactoring/implementMembers/ImplementMembersHandlerTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypeResolvingTest.kt, src/test/kotlin/org/rust/lang/core/type/RsTypificationTestBase.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/6943.
Depends on https://github.com/intellij-rust/intellij-rust/pull/8144 and https://github.com/intellij-rust/intellij-rust/pull/8145.
changelog: Render const generics in quick docs and inline hints
=> UI: Render const generics in quick docs and inline hints

src/main/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsNeedlessLifetimesInspectionTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/9210.
changelog: Fix `Needless lifetimes` inspection in case of async functions
=> INSP: Fix `Needless lifetimes` inspection in case of async fn

src/main/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessor.kt, src/main/kotlin/org/rust/ide/typing/assist/SemicolonFixer.kt, src/test/kotlin/org/rust/ide/typing/assist/RsSmartEnterProcessorTest.kt
Fixes #9736
Now smart enter will add a semicolon for type aliases, trait aliases, extern crates and constants
changelog: Support smart enter for type aliases
=> Support smart enter for more items

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
@mchernyavsky Is this the correct way forward to display multiple spans per linter message?
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7508
=> INSP: add support for multiple spans in external linter check inspection

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsErrorAnnotatorTest.kt
This PR is about four builtin macros: `inline`, `repr`, `start` and `derive`. 
* `inline`, `repr` and `start` can't be overwritten by user macro (there will be ambigiuos error E0659). So I think we can still annotate them even if there is user attr proc macro in scope
* `derive` can be user attr proc macro. Note that there is `derive` macro 2.0 in stdlib, that's why `DeriveAttrUnsupportedItem` currently doesn't work. This should be fixed in separate PR like #5911
changelog: Fixes [`E0518`](https://doc.rust-lang.org/error-index.html#E0518) error detection when there is cfg-disabled import of `inline` proc macro
=> ANN: Check builtin attributes even when there is proc macro in scope

src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsMetaItem.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt
This PR is based on #10146.
changelog:
- Check that the proper delimiter is applied when specifying an attribute
e.g. the following code is incorrect (`{}` used instead of `()`):
```rust
#[allow { foo_lint }]
fn delim_brace() {}
```
Compiler reference: https://github.com/rust-lang/rust/blob/c9ae38c71e2838f1ac282803ddde47f21f4ca76e/compiler/rustc_parse/src/validate_attr.rs#L87
- Check that attribute format is conforming with the respective template. 
e.g. `recursion_limit` attribute has the following template: 
```{"word":false,"list":null,"nameValueStr":"N"}```
which means the only way to specify this attribute is by providing an integer as a parameter, thus making the following code produce an error:
```rust
#![recursion_limit]
```
More on attribute templates: …
=> ANN: Add attribute errors support

src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/Processors.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt
Fixes #7062
changelog: Fix completion of derive proc macro with `doc(hidden)` attribute in imports
=> RES: Fix completion of derive proc macro in imports

src/main/resources/inspectionDescriptions/RsApproxConstant.html, src/main/resources/inspectionDescriptions/RsCStringPointer.html, src/main/resources/inspectionDescriptions/RsDanglingElse.html, src/main/resources/inspectionDescriptions/RsDoubleNeg.html, src/main/resources/inspectionDescriptions/RsDropRef.html, src/main/resources/inspectionDescriptions/RsMissingElse.html, src/main/resources/inspectionDescriptions/RsNeedlessLifetimes.html, src/main/resources/inspectionDescriptions/RsRedundantElse.html, src/main/resources/inspectionDescriptions/RsSelfConvention.html, src/main/resources/inspectionDescriptions/RsSuspiciousAssignment.html, src/main/resources/intentionDescriptions/AddStructFieldsLiteralIntention/description.html, src/main/resources/intentionDescriptions/AddStructFieldsLiteralRecursiveIntention/description.html, src/main/resources/intentionDescriptions/AddStructFieldsPatIntention/description.html, src/main/resources/intentionDescriptions/AddWildcardArmIntention/description.html, src/main/resources/intentionDescriptions/MoveTypeConstraintToParameterListIntention/description.html, src/main/resources/intentionDescriptions/MoveTypeConstraintToWhereClauseIntention/description.html, src/main/resources/intentionDescriptions/NestUseStatementsIntention/description.html, src/main/resources/intentionDescriptions/RemoveCurlyBracesIntention/description.html, src/main/resources/intentionDescriptions/ShareInPlaygroundIntention/description.html, src/main/resources/intentionDescriptions/SplitIfIntention/description.html, src/main/resources/intentionDescriptions/ToggleFeatureIntention/description.html, src/main/resources/intentionDescriptions/UnwrapToMatchIntention/description.html, src/main/resources/intentionDescriptions/UnwrapToTryIntention/description.html
* Fix links to Clippy list of lints.
* Fix formatting of some code elements in the intention descriptions.
* Fix hyperlink to Playground in intention description.
Closes #9370
changelog: Fix formatting and links in descriptions of some intentions and inspections
=> Fix inspection & intention descriptions

src/main/kotlin/org/rust/ide/annotator/RsUnsafeExpressionAnnotator.kt, src/test/kotlin/org/rust/ide/annotator/RsUnsafeExpressionErrorAnnotatorTest.kt
changelog: Fix showing error when assigning value to union field outside unsafe block.
=> ANN: Fix showing error when assigning value to union field

src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/cargo/RsWithToolchainTestBase.kt, src/test/kotlin/org/rust/ide/formatter/RsFormatterTestBase.kt, src/test/kotlin/org/rust/lang/core/lexer/LexerTestCaseBase.kt, src/test/kotlin/org/rust/lang/core/parser/RsParsingTestCaseBase.kt
Since #10277 we run *some* tests (descendants of `RsIntentionTestBase` class) using JUnit4, but we still run most of the tests using JUnit3. I'd want to put all tests in line in order to avoid possible differences in the framework behavior and also to benefit from JUnit4 features like the `@Ignore` annotation.
JUnit4 basically implies using `@Test` annotations to mark a test function, but I managed to avoid it by using a custom test runner (I don't want to bring `> 10000` changes in `> 600` files right now).
If everything goes well, this PR won't affect anything (since you can write and run tests as usual).
changelog: migrate tests to JUnit4
=> T: run tests with JUnit4

src/main/kotlin/org/rust/ide/fixes/ChangeReprAttributeFix.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/typecheck/ChangeReprAttributeFixTest.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/7894.
changelog: Add a quick fix for [type mismatch E0308](https://doc.rust-lang.org/error-index.html#E0308) error that adds a `#[repr(...)]` attribute to a enum:
```rust
enum Foo {
FooVariant = 1u16 // Error: expected `isize`, found `u16`
}
```
=>
```rust
#[repr(u16)]
enum Foo {
FooVariant = 1u16
}
```
=> INSP: Add `#[repr(...)]` quick fix for E0308 error

src/main/kotlin/org/rust/ide/annotator/RsSyntaxErrorsAnnotator.kt, src/main/kotlin/org/rust/ide/docs/RsDocumentationProvider.kt, src/main/kotlin/org/rust/ide/presentation/RsPsiRenderer.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/core/stubs/StubImplementations.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsFunctionSignatureSyntaxTest.kt
changelog:
- support for [E0045](https://doc.rust-lang.org/error_codes/E0045.html)
- fix: don't show error `function cannot be variadic` when use default ABI
=> ANN: Add support for E0045 | Fix checking use of variadic

src/main/kotlin/org/rust/cargo/project/configurable/RsExternalLinterConfigurable.kt, src/main/kotlin/org/rust/cargo/project/settings/RsExternalLinterProjectSettingsService.kt, src/main/kotlin/org/rust/cargo/toolchain/CommandLine.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/statistics/RsSettingsUsagesCollector.kt, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/cargo/project/RsExternalLinterProjectSettingsServiceTest.kt
Depends on https://github.com/intellij-rust/intellij-rust/pull/8908.
Closes https://github.com/intellij-rust/intellij-rust/issues/8884.
Closes https://github.com/intellij-rust/intellij-rust/issues/8503.
Closes https://github.com/intellij-rust/intellij-rust/pull/10122.
changelog: Allow to configure the channel and environment variables for external linters
=> RUN: Allow to configure the channel and environment variables for external linters

src/main/kotlin/org/rust/lang/core/types/infer/TypeInferenceWalker.kt, src/test/kotlin/org/rust/lang/core/completion/RsAwaitCompletionTest.kt
Fixes #10407
The bug was triggered by #9315
changelog: Can be omitted since the bug was triggered in the same release
=> COMP: fix `.await` completion for async fn returned type

src/main/grammars/RustParser.bnf, src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserDefinition.kt, src/main/kotlin/org/rust/lang/core/parser/RustParserUtil.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt
Fixes expansion of `foo!()` in such caese:
```rust
($ i:meta) => (
#[$ i]
fn bar() {}
)
}
foo! { doc = concat!("foo", "bar") }
```
Also now the plugin can expand `foo` in a meta item value context:
```rust
() => {"bar"}
}
#[doc = foo!()]
//^
fn foo() {}
```
Also fixes name resolution in `axum` crate
```toml
[dependencies]
axum = "0.6.17"
```
```rust
use axum::routing::{post};
//^ can be resolved now
```
=> GRAM&MACRO: Parse and expand macros in attributes: `#[doc = foo!()]`

src/main/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsAttrErrorAnnotatorTest.kt
changelog:
* Add support for E0538, multiple items used in `#[deprecated]` attribute, e.g.:
```rust
#[deprecated(
since = "a",
since = "b", // error
note = "c"
)]
fn f1() { }
```
Error code reference: https://doc.rust-lang.org/error_codes/E0538.html
Compiler reference: https://github.com/rust-lang/rust/blob/904dd2c3987028f0270db306b9964bc465689de8/compiler/rustc_attr/src/builtin.rs#L834
* Add support for E0541, unknown item used inside `#[deprecated]`:
```rust
#[deprecated(
since="1.0.0",
// error: unknown meta item
reason="Example invalid meta item. Should be 'note'")
]
fn deprecated_function() {}
```
Error code reference: https://doc.rust-lang.org/error_codes/E0541.html
Compiler reference: https://github.com/rust-lang/rust/blob/904dd2c3987028f0270db306b9964bc465689de8/compiler/rustc_attr …
=> ANN: check `#[deprecated]` attr syntax: E0538, E0551, E0541

src/main/kotlin/org/rust/ide/annotator/RsExternalLinterUtils.kt, src/test/kotlin/org/rust/ide/annotator/fixes/ApplySuggestionFixTest.kt, src/test/kotlin/org/rustSlowTests/RsExternalLinterPassTest.kt
Reverts #7509,
Fixes #10429
Fixes #10401
=> Revert "INSP: Add support for multiple spans in external linter check inspection"

README.md
We don't use gitter for a long time
=> Drop gitter links in readme

src/main/kotlin/org/rust/ide/experiments/RsExperiments.kt, src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt, src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt, src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt, src/main/kotlin/org/rust/lang/core/types/Extensions.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerUninitializedTest.kt
Implement error E0381 using MIR-dataflow. Works only if `org.rust.mir.borrow-check` experimental feature is enabled. See #10452
=> MIR: Annotate E0381

src/main/kotlin/org/rust/ide/inspections/RsBorrowCheckerInspection.kt, src/main/kotlin/org/rust/lang/core/mir/borrowck/FacadeBorrowck.kt, src/main/kotlin/org/rust/lang/core/mir/borrowck/MirBorrowCheckVisitor.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
Implement error E0382 using MIR-dataflow. Works only if `org.rust.mir.borrow-check` experimental feature is enabled. See #10452
=> MIR: Annotate E0382

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributorTest.kt
changelog: Add completion for keyword `let` after `if` and `while`
=> COMP: complete `let` after `if` and `while`

src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsKeywordCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsImplForCompletionTest.kt
changelog: Add completion for keyword `for` after `impl` block
=> COMP: Complete `for` after `impl` block

build.gradle.kts, gradle-231.properties, gradle-232.properties
It makes `gradle-*.properties` files contain all necessary information about dependency plugins, and allows us to automatically update them
=> GRD: move plugin ids from `build.gradle.kts` to `gradle-*.properties`

src/main/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsUnnecessaryCastInspectionTest.kt
changelog: Support `Unnecessary cast` inspection for function types
=> INSP: Support `Unnecessary cast` inspection for function types

src/main/kotlin/org/rust/ide/hints/parameter/RsAsyncParameterInfoHandler.kt, src/main/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandler.kt, src/main/kotlin/org/rust/ide/hints/parameter/RsStructLiteralParameterInfoHandler.kt, src/main/kotlin/org/rust/ide/typing/RsTypedHandler.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/hints/parameter/RsParameterInfoHandlerTestBase.kt, src/test/kotlin/org/rust/ide/hints/parameter/RsStructLiteralParameterInfoHandlerTest.kt
Note that hint should be shown automatically after typing `{`
=> Make parameter info available inside struct literal

build.gradle.kts, src/test/kotlin/org/rust/RsJUnit4TestRunner.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt
1. Sort tests by project descriptor
Switching between project descriptors is expensive, so let's group tests by project descriptor
2. Pass `macroExpansionCachingKey` through `WithProcMacros`
3. Use proper ForkJoinPool threadFactory in tests
The factory should be set up automatically in `IdeaForkJoinWorkerThreadFactory.setupForkJoinCommonPool`,
but when tests are launched by Gradle this may not happen because Gradle can use the pool earlier.
Setting this factory is critical for `ReadMostlyRWLock` performance, so ensure it is properly set
=> T&PERF: slightly speed up tests

src/main/kotlin/org/rust/ide/refactoring/suggested/RsSuggestedRefactoringStateChanges.kt, src/test/kotlin/org/rust/ide/refactoring/suggested/RsChangeSignatureSuggestedRefactoringTest.kt
Previously, `change signature` refactoring was not suggested in this case:
```rust
trait Trait {
fn foo(self: &Self/*caret*/); // Type `, a: i32`
}
struct S;
impl Trait for S {
fn foo(self: &Self) {}
}
```
changelog: Suggest `change signature` refactoring when editing a signature of a method with explicit `self` type
=> Fix `self` parameter type handling in suggested refactoring

src/main/kotlin/org/rust/cargo/project/model/impl/TestCargoProjectsServiceImpl.kt, src/main/kotlin/org/rust/lang/core/macros/MacroExpansionManager.kt, src/test/kotlin/org/rust/ProjectDescriptor.kt, src/test/kotlin/org/rust/RsTestBase.kt, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/lang/core/completion/RsPathCompletionTest.kt, src/test/kotlin/org/rust/lang/core/macros/MacroExpansionFileSystemTest.kt, src/test/kotlin/org/rust/lang/core/resolve2/RsMultipleDefMapsUpdateTest.kt, src/test/kotlin/org/rustPerformanceTests/RsParsingPerfTest.kt, src/test/kotlin/org/rustSlowTests/RsCompilerSourcesLazyBlockStubCreationTest.kt, src/test/kotlin/org/rustSlowTests/RsCompilerSourcesPerfTest.kt
Use one `LightProjectDescriptor` in almost all tests. The test framework caches `com.intellij.openapi.project.Project`
instance between tests if these tests have the same `LightProjectDescriptor` instance. If not, the framework initializes a new `Project`. Previously we used different `LightProjectDescriptor` instances in order to make different `CargoWorkspace`
setups (For example, with, or without stdlib). But we could change this setup without creating a new `Project`. So I've introduced `RustLightProjectDescriptor` which is now used in almost all tests. The Cargo workspace setup is done by `RustProjectDescriptorBase` as before (but now `RustProjectDescriptorBase` does not extend `LightProjectDescriptor` and works in parallel with it)
=> T&PERF: use single `LightProjectDescriptor` in most tests

src/main/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryCastInspection.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspection.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryCastInspectionTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspectionTest.kt
Also, move the corresponding classes into `inspections.lints` package
changelog: Move `Unused mut modifier` and `Unnecessary cast` inspections to `Rust/Lint` group in inspection settings
=> INSP: move `Unused mut modifier` and `Unnecessary cast` inspections to `Rust/Lint` group

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspection.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsUnusedMutInspectionTest.kt
changelog: Take into account lint level by `Unused mut` inspection during highlighting
=> INSP: respect lint level by `Unused mut` inspection

src/main/resources/META-INF/rust-core.xml
Important for faster loading of IDE/project settings dialogs; in 232, there is an assertion for missing names.
=> Specifying a display name for project configurables in .xml

src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/lang/core/macros/errors/GetMacroExpansionError.kt, src/main/kotlin/org/rust/lang/core/macros/errors/MacroExpansionError.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProMacroExpanderVersion.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroApplicationService.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/proc/ProcMacroServerPool.kt, src/main/kotlin/org/rust/lang/core/macros/proc/Request.kt, src/main/kotlin/org/rust/lang/core/macros/proc/Response.kt, src/main/kotlin/org/rust/stdext/SynchronizedCancellableLazy.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroExpanderTest.kt
From the user perspective the PR is about the error message in the case when proc macro expander from user's toolchain has too recent version.
Before:
After:
Part of #10566
changelog: Implement proc macro expander version check
=> MACRO: Implement proc macro expander version check

src/main/kotlin/org/rust/ide/inspections/RsCompileErrorMacroInspection.kt, src/main/kotlin/org/rust/ide/inspections/RsLocalInspectionTool.kt, src/main/kotlin/org/rust/ide/inspections/RsWithMacrosInspectionVisitor.kt, src/main/kotlin/org/rust/lang/core/macros/MacroHighlightingUtil.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsCompileErrorMacro.html, src/test/kotlin/org/rust/RustProjectDescriptors.kt, src/test/kotlin/org/rust/ide/inspections/RsCompileErrorMacroInspectionTest.kt, testData/test-proc-macros/src/lib.rs
This is mostly useful for procedural macros that use `compile_error!()` to show custom errors
changelog: Highlight `compile_error!()` usage as an error
=> Highlight `compile_error!()` usage as an error

src/main/kotlin/org/rust/ide/fixes/ReplaceCastWithLiteralSuffixFix.kt, src/main/kotlin/org/rust/ide/inspections/lints/RsReplaceCastWithSuffixInspection.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/inspectionDescriptions/RsReplaceCastWithSuffix.html, src/test/kotlin/org/rust/ide/inspections/fixes/ReplaceCastWithSuffixTest.kt, src/test/kotlin/org/rust/ide/inspections/lints/RsReplaceCastWithSuffixInspectionTest.kt
changelog: Implement `as` cast can be replaced with literal suffix inspection
=> INSP: Implement `as` cast can be replaced with literal suffix inspection

src/main/kotlin/org/rust/ide/annotator/AnnotatorBase.kt, src/main/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotator.kt, src/main/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPass.kt, src/test/kotlin/org/rust/ide/annotator/RsCfgDisabledCodeAnnotatorTest.kt
Fixes #9712
changelog: Don't mishighlight cfg-disabled code in macro calls
=> MACRO&ANN: Don't mishighlight cfg-disabled code in macro calls

src/main/resources-nightly/META-INF/experiments.xml, src/main/resources-stable/META-INF/experiments.xml, src/test/kotlin/org/rust/ide/annotator/RsHighlightingAnnotatorTest.kt, src/test/kotlin/org/rust/ide/annotator/RsMacroExpansionHighlightingPassTest.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTest.kt, src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionSortingTest.kt, src/test/kotlin/org/rust/lang/core/macros/proc/RsProcMacroErrorTest.kt, src/test/kotlin/org/rust/lang/core/psi/ProcMacroAttributeTest.kt
It looks like most of the issues with attribute macros are fixed now, so we can enable their expansion by default.
Part of #6908
Fixes #5104
Fixes #5239
Fixes #5748
Fixes #5896
Fixes #6006
Fixes #6091
Fixes #6093
Fixes #6482
Fixes #6938
Fixes #7610
Fixes #7863
Fixes #8350
Fixes #8407
Fixes #8640
Fixes #9128
Fixes #9384
Fixes #9534
Fixes #9918
Fixes #9973
changelog: Enable [attribute](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros) procedural macro expansion by default.
=> Enable attribute procedural macro expansion by default

gradle.properties
- increase heap for Gradle daemon
- don't use kotlin classpath snapshot
=> GRD: try to avoid OOM during building

src/main/kotlin/org/rust/cargo/runconfig/buildtool/CargoBuildTaskRunner.kt
Fixes https://github.com/intellij-rust/intellij-rust/issues/10346.
changelog: Don't run `cargo clean` on `Build` action
=> RUN: Don't run `cargo clean` on `Build` action

src/main/kotlin/org/rust/cargo/runconfig/CargoTestRunState.kt
changelog: Add notification about disabling the Test tool window with `Revert` button
=> RUN: Add notification about disabling the Test tool window with `Revert` button

src/main/kotlin/org/rust/ide/template/postfix/RsPostfixTemplateProvider.kt, src/main/kotlin/org/rust/ide/template/postfix/stringBasedPostfixTemplates.kt, src/main/kotlin/org/rust/lang/core/resolve/ImplLookup.kt, src/main/resources/postfixTemplates/SlicePostfixTemplate/after.rs.template, src/main/resources/postfixTemplates/SlicePostfixTemplate/before.rs.template, src/main/resources/postfixTemplates/SlicePostfixTemplate/description.html, src/test/kotlin/org/rust/ide/template/postfix/SlicePostfixTemplateTest.kt
changelog: Provide postfix completion items `.sublist` and `.slice` on indexable expressions that will complete into `[]`
=> COMP: Provide postfix completion items `.sublist` and `.slice` on indexable expressions that will complete into `[]`

src/main/kotlin/org/rust/ide/template/RsContextType.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/org/rust/ide/liveTemplates/iterations.xml, src/main/resources/org/rust/ide/liveTemplates/other.xml, src/main/resources/org/rust/ide/liveTemplates/output.xml, src/main/resources/org/rust/ide/liveTemplates/test.xml, src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
Currently we have `RsContextType.Statement` which accepts wide range of contexts, e.g. those locations:
```
let x = /*caret*/
func(/*caret*/);
break '/*caret*/
```
Thus live templates such as `assert!();` are incorrectly suggested in those locations. This PR changes `RsContextType.Statement` to accept only top-level statements inside RsBlock, and introduces `RsContextType.Expression` which equals to current `RsContextType.Statement`.
=> Fix live templates suggestion in loop labels and other positions

src/main/kotlin/org/rust/lang/core/completion/RsBuildScriptCargoInstructionCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/test/kotlin/org/rust/lang/core/completion/RsBuildScriptCargoInstructionCompletionTest.kt
changelog: Complete Cargo [instructions](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) in build scripts
=> COMP: complete Cargo instructions in build scripts

src/main/kotlin/org/rust/ide/fixes/AddUnsafeFix.kt, src/main/kotlin/org/rust/ide/injected/RsDoctestLanguageInjector.kt, src/test/kotlin/org/rust/ide/annotator/fixes/AddUnsafeFixTest.kt
changelog:
- The `add unsafe to function` quickfix is no longer raised when an unsafe call is made inside a test function, doctest main function, or in a implemented function where the parent trait function is not marked as unsafe. Suggests `Surround with unsafe block` instead.
- Fixes #10312
- Fixes #10183
=> (INT): Fix `Add unsafe to function` quickfix false positives

src/main/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspection.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/inspections/RsUnresolvedReferenceInspectionTest.kt
After enabling attribute macro expansion I think it's time to enable `Unresolved Reference` inspection in the case of a type-independent path.
What should be highlighted:
1. Unresolved reference in a `use`:
```rust
use foo:bar;
```
2. Unresolved 1-segment path:
```rust
fn main() {
let b = a + 1;
}
```
3. Unresolved multi-segment path if the penultimate segment is a module:
```rust
mod foo {}
fn main () {
let a = foo::bar;
}
```
4. Unresolved multi-segment path if the penultimate segment is a enum and the last segment starts with an uppercase letter:
```rust
enum Foo { A, B }
fn main() {
let a = Foo::C;
}
```
What should NOT be highlighted:
1. A non-path, e.g. a method call:
```rust
struct S;
fn foo() {
S.unresolved(); // NOT highlighted
}
```
2. A multi-segment path if the penultimate …
=> Show `Unresolved Reference` error for type-independent paths

src/main/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsElement.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/inspections/lints/RsBareTraitObjectsInspectionTest.kt
Trait objects without the `dyn` keyword became an error ([E0782](https://doc.rust-lang.org/error_codes/E0782.html)) in the 2021 Rust edition, however the inspection for it only raised a warning that it was deprecated.
changelog:
- The "trait objects without dyn keyword" inspection raises an error in the 2021 edition, and a warning on 2018.
=> (ANN): Change bare trait object lint to error E0782

src/main/kotlin/org/rust/lang/core/types/regions/Scope.kt, src/test/kotlin/org/rust/ide/inspections/borrowck/RsBorrowCheckerMovesTest.kt
changelog: Fix false-positive `Use of moved value` for lambda expressions in `for` loops
=> INSP: Fix false-positive `Use of moved value` for lambda expressions in `for` loops

src/main/resources/org/rust/ide/liveTemplates/iterations.xml, src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
changelog: Add `iter` alias for `for` live template
=> COMP: Add `iter` alias for `for` live template

src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/test/kotlin/org/rust/ide/annotator/RsDuplicateDefinitionAnnotatorTest.kt
changelog: Use [E0403](https://doc.rust-lang.org/error_codes/E0403.html) instead of deprecated [E0263](https://doc.rust-lang.org/error_codes/E0263.html)
=> ANN: Use E0403 instead of deprecated E0263

toml/src/main/kotlin/org/rust/toml/inspections/TomlDuplicatedKeyInspection.kt, toml/src/main/resources/inspectionDescriptions/TomlDuplicatedKey.html, toml/src/main/resources/messages/RsTomlBundle.properties, toml/src/main/resources/org.rust.toml.xml, toml/src/test/kotlin/org/rust/toml/inspections/TomlDuplicatedKeyInspectionTest.kt
changelog: Highlight duplicated keys from the same table in TOML files.
=> INSP: Add a TOML inspection for duplicated keys (in simple cases)

debugger/src/231/main/kotlin/org/rust/debugger/RsDebuggerUrlProvider.kt, debugger/src/232/main/kotlin/org/rust/debugger/RsDebuggerUrlProvider.kt, debugger/src/main/kotlin/org/rust/debugger/DebuggerAvailability.kt, debugger/src/main/kotlin/org/rust/debugger/RsDebuggerToolchainService.kt, debugger/src/main/kotlin/org/rust/debugger/RsDefaultDebuggerDriverConfigurationProvider.kt, debugger/src/main/kotlin/org/rust/debugger/runconfig/RsDebugRunnerUtils.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerSettings.kt, debugger/src/main/kotlin/org/rust/debugger/settings/RsDebuggerToolchainConfigurableUi.kt, debugger/src/test/kotlin/org/rust/debugger/RsDebuggerToolchainServiceTest.kt
- the feature is still under `org.rust.debugger.gdb.setup.v2` registry option
- works only since 232.8296
- works only on Linux local debugging. Windows doesn't work because of `winbreak` binaries are expected to be present in Native Debugging plugin but it doesn't contain them. I think it will be fixed on Native Debugging plugin side and won't require any changes from the Rust plugin
- WSL debugging is not supported
changelog: Implement initial support for gdb debugging outside of CLion. Right now it's disabled by default and works only on Linux
=> GDB: Initial support for gdb debugging outside CLion

src/main/kotlin/org/rust/lang/core/macros/MacroExpansion.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroErrorTest.kt
changelog: Improve error message for a non-expanded macro inside an impl block
=> MACRO: fix error message for non-expanded macro inside an impl

src/main/kotlin/org/rust/lang/core/macros/RsExpandedElement.kt, src/test/kotlin/org/rust/lang/core/resolve/RsResolveTest.kt
Example:
```rust
fn main() {
{
let mut a = 1;
//X
#[cfg(intellij_rust)]
{
use foo::bar;
a += 1;
} //^
a
};
}
```
changelog: Fix name resolution inside a nested block under cfg attribute
=> RES: Fix name resolution inside a nested block under cfg attribute

src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/main/kotlin/org/rust/ide/annotator/RsErrorAnnotator.kt, src/main/kotlin/org/rust/ide/fixes/AddTokioMainFix.kt, src/main/kotlin/org/rust/ide/inspections/RsAsyncMainFunctionInspection.kt, src/main/kotlin/org/rust/lang/core/psi/ext/RsFunction.kt, src/main/kotlin/org/rust/lang/utils/RsDiagnostic.kt, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/annotator/fixes/AddTokioMainFixTest.kt
When `async` main function is found, this will suggest to use `#[tokio::main]`.
If `tokio` is not a dependency of the project, it will be added via `cargo add`
This will also suggest to use `#[tokio::main]` if `await` is used inside a non-async main.
changelog: Add quick-fix to install tokio and add #[tokio::main]
=> INT: Adding a quick fix to add #[tokio::main]

src/main/resources/org/rust/ide/liveTemplates/other.xml, src/test/kotlin/org/rust/ide/template/RsLiveTemplatesTest.kt
changelog: Complete `macro` live template only in item context
=> Fix scope for `macro` template

src/main/kotlin/org/rust/lang/core/macros/decl/DeclMacroExpander.kt, src/main/kotlin/org/rust/lang/core/macros/decl/FragmentKind.kt, src/main/kotlin/org/rust/lang/core/parser/util.kt, src/test/kotlin/org/rust/lang/core/macros/decl/RsMacroExpansionTest.kt, src/test/kotlin/org/rust/lang/core/resolve/RsStdlibResolveTest.kt
This also fixes `i32` methods name resolution and completion.
changelog: match negative numeric literals with `$l:literal` macro fragment spec
=> MACRO: match negative literals with `$l:literal` macro fragment spec

src/test/kotlin/org/rust/ide/annotator/AnnotationTestFixtureBase.kt, src/test/kotlin/org/rust/ide/inspections/import/AutoImportFixTestBase.kt, src/test/kotlin/org/rust/ide/intentions/AddImportForPatternIntentionTest.kt, src/test/kotlin/org/rust/ide/intentions/RsIntentionTestBase.kt, src/test/kotlin/org/rust/ide/intentions/ToggleFeatureIntentionTest.kt, src/test/kotlin/org/rust/ide/previewUtils.kt
Previously we checked intention/quick fix preview *before* checking
a normal intention behavior (without preview) which was very unhandy
in a TDD workflow. As a developer, first I want to make intention work,
and only after that I should care about preview.
Now we check intention/quick invocation first, and only after its
success we check the preview.
=> T: Check intention/quick fix preview after checking intention invocation

src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt
Starting from `1.72.0-beta.1` there is a nightly Cargo feature usage in the stdlib:
`cargo-features = ["public-dependency"]`
So we need to pass `RUSTC_BOOTSTRAP=1` during loading the stdlib workspace.
changelog: Fix stdlib deps fetching on 1.72.0-beta
=> Fix stdlib deps fetching on 1.72.0-beta

build.gradle.kts, gradle-232.properties, gradle.properties
And make 2023.2 the default platform for development
changelog: Make 2023.2 the default platform for development
=> Update 2023.2 IDE and plugin dependencies 

src/main/kotlin/org/rust/cargo/project/toolwindow/CargoToolWindow.kt
changelog: Fix Cargo tool window initialization on 2023.3
=> Fix Cargo tool window initialization on 2023.3

src/main/kotlin/org/rust/ide/inspections/RsLiteralOutOfRangeInspection.kt, src/test/kotlin/org/rust/ide/inspections/RsLiteralOutOfRangeInspectionTest.kt
Fixes bug introduced with #10709
On one side negated values are now taken into account. Using a simple strategy of checking for unary minus, similarly to what the compiler does.
On the other side, we're not checking i32 because of type inference issues.
changelog: Fixes bug introduced with #10709 causing negative values to be marked as overflown
=> Fixed bug causing false positives during checking literal value overflow

attributes-info/Cargo.lock
see https://github.com/rust-lang/rust/issues/113152
Fixing update-compiler-feature action, it failed with this error:
Checked that now it is working  https://github.com/neonaot/intellij-rust/pull/90
=> CI: update dependencies versions

src/main/kotlin/org/rust/lang/core/completion/LookupElements.kt, src/main/kotlin/org/rust/lang/core/completion/RsCompletionContributor.kt, src/main/kotlin/org/rust/lang/core/completion/RsSelfParameterCompletionProvider.kt, src/test/kotlin/org/rust/lang/core/completion/RsCompletionTest.kt, src/test/kotlin/org/rust/lang/core/completion/RsSelfParameterCompletionProviderTest.kt
changelog: Fix Completion window shows `self::`, but writes `self`
=> Fix Completion window shows `self::`, but writes `self`

src/main/kotlin/org/rust/ide/inspections/lints/RsUnusedMustUseInspection.kt
We don't expand `tokio::main` async function, so return type of such function was considered as `impl Future`, though actually `tokio::main` expands to function returning unit
=> Fix inspection "Unused must_use" for `tokio::main` proc macro

src/main/kotlin/org/rust/ide/fixes/AddTokioMainFix.kt, src/main/kotlin/org/rust/toml/CrateExt.kt, src/main/kotlin/org/rust/toml/Util.kt, src/main/kotlin/org/rust/toml/completion/CargoTomlFeatureDependencyCompletionProvider.kt, src/main/kotlin/org/rust/toml/completion/RsCfgFeatureCompletionProvider.kt, src/main/kotlin/org/rust/toml/resolve/CargoTomlNameResolution.kt, src/main/kotlin/org/rust/toml/resolve/RsCfgFeatureReferenceProvider.kt, src/main/resources/messages/RsBundle.properties, src/test/kotlin/org/rust/ide/annotator/fixes/AddTokioMainFixTest.kt
This changes the way we are installing tokio dependency. Instead of using `cargo add` we're editing Cargo.toml directly. This allows us to have more control over the features. New helper function to add cargo dependency is added as well.
changelog: Fixes undo not available after adding tokio dependency when using Add `#[tokio::main]` quickfix.
=> Fixes add #[tokio::main] quick fix.

src/main/kotlin/org/rust/cargo/toolchain/impl/CargoMetadata.kt, src/main/kotlin/org/rust/lang/core/psi/RsFileViewProviderFactory.kt, src/main/kotlin/org/rust/lang/core/resolve/indexes/RsAliasIndex.kt, src/main/resources/META-INF/rust-core.xml
I finally figured out how to increase the file limit for Rust files. Now the limit for Rust files is 8MB. Previous attempt was #8699.
Fixes #10624
changelog: Adjust intellisense file size limit for Rust files
=> Adjust intellisense file size limit for Rust files

src/main/kotlin/org/rust/ide/intentions/MatchToIfLetIntention.kt, src/test/kotlin/org/rust/ide/intentions/MatchToIfLetIntentionTest.kt
This PR is another attempt of implementing https://github.com/intellij-rust/intellij-rust/pull/7435.
I learned that `if` expressions must have an `else` block if their type is anything other than `()`. So now the code always generates an `else` branch if it wasn't already generated by other means for match expressions that don't have unit type.
Fixes: https://github.com/intellij-rust/intellij-rust/issues/7409
changelog: The intention to convert a match expression to a series of if let statements is now offered in more situations.
=> INT: generalize MatchToIfLetIntention to arbitrary arm count, take two

src/232/test/kotlin/org/rust/ide/hints/codeVision/RsImplementationsCodeVisionTest.kt, src/main/kotlin/org/rust/ide/hints/codeVision/RsImplementationsCodeVisionProvider.kt, src/main/resources/META-INF/rust-core.xml, src/main/resources/messages/RsBundle.properties
The `handleClick` implementation is copied from `ImplsNavigationGutterIconRenderer::navigateToItems`. It should probably be placed into some unified location, but I'm not sure where does it belong.
Relevant issue: https://github.com/intellij-rust/intellij-rust/issues/9427
changelog: Add support for showing implementations (inheritors) Code Vision. Note, these hints are available starting with 2022.3 and are currently disabled by default. You can turn it on via `Registry... | org.rust.code.vision.implementation`.
=> IDE: add implementations Code Vision hint

src/main/kotlin/org/rust/cargo/CargoConfig.kt, src/main/kotlin/org/rust/cargo/project/model/CargoProjectService.kt, src/main/kotlin/org/rust/cargo/project/model/impl/CargoSyncTask.kt, src/main/kotlin/org/rust/cargo/project/workspace/StandardLibrary.kt, src/main/kotlin/org/rust/cargo/toolchain/tools/Cargo.kt, src/test/kotlin/org/rust/cargo/project/model/CargoPackagesTest.kt, src/test/kotlin/org/rust/cargo/toolchain/CargoConfigTest.kt
changelog: support multiple build.target values in .cargo/config.toml
This is a fix for #10125, where the `cargo metadata` execution fails when multiple build targets are specified in `.cargo/config.toml`. Multiple build targets in config.toml were stabilized in Rust 1.64.0, as part of rust-lang/cargo#8176.
As described in [my comment on the issue](https://github.com/intellij-rust/intellij-rust/issues/10125#issuecomment-1630091562), I have changed `buildTarget: String?` into `buildTargets: List<String>` in the `CargoConfig`, as returned by `Cargo.getConfig()`, and used in various places which calls that function. Instead of being `null`, `buildTargets` is an empty list if build.target is not specified, which is still correctly handled (defaulted to the host triple) by the calling code.
As …
=> #10125: Support multiple build targets in .cargo/config.toml

src/main/kotlin/org/rust/ide/inspections/lints/RsLint.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/ide/inspections/lints/RsUnnecessaryQualificationsInspectionTest.kt
changelog: remove `unused_qualifications` lint from `unused` group, change level to `WEAK WARNING`
=> INSP: remove `unused_qualifications` lint from `unused` group, change level to `WEAK WARNING` 

src/232/test/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionTest.kt, src/main/kotlin/org/rust/ide/hints/codeVision/RsReferenceCodeVisionProvider.kt, src/main/kotlin/org/rust/lang/core/completion/RsCommonCompletionProvider.kt, src/main/kotlin/org/rust/lang/core/resolve/NameResolution.kt, src/main/kotlin/org/rust/lang/core/resolve/PathResolutionContext.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPatBindingReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsPathReferenceImpl.kt, src/main/kotlin/org/rust/lang/core/resolve/ref/RsStructExprFieldReferenceImpl.kt, src/main/resources/META-INF/rust-core.xml, src/test/kotlin/org/rust/lang/core/resolve/RsMultiResolveTest.kt
The provider was initially added in #9927.
Here I enable usages Code Vision for Rust items except:
- an associated item (an impl/trait member)
- a struct field
- a macro declaration
- an enum variant
Usage code vision can be enabled for these elements using `org.rust.code.vision.usage.slow` registry option.
For other items Reference Search does not use type inference and hence it should work fast.
I additionally adjusted `RsReferenceImpl.isReferenceTo()` to ensure it does not touch type inference in such cases.
changelog:  Enable Usages Code Vision hints for some top-level items
=> Enable `RsReferenceCodeVisionProvider` for top-level items

src/main/kotlin/org/rust/ide/annotator/format/impl.kt, src/main/kotlin/org/rust/ide/fixes/ImplementDisplayFix.kt, src/test/kotlin/org/rust/ide/annotator/RsFormatMacroAnnotatorTest.kt
changelog: Fix bugs related to quick fixes of printing of structs with neither display nor debug trait implemented
=> Fix bug for printing of structs w/o display & debug traits quick fixes
